### ISSUE TITLE
Code completion should not ignore default parameters in functions

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#100]
1. Function declaration.
```c++
void testDefault(int a = 5);
````

2. Currently, clangd ignores the default parameters of the function.
![image](https://user-images.githubusercontent.com/10697249/61433826-e4174780-a966-11e9-85b0-9347323fbf83.png)

3. Expected behavior
Clangd shows the complete function signature.
like `testDefault(int a = 5)`

**Comment by usx95** [comment]
Fixed in rL368186.
