### ISSUE TITLE
/tmp gets full of preamble pch files

### ISSUE THREAD

**Issue by Yanpas** [clangd/clangd#1007]
Clangd generate precompiled headers inside /tmp directory and soon start crashing because /tmp gets full.

Files look like "/tmp/preamble-ddb8f3.pch"
**System information**

Output of `clangd --version`: 13.0.0

Editor/LSP plugin: vscode 0.0.15

Operating system: rhel 7

**Comment by HighCommander4** [comment]
You can work around this by running vscode with `TMPDIR` set to a directory on a different partition (with more space) in the environment.

**Comment by flashk1021** [comment]
I have the same issue using clangd. How to change the TMPDIR in vscode? Thx.

**Comment by HighCommander4** [comment]
It's not a setting you change in vscode, but an environment variable that needs to be set before vscode is run (clangd will then inherit it from vscode when it's launched).

For a single invocation of vscode from the terminal, you can use `TMPDIR=/my/tmp/dir vscode <directory>` to launch vscode. For a more persistent solution, you could set it in a place like your `.bashrc`, or start vscode via a wrapper script that sets it.

**Comment by flashk1021** [comment]
I launch vscode locally from a mac, and use remote ssh to read source code on a linux box using clangd to index code. The preamble*.pch files are written into /tmp/ directory on the linux box every time clangd is indexing. It looks like the TMPDIR setup is for vscode launched locally, but not for the clangd extension running remotely. How do I setup the TMPDIR maybe in the clangd extension, but I couldn't find one?

**Comment by HighCommander4** [comment]
> I launch vscode locally from a mac, and use remote ssh to read source code on a linux box using clangd to index code.

Could you say more about how this setup works? I'm not really familiar with it. Does it involve an additional vscode extension, particular vscode settings, `sshfs`, ...?

**Comment by flashk1021** [comment]
Sure. vscode is launched on a mac, ssh to a remote linux box, clangd extension v0.1.16 is installed on the remote linux box. I can see the preamble*.pch files are generated in the /tmp folder on the remote box. I encountered error like not enough space in the remote linux /tmp folder in the output window of vscode when clangd is rebuilding the c++ project index. The workaround is just to release some space of / on remote box. I don't know if there is a better solution to set tmp directory of clangd extension installed on the remote box to other mounted folder.

**Comment by HighCommander4** [comment]
> Sure. vscode is launched on a mac, ssh to a remote linux box, clangd extension v0.1.16 is installed on the remote linux box.

This is the part I'm unclear on: how do you get vscode to connect to the clangd on the remote box?

**Comment by flashk1021** [comment]
I don't know. When I installed the clangd extension I guess it installed remotely. I can see the status of clangd extension shows it is enabled on remote box. Also, at vscode extensions view, there are two sections, one shows the extension installed locally, and the other one shows the extension installed remotely, clangd is in the remote one.

**Comment by flashk1021** [comment]
Also my project is on the remote box, so it make more sense for clangd to index remotely and show the result in vscode locally, instead of the other way around.

**Comment by HighCommander4** [comment]
Ok, having read about it a bit, you're presumably using vscode's [Remote - SSH](https://code.visualstudio.com/docs/remote/ssh) extension.

From [the docs](https://code.visualstudio.com/docs/remote/troubleshooting#_configure-the-environment-for-the-remote-extension-host):

> The environment for the remote extension host and terminal are based on the default shell's configuration scripts. To evaluate the environment variables for the remote extension host process, the server creates an instance of the default shell as an interactive login shell. It probes the environment variables from it and uses them as the initial environment for the remote extension host process

This suggests that adding `export TMPDIR=/my/tmp/dir` to `~/.bash_profile` to `~/.profile` on the remote machine should cause clangd to pick this environment variable up.

**Comment by flashk1021** [comment]
This sounds like the right solution. But I added "export TMPDIR=$HOME/tmp" to ~/.bash_profile, ~/.bash_rc, ~/.porfile and ~/.zshrc, shutdown vscode, restart vscode and remote ssh to linux again, the preamble file is still generated under /tmp directory instead of $HOME/tmp.

**Comment by HighCommander4** [comment]
Hmm, maybe it's because a server-side vscode process persists between client-side vscode invocations, and _that_ needs to be restarted, as discussed in the last paragraph of [this comment](https://github.com/microsoft/vscode-remote-release/issues/1671#issuecomment-542818686)?

**Comment by flashk1021** [comment]
It is working now after restart the remote clangd, thx a lot.
