### ISSUE TITLE
Pass the function signature in the detail property of the completion item instead of the label

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#101]
1. Function declaration.
```c++
void testFuncWithLongName(int a, int b, int c, int d);
```

2. Current behavior.
![image](https://user-images.githubusercontent.com/10697249/61434599-f8f4da80-a968-11e9-951c-61f0a7cddc05.png)

2. Expected behavior.
I think "TypeScript Language Server" display function signature method is more appropriate
![image](https://user-images.githubusercontent.com/10697249/61435001-0b234880-a96a-11e9-9d00-ceab99cffa9f.png)

**Comment by lh123** [comment]
see redhat-developer/vscode-java#685

**Comment by ilya-biryukov** [comment]
We don't have to 100% align with the TypeScript server implementation;
The signature is useful in case of overloaded functions, it's better than having the same name multiples times.

We also have other clients we want to work (e.g. YouCompleteMe inside vim) which do not render the `detail` field at all.

I think at this point we would be better off not changing this.

**Comment by lh123** [comment]
Yes, but we can show the full function signature in the detail. Because some long function signatures cannot be fully displayed in the complete label.

**Comment by HighCommander4** [comment]
Closing based on discussion.
