### ISSUE TITLE
Support type inference for `auto` on function arguments for hover & "expand auto type" code tweak

### ISSUE THREAD

**Issue by vogelsgesang** [clangd/clangd#1015]
## Basic Use case

clangd's hover and "expand auto type" functionality are incredibly useful when working with `auto`.

However, they don't work for the `auto` in the following code:

```
#include <functional>

struct VeryLongAndComplicatedTypeName;

void foo(std::function<void(VeryLongAndComplicatedTypeName*)> callback) {
   callback(/*...*/);
}

void bar() {
   foo([&](auto* x) { });
}
```

In this case, the `auto` is just used to avoid typing a long winded name (realistic examples: `std::vector<int>::iterator`), but the templated lambda is not actually used as a template, i.e. instantiated with multiple different types.

## Advance use cases

Some advanced cases which would also be covered by my proposal below:

```
using Callback1 = std::function<void(VeryLongAndComplicatedTypeName*)>;
using Callback2= void(*)(VeryLongAndComplicatedTypeName*);
using Callback3 = std::function<void(SomeOtherType*)>;

void someFunctionWithCallback1(Callback1);
void someFunctionWithCallback2(Callback2);
void someFunctionWithCallback3(Callback3);

inline void doSomething() {
    someFunctionWithCallback1([](auto* x) { /*,...*/ });
    // In this case, we know for sure, that the template is only instantiated with `VeryLongAndComplicatedTypeName`.
    // We can deduce `auto` to `VeryLongAndComplicatedTypeName` and display it in the hover & offer the tweak.
}

inline void doSomethingElse() {
    auto callback = [](auto* x);
    someFunctionWithCallback1(x);
    someFunctionWithCallback2(x);
    // In this case, we cast `x` into two different callback types (once a std::function, once a raw pointer)
    // But in both cases `auto` is deduced as `VeryLongAndComplicatedTypeName`, so clangd could still
    // offer `VeryLongAndComplicatedTypeName` as the expanded type in the hover & tweak.
}

inline void doSomeThirdThing() {
    auto callback = [](auto* x);
    someFunctionWithCallback1(x);
    someFunctionWithCallback3(x);
    // In this case, the lambda is actually instantiated with two different types.
    // clangd culd display both in the hover of `auto`, but don't offer an "expand auto" tweak anymore
}
```

## Thoughts on implementation

(take those with a grain of salt - I still have little insight into `clangd`'s internals)

The `auto` in the lambda turns the lambda's `operator()` into a template, and clangd can't immediately see which type `auto` will be deduced at by just looking at the lambda itself. However, taking the context of the lambda (it's casted to a `std::function` which is completely typed), the type of the `auto` should be clear.

I think, we can solve this the following way:
* track all types with which the template gets  instantiated with
* if there is only such one type, this is the type we should use for the expanded type in both the hover and the "expand auto type" tweak
* if there are multiple types: display all types on hover. It's pretty useful to know which types a template gets instantiated with, even independently of my request (of course, we would truncate at <magic number> types; displaying a huge list of more than <magic number> types would provide less value but be expensive to compute)

In general, we can't know where a template is instantiated across the code base and need cross-TU information to collect all types for the template instantiation. Afaict, that would require enhancing clangd's index with that information. It would be pretty high-effort.

We should be able to cut down on this cost, and still satisfy my original goal, i.e. "auto" hovers on *local* lambdas, if we would restrict the "collect all type instantiations" to case where the templates instantiation does not escape from the translation unit, i.e. if:
* we are in a cpp file (instead of a header file), or
* we are in a hpp file, but we are not at the top-level scope, e.g. inside some function (see example below)

In those cases, we know that all instantiations must be local, and that our list of instantiations collected from the current TU is actually exhaustive.

Example for"not in a top-level scope" :

```
// inside some header

using Callback1 = std::function<void(VeryLongAndComplicatedTypeName*)>;
using Callback2= void(*)(VeryLongAndComplicatedTypeName*);
using Callback3 = std::function<void(SomeOtherType*)>;

inline void doSomethingElse() {
    auto callback = [](auto* x);
    someFunctionWithCallback1(x);
    someFunctionWithCallback2(x);
    // Yes, we are in a header. But we know for sure, that nobody outside of the `doSomethingElse`
    // function scope could possibly instantiate `callback::operator()`, so we can still figure out all
    // used types for the `auto` without an index, using only local reasoning inside the current header 
}
```

**Comment by HighCommander4** [comment]
See #493 for a very similar request and some discussion.

If you're interested in contributing enhancements in this area, I'm happy to provide guidance.

**Comment by sam-mccall** [comment]
This is way less scary than I had previously thought. Sent out https://reviews.llvm.org/D119537
