### ISSUE TITLE
Go-to-type on smart_ptr<Foo> should show Foo.

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#1026]
This is a more useful result than smart_ptr itself. We should show either Foo or both Foo and smart_ptr.

(this applies to typeDefinition and go-to-definition on auto)

**Comment by hokein** [comment]
`llvm::Optional`/`std::optional` is good candidate to cover as well.

**Comment by kadircet** [comment]
in addition to special casing by types, another option might be to check if we are providing definition for a class template, with a single explicit argument (might have more defaulted args), that lies inside system headers, and if so do an extra query for the template argument as well

**Comment by sam-mccall** [comment]
We've had some discussion in the past about detecting/handling smart pointers, and I think the heuristic resolver even has logic to extract the pointee type we could share. (It's used in go-to-def on p->size() where p is `unique_ptr<vector<dependent>>`)

IIRC the trick was:
- the presence of `operator*` and `operator->` is a good heuristic **this is some kind of smart pointer** to avoid false positives
- but the operator return type is often dependent metaprogramming goo
- if we know it's a smart pointer, the first-template-arg heuristic Kadir mentioned is good

@HighCommander4 is the expert on this stuff though

**Comment by HighCommander4** [comment]
> We've had some discussion in the past about detecting/handling smart pointers, and I think the heuristic resolver even has logic to extract the pointee type we could share. (It's used in go-to-def on p->size() where p is `unique_ptr<vector<dependent>>`)

Yep, see [`HeuristicResolver::getPointeeType()`](https://searchfox.org/llvm/rev/d7d4ed0847dfb42c3ecfd550875033b1ab0931ef/clang-tools-extra/clangd/HeuristicResolver.cpp#58).

The current heuristic just checks for the presence of `operator->`, and then assumes the pointee type is the first template argument of the smart pointer type, which handles the common cases.
