### ISSUE TITLE
Precise analysis of singly-instantiated templates

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#1027]
Sometimes a template is only instantiated once. e.g. `auto` params to lambdas or functions used for terseness:

```
std::sort(foo.begin(), foo.end(), [](auto &L, auto &R) { ... });
```

Sad side effect: the body has a much less interesting AST, with fewer types and resolved symbols.

However we do have AST for specializations, and when there's exactly one we could traverse that instead.
This would yield precise go-to-definition etc.

Caveats:
 - if it's only an accident that there's exactly one visible instantiation, this is very confusing
 - it may be confusing/misleading that results don't match the literal code meaning
 - this technique doesn't apply to code completion, which runs during template parsing (we never get to instantiation)
 - dealing with multiple "mostly-compatible" instantiations is probably more trouble than it's worth

https://reviews.llvm.org/D120131 is a prototype of this technique.

**Comment by sam-mccall** [comment]
Nevermind, let's fold this into #493

**Comment by HighCommander4** [comment]
This is sufficiently adjacent to an editor feature I've long wanted, that you inspired me to write it up at #1028
