### ISSUE TITLE
edit: Neovim-lsp load issues, lsp reports false errors when project build successfully

### ISSUE THREAD

**Issue by ntn888** [clangd/clangd#1029]
Please describe the problem.
issue in detecting a bl-iot-sdk risc-v MCU project. (similar issues seen in arm cortex-M projects based on Zephyr framework)

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
```
/include -I . -c /home/ajit/work/uc/bl602/my_blink/main/main.c -o main.o -fsyntax-only -resource-dir=/usr/lib/llvm-12/lib/clang/12.0.0\n'
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "E[04:49:22.072] VFS: failed to set CWD to /home/ajit/work/uc/bl602/my_blink/build_out/main: No such file or directory\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[04:49:22.074] --> window/workDoneProgress/create(0)\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[04:49:22.074] Enqueueing 1 commands for indexing\nI[04:49:22.075] <-- reply(0)\nI[04:49:22.075] --> $/progress\nI[04:49:22.075] --> $/progress\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "E[04:49:22.082] VFS: failed to set CWD to /home/ajit/work/uc/bl602/my_blink/build_out/main: No such file or directory\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[04:49:22.084] --> $/progress\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[04:49:22.084] --> $/progress\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "E[04:49:22.134] VFS: failed to set CWD to /home/ajit/work/uc/bl602/my_blink/build_out/main: No such file or directory\n"
[ERROR][2022-02-23 04:49:22] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[04:49:22.159] --> textDocument/publishDiagnostics\n"
```

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`: Ubuntu clangd version 12.0.0-3ubuntu1~21.04.2

Editor/LSP plugin: Neovim/lsp

Operating system: Pop-os 21.04

**Comment by sam-mccall** [comment]
Without a description of the problem or it's symptoms there isn't anything we can do here.

This log doesn't show the problem. (And neovim logs are not usable anyway: https://github.com/neovim/neovim/issues/16807)

Please reproduce with `clangd --check --log=verbose` and provide its output. (as well as describing what the problem is)

**Comment by sam-mccall** [comment]
That directory is specified by your compile_commands.json. It's used to resolve relative paths in the compile command used to parse the file. If it doesn't exist, possibly your build system is producing an incorrect compile_commands.json.

However that message in a log file isn't the real problem you're having right? What symptoms are your seeing?

**Comment by ntn888** [comment]
i'm not able to traverse include files within the skd files, but can jump to files within the project.

an error message is shown at line 1 (as in log) but the project compiles successfully...

**Comment by ntn888** [comment]
> That directory is specified by your compile_commands.json. It's used to resolve relative paths in the compile command used to parse the file. If it doesn't exist, possibly your build system is producing an incorrect compile_commands.json.

> that error anyway is because i ran ```make clean```,

**Comment by ntn888** [comment]
sorry i can jump to any part of the source including sdk,
only issue is the error:
```
E[05:18:38.155] [drv_unknown_argument] Line 1: unknown argument: '-fstrict-volatile-bitfields'
```

**Comment by ntn888** [comment]
actually it does follow up if other errors are present and codecompletions.
so looks like i can safely ignore it...

**Comment by HighCommander4** [comment]
If you'd like to suppress the "unknown argument" diagnostic, you can do so by instructing clangd to remove that flag from the compile command as described [here](https://clangd.llvm.org/config.html#remove).
