### ISSUE TITLE
Clangd should parse header files in context

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#103]
1. foo.h
```c++
#ifndef TEST
#error TEST not defined!
#endif
```
2. main.cpp
```c++
#define TEST
#include "foo.h"
```
3. Current behavior.
![image](https://user-images.githubusercontent.com/10697249/61577040-80cb1800-ab14-11e9-9d94-616447564558.png)
4. Expected behavior. (from `Microsoft C/C++ extension`)
![image](https://user-images.githubusercontent.com/10697249/61577077-e61f0900-ab14-11e9-86df-9eec4c4e1464.png)

**Comment by srillia** [comment]
this is a bug, which not fix by now, too for me

**Comment by njames93** [comment]
The issue is, we can't make concrete assumptions about this. The file may be included somewhere else with different macros defined etc. Clangd is designed to work on the assumption that all files are self contained.

**Comment by srillia** [comment]
that't the problem, but clion can do that well. when there is not #include ,it will fell that and give me the best choice.

**Comment by njames93** [comment]
foo.h
```c
#ifdef TEST
#error
#endif
```

a.c
```c
#include "foo.h"
```

b.c
```c
#define TEST
#include "foo.h"
```

In this contrived example, should clangd give an error or not when parsing `foo.h`?
If we treat the header as self contained its always going to be no.
Likewise parsing in `a.c`'s context it also wont error.
However parsing in `b.c`'s context will cause an error. 
This non-deterministic behaviour is part of the reason for assuming headers are self contained in clangd.

**Comment by HighCommander4** [comment]
> In this contrived example, should clangd give an error or not when parsing `foo.h`?
> If we treat the header as self contained its always going to be no.
> Likewise parsing in `a.c`'s context it also wont error.
> However parsing in `b.c`'s context will cause an error.

Eclipse's behaviour here is:

  * if `foo.h` is opened by following the include from `a.c`, no error
  * if `foo.h` is opened by following the include from `b.c`, error
  * if `foo.h` is opened "without context" (e.g. from the editor's file browser), you get one of the two behaviours, but there is no guarantee about which one

**Comment by kadircet** [comment]
This is almost the same problem as #45
