### ISSUE TITLE
extract variable bug

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#105]
```c++
int main() {
    int a = 1 + [[2 + 3]];
}
```
Extract variables in "[[ ]]"
1. Current behavior
```c++
int main() {
    auto dummy = 1 + 2 + 3;
    int a = dummy;
}
```
2. Expected behavior
```c++
int main() {
    auto dummy = 2 + 3;
    int a = 1 + dummy;
}
```

**Comment by sam-mccall** [comment]
Yeah, I thought it would take longer for anyone to catch this :-)

Formally, 2 + 3 is not a subexpression here, because + is left-associative: the AST is (1 + 2) + 3.
However it's clear what the right thing to do is. https://reviews.llvm.org/D65139

**Comment by sam-mccall** [comment]
r367121
