### ISSUE TITLE
Support renaming virtual methods

### ISSUE THREAD

**Issue by tom-anders** [clangd/clangd#1051]
There's already a FIXME for this in Rename.cpp:218 that claims the index doesn't have the required information for this feature. However, I think this might be outdated, since clangd supports "textDocument/implementation" which actually is able to find overrides of virtual methods.

**Comment by HighCommander4** [comment]
Dupe of #706

**Comment by tom-anders** [comment]
Ah I actually used the search function but must have overlooked it, sorry!
