### ISSUE TITLE
Don't emit default template arguments when expanding auto 

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#106]
Example:

```cpp
#include <vector>
std::vector<int> foo();
int main() {
  au^to S = foo();
}
```

Expect: `std::vector<int> S = foo();`
Actual: `std::vector<int, std::allocator<int>> S = foo();`

**Comment by sam-mccall** [comment]
Doing this in the obvious, principled way is hard.

We'd like to verify if the actual args in the type are equal to the default (not defaulted: e.g. std::string::substr returns basic_string<char, traits, allocator>).

We can get the actual `TemplateArgument`s from the type (`int`, `std::allocator<int>`), and the `TemplateParameter`s with default values from the template name (`T`, `allocator = std::allocator<T>`).
However `allocator<int>` isn't structurally the same as `allocator<T>` - the defaults are *substituted*.

That substitution is exposed by sema (`SubstDefaultTemplateArgumentIfAvailable`) but we don't have  access to sema (and if we did, it's probably slow and has side effects like diagnostics).

---

Less direct approaches:
 - special case strings+vectors or allocators or something in the pretty-printer, behind a pretty-printing flag.
 - try to mangle the strings that come out of the pretty printer!
 - write a completely separate piece of code to walk the template arg list and template parameter list, working out which arguments are equivalent to the default values. This is a simpler problem than actual substitution, and we only need to detect the cases that are important in practice. Still this is probably complicated.

**Comment by hokein** [comment]
another easier (but hacky) approach is: we could make pretty printer only print [minimal required arguments](https://github.com/llvm/llvm-project/blob/master/clang/include/clang/AST/DeclTemplate.h#L152) for a template argument list.

However it won't work if the actual arg is different than the default one. Maybe we could just add a new option like `SuppressDefaultTemplateArguments` to the `PrintingPolicy`, and only set it for the special cases like `std::vector`.

**Comment by hokein** [comment]
This is fixed in https://github.com/llvm/llvm-project/commit/e7f3e2103cdb567dda4fd52f81bf4bc07179f5a8
