### ISSUE TITLE
Clangd fails to deduce type of template arguments

### ISSUE THREAD

**Issue by rag-hav** [clangd/clangd#1060]
Trying to use clangd with neovim editor on the codebase of bitcoin. Clangd gives error `clang: No viable constructor or deduction guide for deduction of template arguments of 'Span' [deduced_class_template_ctor_no_viable]` on line https://github.com/bitcoin/bitcoin/blob/7b83c7d609ba61c5726650208b53111eb11a4b0e/src/compressor.h#L68

Vs Code's LSP works fine, and code compiles with both gcc 11.2 and clang 13

**System information**

Output of `clangd --version`: 
clangd version 13.0.0 (Fedora 13.0.0-3.fc35)
Features: linux
Platform: x86_64-unknown-linux-gnu; target=x86_64-redhat-linux-gnu

Editor/LSP plugin: NVIM v0.6.1 

Operating system: Fedora 35

**Comment by HighCommander4** [comment]
> Vs Code's LSP works fine

Were you testing with clangd (vscode-clangd plugin), or Microsoft's language server (vscode-cpptools plugin)?

**Comment by HighCommander4** [comment]
If clang 13 compiles the code fine but clangd 13 gives an error, the issue is likely to be configuration-related. Do you have a `compile_commands.json` for the workspace? Can you share a [clangd log](https://clangd.llvm.org/troubleshooting#gathering-logs)?

**Comment by rag-hav** [comment]
I was testing it with Microsoft's language server.

Yes I do have a [compile_commands.json](https://gist.github.com/rag-hav/8a2b3f3ddf2aa764c47fcbc280026817) created using bear.

Here is the log https://pastebin.com/e5aMmwP6

**Comment by HighCommander4** [comment]
Thanks. The interesting part of the log is:

> I[11:10:35.655] ASTWorker building file /main/Small Projects/bitcoin/src/compressor.h version 0 with command inferred from /main/Small Projects/bitcoin/src/compressor.cpp
> [/main/Small Projects/bitcoin/src]
> /usr/bin/clang++ --driver-mode=g++ -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wrange-loop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy -fPIE -g -O2 -c -x c++-header -std=c++17 --std=c++17 -include=$HOME/projects/bitcoin -resource-dir=/home/raghav/.local/share/nvim/lsp_servers/clangd/clangd/lib/clang/13.0.0 -- "/main/Small Projects/bitcoin/src/compressor.h"

As you can see, clangd prints the full command that it's running, and the directory (`/main/Small Projects/bitcoin/src`) in which it runs it.

Can you try going to that directory on the command line, and then running the same command? Do you get the same error on the command line?

**Comment by rag-hav** [comment]
It gives a different error

`/main/Small Projects/bitcoin/src master ❯ /usr/bin/clang++ --driver-mode=g++ -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wrange-loop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy -fPIE -g -O2 -c -x c++-header -std=c++17 --std=c++17 -include=$HOME/projects/bitcoin -resource-dir=/home/raghav/.local/share/nvim/lsp_servers/clangd/clangd/lib/clang/13.0.0 -- "/main/Small Projects/bitcoin/src/compressor.h"
<built-in>:1:10: fatal error: '=/home/raghav/projects/bitcoin' file not found
#include "=/home/raghav/projects/bitcoin"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`

It looks like it was expecting a file, but got a folder from compile_flags.json

**Comment by rag-hav** [comment]
`/main/Small Projects/bitcoin/src master ?1 ❯ /usr/bin/clang++ --driver-mode=g++ -DHAVE_CONFIG_H -I. -I../src/config -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./minisketch/include -I./secp256k1/include -I./univalue/include -I/usr/include -I./leveldb/include -I./leveldb/helpers/memenv -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -Wall -Wextra -Wgnu -Wformat -Wformat-security -Wvla -Wshadow-field -Wthread-safety -Wrange-loop-analysis -Wredundant-decls -Wunused-member-function -Wdate-time -Wconditional-uninitialized -Woverloaded-virtual -Wsuggest-override -Wunreachable-code-loop-increment -Wimplicit-fallthrough -Wno-unused-parameter -Wno-self-assign -Wno-deprecated-copy -fPIE -g -O2 -c -x c++-header -std=c++17 --std=c++17 -I. -resource-dir=/home/raghav/.local/share/nvim/lsp_servers/clangd/clangd/lib/clang/13.0.0 -- "/main/Small Projects/bitcoin/src/compressor.h" `

Changing the `-include=$HOME/projects/bitcoin ` to `-I.`  makes it run without any errors or output.

**Comment by HighCommander4** [comment]
Interesting, that seems to rule out at least most kinds of configuration issues.

Would you be able to get a log with `--log=verbose` added to clangd's command line arguments?

**Comment by rag-hav** [comment]
I was not able to find any way to pass the verbose flag. However, the issue resolved itself while I was trying to do that. 

I am not sure why

```CompileFlags: # Tweak the parse settings
  Add: [--std=c++17, -include $HOME/projects/bitcoin]
  # Add: [--std=c++17]```
  
But with this -include in my `~/.config/clangd/config.yaml` I get a bunch of  unrelated errors like the template type deduction, but upon removing it (like in the commented line), it all works well.

Anyway, thanks @HighCommander4 for taking you time to look into this, much appreciated.
