### ISSUE TITLE
Argument hint names not shown for function pointer variable call (vscode-clangd, clion)

### ISSUE THREAD

**Issue by Qwinci** [clangd/clangd#1068]
In both vscode with clangd and clion > 2021.2.4 argument hint popup that appears when you call a function (type '(' to make the popup appear) doesn't show argument names for function pointer variable, they only show types like vscode only shows this popup: `(int, int) -> void` and not `(int idk, int idk2) -> void`

```cpp

//typedef void (*test)(int idk, int idk2);
using test = void (*)(int idk, int idk2);
test bruh;

int main() {
	bruh();
}
```
**System information**

Output of `clangd --version`: 
    clangd version 13.0.1
    Features: linux
    Platform: x86_64-pc-linux-gnu

Editor/LSP plugin: vscode-clangd

Operating system: Arch Linux

**Comment by sam-mccall** [comment]
The reason for this lies pretty deep inside clang: there's a `clang::FunctionProtoType` representing `void(int, int)`, but no sugar `Type` representing that type decorated with these specific parameters. (Sugar types are a thing in general, just there isn't one here).

The parameters are attached to the AST, but they're instead attached to the `FunctionProtoTypeLoc` attached to the `TypedefNameDecl`. Having them in the TypeLoc but not a sugar type means that we do have a way to find the AST node for `idk` (hover on it!) but that information doesn't propagate when the type is used e.g. in expressions. So there's no way to get from `bruh` to `idk`.

I think the only reasonable way to implement this would be to add a sugar type (either allowing `FunctionProtoType` to be sugar sometimes, or adding a new kind of `Type`). Realistically it doesn't seem so likely:
 - adding AST nodes is a bunch of work
 - it's fairly rare that function types actually name parameters (except when declaring functions)
 - it's fairly rare that knowing the name of those parameters is useful (just this bug?) so the benefit is limited
Maybe a secondary benefit is cleaning up the places clang passes around FunctionDecl + FunctionType together though.

**Comment by Qwinci** [comment]
@sam-mccall 
Thanks for the info. Really the only place where I find this especially annoying is in glad (OpenGL extension loader generator) because it uses this type of function pointers and theres a lot of them so it would be useful to see the actual argument names instead of needing to search in the internet what they are or looking inside the header itself.

**Comment by HighCommander4** [comment]
> So there's no way to get from `bruh` to `idk`.

What prevents us from navigating from `TypedefType` --> `TypedefNameDecl` --> `FunctionProtoTypeLoc`?

**Comment by Qwinci** [comment]
This exact same thing seems to happen with plain function pointers too. 
```cpp
void (*testFunction)(int param1);

int main() {
	testFunction();
	return 0;
}
``` 
for an example. I don't remember this being always an issue, was there something changed in clang/clangd in the recent versions which caused this?

**Comment by HighCommander4** [comment]
> I don't remember this being always an issue, was there something changed in clang/clangd in the recent versions which caused this?

If you can find an older clangd version which behaves differently, we should be able to track down what's changed.

I tested with clangd-12 and I see the same behaviour (no argument name in the hint) on this testcase.

**Comment by Qwinci** [comment]
> > I don't remember this being always an issue, was there something changed in clang/clangd in the recent versions which caused this?
> 
> If you can find an older clangd version which behaves differently, we should be able to track down what's changed.
> 
> I tested as far back as clangd-10 and I see the same behaviour (no argument name in the hint) on this testcase.

I hadn't actually tested this in vscode before, but in clion 2021.2.4 which uses clang 13.0.0 it works like it should but on anything above that it doesn't work.
![image](https://user-images.githubusercontent.com/32550582/159062602-625004b0-46ff-4cef-90ca-5636eaa70592.png)

**Comment by HighCommander4** [comment]
Interesting. Unfortunately, I don't have access to CLion, so I'm not sure how to investigate that further.

You may want to report this as a regression in the CLion issue tracker. It's possible they have local patches applied to clangd, or that they modify/enhance the completion results on their client side based on their own code model. If they believe it's a clangd regression, they should be able to provide details such as LSP message logs that would allow us to investigate further.

**Comment by Qwinci** [comment]
I already reported it in their issue tracker 3 weeks ago. Though no response yet. https://youtrack.jetbrains.com/issue/CPP-28483

**Comment by Qwinci** [comment]
Is there any update to this? I guess I could try to do it myself, but I am not at all familiar with clang/clangd source.

**Comment by HighCommander4** [comment]
> Is there any update to this? I guess I could try to do it myself, but I am not at all familiar with clang/clangd source.

I'm happy to provide guidance. (We have a [Discord channel](https://discord.gg/xS7Z362) which is a good place to discuss such things, or here in the issue is fine too.)

I can't make any promises about working on this myself any time soon, there are many other bugs ahead of this in my queue.

**Comment by HighCommander4** [comment]
Thank you @Qwinci for fixing!
