### ISSUE TITLE
When the header file is modified, the corresponding source file should be re-parsed

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#107]
1. Original code.
```c++
// foo.h
void getFoo();

// foo.cpp
#include "foo.h"
int main() {
    int a = getFoo();
}
```
Error: `Cannot initialize a variable of type 'int' with an rvalue of type 'void'`

2. After modifying the header file, the error should disappear.
```c++
// foo.h
int getFoo();

// foo.cpp
#include "foo.h"
int main() {
    int a = getFoo();
}
```

**Comment by ilya-biryukov** [comment]
One obvious problem here is that we don't rebuild files when their dependencies change. Need file-watching capabilities for that, we don't have them implemented in clangd yet.
Without those, the errors will only be updated when `foo.cpp` changes.

Another potentially confusing bit is that we read files from disk, therefore if you only change `foo.h` in the editor and not save it, clangd will read the version of `foo.h` from disk; so the errors won't go away until you save it.
This was a deliberate trade-off we chose to make early on, but we should watch out for cases when it causes confusion.
