### ISSUE TITLE
clang crash when instantiating operator-> after recovery

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#1073]
```
template <typename T> struct Ptr { T* operator->(); };

struct Struct { int len; };

template <int>
struct TemplateStruct {
  Ptr<Struct> val();
};

template <int I>
void templateFunc(const TemplateStruct<I>& ts) {
  Ptr<Struct> ptr = ts.val();
  ptr->len;
}

template void templateFunc<0>(const TemplateStruct<0>&);
```

Crashes clang at trunk: https://godbolt.org/z/GbToP46E9
Does not reproduce with -Xclang -fno-recovery-expr

**Comment by kadircet** [comment]
irrelevant to bug itself, but I think we should start filing such issues to llvm-project/llvm nowadays as the fix will also be in clang.

**Comment by HighCommander4** [comment]
This seems to be fixed (trunk was on 15.x at the time of filing, and the 15.x release is unaffected).

**Comment by HighCommander4** [comment]
(The fixing commit was https://github.com/llvm/llvm-project/commit/7e459126185f4d5115e6e2166a866aba1369d024)
