### ISSUE TITLE
SelectionTree doesn't handle semicolons properly

### ISSUE THREAD

**Issue by sureyeaah** [clangd/clangd#109]
Consider the following selection:
```cpp
void f() {
  [[int a = 5;]]
}
```

Since the Clang AST doesn't have a way of representing semicolons, SelectionTree doesn't handle semicolons specially as such and in most cases, the surrounding CompoundStmt(which isn't included in the user selection) claims the selected semicolon and gets (partially) selected.

**Comment by sam-mccall** [comment]
r367453 made SelectionTree ignore semicolons as well as whitespace, because the AST doesn't model them completely and (for better or worse) SelectionTree is coupled to the AST.

I think this is as fixed as this is likely to get soon.
