### ISSUE TITLE
Compiler not detected when path is given in single quotes

### ISSUE THREAD

**Issue by Arazu161** [clangd/clangd#1094]
I'm using [bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) on Windows to generate compile commands for a bazel project. An example output from the tool is given below:

```
"file": "main.cpp",
"command": "'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe' --language=c++ /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-fastbuild/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-fastbuild/bin/external/bazel_tools /Iinclude /showIncludes /MD /Od /Z7 /wd4117 '-D__DATE__=\"redacted\"' '-D__TIMESTAMP__=\"redacted\"' '-D__TIME__=\"redacted\"' /std:c++17 /Fobazel-out/x64_windows-fastbuild/bin/_objs/test/main.obj /c main.cpp",
"directory": "D:/projects/cpp/test"
```
The initial problem was that clangd did not detect the include directories, unless the command was changed from `/I` to `-I`. Either form should in theory work with cl though. After some investigation, it looks like clangd doesn't detect that the compiler is cl.exe and defaults to gcc mode and so doesn't recognise `/I`.
Basically, parsing the path to the compiler breaks on the space in "Program Files" unless either single quotes around the string are escaped (which isn't valid JSON afaik, but from what I can see, clangd expects single quote strings to be escaped) or the single quotes are changed to escaped double quotes.

The reason I think this is an issue with clangd, rather than the generator, is that as I said above, clangd appears to look for escaped single quotes which isn't valid JSON

cmake compile commands gives a form of the path without spaces, so isn't required to quote it (`C:\\PROGRA~2\\MICROS~2\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\Hostx64\\x64\\cl.exe`) which hides this issue, and I think it is unlikely that you will come across a path with spaces in it outside of Windows generally.

**Output of `clangd --version`:**
```
clangd version 14.0.0
Features: windows
Platform: x86_64-pc-windows-msvc
```
(I tested with 13.0 previously as well)

**Editor/LSP plugin:**
tested with VSCode + clangd extension, neovim + builtin LSP, and CLion (note: CLion did not parse the compile_commands.json file at all, and complained about the space in the path which is what pointed me in this direction in the first place)

**Operating system:**
Windows 10

**Comment by sam-mccall** [comment]
Are single quoted strings actually valid on standard windows shells?

When you pass the argv as a single `command` string (rather than an `arguments`) array, it is tokenized according to shell rules based on platform. If you're on windows, these try to emulate the rules used by `cmd.exe`, implemented in `llvm::cl::tokenizeWindowsCommandLine`. This doesn't handle single-quotes at all, and seacrhing the web seems to confirm that single quotes have no special meaning to cmd.exe. Therefore as the space is not escaped in any way, splitting on it seems correct.

**Comment by cpsauer** [comment]
FWIW, my mental model was (wrongly) that we were targeting powershell rather than cmd, thinking of it as the default Windows shell. (I'm certainly no Windows expert, though.) So @Arazu161 is why the single quotes had originally passed my visual sanity check.

**Comment by cpsauer** [comment]
But also--with both of your agreement and assuming it works for people--I'd be happy if we just resolved this as "use arguments (or cmd format) on Windows."

Huge thanks to you both. Was truly a delight to wake up this morning seeing that both of you had figured things out so well.

**Comment by sam-mccall** [comment]
Thanks @cpsauer for fixing! Yeah, this sort of thing is a good reason to prefer the args array.

The JSON CDB spec page says "platform conventions" which is vague. Even if powershell is considered the clear default today, changing the interpretation could break existing generators.

I think we're better off avoiding muddying the waters by trying to change the parsing, and pushing generators to use the args array if at all possible.

**Comment by cpsauer** [comment]
SGTM. Thanks again, @sam-mccall!
