### ISSUE TITLE
`clangd` is inferring the wrong source file from a unity build source file

### ISSUE THREAD

**Issue by vittorioromeo** [clangd/clangd#1098]
I have the following file structure:

```
- src/
    - OHServerControl/
         - main.cpp
    - OHWorkshopUploader/
         - main.cpp
```

I build my project using CMake, with `set(CMAKE_UNITY_BUILD ON)`. The resulting `compile_commands.json` looks like this for the files mentioned above:

```json
{
    "directory": "C:/OHW/SSVOpenHexagon/buildrel",
    "command": "C:\\msys64\\mingw64\\bin\\g++.exe -o CMakeFiles\\OHWorkshopUploader.dir\\Unity\\unity_0_cxx.cxx.obj -c C:\\OHW\\SSVOpenHexagon\\buildrel\\CMakeFiles\\OHWorkshopUploader.dir\\Unity\\unity_0_cxx.cxx",
    "file": "C:\\OHW\\SSVOpenHexagon\\buildrel\\CMakeFiles\\OHWorkshopUploader.dir\\Unity\\unity_0_cxx.cxx"
},
{
    "directory": "C:/OHW/SSVOpenHexagon/buildrel",
    "command": "C:\\msys64\\mingw64\\bin\\g++.exe -o CMakeFiles\\OHServerControl.dir\\Unity\\unity_0_cxx.cxx.obj -c C:\\OHW\\SSVOpenHexagon\\buildrel\\CMakeFiles\\OHServerControl.dir\\Unity\\unity_0_cxx.cxx",
    "file": "C:\\OHW\\SSVOpenHexagon\\buildrel\\CMakeFiles\\OHServerControl.dir\\Unity\\unity_0_cxx.cxx"
},
```

There clearly are two separate unity source files generated. However, `clangd` completion fails in VSCode with missing includes and other unexpected errors. After checking the logs, it seems that `clangd` picks the wrong unity source file:

```
[16:30:01.095] ASTWorker building file c:/OHW/SSVOpenHexagon/src/OHWorkshopUploader/main.cpp version 1 with command inferred from C:\OHW\SSVOpenHexagon\buildrel\CMakeFiles\OHServerControl.dir\Unity\unity_0_cxx.cxx
```

You can clearly see that `clangd` picks the unity source file from `OHServerControl` for `OHWorkshopUploader`, which is incorrect.

---

**System information**

Output of `clangd --version`:

```
clangd version 13.0.1
Features: windows
Platform: x86_64-w64-windows-gnu
```

Editor/LSP plugin:
- `llvm-vs-code-extensions.vscode-clangd` v0.1.15

Operating system:
- Windows 10 x64

**Comment by HighCommander4** [comment]
There are potentially two separate issues here:

  1. The way clangd chooses a source file in the compile_commands.json whose command to use, does not take into account the actual inclusion relationships between files. This is tracked in #123.

  2. If main.cpp is not self-contained, i.e. it implicitly relies on symbols from other source files included earlier in the unity source file, then this is a code pattern clangd does not support, and it will not be able to parse main.cpp even with issue (1) fixed. This is tracked in #45 (and less likely to be fixed).
    (If, on the other hand, you only need it to pick the right unity source file because different unity source files have different flags in their compile command, then fixing (1) should be sufficient to make that work.)

**Comment by HighCommander4** [comment]
I'm going to close this as I don't think there's anything here that isn't covered by the two issues mentioned in the previous comment.
