### ISSUE TITLE
SelectionTree doesn't understand foreach

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#110]
```
for (auto a : f());
              ~~~
```
Clangd thinks the selection is:
```
CXXForRangeStmt for (auto a : f());
  .DeclStmt auto a = * __begin1;
```

clearly getting confused by the synthetic code.

This prevents extract expression to variable.

**Comment by ilya-biryukov** [comment]
Ran into a similar issue when building a syntax tree for those.
Ended up patching the RecursiveASTVisitor a bit to avoid traversing the synthesized nodes. See `TraverseCXXForRangeStmt` in the [https://reviews.llvm.org/D63835#change-QqmKCOxZ37eX](code review).

Maybe the same trick could help here.

**Comment by sam-mccall** [comment]
rL370191
