### ISSUE TITLE
The compile commands header to source heuristic doesn't use the file type

### ISSUE THREAD

**Issue by ishaangandhi** [clangd/clangd#1108]
When a compilation database does not contain an entry for a header file, say X.H, clangd employs a heuristic to find a reasonable compile command, which typically involves finding X.c or X.cpp, and using its compile command instead.

This heuristic, however, uses the path of the file to guess the type of the file, instead of using the file type passed in by the client.

See the getCompileCommands function [here](https://reviews.llvm.org/source/llvm-github/browse/main/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp$509).

```
auto Lang = guessType(Filename, &TypeCertain);
```

My organization uses the ".C" extension for cpp files, and leads clangd to be unusable without adding an entry for every header to the compilation database.

I'd be happy to submit a patch for this issue, if it would be welcome. Would such a patch be welcome?

**Comment by HighCommander4** [comment]
Aren't `.C` and `.H` already recognized as C++ based on [this](https://searchfox.org/llvm/rev/0ac213667df1afbba3f66cb4fc3ec51073b9c158/clang/lib/Driver/Types.cpp#277,281)?

**Comment by ishaangandhi** [comment]
I don't think so. Here is a way of reproducing:

```
$ tree
.
├── body.C
├── body.H
├── compile_commands.json
└── random_file.cpp

$ cat compile_commands.json 
[
    {
        "file": "body.C",
        "directory": "/Users/ishaangandhi/Desktop/test/failing_clangd",
        "command": "clang++ body commands"
    },
    {
        "file": "random_file.cpp",
        "directory": "/Users/ishaangandhi/Desktop/test/failing_clangd",
        "command": "clang++ random file commands"
    }
]% 
```

Now run clangd with `-log=verbose` and open up "Body.H":

```
I[20:41:18.962] Loaded compilation database from /Users/ishaangandhi/Desktop/test/failing_clangd/compile_commands.json
V[20:41:18.962] Broadcasting compilation database from /Users/ishaangandhi/Desktop/test/failing_clangd
I[20:41:18.962] ASTWorker building file /Users/ishaangandhi/Desktop/test/failing_clangd/body.H version 1 with command inferred from random_file.cpp
```

I would expect the command to be inferred from body.C, but instead it is inferred from random_file.cpp.

**Comment by ishaangandhi** [comment]
Now say you change the filename "body.C" to "body.cpp":

```
I[20:47:47.353] Loaded compilation database from /Users/ishaangandhi/Desktop/test/failing_clangd/compile_commands.json
I[20:47:47.353] ASTWorker building file /Users/ishaangandhi/Desktop/test/failing_clangd/body.C version 1 with command inferred from body.cpp
```

This now works as expected.

**Comment by ishaangandhi** [comment]
The issue is `FileIndex(std::vector<std::string> Files)` gets files with everything lowercased. So "file.C" looks like "file.c".

Then, when it determines types, it guesses it is a C and not a C++ file. In that constructor, we use the line:

```
StringRef Path = Strings.save(StringRef(OriginalPaths[I]).lower());
...
Types.push_back(foldType(guessType(Path)));
```

We could instead guess the type of the original path, without a call to lower. I confirmed this approach works on the above-mentioned simple reproduction. That would be enough for my company's use case of having ".C" C++ files. Though it still would be nice to actually use the file type the user so generously provided and not guess :)

**Comment by ishaangandhi** [comment]
Gotcha. Would a patch with the approach of not lowercasing the path before passing to the type guesser be welcome to fix this?

**Comment by HighCommander4** [comment]
I think a patch that gets `InterpolatingCompilationDatabase` to correctly classify `.C` files as having C++ filetype would definitely be welcome.

I don't have the confidence to say the exact change to describe is the right one, but I think that's more of a detail to be sorted out during code review. In other words, I encourage you to write the patch!

**Comment by sam-mccall** [comment]
> Gotcha. Would a patch with the approach of not lowercasing the path before passing to the type guesser be welcome to fix this?

It needs to be more nuanced than that: the case folding was added because some projects use `FooBar.h` and `foo_bar.cpp`.
(I find that a little odd, but I also find `.C` a little odd, let's find a way to make them both work)

**Comment by ishaangandhi** [comment]
The proposal was to use the original path before pushing an element into the "Types" array. the "Path" variable, which is the lowercased version would still be used elsewhere. Would that address the concern?

**Comment by sam-mccall** [comment]
Sounds like it would, sorry for not reading so carefully!

(I morbidly wonder whether this is going to mess up parsing of `C:\HELLOW~1.H` for someone :smile:)

> Though it still would be nice to actually use the file type the user so generously provided and not guess :)

Problem is robustly parsing the type out of a set of flags is a fair amount of work: unescaping the JSON, shell-unescaping into a list of args, then feeding those to clang's arg parser which isn't optimized for speed... This would need to be done for all files in the CDB to build the index, and it would happen right on startup, blocking parsing the user's first file.

When we tried using more of the compile_commands.json contents upfront, this caused noticeable slowdown in chrome-sized projects (compilation database is several hundred MB).
