### ISSUE TITLE
Expand auto offered when not available (e.g. lambdas)

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#111]
```
auto f = []{};
~~~~
```

Expand auto is offered here, and should not be.

This is because we defer full checking of the type to `apply()` rather than doing it eagerly in `prepare()`. We're avoiding paying the cost of a traversal: according to comments in the code, we can't directly ask the AutoTypeLoc what its deduced type is.

In principle it must be possible to fix this, either we're holding the AST wrong, or it's modeling the code wrong. Failing that, maybe we should just eat the cost of the traversal.

**Comment by gislan** [comment]
That was fixed in 3c5bed734f9e02bd3bc4fbd1e0acc53506823ebf
