### ISSUE TITLE
suspicious inlay-hints in EXPECT_UNAVAILABLE

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#1118]
Open `clangd/unittests/tweaks/MemberwiseConstructorTests.cpp` with the trunk clangd:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/2557445/164422563-149b8304-deed-450b-88bb-b7ca74433f29.png">

**Comment by HighCommander4** [comment]
I suspect this is #1018
