### ISSUE TITLE
Add inlay parameter hint for (mutable) references

### ISSUE THREAD

**Issue by upsj** [clangd/clangd#1123]
As suggested in https://github.com/clangd/clangd/issues/313#issuecomment-922744284, I think it would be really nice to be able to differentiate between by-value and by-(mutable-)reference parameters not just via semantic highlighting, but also via inlay hints.

Suggested variations:
```cpp
void foo(int& i);

int i{};
foo(i); // hint & or &:
int j{};
foo(j); // hint &i: or i& : or i: &
```

I'm happy to work on this, as I already familiarized myself with the corresponding implementation.

**Comment by HighCommander4** [comment]
Cool! Happy to help if you have any questions.

**Comment by upsj** [comment]
Two questions came up during the implementation:
1. How to deal with (non-variadic) forwarding references? Try to detect them or add `&&` regardless? That may also interact with https://github.com/clangd/clangd/issues/447 later (which I am slowly working towards :) )
2. Any preferences on the suffixes I suggested for named and unnamed mutable references?

**Comment by HighCommander4** [comment]
>     1. How to deal with (non-variadic) forwarding references? Try to detect them or add `&&` regardless? That may also interact with [auto completion for make_* functions #447](https://github.com/clangd/clangd/issues/447) later (which I am slowly working towards :) )

Could you give a concrete example? Are you looking to show a `&&` hint when a function parameter has a (presumably non-const) `&&` reference type?

>     2. Any preferences on the suffixes I suggested for named and unnamed mutable references?

No strong preference, but I like `&:` and `&param:`.

**Comment by upsj** [comment]
Re 1.: yes, but I figured out that this question is not that relevant, what's interesting is, as you said, whether to add && to mutable rvalue references

Re 2.: I have a slight preference for adding & as a suffix, but I see the appeal of your suggestion as well.

**Comment by upsj** [comment]
Addressed with https://reviews.llvm.org/D124359
