### ISSUE TITLE
Clangd fails to get headers for non-native toolchains

### ISSUE THREAD

**Issue by embeddedpenguin** [clangd/clangd#1141]
**Problem**:
clangd doesn't see header files for the (non-native) arm-none-eabi-* toolchain. This causes various issues.

Here is clangd failing to see stdio.h:
![image](https://user-images.githubusercontent.com/33668314/166995586-423516e9-5233-478b-b0d5-f5aec58c0c3a.png)

**Logs**:
I don't know how to provide logs in this instance because clangd is being handled by nvim-lsp. If someone could guide me on how to get logs I'll get some and post them.

**System information**

Output of `clangd --version`:
```
clangd version 13.0.1
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:
Neovim:
```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.7.0/work/neovim-0.7.0_build/config -I/var/tmp/portage/app-editors/neovim-0.7.0/work/neovim-0.7.0/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.7.0/work/neovim-0.7.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.7.0/work/neovim-0.7.0_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
I'm using lunarvim which uses a bunch of default plugins. Relevant ones (I think) are:
 - [jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim)
 - [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer)
 - [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)

Operating system (uname -a):
Linux gpenguin 5.15.16-gentoo-x86_64 #2 SMP Wed Jan 26 15:41:34 CST 2022 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

Gentoo Linux (5.15-16)

**Background Information**
I know a solution to this is to pass --query-driver to the clangd call, but since this is handled behind the scenes I can't really control that call. I am hoping there is some other way for clangd to see the headers. I already use compile_commands.json and the toolchain is in there, but the errors still appear. I've attached my compile_commands.json for reference. Its extension is .txt so github will let me attach it.
[compile_commands.txt](https://github.com/clangd/clangd/files/8633781/compile_commands.txt)

**Comment by HighCommander4** [comment]
> **Logs**: I don't know how to provide logs in this instance because clangd is being handled by nvim-lsp. If someone could guide me on how to get logs I'll get some and post them.

Clangd sends it logs to its stderr.

Every language client should provide a way to access the server's stderr.

The question of how to do that for a specific client is more a question for that client, not for clangd.

Is "nvim-lsp" the same thing as "LanguageClient-neovim"? If so, maybe see [this section](https://github.com/autozimu/LanguageClient-neovim/wiki/Clangd#troubleshooting).

> **Background Information** I know a solution to this is to pass --query-driver to the clangd call, but since this is handled behind the scenes I can't really control that call.

Similarly, every client should provide a way to pass arguments to the language server.

**Comment by sam-mccall** [comment]
Unfortunately neovim does not provide usable server logs: https://github.com/neovim/neovim/issues/16807

It's definitely possible to pass args like --query-driver though.

**Comment by embeddedpenguin** [comment]
> > **Logs**: I don't know how to provide logs in this instance because clangd is being handled by nvim-lsp. If someone could guide me on how to get logs I'll get some and post them.
> 
> Clangd sends its logs to its stderr.
> 
> Every language client should provide a way to access the server's stderr.
> 
> The question of how to do that for a specific client is more a question for that client, not for clangd.
> 
> Is "nvim-lsp" the same thing as "LanguageClient-neovim"? If so, maybe see [this section](https://github.com/autozimu/LanguageClient-neovim/wiki/Clangd#troubleshooting).
> 
> > **Background Information** I know a solution to this is to pass --query-driver to the clangd call, but since this is handled behind the scenes I can't really control that call.
> 
> Similarly, every client should provide a way to pass arguments to the language server.

So I'd like to sort turn this issue into a conversation about --query-driver and possible a feature request so that clangd can just use the toolchain provided in the compile_commands.json file itself. If there's a reason why this can't be done, I understand, but the current method seems extremely counter-productive. If clangd knows both the location and name of my toolchain, it should also know where to find headers, right? I haven't dug through clangd source yet. The current method makes implementing clangd as a lsp server tedious for various editors because of this flag needed to be provided. It would be different if it was a flag without an argument, but because it's an argument, I have to essentially write my own lsp-installer for emacs and neovim based on the possibility of a different toolchain being used. This wouldn't be a big deal if there were a super valid reason for it.

If this feature means rewriting a bunch of clangd then obviously forget about it. I just don't see how it isn't as simple as using the toolchain provided by compile_commands.json. Any feedback is welcome, and if it's something that's doable I can try and submit a PR.

**Comment by HighCommander4** [comment]
> a feature request so that clangd can just use the toolchain provided in the compile_commands.json file itself. [...] If clangd knows both the location and name of my toolchain, it should also know where to find headers, right?

You can read about the ways clangd tries to find system headers [here](https://clangd.llvm.org/guides/system-headers#how-clangd-finds-those-headers).

My understanding is that for cross-compilation scenarios, the only method that tends to work reliably is to **execute** the compiler driver from the `compile_commands.json` in a special mode that gets it to print its built-in include paths.

Doing this automatically is a security risk (clangd is basically executing an arbitrary executable that appears in the `compile_commands.json`), hence the `--query-driver` command line flag to whitelist a safe-to-execute path.

> It would be different if it was a flag without an argument,

The argument is regex; if you're not concerned about the security aspect, you could provide a catch-all regex such as `--query-driver=/**/*`.

See also #539 for some discussion about making `--query-driver` automatic in some cases, that might be along the lines of what you're looking for.

**Comment by embeddedpenguin** [comment]
Thanks a bunch for this response. I missed that issue when I was looking this up. I didn't realize that potential security vulnerability, so the issue is clearly way more complicated than just "make query-driver the default" like I originally thought.

**Comment by embeddedpenguin** [comment]
Going to close this issue since there is a lot more to it than just making query-driver the default behavior. But there is a lot of interest in this functionality, especially for platforms that cannot be compiled for natively.
