### ISSUE TITLE
Increasing memory usage over time

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#115]
A clangd instance running on llvm code with 19 open files was consuming ~20gb of resident memory. Instance was running for ~4 days.

In addition to the increased memory usage, all of the operations also seemed to be slowing down overtime. CodeCompletion/Document Highlights started with <10 ms latency, and increased up to ~300ms. SignatureHelp started with ~200ms and increased up to ~3 seconds.
Logs indicate that BackgroundIndex was using ~700mb for serving structures.

**Comment by Trass3r** [comment]
According to HeapTrack there are considerable memory leaks. They look like false positives though.

**Comment by HighCommander4** [comment]
I definitely have to restart clangd once every few days to avoid memory usage going beyond 20+ GB.

**Comment by sam-mccall** [comment]
Recent clangd builds support the [`$/memoryUsage` request](https://github.com/llvm/clangd-www/blob/6c3f99bcca1bd163b009898df6ff794d7ad440af/extensions.md#memory-usage), that returns estimated memory usage broken down by component. It'd be really useful to know:

a) if the usage there looks reasonable but the system usage is not (evidence of a leak or at least that we're neglecting something important)
b) if the usage there looks high, where it is

The VSCode extension has a fancy tree view for this (you can run "clangd: Show memory usage" from the command palette), but it should be possible to invoke from other clients (the request has no parameters, and the JSON response should be human-readable when fed through a prettyprinter)

**Comment by HighCommander4** [comment]
So, a preliminary observation: with the LLVM codebase open as the workspace, I looked at the clangd memory report as well as the virtual memory used by the `clangd.main` process in `top` at two points in time:

 1. Shortly after startup, once the indexer settled down (i.e. serving structures were built) and open files (of which there were only two) were parsed. The clangd memory report showed around **300 MB**. Virtual memory usage of the `clangd.main` process in `top` was around **2 GB**.
 2. About 24 hours later, with vscode left open during that time. I also did some editing, bringing the total number of open files (as shown in the `tuscheduler` subtree) up to 12. The calng memory report shows around **600 MB**. Virtual memory usage of the `clangd.main` process in `top` is **5.8 GB**.

To me, this suggests that the clangd memory report is failing to capture something that isn't just a constant overhead (since the difference between the memory report and the actual virtual memory usage grew significantly over the 24-hour period), or that there is a leak like you say.

**Comment by HuanGong** [comment]
same issue here, about 11GB memory, and more then 20+ thread in background
/usr/local/bin/clangd -j=4 --clang-tidy --limit-results=20 --background-index --header-insertion=nerver
![image](https://user-images.githubusercontent.com/10153981/101432859-9d076900-3944-11eb-9593-d9ac23155515.png)

version:
clangd version 11.0.0

**Comment by HighCommander4** [comment]
On a larger project, with clangd having been open for ~3 days: the clangd memory report shows **2.1 GB**, while the process's memory usage in `top` is **20.6 GB**. Around this point I need to restart clangd to avoid thrashing.

**Comment by HighCommander4** [comment]
Now that I've restarted, clangd memory report shows **1.9 GB**, and process memory usage in `top` is **3.2 GB**. So, the vast majority of the memory usage increase over time is memory that's not accounted in the report.

**Comment by HighCommander4** [comment]
Thanks a lot @qchateau for tracking down and fixing this!

@sam-mccall, do you think this fix might be a good candidate to backport to the next LLVM 11 dot release?

**Comment by HuanGong** [comment]
great job ！

**Comment by kadircet** [comment]
> Thanks a lot @qchateau for tracking down and fixing this!
> 
> @sam-mccall, do you think this fix might be a good candidate to backport to the next LLVM 11 dot release?

we are already close to 12 release. IIRC the cut will be on Jan 26. Is there a specific reason to have it available in a dot release?

**Comment by HighCommander4** [comment]
> we are already close to 12 release. IIRC the cut will be on Jan 26. Is there a specific reason to have it available in a dot release?

It just seems like an impactful issue of the sort that we've sometimes backported in the past, so I just wanted to raise the possibility. If we're at a stage where we're not planning on further backports to 11, or if the code footprint of this patch makes it annoying to backport, there's probably no need to go out of our way specifically for this.

**Comment by sam-mccall** [comment]
I agree this would be a good candidate for backporting for the reasons @HighCommander4 gave. Thanks for bringing it up! Unfortunately 11.0.1 was released a week ago, and only one dot-release is planned per cycle, so I'm not sure there's anything to be done at this point. We could have barely made it into the dot release if we were fast, but I didn't think of it :-(

@kadircet: I expect distros are more willing to push new point releases than major-version releases by default, especially for toolchain-adjacent stuff. e.g. it looks like Debian clangd-10 10.0.1 packages went to unstable in early July, but clangd only became an alias for clangd-11 in December.
