### ISSUE TITLE
FAQ seems to be wrong 

### ISSUE THREAD

**Issue by sebffischer** [clangd/clangd#1150]
Here in the [FAQ](https://clangd.llvm.org/faq) it says that one can use `-I=path_to_headers` to include additional header files. 
However for me this was not the case and I had to use `--include-directory=path_to_headers` to make it work

**Comment by HighCommander4** [comment]
`-I` does work, but it does not seem to support `=` as a separator between the flag and the value. On the clang command line, the separator needs to be a space (`-I path_to_headers`) or just nothing (`-Ipath_to_headers`).

In the config file syntax, the first case (space) needs to be expressed as two arguments:

```
CompilerFlags:
  Add: [-I, path_to_headers]
```
