### ISSUE TITLE
Crash when opening header file with template class declaration

### ISSUE THREAD

**Issue by lingege32** [clangd/clangd#1154]
Hi Clangd Developers,
There is a crash when I opened a header file.

I observe two points that result in Clangd crash.
The first one is `-Wall` compile flags.
If I add `-Wall` in ${HOME}/.config/clangd/config.yaml then Clangd crash.
On the other hand, If I remove `-Wall`,  Clangd works fine.

The second point is class/struct declaration `Foundry` in the following code. I know it's weird that Foundry is declared as struct in a.h and as friend class in `class ProduceA` in b.h.
However,  the compilation is success with `g++ -Wall b.cpp` or `clang++ -Wall b.cpp` where g++ version is 9.2.0 and clang++ is 15.0.0 (build from github)

The following is my code:
 .
├── a.h
├── b.cpp
└── b.h

// a.h
```
  template <typename T>
  struct Foundry {};
  template<> 
  struct Foundry<ItemA> {
      Foundry(const ProduceA& f): nl(f) {}
      bool operator () () {
          return false;
      }
      ItemA gA() {
          return nl.getA();
      }
      const ProduceA& nl;
  };
```

// b.h
```
  #include<iostream>
  class ItemA {
      public:
      void dump(){std::cout<<"a"<<std::endl;}
  };
  class ProduceA {
      ItemA getA() const {
          ItemA tmp;
          return tmp;
      };
      template <typename> friend class Foundry;
  };
  #include "a.h"       
```
// b.cpp
```
  #include "b.h"                                                                                                                                                                              
  int main()
  {
      ProduceA tmpa;
      Foundry<ItemA> b{tmpa};
      ItemA c = b.gA();
      c.dump();
      return 0;
  }
```
**Logs**
 #0 0x0000000000521e73 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/runner/work/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:13
 #1 0x000000000051fdec llvm::sys::RunSignalHandlers() /home/runner/work/clangd/clangd/llvm-project/llvm/lib/Support/Signals.cpp:98:18
 #2 0x00000000005221e6 SignalHandler(int) /home/runner/work/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #3 0x00007ffff7bd0010 __restore_rt sigaction.c:0:0
 #4 0x0000000000b2cee0 clang::clangd::toLSPDiags(clang::clangd::Diag const&, clang::clangd::URIForFile const&, clang::clangd::ClangdDiagnosticOptions const&, llvm::function_ref<void (clang::clangd::Diagnostic, llvm::ArrayRef<clang::clangd::Fix>)>) /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/Diagnostics.cpp:0:0
 #5 0x0000000000ab2d42 operator++ /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_iterator.h:1002:2
 #6 0x0000000000ab2d42 clang::clangd::ClangdLSPServer::onDiagnosticsReady(llvm::StringRef, llvm::StringRef, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >) /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.cpp:1581:19
 #7 0x0000000000aed9a2 ~vector /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:680:30
 #8 0x0000000000aed9a2 operator() /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/ClangdServer.cpp:89:9
 #9 0x0000000000aed9a2 void llvm::function_ref<void ()>::callback_fn<clang::clangd::(anonymous namespace)::UpdateIndexCallbacks::onMainAST(llvm::StringRef, clang::clangd::ParsedAST&, llvm::function_ref<void (llvm::function_ref<void ()>)>)::'lambda'()>(long) /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
#10 0x0000000000c80c6d __gthread_mutex_unlock /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10/bits/gthr-default.h:778:7
#11 0x0000000000c80c6d unlock /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_mutex.h:118:7
#12 0x0000000000c80c6d ~lock_guard /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/std_mutex.h:165:19
#13 0x0000000000c80c6d operator() /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:1125:3
#14 0x0000000000c80c6d void llvm::function_ref<void (llvm::function_ref<void ()>)>::callback_fn<clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >)::$_15>(long, llvm::function_ref<void ()>) /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
#15 0x0000000000aed34c ~vector /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:680:30
#16 0x0000000000aed34c clang::clangd::(anonymous namespace)::UpdateIndexCallbacks::onMainAST(llvm::StringRef, clang::clangd::ParsedAST&, llvm::function_ref<void (llvm::function_ref<void ()>)>) /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/ClangdServer.cpp:92:3
#17 0x0000000000c802ce generateDiagnostics /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:1128:15
#18 0x0000000000c802ce clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >, clang::clangd::WantDiagnostics)::$_2::operator()() /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:1024:5
#19 0x0000000000c7b2f3 operator() /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
#20 0x0000000000c7b2f3 clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void ()>) /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:1204:3
#21 0x0000000000c795df run /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:1338:5
#22 0x0000000000c795df operator() /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/TUScheduler.cpp:727:42
#23 0x0000000000c795df void llvm::detail::UniqueFunctionBase<void>::CallImpl<clang::clangd::(anonymous namespace)::ASTWorker::create(llvm::StringRef, clang::clangd::GlobalCompilationDatabase const&, clang::clangd::TUScheduler::ASTCache&, clang::clangd::TUScheduler::HeaderIncluderCache&, clang::clangd::AsyncTaskRunner*, clang::clangd::Semaphore&, clang::clangd::TUScheduler::Options const&, clang::clangd::ParsingCallbacks&)::$_6>(void*) /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:222:12
#24 0x0000000000e14d91 PointerIntPair /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:49:12
#25 0x0000000000e14d91 UniqueFunctionBase /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:340:3
#26 0x0000000000e14d91 unique_function /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:369:3
#27 0x0000000000e14d91 operator() /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:95:14
#28 0x0000000000e14d91 Apply<(lambda at /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:90:15)> /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:42:5
#29 0x0000000000e14d91 GenericThreadProxy<std::tuple<(lambda at /home/runner/work/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:90:15)> > /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:50:5
#30 0x0000000000e14d91 void* llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::$_1> >(void*) /home/runner/work/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:60:5
#31 0x00007ffff7bc8364 start_thread /remote/depotsrc/depotsrc/vikash/rhel7/glibc-2.20/nptl/pthread_create.c:310:0
#32 0x00007ffff71f9d7d clone /remote/depotsrc/depotsrc/vikash/rhel7/glibc-2.20/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111:0

**System information**
Output of `clangd --version`:
clangd version 14.0.3 (https://github.com/llvm/llvm-project 1f9140064dfbfb0bbda8e51306ea51080b2f7aac)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin: 
VScode + Clangd Plugin
Vim + vim-plug + vim-lsp plugin

Operating system:
Centos 7

**Comment by HighCommander4** [comment]
Hmm, I can't seem to reproduce it in a newer trunk build. Maybe it's been fixed since clangd 14?

**Comment by HighCommander4** [comment]
Indeed, issue went away between the 2022-03-20 and 2022-03-27 snapshots.

Maybe https://reviews.llvm.org/D122315?

**Comment by HighCommander4** [comment]
Confirmed, https://reviews.llvm.org/D122315 is what fixed it.

You can download a weekly snapshot build from https://github.com/clangd/clangd/releases to access the fix before it appears in the clangd 15 release.

**Comment by lingege32** [comment]
Thanks for your response.
It can work with snapshop build.
So, it looks like the fix is not submitted to the branch 14.x, right?
Excitedly awaiting the next stable release clangd15.
