### ISSUE TITLE
clangd crashes weirdly

### ISSUE THREAD

**Issue by Creepercdn** [clangd/clangd#1166]
clangd crashes when build AST.

I have a constexpr function to connect bytes:
```cpp
rawCat(0xFF, 0xAF) -> 0xFFAF
```
I call this function (argument are literal) in the same file, everything is fine.
But when I call this function (argument are literal) in another file, clangd crashes!

Example code is in https://github.com/Creepercdn/clangd_test_28_may

**Logs**

Verbose log:
https://github.com/Creepercdn/clangd_test_28_may/blob/master/verbose.log
`llvm-symbolizer` is in my PATH.

**System information**

Output of `clangd --version`: 
```
clangd version 14.0.0
Features: windows
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin: vscode-clangd

Operating system: Windows 10

**Comment by Creepercdn** [comment]
Also, vscode-clangd try to restart clangd, so the log repeats.

**Comment by HighCommander4** [comment]
I can reproduce the crash with clangd 14. However, it seems to have been fixed since then on trunk: the latest weekly snapshot build from https://github.com/clangd/clangd/releases does not crash.

**Comment by Creepercdn** [comment]
clangd 14.0.3 crashes too. I can't see any weekly snapshot in GitHub Releases.

**Comment by HighCommander4** [comment]
> clangd 14.0.3 crashes too.

Right, it's only been fixed on trunk, not the 14.x branch.

> I can't see any weekly snapshot in GitHub Releases.

Here's the latest one: https://github.com/clangd/clangd/releases/tag/snapshot_20220529
It's the fifth entry from the top https://github.com/clangd/clangd/releases

**Comment by Creepercdn** [comment]
Everything is fine in the snapshot. Thanks.
