### ISSUE TITLE
Cannot rename when path in compile_commands.json is not absolute

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#117]
Try renaming `T` to `U` in the following code:
```cpp
template <class [[T]]> struct Foo {
  using type = T;
};
```

Expected: template parameter is renamed.
Actual: code is unchanged, no error or warning is shown.

**Comment by ilya-biryukov** [comment]
@hokein if the fix is small, it would be nice to merge it into the `9.0` release.

**Comment by ilya-biryukov** [comment]
@hokein  reports everything works fine on his machine.
After digging a bit more, the problem comes from the fact that `compile_commands.json` I was using had a relative path:
```json
{"file": "/home/ilya/project/tmp/foo.cpp", 
 "directory": "/home/ilya/project/tmp",
 "command": "/usr/bin/c++ -xc++ -c foo.cpp"}
```

The changes are (incorrectly) filtered out [here](https://github.com/llvm/llvm-project/blob/de98e92bc2b691248fd6557cea1c03237e21adb2/clang-tools-extra/clangd/refactor/Rename.cpp#L198)

**Comment by ilya-biryukov** [comment]
Can confirm that `gn`, followed by `ninja -t compdb cxx` produces `compile_commands.json` with relative paths, so this issue could be classified as high-to-medium priority.

**Comment by kadircet** [comment]
i believe a similar issue also occurs with bazel, since compile commands
refers to same file via a different path due to symlinked execroot path

**Comment by hokein** [comment]
I believe the issue exists for a long time (and in the previous release). One option to fix this is to check the absolute file path (but it'd not work for the symlink case). Given the fact that we only get `Replacement` result from the `rename` library, it is non-trivial to fix it using other options e.g. checking the replacement source location is in main file.

And we don't have this issue internally as we use a filesystem wrapper in clangd.

**Comment by ilya-biryukov** [comment]
Even better, we should check on `FileID` being equal to the main file id. @sam-mccall suggested we just replace calls to `rename` with whatever it calls internally to get all ranges of references (or even use capacities we have in clangd's XRefs instead?).

Does the `rename` function does anything extra than finding all places where a name is references?

**Comment by hokein** [comment]
fixed in upstream rL368429.
