### ISSUE TITLE
lambda return with if constexpr

### ISSUE THREAD

**Issue by Creepercdn** [clangd/clangd#1179]
```cpp
template <std::size_t N>
using typeof = decltype([] {
    if constexpr (N <= 1) {
        return std::uint8_t{};    <--- In instantiation of template type alias 'typeof' requested here
    } else if constexpr (N <= 2) {
        return std::uint16_t{}; <-- Return type 'std::uint16_t' (aka 'unsigned short') must match previous return type 'std::uint8_t' (aka 'unsigned char') when lambda expression has unspecified explicit return typeclang(typecheck_missing_return_type_incompatible)
    } else if constexpr (N <= 4) {
        return std::uint32_t{};
    } else {
        static_assert(N <= 8);
        return std::uint64_t{};
    }
}());
```

But it will not raise any error when compile by clang++.
The lambda's return type is fixed by the template arguments. (because of if constexpr)

**Logs**

Verbose log: https://pastebin.com/gvPn2xnf

**System information**

Output of `clangd --version`: clangd version 15.0.0 (https://github.com/llvm/llvm-project 0776c48f9b7e69fa447bee57c7c0985caa856be9)

Editor/LSP plugin: vscode-clangd

Operating system: windows 10

**Comment by HighCommander4** [comment]
Hmm, I do not get an error with clangd either.

Tested on the following file (your example, with an #include added and commentary removed to make it compilable):

```c++
#include <cstdint>

template <std::size_t N>
using typeof = decltype([] {
    if constexpr (N <= 1) {
        return std::uint8_t{};   
    } else if constexpr (N <= 2) {
        return std::uint16_t{};
    } else if constexpr (N <= 4) {
        return std::uint32_t{};
    } else {
        static_assert(N <= 8);
        return std::uint64_t{};
    }
}());
```

**Comment by HighCommander4** [comment]
I guess you must have additional code, needed to trigger the error, that instantiates `typeof`.

**Comment by Creepercdn** [comment]
Yes. Just add a line in main():
```
typeof<4> a;
```

**Comment by HighCommander4** [comment]
Still no error for me:

```c++
#include <cstdint>

template <std::size_t N>
using typeof = decltype([] {
    if constexpr (N <= 1) {
        return std::uint8_t{};   
    } else if constexpr (N <= 2) {
        return std::uint16_t{};
    } else if constexpr (N <= 4) {
        return std::uint32_t{};
    } else {
        static_assert(N <= 8);
        return std::uint64_t{};
    }
}());

int main() {
  typeof<4> a;
}
```

**Comment by Creepercdn** [comment]
Well, interesting.
try this:
```cpp
// https://stackoverflow.com/a/72161270/
    template <std::size_t N>
    using typeof = decltype([] {
        if constexpr (N <= 1) {
            return std::uint8_t{};
        } else if constexpr (N <= 2) {
            return std::uint16_t{};
        } else if constexpr (N <= 4) {
            return std::uint32_t{};
        } else {
            static_assert(N <= 8);
            return std::uint64_t{};
        }
    }());

    /// \brief A function to connect bytes,
    /// \code {.cpp}
    /// rawCat(0xFF, 0xFA) -> 0xFFFA
    /// \endcode 
    template <class... T>
    constexpr auto rawCat(uint8_t fbyte, T... bytes)
    {
        typeof<sizeof...(bytes)+1> result = fbyte << sizeof...(bytes)*8;
        if constexpr (sizeof...(bytes)>0) {
            result += rawCat(bytes...);
        }
        return result;
    }
```

**Comment by HighCommander4** [comment]
Thanks. For this updated example, I do get an error with clangd, but I get the same error trying to compile with clang.

> But it will not raise any error when compile by clang++.

What version of clang are you using to compile, that accepts this code?

**Comment by HighCommander4** [comment]
> What version of clang are you using to compile, that accepts this code?

I'm going to guess it's clang 13, since my local testing shows:

 * clang 12 does not yet support lambda expressions in unevaluated contexts
 * clang 13 accepts this code
 * clang 14 and later gives the error

The error seems bogus to me (the line triggering the instantiation of `typeof` is `typeof<sizeof...(bytes)+1>`, which is still dependent), so I think this is an upstream clang regression between clang 13 and clang 14.

**Comment by HighCommander4** [comment]
Reduced code example:

```c++
template <unsigned N>
using typeof = decltype([] {
    if constexpr (N <= 1) {
        return char{};
    } else {
        return int{};
    }
}());

template <unsigned N>
void foo() {
    typeof<N> a;
}
```

**Comment by HighCommander4** [comment]
Filed upstream as https://github.com/llvm/llvm-project/issues/55890.
