### ISSUE TITLE
Don't Mark Conditional Preprocessor Line as Inactive

### ISSUE THREAD

**Issue by daiyousei-qz** [clangd/clangd#1181]
Currently, clangd will mark all lines that's skipped by the clang preprocessor as inactive, including those #elif and alike. Although technically it's correct from the perspective of the preprocessor, it's less readable since all conditional directives are "hidden" among all other codes.

They should instead be treated as normal code.

A workaround could be: https://github.com/llvm/llvm-project/compare/main...daiyousei-qz:avoid-mark-conditional-preprocessor-line-inactive
which presents the following syntax highlighting:
![image](https://user-images.githubusercontent.com/12378019/172103559-05bb6c09-8b2f-4528-9cde-3454706a77a8.png)

However, the changes above feel more like a workaround instead of a fix to me. Probably, the change should be made to the PPCallback::SourceRangeSkipped. But I'm afraid changing behavior of that could be destructive to other tools and the current model is technically correct from the compiler's perspective.

Limitation of the change above:
1. Macros in directives that are not taken doesn't get correct semantic token info as displayed in the example above
2. The following code will crash the clangd in clangd::toSemanticTokens "assert(Tok.R.end.line == Tok.R.start.line);"
```
#ifdef \
test
#endif
```

---
Update:
Crash doesn't seem to be related to the change above, maybe it's related to https://github.com/clangd/clangd/issues/1145

**Comment by HighCommander4** [comment]
If I understand correctly, this is the same as #773, and may be fixed by the patch at https://reviews.llvm.org/D125863

**Comment by daiyousei-qz** [comment]
Wow, I'm happy this is being worked on. Though the current patch at https://reviews.llvm.org/D125863 seems to only work with the terminating PP while the workaround above attempts to filter all conditional directive lines as active codes. But it's like embedding a little parser into the clangd codebase which could be a burden to maintain (I doubt new conditional preprocessor will be introduced in the future though except two in C++23).

**Comment by HighCommander4** [comment]
Ah, you mean you would like a preprocessor directive in the middle of an inactive block to be colored as if it were active, as well?

**Comment by daiyousei-qz** [comment]
Exactly. Personally, I think this is more intuitive to see the structure of preprocessors. This is also what cpptools does.

**Comment by daiyousei-qz** [comment]
Anyway, closing this as a dup since this is being worked on.

**Comment by daiyousei-qz** [comment]
Duplicate of https://github.com/clangd/clangd/issues/773
