### ISSUE TITLE
Extra pair of parentheses often gets added

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#119]
In the `--completion-style=bundled` mode, we could avoid adding extra parentheses if they're already there.

Input (complete at `^`): `foo^(10, 20)`
Expected: `foo^(10, 20)`
Actual: `foo(^)(10, 20)`

Ideally, we would even move the cursor *into* the existing pair of parentheses (`foo(^10, 20)`), but I believe LSP won't let us do this.

Note that if we complete argument snippets, omitting the parentheses does not seem like a good option.

**Comment by kirillbobyrev** [comment]
#387 is a superset of this.
