### ISSUE TITLE
Expand auto should respect typedef name decls

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#120]
Example:

```
struct Foo {};
using A = Foo;
typedef Foo B;
void s() {
  auto S1 = A();
  auto S2 = B();
}
```

expected:
`
A S1 = A();
B S2 = B();
`

actual:
`
Foo S1 = A();
Foo S2 = B();
`

**Comment by kadircet** [comment]
This seems to be fixed at [head](https://github.com/llvm/llvm-project/commit/517f1d9e5cd0b78b37eda83f58ed531f73b7a15c)
