### ISSUE TITLE
Cannot suppress error for gcc intrin.

### ISSUE THREAD

**Issue by sgsdxzy** [clangd/clangd#1203]
My project is built using conan+cmake and gcc10 from devtoolset-10. Clangd is complaining about some gcc-specific headers and I found no way to suppress them.

For example, a simple test program:
```
// test.cpp
#include <xmmintrin.h>
int main() { return 0; }
```
```
// compile_commands.json
[
  {
    "directory": "/tmp/test",
    "arguments": ["/opt/rh/devtoolset-10/root/usr/bin/g++", "-o", "test", "test.cpp"],
    "file": "test.cpp"
  }
]
```
This program can be compiled by g++ with no error.

run `clangd --check=test.cpp --query-driver=/opt/rh/devtoolset-10/root/usr/bin/g++ --enable-config`
and clangd gives error `[bultin_definition] Line 1: in included file: definition of builtin function '_mm_getcsr'`

I tried with config.yaml like this
```
If:
  PathMatch: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/include/.*
Diagnostics:
  Suppress: '*'
```
but the problem still exists.

Sorry the system is airgapped so I cannot export the logs. If it is required, I can try uploading screenshot. But I think the above example might be enough to illustrate the problem.

**System information**

Output of `clangd --version`:
```
clangd version 13.0.1 (https://github.com/conda-forge/clangdev-feedstock b741c7551b48482d08d2f65a791b7602c1f23c9d)
Features: linux
Platform: x86_64-unknown-linux-gnu
```
(Sorry again for airgapped system so I typed these, the hashtag might be incorrect)

Editor/LSP plugin: I am using vscode+clangd, but the problem can be reproduced by calling clangd --check directly.

Operating system: Oricale Linux Server 7.9

**Comment by HighCommander4** [comment]
There are two different issues here preventing the suppression from working:

 1. Config fragments are applied on a per-document basis, and `PathMatch:` applies to the path of the document (i.e. the file open in the editor). So, `PathMatch: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/include/.*` will make the suppression apply when opening the system header itself, but not when opening a file in your project that includes the header; for that, you need to put the suppression into your project config (`.clangd` file in the project root; no `If:` needed). Of course, you probably don't want `Suppress: '*'` applying to your project files (since that would suppress useful diagnostics that you want to see), so you can suppress just this specific type of error with `Suppress: 'builtin_definition'` instead.

 2. Independent of the above, clangd 13 has a bug (#906) where it fails to apply suppressions to diagnostics from included header files. This is fixed in clangd 14, so you'd need to upgrade.

**Comment by HighCommander4** [comment]
Separate from suppression issues, the fact that this diagnostic is generated in the first place suggests another problem.

My understanding is that `<xmmintrin.h>` is an example of a [built-in header](https://clangd.llvm.org/troubleshooting#cant-find-compiler-built-in-headers-stddefh-etc) such that clangd is supposed to use its own, not gcc's, even when trying to emulate gcc.

However, with `--query-driver`, clangd's system include extractor adds the path containing gcc's copy of this header to the synthesized compile command, causing clangd to (try to) use gcc's copy.

I don't really understand how this is intended to work.

**Comment by sgsdxzy** [comment]
> There are two different issues here preventing the suppression from working:
> 
>     1. Config fragments are applied on a per-document basis, and `PathMatch:` applies to the path of the document (i.e. the file open in the editor). So, `PathMatch: /opt/rh/devtoolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/include/.*` will make the suppression apply when opening the system header itself, but not when opening a file in your project that includes the header; for that, you need to put the suppression into your project config (`.clangd` file in the project root; no `If:` needed). Of course, you probably don't want `Suppress: '*'` applying to your project files (since that would suppress useful diagnostics that you want to see), so you can suppress just this specific type of error with `Suppress: 'builtin_definition'` instead.
> 
>     2. Independent of the above, clangd 13 has a bug ([Diagnostic suppression not respected in header files #906](https://github.com/clangd/clangd/issues/906)) where it fails to apply suppressions to diagnostics from included header files. This is fixed in clangd 14, so you'd need to upgrade.

Sadly, the conan build system make all dependency packages' header as system include, so regression #1100 is preventing me from using clangd 14 (in fact I just downgraded from 14). So is there any chance I can get a version fixing both issue, or do I have to wait clang 15 (or build a custom one)?

**Comment by HighCommander4** [comment]
You can get a weekly snapshot build that includes the fix for #1100 from https://github.com/clangd/clangd/releases.

**Comment by sgsdxzy** [comment]
Thanks, I will give it a try.

**Comment by sgsdxzy** [comment]
The snapshot build turns out to depend on glibc 2.18, which is too new for my (version locked) system. I ended up building from source and it is working now.
