### ISSUE TITLE
Can not find duckdb headers

### ISSUE THREAD

**Issue by zhanglistar** [clangd/clangd#1204]
Code: 	https://github.com/duckdb/duckdb.git
Open with vscode + remote ssh + clangd extension on remote host, result is:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/985418/177746631-bfb56333-0f70-44f3-bf48-fac93d0045d4.png">
remote host OS: ubuntu 20.04
cmake version: 3.16.3
clang version: Ubuntu clang version 13.0.1-++20220112083154+b9a243d1cac2-1~exp1~20220112203239.53
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
local OS: macOS Monterey

But it works fine on my local macbook pro.
Thanks for your reply.

**Comment by HighCommander4** [comment]
Have you built the project and generated a `compile_commands.json` for clangd? (See https://clangd.llvm.org/installation#project-setup.)

If you've generated a `compile_commands.json` and it still does not work, please share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs).

**Comment by zhanglistar** [comment]
> 

@HighCommander4 Thanks for you reply. `compile_commands.json` is there using cmake command and compile this project is fine. Here is the clangd output
`I[15:33:05.304] clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
I[15:33:05.305] Features: linux+grpc
I[15:33:05.305] PID: 3802102
I[15:33:05.305] Working directory: /data1/zzb/code/duckdb
I[15:33:05.305] argv[0]: /home/zhangzhibiao/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/bin/clangd
I[15:33:05.305] Starting LSP over stdin/stdout
I[15:33:05.311] <-- initialize(0)
I[15:33:05.312] --> reply:initialize(0) 1 ms
I[15:33:05.327] <-- initialized
I[15:33:05.327] <-- textDocument/didOpen
I[15:33:05.328] --> textDocument/publishDiagnostics
I[15:33:05.328] Failed to find compilation database for /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/insert_statement.hpp
I[15:33:05.328] ASTWorker building file /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/insert_statement.hpp version 1 with command clangd fallback
[/data1/zzb/code/duckdb/src/include/duckdb/parser/statement]
/usr/bin/clang -resource-dir=/data1/zzb/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -- /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/insert_statement.hpp
I[15:33:05.329] --> textDocument/clangd.fileStatus
I[15:33:05.342] --> workspace/semanticTokens/refresh(0)
I[15:33:05.342] --> textDocument/clangd.fileStatus
I[15:33:05.357] --> textDocument/publishDiagnostics
I[15:33:05.357] --> textDocument/clangd.fileStatus
I[15:33:05.448] <-- reply(0)
I[15:33:05.560] <-- textDocument/documentSymbol(1)
I[15:33:05.560] <-- textDocument/codeAction(2)
I[15:33:05.560] <-- textDocument/documentLink(3)
I[15:33:05.561] --> reply:textDocument/documentSymbol(1) 0 ms
I[15:33:05.561] --> reply:textDocument/codeAction(2) 0 ms
I[15:33:05.561] --> reply:textDocument/documentLink(3) 0 ms
I[15:33:05.561] --> textDocument/clangd.fileStatus
I[15:33:05.897] <-- textDocument/documentLink(4)
I[15:33:05.897] --> reply:textDocument/documentLink(4) 0 ms
I[15:33:05.897] <-- textDocument/documentSymbol(5)
I[15:33:05.898] --> reply:textDocument/documentSymbol(5) 0 ms
I[15:33:05.898] --> textDocument/clangd.fileStatus
I[15:33:05.992] <-- textDocument/codeAction(6)
I[15:33:05.992] --> reply:textDocument/codeAction(6) 0 ms
I[15:33:05.992] --> textDocument/clangd.fileStatus
I[15:33:06.422] <-- $/setTrace
I[15:33:06.422] unhandled notification $/setTrace
I[15:33:06.422] <-- $/setTrace
I[15:33:06.422] unhandled notification $/setTrace
I[15:33:07.211] <-- textDocument/codeAction(7)
I[15:33:07.211] <-- $/cancelRequest
I[15:33:07.211] --> reply:textDocument/codeAction(7) 0 ms, error: Task was cancelled.
I[15:33:07.211] --> textDocument/clangd.fileStatus
I[15:33:07.211] <-- textDocument/codeAction(8)
I[15:33:07.211] --> reply:textDocument/codeAction(8) 0 ms
I[15:33:07.211] --> textDocument/clangd.fileStatus
[Error - 3:33:07 PM] Request textDocument/codeAction failed.
[object Object]
I[15:33:08.151] <-- textDocument/codeAction(9)
I[15:33:08.151] <-- $/cancelRequest
I[15:33:08.151] --> reply:textDocument/codeAction(9) 0 ms
I[15:33:08.151] --> textDocument/clangd.fileStatus
I[15:33:08.151] <-- textDocument/codeAction(10)
I[15:33:08.151] --> reply:textDocument/codeAction(10) 0 ms
I[15:33:08.151] --> textDocument/clangd.fileStatus
I[15:33:08.151] <-- $/cancelRequest
I[15:33:08.151] <-- textDocument/codeAction(11)
I[15:33:08.151] --> reply:textDocument/codeAction(11) 0 ms
I[15:33:08.151] --> textDocument/clangd.fileStatus`

**Comment by HighCommander4** [comment]
The log shows:

> Failed to find compilation database for /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/insert_statement.hpp

What is the full path of the `compile_commands.json` file?

**Comment by zhanglistar** [comment]
> compile_commands

@HighCommander4 Thanks for your reply. Full path is
`/data1/zzb/code/duckdb/build/compile_commands.json`

**Comment by HighCommander4** [comment]
@zhanglistar Can you try symlinking it into `/data1/zzb/code/duckdb` and see it that helps?

**Comment by zhanglistar** [comment]
> @zhanglistar Can you try symlinking it into `/data1/zzb/code/duckdb` and see it that helps?

@HighCommander4 It does no help. 
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/985418/178961980-7793b1f6-05e8-4b0f-8263-b4f893e993cc.png">

Still got the error:
`I[18:24:39.543] <-- textDocument/documentSymbol(45)
I[18:24:39.543] Failed to find compilation database for /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/extension_statement.hpp
I[18:24:39.544] ASTWorker building file /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/extension_statement.hpp version 1 with command clangd fallback
[/data1/zzb/code/duckdb/src/include/duckdb/parser/statement]
/usr/bin/clang -resource-dir=/data1/zzb/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -- /data1/zzb/code/duckdb/src/include/duckdb/parser/statement/extension_statement.hpp
I[18:24:39.545] --> textDocument/clangd.fileStatus
I[18:24:39.553] --> workspace/semanticTokens/refresh(1)
I[18:24:39.553] --> textDocument/clangd.fileStatus`

**Comment by HighCommander4** [comment]
Very strange. Clangd looks for the `compile_commands.json` in the ancestor directories of the file being opened, so if you're opening `/data1/zzb/code/duckdb/src/include/duckdb/parser/statement/extension_statement.hpp`, it should look in `/data1/zzb/code/duckdb/src/include/duckdb/parser/statement/` and then `/data1/zzb/code/duckdb/src/include/duckdb/parser/` and so on and eventually in `/data1/zzb/code/duckdb/`. I'm not really sure what goes wrong in this case.

**Comment by zhanglistar** [comment]
> Maybe try using the `--compile-commands-dir` command line argument to clangd, as discussed in [this FAQ entry](https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory)?

@HighCommander4 Thanks for you reply, so how do I pass the argument of `--compile-commands-dir` to clangd?

**Comment by HighCommander4** [comment]
In vscode settings, something like:

```
{
  "clangd.arguments": [
    "--compile-commands-dir=/data1/zzb/code/duckdb/build"
  ]
}
```

**Comment by zhanglistar** [comment]
> 

@HighCommander4 This works! So where is wrong?

**Comment by HighCommander4** [comment]
> @HighCommander4 This works!

Yay!

> So where is wrong?

I'm not sure, sorry. Perhaps someone else can offer a hypothesis or suggest a way to investigate the original setup further.

**Comment by infdahai** [comment]
> In vscode settings, something like:
> 
> ```
> {
>   "clangd.arguments": [
>     "--compile-commands-dir=/data1/zzb/code/duckdb/build"
>   ]
> }
> ```

Thanks. It works well in wsl.

**Comment by ZENOTME** [comment]
May it caused by following reason?
> clangd will look in the parent directories of the files you edit looking for it, and also in subdirectories named build/. For example, if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …

[ref](https://clangd.llvm.org/installation#project-setup)

**Comment by qujihan** [comment]
> Because duckdb sets the [compile_commands.json path](https://github.com/duckdb/duckdb/blob/dfc1d1b7feee0fecf056ca700848249c2c09e851/.clangd#L2), just change it.

or use `make clangd` to generate a compile_commands.json file at build/clangd
