### ISSUE TITLE
Clangd not finding include for external library headers

### ISSUE THREAD

**Issue by sgsdxzy** [clangd/clangd#1205]
I use conan to manage projects. For example I have three projects: A that depends only on system libs, B that depends on A, and C that depends on B.
For A, it builds fine and clangd works fine. Conan would place the built project header under like $HOME/.conan/data/A/include/A.h;
For B, conan can provide FindA.cmake, so it builds fine and clangd works fine (as long as cmake is requested to generate compile_commands.json). The code check and insight works both in project B's files, and when Ctrl+Click on a symbol from A and it jumps to header files of A in $HOME/.conan/data/A/include. Conan would place the built project header under $HOME/.conan/data/B/include/B.h;
The problem is for C. Conan provide FindA.cmake and FindB.cmake, and the project also builds fine. Clangd also work for C's files. However,  when Ctrl+Click on a symbol from B and it jumps to header file $HOME/.conan/data/B/include/B.h, clangd no longer works and reports it cannot find header A.h which is included in B.h (pp_file_not_found).

**System information**

Output of `clangd --version`:  (I built it from [llvm/llvm-project@1343632](https://github.com/llvm/llvm-project/commit/134363208b9272a967c911f7b56c255a72a6f0a0))
```
clangd version 15.0.0
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: vscode-clangd

Operating system: Oricale Linux Server 7.9

**Comment by HighCommander4** [comment]
Please have a look at https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory
