### ISSUE TITLE
Can't turn off --function-arg-placeholders

### ISSUE THREAD

**Issue by uuuuu-diwu** [clangd/clangd#1208]
![image](https://user-images.githubusercontent.com/17615704/178197666-5b0d2873-37ea-4ce8-adca-9fa4ae5119bd.png)

clangd arguments:

```
"clangd.arguments": [
        "--function-arg-placeholders=0",
        // 在后台自动分析文件（基于complie_commands)
        "--background-index",
        // clang-tidy功能
        "--clang-tidy",
        "--clang-tidy-checks=performance-*,bugprone-*",
        // 全局补全（会自动补充头文件）
        "--all-scopes-completion",
        // 更详细的补全内容
        "--completion-style=detailed",
        // 补充头文件的形式
        "--header-insertion=iwyu",
        // pch优化的位置
        "--pch-storage=disk",
        "--compile-commands-dir=${workspaceFolder}/build/",
    ],
```

**System information**

Output of `clangd --version`:

clangd version 14.0.3 (https://github.com/llvm/llvm-project 1f9140064dfbfb0bbda8e51306ea51080b2f7aac)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

**Comment by HighCommander4** [comment]
The annotations circled in the screenshot are called "inlay hints". They can be disabled on the [client side](https://github.com/clangd/vscode-clangd/issues/339#issuecomment-1134250952) or [server side](https://github.com/clangd/vscode-clangd/issues/339#issuecomment-1134252016).

(--function-arg-placeholders is something else, related to code completion behaviour.)

**Comment by uuuuu-diwu** [comment]
> The annotations circled in the screenshot are called "inlay hints". They can be disabled on the [client side](https://github.com/clangd/vscode-clangd/issues/339#issuecomment-1134250952) or [server side](https://github.com/clangd/vscode-clangd/issues/339#issuecomment-1134252016).
> 
> (--function-arg-placeholders is something else, related to code completion behaviour.)

i got it, thank you !

**Comment by Michaelzhouisnotwhite** [comment]
How to turn off function-arg-placeholders in clangd.arguments?

**Comment by DonShmily** [comment]
> How to turn off function-arg-placeholders in clangd.arguments?

Add "--function-arg-placeholders = false", in your calngd.arguments,
and if your calngd.arguments, already have "--function-arg-placeholders = true", chage it to false.
