### ISSUE TITLE
Expand auto does not expand correctly on decltype(auto)

### ISSUE THREAD

**Issue by jvikstrom** [clangd/clangd#121]
Example code snippet:
```
class Foo{};
decltype(auto) F = Foo();
```
When trying to expand auto on the decltype the resulting code is:
```
class Foo{};
Foo(auto) F = Foo();
```

it should be:
```
class Foo{};
Foo F = Foo();
```

Also it is not possible to expand auto inside the parentheses (no code action shows up when the cursor is inside the (auto))

**Comment by ilya-biryukov** [comment]
Disabled the code action on `decltype(auto)` for now (r374048).
This should not be hard to fix, we just need to figure out the right range.

Help welcome.
