### ISSUE TITLE
NolintBlocks not work in clangd

### ISSUE THREAD

**Issue by pangweiwei** [clangd/clangd#1212]
no lint block like 
// NOLINTBEGIN
// NOLINTEND

not work in latest version, I check code found that:

```c++
         SmallVector<tooling::Diagnostic, 1> TidySuppressedErrors;
          if (IsInsideMainFile && CTContext->shouldSuppressDiagnostic(
                                      DiagLevel, Info, TidySuppressedErrors,
                                      /*AllowIO=*/false,
                                      /*EnableNolintBlocks=*/false)) {
```
if you change EnableNolintBlocks param to true and rebuild, It works for me.

Can I fix like that?

**System information**

Output of `clangd --version`:   14.0.6

Editor/LSP plugin: vscode

Operating system: macosx

**Comment by HighCommander4** [comment]
This is fixed in trunk: https://github.com/llvm/llvm-project/commit/eb265e3ba28dbac6d6c18674ae603428753559e9
