### ISSUE TITLE
Mem-initializer does not get a highlighting

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#122]
In the following code:

```
class A {
  int field;

  A(int f) : field(f) {}   // <--
};
```

the use of `field` on the indicated line does not get a semantic highlighting.

I would expect it to be highlighted as a field (`"variable.other.field.cpp"`).

cc @jvikstrom

**Comment by sam-mccall** [comment]
Johan: the relevant AST node to handle is CXXCtorInitializer (this isn't a declrefexpr or memberexpr)

**Comment by jvikstrom** [comment]
Added support for highlighting constructor initializers here: https://reviews.llvm.org/rL368434 . So it should be highlighted as fields now.
