### ISSUE TITLE
Including wrong headers

### ISSUE THREAD

**Issue by abbaswasim** [clangd/clangd#1231]
In this simple reproducer code;

```
#include <cstdint>

int main(int argc, char *argv[])
{
    return 0;
}

```
if I type `uint32_t` just before the return statement, clangd is adding `#include <_types/_uint32_t.h>` instead of using the already included `cstdint`. I would expect it to not include these MacOs only platform headers. Following is a gif to show the issue.

![clangd_cstdint](https://user-images.githubusercontent.com/5260991/181729926-0cd3380e-9e73-441f-81d2-51588fbacd21.gif)

Even adding `using namespace std;` before the main has the same behaviour. This is a simple reproducer, but I saw the issue in a project with proper `c++17` compile flags via `compile_commands.json`

**Logs**

Struggling to gather logs for some reason neither `--log=verbose` nor `-log=verbose` is working for me in emacs. Will be happy to try it again if needed but I thought this issue is simple enough and can be reproduced easily.

**System information**

Output of `clangd --version`:

```
Homebrew clangd version 14.0.6
Features: mac+xpc
Platform: x86_64-apple-darwin20.6.0
```

Editor/LSP plugin:
`LSP :: lsp-mode 20220727.817, Emacs 28.1, darwin`

Operating system:
`MacOs 11.6.7`

**Comment by abbaswasim** [comment]
Has anyone looked at this? this has been a continuous pain. I can't auto-complete things with the fear it will add headers that I have to remove manually.

**Comment by ckandeler** [comment]
Why don't you just turn it off?

**Comment by abbaswasim** [comment]
Turn off what exactly?
I like adding headers for my code methods, types etc. It's just for standard types it does that. Is there a way to disable that specific bit?

**Comment by abbaswasim** [comment]
Reading the description of `header-insertion` says:

```
  --header-insertion=<value>          - Add #include directives when accepting code completions
    =iwyu                             -   Include what you use. Insert the owning header for top-level symbols, unless the header is already directly included or the symbol is forward-declared
```

I guess the main issue here is that the `unless the header is already directly` bit is not working.

**Comment by HighCommander4** [comment]
I can't reproduce this on Linux.

If someone with a Mac (and who can reproduce this) would like to try investigating it, I can provide pointers for where in the code to look.

**Comment by abbaswasim** [comment]
@HighCommander4 thanks for looking into this.

I am more than happy to help. In this case it will probably take me more time to setup my debugging workflow with `clangd` standalone. I do remember testing this once with some hand written JSON RPC. Is that how it should be done?

Regarding the solution. Is it not something along the lines of, for standard types, filter the includes by standard includes? (will probably break if someone have aliases for standard types with something like `using uint32_t = std::uint32_t` which I have seen)

**Comment by HighCommander4** [comment]
@abbaswasim What clangd version are you using now? There was a [fix](https://reviews.llvm.org/D143214) made in clangd 17 that fixed many issues like this.

**Comment by HighCommander4** [comment]
@abbaswasim The latest clangd version is currently clangd 18. Please try it (you can get it from e.g. https://github.com/clangd/clangd/releases/tag/18.1.3) and see if the issue still occurs. There's not much point discussing potential fixes if we don't even know whether the issue affects the latest version.

**Comment by abbaswasim** [comment]
@HighCommander4 with 18.1.3 from that link I can't reproduce it, seems to have been fixed. Thanks for your time.

**Comment by HighCommander4** [comment]
Glad to hear it!
