### ISSUE TITLE
[clangd] Allow projects to configure include styles as bracketed or quoted

### ISSUE THREAD

**Issue by ilovepi** [clangd/clangd#1247]
Supporting a configurable way to set policies for brackets vs quotes with header-insertion was raised in #670.

The workaround proposed there was a `sed` command, but that solution doesn't scale for large projects.

In Fuchsia we use `clangd` and other LLVM based tooling extensively throughout our system. We would like our developers to be able to use our project's default style rules when header-insertion is enabled, preferably by setting these in project wide config.

Are there plans for this feature, or other steps we can take to avoid issues in the future?

**Comment by kadircet** [comment]
Hi @ilovepi (sorry for the late reply), this is a discussion we had with Fuchsia folks in the past as well. The conclusions were around making changes to the toolchain to be more explicit about the intent for those include paths by using `-isystem` or `-iquote` appropriately. Apart from that we're not actively working on a solution here ATM.

**Comment by sam-mccall** [comment]
> Apart from that we're not actively working on a solution here ATM.

We've had multiple reports of this. I think we would accept a patch that allowed overriding the quote style for a path pattern. But `-isystem` is available today, so it's worth checking whether that could work for you.

**Comment by ilovepi** [comment]
Thanks for the updates. I'll see if the `-isystem` approach works for our use-case. I'm not sure I have time to devote to patching this either, unfortunately.  I'm not that familiar w/ `clangd`'s internals, so on the off-chance I find that time(or someone else wants to pick this up), would the basic approach be to:

1. Add a new config option
2. expose that through the existing config file
3. plumb the new option through to the (hopefully few) places where the choice is made

If that's the rough idea, then do you think it would be worth marking as a good starter bug?

**Comment by qhsong** [comment]
I also need this feature.
Current preprocess binary seems mix the use of bracketed and quoted style.

**Comment by kleinesfilmroellchen** [comment]
Since clangd works with little configuring for SerenityOS, we do not need to modify `-isystem` which is picked up from our toolchain. However, those includes do not include all the headers we include with the bracketed style, so a better way of configuring this is needed.

**Comment by HighCommander4** [comment]
Linking to patch written by @ADKaster: https://reviews.llvm.org/D145843

**Comment by mrbald** [comment]
The heuristic without additional configuration: use triangular brackets if a header is on either `-i` or `-I` search path, else use double quotes.

**Comment by HighCommander4** [comment]
> The heuristic without additional configuration: use triangular brackets if a header is on either `-i` or `-I` search path, else use double quotes.

Yeah, I expect that would align with at least some projects' conventions.

We'd still need at least one bit of configuration though: to choose between this heuristic, and the current one (since we wouldn't want to silently change the default behaviour from the current one, which aligns with the conventions of some other projects).

**Comment by Spongman** [comment]
if my source file already contains:
```
#include <some/project/path/file.hpp>
```

then when adding `some/project/path/another.hpp` it _should_ place that include next to the existing one in the same directory, and use the same bracket/quote style.

**Comment by Jan-Felix-Langenbach-casaGeo** [comment]
The current behavior conflicts with the C++ Core Guidelines, section [SF.12](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf12-prefer-the-quoted-form-of-include-for-files-relative-to-the-including-file-and-the-angle-bracket-form-everywhere-else). The Guidelines recommend using `""` for relative includes only, and `<>` everywhere else.

**Comment by travisdowns** [comment]
> The workaround of using `-isystem` is not usable because it has other impacts such as disabling warnings in those headers.

This is a critical point. Essentially there is no viable workaround in most cases: the cost of disabling warnings (we treat warnings as errors for our own code) is almost never going to be worth it to get the correct auto-add behavior.

**Comment by ilovepi** [comment]
This is still an issue for Fuchsia, too. As others have mentioned `-isystem` isn't the right approach, and our team won't be changing our build rules to use it.
