### ISSUE TITLE
'rename symbol' configurable file limit

### ISSUE THREAD

**Issue by bangyii** [clangd/clangd#1251]
From what I can tell from going through the source, the allowable file limit when trying to rename symbols (including those outside file) is hardcoded to 50 files.

Trying to rename a symbol which occurs in more than 50 files result in:

**The number of affected files exceeds the max limit 50**

Is this currently configurable via a clangd argument?
If not, will it be possible to expose an argument to allow increasing limit?

**Comment by HighCommander4** [comment]
> Is this currently configurable [...]?

Not currently.

> If not, will it be possible to expose an argument to allow increasing limit?

I think making it configurable would make sense. I expect the preferred configuration mechanism would be https://clangd.llvm.org/config.html, rather than a command-line argument.

**Comment by bangyii** [comment]
https://github.com/bangyii/llvm-project/commit/06039d2073c9139ab55e16766ece1b7285ce743c

Would something like the above work? Few issues I think with the above implementation:

1. Adding the `||` check in Rename.cpp seems a bit hacky
2. Could not find a way to access Config from ClangdLSPServer.cpp, which is where the FileLimit param originates from.
3. Not sure how to expose an integer config param, did not dig too deep into that and no other params take in integers

**Comment by kadircet** [comment]
yanking my comments about the issue from discord for future reference.

> yeah agree with @nridge here, the default is also questionable. we had set it to 50 because of an internal editor, but there isn't much point in having a limit for local editors (as there are likely no other ways to perform the rename).

> i am not so sure about putting it into config mechanism, rather than having a command line flag though. as this isn't really project specific, but rather about the development environment of the user (mostly the editor). so making it a command line flag, and let it apply to all the projects they're editing makes more sense. hence i'd suggest something like rename-file-limit. as for the default, despite my comment up above saying it shouldn't be limited, due to the way LSP interaction works, editors are likely to open all these files. so we still need a limit from that perspective, and 50 has been working out nicely so far. so let's leave it as-is and revisit if we see more people fiddling with it. i am trying to avoid the scenario in which we have a higher limit and that causes the rename to crash the editor by default in certain circumstances, rather than giving user some info.

**Comment by HighCommander4** [comment]
I believe this has been addressed by https://reviews.llvm.org/D136454.
