### ISSUE TITLE
[`Feature request`]: linux aarch64 release 

### ISSUE THREAD

**Issue by valord577** [clangd/clangd#1261]
Please add linux aarch64 release.

**Comment by HighCommander4** [comment]
As with FreeBSD (#1265), Github Actions does not offer hosted aarch64 machines, so we'd have to provide our own or cross-compile.

**Comment by HighCommander4** [comment]
Looks like this was already on file as #514, and there's more discussion there (and more recently, also a third-party repo hosting ARM builds of clangd)
