### ISSUE TITLE
clangd can't search default include when I use <vector>

### ISSUE THREAD

**Issue by fcying** [clangd/clangd#1262]
when I use `vector`, it get Diagnostics
```
E    1:10 ▏In included file: no type named 'pointer' in 'std::_Vector_base<int, std::allocator<int>>'
E    5:17 ▏In template: no type named '_Tp_alloc_type' in 'std::_Vector_base<int, std::allocator<int>>'
```

` g++ -c main.cpp -v` not get error, and the default include is:
```
#include <...> search starts here:
 /usr/include/c++/10
 /usr/include/x86_64-linux-gnu/c++/10
 /usr/include/c++/10/backward
 /usr/lib/gcc/x86_64-linux-gnu/10/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```
After I add `/usr/lib/gcc/x86_64-linux-gnu/10/include` to `compile_commands.json`, clangd work fine, no diagnostics.

How can I let clangd search default include, no modify `compile_commands.json` by manually?

test code
```
#include <vector>
using namespace std;
int main (int argc, char *argv[])
{
    vector<int> test = {1, 2};
    return 0;
}
```
compile_commands.json(create by cmake)
```
[
{
  "directory": "/home/fcying/test/cpp/build",
  "command": "/usr/bin/g++    -o CMakeFiles/test.dir/main.cpp.o -c /home/fcying/test/cpp/main.cpp",
  "file": "/home/fcying/test/cpp/main.cpp"
}
]
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8)
project(test)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_executable(test main.cpp)
```

**System information**

Output of `clangd --version`:
clangd version 16.0.0 (https://github.com/llvm/llvm-project e3dd0ddc5b8d65a0ba9c4faf5834b79aeb82ec77)
Features: linux
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
neovim + lspconfig

Operating system:
debian 11

**Comment by HighCommander4** [comment]
Issues like this can often be resolved using the `--query-driver` approach discussed in https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc.

**Comment by fcying** [comment]
> Issues like this can often be resolved using the `--query-driver` approach discussed in https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc.

tks, after add option `--query-driver=/usr/bin/g++`, it work fine.

but I not using an unusual compiler, and there only one `g++` in my os. 
Why can’t find standard library headers?
```
$ whereis g++
g++: /usr/bin/g++
```

**Comment by HighCommander4** [comment]
How did you install `clangd`? Is there a `clang` executable in the same location? If so, can you check its built-in include paths the same way you've checked gcc's?

**Comment by fcying** [comment]
> How did you install `clangd`? Is there a `clang` executable in the same location? If so, can you check its built-in include paths the same way you've checked gcc's?

tks, `built-in include paths` is the problem.

I use clangd compiled by myself, I only cp `bin/clangd` to ~/bin, it get the problem.
after I cp `lib/clang/15.0.0/include`, it work fine.
