### ISSUE TITLE
Spurious Standard Library Inclusion Errors with GCC, --query-driver, and .h header commands

### ISSUE THREAD

**Issue by cpsauer** [clangd/clangd#1263]
Hey wonderful clangd folks,

This is another bug report bubbling up from clangd users over at [hedronvision/bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor
). Don't worry; I've stripped all bazelisms from the reproducing example.

## Reproducing
Let's say you have a simple clangd project like the following, and you're using GCC on Ubuntu.

First, there's a foo.h, like this:
```c++
#include <iostream>
```
And a foo.cc, like this:
```c++
#include "foo.h"

#include <iostream>

void foo() { std::cout << "Hello!\n"; }
```
And finally, you have a compile_commands.json, like this, with an entry for the header to work around #123
```json
[
  {
    "file": "foo.cc",
    "arguments": [
      "gcc",
      "foo.cc"
    ],
    "directory": "<replace with yours>"
  },
  {
    "file": "foo.h",
    "arguments": [
      "gcc",
      "foo.cc"
    ],
    "directory": "<replace with yours>"
  }
]
```
And you've got --query-driver on, just for kicks. Let's say it's set to `--query-driver=**` so we know it's always on.

Everything should work and there should be no errors! It compiles nicely with gcc and clangd was working great before you added the compile_commands.json. Everything works with clang... And you'd expect it to infer that foo.h is a c++ file, because foo.cc is in its command, per https://reviews.llvm.org/D116167

But...there's a strange red squiggly in foo.h: `In included file: 'stdlib.h' file not found.`

Sad times. But it gets stranger. That file is definitely there. You can `#include <cstdlib>` it just fine from foo.h, with no problems reported. Similarly, you can ctrl click through just fine, so all the files are there. And when you go into the (transitive) cstdlib file, there are no errors at all. stdlib.h is found just fine, though you see that it's in an `#include_next`.

## Scoping the problem
- The spurious error has something to do with include_next; modifying the standard library to change the problematic, transitive `#include_next <cstdlib>`s to `#include <cstdlib>` makes the problem go away. Similarly, directly including cstdlib from foo.h works fine.
  - The problem seems to be triggered by GCC, not clang. I reproduced it in a fresh Ubuntu VM, where basically all I'd done is get gcc with `sudo apt-get install build-essential`. I couldn't reproduce it with clang on my mac. The original bug report was with a different version of gcc, targeting Raspberry Pi Pico (arm) from Windows.
- Disabling --query-driver causes the error to go away.
  - The logs indicate that it was successful but missing C++ paths: 
```
/usr/bin/gcc -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include --target=x86_64-linux-gnu -x c++-header -resource-dir=<clang/14.0.3> -- <your directory>/foo.h
System includes extractor: successfully executed /usr/bin/gcc
	got includes: "/usr/lib/gcc/x86_64-linux-gnu/11/include, /usr/local/include, /usr/include/x86_64-linux-gnu, /usr/include"
	got target: "x86_64-linux-gnu"
```
- Things also resolve if you add a `-xc++` flag to the header command. (But no problems appear if you add -xc++-header to the source.)
  - This causes query driver to get the C++ paths. But it still replaces the `-xc++` with `-x c++-header`:
```
/usr/bin/gcc -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -isystem /usr/include/c++/11/backward -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include --target=x86_64-linux-gnu -x c++-header -resource-dir=<clangd_14.0.3/lib/clang/14.0.3> -- <your directory>/foo.h
System includes extractor: successfully executed /usr/bin/gcc
	got includes: "/usr/include/c++/11, /usr/include/x86_64-linux-gnu/c++/11, /usr/include/c++/11/backward, /usr/lib/gcc/x86_64-linux-gnu/11/include, /usr/local/include, /usr/include/x86_64-linux-gnu, /usr/include"
	got target: "x86_64-linux-gnu"
```
- Removing the CDB entry for the header also causes the error to go away, even though that means clangd is inferring from the same source command, since the source file has the same arguments. The logged command is `/usr/bin/gcc -x c++-header -resource-dir=<clangd_14.0.3/lib/clang/14.0.3> -- <your directory>/foo.h`
- Changing to a hpp extension causes the error to go away.
  - Query driver finds the same paths as with `-xc++`.
  - The logged command is the same as above, except that `-x c++-header` is not inferred: `/usr/bin/gcc -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -isystem /usr/include/c++/11/backward -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include --target=x86_64-linux-gnu -resource-dir=<clangd_14.0.3/lib/clang/14.0.3> -- <your directory>/foo.hpp`

Thanks for taking a peek!
Chris

[CC'ing @NomiChirps, the original reporter, and @HighCommander4 from the original issue, https://github.com/hedronvision/bazel-compile-commands-extractor/issues/70. Also @sam-mccall, because we're discussing something related to https://reviews.llvm.org/D116167.]

**Comment by HighCommander4** [comment]
Thanks for the comprehensive report and reduced testcase!

I can confirm that I'm seeing the same problem.

(In my case, what's extra fun is that my clang(d) is built with a `--with-gcc-toolchain` pointing to one gcc version (in my case, gcc 11), while my default `gcc` is gcc 8. Following `<iostream>` in `foo.cpp` goes to gcc 8's `<iostream>` (which is good, it means it's using the paths extracted from `gcc` via `--query-driver`), but following `<iostream>` in `foo.h` goes to gcc 11's `<iostream>` (suggesting it's falling back to clangd's defaults). This actually illustrates the problem nicely.)

I'll double-check tomorrow, but I suspect the root cause is the same as in https://github.com/clangd/clangd/issues/1173#issuecomment-1223595741: `QueryDriverDatabase` is looking at the `foo.h` command **before** `CommandMangler` adds `-x c++-header`, thinks it's a C header, and only queries the C headers from `gcc`.

**Comment by HighCommander4** [comment]
My tentative diagnosis above does seem to be consistent with the various symptoms reported:

 * Why it affects `#include_next`: the C file ends up with a combination of the queried gcc's C include paths and clangd's default C++ include paths. That's an unexpected order/combination of include paths, and `#include_next` relies on a particular order.
 * Why removing --query-driver fixes it: now we just use clangd's default paths consistently. Clangd's defaults are inserted by the clang driver code which runs after all clangd stuff, including `CommandMangler`, so the `-x c++-header` is present by then and the driver knows to include C++ paths.
 * Why adding `-xc++` to the command fixes it: now `QueryDriverDatabase` sees the `-xc++` and deduces the language as C++ correctly.
   * Likewise if the file extension is changed to `.hpp`.
 * Why removing the header's entry from the CDB fixes it: this one is the least obvious. Now, the filesystem-based heuristic described in https://github.com/clangd/clangd/issues/1173#issuecomment-1153489948 is used to choose `foo.cc` as a proxy, and that adds `-x c++`. This happens in `InterpolatingCompilationDatabase`, which runs before `QueryDriverDatabase`, so `QueryDriverDatabase` sees the `-x c++`.

**Comment by cpsauer** [comment]
Thanks so much for digging into these, @HighCommander4. I really appreciate you!

**Comment by cpsauer** [comment]
[Re gcc-toolchain: Sounds like you understand what's going on there much better than I, but thought I should cross-ref that clangd seems to choke on them when provided as a flag, in case that's useful or related: #1248.]

**Comment by HighCommander4** [comment]
> [Re gcc-toolchain: Sounds like you understand what's going on there much better than I, but thought I should cross-ref that clangd seems to choke on them when provided as a flag, in case that's useful or related: #1248.]

(I believe that's unrelated. I was referring to a flag used when building clang, to associate it with a default gcc toolchain whose standard library headers to use. `--with-gcc-toolchain` is actually the old name of the flag used by the clang's `autotools` build system which has since been removed; these days, it would be `-DGCC_INSTALL_PREFIX` for the cmake build.)

**Comment by HighCommander4** [comment]
Proposed patches:
https://reviews.llvm.org/D133756
https://reviews.llvm.org/D133757

They also fix #1089 and #1173

**Comment by cpsauer** [comment]
@HighCommander4, I booted up my test VM back up, grabbed the latest snapshot...and I can confirm it  fixes this one! Thank you, thank you, thank you!

[I'll test the other one shortly.]

**Comment by HighCommander4** [comment]
Yay!
