### ISSUE TITLE
Much More Memory & CPU usage under -std=c++20 and -std=c++2b compared with under -std=c++17

### ISSUE THREAD

**Issue by SiyangShao** [clangd/clangd#1264]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

When editing a file, and setting is -std=c++20 under config.yaml, clangd consumed lots of memory and CPU usage and stuck the computer. But when i change it to -std=c++17, everything works.

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`: clangd version 14.0.6. I've manually downgrade clangd to 14.0.5, but there still exist this problem  

Editor/LSP plugin: Appears on both VScode clangd and neovim clangd 

Operating system: Arch linux, run on 5.19.3-arch1-1

**Comment by sam-mccall** [comment]
This sounds plausible, but without an example that clearly shows the problem, it's not actionable.

There are many possible causes, I'd guess the most likely are:
 - libraries, particularly the standard library, may expose much more code behind `#ifdef`s in C++17 mode
 - clang itself may parse slower in c++20 mode.

These are things we're interested in and can help fix, but are not the code we're most familiar with. So it's unlikely we can make any progress without a reproducer.

If you want to try to isolate this, you can measure with `/bin/time -v clangd --check=$FILENAME` and look at the "user time" (CPU) "maximum resident set size"  (RAM).
