### ISSUE TITLE
.clangd/index directory conflict with .clangd file

### ISSUE THREAD

**Issue by ethereal14** [clangd/clangd#1267]
Hi！

clangd version:
```
clangd version 10.0.0-4ubuntu1~18.04.2 
```

this is error log:
```
V[00:15:34.374] Ignored diagnostic. unknown target CPU 'armv7-a'
``` 

for this issue #734 , I added a `.clangd` file in the linux kernel source directory. And this kernel for Arm device.

.clangd file content:
```
CompileFlags:
  Add: --target=armv7-a
```

the file tree like this, `Makefile` and `compile_commands.json` in the same directory
```
arch   certs    CREDITS  Documentation  firmware  include  ipc     Kconfig  lib       MAINTAINERS  Makefile  net     samples  security  tools  virt
block  COPYING  crypto   drivers        fs        init     Kbuild  kernel   LICENSES  make_deb.sh  mm        README  scripts  sound     usr
```

but when I rebuild index file , `.clangd` conflict with `.clangd/index` directory(in Linux environment file name can't be same as directory name), so I can't create index file

**Comment by HighCommander4** [comment]
As mentioned in https://clangd.llvm.org/config.html, support for the `.clangd` config file was added in clangd 11, and you're running clangd 10.

**Comment by ethereal14** [comment]
> 

Tanks，bro! Upgrage clangd can solve this problem
