### ISSUE TITLE
clangd cannot infer that a header file was included in another header file (JUCE)

### ISSUE THREAD

**Issue by ancientjpeg** [clangd/clangd#1268]
Hi! I've been using clangd both at work and in personal projects using JUCE. It's been great, but unfortunately I've encountered an issue that I haven't been able to remedy. In virtually all JUCE headers that contain class definitions, clangd seems to think that the macro `JUCE_API` is not a macro but actually the name of the class itself. I've attached an image of what I'm talking about:

<img width="563" alt="Screen Shot 2022-08-27 at 14 33 35" src="https://user-images.githubusercontent.com/65221904/187048800-0d297df0-2e23-4bbc-aea6-d043b45ddde5.png">

I've figured that the problem is that most juce headers don't actually have any `#include` statements — instead, they're all included in sequence in larger "module" files. I.e., `juce_String.h` and `juce_Time.h` are included inside a larger file `juce_core.h`, thus gaining access to definitions for macros like `JUCE_API`. 

However, I can't seem to find a way to get clangd to understand this file structure. At first I'd have thought it impossible, but I know that CLion is capable of resolving this frankly bizarre dependency chain, and that CLion makes heavy use of clangd under the hood. I'm not quite sure if this is a bug or a configuration error, but I'd deeply appreciate any help either way!

### System Info:

```
Homebrew clangd version 14.0.6
Features: mac+xpc
Platform: arm64-apple-darwin21.5.0
```

macOS Montery 12.4

via clangd VSCode Plugin

*edit:* compiling via CMake and using CMake's generated `compile_commands.json` to inform clangd.

**Comment by HighCommander4** [comment]
This is a known limitaton of clangd, please see #45.

> At first I'd have thought it impossible, but I know that CLion is capable of resolving this frankly bizarre dependency chain, and that CLion makes heavy use of clangd under the hood.

It's hard to say how CLion accomplishes this given that it's closed source. They may have patched clangd heavily, or rely on their own parser in some cases.

If you learn more details about how CLion handles this situation, please feel free to share them (e.g. in a [discussion thread](https://github.com/clangd/clangd/discussions)), as many clangd users are likely to be interested.

**Comment by ancientjpeg** [comment]
I'd be happy to, although I don't intend to use CLion regularly — I just gave it a shot to see if it was doing some sort of configuration trickery in order to get clangd to "see" the proper header inclusions. I assumed this was similar to the non-self-contained files issue, but I wanted to check and make sure I wasn't missing anything. Thank you so much for your response!
