### ISSUE TITLE
Searching for references of a variable finds its conversion operators instead

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#128]
Minimal repro:
```cpp
struct X {
  operator bool();
};

int test() {
  X a;
  X b;
  if (a || b) {}
}
```

Search for references on `if (^a || b)`.
Expected: all references of `a` are found (`X [[a]]` and `if ([[a]] || b)`).
Actual: references of `a` **and** `X::operator bool()` are found.

Real-world repro:
Open `ClangdMain.cpp` and search for references of `Test` inside an if statement, e.g. [here](https://github.com/llvm/llvm-project/blob/49661f94c8d07b0db9190261c47138b99a47546b/clang-tools-extra/clangd/tool/ClangdMain.cpp#L454).

Expected: references of `Test` are found
Actual: additionally, references of conversion operator are found, resulting in too many references being returned.

**Comment by hokein** [comment]
Fixed in upstream rL369514.
