### ISSUE TITLE
Enum name in `using enum` does not get a semantic token

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1283]
In the following C++20 code:

```c++
enum class Foo {Bar, Baz};

void test() {
  using enum Foo;
}
```

the `Foo` in `using enum Foo` does not get a semantic token

**Comment by sam-mccall** [comment]
This is a symptom of the AST being deficient here: there's no TypeLoc for Foo, and in the AST for `using enum a::Foo` there's no record of `a` at all. Seems worth fixing properly...

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D134303
