### ISSUE TITLE
std::variant not found (C++17)

### ISSUE THREAD

**Issue by renzobazan96** [clangd/clangd#1286]
I have the following code
``` cpp
#include <variant>

int main() {
  std::variant<int, float> v, w;
}
```

 I get warning the following error when I hover over std::variant 
**No member named 'variant' in namespace 'std'clang(no_member)**

I have set C++17 in my CMakeList.txt file and it builds successfully with colcon.

Screenshot:
![Screenshot from 2022-09-12 10-20-55](https://user-images.githubusercontent.com/82440252/189607225-32359adb-7e69-4069-9c7f-ed1b6ddec4bd.png)

**System information:**
Editor: VS Code/Clangd extension
Operating System: Ubuntu 22.04
Clangd version: 14.0.3

**Comment by Joker2387089590** [comment]
Have you set CMAKE_EXPORT_COMPILE_COMMANDS ON? If yes, can you post your compile_commands.json?

**Comment by renzobazan96** [comment]
Yes. I used CMAKE_EXPORT_COMPILE_COMMANDS ON, here is the compile_commands.json:
```json
[
{
  "directory": "/workspaces/test_ws/build/hello_world",
  "command": "/usr/bin/c++  -I/workspaces/test_ws/src/hello_world/include -O3 -DNDEBUG -Wall -Wextra -Wpedantic -o CMakeFiles/test1.dir/src/test1.cpp.o -c /workspaces/test_ws/src/hello_world/src/test1.cpp",
  "file": "/workspaces/test_ws/src/hello_world/src/test1.cpp"
}
]
```

**Comment by Joker2387089590** [comment]
There is no std flag in the command, you need to add 
```cmake
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
to your CMakeLists.txt

**Comment by renzobazan96** [comment]
The **set(CMAKE_CXX_STANDARD_REQUIRED ON)** solved the problem! Thanks!

**Comment by sam-mccall** [comment]
Pinning the required standard is the "safe" option here.

The reason you may expect this to work without -std is gcc now defaults to c++17. Clang has recently also been updated to do this, so clangd 16 will too.

I don't think there's anything more we can do here.
