### ISSUE TITLE
15.0.0 release?

### ISSUE THREAD

**Issue by stk-ableton** [clangd/clangd#1287]
The LLVM 15.0.0 release has been out for a week now, but the latest stable clangd release is still 14.0.3. There is a 15.0.0 release for clangd, but it is marked as Pre-release. This means that the VS Code extension doesn't auto-update to 15.

Just wondering if this is intentional, or if there was maybe some manual step that somebody forgot to do...

**Comment by kadircet** [comment]
yes this is intentional, we're testing out the release "manually" during our regular development to see there are no regressions that slipped away before shipping it to everyone. we'll probably send it to everyone before the end of the month if we don't encounter any big regressions

**Comment by sam-mccall** [comment]
I've marked the release as stable now, it seems to be good to go.

(Had to rebuild it - there was an accidental dynamic dependency on zstd, which could cause clangd to fail to start on machines without zstd.{so,dylib,dll}.)

**Comment by cpsauer** [comment]
Just wanted to say thank you for your guys' good care.

Cheers,
Chris

[I remember I had this question once upon a time, and smiled seeing this issue.]
