### ISSUE TITLE
Error checking __FUNCTION__ for MSVC

### ISSUE THREAD

**Issue by RimuruChan** [clangd/clangd#1297]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

![image](https://user-images.githubusercontent.com/42002296/190852935-2eb4b6e3-35f8-433a-b9ca-bb9e0a5ebf10.png)
In MSVC, the macro `__FUNCTION__` is a literal, so it is possible to splice it with other literal strings

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

```cpp
#include <string>
int main() {
    std::string test = "the function: " __FUNCTION__;
}
```

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:

```log
clangd version 14.0.6
Features: windows
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin:

Operating system:

Windows 11 22000.978

**Comment by sam-mccall** [comment]
That's right, `__FUNCTION__` is a nonstandard feature that is treated by MSVC as a macro and by clang+gcc as an alias for `__func__`. The macro usage is conceptually confusing (how could the preprocessor know what function we're in, let alone instantiation?).

We're not going to diverge from clang here: I'd suggest using __func__ in portable code. You can work around it by defining `-DFUNCTION="dummy"`, e.g. specifying this as a command-line flag to add in the clangd config file. (Be aware of escaping issues: you need the quotes to survive YAML unescaping)

**Comment by HighCommander4** [comment]
(`-D__FUNCTION__="dummy"` presumably)

**Comment by RimuruChan** [comment]
> (`-D__FUNCTION__="dummy"` presumably)

Awesome, thanks!

**Comment by RimuruChan** [comment]
> That's right, `__FUNCTION__` is a nonstandard feature that is treated by MSVC as a macro and by clang+gcc as an alias for `__func__`. The macro usage is conceptually confusing (how could the preprocessor know what function we're in, let alone instantiation?).
> 
> We're not going to diverge from clang here: I'd suggest using **func** in portable code. You can work around it by defining `-DFUNCTION="dummy"`, e.g. specifying this as a command-line flag to add in the clangd config file. (Be aware of escaping issues: you need the quotes to survive YAML unescaping)

Thanks!
