### ISSUE TITLE
[vscode client] Indicate that background indexing is in progress in the status bar

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#131]
The vscode client shows "clangd: parsing includes" in the status bar when a file is opened and parsed, but clangd also indexes the project in the background and there is no indication of this in the status bar. It would be nice to show this, as e.g the user may not want to run another resource-intensive operation until the indexing is complete.

**Comment by HighCommander4** [comment]
Even better if the status bar showed a percentage progress for indexing (that sounds like it depends on #22).

**Comment by hokein** [comment]
I think LSP's [progress](https://github.com/microsoft/language-server-protocol/issues/786) is a better fit for reporting background index progress.

**Comment by sam-mccall** [comment]
From tobiashieta on discord:
> one reason that people in my team prefer ccls over clangd is the ccls feedback when it's indexing the tree

I did hack up some part of progress support, I think we can do this reasonably. (I got frustrated because the protocol as standardized is pretty messy IMO, but the fundamental bits aren't that hard)

**Comment by hokein** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/7d20e80225b3e4f3f5a8c57929061bef55f3d855. 

This feature should be available in truck clangd with vscode-clangd 0.0.20.
