### ISSUE TITLE
parent directory (..) in compile_commands.json might prevent background indexing

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [clangd/clangd#1317]
### Failing case

`window.h` says:
```
inline void f() {}
```

window.cpp says:
```
#include "window.h"
int main() { f(); }
```

My files/directories are:
```
./window.cpp
./build/
./window.h
```
I ran:
```
cd build
bear -- clang++ ../window.cpp
```
build/compile_commands.json says:
```
[
  {
    "arguments": [
      "/usr/bin/ccache",
      "-c",
      "../window.cpp"
    ],
    "directory": "/home/bjacob/backup/C++/src/gui/build",
    "file": "/home/bjacob/backup/C++/src/gui/build/../window.cpp",
    "output": "/home/bjacob/backup/C++/src/gui/build/../window.o"
  }
]
```

I opened window.h, but I did not open window.cpp.

I tried to find references for function `f`, but found none.  I expected it to find the reference in the main function.  [clangd logs](https://pastebin.com/cV5gk6cZ) show that it found compile_commands.json but the logs show no attempt to background-index window.cpp.

### Workaround

Previously I ran `bear` in the `build` directory.  A workaround is to run `bear` in the same directory as window.cpp which requires I remove the `../` from the `bear` command:

```
cd ..
bear -- clang++ window.cpp
```
compile_commands.json says:
```
[
  {
    "arguments": [
      "/usr/bin/ccache",
      "-c",
      "window.cpp"
    ],
    "directory": "/home/bjacob/backup/C++/src/gui",
    "file": "/home/bjacob/backup/C++/src/gui/window.cpp",
    "output": "/home/bjacob/backup/C++/src/gui/window.o"
  }
]
```

I restarted my editor, which kills the clangd process.

I opened window.h, but I did not open window.cpp.

I tried to find references for `f`, and it found the call in main().  [clangd logs](https://pastebin.com/JN9c3T77) show it finding compile_commands.json in the same directory as window.cpp and it shows it doing a background index on window.cpp:

```
Indexing /home/bjacob/backup/C++/src/gui/window.cpp
```
### My theory for the cause:

In both the success and failure cases, clangd logs say it found compile_commands.json.  Therefore, in both cases, it should have background-indexed window.cpp.  I think the reason it did not index in the failure case is that the failure case produced `../` (pathname parent indicator) in the compile_commands.json.  Despite the different pathnames, the pathnames still ultimately refer to the same file.  I verified that by using the UNIX `ls` command to show that `ls` understands the alternate pathname format and finds the file:

```
$ ls -l /home/bjacob/backup/C++/src/gui/build/../window.cpp
-rw-r--r-- 1 bjacob bjacob 40 Sep 30 16:41 /home/bjacob/backup/C++/src/gui/build/../window.cpp
```

That `ls` command formats the pathname the same as in compile_commands.json.

Unlike `ls`, maybe clangd can't handle the alternate pathname syntax.

Another way that pathnames can be different but still refer to the same file is on case-insensitive filesystems and clangd used to have a [bug](https://github.com/clangd/clangd/issues/102#issuecomment-515081564) dealing with that, so maybe it also had a bug dealing with `../`

**System information**

Output of `clangd --version`:
```
clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: Emacs 27.1 / lsp-mode-7.0.1

Operating system: Debian GNU/Linux 11

**Comment by HighCommander4** [comment]
Does passing `--compile-commands-dir=/home/bjacob/backup/C++/src/gui/build` as a command-line argument to clangd (configured somewhere in your editor's preferences) make any difference?

**Comment by Jacob-Burckhardt** [comment]
Yes, that fixed it.  Thanks.

I often switch back and forth between multiple projects.  That means `--compile-commands-dir` would need to differ depending on which project I am working on.  It would be tedious to have to change the value of `--compile-commands-dir` whenever I switch projects.  My editor (Emacs) starts one clangd process for each project for which I have a file open.  Hopefully, my editor has a way to automate the command line options or the CLANGD_FLAGS environment variable before it starts a new clangd process so that I can customize `--compile-commands-dir` to work with that project.

Or maybe I will try to make my build system avoid using `../` in the source filenames.

Or maybe I will find some other workaround to handle multiple projects.

`clangd -h` says: 
> --compile-commands-dir=<string>     - Specify a path to look for compile_commands.json. If the path is invalid, clangd will look in the current directory and parent paths of each source file

I suggest that documentation be updated to say that the option also makes it more likely that clangd will successfully start indexing in the background.

Thanks.

**Comment by HighCommander4** [comment]
I agree that there is a bug here and using `--compile-commands-dir` is more just a workaround rather than the intended solution.

The fact that this workaround works makes me suspect that the bug is in clangd's logic of figuring out which files are "governed" by which compilation databases. Possibly there's a step in there that should canonicalize paths (e.g. remove `../foo`) but doesn't.

**Comment by kadircet** [comment]
sent out https://reviews.llvm.org/D137962
