### ISSUE TITLE
Grey out code in inactive preprocessor branches

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#132]
Eclipse CDT and cquery have a neat feature where code in an inactive preprocessor branch is greyed out. This makes it more readily apparent when you're looking at code in an inactive preprocessor branch (right now, the only clue is the lack of semantic highlighting, which is more subtle).

There is no dedicated LSP protocol for this, so we'd have to make up an extension (that's what cquery does). We could then propose the extension for standardization.

**Comment by kadircet** [comment]
or we could just use semantic highlighting and give a different color to
whole range?

**Comment by HighCommander4** [comment]
Yes, this is a possibility. In fact, on the client side, cquery uses the same API as semantic highlighting (`setDecorations()`) to style the code.

However, the style for inactive code is applied to the background, while the style for semantic highlighting is applied to the foreground, so I don't know how much sharing between the two mechanisms makes sense.

I would also like, in the future, to apply semantic highlighting to inactive code as well, in which case the foreground decorations for semantic highlighting can be merged with the background decorations for inactive code.

**Comment by mellery451** [comment]
Is this feature is still TBD or perhaps does any of the recent semantic highlighting work cover this?

**Comment by HighCommander4** [comment]
> Is this feature is still TBD or perhaps does any of the recent semantic highlighting work cover this?

The old semantic highlighting protocol has support for in in clangd, but there is no corresponding client-side support. I did write a [vscode implementation](https://reviews.llvm.org/D67537) which I use locally, but review of that has stalled.

I should probably focus my efforts on getting it to work with the new protocol.

**Comment by hokein** [comment]
After https://reviews.llvm.org/D85635, I think it already works in VSCode with the new SemanticTokens protocol (https://github.com/clangd/vscode-clangd/pull/54/files).

**Comment by Trass3r** [comment]
It does starting with clangd-12 but the semantic token type is set to comment which is sub-optimal.

**Comment by gpoirierhub** [comment]
I see that this feature has been enabled in clangd-12. There are cases where it is nice to have semantic highlighting "on" for inactive preprocessor branches. Is there a way to have clangd-12 do semantic highlighting on inactive preprocessor branches?

**Comment by HighCommander4** [comment]
> Is there a way to have clangd-12 do semantic highlighting on inactive preprocessor branches?

Not really. Semantic highlighting is based on the AST, and clang does not build an AST for inactive preprocessor branches, it's just token soup.

Providing semantic highlighting for the inactive branches would require something like re-parsing the file with different sets of flags (so that each region is active in at least one parse), and then merging the tokens; this is likely to be prohibitively expensive.

> IE: A way to switch off this new feature?

Note that clangd would not provide semantic highlightings for inactive branches in older versions, either. If you saw any highlighting there at all, it would have been your client's lexical highlighting (e.g. vscode's TextMate rules).

**Comment by gpoirierhub** [comment]
I see. Thank you for the reply.

"If you saw any highlighting there at all, it would have been your client's lexical highlighting (e.g. vscode's TextMate rules)."

This is consistant with what I'm seeing. When I open a file, every line of code is highlighted but 1 sec later the inactive preprocessor branch code highlighting switches to comment style highlighting. Is there a way to have clangd-12 somehow not enforce it's inactive preprocessor branch highlighting so vscode's highlighting can persist for these lines of code? If that is not possible, is there a way to swtich off clangd-12's lexical highlighting entirely (while keeping everything else that clangd provides)?

**Comment by Trass3r** [comment]
There's clangd/vscode-clangd#193 and microsoft/vscode#123352 and there's also a setting for semantic highlighting.

**Comment by HighCommander4** [comment]
You raise an interesting point: in https://github.com/clangd/vscode-clangd/pull/193 I implement an enhancement where the inactive regions get a grey background styling instead. However, they still have a (darker) grey foreground as well. I wonder if, instead, I could keep the grey background but omit a foreground style altogether, and that might result in the client-side foreground colors being retained (and combined with the grey background). That would be a nice improvement.

**Comment by kadircet** [comment]
Closing this as there's little we can do on the server-side. We can either wait for LSP to have a dedicated token kind for inactive/dead code (microsoft/vscode#123352) or start providing a custom one in clangd. As mentioned above the latter is not preferred and won't really solve the solution for clients that don't implement this extension. The former we can pick up, as soon as its available though.

For the vscode-clangd though, there's a discussion in https://github.com/clangd/vscode-clangd/issues/85 and patch @HighCommander4 prepared at clangd/vscode-clangd#193. Feel free to chime in there (and hopefully we'll get to the patch soon).

**Comment by HighCommander4** [comment]
In case anyone following this old issue has missed it: in https://reviews.llvm.org/D143974 (to appear in clangd 17), clangd has gained support for a custom protocol extension for inactive regions, with client-side support in vscode added in https://github.com/clangd/vscode-clangd/pull/193.

Unlike the previous approaches, this one has the flexibility that it allows clients to style inactive regions in a way that combines with client-side highlighting (for example, in vscode, the inactive regions have either a reduced opacity or a modified background color, while retaining the foreground colors from the client-side TextMate tokens).

If the maintainers of any other clients are interested in implementing this protocol extension (and/or providing feedback on it), that would be welcome.

**Comment by fargiolas** [comment]
> If the maintainers of any other clients are interested in implementing this protocol extension (and/or providing feedback on it), that would be welcome.

Thanks for pushing this into clangd!
I'm working on a little emacs package supports inactiveRegions notifications using eglot (emacs built-in mode for language server support). It's still mostly an experiment but if anyone's interested you can check it out  [here](https://github.com/fargiolas/clangd-inactive-regions). Feedback welcome!

Seems a really useful extension, any idea if this is ever going to enter the official LSP protocol?

**Comment by HighCommander4** [comment]
> any idea if this is ever going to enter the official LSP protocol?

I'd like to gather a bit more usage experience with the protocol (it's yet to appear in a vscode-clangd release, though hopefully it will soon per https://github.com/clangd/vscode-clangd/pull/516), and then propose it as an addition to LSP.
