### ISSUE TITLE
Symbol `boost::asio::awaitable` not found although it exists

### ISSUE THREAD

**Issue by raldone01** [clangd/clangd#1328]
**Source code**
```cpp
#include <boost/asio.hpp>
#include <coroutine>
#include <iostream>
namespace asio = boost::asio;

boost::asio::awaitable<void> myfun(asio::io_context &io, std::string msg,
                                   boost::posix_time::seconds secs) {
  asio::deadline_timer t(io, secs);
  try {
    while (true) {
      co_await t.async_wait(asio::use_awaitable);
      t.expires_from_now(secs);
      std::cout << "msg " << msg << " "
                << std::hash<std::thread::id>{}(std::this_thread::get_id())
                << std::endl;
    }
  } catch (std::exception &e) {
    std::printf("echo Exception: %s\n", e.what());
  }
}

int main() {
  boost::asio::io_context io;
  boost::asio::co_spawn(io, myfun(io, "co1", boost::posix_time::seconds(5)),
                        boost::asio::detached);
  boost::asio::co_spawn(io, myfun(io, "co2", boost::posix_time::seconds(2)),
                        boost::asio::detached);
  std::cout << "Hello World! "
            << std::hash<std::thread::id>{}(std::this_thread::get_id())
            << std::endl;
  io.run();
  return 0;
}
```

Compiles and runs on gcc `12.2.0`.

**Errors**
```json
[{
	"resource": "/home/main/Desktop/BoostAwaitErrorClionBug/main.cpp",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "no_member_template",
	"severity": 8,
	"message": "No template named 'awaitable' in namespace 'boost::asio'",
	"source": "clang",
	"startLineNumber": 6,
	"startColumn": 14,
	"endLineNumber": 6,
	"endColumn": 23
},{
	"resource": "/home/main/Desktop/BoostAwaitErrorClionBug/main.cpp",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "implied_std_coroutine_traits_promise_type_not_found",
	"severity": 8,
	"message": "This function cannot be a coroutine: 'std::coroutine_traits<int, boost::asio::io_context &, std::basic_string<char>, boost::posix_time::seconds>' has no member named 'promise_type'",
	"source": "clang",
	"startLineNumber": 6,
	"startColumn": 30,
	"endLineNumber": 6,
	"endColumn": 35
},{
	"resource": "/home/main/Desktop/BoostAwaitErrorClionBug/main.cpp",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "no_member",
	"severity": 8,
	"message": "No member named 'use_awaitable' in namespace 'boost::asio'",
	"source": "clang",
	"startLineNumber": 11,
	"startColumn": 35,
	"endLineNumber": 11,
	"endColumn": 48
},{
	"resource": "/home/main/Desktop/BoostAwaitErrorClionBug/main.cpp",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "no_member",
	"severity": 8,
	"message": "No member named 'co_spawn' in namespace 'boost::asio'",
	"source": "clang",
	"startLineNumber": 24,
	"startColumn": 16,
	"endLineNumber": 24,
	"endColumn": 24
},{
	"resource": "/home/main/Desktop/BoostAwaitErrorClionBug/main.cpp",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "no_member",
	"severity": 8,
	"message": "No member named 'co_spawn' in namespace 'boost::asio'",
	"source": "clang",
	"startLineNumber": 26,
	"startColumn": 16,
	"endLineNumber": 26,
	"endColumn": 24
}]
```

Repository to reproduce: https://github.com/raldone01/BoostAwaitErrorClionBug

**Logs**
 
Could not see any obvious errors in the log.

**System information**

Output of `clangd --version`:

```
clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: `vscode-clangd`

Operating system: `Linux 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux`

**Comment by HighCommander4** [comment]
I can reproduce by cloning the repo and running `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .`.

If I open `compile_commands.json`, copy the command for main.cpp's entry and run it in the terminal, I get the same errors.

This suggests the issue is not with clangd, but with cmake generating an incorrect `compile_commands.json`.

A potential next diagnostic step would be to compare the compile command run during the actual build with the one in `compile_commands.json` and see what is missing/different in the latter.

**Comment by raldone01** [comment]
Thank you for reproducing and providing insights in how the `compile_commands.json` are generated.
I will try your suggestion as soon as possible.
If it really is a cmake issue I will take my issue to them. 😉

**Comment by HighCommander4** [comment]
Slight correction: the compile in `compile_commands.json` uses `/usr/bin/c++` as the driver, so I guess the behaviour depends on what that resolves to.

If I replace `/use/bin/c++` with `g++`, it does indeed compile, but if I replace it with `clang++` I get the errors.

So, rather than the issue being with cmake, I think the issue is that the code is not portable between gcc and clang. My guess is, likely related to the state of coroutine support in the two compilers?

**Comment by raldone01** [comment]
Does clangd aim to support both compilers?

**Comment by HighCommander4** [comment]
clangd uses clang's internals to understand the code, so the code needs to be accepted by clang.

Chances are there's a simple workaround to get clang to accept this code. I can't investigate further at the moment, but now that we've reduced the problem to "how to get this coroutine example to compile with clang?", you can probably get help with that in non-clangd-specific forums like StackOverflow or the LLVM Discourse :)

**Comment by raldone01** [comment]
So to use clangd I should make sure my code compiles with clang. Makes sense.
Should I not use clangd if I use gcc internals?
Do you know how clangd handles these?

> ..., you can probably get help with that in non-clangd-specific forums like StackOverflow or the LLVM Discourse or the Boost mailing lists :)

I will try my luck on stackoverflow later. Thank you for your input.

**Comment by HighCommander4** [comment]
> Should I not use clangd if I use gcc internals? Do you know how clangd handles these?

By "internals" I mean that clangd uses clang's parser to parse C++ code for the purpose of providing its language server features. So, if e.g. there is a new language feature that clang's parser does not yet support, then clangd will likewise not work for that feature.

**Comment by HighCommander4** [comment]
I looked into the `No template named 'awaitable' in namespace 'boost::asio'` error a little.

The definition of `boost::asio::awaitable` is [gated](https://github.com/boostorg/asio/blob/0af7858e7b5603a2415a30b69e16c7ef1d47a5e9/include/boost/asio/use_awaitable.hpp#L20) on the macro `BOOST_ASIO_HAS_CO_AWAIT`. That macro is in turn defined by compiler-specific feature-detection logic [here](https://github.com/boostorg/asio/blob/0af7858e7b5603a2415a30b69e16c7ef1d47a5e9/include/boost/asio/detail/config.hpp#L2045-L2070).

The [clang portion](https://github.com/boostorg/asio/blob/0af7858e7b5603a2415a30b69e16c7ef1d47a5e9/include/boost/asio/detail/config.hpp#L2056-L2062) of that logic only checks for the presence of the `<experimental/coroutine>` header, not the standard `<coroutine>` one. However, newer clang versions provide `<coroutine>` and have stopped providing `<experimental/coroutine>`.

So, I think Boost Asio needs to update its feature detection logic to check for `<coroutine>` for clang as well; consider filing a [Boost Asio issue](https://github.com/boostorg/asio/issues) about that.

**Comment by HighCommander4** [comment]
(If you found a different solution or workaround, please feel free to mention it here in case future users find this issue.)

**Comment by raldone01** [comment]
Yes actually the boost asio header detection is faulty. https://github.com/boostorg/asio/pull/395

**Comment by mkckr0** [comment]
I have a temporary solution that just add `#define BOOST_ASIO_HAS_CO_AWAIT` before `#include <boost/asio.hpp>` to enforce asio to enable coroutine.
