### ISSUE TITLE
Structured binding variables do not get a highlighting

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#133]
In the following code:

```
struct S {
    int k;
    int v;
};

int foo() {
    auto [key, value] = S();
    return key + value;
}
```

the declarations and references of the structured binding variables `key` and `value` do not get a highlighting.

I would expect them to get a highlighting of type `HighlightingKind::Variable`.

**Comment by puremourning** [comment]
structured bindings don't introduce variables, right, only "names" (e.g. you can't capture them in a lambda). Not sure if that's relevant, but it is a (perhaps) surprising quirk of the standard.

**Comment by HighCommander4** [comment]
cc @jvikstrom

**Comment by HighCommander4** [comment]
> structured bindings don't introduce variables, right, only "names" (e.g. you can't capture them in a lambda). Not sure if that's relevant, but it is a (perhaps surprising) quirk of the standard.

That's technically true, but I don't think the distinction is relevant to the user, and certainly not a reason to leave them uncoloured. (It could conceivably be a reason to give them their own highlighting kind, but I'm not sure how much there is to gain from that.)

**Comment by hokein** [comment]
Fixed in rL370473.
