### ISSUE TITLE
Extract to function and Extract to variable don't work on plain C files.

### ISSUE THREAD

**Issue by enesaltinkaya** [clangd/clangd#1332]
I'm using Vscode with Clangd extension on Linux.
Clangd version installed is 14.0.6-2.

If i rename the file to .cpp extract features work.
Is this expected?

Thanks.

**Comment by tom-anders** [comment]
Looks like it was intentionally disabled since it uses `auto`: https://reviews.llvm.org/D85727

**Comment by enesaltinkaya** [comment]
Thanks.
What a shame.
