### ISSUE TITLE
Slow semantic highlighting request

### ISSUE THREAD

**Issue by timxx** [clangd/clangd#1346]
Take `ClangdLSPServer.cpp` for example, on my computer it takes 4 seconds to finished:
```
V[20:54:59.557] <<< {"id":188,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///d%3A/Projects/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.cpp"}}}

I[20:54:59.557] <-- textDocument/semanticTokens/full(188)

V[20:55:03.197] Build dynamic index for header symbols with estimated memory usage of 33400296 bytes
V[20:55:03.229] Built preamble of size 44301400 for file d:\Projects\llvm-project\clang-tools-extra\clangd\ClangdLSPServer.cpp version 1
I[20:55:03.231] --> workspace/semanticTokens/refresh(12)
I[20:55:03.231] --> textDocument/clangd.fileStatus
V[20:55:03.231] >>> {"id":12,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}


V[20:55:03.952] ASTWorker running SemanticHighlights on version 1 of d:\Projects\llvm-project\clang-tools-extra\clangd\ClangdLSPServer.cpp
[Error - 20:55:03] Request textDocument/documentSymbol failed.
[object Object]
I[20:55:03.958] --> reply:textDocument/semanticTokens/full(188) 4401 ms
```

Even if `ClangdLSPServer.cpp` already indexed. It seems that clangd will not use the index file first.

```C++
void ClangdServer::semanticHighlights(
    PathRef File, Callback<std::vector<HighlightingToken>> CB) {
  auto Action =
      [CB = std::move(CB)](llvm::Expected<InputsAndAST> InpAST) mutable {
        if (!InpAST)
          return CB(InpAST.takeError());
        CB(clangd::getSemanticHighlightings(InpAST->AST));
      };
  WorkScheduler->runWithAST("SemanticHighlights", File, std::move(Action),
                            Transient);
}
```

Is it possible to use the index first and then `build` the ast (and then notify client that a refresh is required)?
I think most of the time the index should contains the correct symbols, it's too slow to build ast every time.

All other ast related request seems has the same problem as clangd always rebuild the ast.

**System information**

Output of `clangd --version`:
14.0.6

Editor/LSP plugin:
VS Code

Operating system:
Windows 11

**Comment by sam-mccall** [comment]
Are you saying it takes 4 seconds every time you edit the file, or just when you open it?

**Comment by timxx** [comment]
Every time open. Edit performance seems fine.
Most of the big file takes more than 4 seconds in our project.

**Comment by sam-mccall** [comment]
This is the expected performance. Files are parsed when opened, and incrementally parsed when edited. The index does not store semantic highlight information.

**Comment by AstroWYH** [comment]
> This is the expected performance. Files are parsed when opened, and incrementally parsed when edited. The index does not store semantic highlight information.这是预期的性能。文件在打开时解析，在编辑时增量解析。索引不存储语义高亮信息。

https://github.com/clangd/clangd/issues/2355 
It bothers me for a long time, could you watch my issue plz. I want to know what are the things in the index, and how can I increase the speed of clangd to parse one cpp file. I don't care the hard disk usage, all I care about is speed.
