### ISSUE TITLE
False accusation of unused variable

### ISSUE THREAD

**Issue by LuxElx** [clangd/clangd#1347]
![image](https://user-images.githubusercontent.com/116464156/197369993-e18530c8-f4ee-4620-bc60-b786eddb1000.png)
processor is called as a function since its a lambda, but clangd doesnt know that

**Comment by HighCommander4** [comment]
Could you provide a complete example please? It's not even clear what the diagnostic in question is here.

**Comment by LuxElx** [comment]
![image](https://user-images.githubusercontent.com/116464156/197407338-ae6d8a94-b87f-4a24-bcd5-2252d9854bd9.png)

**Comment by sam-mccall** [comment]
Sorry, screenshots aren't a useful way to report bugs in code, and this diagnostic isn't even from clangd.

**Comment by LuxElx** [comment]
Ok so it turns out, processor was declared as a variable, and not function, i needed to do const auto &processor()
as stated by @AndrewDisco
