### ISSUE TITLE
Use '.' to trigger completion for struct pointers

### ISSUE THREAD

**Issue by BIKA-C** [clangd/clangd#1349]
It would be nice to have '.' as a trigger to struct fields completion just like ccls

For example, 
```c
struct e {
    int key;
    int val;
};

struct e *a;;
```
Now, if I type
```c
a.
```
I should be able to have the code completion showing me the 2 fields

**Comment by BIKA-C** [comment]
Just realized that clangd has sent the completion but the client did not display

**Comment by sam-mccall** [comment]
Right for dot-to-arrow and arrow-to-dot completion, clients often end up filtering these out as the inserted text  doesn't match what the client thinks the query is :-(
