### ISSUE TITLE
DOOM Emacs Cant rid `Unknown argument '-mlongcalls'; did you mean '-mlong-calls'? (lsp)`

### ISSUE THREAD

**Issue by ntn888** [clangd/clangd#1354]
contents of ~/.config/clangd/config.yaml:
```
CompileFlags:
    Remove: ['-fno-reorder-functions']
    Remove: ['-mlongcalls']
```

the first remove works fine, but the '-mlongcalls' does no effect?

**System information**

Output of `clangd --version`: Debian clangd version 11.0.1-2

Editor/LSP plugin: DOOM Emacs/lsp

Operating system: Debian 11

**Comment by HighCommander4** [comment]
Try

```
CompileFlags:
    Remove: ['-fno-reorder-functions', '-mlongcalls']
```

In vscode, if I open the `.clangd` file in the editor, clangd does produce a "Duplicate key `Remove` is ignored" diagnostic -- not sure how well this works with other editors.

**Comment by ntn888** [comment]
that did it. thanks so much!
