### ISSUE TITLE
No type named 'scoped_lock' in namespace 'std'

### ISSUE THREAD

**Issue by LukeOrgana** [clangd/clangd#1359]
I am using clangd 15.0.3 via coc.nvim coc-clangd to provide autocompletion for C++in Neovim, running on Ubuntu 20.04 LTS. I am writing some multithreaded code and trying to use std::scoped_lock. However, this is flagged as an error in my code, saying that there is "No type named 'scoped_lock' in namespace 'std'". In my .clangd file I include the `-std=c++17` flag, and when I actually compile the code using gcc, again with the `-std=c++17`, it compiles fine so I'm fairly confident its not me making a silly mistake in my code. 

I'm not sure if this could be a bug in clangd or coc-clangd, or maybe I am doing wrong.

**Comment by HighCommander4** [comment]
Can you attach [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) please?

**Comment by kadircet** [comment]
closing this as this requires additional information to act on our side. feel free to re-open if you can attach logs or provide a reproducer.
