### ISSUE TITLE
Clangd shows errors when opening a standard library implementation header

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#136]
Steps to reproduce:

  1. Use clangd in a configuration where the standard library is libstdc++. (It's possible the issue also occurs with libc++, but I don't have it around to test.)
  2. Perform go-to-definition on an `#include <memory>` in a source file.
  3. Inside `<memory>`, perform another go-to-definition on `#include <bits/shared_ptr.h>`
  4. Observe that clangd shows a bunch of errors inside `<bits/shared_ptr.h>`, such as `No template named 'basic_ostream' in namespace 'std'`

I think the error is related to the fact that `<bits/shared_ptr.h>` is not a "standalone" header, that is, it expects some of its dependencies to be included by `<memory>` rather than including them itself.

It would be nice if this worked, as users sometimes have to dig through standard library code to understand compiler errors.

**Comment by kadircet** [comment]
This is same as #45.
