### ISSUE TITLE
clangd-9 not found in clang-tools-9 apt package

### ISSUE THREAD

**Issue by m5ome** [clangd/clangd#138]

**Comment by sam-mccall** [comment]
This has moved to a separate package, it should be available as `clangd-9`.

@sylvestre: should any of {`clang-tools`, `clang-tools-9`, a new `clangd`} have a dep on `clangd-9`?
I don't understand the version-marked packages very well, but I guess users are typically expected to install $package rather than $package-version.

**Comment by sylvestre** [comment]
@sam-mccall maybe? :)
I don't have a strong opinion on this. I like when packages don't install too many things.

If you have a strong feeling, please let me know and I will add a dep: clang-tools => clangd

**Comment by m5ome** [comment]
@sam-mccall yep, exists as clangd-9. Thanks!

**Comment by sam-mccall** [comment]
@sylvestre Agreed about not installing too many things, let's not add the dep. Recommends might make sense, but probably isn't necessary.

The `clangd` package itself doesn't exist. (unlike say `clang-tools` which just has a dep on `clang-tools-8`). Is this a pain to add? It'd be nice if `apt install clangd` did the right thing.

While I was looking at the packages: I believe `clangd-9` is missing a dep on `libclang-common-9-dev` for clang's builtin headers. Do you mind adding that?
When it was part of `clang-tools-N` it got this via a dep on `clang-N`, which works but is overkill I think.

(Sorry for the scattershot of questions here; please let me know what the better forum is!)

**Comment by sylvestre** [comment]
Sure, could you please open bugs in https://bugs.llvm.org/enter_bug.cgi?product=Packaging to make sure that they aren't lost? thanks

**Comment by sam-mccall** [comment]
Done, thanks a lot!

https://bugs.llvm.org/show_bug.cgi?id=43152 for the missing dep

https://bugs.llvm.org/show_bug.cgi?id=43153 for a generic clangd package.
