### ISSUE TITLE
"-std:c++latest" can-not be identified

### ISSUE THREAD

**Issue by MaxwellGengYF** [clangd/clangd#1383]
"-std:c++latest" in compile_commands.json can-not be identified by clangd, however "-std:c++20" is identified well.

Editor/LSP plugin:
coc-nvim with clangd
vscode with clangd
Operating system:
Windows 10

**Comment by inclyc** [comment]
Link: https://github.com/clangd/clangd/issues/527

**Comment by HighCommander4** [comment]
> Link: #527

Thanks, closing as duplicate.
