### ISSUE TITLE
code action: offer to create method when encountering an undeclared identifier

### ISSUE THREAD

**Issue by rwols** [clangd/clangd#1386]
IntelliJ has this nice feature where you can just write a method invocation and it'll offer to create the method with the correct signature if that method doesn't exist yet. I would like to have the same functionality in clangd.

```
// Foo.h
struct Foo {
  void doFooThings();
}

// Foo.cpp
void Foo::doFooThings() {
  int x = 0;
  int y = 0;
  bar(x, y); // ERROR: undeclared identifier 'bar' --> offer to create method "bar" with signature void(int, int)
}

```

I'm unsure what the access modifier should be though. Maybe keep it private by default for classes and public by default for structs? Or offer three alternative code actions instead for public, protected, private.

**Comment by HighCommander4** [comment]
Sounds like a special case of #467 ("create from usage")

**Comment by rwols** [comment]
Yep, didn’t see that one.
