### ISSUE TITLE
Emacs - clangd - Filesystem

### ISSUE THREAD

**Issue by centuryx476** [clangd/clangd#1388]
Please describe the problem.
I am using Doom Emacs with clangd as my C++ lsp. The header library <filesystem> and that is being accepted. But when I try to use the library I get the below error in the screenshot.
Not sure what I am doing wrong or if their is a deeper reason for this error.

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
![image](https://user-images.githubusercontent.com/38863757/202972113-626f3e7a-8469-4f72-be2e-b9d829208d45.png)

**Logs**
no member named 'filesystem' in namespace 'std'

**System information**

Output of `clangd --version`: 15.0.3

Editor/LSP plugin: Doom Emacs

Operating system: Windows 10 Pro

**Comment by HighCommander4** [comment]
Please review https://clangd.llvm.org/installation#project-setup

If you believe the project is correctly configured (in this case, the relevant things would be (1) that it has a `compile_commands.json` or `compile_flags.txt`, and (2) that the command or flags includes `-std=c++17` or a higher version) and it's still not working, please attach [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs).

**Comment by centuryx476** [comment]
It was the compile_commands.json was missing the C++ standard setting. Once I changed it to C++17 the missing std::namespace disappeared.
Thank You
