### ISSUE TITLE
Unable to find system headers when using arm-none-eabi-g++

### ISSUE THREAD

**Issue by daantimmer** [clangd/clangd#1398]
clangd is unable to find _any_ system header when my compiler is set to arm-none-eabi-g++
It seems to be able to infer that my compiler is a variant `g++`, but unable to find the (c++) headers, like `<algorithm>`.

If I change the order of the includes (currently alphabetical), then clangd will complain about the very first system header it encounters. (not necessarily c++ headers, `stdlib.h` can also not be found for example.

**Logs**
[clangd-server-output-opening-a-MemoryRange.hpp-file-with-verbose-logging.txt](https://github.com/clangd/clangd/files/10102932/clangd-server-output-opening-a-MemoryRange.hpp-file-with-verbose-logging.txt)

[clangd-server-output-hovering-algorithm-include-file-with-verbose-logging.txt](https://github.com/clangd/clangd/files/10102939/clangd-server-output-hovering-algorithm-include-file-with-verbose-logging.txt)

**System information**

Output of `clangd --version`:
> clangd --version
> Ubuntu clangd version 14.0.6
> Features: linux+grpc
> Platform: x86_64-pc-linux-gnu

Editor/LSP plugin:
> Visual Studio Code: v1.73.1 (user setup)
> clangd extension: v0.1.23

Operating system:
> Windows: 10 host
> Ubuntu: 22.04 container
> arm-none-eabi toolchain: 10.3-2021.10

**Comment by HighCommander4** [comment]
Are you using `--query-driver` as described in https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc? (The logs you posted don't include the part where clangd prints its arguments on startup so I can't tell.)

It's usually needed in cross-compilation scenarios such as when using an ARM toolchain.

**Comment by daantimmer** [comment]
I did not. However I fear this won't be able to help me. The top level
cmake, and root of the project is the single entry point to compile with
clang (mutation testing and fuzzing) GCC (for unit tests) and
arm-none-eabi-gcc (for cross-compiling).

I can only set a single value for the whole project (vscode settings) and
on directory level there is no difference.

**Comment by HighCommander4** [comment]
The description of `--query-driver` in `clangd --help` is:

```
--query-driver=<string>  - Comma separated list of globs for white-listing gcc-compatible drivers that
                           are safe to execute. Drivers matching any of these globs will be used to
                           extract system includes. e.g. /usr/bin/**/clang-*,/path/to/repo/**/g++-*
```

The actual driver that is executed to extract system includes is the argv[0] of the compile command from `compile_commands.json`.

So, if your project contains a mix of files compiled with arm-none-eabi-gcc and other compilers, you can use multiple entries and/or globs in `--query-driver` to whitelist them all.

**Comment by daantimmer** [comment]
Right, this indeed solved the issue. To be honest, not as straight forward as I expected it to work. Anyway, for anyone ever stumbling upon this issue I resolved it by adding 
```json
    "clangd.arguments": [
        "--query-driver=/**/arm-none-eabi-*"
    ]
```
to my settings.json
