### ISSUE TITLE
Display macro document when hovering 

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#140]
Hover on macro.
![image](https://user-images.githubusercontent.com/10697249/60969339-e0c20180-a351-11e9-8d6a-56ec6ab63e32.png)

_Originally posted by @lh123 in https://github.com/clangd/clangd/issues/74#issuecomment-510041697_

**Comment by Trass3r** [comment]
#779

**Comment by kadircet** [comment]
this is https://github.com/llvm/llvm-project/issues/38206.
