### ISSUE TITLE
Resolve references using the primary template (or current specialization?)

### ISSUE THREAD

**Issue by abbaswasim** [clangd/clangd#141]
I have been trying to figure out why `lsp-mode` using `clangd` in emacs couldn't find references in a single header file with and without `background-index`

Here is a reproducer project [lsp-clangd-test.zip](https://github.com/clangd/clangd/files/3561654/lsp-clangd-test.zip)

If you try to find references to `add_child` on line `84` in `graph.hpp` you will find some but not all references, same for line `80`. On line `78` however there are no references. I have created an `lsp-mode` bug (https://github.com/emacs-lsp/lsp-mode/issues/990) but the guys over there are very confident its in `clangd` not `lsp-mode`. I haven't managed to confirm this though. I don't know a way to test `clangd` in isolation.

EDIT: I have now confirmed this is `clangd` related. Please have a look at the `lit` test [references2.test](https://github.com/clangd/clangd/files/3563707/references2.test.txt) for `graph.hpp` attached. Also confirmed in Xcode 10.3.

EDIT2: Also tested it has something to do with Templates as well.

```
$ clangd --version
clangd version 8.0.1 (tags/RELEASE_801/final)
```
OS
```
macOs Mojave 10.14.6 (18G95)
Manjaro (Arch Linux)
```

**Comment by hokein** [comment]
Thanks for the detailed report.

Yes, this is a bug of clangd, reduced to a small testcase:

```cpp
template<class T>
class Foo {
 public:
  void foo() {
    this->f^oo(); // go-to-def, find references are not working.
  }
};

```

**Comment by abbaswasim** [comment]
What is the process of resolving these bugs. How can we get more visibility?

 I know `llvm` is not hosted on github so does it mean all these bugs are getting resolved somewhere and will magically all close down once next version `llvm` and `clangd` comes out?

Reading the llvm project instructions I managed to create a pull request https://reviews.llvm.org/D67025 but there doesn't seem to be any activity on that either. What am I missing?

**Comment by kadircet** [comment]
> What is the process of resolving these bugs. How can we get more visibility?

there's no great way to get more visibility currently, you can try registering for notifications on changes that mention clangd with something similar to: https://reviews.llvm.org/H378

> I know llvm is not hosted on github so does it mean all these bugs are getting resolved somewhere and will magically all close down once next version llvm and clangd comes out?

We tend to mark these bugs as fixed as soon as a patch lands into the tree, without waiting for the next release.


> Reading the llvm project instructions I managed to create a pull request https://reviews.llvm.org/D67025 but there doesn't seem to be any activity on that either. What am I missing?

you might need to find different reviewers or try pinging them, reviewers for such files receive a lot of requests and things might go unnoticed from time to time unfortunately.

**Comment by sam-mccall** [comment]
Regarding the original bug: clang thinks the access to `foo` is dependent here, the cursor is over a `DependentScopeMemberExpr` here.

The general case is something like:
`template <typename T> int zero = std::vector<T>.s^ize()`

Formally, we don't know what size() is, as it may be defined in a specialization (e.g. if `T = bool`). But in practice, we'd like go-to-definition to use the primary template here.

This would be a change in behavior for `targetDecl`, maybe that API should flag such references with `PrimaryTemplate` or a new flag `Probable` or similar.
I believe libIndex traverses the primary template trying to find a decl with the right name - we should probably emulate that.
https://github.com/llvm-mirror/clang/blob/master/lib/Index/IndexBody.cpp#L185-L198

**Comment by abbaswasim** [comment]
> Regarding the original bug: clang thinks the access to `foo` is dependent here, the cursor is over a `DependentScopeMemberExpr` here.
> 
> The general case is something like:
> `template <typename T> int zero = std::vector<T>.s^ize()`
> 
> Formally, we don't know what size() is, as it may be defined in a specialization (e.g. if `T = bool`). But in practice, we'd like go-to-definition to use the primary template here.
> 
> This would be a change in behavior for `targetDecl`, maybe that API should flag such references with `PrimaryTemplate` or a new flag `Probable` or similar.
> I believe libIndex traverses the primary template trying to find a decl with the right name - we should probably emulate that.
> https://github.com/llvm-mirror/clang/blob/master/lib/Index/IndexBody.cpp#L185-L198

All of that makes sense but I am still not sure why `this->` matters. For example the reproducer @hokein provided:

```c++
template<class T>
class Foo
{
  public:
	void foo(int a)
	{
		fo^o(a);        // go-to-def, find references are not working.
	}
};
```

doesn't work but removing `this->` from `this->foo();` works even for templates.

```c++
template<class T>
class Foo
{
  public:
	void foo(int a)
	{
		fo^o(a);        // go-to-def, find references are working.
	}
};
```

**Comment by HighCommander4** [comment]
It's because `this->` makes the function name dependent (only resolved after instantiation) due to the type of `this` being dependent.

Here's an example where using `this->` changes the outcome of name lookup:

```
void foo(int);

template <typename T>
struct Base {
  void foo(int);
};

template <typename T>
struct Derived : Base<T> {
  void bar() {
    foo(42);        // calls global foo(int)
    this->foo(42);  // calls Base<T>::foo(int)
  }
};
```

**Comment by HighCommander4** [comment]
I'd like to give this a try.

**Comment by abbaswasim** [comment]
will be more than happy to test if needed.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D71240)

**Comment by HighCommander4** [comment]
The fix should handle the cases described in this issue.

There are more complex cases that are not yet handled, such as calling through a `std::unique_ptr` to a dependent type, as @sam-mccall pointed out during the review.

Please feel free to file issues with more examples if you come across them!
