### ISSUE TITLE
SystemIncludesExtractor stripping meaningful compiler arguments

### ISSUE THREAD

**Issue by ehntoo** [clangd/clangd#1410]
I have a project using CMake and ARM's GNU embedded toolchain release 11.3.1, and have noticed an issue with the way the query driver invokes the compiler when extracting includes paths. I'm using the newlib-nano libc included with the toolchain, which is selected by passing GCC the `-specs=nano.specs` flag during both compilation and linking. The `nano.specs` file alters several things, but importantly for clangd, it modifies system includes using these lines:
```
%rename cpp_unique_options		nano_cpp_unique_options

*cpp_unique_options:
-isystem =/include/newlib-nano %(nano_cpp_unique_options)
```

The clangd system includes extractor seems to only preserve the `--sysroot` and `-isysroot` arguments when invoking the target compiler to extract a list of includes paths (https://github.com/llvm/llvm-project/blob/f4fb2b3048c7e775df7b12a94cc41d490ca3b58e/clang-tools-extra/clangd/SystemIncludeExtractor.cpp#L188), so clangd does not receive the additional `include/newlib-nano` `-isystem` path needed for accurate system includes information.
```
V[17:10:38.392] System include extraction: target extracted: "arm-none-eabi"
V[17:10:38.392] System include extraction: adding  /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include
V[17:10:38.392] System include extraction: adding  /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include-fixed
V[17:10:38.392] System include extraction: adding  /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include
I[17:10:38.392] System includes extractor: successfully executed /usr/local/bin/arm-none-eabi-gcc
	got includes: "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include, /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include-fixed, /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include"
	got target: "arm-none-eabi"
```

Invoking the compiler with `-E -x c -v -specs=nano.specs` includes the specs file modifications, so system includes paths are printed as expected:
```
% cat /dev/null | arm-none-eabi-gcc -E -x c - -v -specs=nano.specs
Using built-in specs.
Reading specs from /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/nano.specs
rename spec link to nano_link
rename spec link_gcc_c_sequence to nano_link_gcc_c_sequence
rename spec cpp_unique_options to nano_cpp_unique_options
COLLECT_GCC=arm-none-eabi-gcc
Target: arm-none-eabi
Configured with: /Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/src/gcc/configure --target=arm-none-eabi --prefix=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/install --with-gmp=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/host-tools --with-mpfr=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/host-tools --with-mpc=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/host-tools --with-isl=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/host-tools --disable-shared --disable-nls --disable-threads --disable-tls --enable-checking=release --enable-languages=c,c++,fortran --with-newlib --with-gnu-as --with-gnu-ld --with-sysroot=/Volumes/data/jenkins/workspace/GNU-toolchain/arm-11/build-arm-none-eabi/install/arm-none-eabi --with-multilib-list=aprofile,rmprofile --with-pkgversion='Arm GNU Toolchain 11.3.Rel1' --with-bugurl=https://bugs.linaro.org/
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 11.3.1 20220712 (Arm GNU Toolchain 11.3.Rel1)
COLLECT_GCC_OPTIONS='-E' '-v' '-specs=nano.specs' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t'
 /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/11.3.1/cc1 -E -isystem =/include/newlib-nano -quiet -v -iprefix /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/ -isysroot /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi -D__USES_INITFINI__ - -mcpu=arm7tdmi -mfloat-abi=soft -marm -mlibarch=armv4t -march=armv4t -dumpbase -
ignoring duplicate directory "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/../../lib/gcc/arm-none-eabi/11.3.1/include"
ignoring nonexistent directory "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi/usr/local/include"
ignoring duplicate directory "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/../../lib/gcc/arm-none-eabi/11.3.1/include-fixed"
ignoring duplicate directory "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/../../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include"
ignoring nonexistent directory "/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi/include/newlib-nano
 /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include
 /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include-fixed
 /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include
End of search list.
# 0 "<stdin>"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "<stdin>"
COMPILER_PATH=/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../libexec/gcc/arm-none-eabi/11.3.1/:/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../libexec/gcc/:/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/bin/
LIBRARY_PATH=/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/:/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/:/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/lib/:/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi/lib/
```

I can put together a PR to add `-specs` to the list of preserved driver arguments, but I was not sure if this would be the preferred solution for this issue, as there seems to be some other issues (https://github.com/clangd/clangd/issues/1403) wherein preserving additional flags is problematic.

As an aside, I was able to override the detected `-isystem` paths using a `CompileFlags:` `Remove: [-isystem]` and an `Add:` entry for each required `-isystem` in my `.clangd` configuration. Unfortunately, this only works for C and C++ files. "Inferred" compilation commands such as those used for headers contain the original driver-provided `-isystem` paths, even when the file chosen as the inference source was correctly overridden. Note that in the following extract, the `heap_useNewlib.c` compile command includes the `include/newlib-nano` directory in system headers, but the header does not. I'm happy to make this its own issue if that would be best.
```
I[17:10:38.393] ASTWorker building file /Users/mitch/projdir/source/heap_useNewlib.c version 33 with command 
[/Users/mitch/projdir/build]
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/arm-none-eabi-gcc --target=arm-none-eabi --sysroot=/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi *project defines removed* *project includes paths removed* -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -nostdlib -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -specs=nano.specs -ggdb -g3 -Os -Wall -Wextra -Wno-unused-parameter -imacros /Users/mitch/projdir/source/include/app_preinclude.h -std=gnu99 -o CMakeFiles/out_target.dir/source/heap_useNewlib.c.obj -c -isystem/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include -isystem/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include-fixed -isystem/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include/newlib-nano -isystem/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include "-resource-dir=/Users/mitch/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.3/clangd_15.0.3/lib/clang/15.0.3" -- /Users/mitch/projdir/source/heap_useNewlib.c
*snip*
I[17:20:57.299] ASTWorker building file /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/arm-none-eabi/include/sys/reent.h version 1 with command inferred from /Users/mitch/projdir/source/heap_useNewlib.c
[/Users/mitch/projdir/build]
/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/arm-none-eabi-gcc --target=arm-none-eabi --sysroot=/Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../arm-none-eabi *project defines removed* *project includes paths removed* -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -nostdlib -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -specs=nano.specs -ggdb -g3 -Os -Wall -Wextra -Wno-unused-parameter -imacros /Users/mitch/projdir/source/include/app_preinclude.h -c -isystem /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include -isystem /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/include-fixed -isystem /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/11.3.1/../../../../arm-none-eabi/include "-resource-dir=/Users/mitch/Library/Application Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.3/clangd_15.0.3/lib/clang/15.0.3" -x c-header -std=gnu99 -- /Applications/ArmGNUToolchain/11.3.rel1/arm-none-eabi/arm-none-eabi/include/sys/reent.h
```

**System information**

Output of `clangd --version`:
```
% /Users/mitch/Library/Application\ Support/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/15.0.3/clangd_15.0.3/bin/clangd --version
clangd version 15.0.3 (https://github.com/llvm/llvm-project 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)
Features: mac+grpc+xpc
Platform: x86_64-apple-darwin21.6.0
```

Editor/LSP plugin:
VSCode / llvm-vs-code-extensions.vscode-clangd

Operating system:
macOS 12.6

**Comment by HighCommander4** [comment]
Thanks for the report! I think a reasonable order of operations here would be to get #1403 fixed first (i.e. include the preserved flags in the memoization key for system include extractor results), and then add `-specs` as another preserved flag.

Also, this makes me realize that preserving the `-specs` flag during system include extraction is probably sufficient to solve https://github.com/clangd/clangd/discussions/1042 as well. (At the time that issue was filed, I thought a solution would require the clang driver gaining support for the ability to parse specs files itself, but perhaps for most use cases it's sufficient to just pass it through to gcc and consume the resulting system includes.)

> As an aside, I was able to override the detected `-isystem` paths using a `CompileFlags:` `Remove: [-isystem]` and an `Add:` entry for each required `-isystem` in my `.clangd` configuration. Unfortunately, this only works for C and C++ files. "Inferred" compilation commands such as those used for headers contain the original driver-provided `-isystem` paths, even when the file chosen as the inference source was correctly overridden. [...]

That's because a project config file located at `/Users/mitch/projdir/.clangd` is scoped to files located in the directory tree `/Users/mitch/projdir`. If you want it to take effect for files in e.g. `/Applications/ArmGNUToolchain/11.3.rel1/`, you can do it by adding something like this to the [user config file](https://clangd.llvm.org/config.html#files):

```yaml
If:
  PathMatch: /Applications/ArmGNUToolchain/11.3.rel1/.*

CompileFlags:
  Add: /* ... */
```

**Comment by ehntoo** [comment]
Thanks for such a fast response! I put together an attempt at addressing #1403 and this bug here: https://reviews.llvm.org/D139277. It's my first time through the llvm/clang code review process and C++ is not one of my main programming languages, so apologies if I've made any mistakes. :)

In my testing, this patch completely solved the issues I was having regarding system headers added by the `-specs=nano.specs` file.

**Comment by i-ky** [comment]
As a reporter of #1042 I need this feature, but adding this feature just to clangd feels like a hack. What if I want to use other `compile_commands.json`-based tools like clang-tidy? (I know that clangd encapsulates clang-tidy diagnostics, but this does not cover CI/CD use case.) After filing #1042 I became more and more inclined to think that a proper solution would be a universal `compile_commands.json` preprocessor, that would "resolve" `-specs` in `compile_commands.json` by parsing spec files.

**Comment by HighCommander4** [comment]
> As a reporter of #1042 I need this feature, but adding this feature just to clangd feels like a hack. What if I want to use other `compile_commands.json`-based tools like clang-tidy?

This question makes me wonder how `clang-tidy` addresses the use case of `--query-driver` (which is indeed a clangd-specific feature), i.e. determining the correct standard library include paths to use for processing a file in cases where e.g. the file is cross-compiled.

@njames93 perhaps you know?

**Comment by i-ky** [comment]
> how `clang-tidy` addresses the use case of `--query-driver`

I believe [it doesn't](https://stackoverflow.com/questions/66268932/using-clang-tidy-to-analize-embedded-gcc-project).

**Comment by HighCommander4** [comment]
> > how `clang-tidy` addresses the use case of `--query-driver`
> 
> I believe it doesn't, see [here](https://stackoverflow.com/questions/66268932/using-clang-tidy-to-analize-embedded-gcc-project) and [here](https://discourse.cmake.org/t/using-clang-tidy-with-cross-compilation/5435).

I wonder, then, if it would make sense to upstream SystemIncludeExtractor to libTooling, so that clang-tidy (and other tools if desired) would make use of it as well.

(But I guess that still wouldn't address the use case of specs files in a fully general way, because SystemIncludeExtractor only provides the built-in include paths and the `--target` flag, while presumably specs files can affect other things as well?)

**Comment by i-ky** [comment]
> I wonder, then, if it would make sense to upstream SystemIncludeExtractor to libTooling, so that clang-tidy (and other tools if desired) could make use of it as well.

In my opinion it does make sense.

> (But I guess that still wouldn't address the use case of specs files in a fully general way, because SystemIncludeExtractor only provides the built-in include paths and the `--target` flag, while presumably specs files can affect other things as well?)

Yes, in my understanding spec files can add any flags to compiler invocation, including warnings and whatnot. I don't think it is mainstream to use spec files this way, but when there is a feature, there are likely users depending on it.

**Comment by matthijskooijman** [comment]
> I wonder, then, if it would make sense to upstream SystemIncludeExtractor to libTooling, so that clang-tidy (and other tools if desired) could make use of it as well.

I would be much in favor of this. I've been using `clangd` for completion in my embedded projects a lot, which handles most of my code perfectly, while other clang-based tools choke on include paths and an incorrect target. Would be good if this would just work (or would be easy to make working) for other tools as well.

**Comment by HighCommander4** [comment]
Now that #1403 is fixed, it should be a straightforward patch to add `-specs` to the cache key -- @ehntoo are you interested in updating your previous patch to do this?

**Comment by cjc25** [comment]
The difference between this and #1784 is that `-specs=` can be passed more than once, and empirically gcc honors all provided specs files. All the existing features in `DriverArgs` are single-flag options, but this is still straightforward as long as a vector-like field can be mixed into the hash key.

**Comment by cjc25** [comment]
Gentle ping for pr llvm/llvm-project#70285
