### ISSUE TITLE
Continuous Code Complete

### ISSUE THREAD

**Issue by koalarcoder** [clangd/clangd#1424]
now, when i inculding a header file, i just write “#i”， then i can use the code completion to get "   #include ""   ",but when i write the header file's name continuously after I used the code completion once like I said previously, i can't get the code completion until i write the ".". So can I get a function that I can get the code completion immediately after I write name of the header file , No more need to write a ".".

**Comment by HighCommander4** [comment]
What editor are you using?

**Comment by koalarcoder** [comment]
> What editor are you using?

VS code    
I use VS Code in Windows10. But i am not write the code in Windows, I linked the VS Code to Ubuntu Server by SSH pluign in Vs code.And my code and complie chain are in Ubuntu.

**Comment by koalarcoder** [comment]
not only when I include header file will triger that issue,but also when write "#pragma " ,ect

**Comment by HighCommander4** [comment]
Does adding the following to your vscode settings help?

```
    "editor.quickSuggestions": {
      "strings": "on"
    }
```

**Comment by koalarcoder** [comment]
yes, it worked. Thank you very much.

**Comment by koalarcoder** [comment]
there is one more question 
when i write a vector like this
![image](https://user-images.githubusercontent.com/82642902/208007535-8567d08e-ad36-45a8-aff8-ae9b2c37e94c.png)
then i write the class i need in the  <> that automatic write by clangd, it will not give the code completion prompt
can you help me?

**Comment by HighCommander4** [comment]
> it still not work after i add "other": "on"

Hmm, you're right, I see the same thing.

However, I don't think clangd has control over this behaviour, I think it's a bug on the vscode side. Please consider filing at https://github.com/microsoft/vscode/issues.

**Comment by koalarcoder** [comment]
ok, I'll fill to it.

**Comment by HighCommander4** [comment]
I added some clarifications to the vscode issue at https://github.com/microsoft/vscode/issues/169360.

**Comment by HighCommander4** [comment]
> I added some clarifications to the vscode issue at [microsoft/vscode#169360](https://github.com/microsoft/vscode/issues/169360).

See [this comment](https://github.com/microsoft/vscode/issues/169360#issuecomment-1354392689) on the issue for an explanation, but I think the key point is that setting `"editor.suggest.snippetsPreventQuickSuggestions": false` in vscode settings should make it work the way you'd like.
