### ISSUE TITLE
Clangd does not show parameter name inside of functions.

### ISSUE THREAD

**Issue by MubinMuhammad** [clangd/clangd#1425]
Clangd does not show type names inside of function for showing the parameters. It sometimes shows it & sometimes does not.
For example here it is showing the type name with the parameter name:
![1671161527](https://user-images.githubusercontent.com/101094719/208015876-b07b9ec5-bb9a-4b36-b8bc-cf8a85f47ab3.png)

And Sometimes it does not for example right here:
![1671161609](https://user-images.githubusercontent.com/101094719/208016024-1dadec08-4f88-408d-8ddb-1b36c04157f9.png)

it is really annoying so hopping that the bug will fix soon.

**Comment by HighCommander4** [comment]
Can you perform go-to-definition on `glTextImage2D` and copy the declaration or definition where clangd navigates here?

**Comment by MubinMuhammad** [comment]
I don't know much about clangd. And I am not understanding what you are meaning by "go-to-definition".

**Comment by MubinMuhammad** [comment]
and it's not just happening for glTexImage2D but all the OpenGL functions.

**Comment by HighCommander4** [comment]
> I am not understanding what you are meaning by "go-to-definition".

Clangd has a feature where it can navigate from the use of a symbol to its definition. What editor are you using?

**Comment by MubinMuhammad** [comment]
I am using Helix (written in rust). It's like vim.

**Comment by HighCommander4** [comment]
Ok, so I'm talking about this command:

![image](https://user-images.githubusercontent.com/1751085/208029774-428c9ff7-be81-4adb-bd14-9b378081bfc8.png)

from https://docs.helix-editor.com/keymap.html#goto-mode.

**Comment by MubinMuhammad** [comment]
I'm sorry. The LSP definition means the definition for the declaration. But OpenGL's declaration is confirmed by the manufacture like intel, amd, nvidia stuff like that. Those declaration is saved to a libGL.so file. (I use linux by the way).

**Comment by MubinMuhammad** [comment]
And I am starting to use helix for the first time. So I may don't know many things. I am apologize for that.

**Comment by HighCommander4** [comment]
No need to apologize, we were all new to the tools we use at some point :)

What LSP calls "definition" can sometimes mean "declaration" in C++, e.g. if it's a library function and clangd doesn't know about the source files of that library (only the header files).

So, I'm asking you to invoke this action on the use of `glTextImage2D`, and copy the declaration that clangd navigates to.

I'm asking this because clangd gets the parameter names from the declaration, so looking at the declaration might help explain why clangd is not showing the parameter names. (Like maybe the parameter names are missing in the declaration, or the declaration has a form that clangd's code for getting the parameter names does not currently handle.)

**Comment by MubinMuhammad** [comment]
I found this thing in the glad.h file (OpenGL header file).  Which relates with the glTexImage2D and it has the names of the function parameters:
![1671170801](https://user-images.githubusercontent.com/101094719/208033799-534ddd9b-2285-4677-8b01-53b795e733a3.png)

**Comment by HighCommander4** [comment]
Interesting, this case (parameter names in typedef declaration) should be handled by the work that was done in #1068.

What clangd version are you using?

**Comment by MubinMuhammad** [comment]
This is what I get if a I do `clangd --version`:
clangd version 14.0.6
Features: linux
Platform: x86_64-pc-linux-gnu

**Comment by HighCommander4** [comment]
Ok, that explains it: the fix of #1068 first appeared in clangd 15.

So, this has already been fixed, and you just need to upgrade clangd to start benefiting from the fix.
