### ISSUE TITLE
Hey, can't I update to Clangd 15?

### ISSUE THREAD

**Issue by MubinMuhammad** [clangd/clangd#1428]
I am using Arch Linux. If I try to update my packages, all packages update except clangd. Is there Clangd 15 even exist? I think so. Because I had an issue in the past where the parameter types are only being shown. And "[HighCommander4](https://github.com/HighCommander4)" said that I needed to update to the clangd version 15. But I can't, need Help!

**Comment by HighCommander4** [comment]
Maybe your package manager hasn't added a clangd 15 package yet.

As an alternative to getting it through your package manager, you can get the latest release directly from the Github releases: https://github.com/clangd/clangd/releases

**Comment by MubinMuhammad** [comment]
Actually, Clangd comes with clang. So, I tried to update clang.

**Comment by MubinMuhammad** [comment]
But, what do I do with the clangd binary file in the bin folder? How do I connect it with helix?

**Comment by HighCommander4** [comment]
> But, what do I do with the clangd binary file in the bin folder? How do I connect it with helix?

That's more a Helix-related question, but based on a quick browse of the Helix website I found this:

https://docs.helix-editor.com/languages.html#language-server-configuration

**Comment by MubinMuhammad** [comment]
I have added this to "command" in my languages.toml file:
![20221218_11h17m26s_grim](https://user-images.githubusercontent.com/101094719/208282698-ece55cb9-f255-4785-b21a-043dbf1f8497.png)
And I have put the clangd binary to the `/usr/local/bin`. Is it correct?

**Comment by HighCommander4** [comment]
> Is it correct?

As far as I can tell, no, there are two issues:

 * `command` is a subkey under `language-server`, have a look at the example at the top of https://docs.helix-editor.com/languages.html#language-configuration
 * You shouldn't separate the `clangd` executable from the other files in the package. Instead, put the `bin` subdirectory of the directory where you extracted the package, into your PATH.

**Comment by MubinMuhammad** [comment]
And I have checked my $PATH it is `/usr/local/bin` after i checked it is giving me multiple error in c++ files.

**Comment by MubinMuhammad** [comment]
Here is the error: 
![20221218_11h28m42s_grim](https://user-images.githubusercontent.com/101094719/208283055-26a6ebd6-3804-4784-b018-677561ef8f10.png)

**Comment by MubinMuhammad** [comment]
I think I should go over to helix and report this issue.
