### ISSUE TITLE
[vscode client] Respect editor.tokenColorCustomizations

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#143]
VSCode supports customizing the colors in the current theme by adding entries like this to the user or workspace settings:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "Classes",
                "scope": "entity.name.type.class.cpp",
                "settings": {
                    "foreground": "#008080"
                }
            },
            ...
        ]
    },
```

This causes the specified color to override the color for from the current theme for the specified scope (in this example, `"entity.name.type.class.cpp"`).

However, vscode-clangd's semantic highlighting does not respect these customizations, and unconditionally applies the color from the theme even if it's overriden in `editor.tokenColorCustomizations`.

**Comment by HighCommander4** [comment]
cc @jvikstrom

**Comment by knopp** [comment]
Another problem is that the "Developer: Inspect Editor Tokens and Scopes" doesn't work properly anymore. It shows the original scope, not the one replaced by clangd.

**Comment by knopp** [comment]
I think the issue here is that the plugin customizes syntax highlighting by creating text decorations. But vscode now has support for semantic highlighting.

**Comment by HighCommander4** [comment]
Yes, clangd's semantic highlighting support predates its implementation in vscode, so we implemented it using text decorations. The older implementation also uses an older draft of the LSP protocol.

Clangd did [recently gain](https://reviews.llvm.org/D76663) an implementation of the new protocol which vscode has built-in support for. I don't think it's enabled by default in the vscode-clangd plugin yet.

Regarding the original purpose of this issue, there will no longer be a need to implement support for `editor.tokenColorCustomizations` with the new protocol, since we can just leverage vscode's built-in support. (Note, currently semantic color customizations are exposed under `editor.tokenColorCustomizationsExperimental` in vscode).

**Comment by knopp** [comment]
Will the extension need to provide Document(Range)SemanticTokensProvider or is it handled completely outside of the extension?

**Comment by HighCommander4** [comment]
I don't think so. I think the purpose of that interface is to allow a vscode extension to provide semantic highlightings itself, rather than by asking an LSP language server.

**Comment by sam-mccall** [comment]
I think this isn't something we're likely to fix. The custom client-side highlighting implementation is there to support clangd 10 and earlier, and can be removed in a release cycle or so.
