### ISSUE TITLE
Support GRPC load balancing with SRV records 

### ISSUE THREAD

**Issue by bciobanu** [clangd/clangd#1431]
Hi,

I'm looking to set up some instances of clangd remote servers and have a load balancer arbitrate between them. 
There's an example of a server-side set up for load balancing over at https://github.com/clangd/llvm-remote-index. 

In my case it would be simpler if I could use the SRV mechanism optionally configurable in GRPC, per https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md. 
This implies a minimal change in the way GRPC channels are configured in clangd, to enable GRPC_ARG_DNS_ENABLE_SRV_QUERIES. In that mode, it performs an initial _grpclb._tcp srv query to get a list of servers and runs in load balancer mode between them.

Presumably this should not break existing clients because it didn't work so there was no reason to set up dns that way.

Would you be open to upstream a change that enables this mode for the clangd remote client and monitor?

**Comment by sam-mccall** [comment]
Sure, that sounds fine to me.

I guess if there's no SRV entry then the client will just contact the address from the A as usual? (This seems obvious, i just didn't see it explicitly in the docs)

Can you send a patch? (I guess it's trivial, and no need for a test, but you're in the best position to verify it actually works!)

**Comment by bciobanu** [comment]
Ah, I see grpclb is considered deprecated now, in favor of xDS ([Evolution of gRPCLB](https://groups.google.com/g/grpc-io/c/0yGihF-EFQo/m/A4QKdXffBwAJ])). 
The SRV functionality is only used when the load balancing policy is set to grpclb, so it doesn't seem worthwhile to support it in clangd.

Thanks for your prompt response.
