### ISSUE TITLE
Quick question,does clangd not support c++

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [clangd/clangd#1435]
### Discussed in https://github.com/clangd/clangd/discussions/1418

<div type='discussions-op-text'>

<sup>Originally posted by **RESDXChgfore9hing** December  8, 2022</sup>
It seems like the include doesnt *include the c++ std lib headers and include files
such as iostream
Thus when using it in lsp for c++ it gives error.</div>

i checked https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc

it seems to mention the need to setup some configuration file to point to the compiler?
Is it .clangd or compile_commands.json
and if so what do i type inside?Is there a template?

does something like this work?
{"path":"C:\\test\\compile_commands.json"}

**Comment by HighCommander4** [comment]
Answered in the discussion. Sorry for not replying sooner; we get a high volume of user questions and issue reports and we have answers to a lot of common questions (for example, how to create a `compile_commands.json`) on the [website](https://clangd.llvm.org/), reviewing the material there is always a good starting point.

**Comment by RESDXChgfore9hing** [comment]
I think you are missing the point.
The point is that the document is extremely confusing to me and I could not fully understand and make what I want.

for example,if I try look around and did my best to read this>https://clangd.llvm.org/config

It doesnt seems to tell me what is the minimum required (key*) in terms of json terminology.
It also seems to be written in YAML which makes it more confusing to convert to a json equivalent text.

Nor does any flag in that config page seems to hint adding what to resolve this.

for example(how do I put this into json??????)>
If:                               # Apply this config conditionally
  PathMatch: .*\.h                # to all headers...
  PathExclude: include/llvm-c/.*  # except those under include/llvm-c/

"if"{"PathMatch":".*\.h"}

or

{"PathMatch":".*\.h","PathExclude":"include/llvm-c/.*"}

I am sorry that I am not as experienced as you are,but I am trying my best to understand and trying to fix it.

**Comment by HighCommander4** [comment]
The clangd config file discussed at https://clangd.llvm.org/config, and `compile_commands.json`, are two different files (with different file formats).

To solve the problem of not finding standard library headers like <iostream>, you only need `compile_commands.json`, you don't need a clangd config file.

As I mentioned [here](https://github.com/clangd/clangd/discussions/1418#discussioncomment-4480478), `compile_commands.json` is usually not written manually, it's generated by a tool. https://clangd.llvm.org/installation#project-setup talks about some common ways to generate it. For example, for a small project that you build with `make`, the easiest way in my experience is to generate it using `bear make`.

**Comment by RESDXChgfore9hing** [comment]
I see so if I use devcpp IDE or directly g++ then it would be very hard to setup properly then.i assume?

hm..... Anyway thank you for trying to figure this out with me.

**Comment by HighCommander4** [comment]
> I see so if I use devcpp IDE or directly g++ then it would be very hard to setup properly then.i assume?

`bear` can be used to wrap any script, so if currently you call `g++` directly to compile your code, you can instead put the `g++` invocation into a script file like `build.sh` and call `bear build.sh`, and it will generate a `compile_commands.json`.

As for devcpp, are you referring to [this](https://www.bloodshed.net/)? Does it support clangd at all?

**Comment by HighCommander4** [comment]
Also, if you're on Windows, you may want to use [compiledb](https://github.com/nickdiego/compiledb) instead of `bear` (since I'm not sure how well `bear` supports Windows, I think I recall some users saying it didn't).

**Comment by RESDXChgfore9hing** [comment]
As for devcpp, are you referring to this? Does it support clangd at all?>yes haha.

Hmm ok I will take a look at compiledb.and try setup msys2/mingw32.Huge thanks.

Maybe a link to this issue at the clangd docs about windows,g++ can help the future user.

**Comment by HighCommander4** [comment]
I would be curious to know how you use Dev-C++ with clangd. Clangd generally requires editors to have support for it, or at least generic support for the Language Server Protocol. Does Dev-C++ have this?

**Comment by RESDXChgfore9hing** [comment]
nah I dont use Devc++ with this.
I use cudatext with the lsp,
I only use Devc++ to compile and build,

I use cudatext as like a editor*
and then Devc++ as a compile/build tool.

____
But the problem with cudatext is the plugin must be fully py,or else need to do (py- whatever language that is)
So it take some effort to fully automate.

So in this case,even if I figured out how to generate the compile_commands.json
I would still need to manually run or config it,nor can it directly build it 
___
Thus I mentioned g++ or devc++ since it would be more convienent to just
- run an app,pick the source from path and config dependencies and press compile.
 vs
- create a plugin and then deal with a possibly 300-1000+ line py code,due to how complex it could be.
