### ISSUE TITLE
Support sizeof() of class/struct result evaluation

### ISSUE THREAD

**Issue by cacosub7** [clangd/clangd#1444]
Does clangd have a feature that evaluating the sizeof(class/struct) result on hover？ ![image](https://user-images.githubusercontent.com/46550268/209760467-0cbef5cd-0d9c-412f-9a43-0edfa6455a41.jpeg)
(this is what vscode C/C++ extension shows)

**Comment by HighCommander4** [comment]
Please do not file issues in duplicate. Answered in https://github.com/clangd/clangd/discussions/1443.
