### ISSUE TITLE
fixit-hint for missing `<typeinfo>` include includes `<typeid>` instead

### ISSUE THREAD

**Issue by philnik777** [clangd/clangd#1449]
When using `typeid` and the `<typeinfo>` include is missing, clangd's fixit-hint includes `<typeid>` instead.

minimal reproducer:

```c++
void func() {
  typeid(int); // fixit-hint includes <typeid> instead of <typeinfo>
}
```

Output of `clangd --version`:
clangd version 16.0.0 (git@github.com:llvm/llvm-project.git c52053bd9961cc1854e86958ffb0f89e2cfe4e5f)
Features: linux
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
VSCodium/clangd

Operating system:
Linux

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D141218)
