### ISSUE TITLE
IWYU code action

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#145]
We could add a "add include for XXX" code action when selecting any node where the include is likely missing.

We can get the include from the index in apply() but avoid the index lookup in prepare() by simply checking if no redecls are directly included. We need to check for IWYU directives/standard library, but that should cover most cases.

Precision doesn't have to be *super* high if we don't add a diagnostic.

**Comment by HighCommander4** [comment]
Is this a dupe of #79?

**Comment by kiwixz** [comment]
Isn't this already implemented as a hint ?

**Comment by kadircet** [comment]
> Isn't this already implemented as a hint ?

Not really, clangd currently only offers inserting the header if definition for a symbol is missing (i.e build would fail, there's a real diagnostic).

But absence of diags doesn't imply file is IWYU complaint. It might still be depending on a symbol transitively. This issue suggests, offering a code action in such cases for inserting the direct header declaring/defining the symbol in such cases.

**Comment by kadircet** [comment]
This is likely to be made easier with the implementation of IWYU missing header diagnostics (as they can share the same infra) and might be a different way to make use of the feature for users that don't want "strict" IWYU mode.

**Comment by sam-mccall** [comment]
This is done: https://clangd.llvm.org/guides/include-cleaner
