### ISSUE TITLE
Add the `--style` parameter in clang-format to clangd

### ISSUE THREAD

**Issue by linqingyao** [clangd/clangd#1450]
The **clang-format** `--fallback-style` parameter is supported in **clangd**, but it's not enough. Adding `--style` can be a better interaction between **clangd** and **clang-format**, making file formatting options more varied

**Comment by HighCommander4** [comment]
Some digging in code history led me to discover that this was previously proposed and discussed in #26, see in particular the last section of https://github.com/clangd/clangd/issues/26#issuecomment-489091298.

**Comment by linqingyao** [comment]
Oh, my God. Thank you very much for your reply. I have checked the discussion you mentioned and I have understood it. But I still have a problem with the --fallback-style option, which I'll address in a new issue.
