### ISSUE TITLE
Supplementary --fallback-style=<string> option

### ISSUE THREAD

**Issue by linqingyao** [clangd/clangd#1453]
In the current --fallback-style, it is possible to set the rollback style[^1], but I want the rollback style to be a custom path configuration[^2]. Because I want all of my code to be formatted as it should be without having to copy `.clang-format` files everywhere.

When set to `--fallback-style=file:<format_file_path>`: Use the `<format_file_path>` configuration file when no `.clang-format` file is found.

[^1]: for example: LLVM
[^2]: Similar to the `3. 'file:<format_file_path>' to explicitly specify the configuration file` section of the option

**Comment by linqingyao** [comment]
I know I sent it in the wrong place, but I can't find the page where the clang-format library is located to submit the issue.

**Comment by HighCommander4** [comment]
We have https://github.com/clangd/clangd/issues/805 on file for adding a way to point clangd to a specific clang-format config file.

(See also https://github.com/clangd/vscode-clangd/issues/184 and the workarounds discussed there, notably the workaround of putting a `.clang-format` file in a directory which is an ancestor directory of all your projects, for example your home directory.)

If you're suggesting a change to clang-format's `--fallback-style` flag itself (which would affect the `clang-format` command-line tool in addition to clangd), you can file an issue upstream at https://github.com/llvm/llvm-project/issues.

**Comment by linqingyao** [comment]
Thank you for everything on it.
