### ISSUE TITLE
Weird go to def/hover/find-ref behavior in decltype() expressions inside of a template 

### ISSUE THREAD

**Issue by tdupes** [clangd/clangd#1463]
I see weird behavior when using clangd on [folly](https://github.com/facebook/folly) which makes heavy use of templates. In this example I see it on the file `Expected.h` ([link](https://github.com/facebook/folly/blob/30abf028d4773f07115c32c67d2e156b316c5417/folly/Expected.h#L677))  if I hover over any token inside of the decltypes in the template parameters I get results as if it were for the function itself. 

<img width="1010" alt="Screenshot 2023-01-12 at 7 14 05 PM" src="https://user-images.githubusercontent.com/5506107/212214460-79d7d351-f42f-47a0-b85b-fd7cd3f32069.png">

In this case even the token for `std::` is treated as the function itself when it should be able to know its referencing the std namespace. 

**System information**

I've verified this behavior on clangd version 14.0.0, 15.0.06 and with a clangd built from head which shows 16.0.0

Editor/LSP plugin:
vscode with official clangd plugin

Operating system:
linux (fedora)

**Comment by sam-mccall** [comment]
Are you able to provide a minimized example? The following works for me with recent clangd:

```
namespace std { template <class X> X declval(); }

template <
    class This, class Yes, class No,
    class Ret = decltype(std::declval<Yes>()(std::declval<This>().value())),
    class Err = decltype(std::declval<No>()(std::declval<This&>().value()))>
static Ret thenOrThrow_(This&& ex, Yes&& yes, No&& no);
```

![image](https://user-images.githubusercontent.com/548993/212218886-474e4ad6-665a-4448-a3e3-9e11bda22950.png)

**Comment by tdupes** [comment]
I was able to fix the issue by using an alternative build method to produce a different compdb. I suppose its an issue of incomplete build args meant the decltype expressions in the AST weren't fully actualized?

Anyways, sorry for the noise.

**Comment by tdupes** [comment]
For posterity, it also looks like this was the behavior in clangd version 12 when I tested it.

**Comment by sam-mccall** [comment]
> I suppose its an issue of incomplete build args meant the decltype expressions in the AST weren't fully actualized?

Yes, incomplete flags tend to lead to the parse failing somewhere and that ends up cascading into incomplete AST in lots of places, some combination of {parsing C++ is highly context-sensitive, clang's AST tries to preserve strong invariants}.

To a first approximation clangd sees the AST produced by `clang -fsyntax-only -Xclang -ast-dump $FLAGS file.cpp`.
