### ISSUE TITLE
C++ 20 Modules Support

### ISSUE THREAD

**Issue by sdykae** [clangd/clangd#1468]
Modules intellisense and completion not working even when cmake compiles
llvm compiled from  https://github.com/mathstuf/llvm-project/tree/p1689r5-csd
according cmake reference https://gitlab.kitware.com/cmake/cmake/-/issues/18355
![image](https://user-images.githubusercontent.com/50224521/209910548-45d29d64-e62f-4f48-92ce-0e439ab6db49.png)

![image](https://user-images.githubusercontent.com/50224521/209910683-b0c79d3a-6818-4715-8a95-865801bf54dd.png)
Compilation works and executable but intellisense 
![image](https://user-images.githubusercontent.com/50224521/209910724-f995050f-70a5-4279-bbde-4f65276d0fb4.png)
![image](https://user-images.githubusercontent.com/50224521/209910744-71fd5e78-e7ee-4f5b-87dc-10ee98697c93.png)

main.cpp
```cpp
import Hello;
int main() { hello(); }
```
hello.cppm
```cpp
module;
#include <iostream>
export module Hello;
export void hello() {
  std::cout << "Hello World!\n";
}
```
CMakeList.txt
```cmake
cmake_minimum_required(VERSION 3.25.2`)
project(app)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_C_COMPILER /Users/sdykae/development/llvm-project-p1689r5-csd/build/bin/clang)
set(CMAKE_CXX_COMPILER /Users/sdykae/development/llvm-project-p1689r5-csd/build/bin/clang++)

set(CMAKE_LDFLAGS "-L/Users/sdykae/development/llvm-project-p1689r5-csd/build/lib")
SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fuse-ld=/Users/sdykae/development/llvm-project-p1689r5-csd/build/bin/ld64.lld")
SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wl,-L/Users/sdykae/development/llvm-project-p1689r5-csd/build/lib")
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -std=c++2b -fexperimental-library -stdlib=libc++" )
message(STATUS "CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.15")
set(CMAKE_OSX_ARCHITECTURES "x86_64")

set(CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API "2182bf5c-ef0d-489a-91da-49dbc3090d2a")
set(CMAKE_EXPERIMENTAL_CXX_MODULE_DYNDEP 1)

string(CONCAT CMAKE_EXPERIMENTAL_CXX_SCANDEP_SOURCE
  "/Users/sdykae/development/llvm-project-p1689r5-csd/build/bin/clang-scan-deps"
  " -format=p1689 --p1689-targeted-file-name=<SOURCE> --p1689-targeted-output=<OBJECT> "
  " --p1689-makeformat-output=<DEP_FILE>"
  " --"
  " <DEFINES> <INCLUDES> <FLAGS> -x c++ <SOURCE>"
  " -MT <DYNDEP_FILE> -MD"
  " > <DYNDEP_FILE>")

set(CMAKE_EXPERIMENTAL_CXX_MODULE_MAP_FORMAT "clang")
set(CMAKE_EXPERIMENTAL_CXX_MODULE_MAP_FLAG "@<MODULE_MAP_FILE>")
set(CMAKE_CXX_EXTENSIONS OFF)
set(source_files main.cc )

add_executable(${PROJECT_NAME})
target_sources(${PROJECT_NAME}
  PRIVATE
    main.cpp
  PRIVATE
    FILE_SET CXX_MODULES
      # BASE_DIRS
      #   "${CMAKE_CURRENT_SOURCE_DIR}"
      FILES
        hello.cppm
)

target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_20)


```
If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from the "Output" window if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`):
![image](https://user-images.githubusercontent.com/50224521/209910875-ddc84f7c-b95b-4337-b279-47ef04692721.png)
clangd extension version: 16.0.0
Operating system: osx ventura 13.1

**Comment by kadircet** [comment]
moving to clangd and closing as duplicate
