### ISSUE TITLE
In clangd configuration website page. There is no option Designators under Inlayhints.

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [clangd/clangd#1472]
![image](https://user-images.githubusercontent.com/52443370/213859423-f739f881-caf0-4f2a-8475-52647d0babaa.png)

I add this key to close `[0]=`, `[1]=`. It is controled by `Designators` which is missing from the docs.

<https://github.com/clangd/clangd/discussions/1470>

**Comment by HighCommander4** [comment]
Thanks for filing!

Would you like to submit a documentation patch? The source file is at https://github.com/llvm/clangd-www/blob/main/config.md.

**Comment by kadircet** [comment]
fixed via https://github.com/llvm/clangd-www/pull/78
