### ISSUE TITLE
Navigation to != operator results in "No definition found" error when using C++20 and == operator defined

### ISSUE THREAD

**Issue by vagran** [clangd/clangd#1476]
According to [cppreference.com](https://en.cppreference.com/w/cpp/language/operators) starting from C++20:

> The inequality operator is automatically generated by the compiler if operator== is defined. Likewise, the four relational operators are automatically generated by the compiler if the three-way comparison operator operator<=> is defined.

I propose to resolve implicitly defined operators in the way the compiler does it, navigating in such cases either to `==` or `<=>` operators if they are defined and `-std=c++20` or above is specified.

Tested with `clangd version 15.0.3 (https://github.com/llvm/llvm-project 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)`

**Comment by jensmassberg** [comment]
The problem here is that in C++20 `a != b` is rewritten to `!(a == b)` and clangd doesn't consider the corresponding `CXXRewrittenBinaryOperator` yet. In case of a `CXXRewrittenBinaryOperator`  we should go to the inner operator of the decomposed form.
I'm working on a fix.

**Comment by jensmassberg** [comment]
This has been fixed in https://reviews.llvm.org/D153331
