### ISSUE TITLE
Can not find reference to member template function when instantiated with type parameter

### ISSUE THREAD

**Issue by Daniel-OConnor** [clangd/clangd#1477]
```
class A
{
public:
    template<typename T>
    void member_foo()
    {
    }
};

template<typename T>
void free_foo()
{
}

template<typename T>
void bar()
{
    A a;
    a.member_foo<T>(); // This is not found
    free_foo<T>(); // This is found
    a.member_foo<int>(); // This is also found
}
```

Go to references fails to find the first call to `member_foo`, but go to definition works for all function calls.

Output of `clangd --version`:
clangd version 15.0.7 (https://github.com/llvm/llvm-project.git 8dfdcc7b7bf66834a761bd8de445840ef68e4d1a)
Features: linux
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin: vscode

Operating system: Centos 7

**Comment by HighCommander4** [comment]
This is fixed in clangd 16 (not yet released).

**Comment by Daniel-OConnor** [comment]
Thank you, the issue is fixed if I use current main. Should I close the ticket or leave it open until clang16 is released?

**Comment by HighCommander4** [comment]
I believe the change that fixed it was https://reviews.llvm.org/D131091.

We can close the issue.
