### ISSUE TITLE
not crorrect placeholder when completion base className in initialization list of construct

### ISSUE THREAD

**Issue by lxz12523** [clangd/clangd#1479]
wrong after completion AB(int a2, int b2):
  Test(double a1) : **AB(int a2, )**
expect after completion AB(int a2, int b2):
  Test(double a1) : **AB(int a2, int b2)**
![image](https://user-images.githubusercontent.com/42319043/215047661-79b96d46-ac56-4d51-a401-527cf8372128.png)

**Logs**
![image](https://user-images.githubusercontent.com/42319043/215046606-66ed7e2b-4139-4245-a7b6-ba3bb2471ff1.png)

**System information**

Output of clangd --version:
clangd version 15.0.6
Features: windows+debug
Platform: x86_64-pc-windows-msvc

Editor/LSP plugin:
vscode-clangd
Operating system:
Windows 11

**Comment by HighCommander4** [comment]
Next time, please include the code in text form as well, so I don't have to type it out from an image :)

Slightly simplified test case:

```c++
struct Base {
  Base(int a, int b) {}
};

struct Test : Base {
  Test() : Base^
};

```

 * Invoke completion at the `^`
 * Select the proposal for the `Base` constructor
 * The inserted text is `Base(int a, )` instead of the expected `Base(int a, int b)`

**Comment by zyn0217** [comment]
Is this a dup of [152837](https://github.com/microsoft/vscode/issues/152837)?
Completion snippet is `(${1:int a}, $0)`, `$0` is where we want to put the cursor?

**Comment by HighCommander4** [comment]
I don't think so, I think clangd should be sending `(${1:int a}, ${2:int b})`

**Comment by HighCommander4** [comment]
Oh, I see the connection to https://github.com/microsoft/vscode/issues/152837: the fact that clangd is currently sending `(${1:int a}, $0)` may be a consequence of https://reviews.llvm.org/D128621, which is a workaround for https://github.com/microsoft/vscode/issues/152837.

If so, this is a case where that workaround made our behaviour worse, and we should try to come up with something better if possible.

**Comment by HighCommander4** [comment]
I am a bit surprised that this particular case is exercising the [CompletingPattern == true](https://searchfox.org/llvm/rev/6e1ea30fdfc1b9eb2c8ddf41e7bb04000424f7e1/clang-tools-extra/clangd/CodeCompletionStrings.cpp#103) codepath, I would have expected this completion to be a declaration rather than a pattern.

**Comment by zyn0217** [comment]
> Oh, I see the connection to [microsoft/vscode#152837](https://github.com/microsoft/vscode/issues/152837): the fact that clangd is currently sending `(${1:int a}, $0)` may be a consequence of https://reviews.llvm.org/D128621, which is a workaround for [microsoft/vscode#152837](https://github.com/microsoft/vscode/issues/152837).
> 
> If so, this is a case where that workaround made our behaviour worse, and we should try to come up with something better if possible.

Yes. I'm not quite familiar with the protocol, is `(${1:int a}, $0${2:int b})` a choice?

**Comment by HighCommander4** [comment]
> is `(${1:int a}, $0${2:int b})` a choice?

This would mean that after you type the second argument expression, pressing <kbd>Tab</kbd> would take you back to the beginning of the argument expression.

For more context on how this syntax is interpreted and what workaround approaches we considered, see https://github.com/clangd/clangd/issues/1190, especially the following comments:
 * https://github.com/clangd/clangd/issues/1190#issuecomment-1162585773
 * https://github.com/clangd/clangd/issues/1190#issuecomment-1165310144
 * https://github.com/clangd/clangd/issues/1190#issuecomment-1181817829

**Comment by zyn0217** [comment]
Thanks for the clarification :)

**Comment by zyn0217** [comment]
> I would have expected this completion to be a declaration rather than a pattern.

Well, I guess it is [because of this](https://github.com/llvm/llvm-project/blob/8f6c623e874624c1f247f93bf457d5196a84cec6/clang/lib/Sema/SemaCodeComplete.cpp#L6871). (It really takes a time to navigate to such line...)

**Comment by HighCommander4** [comment]
Right, I guess `CodeCompletionResult::RK_Pattern` is pretty general and used in a wide variety of code completion proposals.

Maybe we should also look at `CodeCompletionResult::CursorKind` to determine whether to treat the proposal as a "pattern" for the purposes of using the `$0` tab stop.

Based on [this comment](https://reviews.llvm.org/D128621#3611673), the main motivating use case for the `$0` behaviour is patterns which involve statements/declarations inside braces, so if we can discriminate those from other patterns using `CursorKind`, we can refine our logic.

**Comment by zyn0217** [comment]
> so if we can discriminate those from other patterns using CursorKind, we can refine our logic.

We can, despite the fact that we have to enumerate all possible fields of `CXCursorKind` (or at least those used in `getCursorKindForDecl`), which is kind of verbose and error-prone, I think.

I've also noticed that we have a special flag named `CodeCompletionResult::InBaseClass`, however it is not set when we add ctor patterns from base class. A quick trial showed that it is possible to work around this issue by distinguish patterns with this flag, while not breaking other tests. But I don't know if we still have other cases influenced by this issue. Personally, I prefer the former approach, but it may take some time to investigate.

**Comment by zyn0217** [comment]
A possible fix: https://reviews.llvm.org/D145319

**Comment by HighCommander4** [comment]
(This was fixed in clangd 17, we just forgot to close the issue.)
