### ISSUE TITLE
clangd shouldn't create placeholders for default template parameters

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#148]
1. Under normal circumstances, clangd does not create placeholders for default template parameters.
![image](https://user-images.githubusercontent.com/10697249/64598827-f784e300-d3ea-11e9-8367-2085bcb8b13c.png)
2. After using jump to definition for `std::vector<int>`.
![image](https://user-images.githubusercontent.com/10697249/64598908-18e5cf00-d3eb-11e9-99e9-2acb5dbba6ea.png)

**Comment by sam-mccall** [comment]
I was originally able to reproduce this, but it seems to be fixed.
