### ISSUE TITLE
symbols from `std::experimental::filesystem` should be mapped

### ISSUE THREAD

**Issue by zyn0217** [clangd/clangd#1481]
Our team uses GCC 7.5 whose std::filesystem is still experimental. Current Clangd doesn't map these symbols (in CanonicalIncludes::addSystemHeadersMapping IIUC), making inserting headers of code completion broken sometimes.

To put it simple,
```cpp
#include <experimental/filesystem>

namespace fs = std::experimental::filesystem;

int main() {
  fs::pa^  // unexpected `<experimental/bits/fs_path.h> would be included`
}
```

![1](https://user-images.githubusercontent.com/117258288/215318435-421da9bf-59cc-4d87-abab-3760ec602f7f.png)

**Comment by HighCommander4** [comment]
Linking to patch at https://reviews.llvm.org/D142836

**Comment by zyn0217** [comment]
D142836 is closed. See https://reviews.llvm.org/D143319
