### ISSUE TITLE
[rename]can rename or rename error in using Namespace

### ISSUE THREAD

**Issue by lxz12523** [clangd/clangd#1483]
[rename]can rename or rename error in using Namespace
// in test.cpp
namespace RN {
    void test() {}//rename error
}
using RN::test; //can't rename
void foo() {
    test();// can't rename
}

after rename:

namespace RN {
    void test2() {}
}
using RN::test2;
void foo() {
    test();
}

**Logs**

V[20:52:23.770] <<< {"id":643,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":6,"line":5},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:23.770] <-- textDocument/hover(643)
V[20:52:23.771] ASTWorker running Hover on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:23.773] --> reply:textDocument/hover(643) 3 ms
V[20:52:23.773] >>> {"id":643,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### using `test`  \n\n---\n```cpp\nusing RN::test\n```"},"range":{"end":{"character":8,"line":5},"start":{"character":4,"line":5}}}}

I[20:52:23.773] --> textDocument/clangd.fileStatus
V[20:52:23.773] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:24.694] <<< {"id":644,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":7,"line":5},"start":{"character":7,"line":5}},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:24.694] <-- textDocument/codeAction(644)
V[20:52:24.694] ASTWorker running EnumerateTweaks on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:24.694] --> reply:textDocument/codeAction(644) 0 ms
V[20:52:24.694] >>> {"id":644,"jsonrpc":"2.0","result":[]}

I[20:52:24.694] --> textDocument/clangd.fileStatus
V[20:52:24.694] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:25.175] <<< {"id":645,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":6,"line":5},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:25.175] <-- textDocument/hover(645)
V[20:52:25.175] ASTWorker running Hover on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:25.178] --> reply:textDocument/hover(645) 2 ms
V[20:52:25.178] >>> {"id":645,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### using `test`  \n\n---\n```cpp\nusing RN::test\n```"},"range":{"end":{"character":8,"line":5},"start":{"character":4,"line":5}}}}

I[20:52:25.178] --> textDocument/clangd.fileStatus
V[20:52:25.178] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:27.746] <<< {"id":646,"jsonrpc":"2.0","method":"textDocument/prepareRename","params":{"position":{"character":7,"line":5},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:27.746] <-- textDocument/prepareRename(646)
V[20:52:27.746] ASTWorker running PrepareRename on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:27.746] --> reply:textDocument/prepareRename(646) 0 ms, error: Cannot rename symbol: there are multiple symbols at the given location
V[20:52:27.746] >>> {"error":{"code":-32001,"message":"Cannot rename symbol: there are multiple symbols at the given location"},"id":646,"jsonrpc":"2.0"}

I[20:52:27.746] --> textDocument/clangd.fileStatus
V[20:52:27.746] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:43.191] <<< {"id":647,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":11,"line":1},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:43.191] <-- textDocument/hover(647)
V[20:52:43.193] ASTWorker running Hover on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:43.193] --> reply:textDocument/hover(647) 1 ms
V[20:52:43.193] >>> {"id":647,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### function `test`  \n\n---\n→ `void`  \n\n---\n```cpp\n// In namespace RN\nvoid test()\n```"},"range":{"end":{"character":13,"line":1},"start":{"character":9,"line":1}}}}

I[20:52:43.193] --> textDocument/clangd.fileStatus
V[20:52:43.193] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:43.634] <<< {"id":648,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":11,"line":1},"start":{"character":11,"line":1}},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:43.634] <-- textDocument/codeAction(648)
V[20:52:43.634] ASTWorker running EnumerateTweaks on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:43.634] --> reply:textDocument/codeAction(648) 0 ms
V[20:52:43.634] >>> {"id":648,"jsonrpc":"2.0","result":[]}

I[20:52:43.634] --> textDocument/clangd.fileStatus
V[20:52:43.634] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:44.078] <<< {"id":649,"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":11,"line":1},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:44.078] <-- textDocument/hover(649)
V[20:52:44.078] ASTWorker running Hover on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:44.082] --> reply:textDocument/hover(649) 4 ms
V[20:52:44.082] >>> {"id":649,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### function `test`  \n\n---\n→ `void`  \n\n---\n```cpp\n// In namespace RN\nvoid test()\n```"},"range":{"end":{"character":13,"line":1},"start":{"character":9,"line":1}}}}

I[20:52:44.083] --> textDocument/clangd.fileStatus
V[20:52:44.083] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:46.485] <<< {"id":650,"jsonrpc":"2.0","method":"textDocument/prepareRename","params":{"position":{"character":11,"line":1},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:46.485] <-- textDocument/prepareRename(650)
V[20:52:46.485] ASTWorker running PrepareRename on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:46.485] --> reply:textDocument/prepareRename(650) 0 ms
V[20:52:46.485] >>> {"id":650,"jsonrpc":"2.0","result":{"end":{"character":13,"line":1},"start":{"character":9,"line":1}}}

I[20:52:46.485] --> textDocument/clangd.fileStatus
V[20:52:46.485] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.033] <<< {"id":651,"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"test2","position":{"character":11,"line":1},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:49.033] <-- textDocument/rename(651)
V[20:52:49.035] ASTWorker running Rename on version 182 of d:\Code\cpp_proj\test.cpp
I[20:52:49.036] --> reply:textDocument/rename(651) 2 ms
V[20:52:49.036] >>> {"id":651,"jsonrpc":"2.0","result":{"changes":{"file:///d:/Code/cpp_proj/test.cpp":[{"newText":"test2","range":{"end":{"character":13,"line":1},"start":{"character":9,"line":1}}},{"newText":"test2","range":{"end":{"character":14,"line":3},"start":{"character":10,"line":3}}}]}}}

I[20:52:49.036] --> textDocument/clangd.fileStatus
V[20:52:49.036] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.045] <<< {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":14,"line":3},"start":{"character":14,"line":3}},"rangeLength":0,"text":"2"},{"range":{"end":{"character":13,"line":1},"start":{"character":13,"line":1}},"rangeLength":0,"text":"2"}],"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp","version":183}}}

I[20:52:49.045] <-- textDocument/didChange
I[20:52:49.045] --> textDocument/clangd.fileStatus
V[20:52:49.045] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"file is queued","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

I[20:52:49.108] ASTWorker building file d:\Code\cpp_proj\test.cpp version 183 with command 
[D:/Code/cpp_proj/cmake-build-debug]
"D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe" --driver-mode=cl /nologo /TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd "/FoCMakeFiles\\cpp_proj.dir\\test.cpp.obj" /FdTARGET_COMPILE_PDB /FS -c "-resource-dir=D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6" -- "d:\\Code\\cpp_proj\\test.cpp"
V[20:52:49.121] Driver produced command: cc1 -cc1 -triple x86_64-pc-windows-msvc19.34.31935 -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -mllvm -x86-asm-syntax=intel -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -D_DEBUG -D_MT -D_DLL --dependent-lib=msvcrtd --dependent-lib=oldnames -stack-protector 2 -fcxx-exceptions -fexceptions -fexternc-nounwind -fms-volatile -fdiagnostics-format msvc -gno-column-info -gcodeview -debug-info-kind=constructor -fcoverage-compilation-dir=D:/Code/cpp_proj/cmake-build-debug -resource-dir "D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6" -D WIN32 -D _WINDOWS -internal-isystem "D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6\\include" -internal-isystem "D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\include" -internal-isystem "D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt" -O0 -fdeprecated-macro -fdebug-compilation-dir=D:/Code/cpp_proj/cmake-build-debug -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.34.31935 -std=c++14 -fdelayed-template-parsing -fno-inline -no-round-trip-args -faddrsig -x c++ "d:\\Code\\cpp_proj\\test.cpp"
I[20:52:49.122] --> textDocument/clangd.fileStatus
V[20:52:49.122] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

I[20:52:49.122] --> textDocument/clangd.fileStatus
V[20:52:49.122] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.123] Reusing preamble version 5 for version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:49.124] --> textDocument/clangd.fileStatus
V[20:52:49.124] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.168] Trying to fix unresolved name "test" in scopes: []
V[20:52:49.168] Dex query tree: false
V[20:52:49.168] Dex query tree: false
V[20:52:49.168] indexed file AST for d:\Code\cpp_proj\test.cpp version 183:
  symbol slab: 4 symbols, 5152 bytes
  ref slab: 3 symbols, 5 refs, 4304 bytes
  relations slab: 0 relations, 24 bytes
V[20:52:49.168] Build dynamic index for main-file symbols with estimated memory usage of 31696 bytes
I[20:52:49.168] --> textDocument/publishDiagnostics
V[20:52:49.168] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"undeclared_var_use_suggest","message":"Use of undeclared identifier 'test'; did you mean 'test2'? (fix available)","range":{"end":{"character":8,"line":5},"start":{"character":4,"line":5}},"relatedInformation":[{"location":{"range":{"end":{"character":15,"line":3},"start":{"character":10,"line":3}},"uri":"file:///D:/Code/cpp_proj/test.cpp"},"message":"'test2' declared here"}],"severity":1,"source":"clang"}],"uri":"file:///d:/Code/cpp_proj/test.cpp","version":183}}

I[20:52:49.168] --> textDocument/clangd.fileStatus
V[20:52:49.168] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.342] <<< {"id":652,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"117","textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:49.342] <-- textDocument/semanticTokens/full/delta(652)
V[20:52:49.342] ASTWorker running SemanticHighlights on version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:49.342] --> reply:textDocument/semanticTokens/full/delta(652) 0 ms
V[20:52:49.342] >>> {"id":652,"jsonrpc":"2.0","result":{"edits":[{"data":[1,9,5,3,8193,2,6,2,15,8192,0,4,5,3,8192],"deleteCount":15,"start":5}],"resultId":"118"}}

I[20:52:49.342] --> textDocument/clangd.fileStatus
V[20:52:49.342] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.398] <<< {"id":653,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:49.398] <-- textDocument/documentSymbol(653)
V[20:52:49.398] ASTWorker running DocumentSymbols on version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:49.399] --> reply:textDocument/documentSymbol(653) 0 ms
V[20:52:49.399] >>> {"id":653,"jsonrpc":"2.0","result":[{"children":[{"detail":"void ()","kind":12,"name":"test2","range":{"end":{"character":19,"line":1},"start":{"character":4,"line":1}},"selectionRange":{"end":{"character":14,"line":1},"start":{"character":9,"line":1}}}],"kind":3,"name":"RN","range":{"end":{"character":1,"line":2},"start":{"character":0,"line":0}},"selectionRange":{"end":{"character":12,"line":0},"start":{"character":10,"line":0}}},{"kind":3,"name":"test2","range":{"end":{"character":15,"line":3},"start":{"character":0,"line":3}},"selectionRange":{"end":{"character":15,"line":3},"start":{"character":10,"line":3}}},{"detail":"void ()","kind":12,"name":"foo","range":{"end":{"character":1,"line":6},"start":{"character":0,"line":4}},"selectionRange":{"end":{"character":8,"line":4},"start":{"character":5,"line":4}}}]}

I[20:52:49.399] --> textDocument/clangd.fileStatus
V[20:52:49.399] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:49.429] <<< {"id":654,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":11,"line":1},"start":{"character":11,"line":1}},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:49.429] <-- textDocument/codeAction(654)
V[20:52:49.429] ASTWorker running EnumerateTweaks on version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:49.429] --> reply:textDocument/codeAction(654) 0 ms
V[20:52:49.429] >>> {"id":654,"jsonrpc":"2.0","result":[]}

I[20:52:49.429] --> textDocument/clangd.fileStatus
V[20:52:49.429] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:50.044] <<< {"id":655,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:50.044] <-- textDocument/documentLink(655)
V[20:52:50.044] ASTWorker running DocumentLinks on version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:50.044] --> reply:textDocument/documentLink(655) 0 ms
V[20:52:50.044] >>> {"id":655,"jsonrpc":"2.0","result":[]}

I[20:52:50.044] --> textDocument/clangd.fileStatus
V[20:52:50.044] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:50.077] <<< {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:50.077] <-- textDocument/didSave
I[20:52:50.077] File version went from 183 to 183
I[20:52:50.077] --> textDocument/clangd.fileStatus
V[20:52:50.077] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"file is queued","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

I[20:52:50.137] ASTWorker building file d:\Code\cpp_proj\test.cpp version 183 with command 
[D:/Code/cpp_proj/cmake-build-debug]
"D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64\\cl.exe" --driver-mode=cl /nologo /TP /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd "/FoCMakeFiles\\cpp_proj.dir\\test.cpp.obj" /FdTARGET_COMPILE_PDB /FS -c "-resource-dir=D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6" -- "d:\\Code\\cpp_proj\\test.cpp"
V[20:52:50.154] Driver produced command: cc1 -cc1 -triple x86_64-pc-windows-msvc19.34.31935 -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -relaxed-aliasing -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -mllvm -x86-asm-syntax=intel -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -D_DEBUG -D_MT -D_DLL --dependent-lib=msvcrtd --dependent-lib=oldnames -stack-protector 2 -fcxx-exceptions -fexceptions -fexternc-nounwind -fms-volatile -fdiagnostics-format msvc -gno-column-info -gcodeview -debug-info-kind=constructor -fcoverage-compilation-dir=D:/Code/cpp_proj/cmake-build-debug -resource-dir "D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6" -D WIN32 -D _WINDOWS -internal-isystem "D:\\Code\\llvm\\llvm-project\\llvm\\cmake-build-debug\\lib\\clang\\15.0.6\\include" -internal-isystem "D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\include" -internal-isystem "D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt" -O0 -fdeprecated-macro -fdebug-compilation-dir=D:/Code/cpp_proj/cmake-build-debug -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.34.31935 -std=c++14 -fdelayed-template-parsing -fno-inline -no-round-trip-args -faddrsig -x c++ "d:\\Code\\cpp_proj\\test.cpp"
I[20:52:50.154] --> textDocument/clangd.fileStatus
V[20:52:50.154] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

I[20:52:50.154] --> textDocument/clangd.fileStatus
V[20:52:50.154] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:50.155] Reusing preamble version 5 for version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:50.155] --> textDocument/clangd.fileStatus
V[20:52:50.155] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

I[20:52:50.155] --> textDocument/clangd.fileStatus
V[20:52:50.155] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

V[20:52:50.297] <<< {"id":656,"jsonrpc":"2.0","method":"textDocument/inlayHint","params":{"range":{"end":{"character":1,"line":6},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///d%3A/Code/cpp_proj/test.cpp"}}}

I[20:52:50.297] <-- textDocument/inlayHint(656)
V[20:52:50.297] ASTWorker running InlayHints on version 183 of d:\Code\cpp_proj\test.cpp
I[20:52:50.297] --> reply:textDocument/inlayHint(656) 0 ms
V[20:52:50.297] >>> {"id":656,"jsonrpc":"2.0","result":[]}

I[20:52:50.297] --> textDocument/clangd.fileStatus
V[20:52:50.297] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Code/cpp_proj/test.cpp"}}

**System information**

Output of clangd --version:
clangd version 15.0.6
Features: windows+debug
Platform: x86_64-pc-windows-msvc

Editor/LSP plugin:
vscode-clangd
Operating system:
Windows 11

**Comment by tom-anders** [comment]
I think this should be fixed in clangd-16: https://reviews.llvm.org/D135489

See also https://github.com/clangd/clangd/issues/586 and https://github.com/clangd/clangd/issues/170

**Comment by HighCommander4** [comment]
Indeed, this is working well in clangd-16.

**Comment by lxz12523** [comment]
Where I can find clangd-16 ?
I can get last release clangd version (15.0.6) for this website (https://github.com/clangd/clangd/releases)

**Comment by HighCommander4** [comment]
clangd-16 is not released yet. However, you can get a weekly pre-release snapshot if you'd like (scroll down on the releases page to see them, the current latest one is https://github.com/clangd/clangd/releases/tag/snapshot_20230129).
