### ISSUE TITLE
Macro proposal's CompletionItemKind should be something other than Text

### ISSUE THREAD

**Issue by traversebitree** [clangd/clangd#1484]
I suggest changing the macro prompt icon, not use "abc". It's sometimes confused with the "intelligence learning" of the user's code.

## Compare With C/C++ Plugin and Python language
![image](https://user-images.githubusercontent.com/30373236/215340200-4bdbc539-2656-4f88-9b77-d57930b8c5ba.png)

![image](https://user-images.githubusercontent.com/30373236/215340128-51ef5473-a81a-45fe-a735-6d353a4cdf03.png)

![image](https://user-images.githubusercontent.com/30373236/215340218-0e3f0c19-2549-440f-bb0f-e8c4263e9bcf.png)

**Comment by HighCommander4** [comment]
Proposed fix: https://reviews.llvm.org/D144703
