### ISSUE TITLE
How can I revise the inline snippets?

### ISSUE THREAD

**Issue by Stellarist** [clangd/clangd#1486]
For example, the snippets for template class is `ClassName<template T>`, but sometimes I want `ClassName` only(without `<template T>`, because it's easier to type `<T>` rather than delete `<typename T>`). And others like space in snippets doesn't match my own coding style.
So, I want to ask whether clangd has snippet.json like vscode's one, allowing us to revise inline snippets? Thank you.

**Comment by HighCommander4** [comment]
I'm not aware of anything like custom snippets support in clangd today.

That said, I'm not even entirely sure how to trigger the `ClassName<template T>` snippet -- can you give an example of a piece of code and what you have to type to get this?

**Comment by HighCommander4** [comment]
> And others like space in snippets doesn't match my own coding style.

We have #1235 on file for applying the project's clang-format settings to code inserted by code completion.

Until that is fixed, a workaround is to manually invoke your editor's "format document" command, or to configure your editor to perform it automatically on file-save.

**Comment by HighCommander4** [comment]
> There is a previous request on file, #1252, to add an option to have the placeholder contain only the argument name (not its type) for function arguments. I think it would make sense to extend the same behaviour to template arguments as well.

As an update to this, I wrote a [proposal](https://github.com/llvm/llvm-project/issues/63565#issuecomment-1975065771) for a configuration option that would address this request among others. Remembering this issue, I took care to have it handle both function and template argument list :) Feedback on the proposal is welcome.
