### ISSUE TITLE
In-memory caching

### ISSUE THREAD

**Issue by evur** [clangd/clangd#1493]
The `.cache` directory in the project folder causes disk-writes and is not nice to handle (shown in file listings, IDE, .gitignore). So my proposal is to make the cache in-memory.

This could be done by adding a config option for the cache directory's path, which would allow for a directory residing in a tmpfs to be specified or by adding a boolean which toggles between project and temporary directory.

**Comment by HighCommander4** [comment]
The files stored in `.cache` are the project's background index. You can disable it by passing `--background-index=false` as a command-line argument to clangd.

**Comment by evur** [comment]
Thank you! I didn't know that it's possible to disable the indexing. It would be nice to have this mentioned in the docs in relation to the `.cache` directory.
But I still think that it would be good to have an option to keep the indexing while fixing the disk problems.

**Comment by HighCommander4** [comment]
> It would be nice to have this mentioned in the docs in relation to the `.cache` directory.

The `--background-index` option is documented in `clangd --help`.

I'm not sure whether it would make sense to additionally mention it somewhere on the website, but you're welcome to suggest a change if you'd like; the website's repo is at https://github.com/llvm/clangd-www.

> But I still think that it would be good to have an option to keep the indexing while fixing the disk problems.

This would of course be technically possible, though I admit I struggle to see the use case.

As a data point, an 8000 source file codebase that I work on takes 3 hours to index (with the bottleneck being compute, not disk). If that indexing process had to be repeated every time I start my editor, that doesn't seem very useful.

**Comment by evur** [comment]
> This would of course be technically possible, though I admit I struggle to see the use case.
> 
> As a data point, an 8000 source file codebase that I work on takes 3 hours to index (with the bottleneck being compute, not disk). If that indexing process had to be repeated every time I start my editor, that doesn't seem very useful.

This makes sense to me.
The use case I had in mind would be small projects where it is unnecessary to write to disk. But I guess then it is also quick enough to regenerate it every time.

Thanks for your patience!

**Comment by HighCommander4** [comment]
One way to accomplish this without changes to clangd would be mount a RAM disk at `<project>/.cache`.

We also have #184 on file for customizing the index storage location, with that in place you could configure the index to be stored at `/path/to/ramdisk/projectN` (and then just have one RAM disk for all projects).
