### ISSUE TITLE
strcmp only exists in global namespace

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#15]
During code completion clangd does not suggest strcmp when queried under std:: scope.

```cpp
#include <cstring>
void foo() {
  std::strcm^
}
```
Above code does not yield strcmp as a completion item, whereas the one below works:
```cpp
#include <cstring>
void foo() {
  strcm^
}
```

**Comment by sam-mccall** [comment]
This is expected if we've indexed something including <string.h> but
nothing with <cstring> could this be the cause?

**Comment by kadircet** [comment]
As can be seen from the examples below code directly includes cstring. More
interestingly we got other symbols like strchr under std:: but strcmp is
missing

**Comment by kadircet** [comment]
https://reviews.llvm.org/D58341
