### ISSUE TITLE
Clangd don't recognize `-fexperimental-library`

### ISSUE THREAD

**Issue by sonder-joker** [clangd/clangd#1501]
I use clangd-17 ,clang-17 and cmake.
![image](https://user-images.githubusercontent.com/56215747/218325153-7c838f86-14b0-42a0-9763-72f5be97832e.png)
when add target attribute
```cmake
target_compile_features(project PUBLIC cxx_std_20)
target_compile_options(preject PUBLIC -stdlib=libc++)
target_compile_options(project PUBLIC -fexperimental-library)
```
and config .clangd
```yaml
CompileFlags:
  Add: -Wno-unknown-warning-option
```
![image](https://user-images.githubusercontent.com/56215747/218325344-0ec1179d-8797-4230-88b8-886192051c4f.png)

I have to use `_LIBCPP_ENABLE_EXPERIMENTAL`. Any plan support about it in clangd?

Output of `clangd --version`:clangd-17

Editor/LSP plugin:vscode

Operating system:linux

**Comment by HighCommander4** [comment]
Seems to work for me.

Can you share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs)? They might contain a clue as to what's going on.

**Comment by sonder-joker** [comment]
Thanks for your help! I found the log show extension use clangd-15
```
I[21:53:18.671] Ubuntu clangd version 15.0.0...
```
For those use remote feature of vscode should modify `clangd path` in `Remote` rather `Use`r :confused:
![image](https://user-images.githubusercontent.com/56215747/218476394-b1b73ba6-8d93-494d-a9df-774ba84820b6.png)
It work well now.
