### ISSUE TITLE
Segfault aka sig 11

### ISSUE THREAD

**Issue by Sarna555** [clangd/clangd#1502]
Recently I've started getting segfaults. It works than I make some change in code and i starts to seg fault, the code compiles with gcc-10

**Logs**
![image](https://user-images.githubusercontent.com/5701624/218721010-42db2ade-66f6-4633-b95b-1ec72219548b.png)

**System information**

Output of `clangd --version`:
clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
Editor/LSP plugin:

vim + coc-clangd
nvim + nvim-lspconfig

Operating system:
Ubuntu 22.04 LTS

**Comment by HighCommander4** [comment]
Stack trace looks similar to https://github.com/clangd/clangd/issues/1311, suggesting this is likely a crash that has been fixed in clangd 16.

Clangd 16 is not released yet but weekly snapshot builds are available at https://github.com/clangd/clangd/releases (scroll down past the releases).

**Comment by Sarna555** [comment]
ok, looks like it helps, thanks! the version I've downloaded
```
clangd version 17.0.0 (https://github.com/llvm/llvm-project 15cb5ebed7a45002abb617600ca1d6609b0dc5a9)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```
