### ISSUE TITLE
Include system files from /use/include/c++ automaticly

### ISSUE THREAD

**Issue by Fildo7525** [clangd/clangd#1503]
I have generated compile_commands.json from cmake. However, the system files are not specified in this file. Therefore when I start clangd in neovim all the system files are not included and for every file I have to write the include flags.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html
The clangd could automatically include the system files from /usr/include/c++/11 and /usr/include/<architecture>/c++/11

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Also supported in the file
[lsp.log](https://github.com/clangd/clangd/files/10732950/lsp.log)

[ERROR][2023-02-14 14:42:12] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:12.613] <-- shutdown(52)\nI[14:42:12.613] --> reply:shutdown(52) 0 ms\nI[14:42:12.613] <-- shutdown(53)\nI[14:42:12.613] --> reply:shutdown(53) 0 ms\n"
[ERROR][2023-02-14 14:42:12] .../vim/lsp/rpc.lua:733	"rpc"	"cmake-language-server"	"stderr"	"WARNING:pygls.protocol:Server shutting down. No more requests!\n"
[ERROR][2023-02-14 14:42:12] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:12.619] <-- exit\nI[14:42:12.619] LSP finished, exiting with status 0\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.141] clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)\nI[14:42:13.141] Features: linux+grpc\nI[14:42:13.141] PID: 30083\nI[14:42:13.141] Working directory: /home/fildo7525/Bakalarka/code\nI[14:42:13.141] argv[0]: clangd\nI[14:42:13.141] argv[1]: --background-index\nI[14:42:13.141] argv[2]: --clang-tidy\nI[14:42:13.141] argv[3]: --compile_args_from=filesystem\nI[14:42:13.141] argv[4]: --completion-parse=always\nI[14:42:13.141] argv[5]: --completion-style=bundled\nI[14:42:13.141] argv[6]: --debug-origin\nI[14:42:13.141] argv[7]: --function-arg-placeholders\nI[14:42:13.141] argv[8]: --header-insertion=iwyu\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.141] argv[9]: -j=4\nI[14:42:13.141] argv[10]: --query-driver=/usr/bin/g++\nI[14:42:13.141] Starting LSP over stdin/stdout\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.141] <-- initialize(1)\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.142] --> reply:initialize(1) 0 ms\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.142] <-- initialized\nI[14:42:13.142] <-- textDocument/didOpen\nI[14:42:13.143] Loaded compilation database from ./build/compile_commands.json\nI[14:42:13.143] --> window/workDoneProgress/create(0)\nI[14:42:13.143] Enqueueing 11 commands for indexing\nI[14:42:13.143] ASTWorker building file /home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/controlSW/BlackMetal.cpp version 0 with command \n[/home/fildo7525/Bakalarka/code/build/blackmetal/src/communication/controlSW]\n/usr/bin/c++ --driver-mode=g++ -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DRCUTILS_ENABLE_FAULT_INJECTION -I/home/fildo7525/Bakalarka/code/src/blackmetal/src -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/logger -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/client -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/queue -isystem /opt/ros/humble/include/rclcpp -isystem /opt/ros/humble/include/std_msgs -isystem /opt/ros/humble/include/geometry_msgs -isystem /opt/ros/humble/include/ament_index_cpp -isystem /opt/ros/humble/include/libstatistics_collector -isystem /opt/ros/humble/include/rcl -isystem /opt/ros/humble/include/rcl_interfaces -isystem /opt/ros/humble/include/builtin_interfaces -isystem /opt/ros/humble/include/rosidl_runtime_c -isystem /opt/ros/humble/include/rcutils -isystem /opt/ros/humble/include/rosidl_typesupport_interface -isystem /opt/ros/humble/include/fastcdr -isystem /opt/ros/humble/include/rosidl_runtime_cpp -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_cpp -isystem /opt/ros/humble/include/rmw -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_cpp -isystem /opt/ros/humble/include/rcl_logging_interface -isystem /opt/ros/humble/include/rcl_yaml_param_parser -isystem /opt/ros/humble/include/libyaml_vendor -isystem /opt/ros/humble/include/tracetools -isystem /opt/ros/humble/include/rcpputils -isystem /opt/ros/humble/include/statistics_msgs -isystem /opt/ros/humble/include/rosgraph_msgs -isystem /opt/ros/humble/include/rosidl_typesupport_cpp -isystem /opt/ros/humble/include/rosidl_typesupport_c -g -Wall -Wextra -Wpedantic -std=gnu++17 -o CMakeFiles/bm_controlSW.dir/BlackMetal.cpp.o -c -resource-dir=/home/fildo7525/.local/share/nvim/lsp_servers/clangd/clangd/lib/clang/15.0.6 -- /home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/controlSW/BlackMetal.cpp\nI[14:42:13.144] <-- textDocument/didOpen\nI[14:42:13.144] ASTWorker building file /home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/controlSW/BlackMetal.hpp version 0 with command inferred from /home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/controlSW/BlackMetal.cpp\n[/home/fildo7525/Bakalarka/code/build/blackmetal/src/communication/controlSW]\n/usr/bin/c++ --driver-mode=g++ -DDEFAULT_RMW_IMPLEMENTATION=rmw_fastrtps_cpp -DRCUTILS_ENABLE_FAULT_INJECTION -I/home/fildo7525/Bakalarka/code/src/blackmetal/src -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/logger -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/client -I/home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/queue -isystem /opt/ros/humble/include/rclcpp -isystem /opt/ros/humble/include/std_msgs -isystem /opt/ros/humble/include/geometry_msgs -isystem /opt/ros/humble/include/ament_index_cpp -isystem /opt/ros/humble/include/libstatistics_collector -isystem /opt/ros/humble/include/rcl -isystem /opt/ros/humble/include/rcl_interfaces -isystem /opt/ros/humble/include/builtin_interfaces -isystem /opt/ros/humble/include/rosidl_runtime_c -isystem /opt/ros/humble/include/rcutils -isystem /opt/ros/humble/include/rosidl_typesupport_interface -isystem /opt/ros/humble/include/fastcdr -isystem /opt/ros/humble/include/rosidl_runtime_cpp -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_cpp -isystem /opt/ros/humble/include/rmw -isystem /opt/ros/humble/include/rosidl_typesupport_fastrtps_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_c -isystem /opt/ros/humble/include/rosidl_typesupport_introspection_cpp -isystem /opt/ros/humble/include/rcl_logging_interface -isystem /opt/ros/humble/include/rcl_yaml_param_parser -isystem /opt/ros/humble/include/libyaml_vendor -isystem /opt/ros/humble/include/tracetools -isystem /opt/ros/humble/include/rcpputils -isystem /opt/ros/humble/include/statistics_msgs -isystem /opt/ros/humble/include/rosgraph_msgs -isystem /opt/ros/humble/include/rosidl_typesupport_cpp -isystem /opt/ros/humble/include/rosidl_typesupport_c -g -Wall -Wextra -Wpedantic -c -std=gnu++17 -resource-dir=/home/fildo7525/.local/share/nvim/lsp_servers/clangd/clangd/lib/clang/15.0.6 -- /home/fildo7525/Bakalarka/code/src/blackmetal/src/communication/controlSW/BlackMetal.hpp\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.146] <-- textDocument/documentHighlight(2)\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.146] <-- reply(0)\nI[14:42:13.146] --> $/progress\nI[14:42:13.146] --> $/progress\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.198] --> $/progress\nI[14:42:13.198] --> $/progress\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"cmake-language-server"	"stderr"	"INFO:root:cmakeExecutable=cmake, buildDirectory=\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.371] --> textDocument/publishDiagnostics\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.392] --> textDocument/publishDiagnostics\n"
[ERROR][2023-02-14 14:42:13] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[14:42:13.392] --> reply:textDocument/documentHighlight(2) 245 ms\n"

**System information**

Output of `clangd --version`:
clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

as a plugin I use the neovim native 
lspconfig.

Operating system:
Ubuntu 22.04

**Comment by HighCommander4** [comment]
I suspect you're running into #1394, a common issue on Ubuntu 22.04.

Please see https://github.com/clangd/clangd/issues/1394#issuecomment-1328676884 for available workarounds. (TL;DR: install `g++12`)

**Comment by Fildo7525** [comment]
Yes it fixed it thanks.
