### ISSUE TITLE
compile_commands.json is in .vscode directory, but it seems clangd Failed to find compilation database, 

### ISSUE THREAD

**Issue by guijiyang** [clangd/clangd#1506]
clangd cant find include header . the compile_commands.json was generated in .vscode directory, 
and clangd output like this:
` Failed to find compilation database for d:\Code\MyProject\cxx\finance\commonlib\include\Commonlib\Thread\Thread.h
I[19:15:02.213] ASTWorker building file d:\Code\MyProject\cxx\finance\commonlib\include\Commonlib\Thread\Thread.h version 1 with command clangd fallback`

it works if compile_commands.json in build directory or project directory, why cant work in .vscode directory?
`Loaded compilation database from d:\Code\MyProject\cxx\finance\commonlib\compile_commands.json
I[19:27:30.545] ASTWorker building file d:\Code\MyProject\cxx\finance\commonlib\src\MessageLoop\Task.cpp version 1 with command 
[D:\Code\MyProject\cxx\finance\commonlib`

**System information**

 clangd version 14.0.0

 vscode

windows

**Comment by HighCommander4** [comment]
The search algorithm for `compile_commands.json` is documented at https://clangd.llvm.org/installation#compile_commandsjson:

> clangd will look in the parent directories of the files you edit looking for it, and also in subdirectories named build/. For example, if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …

You can also instruct clangd to look in a custom location with the `--compile-commands-dir` command-line argument.

**Comment by guijiyang** [comment]
ok, I got it,

> The search algorithm for `compile_commands.json` is documented at https://clangd.llvm.org/installation#compile_commandsjson:
> 
> > clangd will look in the parent directories of the files you edit looking for it, and also in subdirectories named build/. For example, if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …
> 
> You can also instruct clangd to look in a custom location with the `--compile-commands-dir` command-line argument.

ok ,thanks, i got it.
