### ISSUE TITLE
use g++-12 compile with "-std=c++20"  ,but pre defined macro __cplusplus value 201402L

### ISSUE THREAD

**Issue by guijiyang** [clangd/clangd#1513]
compile_commands.json 
```json
[
{
  "directory": "/home/guijiyang/Code/cxx/My/gcommon",
  "arguments": ["g++-12", "-c", "-fPIC", "-g", "-Wall", "-Werror", "-O0", "-std=c++20", "-I/home/guijiyang/Code/cxx/My/gcommon", "-fexceptions", "-o", "build/.objs/utils/linux/x86_64/debug/gcommon/ScopeGuard.cc.o", "gcommon/ScopeGuard.cc"],
  "file": "gcommon/ScopeGuard.cc"
}]
```
with -std=c++20 still mcaro __cplusplus wrong defined value  201402L.
when I try use some traits newer than c++14 like std::is_const_v or std::is_same_v， but clangd tips dont work.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/24927925/220510089-e5c5dc41-cbec-4e01-8f8d-04ca43a509d1.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/24927925/220511709-50af0327-cced-4258-812b-424e0b7fdaa7.png">

**System information**

Output of `clangd --version`: clangd version 15.0.7

Editor/LSP plugin: vscode

Operating system: linux

**Comment by HighCommander4** [comment]
Please share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs)

**Comment by guijiyang** [comment]
> Please share [clangd logs] 
`Failed to find compilation database for /usr/local/gcc-12.2.0/include/c++/12.2.0/type_traits
I[14:23:06.684] ASTWorker building file /usr/local/gcc-12.2.0/include/c++/12.2.0/type_traits version 1 with command clangd fallback
[/usr/local/gcc-12.2.0/include/c++/12.2.0]
/usr/local/llvm-15.0.7/bin/clang -xobjective-c++-header -resource-dir=/usr/local/llvm-15.0.7/lib/clang/15.0.7 -- /usr/local/gcc-12.2.0/include/c++/12.2.0/type_traits
`

**Comment by HighCommander4** [comment]
Please see https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory

**Comment by guijiyang** [comment]
> Please see https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory

thank you , and below text to clangd arguments, it worked normally now.
`
--compile-commands-dir=/home/guijiyang/Code/cxx/My/gcommon`
