### ISSUE TITLE
No intelligent suggestion when defining the private method

### ISSUE THREAD

**Issue by traversebitree** [clangd/clangd#1520]
No intelligent suggestion when defining the private method.
**Reproduce**

_test.hpp_
```cpp
class TestClass {
private:
  int m_v1;
  int foo(int);

public:
  explicit TestClass();
  int bar(int);
};
```
_test.cpp_
```cpp
#include <test.hpp>

TestClass::TestClass() { m_v1 = 0; }
// Below is public method definition
int TestClass::bar(int param) {
  m_v1 = param;
  return m_v1;
}
// Below is private method definition, Bug is here
void TestClass::foo(int param) { m_v1 = param; }
```
![image](https://user-images.githubusercontent.com/30373236/222437861-3f943ab9-d889-4661-a0f0-4ec9468f8e0f.png)

**System information**

Output of `clangd --version`:
```txt
clangd version 16.0.0
Features: windows
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin:
- clangd
- CMake Tools

Operating system: Windows11 22621.1265

**Comment by HighCommander4** [comment]
Duplicate og #880
