### ISSUE TITLE
std::shared_ptr use break color syntax and go definition

### ISSUE THREAD

**Issue by jlmxyz** [clangd/clangd#1523]
I have a class 
```
#ifndef __factory_h__
#define __factory_h__
#include "hardware/flash.h"
#include <memory>

// fwd decl, to prevent include
class Encoder;
class uartInterface;
class cmdParser;

class Factory
{
    public : 
        static Factory& I();
        Encoder& getEncoder();
        uartInterface& getSerial();
        cmdParser& getParser();
        FlashParameters& getParams();
    protected :
        cmdParser* mParser;
        uartInterface* mSerial;
        Encoder* mEncoder;
        FlashParameters mParams;
    private :
        Factory();
};


#endif //__factory_h__
```
that I modifiy into a std::shared_ptr based one 
```
class Factory
{
    public : 
        static Factory& I();
        std::shared_ptr<Encoder> getEncoder();
        std::shared_ptr<uartInterface> getSerial();
        std::shared_ptr<cmdParser> getParser();
        std::shared_ptr<FlashParameters> getParams();
    protected :
        std::shared_ptr<cmdParser> mParser;
        std::shared_ptr<uartInterface> mSerial;
        std::shared_ptr<Encoder> mEncoder;
        std::shared_ptr<FlashParameters> mParams;
    private :
        Factory();
};
```

in constructor : 
```
Factory::Factory()
    : mParser(nullptr)
      , mSerial(nullptr)
      , mEncoder(new Encoder(*TIM1, mParams))
      , mParams(new FlashParameters())
{
...
}
```
the mEncoder, mSerial, .... are no longer syntax highligted, and a jump to definition just jump at `Factory::Factory()` line not into the header (if no std::shared_ptr, the behavior is correct)

and in code
`Factory::I().getParams()->setExtMicrostepping(32);`
I get errors  

- [clang typecheck_member_reference_suggestion] Member reference type 'std::shared_ptr<FlashParameters>' is not a pointer; did you mean to use '.'? (fix available) [E]
- [clang no_member] No member named 'setExtMicrostepping' in 'std::shared_ptr<FlashParameters>' [E]

**Logs**
I attach a log of what happens while I do the change from pointer to shared_ptr
[clangd-shared_ptr-definition.log](https://github.com/clangd/clangd/files/10892433/clangd-shared_ptr-definition.log)
and a log of errors I get when using the shared_ptr
[clangd-shared_ptr-use.log](https://github.com/clangd/clangd/files/10892434/clangd-shared_ptr-use.log)

**System information**

```
$ clangd --version
clangd version 15.0.7
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:
https://github.com/clangd/coc-clangd

Operating system:
linux (gentoo)

**Comment by HighCommander4** [comment]
The logs show that when you open up `factory.h`, clangd produces some error diagnostics, and then `Too many errors emitted, stopping now`.

This means clangd has given up trying to build an AST for the rest of the file due to the previous errors. Without an AST, features like syntax coloring and go-to-def will not work properly.

So the errors in that file need to be fixed first.

**Comment by jlmxyz** [comment]
in factory.h???? 
it's a 29 line file that I've given in the bug description, the c++ sources is 149 lines (75% comments) and compiles fine, with no error nor warning...
I can reproduce the behavior 100% : just have to take a source file with no error, all syntax coloring fine, add `#include <memory>` (until now, nothing breaks) find a pointer, make it a std::shared_ptr, and taaadaaa! everything is broken... 

I even simplified the header so that i should be trivial to parse : one include : memory, 4 fwd class déclarations, a single class : 
```
#ifndef __factory_h__
#define __factory_h__
#include <memory>

// fwd decl, to prevent include
class Encoder;
class uartInterface;
class cmdParser;
class FlashParameters;

class Factory
{
    public : 
        static Factory& I();
        std::shared_ptr<Encoder> getEncoder();
        std::shared_ptr<uartInterface> getSerial();
        std::shared_ptr<cmdParser> getParser();
        std::shared_ptr<FlashParameters> getParams();
    protected :
        std::shared_ptr<cmdParser> mParser;
        std::shared_ptr<uartInterface> mSerial;
        std::shared_ptr<Encoder> mEncoder;
        std::shared_ptr<FlashParameters> mParams;
    private :
        Factory();
};


#endif //__factory_h__
```
same source but with standard pointers
```
#ifndef __factory_h__
#define __factory_h__

// fwd decl, to prevent include
class Encoder;
class uartInterface;
class cmdParser;
class FlashParameters;

class Factory
{
    public : 
        static Factory& I();
        Encoder* getEncoder();
        uartInterface* getSerial();
        cmdParser* getParser();
        FlashParameters* getParams();
    protected :
        cmdParser* mParser;
        uartInterface* mSerial;
        Encoder* mEncoder;
        FlashParameters* mParams;
    private :
        Factory();
};


#endif //__factory_h__
```

in fact... just have to comment `#include <memory>` to have  `Too many errors emitted, stopping now` diseapear.... source compiles fine in gcc or clang... no error, no warning... I'm updating system right now, clang-15 should be available soon... will see if issue is still here...

**Comment by HighCommander4** [comment]
> in fact... just have to comment `#include <memory>` to have `Too many errors emitted, stopping now` diseapear.... 

This suggests that there is a configuration issue in your project that is causing your standard library headers to not be parsed correctly.

> source compiles fine in gcc or clang... no error, no warning

That the source compiles fine with clang is a good sign! Should be just a matter of making sure that clangd is seeing all the same flags (`-I` flags, `-D` flags, etc.) that are used when building the file.

**Comment by jlmxyz** [comment]
how can I prevent clang to provide builtin defines?  I try to compile using the same flags than the crosscompiler, but some source require GCC so I had to create an include file from GCC builtin's defines, but they conflict with clang builtin defines....

**Comment by HighCommander4** [comment]
> how can I prevent clang to provide builtin defines?

Unfortunately, based on the discussion in https://github.com/clangd/clangd/issues/533, I don't think this is possible.

Since clangd uses clang's compiler engine, being able to get clang to accept your code somehow (at least in the front-end) is basically a requirement. Clang does support many embedded targets and you can often get it to work with cross-compiled code with the right flags.

One thing to check: are you using `--query-driver` as discussed in https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc? This is usually a necessary step for working with a cross-compiler (but not always sufficient).

> some source require GCC so I had to create an include file from GCC builtin's defines, but they conflict with clang builtin defines....

One idea here might be to avoid using _all_ of GCC's builtin defines whole-sale, and just use particular ones necessary for the non-portable code in your project.

**Comment by jlmxyz** [comment]
really... something has to be done about clang's buildin defines and parsing of header using project's .clangd.....
looks....
here is what I get if I don't strip clang's buildin define and replace them by project's build in compiler defines

![image](https://user-images.githubusercontent.com/40383940/228008271-2f37c798-66b5-42fa-8775-4ee4561469da.png)

clangd is not even beeing able to handle the std::shared_ptr as a pointer...
however, if I create a compiler_defines.h by undef all clang builtins and add all the gcc crosscompiler builtins as in the comment I made in #533, the shared_ptr don't create anymore issue....
even if I have other issues because if I use the g++ command to get the buildin, it don't define `__cplusplus` but `gcc -xc++` does....
```
$ /home/xxx/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-g++ -dM -E - < /dev/null | grep __cplusplus
$ /home/xxx/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc -xc++ -dM -E - < /dev/null | grep __cplusplus
#define __cplusplus 201402L
```

**Comment by jlmxyz** [comment]
and in a way, I'm puzzled that this issue wasn't foreseen with creating clangd... in a way clangd impress me a lot! it's by far the best tool I used to help C/C++ dev, it's accurate, fast, and usable with vim... but it is obvious that using clang to parse and provide errors will barely works if the real compiler's feature aren't the same as the clang (which will be of course true since gcc dev won't go at same speed as clang dev, and same for any compiler, intel, cross compiler and so on) so it's obvious that anything "builtin" will have side effect and that anything builtin clang has to be cleared and replaced by the real compiler's builtins...

**Comment by HighCommander4** [comment]
>    * they both compile fine on host using the host's compilers, eg gcc or clang,  but I have to "break target's dependencies" eg remove the target's header (or stub it) and then gcc and clang can use their respective headers....

One thing to consider is, maybe this "host compiler mode" is good enough to use with clangd for development purposes?

If you need to stub a header for clangd's purposes, one way to do it is with a clangd-specific macro defined in `.clangd`:

.clangd:
```yaml
CompileFlags:
  Add: [-D__CLANGD__]
```

source file in your project:
```c++
#ifdef __CLANGD__
  // include stub header
#else
  // include real header
#endif
```

I realize this is a workaround rather than a proper solution, but perhaps it's useful until the underlying issues like #533 are resolved.

**Comment by jlmxyz** [comment]
this will be tooooo much work... I made it for some sources, just for the investigation, but it's huge work and also create compile time errors when developing (since using stubs clangd isn't able to find "deep" issues).... right now, the solution I found using compile_commands.json seding and compiler builtin header creation seems to work... it's a workaround... ugly but seems to work... 

I think this issue and #1438 can be closed as a related to #907 and #533 since there is the workaround described into https://github.com/clangd/clangd/issues/533#issuecomment-1485572563

**Comment by jlmxyz** [comment]
closed as a related to https://github.com/clangd/clangd/discussions/907 and https://github.com/clangd/clangd/issues/533 since there is the workaround described into https://github.com/clangd/clangd/issues/533#issuecomment-1485572563

**Comment by HighCommander4** [comment]
Understood. My only other thought, then, is: if there are things missing in clang upstream that prevent your project from being fully portable across gcc and clang (when targeting the embedded platform, not the host), it's worth making sure there are bugs on file for those things as well.
