### ISSUE TITLE
"Auto Fix" does not apply multiple quick-fixes

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1536]
**Steps to reproduce**

 1. In a client that supports an [Auto Fix](https://github.com/clangd/clangd/issues/830#issuecomment-1457716457) command, such as VSCode, open a file containing the following:

    ```c++
    #include <stdio.h>

    int main() {
      unsigned long a = 1, b = 2;
      printf("%llu", a);
      printf("%llu", b);
    }
    ```
2. Observe that there are two diagnostics on lines 5 and 6, each with a quick-fix.
3. Select lines 5 and 6 (or the whole file) in a single selection.
4. Invoke the "Auto Fix" command on the selection.

**Expected results**

Both quick-fixes are applied.

**Actual results**

No quick-fixes are applied. VSCode reports that none are available.

If only one of line 5 or 6 is individually selected, the quick fix on that line is applied by "Auto Fix".

**Comment by HighCommander4** [comment]
As discussed [here](https://github.com/clangd/clangd/issues/830#issuecomment-1457716457), Auto Fix only applies those quick-fixes with `CodeAction.isPreferred == true`.

In the case where the selection includes multiple quick-fixes, the `isPreferred` flag is not set on any of them.

Clangd's logic for computing the `isPreferred` flag in the response to the `textDocument/codeAction` request is [here](https://searchfox.org/llvm/rev/2f887c9a760dfdffa584ce84361912fe122ad79f/clang-tools-extra/clangd/ClangdLSPServer.cpp#1005,1018). It sets `isPreferred == true` only in the case where there is a single quick-fix in the entire response.

I believe what we want to do instead is set it for all quick-fixes which are the only quick-fix for their corresponding diagnostic.

**Comment by cacosub7** [comment]
i'm wondering that is there have possibility to fix this issure without recompile clangd?

**Comment by HighCommander4** [comment]
> i'm wondering that is there have possibility to fix this issure without recompile clangd?

The fix will require a clangd change, so making use of it will require an updated clangd.

We do provide weekly snapshots builds on our [releases](https://github.com/clangd/clangd/releases) page (and, on Linux, apt.llvm.org provides nightly packages that include clangd), so you don't have to compile it yourself.

**Comment by cacosub7** [comment]
We are developing on a somewhat outdated Centos2.6 system. Previously, we found that the dependency library versions were incorrect when using clangd on the [releases page](https://github.com/clangd/clangd/releases) (updating the corresponding dependency libraries directly would cause issues with basic commands such as 'ls'). Therefore, we had to recompile and rebuild the entire LLVM codebase in order to use clangd. In this situation, can we directly download a clangd from the [releases page ](https://github.com/clangd/clangd/releases)and replace the local one, as you suggested?

**Comment by HighCommander4** [comment]
> In this situation, can we directly download a clangd from the [releases page ](https://github.com/clangd/clangd/releases)and replace the local one, as you suggested?

I'm not sure, but my guess is probably not?

You could consider backporting the fix to your local LLVM checkout to minimize the amout of rebuilding.

**Comment by cacosub7** [comment]
Okay, please let me know here if the fix is completed.

**Comment by torshepherd** [comment]
Are there any updates on this issue?

**Comment by HighCommander4** [comment]
Based on our findings in https://github.com/llvm/llvm-project/pull/79448, this issue is invalid: "Auto fix" is only intended to fix one diagnostic at a time. As such, whether clangd sets the `isPreferred` flag when returning fixes for multiple diagnostics is not very interesting.

Instead, the use case of applying all suitable quick-fixes in a file can be supported via the "Fix all" command. Support for this is tracked in #1446.
