### ISSUE TITLE
No missing include diagnostics for macro symbol usage.

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#1538]
```
// foo.h
#pragma once
#define FOO 1

// all.h
#pragma once
#include "foo.h"

// main.cc
#include "all.h"
int b = FOO; 
```
clangd fails to emit a missing-include `foo.h` for the macro `FOO` usage in `main.cc`

**Comment by VitaNuo** [comment]
The reason for this is that the include-cleaner library lists `all.h` as provider for `FOO` in this setup.
The list of `FOO` providers (as returned from the include-cleaner library): [`foo.h`, `main.cc`, `all.h`].

**Comment by VitaNuo** [comment]
Fixed in https://reviews.llvm.org/D146727.
