### ISSUE TITLE
Clang-format error: unknown enumerated scalar SpaceBeforeParens: Custom

### ISSUE THREAD

**Issue by alexolog** [clangd/clangd#1542]
When trying to format a C++ file from within Visual Studio Code with the clangd addon, and using clang-format 15.0.6 or 15.0.7 that was previously installed using homebrew (on Mac OSX), I get an error saying:
```
error: unknown enumerated scalar
SpaceBeforeParens: Custom
```
According to documentation, this option is valid in version 15

**Comment by sam-mccall** [comment]
You're probably using Apple's forked version of clangd, they have a different version scheme, it's not actually version 15.

(Clangd does not use any external clang-format program)

**Comment by sam-mccall** [comment]
Try downloading the release from github.com/clangd/clangd/releases
