### ISSUE TITLE
[misc-definitions-in-headers] incorrectly warns definition in unnamed namespace

### ISSUE THREAD

**Issue by namniav** [clangd/clangd#1543]
Clangd incorrectly warns definition in unnamed namespace in header file.
```c++
// test.hpp
namespace a {
  namespace  /*b*/  {
    static int c[[maybe_unused]] = 42; // even static doesn't help
  }
}
```
```c++
test.hpp|3 col 16 warning| Variable 'c' defined in a header file; variable definitions in header files can lead to ODR violations [misc-definitions-in-headers]
```
However, this only happens in unnamed namespace. If I uncomment `b`, the warning is gone.

**System information**

Output of `clangd --version`:
```
Homebrew clangd version 15.0.7
Features: mac+xpc
Platform: arm64-apple-darwin21.4.0
```
Editor/LSP plugin: VIM 9.0 + YouCompleteMe
Operating system: MacOS

**Comment by i-ky** [comment]
This should probably be reported in [llvm/llvm-project](https://github.com/llvm/llvm-project).

**Comment by namniav** [comment]
Okey, I have reported there. Thanks.
