### ISSUE TITLE
False positive error: Public using declaration of a protected conversion member function

### ISSUE THREAD

**Issue by SethughesEFJ** [clangd/clangd#1544]
clangd reports an error when using a protected implicit conversion function from a base class when it is made available by a public using declaration in the child class. A protected member access error is reported, but g++ and clang++ both compile the code and the program output is as expected. Below is a snippet to reproduce:

```c++
#include <iostream>

class A
{
public:
   A(int value) : data(value) {}

protected:
   int get() { return data; }
   operator int &() { return data; };

private:
   int data;
   // A a;
};

class B : private A
{
public:
   B(int value) : A(value) {}

   using A::get;
   using A::operator int &;
};

int main(int argc, char *argv[])
{
   B b(10);
   std::cout << b.get() << std::endl;
   //           ^~~~~~~ Fine
   std::cout << b << std::endl;
   //           ^~ Error
   // protected function "A::operator int &" (declared at line 18) is not accessible through a "B" pointer or object

   return 0;
}
```

**Logs**

There are no clangd errors in output.

**System information**

Output of `clangd --version`:
```sh
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:
VSCode 1.76.2
WSL Extension
C/C++ (Microsoft) Extension

Operating system:
WSL Ubuntu 22.04
Windows 10

**Comment by HighCommander4** [comment]
This error ("protected function ... is not accessible through") is not produced by clangd. Searching around a bit [suggests](https://stackoverflow.com/questions/26143344/cant-call-base-class-constructor-with-brace-initialization-intellisense-error) that it's produced by Microsoft's Intellisense engine.

Do you have Microsoft's C/C++ plugin installed in addition to clangd? If so, you may want to disable it, or at least the Intellisense part.
