### ISSUE TITLE
Don't treat inactive preprocessor regions as comments

### ISSUE THREAD

**Issue by Ollrogge** [clangd/clangd#1545]
Is there a way to disable the [syntax highlighting of inactive regions](https://releases.llvm.org/12.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html#semantic-highlighting) as comments ? I would like to have syntax highlighting also in these regions.

**Comment by HighCommander4** [comment]
I wrote a [patch](https://reviews.llvm.org/D143974) implementing a protocol extension that allows clients to combine client-side syntax highlighting in inactive regions with a server style (e.g. different colour background, or reduced opacity) that indicates the region is inactive.

The extension requires client-side support, and I've implemented such support for VSCode in https://github.com/clangd/vscode-clangd/pull/193. Patches adding support in other clients are welcome.

**Comment by Ollrogge** [comment]
Ahh nice :) So I can close this issue I guess.
