### ISSUE TITLE
Auto Fix match errors

### ISSUE THREAD

**Issue by lalala-233** [clangd/clangd#1547]
If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

This is the example

```cpp
bool is_type_equal(auto typeA, auto typeB)
{
    if(typeid(typeA) == typeid(typeB))
    {
        return true;
    }
    else
    {
        return false;
    }
}
```

Yes, I don't include `<typeinfo>`. And clangd tell me that `You need to include <typeinfo> before using the 'typeid' operator (fix available)`

So I use the auto fix.

Why it includes `<typeid>`? I have never seen this.

**System information**

Output of `clangd --version`:    

```bash
clangd version 15.0.7
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin: VS code

Operating system: ArchLinux

**Comment by HighCommander4** [comment]
This has been fixed in #1449. The fix will appear in clangd 16.
