### ISSUE TITLE
clangd completions mark macros as text

### ISSUE THREAD

**Issue by UtkarshVerma** [clangd/clangd#1566]
**Problem description**
`clangd` completions mark macros as plain text for me. I believe they should be marked as a "Constant" at least, because it is hard to segregate macros from the word completions presented to me based on my buffer.

![image](https://user-images.githubusercontent.com/31820255/229328497-61c910e9-8265-4675-ad8b-cfbbab199cc7.png)

**System information**
Output of `clangd --version`:
15.0.7

Editor/LSP plugin:
nvim v0.8.3 with nvim-lspconfig and clangd

Operating system:
Arch Linux

**Comment by HighCommander4** [comment]
I've recently fixed this in #1484
