### ISSUE TITLE
arm  compiler reporting unknown type name '__Int8x8_t'

### ISSUE THREAD

**Issue by lichjian** [clangd/clangd#1588]
V[15:39:37.337] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:38:9:unknown type name '__Int8x8_t'
V[15:39:37.347] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:39:9:unknown type name '__Int16x4_t'
V[15:39:37.361] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:40:9:unknown type name '__Int32x2_t'; did you mean '__int32_t'?
V[15:39:37.361] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/bits/types.h:41:20:'__int32_t' declared here
V[15:39:37.376] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:41:9:unknown type name '__Int64x1_t'; did you mean '__int64_t'?
V[15:39:37.376] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/bits/types.h:44:25:'__int64_t' declared here
V[15:39:37.391] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:42:9:unknown type name '__Float16x4_t'
V[15:39:37.403] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:43:9:unknown type name '__Float32x2_t'
V[15:39:37.421] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:44:9:unknown type name '__Poly8x8_t'
V[15:39:37.435] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:45:9:unknown type name '__Poly16x4_t'
V[15:39:37.449] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:46:9:unknown type name '__Uint8x8_t'
V[15:39:37.469] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:47:9:unknown type name '__Uint16x4_t'
V[15:39:37.484] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:48:9:unknown type name '__Uint32x2_t'
V[15:39:37.500] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:49:9:unknown type name '__Float64x1_t'
V[15:39:37.514] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:50:9:unknown type name '__Uint64x1_t'
V[15:39:37.527] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:51:9:unknown type name '__Int8x16_t'; did you mean '__int16_t'?
V[15:39:37.527] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/bits/types.h:39:26:'__int16_t' declared here
V[15:39:37.539] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:52:9:unknown type name '__Int16x8_t'
V[15:39:37.556] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:53:9:unknown type name '__Int32x4_t'; did you mean '__int32_t'?
V[15:39:37.556] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/bits/types.h:41:20:'__int32_t' declared here
V[15:39:37.569] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:54:9:unknown type name '__Int64x2_t'; did you mean '__int64_t'?
V[15:39:37.569] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/bits/types.h:44:25:'__int64_t' declared here
V[15:39:37.589] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:55:9:unknown type name '__Float16x8_t'; did you mean '__SVFloat16_t'?
V[15:39:37.589] Ignored diagnostic. '__SVFloat16_t' declared here
V[15:39:37.602] Ignored diagnostic. gcc-aarch64-linux-gnu../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h:56:9:unknown type name '__Float32x4_t'
V[15:39:37.612] Ignored diagnostic. too many errors emitted, stopping now

**Comment by zyn0217** [comment]
Next time please report issue in English.

Translated title:
ARM compiler keeps reporting "unknown type name '__Int8x8_t'"

Could you please provide more information about compiler command and clangd version with reduced code snippet if possible?

**Comment by lichjian** [comment]
> Next time please report issue in English.
> 
> Translated title: ARM compiler keeps reporting "unknown type name '__Int8x8_t'"
> 
> Could you please provide more information about compiler command and clangd version with reduced code snippet if possible?

V[16:17:55.164] <<< {"id":39,"jsonrpc":"2.0","method":"shutdown"}

I[16:17:55.165] <-- shutdown(39)
I[16:17:55.165] --> reply:shutdown(39) 0 ms
V[16:17:55.165] >>> {"id":39,"jsonrpc":"2.0","result":null}

V[16:17:55.239] <<< {"jsonrpc":"2.0","method":"exit"}

I[16:17:55.239] <-- exit
I[16:17:55.240] LSP finished, exiting with status 0
The flag `-clang-tidy-checks` is obsolete and ignored.
I[16:17:55.263] clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)
I[16:17:55.263] Features: linux+grpc
I[16:17:55.263] PID: 981060
I[16:17:55.263] Working directory: /home/lcj/code/v3/
I[16:17:55.263] argv[0]: /home/lcj/clangd_15.0.6/bin/clangd
I[16:17:55.263] argv[1]: --query-driver=/opt/gcc-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
I[16:17:55.263] argv[2]: --background-index
I[16:17:55.263] argv[3]: --clang-tidy
I[16:17:55.263] argv[4]: --log=verbose
I[16:17:55.263] argv[5]: --all-scopes-completion
I[16:17:55.263] argv[6]: --completion-style=detailed
I[16:17:55.263] argv[7]: --header-insertion=never
I[16:17:55.263] argv[8]: --clang-tidy-checks=cppcoreguidelines-*,performance-*,bugprone-*,portability-*,modernize-*,google-*
I[16:17:55.263] argv[9]: --fallback-style=file
I[16:17:55.263] argv[10]: -j=6
V[16:17:55.263] User config file is /home/lcj/.config/clangd/config.yaml
I[16:17:55.263] Starting LSP over stdin/stdout
..................................
I[16:17:55.333] Enqueueing 277 commands for indexing
V[16:17:55.358] System include extraction: target extracted: "aarch64-linux-gnu"
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/backward
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/include
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include
V[16:17:55.358] System include extraction: adding  /usr/include
I[16:17:55.358] System includes extractor: successfully executed /home/lcj/gcc-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
	got includes: "/home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/backward, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/include, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include, /usr/include"
	got target: "aarch64-linux-gnu"
V[16:17:55.358] System include extraction: target extracted: "aarch64-linux-gnu"
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/backward
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/include
V[16:17:55.358] System include extraction: adding  /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include
V[16:17:55.358] System include extraction: adding  /usr/include
I[16:17:55.358] System includes extractor: successfully executed /home/lcj/gcc-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
	got includes: "/home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include/c++/9/backward, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/include, /home/lcj/gcc-aarch64-linux-gnu/bin/../lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/include, /usr/include"
	got target: "aarch64-linux-gnu"
........................................
I[16:17:55.305] --> $/progress
V[16:17:55.305] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}

I[16:17:55.306] Loaded compilation database from /home/lcj/code/v3/build/compile_commands.json
V[16:17:55.306] Broadcasting compilation database from /home/lcj/code/v3/build/


**Under the project directory file  .clangd content is**
CompileFlags:                             
    CompilationDatabase: /home/lcj/code/v3/build/

**Comment by lichjian** [comment]
V[18:00:52.218] Dropped diagnostic: /home/lcj/code/v3/build/../test.h: 'Reset' overrides a member function but is not marked 'override'
V[18:00:52.226] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int8x8_t'
V[18:00:52.233] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int16x4_t'
V[18:00:52.240] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int32x2_t'; did you mean '__int32_t'?
V[18:00:52.249] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int64x1_t'; did you mean '__int64_t'?
V[18:00:52.258] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Float16x4_t'
V[18:00:52.266] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Float32x2_t'
V[18:00:52.273] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Poly8x8_t'
V[18:00:52.281] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Poly16x4_t'
V[18:00:52.288] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Uint8x8_t'
V[18:00:52.298] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Uint16x4_t'
V[18:00:52.306] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Uint32x2_t'
V[18:00:52.315] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Float64x1_t'
V[18:00:52.324] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Uint64x1_t'
V[18:00:52.334] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int8x16_t'; did you mean '__int16_t'?
V[18:00:52.343] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int16x8_t'
V[18:00:52.349] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int32x4_t'; did you mean '__int32_t'?
V[18:00:52.357] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Int64x2_t'; did you mean '__int64_t'?
V[18:00:52.357] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Float16x8_t'; did you mean '__SVFloat16_t'?
V[18:00:52.374] Dropped diagnostic: /home/lcj/gcc-aarch64-linux-gnu//bin/../lib/gcc-cross/aarch64-linux-gnu/9/include/arm_neon.h: unknown type name '__Float32x4_t'
V[18:00:55.195] indexed preamble AST for /home/lcj/code/v3/input.h version 1:
  symbol slab: 50515 symbols, 14430648 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 4366 relations, 139288 bytes

**arm_ neon. h used aarch64 instead of using clang，this is the possibility of causing problems
Is there any way to force the program to use clang include**

**Comment by zyn0217** [comment]
> Is there any way to force the program to use clang include

Sorry I'm blind to ARM-based development, but I saw that you have run clangd with `--query-driver=/opt/gcc-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++`. This might be reason why Clangd use headers from GCC rather than Clang.
