### ISSUE TITLE
Building vscode-clangd gives error: "Couldn't detect the repository where this extension is published."

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#159]
I used to be able to build vscode-clangd locally by running `vsce package` in `clang-tools-extra/clangd/clients/clangd-vscode`.

However, recently that started giving the following error:

```
ERROR  Couldn't detect the repository where this extension is published. 
The image 'doc-assets/complete.png' will be broken in README.md.
Please provide the repository URL in package.json or use the
--baseContentUrl and --baseImagesUrl options.
```

Can we avoid this error, or provide a script to build the plugin that provides these options?

**Comment by hokein** [comment]
Yes, we start encountering it after we added the screenshots to the readme. It informs that the screenshots in the readme would not be rendered correctly in the VSCode market. 

You could suppress the error by using the command: `vsce package --baseImagesUrl https://raw.githubusercontent.com/llvm/llvm-project/master/clang-tools-extra/clangd/clients/clangd-vscode/` which is documenting in [DEVELOPING.md](https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/clients/clangd-vscode/DEVELOPING.md).

I think it makes sense to add a wrap command e.g. `npm run package` in the `package.json`.

**Comment by hokein** [comment]
After rL372980, you could run the command `npm run package` to build the extension locally.
