### ISSUE TITLE
included file <bits/stl_set.h> emit error

### ISSUE THREAD

**Issue by iaIm14** [clangd/clangd#1613]
Hi, I'm working on my Linux Fedora 36 machine, and I installed gcc-c++ (using `dnf install gcc-c++-12.2.1-4.fc36.x86_64`) to compile my program. I'm using Visual Studio Code with the `llvm-vs-code-extensions.vscode-clangd` extension, and I added `-I/usr/include/c++/12` to the user configuration file of the clangd extension. However, when I include the file <bits/stl_set.h> (absolute path = `/usr/include/c++/12/bits/stl_set.h`), clangd reports unexpected errors from the header file. Specifically, the error looks like:
```txt
In included file: no template named 'less' in namespace 'std' in line 92 
```
the header file's content:
```c++
  template<typename _Key, typename _Compare = std::less<_Key>,
	   typename _Alloc = std::allocator<_Key> >
    class set ...
```

**System information**

Output of `clangd --version`:
clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
Editor/LSP plugin:
VSCode + clangd 
Operating system:
Linux fedora 6.2.10-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  6 23:20:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zyn0217** [comment]
> However, when I include the file <bits/stl_set.h> (absolute path = /usr/include/c++/12/bits/stl_set.h)

Sorry but why would you consider including an internal header of libstdc++?
