### ISSUE TITLE
Incorrect presentation of inactive region highlight range

### ISSUE THREAD

**Issue by jay-zhou-yan** [clangd/clangd#1631]
Many thanks to @HighCommander4 for bringing support to inactive region highlight.

I manually compiled the latest [vscode-clangd with support inactive region highlight feature](https://github.com/clangd/vscode-clangd/commit/c03cf78a300895ddb51ff6cabd24b24e3b143146) and the lastest [llvm 17](https://github.com/llvm/llvm-project/commit/7ab9478560abb0750bc1f4c1bc8ca0462b0a2fef),  when I used the newly compiled vscode-clangd extension and llvm 17, I found that for the most part, this function worked fine, but when I used this function to view the source code of the libiconv library, incorrect display scope of inactive region will occur, as shown in the following figure on remote linux,
![2023-05-10_171828](https://github.com/clangd/vscode-clangd/assets/40359079/019462de-fe47-4555-8262-2af68ed912e0)

A problem like the one below appears on windows,
![windows](https://github.com/clangd/vscode-clangd/assets/40359079/bd99d74f-d629-4f42-8e24-d8400b5a706b)

The test code is as follows,
[libiconv_test.tar.gz](https://github.com/clangd/vscode-clangd/files/11440329/libiconv_test.tar.gz)

Could anyone help with a solution to fix this problem? Thank you very much.

Extension version: 0.1.25
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 6.2.9-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.46GB free)|
|Process Argv|E:\\project\\git\\vscode-clangd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: openSUSE|
|OS|Linux x64 6.2.9-1-default|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (10 x 2111)|
|Memory (System)|1.91GB (0.91GB free)|
|VM|100%|
</details>

**Comment by HighCommander4** [comment]
Transferred to clangd repo as this is a server-side issue.

**Comment by HighCommander4** [comment]
I've fixed this issue before: https://github.com/clangd/clangd/issues/602

But the fix needs to be applied again to the `textDocument/inactiveRegions` codepath.

**Comment by jay-zhou-yan** [comment]
Thanks @HighCommander4 for your answer.

BTW, I don't know if the `#endif` syntax highlighted incorrectly in the second image on windows is the same problem as `#elif` in the first image

**Comment by HighCommander4** [comment]
> BTW, I don't know if the `#endif` syntax highlighted incorrectly in the second image on windows is the same problem as `#elif` in the first image

Not sure what's wrong there, the `#else` branch there is active.

**Comment by jay-zhou-yan** [comment]
> > BTW, I don't know if the `#endif` syntax highlighted incorrectly in the second image on windows is the same problem as `#elif` in the first image
> 
> I don't see anything wrong there, the `#else` branch there is active.

I found the cause of this problem,   
clangd of my windows OS has not been updated to clangd17 with support inactive region highlight feature, sorry for this.

There should be only the following question you mentioned.

> I've fixed this issue before: #602
> 
> But the fix needs to be applied again to the `textDocument/inactiveRegions` codepath.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D151190)

**Comment by jay-zhou-yan** [comment]
Thanks for @HighCommander4 !

I used the latest patch D151190 that [\[clangd\] Do not end inactiveRegions range at position 0 of line](https://reviews.llvm.org/D151190) and tested the following results,
![test](https://github.com/clangd/clangd/assets/40359079/aa21f4f4-9e32-4c92-80ab-365c47f43f1d)

The actual desired effect is as follows,
![expected](https://github.com/clangd/clangd/assets/40359079/d1cd6d39-79c5-491a-b513-2dc98730d6dd)

Is it possible for all `#ifdef` `#elif` `#else` `#endif` to be syntactically highlighted, only for the contents to become inactive?

I see [vscode-cpptools](https://github.com/Microsoft/vscode-cpptools)  showing the same effect as I expected, which also ensures that `#ifdef` `#elif` `#else` `#endif` is consistent in several situations.

**Comment by HighCommander4** [comment]
The reason for the current behaviour is: for a given inactive region, the preprocessor directives at the beginning and the end are excluded from the inactive region, but any preprocessor directives in the middle of the inactive region remain included.

> Is it possible for all `#ifdef` `#elif` `#else` `#endif` to be syntactically highlighted, only for the contents to become inactive?

It's technically possible, though it would require additional implementation work to identify the locations of those directives in the middle of an inactive region, and split the region into multiple regions that exclude them. I'm incline to leave that for another issue (please feel free to file one).

**Comment by jay-zhou-yan** [comment]
Thanks for @HighCommander4 !

I have left two issues(#1661 , #1664 ) related to this.
