### ISSUE TITLE
Propose a new inlay hint that marks the declared name of a definition

### ISSUE THREAD

**Issue by daiyousei-qz** [clangd/clangd#1634]
```
void foo() {
} // foo
```
An example is shown above where we could add "// foo" to the end of function definition. This is helpful to identify the end of a long function. Also, the idea applies to struct/class/namespace definition as well

**Comment by daiyousei-qz** [comment]
This is actually very easy to implement. A prototype implementation is at https://github.com/daiyousei-qz/llvm-project/tree/inlay_hint_end_function.

![image](https://github.com/clangd/clangd/assets/12378019/43d20cd4-73e7-4aba-a714-c61dfe770c40)

**Comment by zyn0217** [comment]
As a vscode user, I suppose I could always resort to the breadcrumb bar.
![image](https://github.com/clangd/clangd/assets/117258288/f4a096b2-de65-49af-813a-5ff8f81802c4)
Not sure if other editors offer a feature like that.

**Comment by daiyousei-qz** [comment]
Yes, we can. Also, stickySchroll feature in vscode could also help identify the context. However, have an inlay hint there could make the boundary more identifiable since it is right in the place where the definition ends. In practice, in LLVM codebase we are already adding "// namespace XX" as part of the code, so I suppose this is reasonable feature to add.

Of course, we'll have more details to discuss about when we should add the inlay hints if we are moving forward with this feature. Namely,
- What if the definition only consumes one line
- What if user already put manual annotation there
- What if the definition is a fairly short one or even an empty one
- .etc

**Comment by tom-anders** [comment]
> Yes, we can. Also, stickySchroll feature in vscode could also help identify the context. However, have an inlay hint there could make the boundary more identifiable since it is right in the place where the definition ends. In practice, in LLVM codebase we are already adding "// namespace XX" as part of the code, so I suppose this is reasonable feature to add.
> 
> Of course, we'll have more details to discuss about when we should add the inlay hints if we are moving forward with this feature. Namely,
> 
> * What if the definition only consumes one line
> * What if user already put manual annotation there
> * What if the definition is a fairly short one or even an empty one
> * .etc

Rust-analyzer has already implemented this same feature, so maybe it would we helpful to look at their implementation regarding these details

**Comment by sam-mccall** [comment]
This seems reasonable to me.

> What if the definition only consumes one line
>
> What if the definition is a fairly short one or even an empty one

As a first cut I'd try adding it whenever the opening and closing brace are on different lines, and see whether that feels too noisy.

> What if user already put manual annotation there

For param etc hints, we approx-parse `/*foo=*/` type comments and suppress if they match the hint we'd generate, probably best to be consistent. Namespace comments are the most important because clang-format adds them.

**Comment by daiyousei-qz** [comment]
Hey, I submitted a review at https://reviews.llvm.org/D150635. Also, git branch is at https://github.com/daiyousei-qz/llvm-project/tree/inlay_hint_end_function in case anyone is interested to try it out.

![image](https://github.com/clangd/clangd/assets/12378019/778cfbbb-d22a-4930-ad55-4c1d90236e43)
It roughly looks like what's shown above. Forgive the verboseness to short the image. The minimal lines of definition for this to shown is configurable so in practice it should look better.

- Currently it's shown before ';' in a form like a comment. It's done so because technically ';' is part of the declarator instead of the type declaration. I'm okay with that, but comments are welcome.
- What should be the default value for minimal required lines for definitions? 1 is obviously too verbose as shown above. 2? 10? 100?

**Comment by tom-anders** [comment]
> * Currently it's shown before ';' in a form like a comment. It's done so because technically ';' is part of the declarator instead of the type declaration. I'm okay with that, but comments are welcome.

Any reason for using the `/* */` style instead of `//` ?

> * What should be the default value for minimal required lines for definitions? 1 is obviously too verbose as shown above. 2? 10? 100?

For rust-analyzer apparently it's 25:

```
rust-analyzer.inlayHints.closingBraceHints.minLines (default: 25)
Minimum number of lines required before the } until the hint is shown (set to 0 or 1 to always show them).
```
https://rust-analyzer.github.io/manual.html#inlay-hints

**Comment by daiyousei-qz** [comment]
> Any reason for using the /* */ style instead of // ?
Because a trailing ';' may follow the hint, I want to avoid creating an illusion that things after the hint are commented.

> For rust-analyzer apparently it's 25
Thank you! I thought this is still an in-dev feature since the inlay-hint section doesn't mention it.

**Comment by HighCommander4** [comment]
Fixed by https://reviews.llvm.org/D150635. Thanks, @daiyousei-qz!

**Comment by HighCommander4** [comment]
@daiyousei-qz could you also submit a patch to https://github.com/llvm/clangd-www to document the new config key added in this patch please?
