### ISSUE TITLE
Performance Issue: Slow Suggestions When Including Certain C Libraries Before Standard C++ Libraries

### ISSUE THREAD

**Issue by sgtalh4381** [clangd/clangd#1639]
**Problem**

I'm experiencing a noticeable slowdown in suggestion speed when certain C libraries are included before the standard C++ libraries in my code. When I rearrange the include statements and include the C++ library first, the suggestion speed returns to normal.

Here's the problematic code:
`extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
}
#include <iostream>
`
And here's the rearranged code where performance improves:
`#include <iostream>
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libswscale/swscale.h>
}
`
This issue significantly decreases productivity as the suggestion speed is crucial for a smooth coding workflow.

**Logs**
During the issue occurrence, I noticed several `textDocument/codeAction` requests were cancelled as shown in the logs below:

`I[11:12:50.436] --> reply:textDocument/codeAction(6) 1299 ms, error: Task was cancelled.
V[11:12:50.436] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":6,"jsonrpc":"2.0"}

I[11:12:50.436] --> reply:textDocument/codeAction(7) 1255 ms, error: Task was cancelled.
V[11:12:50.436] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":7,"jsonrpc":"2.0"}

[Error - 11:12:50 AM] Request textDocument/codeAction failed.
[object Object]
[Error - 11:12:50 AM] Request textDocument/codeAction failed.`

I suspect these cancellations might be related to the slow suggestion speed I am experiencing, but I am not entirely sure about it.

**System Information**
Output of clangd --version: clangd version 15.0.6 
Features: windows+grpc

Editor/LSP plugin: Visual Studio Code

Operating System: Windows11

I would appreciate any possible workaround or fix for this issue. Thanks in advance for your assistance!

**Comment by sam-mccall** [comment]
Clangd uses an optimization to avoid reparsing included headers each time the file is parsed (including for code completion). But `extern "C"` is defeating that optimization.

clangd pre-parses a region at the top of the file called the "preamble", and reuses this as you edit the file - this is critical for speed.
The idea behind the split is: preamble is slow to build/changes rarely. Rest of the file is fast to build/changes frequently.

The preamble can only contain #include and other preprocessor directives, it stops as soon as it hits any other text such as declarations. Unfortunately `extern "C"` is such a declaration.

Usually C headers provide the `extern "C"` themselves, behind `#ifdef __cplusplus` - it looks like ffmpeg is an exception.
One workaround is to create a wrapping header yourself that does this, and #include that.

On the clangd side, it might be possible to consider `extern "C" { #include ... } ` part of the preamble, though it is challenging:
- computing the preamble bounds would now need lookahead: we can't tell if an extern block is eligible until we've seen what's inside it
- constructs allowed inside the preamble often require special handling in features (hover, completion, etc)
- clangd's other #include-related features (include insertion etc) also don't understand this style and may mangle the includes

**Comment by sgtalh4381** [comment]
Thank you for answering my question. I have gained a better understanding of the optimizations and issues related to Clangd. You explained how Clangd improves parsing speed by utilizing a preprocessing region called the "preamble," and mentioned that the extern "C" declaration undermines this optimization. I now understand that C headers typically provide the extern "C" declaration themselves, but ffmpeg headers are an exception. You suggested a solution of creating a wrapper header file with the necessary extern "C" declaration and including it. I will try this approach.
