### ISSUE TITLE
enable enumeration & selection of compilation unit for given header file

### ISSUE THREAD

**Issue by jk000** [clangd/clangd#1651]
Creating this issue based on the comment referenced below.

related: #519 and #123
----------------------------------------------------------------
I would like to submit an additional use case related to this.  I have header files with preprocessor conditions, meaning the active portions of the header files vary depending on which file includes it.  I would like to be able to tell clangd: show me the analysis for this header file as seen by this source file or that source file, and be able to switch at runtime.

I imagine a flow like this:

 - Editor opens foo.h
 - Editor asks clangd for the known "views" for foo.h
 - Clangd returns a list of views for foo.h, that is all the times it knows foo.h is included by a compilation unit
 - Editor presents a dropdown to the user, allowing them to switch between views on that header file
 - When selecting a view, editor informs clangd to use the new view
 
Would that make sense?

_Originally posted by @simark in https://github.com/clangd/clangd/issues/519#issuecomment-1040461694_

**Comment by HighCommander4** [comment]
This sounds very similar to #1534. Please see the information I linked there for some notes on the challenges in implementing this, and starting points if someone would like to tackle it.

**Comment by jk000** [comment]
Agreed, I didn't see that when creating this.  I'll close this one.
