### ISSUE TITLE
clangd does not work with cross-compile Kernel

### ISSUE THREAD

**Issue by Ayush1325** [clangd/clangd#1653]
**Description**
I am trying to get my LSP to work with an out-of-tree Kernel module. I am building the module against a custom kernel ([beagle-kernel](https://git.beagleboard.org/beagleboard/linux/-/tree/v5.10.168-ti-arm64-r103)). The host I am building on is x86_64. I am cross-compiling to arm64 using GCC.

My makefile is as follows:
```make
obj-m += bcf-greybus-driver.o

KDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(CURDIR)

all:
	make -C $(KDIR) M=$(PWD) modules

clean:
	make -C $(KDIR) M=$(PWD) clean
```

I have generated a [`compiler_commands.json`](https://pastebin.com/5cYg0FKe) file using [bear](https://github.com/rizsotto/Bear).

I also have some environment variables:
```sh
export KDIR=$HOME/Documents/Programming/BeagleBoard/beagle-linux
export ARCH=arm64
export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-
```

I  initially get some unsupported arguments errors, so I used the `.clangd` file to remove those args:
```
CompileFlags:
  Remove: [-fconserve-stack, -fno-allow-store-data-races]
```

However, I now get `Invalid AST` error whenever I try to do any LSP stuff.

Btw, LSP does not seem to work for the cross-compiled Kernel source, either whose `compile_commands.json` was created using `scripts/clang-tools/gen_compile_commands.py`.  

I can verify that everything seems to work for a non-cross-compiled kernel I am using for something different, so the problem probably occurs due to cross-compilation.

**Logs**
[lsp.log](https://github.com/clangd/clangd/files/11615105/lsp.log)

**System information**

Output of `clangd --version`:d
```
clangd version 16.0.4 (Fedora 16.0.4-1.fc38)
Features: linux
Platform: x86_64-unknown-linux-gnu; target=x86_64-redhat-linux-gnu
```

Editor/LSP plugin: neovim v0.9.0

Operating system: Fedora Silverblue 38

**Comment by HighCommander4** [comment]
From the log, the reason for the "invalid AST" error is:

> Failed to prepare a compiler instance: unknown target ABI 'lp64'

Looking at the `compile_commands.json`, one of the arguments is `-mabi=lp64`, so maybe adding that to the `Remove: [...]` list in `.clangd` fixes it?

**Comment by HighCommander4** [comment]
(See https://github.com/clangd/clangd/issues/734 for a previous occasional where this has come up)

**Comment by Ayush1325** [comment]
Yes, removing `-mabi=lp64` fixes the issue. Thanks.

**Comment by konosubakonoakua** [comment]
For anyone interested, the `lsp.log` located in `~/.local/state/nvim/lsp.log` if using neovim
