### ISSUE TITLE
incorrect code action for bugprone-implicit-widening-of-multiplication-result

### ISSUE THREAD

**Issue by scu319hy** [clangd/clangd#1656]
I[13:16:13.005] clangd version 16.0.4
I[13:16:13.005] Features: windows

// before fix
```cpp
size_t abc = 128*1024;
```

// fixed
```cpp
size_t abc = static_cast<size_t>(128*)1024;
```

**Comment by HighCommander4** [comment]
This is a bug in the checker, can you file it at https://github.com/llvm/llvm-project/issues please?

**Comment by scu319hy** [comment]
OK

**Comment by HighCommander4** [comment]
Moved to https://github.com/llvm/llvm-project/issues/63070
