### ISSUE TITLE
How to disable auto-include for code completion in .clangd file?

### ISSUE THREAD

**Issue by beyond-fu** [clangd/clangd#1659]
Hi,
I am always bothered by auto-include when using code completion just like this:
```
// this is my common.h
#include <stdio.h>
// something
```
```
// this is my test.c
#include <common.h>
#include <stdio.h>
printf("hello world\n");
```
First I have included `<common.h> header`, but when I type `printf function` and complete it, `clangd` auto-include `<stdio.h>` for me. So is there a way to let `clangd` know that the `common.h` have included `<stdio.h>`, or disable auto-include then I will include the missing header files manually. It seems like `--header-insertion=never` config option can be used in vscode .json file, but I did not figure out how to config that in `.clangd file`.

By the way, is there a page listing all the config options for `.clangd file` just like `clang-format documentation`(https://clang.llvm.org/docs/ClangFormatStyleOptions.html)? That will be very convenient.

**My Environment:**
Machine: x86_64
OS: Ubuntu 22.04
Editor: Neovim(v0.9.0-dev) with clangd LSP
Clangd Version: 16.0.2

Thanks in advance!

**Comment by HighCommander4** [comment]
> It seems like `--header-insertion=never` config option can be used in vscode .json file, but I did not figure out how to config that in `.clangd file`.

There isn't currently an option to configure this in `.clangd`, only on the command line with `--header-insertion=never`.

Note that any editor should provide a way to pass command line arguments to the language server, not just vscode.

> By the way, is there a page listing all the config options for `.clangd file` just like `clang-format documentation`(https://clang.llvm.org/docs/ClangFormatStyleOptions.html)? That will be very convenient.

Yes, https://clangd.llvm.org/config.html

**Comment by beyond-fu** [comment]
> So is there a way to let clangd know that the common.h have included <stdio.h>

So can this be a new feature? I don't know if it is hard to implemetation. Maybe it will cause much performance loss to clangd?
>Yes, https://clangd.llvm.org/config.html

Sorry, I thought the configurations in this page were incomplete before.

**Comment by HighCommander4** [comment]
> > So is there a way to let clangd know that the common.h have included <stdio.h>
> 
> So can this be a new feature? I don't know if it is hard to implemetation. Maybe it will cause much performance loss to clangd?

Your questions (how hard is it to implement, how would it perform) are good ones, and the answers are not obvious to me. Maybe the folks who have been working on include-cleaner have a better sense for it.

Anyways, I suggest filing a new issue for it, since this is about implementing a new mode of header insertion.

> > Yes, https://clangd.llvm.org/config.html
> 
> Sorry, I thought the configurations in this page were incomplete before.

Sometimes we add a new config and forget to update this page :)

There is an idea in https://reviews.llvm.org/D140745 to generate both the documentation page and the config-related code from a single schema file.

**Comment by beyond-fu** [comment]
Thank you! I have disabled auto-include in neovim. I will close this issue and open a new issue.
