### ISSUE TITLE
VS Code plugin: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by teki** [clangd/clangd#166]
Environment:
MacOS 10.14.6
llvm: 9.0.0 from homebrew
vscode-clangd: 0.0.18
VS Code: 1.38.1

Everything starts well, indexing runs, plugin works, but after a while I get the disconnected message and then nothing. I have to restart VS Code in about every hour to keep it working.

```
I[14:49:35.756] Indexed /Users/xxxx/Controller.cpp (17768 symbols, 47258 refs, 736 files)
I[14:49:37.321] Indexed /Users/xxxx/boringssl/crypto/pkcs8/p5_pbev2.c (4236 symbols, 7682 refs, 153 files)
I[14:49:42.107] Indexed /Users/xxxx/Config.cpp (26235 symbols, 66540 refs, 1147 files)
[Error - 2:49:42 pm] Connection to server got closed. Server will not be restarted.
```

`--backgound-index` and `--clang-tidy` has no effect on the problem, happens without them too.

**Comment by hokein** [comment]
`Connection to server got closed` is indicating that clangd crashes, it would be nice to provide the stack trace.

> --backgound-index and --clang-tidy has no effect on the problem, happens without them too.

The background-index and clang-tidy are turned on by default. If you want to disable them, you'd need to pass the flags (`--background-index=false`, and `--clang-tidy=false`) to clangd. Could you verify that the issue still happens when you disable them?

**Comment by DoDoENT** [comment]
This often happens to me as well, especially when opening a specific file in my codebase. How can I obtain the stack trace of the crash?

**Comment by kadircet** [comment]
make sure you pass `-log=verbose` to clangd and then open up `Output > Clang Language Server` in vscode.

**Comment by teki** [comment]
I updated to 9.0.1 but the issue persist. Managed to get a stack trace.

[clangd_2020-01-29-095506_C02XH0NKJGH8.crash.txt](https://github.com/clangd/clangd/files/4125788/clangd_2020-01-29-095506_C02XH0NKJGH8.crash.txt)

**Comment by sbowman** [comment]
I don't have a solution, but I'm also seeing crashes on macOS Catalina with clangd 10.0.0.  Neither vscode-clangd nor eglot in Emacs is working, so it's most likely an incompatibility between clangd and Catalina.  

I do see a lot of messages around missing standard library includes in my logs.  I don't know if this is causing the panics, though.

```
Ignored diagnostic. <...filename...> :'functional' file not found
Ignored diagnostic. <...filename...> :'vector' file not found
```

**Comment by kadircet** [comment]
unfortunately there is nothing to act on here. we need a reproducer (source code) triggering the crash so that we can investigate. feel free to re-open if the issue is still happening and you've got a (preferably minimized) source file that triggers the crash.
