### ISSUE TITLE
Template argument type not included in symbol references

### ISSUE THREAD

**Issue by ljden** [clangd/clangd#1666]
The lsp knows of the existence of my `enum struct FOOBAR` and can find most references across files. 
```cpp
enum struct FOOBAR {
    foo,
    bar,
};
template<FOOBAR one, FOOBAR two>
constexpr void func() {
    if (one == FOOBAR::foo) return;
}
```
Using neovim I can get a list of references with:
[`:lua vim.lsp.buf.references()`](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.references())

Calling this on any occurrence of `FOOBAR` returns a list with the definition and the if statement, but not either of the template args.
I can even call it on the template arg and it will show me the other references but not the template args.

The issue is that when I use neovims [rename()](https://neovim.io/doc/user/lsp.html#vim.lsp.buf.rename()) feature, I can rename all occurrences of `FOOBAR` except those in template parameters in *other* files (occurrences in the same file seem to be caught).

Starting with:
```cpp
// header1.hpp
enum struct FOOBAR {
    foo,
    bar,
};
template<FOOBAR one, FOOBAR two>
constexpr void func() {
    if (one == FOOBAR::foo) return;
}
//header2.hpp
template<FOOBAR one, FOOBAR two>
constexpr void func2() {
    if (two == FOOBAR::foo) return;
}
```
and running rename() to make FOOBAR -> foobar on the `FOOBAR` symbol of `enum struct FOOBAR` results in:
```cpp
// header1.hpp
enum struct foobar {
    foo,
    bar,
};
template<foobar one, foobar two>
constexpr void func() {
    if (one == foobar::foo) return;
}
//header2.hpp
template<FOOBAR one, FOOBAR two>
constexpr void func2() {
    if (two == foobar::foo) return;
}
```
## System Information
```bash
$ clangd --version
Ubuntu clangd version 14.0.0-1ubuntu1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
NVIM v0.9.0
https://github.com/hrsh7th/nvim-cmp
OS: Ubuntu 22.04.2 LTS x86_64

Not sure how useful the logs would be in this instance but if they are required I can try to get a coherent log (nvim lsp logging is a bit broken for verbose logging)
Also if you feel this may be an issue on neovim/plugin side let me know if there is a simple way to test this

**Comment by HighCommander4** [comment]
Not neovim-specific, I can reproduce this in vscode as well.

**Comment by HighCommander4** [comment]
Proposed fix: https://reviews.llvm.org/D153251
