### ISSUE TITLE
Renaming namespace aliases doesn't work

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#167]
```cpp
namespace a { namespace b { void foo(); } }

namespace x = a::b;
void bar() {
  x::foo();
}
```

rename x -> y:
- if on the `x^::foo`, fails 
- if on `namespace x^ = a::b`, works but doesn't update `x::foo` to `y::foo`, only changes namespace alias.

**Comment by hokein** [comment]
Fixed in llvm/llvm-project@4f80fc2.
