### ISSUE TITLE
"[clang] Too many arguments provided to function-like macro invocation (fix available)" when using struct literal in macro argument

### ISSUE THREAD

**Issue by aalmkainzi** [clangd/clangd#1682]
for example
```
typedef struct
{
    int elm1;
    int elm2;
} My_Struct;

#define MACRO(arg) (arg)

int main()
{
    MACRO( (My_Struct){1, 2} ); // clangd reports error here
}
```

**System information**

Output of `clangd --version`:
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin: Kate

Operating system: kubuntu

**Comment by sam-mccall** [comment]
clangd is correct to report an error, that code is invalid.

https://devblogs.microsoft.com/oldnewthing/20200508-52/?p=103735
