### ISSUE TITLE
clangd seems more likely to crash when ranges are used

### ISSUE THREAD

**Issue by cjdb** [clangd/clangd#1689]
**Logs**

[log.txt](https://github.com/clangd/clangd/files/11926783/log.txt)

**System information**

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```
```
$ clangd --version
clangd version 17.0.0 (git@github.com:llvm/llvm-project.git bda729ee16d129b04f8e0b64f4ec7ffef4af5105)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu
```
```
$ code --version
1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
x64
```

**Comment by HighCommander4** [comment]
The failing assertion from the log is:

> llvm/lib/Support/APInt.cpp:282: int llvm::APInt::compareSigned(const APInt &) const: Assertion `BitWidth == RHS.BitWidth && "Bit widths must be same for comparison"' failed

Top few lines of stack trace:

```
 #9 0x0000563429786d23 llvm::APInt::compareSigned(llvm::APInt const&) const (/home/cjdb/opt/bin/clangd+0x117cd23)
#10 0x00005634299ed77d EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) ExprConstant.cpp:0:0
#11 0x00005634299ec86a EvaluateStmt((anonymous namespace)::StmtResult&, (anonymous namespace)::EvalInfo&, clang::Stmt const*, clang::SwitchCase const*) ExprConstant.cpp:0:0
#12 0x00005634299c9f39 HandleFunctionCall(clang::SourceLocation, clang::FunctionDecl const*, (anonymous namespace)::LValue const*, llvm::ArrayRef<clang::Expr const*>, (anonymous namespace)::CallRef, clang::Stmt const*, (anonymous namespace)::EvalInfo&, clang::APValue&, (anonymous namespace)::LValue const*) ExprConstant.cpp:0:0
#13 0x00005634299c9b21 clang::Expr::isPotentialConstantExpr(clang::FunctionDecl const*, llvm::SmallVectorImpl<std::__1::pair<clang::SourceLocation, clang::PartialDiagnostic>>&) (/home/cjdb/opt/bin/clangd+0x13bfb21)
#14 0x0000563429fee305 clang::Sema::CheckConstexprFunctionDefinition(clang::FunctionDecl const*, clang::Sema::CheckConstexprKind) (/home/cjdb/opt/bin/clangd+0x19e4305)
#15 0x000056342a2a4d32 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/home/cjdb/opt/bin/clangd+0x1c9ad32)
```

A user recently reported this same crash occurring while indexing the Chromium source code too.

Having a reducer reproducer would be great.

**Comment by usx95** [comment]
Similar stacktrace and same assertion failure is reported in https://github.com/llvm/llvm-project/issues/63453

**Comment by HighCommander4** [comment]
> Similar stacktrace and same assertion failure is reported in [llvm/llvm-project#63453](https://github.com/llvm/llvm-project/issues/63453)

Indeed, and that one has a reduced testcase and a fix in progress at https://reviews.llvm.org/D153296. Looks encouraging.

**Comment by cjdb** [comment]
Since a Clang bug (i.e. not specific to clangd), I'm closing this issue.

**Comment by HighCommander4** [comment]
@cjdb when you get around to building a newer trunk, it would be nice to get a confirmation that https://reviews.llvm.org/D153296 did indeed resolve the crashes for you.

**Comment by cjdb** [comment]
I haven't observed any crashes like this in the past two days :)
