### ISSUE TITLE
Undeclared indentifier __integer_pack (gcc compatability)

### ISSUE THREAD

**Issue by andreichalapco** [clangd/clangd#1691]
When using the clangd lsp server I always receive the error (undeclared identifier) for using the type traits (https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Type-Traits.html) from the gcc (e.g. __integer_pack). Is there a way to make the clangd compatible with the gcc internals.

**System information**

Output of `clangd --version`: 16.0.5

Editor/LSP plugin: nvim-lsp (with mason)

Operating system: Fedora

**Comment by zyn0217** [comment]
Clangd doesn't provide extra builtins besides that from Clang, while it offers [`__make_integer_seq`](https://reviews.llvm.org/D13786) which essentially provides the same feature as `__integer_pack`. In my opinion you could use macro to handle the case:
```c++
#if defined(__clang__)
// Use `__make_integer_seq`
#elif defined(__GNUC__)
// Use `__integer_pack`
```

**Comment by HighCommander4** [comment]
Are you using `__integer_pack` directly in your own source file? Or are you including some sort of library header which uses `__integer_pack` and getting an error from inside that library header?

**Comment by andreichalapco** [comment]
I'm including a header where __integer_pack is used

**Comment by andreichalapco** [comment]
```#include <hpx/local/future.hpp>``` (the error just comes from this include line```. I'm using the hpx library.

**Comment by HighCommander4** [comment]
According to https://hpx-docs.stellar-group.org/latest/html/manual/prerequisites.html#supported-compilers, HPX supports clang 10.0 or later, so its source code should be portable between gcc and clang.

Without having actually downloaded and played around with the library myself, my best guess is: maybe you need to configure it for building with clang (rather than with gcc), and generate a `compile_commands.json` from that configuration for use with clangd. (You don't have to _actually_ build with clang.)

**Comment by andreichalapco** [comment]
I also thought this could be a solution ... but I don't know how to build this compile_commands.json ... I don't have any documentation about it ...

**Comment by HighCommander4** [comment]
The build looks to be based on CMake, you it should just be a matter of adding `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` to the `cmake` command, as mentioned at https://clangd.llvm.org/installation#compile_commandsjson (under "CMake-based projects").

**Comment by andreichalapco** [comment]
So basically if I don't build the project ... (just have the binaries via a dnf install ) I can't do this?

**Comment by zyn0217** [comment]
Or I guess you could add the following to the .clangd file:
```yaml
CompileFlags:
  Add: [-UHPX_HAVE_BUILTIN_INTEGER_PACK, -DHPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ]
```

**Comment by andreichalapco** [comment]
sadly not working ... (i hope my clangd is configured to use this .clangd file)

**Comment by i-ky** [comment]
> So basically if I don't build the project ... (just have the binaries via a dnf install ) I can't do this?

How do you build your project? Do you use `pkg-config` or CMake? (https://hpx-docs.stellar-group.org/latest/html/manual/creating_hpx_projects.html)

If your project uses CMake, you can configure it with clang as a compiler and `-DCMAKE_EXPERT_COMPILE_COMMANDS=1` . This should produce a clang-compatible `compile_commands.json` that will contain required options to make HPX headers work in clangd.

**Comment by i-ky** [comment]
> (i hope my clangd is configured to use this .clangd file)

Make sure it does.

**Comment by andreichalapco** [comment]
So i"m pretty sure the clangd is loading the compilation database ... but I can't see any logs for loading .clangd??? is there a way to check for this?

**Comment by zyn0217** [comment]
> is there a way to check for this?

Just look for the compile command of one TU with the issue and find if there exists something like `-UHPX_HAVE_BUILTIN_INTEGER_PACK, -DHPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ`.

**Comment by andreichalapco** [comment]
so the flags are there: -UHPX_HAVE_BUILTIN_INTEGER_PACK -DHPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ

**Comment by zyn0217** [comment]
So, are you still suffering from the same issue? Could you please attach the full clangd log then?

**Comment by andreichalapco** [comment]
`
[ERROR][2023-07-03 11:55:43] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	'I[11:55:43.349] <-- initialized\nI[11:55:43.350] <-- textDocument/didOpen\nI[11:55:43.350] --> textDocument/publishDiagnostics\nI[11:55:43.351] Loaded compilation database from /home/andreichalapco/uni-code/learning-hpx/test-project/build/compile_commands.json\nI[11:55:43.351] --> window/workDoneProgress/create(0)\nI[11:55:43.351] ASTWorker building file /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp version 0 with command \n[/home/andreichalapco/uni-code/learning-hpx/test-project/build]\n/usr/bin/g++ --driver-mode=g++ -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME_DEFAULT=my_hpx_program "-DHPX_PREFIX_DEFAULT=\\"/usr\\"" -g -std=gnu++17 -pthread -o CMakeFiles/my_hpx_program.dir/main.cpp.o -c -UHPX_HAVE_BUILTIN_INTEGER_PACK -DHPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ -resource-dir=/home/andreichalapco/.local/share/lvim/mason/packages/clangd/clangd_16.0.2/lib/clang/16 -- /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp\nI[11:55:43.351] Enqueueing 1 commands for indexing\nI[11:55:43.352] <-- textDocument/documentSymbol(2)\n'
`

**Comment by zyn0217** [comment]
Sorry I didn't see specific error message from the log. Could you simply run `clangd -check=/home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp` and attach the output here?

**Comment by andreichalapco** [comment]
`
I[12:05:57.735] clangd version 16.0.5 (Fedora 16.0.5-1.fc38)
I[12:05:57.735] Features: linux
I[12:05:57.735] PID: 90187
I[12:05:57.735] Working directory: /home/andreichalapco/uni-code/learning-hpx/test-project
I[12:05:57.735] argv[0]: clangd
I[12:05:57.735] argv[1]: -check=main.cpp
I[12:05:57.735] Entering check mode (no LSP server)
I[12:05:57.735] Testing on source file /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp
I[12:05:57.735] Loading compilation database...
I[12:05:57.735] Loaded compilation database from /home/andreichalapco/uni-code/learning-hpx/test-project/build/compile_commands.json
I[12:05:57.736] Compile command from CDB is: /usr/bin/g++ --driver-mode=g++ -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME_DEFAULT=my_hpx_program "-DHPX_PREFIX_DEFAULT=\"/usr\"" -g -std=gnu++17 -pthread -o CMakeFiles/my_hpx_program.dir/main.cpp.o -c -UHPX_HAVE_BUILTIN_INTEGER_PACK -DHPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ -resource-dir=/usr/lib64/clang/16 -- /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp
I[12:05:57.736] Parsing command...
I[12:05:57.738] internal (cc1) args are: -cc1 -triple x86_64-redhat-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/andreichalapco/uni-code/learning-hpx/test-project/build -resource-dir /usr/lib64/clang/16 -D HPX_APPLICATION_EXPORTS -D HPX_APPLICATION_NAME_DEFAULT=my_hpx_program -D "HPX_PREFIX_DEFAULT=\"/usr\"" -U HPX_HAVE_BUILTIN_INTEGER_PACK -D HPX_HAVE_BUILTIN_MAKE_INTEGER_SEQ -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/x86_64-redhat-linux -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/backward -internal-isystem /usr/lib64/clang/16/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=gnu++17 -fdeprecated-macro -fdebug-compilation-dir=/home/andreichalapco/uni-code/learning-hpx/test-project/build -ferror-limit 19 -pthread -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp
I[12:05:57.738] Building preamble...
I[12:06:00.507] Indexing headers...
I[12:06:01.166] Built preamble of size 25706452 for file /home/andreichalapco/uni-code/learning-hpx/test-project/main.cpp version null in 3.43 seconds
E[12:06:01.169] [undeclared_var_use] Line 15: in included file: use of undeclared identifier '__integer_pack'
I[12:06:01.169] Building AST...
I[12:06:01.246] Indexing AST...
I[12:06:01.247] Building inlay hints
I[12:06:01.247] Building semantic highlighting
I[12:06:01.247] Testing features at each token (may be slow in large files)
I[12:06:01.371] All checks completed, 1 errors
`

**Comment by zyn0217** [comment]
Thanks for providing logs. Another question: which version of HPX are you currently using? The previous macros are based on the trunk branch of HPX and I'm afraid your version of HPX is lack of such facility.

**Comment by HighCommander4** [comment]
> So basically if I don't build the project ... (just have the binaries via a dnf install ) I can't do this?

Sorry, I probably added to the confusion by mixing up the HPX library's build and your own project's build. It's the latter that's relevant, using precompiled binaries for the library is probably fine.

Does your project's build use CMake? (Is that how you created `/home/andreichalapco/uni-code/learning-hpx/test-project/build/compile_commands.json`, with `-DCMAKE_EXPERT_COMPILE_COMMANDS=1`)? Are you able to configure your project to use clang as a compiler rather than gcc?

**Comment by andreichalapco** [comment]
I built the binaries again for hpx ... but this also did not solve the problem ... The fact is I built the project with gcc 13 and I don't want to go again to the hustle of compiling the entire project just for the clang.

Thx Again for all the support ! You guys are great ... but I think I'm gonna find another solution.

**Comment by andreichalapco** [comment]
This is 1 to 1 related to #1906 . Problem were the compiler specific placeholders.
