### ISSUE TITLE
"Go to references" on a constructor definition produces all references to the class

### ISSUE THREAD

**Issue by gribozavr** [clangd/clangd#17]
When I "go to references" in this file on the constructor definition, I expect to see up to two results: the constructor call in `main()`, and maybe also the class definition.

Instead, I get all references to the class name in the source file.

```c++
class MyClass {
 public:
  MyClass() {}  // Go to references on "MyClass"
};

void consumer(const MyClass &);

int main() {
  consumer(MyClass());
  return 0;
}
```

**Comment by kadircet** [comment]
Sent out https://reviews.llvm.org/D58814

**Comment by kadircet** [comment]
Langed https://reviews.llvm.org/D58815
