### ISSUE TITLE
Pragma packed not expanded correctly in structs

### ISSUE THREAD

**Issue by EduMenges** [clangd/clangd#1702]
When applying a pragma in a struct definition, the extension gives the following error:
Declaration of anonymous struct must be a definitionclang(anon_type_definition)
Declaration does not declare anythingclang(-Wmissing-declarations)

You can easily reproduce the error with the following code:
```
#include <cstdint>

#ifdef __GNUC__
#if __cplusplus >= 201103L
#define __begin_packed [[gnu::packed]]
#else
#define __begin_packed __attribute__((packed))
#endif
#define __end_packed
#else // MSVC
#define __begin_packed __pragma(pack(push, 1))
#define __end_packed   __pragma(pack(pop))
#endif

struct Normal {
    uint8_t a;
    uint32_t b;
};

struct __pragma(pack(push, 1)) Packed {
    uint8_t a;
    uint32_t b;
} __end_packed;


struct After {
    uint8_t a;
    uint32_t b;
};

int main() {
    static_assert(sizeof(struct Normal) == 8);
    static_assert(sizeof(struct Packed) == 5);
    static_assert(sizeof(struct After) == 8);
}
```

When compiling for MSVC, the error should appear.

**Logs**

I[20:44:03.585] --> textDocument/clangd.fileStatus
I[20:44:06.948] <-- shutdown(18)
I[20:44:06.948] --> reply:shutdown(18) 0 ms
I[20:44:07.006] <-- exit
I[20:44:07.006] LSP finished, exiting with status 0
I[20:44:07.195] clangd version 17.0.0 (https://github.com/llvm/llvm-project 9259f41e62d2b2d49dac01247003304354ff4493)
I[20:44:07.201] Features: windows+grpc
I[20:44:07.201] PID: 31088
I[20:44:07.201] Working directory: c:\Users\br20279\Downloads\test_packed
I[20:44:07.201] argv[0]: C:\Users\br20279\Documents\clangd.exe
I[20:44:07.241] Starting LSP over stdin/stdout
I[20:44:07.243] <-- initialize(0)
I[20:44:07.258] --> reply:initialize(0) 15 ms
I[20:44:07.265] <-- initialized
I[20:44:07.290] <-- textDocument/didOpen
I[20:44:07.311] Failed to find compilation database for c:\Users\br20279\Downloads\test_packed\packed.cpp
I[20:44:07.311] ASTWorker building file c:\Users\br20279\Downloads\test_packed\packed.cpp version 1 with command clangd fallback
[c:\Users\br20279\Downloads\test_packed]
"C:\\Program Files\\LLVM\\bin\\clang" "-resource-dir=C:\\Users\\br20279\\lib\\clang\\17" -- "c:\\Users\\br20279\\Downloads\\test_packed\\packed.cpp"
I[20:44:07.315] <-- textDocument/documentSymbol(1)
I[20:44:07.321] <-- textDocument/codeAction(2)
I[20:44:07.378] --> textDocument/clangd.fileStatus
I[20:44:07.397] <-- textDocument/documentLink(3)
I[20:44:07.405] <-- textDocument/inlayHint(4)
I[20:44:07.522] Built preamble of size 548980 for file c:\Users\br20279\Downloads\test_packed\packed.cpp version 1 in 0.14 seconds
I[20:44:07.539] Indexing c++14 standard library in the context of c:\Users\br20279\Downloads\test_packed\packed.cpp
I[20:44:07.640] --> workspace/semanticTokens/refresh(0)
I[20:44:07.640] --> textDocument/clangd.fileStatus
I[20:44:07.647] <-- reply(0)
I[20:44:07.693] <-- textDocument/foldingRange(5)
I[20:44:07.704] --> reply:textDocument/foldingRange(5) 11 ms
I[20:44:07.787] --> textDocument/publishDiagnostics
I[20:44:07.788] --> reply:textDocument/documentSymbol(1) 473 ms
I[20:44:07.789] --> reply:textDocument/codeAction(2) 467 ms
I[20:44:07.789] --> reply:textDocument/documentLink(3) 391 ms
I[20:44:07.789] --> reply:textDocument/inlayHint(4) 384 ms
I[20:44:07.789] --> textDocument/clangd.fileStatus
I[20:44:08.084] <-- textDocument/codeAction(6)
I[20:44:08.085] --> reply:textDocument/codeAction(6) 0 ms
I[20:44:08.085] --> textDocument/clangd.fileStatus
I[20:44:15.907] Indexed c++14 standard library: 18843 symbols, 403 filtered

**System information**

Output of `clangd --version`:
clangd version 17.0.0 (https://github.com/llvm/llvm-project 9259f41e62d2b2d49dac01247003304354ff4493)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc

Editor/LSP plugin:
VSCode

Operating system:
Windows 10

**Comment by sam-mccall** [comment]
It looks like clang has some support for `__pragma` and `pack`, but doesn't accept it in the middle of a struct definition.

This isn't standard C++ and the MS docs for the feature don't say whether this use is valid or not, so it's not surprising there are differences.
If you want this changed, you'll need to file a bug against clang, this isn't something we can fix in clangd.

I'm not sure what at a high level you're trying to do, but generally you want to use the clang version of attributes/macros if you have one, or failing that the GCC version. They're much more compatible (e.g. clang supports `[[gnu::packed]]`)
