### ISSUE TITLE
Remove whitespace at the start of the clang-tidy fix modernize-use-override 

### ISSUE THREAD

**Issue by hriekehof** [clangd/clangd#1704]
If i have a class in a header which inherits from a pure virtual base class i observe the following when i apply the fix.

```c++
class A : public Interface
{
    // This will be marked by clangd to use override instead of virtual
    virtual void Reset();

    // After applying the fix i get this and i always have to manually delete the one whitespace :)
     void Reset() override;
};
````
I am not sure if this problem also occurs for other checks where a fix is applied via `clangd`

**System information**
Clangd version (from the log, or `clangd --version`):
```
Apple clangd version 15.0.0 (clang-1500.0.29.1)
Features: mac+xpc
Platform: x86_64-apple-darwin22.5.0; target=arm64-apple-darwin22.5.0
```
clangd extension version: `0.1.24`
Operating system: `macOS Ventura 13.4.1`

**Comment by HighCommander4** [comment]
If you'd like to continue investigating this, the next step would be to check out and build the server code locally.

Instructions for that can be found here: https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd#building-and-testing-clangd

Note, the server code is part of the LLVM project and does not currently support being built independently, so the instructions linked above will build LLVM and clang as dependencies as well.

Once you have a build, I would suggest writing a test case that captures the problem. We have some existing tests for clang-tidy diagnostics in `DiagnosticsTets.cpp`; see for example [this test case](https://searchfox.org/llvm/rev/eadbc4b004b6f5bcd67f17b1d79c9955bd410fb8/clang-tools-extra/clangd/unittests/DiagnosticsTests.cpp#783) for how to enable a particular clang-tidy check, and how to make assertions about the offered quick-fixes.

Once you have written a test case, you can run/debug it locally to track down and fix the problem. (One of the reasons I suggest writing a test case first, is that it's easier to debug a test case than to debug clangd in a context where it's started by an editor.)

Let me know if you run into any issues building or writing the test case.

**Comment by HighCommander4** [comment]
Forgot to mention how to run a testcase. For example, for the one linked above, in your build folder you can run:

```
./tools/clang/tools/extra/clangd/unittests/ClangdTests --gtest_filter=DiagnosticTest.ClangTidySelfContainedDiags
```

**Comment by marcogmaia** [comment]
I believe this issue can be closed.

**Comment by HighCommander4** [comment]
> I believe this issue can be closed.

Thanks. Fixed by https://github.com/llvm/llvm-project/pull/81435.
