### ISSUE TITLE
function overload called display error

### ISSUE THREAD

**Issue by yuThomas** [clangd/clangd#1705]
Please describe the problem.

do have two overload functions, and called as below:
#include <iostream>

int hanlde(std::string &strDev, int nMode) {
    std::cout << strDev << nMode << std::endl;
    return 0;
}

int handle(std::string &strDev, std::string &strId, int nMode) {
    std::cout << strDev << nMode << std::endl;
    return 0;
}

int main(int argc, char **argv) {
    std::string str("hello");
    std::cout << handle(str, 1) << std::endl;            // this line gives me a warnning mesage:  No matching function for call to 
                                                                               //'handle'  clang(ovl_no_viable_function_in_call)
                                                                     //main.cpp(9, 5): Candidate function not viable: requires 3 arguments, but 2 were provided
   return 0;
}

Output of `clangd --version`: 16.0.2

Editor/LSP plugin: 

Operating system: x86_64-pc-windows-msvc

**Comment by HighCommander4** [comment]
StackOverflow is probably a more appropriate forum for this question.

In your code example, the first overload is misspelled "hanlde".

**Comment by yuThomas** [comment]
sorry to provide wrong code, look at some code snippet in my real project:
clas ApiManager {
    int Init(void* pFile, vector<string>& vecServerType, unsigned char cMode);
    int Init(void* pFile, unsigned char cMode);
};

somewhere else:
std::vector<std::string> vecServerType;
m_pApiManager = new ApiManager;
int nRet = m_pApiManager->Init(pUtilIniFileAgent, vecServerType, API_MODE_REDIS);   //API_MODE_REDIS is an int ENUM

warning: Too many arguments to function call, expected 2, have 3clang(typecheck_call_too_many_args

**Comment by sam-mccall** [comment]
That code is still not valid.
Please reopen if clangd is mishandling code that is correct and that clang itself can parse, and you have a minimal self-contained example.
