### ISSUE TITLE
System include extraction: driver clang not found in PATH

### ISSUE THREAD

**Issue by cworld1** [clangd/clangd#1708]
I use CMake for initializing my project, and as fact I tried to generate `compile_commands.json` file to fix any problem. But it did not work well. `--query-driver` did the same.

**Logs**

> Changed `.../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\90351\\AppData\\Local\\nvim-data\\mason\\bin\\clangd.CMD"	"stderr"	` string with ▨ for a better look

```
[ERROR][2023-07-23 01:12:02] .../vim/lsp/rpc.lua:734	"rpc"	""	"stderr"	"I[01:12:02.605] <-- shutdown(7)\r\nI[01:12:02.605] --> reply:shutdown(7) 0 ms\r\n"
[START][2023-07-23 01:12:06] LSP logging initiated
[WARN][2023-07-23 01:12:06] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.491] clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)\r\nI[01:12:07.492] Features: windows+grpc\r\nI[01:12:07.492] PID: 39888\r\nI[01:12:07.492] Working directory: D:\\Project\\C\\json-parse\r\nI[01:12:07.492] argv[0]: C:\\Users\\90351\\AppData\\Local\\nvim-data\\mason\\packages\\clangd\\clangd_16.0.2/bin/clangd.exe\r\nI[01:12:07.492] argv[1]: --query-driver=D:/Source/Qt/Tools/mingw1120_64/bin/g*\r\nI[01:12:07.500] Starting LSP over stdin/stdout\r\nI[01:12:07.500] <-- initialize(1)\r\nI[01:12:07.514] --> reply:initialize(1) 13 ms\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.601] <-- initialized\r\nI[01:12:07.601] <-- textDocument/didOpen\r\n"
[ERROR][2023-07-23 01:12:07] ▨"E[01:12:07.611] System include extraction: driver clang not found in PATH\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.611] <-- textDocument/semanticTokens/full(2)\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.613] --> textDocument/publishDiagnostics\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.614] Loaded compilation database from D:\\Project\\C\\json-parse\\compile_commands.json\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.614] --> window/workDoneProgress/create(0)\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.614] Enqueueing 1 commands for indexing\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.614] <-- reply(0)\r\nI[01:12:07.614] --> $/progress\r\nI[01:12:07.614] --> $/progress\r\n"
[ERROR][2023-07-23 01:12:07] ▨'I[01:12:07.614] ASTWorker building file D:\\Project\\C\\json-parse\\main.cpp version 0 with command \r\n[D:/Project/C/json-parse/build]\r\n"D:\\\\Source\\\\Qt\\\\Tools\\\\mingw1120_64\\\\bin\\\\c++.exe" --driver-mode=g++ -o "CMakeFiles\\\\JSON-parse.dir\\\\main.cpp.obj" -c "-resource-dir=C:\\\\Users\\\\90351\\\\AppData\\\\Local\\\\nvim-data\\\\mason\\\\packages\\\\clangd\\\\clangd_16.0.2\\\\lib\\\\clang\\\\16" -- "D:\\\\Project\\\\C\\\\json-parse\\\\main.cpp"\r\n'
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.615] --> $/progress\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.615] --> $/progress\r\nI[01:12:07.615] --> $/progress\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.679] Indexed D:/Project/C/json-parse/main.cpp (1 symbols, 1 refs, 1 files)\r\nI[01:12:07.679] Failed to compile D:/Project/C/json-parse/main.cpp, index may be incomplete\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.681] --> $/progress\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.686] Built preamble of size 229164 for file D:\\Project\\C\\json-parse\\main.cpp version 0 in 0.01 seconds\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.687] --> workspace/semanticTokens/refresh(1)\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.687] <-- $/cancelRequest\r\nI[01:12:07.687] <-- textDocument/semanticTokens/full(3)\r\nI[01:12:07.687] <-- reply(1)\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.707] --> textDocument/publishDiagnostics\r\n"
[ERROR][2023-07-23 01:12:07] ▨"I[01:12:07.707] --> reply:textDocument/semanticTokens/full(2) 96 ms, error: Task was cancelled.\r\nI[01:12:07.708] --> reply:textDocument/semanticTokens/full(3) 20 ms\r\n"
```

At the same, ide showed me problem like `'iostream' file not found` for a hello world project.

**System information**

Output of `clangd --version`:

```
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc
```

C Compiler: MinGW 11.20

IDE: NeoVim

Editor/LSP plugin:

```
Client: clangd (id: 2, bufnr: [4])
 	filetypes:       c, cpp, objc, objcpp, cuda, proto
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             C:\Users\90351\AppData\Local\nvim-data\mason\bin\clangd.CMD --query-driver=D:/Source/Qt/Tools/mingw1120_64/bin/g*
```

Operating system: Windows 11

**Comment by HighCommander4** [comment]
The comparison of the driver name to the `--query-driver` glob is string based.

In your case, the driver from the compile command is:

> D:\\\\Source\\\\Qt\\\\Tools\\\\mingw1120_64\\\\bin\\\\c++.exe

(I assume the multiple backslashes are just an artifact of escaping when printing the logs, so the actual string is "D:\Source\Qt\Tools\mingw1120_64\bin\c++.exe".)

Your `--query-driver` glob is:

> D:/Source/Qt/Tools/mingw1120_64/bin/g*

The driver name does not match the glob because the slashes are different, and also `g*` does not match `c++.exe`.

So, try `--query=driver=D:\Source\Qt\Tools\mingw1120_64\bin\c++.exe`, and hopefully it works better.

**Comment by cworld1** [comment]
Thanks a lot! It works well. But If I also want to make c lang LSP runs well, how can I do?

**Comment by HighCommander4** [comment]
> But If I also want to make c lang LSP runs well, how can I do?

You'd want to look at what is the executable name in the compiler command for C source files in your `compile_commands.json`, and use a glob which matches that as well.

(If the executable for C++ files was `c++.exe`, I'd venture a guess for C files it's `cc.exe`, in which case a glob of `c*` should work.)

**Comment by cworld1** [comment]
No, It's `gcc.exe`. How can I add it to `--query-driver` glob?

**Comment by HighCommander4** [comment]
> No, It's `gcc.exe`. How can I add it to `--query-driver` glob?

You can pass a comma-separated list, e.g. `--query-driver=D:\Source\Qt\Tools\mingw1120_64\bin\c++.exe,D:\Source\Qt\Tools\mingw1120_64\bin\gcc.exe`.

> Emm... I found setting it as `--query-driver=D:\Source\Qt\Tools\mingw1120_64\bin\*` looks work well. I don't know whether it will take effects on performances or any other way.

That works too. There aren't really any performance implications, the purpose of `--query-driver` is mainly security, i.e. to prevent accidentally having clangd execute malicious executables.

> And if there does not exist `compile_commands.json` file, it cannot work. Does that mean I need to initialize the project with CMake or create JSON manually every time I create a C/C++ project?

An alternative supported in clangd 16 and later is to specify the compiler driver in a [clangd config file](https://clangd.llvm.org/config.html) with:

```yaml
CompileFlags:
  Compiler: D:\Source\Qt\Tools\mingw1120_64\bin\c++.exe
```

There are some known issues with this (e.g. https://github.com/clangd/clangd/issues/1568), and there are other advantages to using `compile_commands.json` (it allows the project to be indexed), which is why I usually recommend the latter.

**Comment by cworld1** [comment]
I've gotten enough info about it. You know, configuring all tools for terminal on Windows is mainly hard. Express extremely appreciation for you.

**Comment by Rickxiaoxin** [comment]
I've got the same problem,but there is a few differece.
`I[16:09:01.620] clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
I[16:09:01.621] Features: windows+grpc
I[16:09:01.621] PID: 3800
I[16:09:01.621] Working directory: e:\C++ Learning\cpp
I[16:09:01.621] argv[0]: D:\clangd_16.0.2\bin\clangd.exe
I[16:09:01.621] argv[1]: --compile_args_from=lsp
I[16:09:01.621] argv[2]: -j=12
I[16:09:01.621] argv[3]: --completion-style=detailed
I[16:09:01.621] argv[4]: --clang-tidy
I[16:09:01.621] argv[5]: --query-driver=D:\mingw64\bin\gcc
I[16:09:01.624] Starting LSP over stdin/stdout
I[16:09:01.625] <-- initialize(0)
I[16:09:01.629] --> reply:initialize(0) 3 ms
I[16:09:01.630] <-- initialized
I[16:09:01.634] <-- textDocument/didOpen
E[16:09:01.637] System include extraction: driver clang not found in PATH
I[16:09:01.637] ASTWorker building file e:\C++ Learning\cpp\C++\13th Chapter\acctabc\usebrass3.cpp version 1 with command clangd fallback
[e:\C++ Learning\cpp\C++\13th Chapter\acctabc]
"D:\\mingw64\\bin\\clang" --target=x86_64-w64-mingw32 "-resource-dir=D:\\clangd_16.0.2\\lib\\clang\\16" -- "e:\\C++ Learning\\cpp\\C++\\13th Chapter\\acctabc\\usebrass3.cpp"`
The set of "--query-driver" seems no function. I've setted "--query-driver=D:\mingw64\bin\gcc" ,but `#include <stdint-gcc.h>` isn't found.In fact ,it exits in mingw. I would appreciate it if you could answer!
