### ISSUE TITLE
Parameter hints for call to overloaded function

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#172]
In the following code:

```
void foo(int);
void foo(std::string);

void bar() {
   foo/*cursor*/
}
```

If I invoke completion with the cursor at the indicated location, I get a single entry that says 

```
foo(...)    [2 overloads]
```

It would be nicer to show the two overloads as separate entries, so I can see the signature for each, pick the one I want to call, and then get parameter hints for the selected function's parameters.

**Comment by kadircet** [comment]
Once you put parentheses, you should get a signature help showing both.

Also you can change the behaviour by passing `--completion-style=detailed` into clangd. But IIRC, we are only turning this to `bundled` in the presence of signature help functionality.

**Comment by HighCommander4** [comment]
> Once you put parentheses, you should get a signature help showing both.

I tried this, but I get the same result (`[2 overloads]`) with or without parentheses.

**Comment by HighCommander4** [comment]
I can confirm that using `--completion-style=detailed` gives the desired behaviour.

**Comment by HighCommander4** [comment]
I am using VSCode as a client. Does this suggest the clangd is expecting VSCode to do something more helpful, that it's not doing?

**Comment by HighCommander4** [comment]
Ok, I see: VSCode has a separate command ("Trigger Parameter Hints", shortcut Ctrl+Shift+Space) which shows the individual signatures when activated. I was expecting that to activate automatically when the completion entry is selected, but it looks like it doesn't.

I think this is just a case of sub-optimal usability on the client side then. I still prefer the `--completion-styled=detailed` behaviour, because you might as well see all the signatures up-front, but I guess that's what the flag is for.

**Comment by LeeProkhor** [comment]
How can I set --completion-style=detailed on Ubuntu? Where is conf file?

**Comment by HighCommander4** [comment]
> How can I set --completion-style=detailed on Ubuntu? Where is conf file?

It's a command-line argument to clangd. The method of setting it depends on the client. For vscode, it can be added to `"clangd.arguments"` in the vscode user or workspace settings.

**Comment by LeeProkhor** [comment]
Thanks, I use neovim and installed clangd using by `kabouzeid/nvim-lspinstall`  plugin. 
In my .config/nvim/init.lua file I added` nvim-lspconfig` and `nvim-compe `plugins for C++ coding, they work OK,
but if method has several overloads (say 3 overloads as on picture below) I can't expand them.
If I understood right, I should set `--completion-style=detailed` [ (https://github.com/clangd/clangd/issues/172) ]
but I can't figure out where is clangd config-file, where I have to add` --completion-style=detailed ("clangd.arguments")`
![overloads](https://user-images.githubusercontent.com/86493671/123539364-0fedfb00-d742-11eb-8e90-868352f151b0.png)

**Comment by HighCommander4** [comment]
It's not going to be a clangd config file, it's going to be a neovim-related config file.

I'm not really familiar with neovim, but a quick read of the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig#quickstart) suggests the file to specify the language server setup is "init.vim".

**Comment by HighCommander4** [comment]
Looking at example config snippets in e.g. [this issue](https://github.com/neovim/nvim-lspconfig/issues/996), it looks like the snippet you'll want is something like:

```
require'lspconfig'.clangd.setup {
  cmd = { "clangd", "--completion-style=detailed" }
}
```

**Comment by LeeProkhor** [comment]
Thanks, tried it. Don't have any errors, but still not expand overload methods.

**Comment by HighCommander4** [comment]
Can you share clangd logs? That should at least allow us to confirm that clangd is seeing the command-line parameter.

**Comment by LeeProkhor** [comment]
I am afraid my system doesn't have clangd logs, cause I installed clangd not from repos, but via `kabouzeid/nvim-lspinstall `plugin.
So I can't find where is clangd logs placed even.

**Comment by LeeProkhor** [comment]
I found where is clangd log on my machine. It was in ~/.cache/nvim/lsp.log
Here is my log

[lsp.log](https://github.com/clangd/clangd/files/6791473/lsp.log)

**Comment by HighCommander4** [comment]
Ok, so the important line is this one near the top:

```
[ ERROR ] 2021-07-09T15:14:23+0300 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/rock/.local/share/nvim/lspinstall/cpp/./clangd/bin/clangd"	"stderr"	"I[15:14:23.122] Working directory: /home/rock/.local/share/nvim/lspinstall/cpp\nI[15:14:23.122] argv[0]: /home/rock/.local/share/nvim/lspinstall/cpp/./clangd/bin/clangd\nI[15:14:23.122] argv[1]: --background-index\nI[15:14:23.154] Starting LSP over stdin/stdout\n"
```

Clangd is being started with the `--background-index` command-line argument, but not `--completion-style=detailed`.

So, whatever you did to configure `--completion-style=detailed` didn't take effect.

**Comment by LeeProkhor** [comment]
Thanks HighCommander4.
I added this code:
```
require'lspconfig'.clangd.setup {
  cmd = { "clangd", "--completion-style=detailed" } 
}
```
to my ~/.config/nvim/init.lua file, but it looks like there isn't any effect.

**Comment by HighCommander4** [comment]
Yup, I understand. I tried to figure out how to configure neovim to provide a command-line argument to clangd based on their documentation, and that's what I came up with, but clearly I'm missing something.

I suggest you ask for further help from people who are actually familar with neovim, such as in the https://github.com/neovim/nvim-lspconfig issue track.

**Comment by kashperanto** [comment]
Apologies for commenting on a dead issue, but I figured I'd post what worked for me using a common newbie neovim setup.

I'm currently using kickstart.nvim, which (when I cloned the repo a year or two ago) uses Lazy as the package manager and nvim-lspconfig as the lsp plugin.

In the large section dedicated to LSP (has a comment `-- LSP Configuration & Plugins`) scroll down to the line with `local servers = {` and add an override configuration for clangd.  Here is a snippet of that section from my init.lua:

```lua
    -- Enable the following language servers
    --  Feel free to add/remove any LSPs that you want here. They will automatically be installed.
    --
    --  Add any additional override configuration in the following tables. Available keys are:
    --  - cmd (table): Override the default command used to start the server
    --  - filetypes (table): Override the default list of associated filetypes for the server
    --  - capabilities (table): Override fields in capabilities. Can be used to disable certain LSP features.
    --  - settings (table): Override the default settings passed when initializing the server.
    --        For example, to see the options for `lua_ls`, you could go to: https://luals.github.io/wiki/settings/
    local servers = {
      clangd = {
        cmd = { 'clangd', '--completion-style=detailed' },
      },
      -- gopls = {},
      -- pyright = {},
      -- rust_analyzer = {},
      -- ... etc. See `:help lspconfig-all` for a list of all the pre-configured LSPs
      ...
```

Also, in my case I had to close and re-open neovim for the LSP to be started with the new argument.  Running :LspRestart did not work, so make sure you close and re-open everything before you go down any rabbit holes.

Before this change it just listed one completion in the list with a note that there are 2 overrides, but didn't expand any arguments or anything.  After this change it has two entries in the completion list (one for each override).
