### ISSUE TITLE
clang --version failed because of the segmentation fault

### ISSUE THREAD

**Issue by freshduer** [clangd/clangd#1723]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html
I use the linux-zip binaries and copy the files in /bin and /lib into /usr/local/bin and /usr/local/lib

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`: 
![image](https://github.com/clangd/clangd/assets/72605280/5d69cf19-b90c-46b6-bedb-a0348c2c0f87)

Editor/LSP plugin:

Operating system:
![image](https://github.com/clangd/clangd/assets/72605280/267d6e06-5247-49f4-a1f9-0844839319cf)

**Comment by HighCommander4** [comment]
> I use the linux-zip binaries

I assume you means binaries from https://github.com/clangd/clangd/releases? What version package did you download? Your screenshots show directories named `clangd_11.0.0` and `clangd_13.0-2.0`, which are both pretty old versions.

**Comment by freshduer** [comment]
> > I use the linux-zip binaries
> 
> I assume you means binaries from https://github.com/clangd/clangd/releases? What version package did you download? Your screenshots show directories named `clangd_11.0.0` and `clangd_13.0-2.0`, which are both pretty old versions.

I have tried clang-16 13 and 11 version ,all of them failed because of this error

**Comment by HighCommander4** [comment]
It would be interesting to try an official LLVM release such as [this one](https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-aarch64-linux-gnu.tar.xz) and see if the crash occurs with that too.

**Comment by freshduer** [comment]
> 

thanks for your help, but my architecture is x86_64...
![image](https://github.com/clangd/clangd/assets/72605280/dd33a6dc-4091-415b-84b6-efd5cc6d217a)

**Comment by HighCommander4** [comment]
My bad, I meant to link to the x86_64 one: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz

I got the link from https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4

**Comment by freshduer** [comment]
> My bad, I meant to link to the x86_64 one: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz
> 
> I got the link from https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4

thanks, so how to use this tar ...Is it the same method as the clangd binaries before?

**Comment by freshduer** [comment]
> My bad, I meant to link to the x86_64 one: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz
> 
> I got the link from https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4

my machine is in a No network environments ,so I prefer the binary method..

**Comment by HighCommander4** [comment]
> > My bad, I meant to link to the x86_64 one: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz
> > I got the link from https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4
> 
> thanks, so how to use this tar ...Is it the same method as the clangd binaries before?

You can extract it using a command line `xz --decompress <filename>` (see https://manpages.org/xz for more details).

**Comment by freshduer** [comment]
> > > My bad, I meant to link to the x86_64 one: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.4/clang+llvm-16.0.4-x86_64-linux-gnu-ubuntu-22.04.tar.xz
> > > I got the link from https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.4
> > 
> > 
> > thanks, so how to use this tar ...Is it the same method as the clangd binaries before?
> 
> You can extract it using a command line `xz --decompress <filename>` (see https://manpages.org/xz for more details).

thanks,now the clangd can print info, but viscose's extension always tells me "The clangd language server is not installed"...but I have changed the clangd path in viscose's setting
å
![image](https://github.com/clangd/clangd/assets/72605280/e59c2f51-98e7-4932-92d7-ef07948790f5)
![image](https://github.com/clangd/clangd/assets/72605280/6b36cf36-bf05-477b-8f4d-cdf96e902432)

**Comment by HighCommander4** [comment]
I believe your issue is the use of `~` in the value of the `clangd.path` setting.

Expanding `~` to `/home/username` is a feature of the shell, it does not happen in vscode setting values; you need to write `/home/username` explicitly.
