### ISSUE TITLE
Cherrypick:

### ISSUE THREAD

**Issue by xcactuzx** [clangd/clangd#1728]
Commit:
-  llvm/llvm-project@

Why is this important or safe?

**Comment by HighCommander4** [comment]
@xcactuzx did you file this by accident? If not, can you fill in information and what you're looking to cherry-pick and why?

**Comment by xcactuzx** [comment]
> Зробити:
> 
> * llvm/llvm-проект@
> 
> Чому це важливо або безпечно?
