### ISSUE TITLE
clangd is very slow on WSL2

### ISSUE THREAD

**Issue by WiresawBlade** [clangd/clangd#1736]
On WSL2, clangd's complement function is very slow, just a file like "hello world" takes about 1 second for me. However, on Windows this process is very fast. VSCode status bar shows that clangd spent a lot of time in "clangd: parsing includes, running EnumerateTweaks". When I switch from WSL2 to WSL1 the speed is back to normal. I'm not sure if this is a clangd issue, as it seems to be only clangd that is experiencing performance issues on WSL2, everything is fine when I write TypeScript or python on WSL2.

Microsoft C/C++ plugin also performs fine on WSL2, but I prefer to use clangd.

```
[/home/blade/projects/c_cpp]
/usr/lib/llvm-14/bin/g++ --driver-mode=g++ -std=c++20 -Wall -Wextra -Wno-unused-parameter -I includes -resource-dir=/home/blade/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/16.0.2/clangd_16.0.2/lib/clang/16 -- /home/blade/projects/c_cpp/main.cpp
I[13:24:50.329] Code complete: sema context Statement, query scopes [] (AnyScope=true), expected type <none>
I[13:24:50.329] Code complete: 27 results from Sema, 100 from Index, 15 matched, 0 from identifiers, 100 returned (incomplete).
I[13:24:50.331] --> reply:textDocument/completion(86) 414 ms
I[13:24:50.353] <-- textDocument/completion(88)
I[13:24:50.455] --> textDocument/clangd.fileStatus
I[13:24:50.517] <-- textDocument/codeAction(89)
I[13:24:50.569] <-- textDocument/foldingRange(90)
I[13:24:50.569] --> reply:textDocument/foldingRange(90) 0 ms
I[13:24:50.802] Code complete: sema context Statement, query scopes [] (AnyScope=true), expected type <none>
I[13:24:50.802] Code complete: 0 results from Sema, 4 from Index, 0 matched, 0 from identifiers, 4 returned.
I[13:24:50.803] --> reply:textDocument/completion(88) 449 ms
I[13:24:50.804] <-- textDocument/documentSymbol(91)
I[13:24:50.904] --> reply:textDocument/semanticTokens/full/delta(87) 587 ms
I[13:24:50.904] Skipping rebuild of the AST for /home/blade/projects/c_cpp/main.cpp, inputs are the same.
I[13:24:50.904] --> textDocument/publishDiagnostics
I[13:24:50.904] --> reply:textDocument/codeAction(89) 386 ms
```

I'm currently using Windows 11 (10.0.25931.1000) with WSL 1.2.5.0.

clangd --version:

```
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

**Comment by WiresawBlade** [comment]
I fixed this issue, it turned out that WSL2 kept Windows environment variables by default causing it to be slow. sorry about that.

**Comment by WiresawBlade** [comment]
I fixed this issue, it turned out that WSL2 kept Windows environment variables by default causing it to be slow. sorry about that.

**Comment by Sawansunar56** [comment]
@WiresawBlade Hello, I wanted to ask how you managed to solve this issue. I cannot quiet understand the comment you wrote. An elaboration would be pretty helpful for me.

**Comment by WiresawBlade** [comment]
> @WiresawBlade Hello, I wanted to ask how you managed to solve this issue. I cannot quiet understand the comment you wrote. An elaboration would be pretty helpful for me.

@Sawansunar56 WSL2 by default adds windows environment variables to the system environment variables as well, and it is well known that IO operations between WSL2 and Windows are slow and for some reason, it slows down clangd.

Specifically, you need to edit the contents of the file `/etc/wsl.conf` . Use `sudo chmod +w /etc/wsl.conf` to make sure you have permission to edit it, then `sudo vim /etc/wsl.conf` , adding at the end of the file:

```
[interop]
appendWindowsPath = false
```

Finally, you need to reboot your WSL completely and then everything will be fine. But this has the side effect that you can no longer quickly initiate a remote connection by typing `code .` inside WSL.

**Comment by Sawansunar56** [comment]
@WiresawBlade Your issue clicked my brain yesterday and I figured that out as well. I use neovim in wsl, and treesitter was accessing nodejs from my windows, that was how I understood your comment about the environment.

Thank you very much, I could have gone forever not noticing this detail.
