### ISSUE TITLE
InlayHint for operator()

### ISSUE THREAD

**Issue by zyn0217** [clangd/clangd#1742]
We don't show parameter hints for a user-defined function call operator() nor a call to lambda, for example:
```cpp
struct S {
  void operator()(int x, int y) const;
};

void foo() {
  auto lambda = [](auto x) {};
  S()(1, 2); // nothing here.
  lambda("abcd") // nothing here.
}
```

This seems to be intended, as per the comment from [InlayHints.cpp](https://searchfox.org/llvm/rev/cbc9c4ea90e17980b7b65966f4bbdba26a395e45/clang-tools-extra/clangd/InlayHints.cpp#40):

```cpp
// Do not show parameter hints for operator calls written using operator
// syntax or user-defined literals. (Among other reasons, the resulting
// hints can look awkard, e.g. the expression can itself be a function
// argument and then we'd get two hints side by side).
```

However, I think it'd be fine to be lenient on function call to `operator()`: They are formed in a normal function call syntax, and I didn't find a case where they are inappropriate.

Nathan, what do you think? @HighCommander4

**Comment by zyn0217** [comment]
https://reviews.llvm.org/D158926

**Comment by HighCommander4** [comment]
> However, I think it'd be fine to be lenient on function call to `operator()`: They are formed in a normal function call syntax, and I didn't find a case where they are inappropriate.
> 
> Nathan, what do you think? @HighCommander4

+1, that seems like an oversight
