### ISSUE TITLE
clangd cannot escape compile-time recursion

### ISSUE THREAD

**Issue by UeType** [clangd/clangd#1745]
I wrote the code like the following.
```cpp
#include <vector>
struct AnyType {
  template <typename T> operator T();
};

using T = std::vector<int>;

consteval int f(auto&&... args) {
  if constexpr (requires { T{ args... }; }) return f(args..., AnyType{});
  else return 0;
}

int main() {
  auto i = f();
}
```
When I type this, *'The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.'*

There is no doubt that the `f()` will keep recursing. And it seems that clangd tries to calculate the result without stopping.

**Comment by zyn0217** [comment]
Looks like we forgot to call `clang::noteBottomOfStack()` at the beginning of the main function, which is [required](https://searchfox.org/llvm/source/clang/lib/Basic/Stack.cpp#52) for [`clang::runWithSufficientStack`](https://searchfox.org/llvm/source/clang/include/clang/Basic/Stack.h#40) to work.

(note: [usage](https://searchfox.org/llvm/source/clang/tools/driver/driver.cpp#379) in clang driver.)

**Comment by zyn0217** [comment]
Patch: https://reviews.llvm.org/D158967

**Comment by zyn0217** [comment]
Fixed in 17. Thanks for reporting again!

**Comment by HighCommander4** [comment]
Closing since this has been fixed.
