### ISSUE TITLE
Mason lsp clangd could not find header files (stdio.h, etc.)

### ISSUE THREAD

**Issue by dduyanhhoang** [clangd/clangd#1758]
I am setting up my neovim by using kickstart neovim for my development environment on a windows machine. Right after successfully apply the kickstart, I add clangd lsp using mason. Seems like it could not automatically locate my gcc (installed with scoop). I have found this slightly similar issue and I am kinda lost because I don't no how or where to pass these configuration to clangd lsp. 

```
  "clangd.arguments": [
    "--query-driver=/usr/bin/clang++",
    "--background-index"
  ],
```

_Originally posted by @fannheyward in https://github.com/clangd/coc-clangd/issues/313#issuecomment-889595229_

**Comment by HighCommander4** [comment]
> I don't no how or where to pass these configuration to clangd lsp.

The quoted comment indicates it should go in a file named `coc-settings.json`.

I don't know more details (such as where that file is located) either, that's a better question for https://github.com/clangd/coc-clangd/issues.

**Comment by fannheyward** [comment]
It's not clangd or coc-clangd issue , but how to set arguments in Lua, check nvim LSP docs.
