### ISSUE TITLE
False positive when capturing a variable declared through a binding

### ISSUE THREAD

**Issue by jacekpoz** [clangd/clangd#1765]
Not sure if the title is clear but when declaring a variable through a binding and then trying to capture and use it in a lambda I get an error that doesn't exist when compiling:
```
#include <functional>
#include <iostream>

int main() {
    int a[2] = {0, 1};

    auto [b, c] = a;
    auto d = a[0];
    auto e = a[1];

    std::function<void()> f = [a, b, c, d, e]() {
        std::cout << "a: " << a << "\nb: " << b << "\nc: " << c << "\nd: " << d << "\ne: " << e << "\n";
    };

    f();
}
```

I get these errors on the capture:
```
Diagnostics:
1. 'b' in capture list does not name a variable [capture_does_not_name_variable]
2. 'c' in capture list does not name a variable [capture_does_not_name_variable]
```
and these when trying to use the variables inside the capture:
```
Diagnostics:
1. Reference to local binding 'b' declared in enclosing function 'main' [reference_to_local_in_enclosing_context]
2. Reference to local binding 'c' declared in enclosing function 'main' [reference_to_local_in_enclosing_context]
```

The code compiles and runs fine.

**System information**

Output of `clangd --version`:
```
clangd version 14.0.6
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: neovim, nvim-lspconfig

Operating system: NixOS Unstable

**Comment by HighCommander4** [comment]
Capturing structured bindings is a C++20 feature that, according to https://clang.llvm.org/cxx_status.html, was first added to clang in clang 16 (see "Structured bindinge extensions").

As such, you need clangd 16 or later to understand them.

**Comment by jacekpoz** [comment]
should've checked, thank you!
