### ISSUE TITLE
RawStringLiteral code action is inconsistent

### ISSUE THREAD

**Issue by vnfedotov** [clangd/clangd#1766]
I'm testing vscode-clangd on a following chunk of code:
```
static void first_process(void)
{
    printf("First process\n");
    RETURN_CODE_TYPE ret;
    int              i = 0;
    while (1)
    {
        printf("First process iteration %d.\n", i);
        SEND_BUFFER(global_buffer_id, (MESSAGE_ADDR_TYPE) &i, sizeof(i), 0, &ret);
        if (ret != NO_ERROR)
        {
            printf("couldn't send to the buffer: %d\n", (int) ret);
            break;
        }
        i++;
        TIMED_WAIT(500000000LL, &ret);
    }
}
```

1. For the first printf call, on line 3, "Convert to raw string" code action is available
2. For the second printf call, on line 8, "Convert to raw string" code action is available
3. For the third printf call, on line 12, no code actions are available

From my understaning, this code action should be available only for strings with escaped characters, so it should be consistent for all three printf calls, either available for all of them or for none.

**Logs**

Relevant part of clangd log with --log=verbose

[clangd.log](https://github.com/clangd/clangd/files/12683648/clangd.log)

**System information**

Output of `clangd --version`: 
Apple clangd version 14.0.3 (clang-1403.0.22.14.1)

Editor/LSP plugin:
Theia 1.41
vscode 1.82.0

Operating system:
Ventura 13.4.1

**Comment by sam-mccall** [comment]
With a recent snapshot clangd, the action works in all three places for me, after deleting the parts that don't compile (RETURN_CODE_TYPE etc).

Can you try with a recent release, and if it still reproduces share a complete example?

(Note that `Apple clangd version 14.0.3` is a fork that doesn't correspond to an official clangd release, but more importantly might be old - apple's version numbers are unrelated to the upstream LLVM versions)

**Comment by vnfedotov** [comment]
Checked on more recent versions 15.0.7 and 16.0.6, it works as it should after I've added correct compile_commands.json. So yeah, doesn't seem like a bug.

**Comment by vit9696** [comment]
@sam-mccall, @vnfedotov, it does not work as it should I believe. I explored the codebase and realised that `clang-tools-extra/clangd/refactor/tweaks/RawStringLiteral.cpp` does not check the source language used. As a result `RawStringLiteral` tweak reports suggestions even for pure C code, which has no raw string literals, not just C++.

Shall we reopen the issue or file a new one?

**Comment by HighCommander4** [comment]
@vit9696 please file a new issue.

**Comment by vit9696** [comment]
Currently in https://github.com/clangd/clangd/issues/1795.
