### ISSUE TITLE
UnusedIncludes dosen't check angle includes

### ISSUE THREAD

**Issue by FeignClaims** [clangd/clangd#1774]
<img width="260" alt="image" src="https://github.com/clangd/clangd/assets/62583114/55507af8-bee6-473e-9f48-dde43ee945e9">

<img width="842" alt="image" src="https://github.com/clangd/clangd/assets/62583114/c0599ecd-b25b-4181-9985-942d8ff08810">

configured using `cmake -S . -B build -G 'Ninja' -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.27)
project(starter)

add_executable(main)
target_sources(main
  PRIVATE
  main.cpp
)
target_include_directories(main
  PRIVATE
  .
)
```

main.cpp

```cpp
#include <hello.hpp>
```

hello.hpp

```cpp
#ifndef HELLO_HPP
#define HELLO_HPP

inline void hello() {}

#endif
```

.clangd

```cpp
Diagnostics:
  UnusedIncludes: Strict
```

**Logs**

for `#include "hello.hpp"`

```txt
V[19:46:25.318] <<< {"id":31,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":19,"line":0},"textDocument":{"uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}}

I[19:46:25.319] <-- textDocument/documentHighlight(31)
V[19:46:25.319] ASTWorker running Highlights on version 94 of /Users/feignclaims/code/cpp/temp/main.cpp
I[19:46:25.319] --> reply:textDocument/documentHighlight(31) 0 ms
V[19:46:25.319] >>> {"id":31,"jsonrpc":"2.0","result":[]}

I[19:46:25.319] --> textDocument/clangd.fileStatus
V[19:46:25.319] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}

V[19:46:25.569] <<< {"id":32,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"unused-includes","codeDescription":{"href":"https://clangd.llvm.org/guides/include-cleaner"},"message":"Included header hello.hpp is not used directly (fix available)","range":{"end":{"character":20,"line":0},"start":{"character":0,"line":0}},"relatedInformation":[],"severity":2,"source":"clangd","tags":[1]}],"triggerKind":2},"range":{"end":{"character":19,"line":0},"start":{"character":19,"line":0}},"textDocument":{"uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}}

I[19:46:25.569] <-- textDocument/codeAction(32)
V[19:46:25.569] ASTWorker running codeAction on version 94 of /Users/feignclaims/code/cpp/temp/main.cpp
I[19:46:25.569] --> reply:textDocument/codeAction(32) 0 ms
V[19:46:25.569] >>> {"id":32,"jsonrpc":"2.0","result":[{"diagnostics":[{"code":"unused-includes","message":"Included header hello.hpp is not used directly (fix available)","range":{"end":{"character":20,"line":0},"start":{"character":0,"line":0}},"severity":2,"source":"clangd"}],"edit":{"documentChanges":[{"edits":[{"newText":"","range":{"end":{"character":0,"line":1},"start":{"character":0,"line":0}}}],"textDocument":{"uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp","version":94}}]},"isPreferred":true,"kind":"quickfix","title":"remove #include directive"}]}

I[19:46:25.570] --> textDocument/clangd.fileStatus
V[19:46:25.570] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}
```

for `#include <hello.hpp>`

```txt
V[19:45:55.341] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":19,"line":0},"textDocument":{"uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}}

I[19:45:55.341] <-- textDocument/documentHighlight(8)
V[19:45:55.341] ASTWorker running Highlights on version 92 of /Users/feignclaims/code/cpp/temp/main.cpp
I[19:45:55.341] --> reply:textDocument/documentHighlight(8) 0 ms
V[19:45:55.341] >>> {"id":8,"jsonrpc":"2.0","result":[]}

I[19:45:55.341] --> textDocument/clangd.fileStatus
V[19:45:55.341] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}

V[19:45:55.590] <<< {"id":9,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":19,"line":0},"start":{"character":19,"line":0}},"textDocument":{"uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}}

I[19:45:55.590] <-- textDocument/codeAction(9)
V[19:45:55.590] ASTWorker running codeAction on version 92 of /Users/feignclaims/code/cpp/temp/main.cpp
I[19:45:55.590] --> reply:textDocument/codeAction(9) 0 ms
V[19:45:55.590] >>> {"id":9,"jsonrpc":"2.0","result":[]}

I[19:45:55.590] --> textDocument/clangd.fileStatus
V[19:45:55.590] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///Users/feignclaims/code/cpp/temp/main.cpp"}}
```

**System information**

Output of `clangd --version`:

```txt
Homebrew clangd version 17.0.1
Features: mac+xpc
Platform: arm64-apple-darwin23.0.0
```

Editor/LSP plugin:

```
VSCode clangd 0.1.24
```

Operating system:

```txt
arm64-apple-darwin22.5.0
```

**Comment by HighCommander4** [comment]
This has come up in https://github.com/clangd/vscode-clangd/issues/452 as well.

I suspect it may be intentional, though I don't know the motivation for it. Perhaps some folks who worked on include-cleaner such as @VitaNuo or @kadircet can provide some details.

**Comment by kiwixz** [comment]
Clangd currently doesn't support detecting what's used in transitive includes.  You can see it with such a setup:
- super_specific_header.hpp
```cpp
#pragma once

void mylib_specific_function();
```
- mylib.h
```cpp
#pragma once

#include "super_specific_header.hpp"
```
- main.cpp
```cpp
// doc says you should use this umbrella header to pull the whole thing
// but you'll get a warning if you used "" instead of <>
#include "mylib.h"

int main() { mylib_specific_function(); }
```

So clangd simply ignores all angle includes (except from std) to not produce false positives with this common pattern.

See [here](https://github.com/llvm/llvm-project/blob/c0a1fcd3bf8ead39e8f0290a8a0af1e0367c7cad/clang-tools-extra/clangd/IncludeCleaner.cpp#L85) if you want to work on this.

**Comment by HighCommander4** [comment]
Assuming that an angle include is a system header doesn't seem justified, since, when resolving an angle include, the compiler does look at regular entries of the include search path after looking at system entries.

A more accurate check for "system header" would be that it was found in an entry of the include search path specified using `-isystem`.

**Comment by sam-mccall** [comment]
@kadircet Is this check still needed?

Standalone clang-include-cleaner doesn't have it, so I suspect the new include-cleaner lib is robust enough to handle system includes (at least for the people willing to use it). If we want to conservatively avoid analyzing system headers we should at least switch to CharacteristicKind (-isystem) and make this a config option with a conservative default.

The original intent was to disable analysis of weird-layout libraries like C++ standard library, C standard library, posix etc.
Angle was a heuristic to cover those, and also other suspected cases. I don't remember if there were technical issues with using CharacteristicKind or it was just oversight.

**Comment by kiwixz** [comment]
> The original intent was to disable analysis of weird-layout libraries like C++ standard library, C standard library, posix etc.

I don't think that's it.  Standard library headers are handled separately.  This was done to avoid errors with umbrella headers.

It'd be nice to keep it this behavior at least behind an option so I don't get spammed with warnings for third party libs, but still enjoy the check on my code that I include with `"`.
