### ISSUE TITLE
indexed c++14 standard library incomplete due to errors on

### ISSUE THREAD

**Issue by LoadLife** [clangd/clangd#1779]
- clangd report error when i include standard library
- clangd can't find my header file (pp_file_not_found)

**code**
- my code are here https://github.com/LoadLife/CppTest  

**Logs**  
I[16:06:49.221] --> textDocument/clangd.fileStatus
V[16:06:49.221] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Program%20Files/Microsoft%20Visual%20Studio/2022/Community/VC/Tools/MSVC/14.31.31103/include/deque"}}

V[16:06:49.446] indexed preamble AST for d:\Jupj\Cpp_Test\struct\src\pImpl.cc version 1:
  symbol slab: 6339 symbols, 1642808 bytes
  ref slab: 0 symbols, 0 refs, 136 bytes
  relations slab: 87 relations, 1622 bytes
V[16:06:49.481] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:98:10:#include nested too deeply
V[16:06:49.481] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:104:10:#include nested too deeply
V[16:06:49.482] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:107:10:#include nested too deeply
V[16:06:49.482] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:110:10:#include nested too deeply
V[16:06:49.483] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:113:10:#include nested too deeply
V[16:06:49.483] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:116:10:#include nested too deeply
V[16:06:49.483] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:119:10:#include nested too deeply
V[16:06:49.483] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:125:10:#include nested too deeply
V[16:06:49.484] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:131:10:#include nested too deeply
V[16:06:49.484] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:143:10:#include nested too deeply
V[16:06:49.484] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:149:10:#include nested too deeply
V[16:06:49.484] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:155:10:#include nested too deeply
V[16:06:49.484] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:164:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:167:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:173:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:176:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:182:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:185:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\deque:188:10:#include nested too deeply
V[16:06:49.485] Ignored diagnostic. too many errors emitted, stopping now
V[16:06:49.491] <<< {"id":13,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"1","textDocument":{"uri":"file:///d%3A/Jupj/Cpp_Test/struct/src/stack.cc"}}}

I[16:06:49.491] <-- textDocument/semanticTokens/full/delta(13)
V[16:06:49.491] ASTWorker running SemanticHighlights on version 1 of d:\Jupj\Cpp_Test\struct\src\stack.cc
I[16:06:49.492] --> reply:textDocument/semanticTokens/full/delta(13) 0 ms
V[16:06:49.492] >>> {"id":13,"jsonrpc":"2.0","result":{"edits":[],"resultId":"2"}}

I[16:06:49.492] --> textDocument/clangd.fileStatus
V[16:06:49.492] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Jupj/Cpp_Test/struct/src/stack.cc"}}

V[16:06:49.498] Build dynamic index for header symbols with estimated memory usage of 5308376 bytes
I[16:06:49.507] Built preamble of size 3852216 for file d:\Jupj\Cpp_Test\struct\src\pImpl.cc version 1 in 0.72 seconds
I[16:06:49.508] --> workspace/semanticTokens/refresh(4)
I[16:06:49.508] --> textDocument/clangd.fileStatus
V[16:06:49.508] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST","uri":"file:///d:/Jupj/Cpp_Test/struct/src/pImpl.cc"}}

I[16:06:49.508] --> textDocument/clangd.fileStatus
V[16:06:49.508] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, parsing main file","uri":"file:///d:/Jupj/Cpp_Test/struct/src/pImpl.cc"}}

V[16:06:49.509] >>> {"id":4,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

V[16:06:49.509] <<< {"id":4,"jsonrpc":"2.0","result":null}

I[16:06:49.509] <-- reply(4)
V[16:06:49.516] <<< {"id":14,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"2","textDocument":{"uri":"file:///d%3A/Jupj/Cpp_Test/struct/src/stack.cc"}}}

I[16:06:49.516] <-- textDocument/semanticTokens/full/delta(14)
V[16:06:49.516] ASTWorker running SemanticHighlights on version 1 of d:\Jupj\Cpp_Test\struct\src\stack.cc
I[16:06:49.516] --> reply:textDocument/semanticTokens/full/delta(14) 0 ms
V[16:06:49.516] >>> {"id":14,"jsonrpc":"2.0","result":{"edits":[],"resultId":"3"}}

I[16:06:49.516] --> textDocument/clangd.fileStatus
V[16:06:49.516] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Jupj/Cpp_Test/struct/src/stack.cc"}}

V[16:06:49.589] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.590] Dex query tree: (LIMIT 10000 (& T=lun T=pim T=plu T=niq T=uep T=iqu T=uni T=ept T=mpl T=imp T=que T=ptr S= ?=Restricted For Code Completion))
V[16:06:49.591] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.593] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.597] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.599] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.601] Trying to fix unresolved name "pImpl_unique_ptr" in scopes: []
V[16:06:49.602] indexed file AST for d:\Jupj\Cpp_Test\struct\src\pImpl.cc version 1:
  symbol slab: 0 symbols, 128 bytes
  ref slab: 0 symbols, 0 refs, 136 bytes
  relations slab: 0 relations, 24 bytes
V[16:06:49.604] Build dynamic index for main-file symbols with estimated memory usage of 404048 bytes
I[16:06:49.604] --> textDocument/publishDiagnostics
V[16:06:49.605] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"pp_file_not_found","message":"'pImpl.h' file not found","range":{"end":{"character":18,"line":0},"start":{"character":9,"line":0}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":23,"line":3},"start":{"character":7,"line":3}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":8},"start":{"character":0,"line":8}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":12},"start":{"character":0,"line":12}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":57,"line":12},"start":{"character":41,"line":12}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":16},"start":{"character":0,"line":16}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":34,"line":16},"start":{"character":18,"line":16}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":68,"line":16},"start":{"character":52,"line":16}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":21},"start":{"character":0,"line":21}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":51,"line":21},"start":{"character":35,"line":21}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":23},"start":{"character":0,"line":23}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":34,"line":23},"start":{"character":18,"line":23}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"unknown_typename","message":"Unknown type name 'pImpl_unique_ptr'","range":{"end":{"character":62,"line":23},"start":{"character":46,"line":23}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":21,"line":25},"start":{"character":5,"line":25}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_unique_ptr'","range":{"end":{"character":16,"line":29},"start":{"character":0,"line":29}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_shared_ptr'","range":{"end":{"character":23,"line":33},"start":{"character":7,"line":33}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_shared_ptr'","range":{"end":{"character":16,"line":38},"start":{"character":0,"line":38}},"relatedInformation":[],"severity":1,"source":"clang"},{"code":"undeclared_var_use","message":"Use of undeclared identifier 'pImpl_shared_ptr'","range":{"end":{"character":21,"line":42},"start":{"character":5,"line":42}},"relatedInformation":[],"severity":1,"source":"clang"}],"uri":"file:///d:/Jupj/Cpp_Test/struct/src/pImpl.cc","version":1}}

I[16:06:49.607] --> textDocument/clangd.fileStatus
V[16:06:49.607] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/Jupj/Cpp_Test/struct/src/pImpl.cc"}}

I[16:06:49.618] Indexed c++14 standard library (incomplete due to errors): 6370 symbols, 2585 filtered
V[16:06:49.754] Build dynamic index for header symbols with estimated memory usage of 5741472 bytes
V[16:06:49.936] indexed preamble AST for d:\Jupj\Cpp_Test\test\test_std_thread.cc version 1:
  symbol slab: 10343 symbols, 3014104 bytes
  ref slab: 0 symbols, 0 refs, 136 bytes
  relations slab: 289 relations, 5396 bytes
V[16:06:50.000] Build dynamic index for header symbols with estimated memory usage of 6881808 bytes
I[16:06:50.015] Built preamble of size 7727416 for file d:\Jupj\Cpp_Test\test\test_std_thread.cc version 1 in 1.71 seconds
I[16:06:50.021] --> textDocument/clangd.fileStatus
V[16:06:50.021] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST","uri":"file:///d:/Jupj/Cpp_Test/test/test_std_thread.cc"}}

I[16:06:50.021] --> textDocument/clangd.fileStatus
V[16:06:50.021] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, parsing main file","uri":"file:///d:/Jupj/Cpp_Test/test/test_std_thread.cc"}}

I[16:06:50.022] --> workspace/semanticTokens/refresh(5)
V[16:06:50.022] >>> {"id":5,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

V[16:06:50.042] <<< {"id":5,"jsonrpc":"2.0","result":null}

I[16:06:50.042] <-- reply(5)
V[16:06:50.062] Trying to fix unresolved name "Thread" in scopes: []
V[16:06:50.063] Dex query tree: (LIMIT 10000 (& T=hre T=thr T=ead T=rea S= ?=Restricted For Code Completion))
V[16:06:50.065] Trying to fix unresolved name "pool" in scopes: []
V[16:06:50.065] Dex query tree: (LIMIT 10000 (& T=ool T=poo S= ?=Restricted For Code Completion))
V[16:06:50.066] <<< {"id":15,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full/delta","params":{"previousResultId":"3","textDocument":{"uri":"file:///d%3A/Jupj/Cpp_Test/struct/src/stack.cc"}}}

**System information**
- windows10 x86_64
- msvc 2022

Output of `clangd --version`:
- clangd_16.02

Editor/LSP plugin:
- vscode && clangd extension

Operating system:
- windows10

**Comment by HighCommander4** [comment]
The attached logs are cut off at the start -- please post logs starting from clangd's startup.

**Comment by LoadLife** [comment]
> The attached logs are cut off at the start -- please post logs starting from clangd's startup.

thanks for your help, And the log is too big, i set it on https://github.com/LoadLife/CppTest/blob/main/clangd_output.log

**Comment by HighCommander4** [comment]
Have you followed the [project setup instructions](https://clangd.llvm.org/installation#project-setup)?

**Comment by LoadLife** [comment]
> Have you followed the [project setup instructions](https://clangd.llvm.org/installation#project-setup)?

thanks for your hint！I noticed that no compile_commands.json was on my build dir. After search i found that on the Windows msvc, i must use the Ninja generator to produce it
