### ISSUE TITLE
Support IWYU pragma: always_keep

### ISSUE THREAD

**Issue by shahamran** [clangd/clangd#1786]
Hi, I noticed clangd only supports a small subset of IWYU pragmas, and I recently needed it to respect `IWYU pragma: always_keep`.

Is this something you're willing to implement?

TIA!

**Comment by sam-mccall** [comment]
This is supported as of https://github.com/llvm/llvm-project/commit/778a5e9bc633. It hasn't made it to a release yet as it's pretty new.

(In fact it was @kadircet who proposed the pragma: https://github.com/include-what-you-use/include-what-you-use/issues/1235)
