### ISSUE TITLE
Clangd weekly builds are broken on windows

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#1793]
It seems like we can't link our binaries on windows for the past month, https://github.com/clangd/clangd/actions/runs/6292555383/job/17082076402#step:13:4223.

It'd be great if anyone with access to a windows machine can take a look and try to repro (I assume something changed in LLVM build graph resulting us dynamically linking certain libraries). Otherwise I'll update this issue when I start digging.

**Comment by Ceron257** [comment]
The `autobuild.yaml` still uses `"-DLLVM_USE_CRT_RELEASE=MT"` which recently got removed in https://github.com/llvm/llvm-project/pull/66850. Should it instead be `"-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded"` in `autobuild.yaml`?

**Comment by Ceron257** [comment]
I have tested the fix locally and also triggered the workflow on a fork. It fixes the issue and I created #1796 for this.

**Comment by i-ky** [comment]
@kadircet, could you please have a look at #1796?
