### ISSUE TITLE
C Header A uses definition from C Header B, C Header B includes C Header A and gives error

### ISSUE THREAD

**Issue by Cyuria** [clangd/clangd#1794]
Consider two headers, `a.h` and `b.h`.
`a.h` contains some field which uses a definition from `b.h`.
`b.h` needs to include `a.h` for whatever reason.

This compiles perfectly (with -Weverything) without any warnings or errors in clang,
however when I open `b.h` in my editor, clangd gives a warning `In included file: field has incomplete type`

The type would be complete, were it not for the pragma guards, without which a recursive header include error would be given.

Simple reproducible example:

`animals.h`
```C
#pragma once

#include "bears.h"

struct animals {
  struct teddybear winniethepooh;
};
```
`bears.h`
```C
#pragma once

#include "animals.h" // Clangd error here

struct teddybear {
  char* name;
};
```

Opening `bears.h` gives an error on line 3 `In included file: field has incomplete type 'struct teddybear'`

I have tried forward declaring the `struct teddybear;` in `animals.h` after the `bears.h` include, before the `bears.h` include and in `bears.h` before the `animals.h` include, none make a difference.

It is possible to resolve the issue by moving the `struct teddybear` definition itself before the `animals.h` include inside `bear.h` however this likely violates every single good practice guideline and makes it impossible to use any other definitions from `animals.h` inside the teddybear struct without first forward declaring those definitions above `struct teddybear`

In theory doing so might be a fix (lol), however ISO C++ forbids enum forward declarations and correct me if I'm wrong, but I'm pretty sure you can't forward declare unions (the forward declaration doesn't actually declare anything as far as I can tell).

**Logs**

Here is my LSP log (paths have been adjusted)
[lsplog.txt](https://github.com/clangd/clangd/files/12998880/lsplog.txt)

**System information**

Output of `clangd --version`:
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
neovim + mason

Operating system:
Kali GNU/Linux Rolling x86_64

**Comment by HighCommander4** [comment]
> This compiles perfectly (with -Weverything) without any warnings or errors in clang

Can you elaborate on what is "this"?

Presumably, you are not compiling header files, but source files that include them, so what those source files look like is also relevant.

For example, a source file named `main.cpp` which contains:

```c++
#include "bears.h"
```

does **not** compile, and in fact gives the same `field has incomplete type" error.

**Comment by Cyuria** [comment]
Thanks for taking a look at this. I was compiling by including the `animals.h` header, which on reflection was a mistake, and you're right, clang can't compile when including `bears.h` maybe this should be an issue with clang itself? I don't think this is intended behaviour.

It prevents using definitions like the following when include `bears.h` but not if you include `animals.h` first.
`animals.h`
```c
#pragma once

#include "bears.h"

enum species { blackbear, polarbear };

struct animals {
  struct teddybear winniethepooh;
};
```
`bears.h`
```c
#pragma once

#include "animals.h"

struct teddybear {
  enum species s;
  const char* name;
};
```

**Comment by HighCommander4** [comment]
I don't think there is a bug in any compiler or tool here, the behaviour you're describing is consistent with the standard, and seen with both clang and gcc like you say.

In terms of best practices for code organization, my suggestion would be to make the header files more granular in a case like this, for example:

 * `species.h` defines just `enum species`
 * `bears.h` includes `species.h` (but not `animals.h`) and defines `struct teddybear`
 * `animals.h` includes `bears.h` and defines `struct animals`
