### ISSUE TITLE
RawStringLiteral code action is available for pure C code

### ISSUE THREAD

**Issue by vnfedotov** [clangd/clangd#1795]
It seems that implementation of RawStringLiteral (`clang-tools-extra/clangd/refactor/tweaks/RawStringLiteral.cpp`) doesn't check for the source language. As a result, `Convert to raw string` code action is available for pure C code, which doesn't have raw strings.

I've put together a very simple test to demonstrate this behaviour: https://github.com/vnfedotov/ls-interact/blob/master/test_clangd_code_actions.py

**Logs**

[log_verbose.txt](https://github.com/clangd/clangd/files/13025805/log_verbose.txt)

**System information**

Output of `clangd --version`: 17.0.3

Editor/LSP plugin: https://github.com/simark/ls-interact

Operating system: MacOS Ventura 13.4.1

**Comment by robozati** [comment]
Can I be assigned to this? I want to start contributing and this seems easy to fix using `SourceManager` and checking if the file ends with `.c`.

**Comment by mnakama** [comment]
Considering that gcc 10 has support for raw strings in C since July 2023, is there an easy way to disable this check so clangd doesn't report a bunch of syntax errors in my code? Does clangd have a way to determine what version of C compiler I'm using and allow raw strings if >= gcc 10?

**Comment by HighCommander4** [comment]
@mnakama This issue is about a code action (a refactoring, that you have to invoke explicitly) to turn a regular string into a raw string). Please file a new issue for the scenario where you're seeing syntax errors.

**Comment by mnakama** [comment]
Thanks, I misunderstood.
