### ISSUE TITLE
SelectionTree goes into implicit ShadowDecls

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#18]
```cpp
void foo(int);

namespace ns {
using ::f^oo;
};
```

This results in the following SelectionTree:
```
TranslationUnitDecl 
  NamespaceDecl namespace ns {
}
   .UsingDecl using ::foo
   .UsingShadowDecl
```

In which the using shadow decl should not reside. Since contract on selection tree is only for "visible" ast nodes, see https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/Selection.h#L78.

**Comment by sam-mccall** [comment]
Yeah I'd seen this. It's confusing and I'm not sure the behavior is right. However I'm also not sure I agree with the characterisation of ShadowDecl as implicit, so I don't think it's clear-cut.

**Comment by sam-mccall** [comment]
This no longer reproduces. I think it was https://github.com/llvm/llvm-project/commit/395fde753c912e66964e1ce097f1ea6c59c79576
