### ISSUE TITLE
A problem of including library

### ISSUE THREAD

**Issue by huanmoon** [clangd/clangd#1803]
### Discussed in https://github.com/clangd/clangd/discussions/1802

<div type='discussions-op-text'>

<sup>Originally posted by **huanmoon** October 25, 2023</sup>
I'm using clangd with coc-clangd in neovim and I am writing a c++ file with library ncurses.h
the functions in this library are very similar to curses.h so clangd include curses.h automaticlly, but I just want to use ncurses.h not curses.h
I've post an issue in coc-clangd and someone told me that it is an issue of clangd, not an issue of coc-clangd(https://github.com/clangd/coc-clangd/issues/633)
Can someone tell me how to fix it?
Thanks in advance! =)</div>

**Comment by i-ky** [comment]
On my system `ncurses.h` is simply a symlink to `curses.h`:
```
$ ls -l /usr/include/*curses.h
-rw-r--r-- 1 root root 100242 May 16 21:25 /usr/include/curses.h
lrwxrwxrwx 1 root root      8 May 16 21:25 /usr/include/ncurses.h -> curses.h
```
This could have confused clangd, I guess... (If you `#include <ncurses.h>`, clangd follows the symlink and indexes `curses.h`. Then, knowing that certain symbols are provided by `curses.h`, clangd uses them as suggestions.)

**Comment by huanmoon** [comment]
> On my system `ncurses.h` is simply a symlink to `curses.h`:
> 
> ```
> $ ls -l /usr/include/*curses.h
> -rw-r--r-- 1 root root 100242 May 16 21:25 /usr/include/curses.h
> lrwxrwxrwx 1 root root      8 May 16 21:25 /usr/include/ncurses.h -> curses.h
> ```
> 
> This could have confused clangd, I guess... (If you `#include <ncurses.h>`, clangd follows the symlink and indexes `curses.h`. Then, knowing that certain symbols are provided by `curses.h`, clangd uses them as suggestions.)
> 
> May be related to #124.

Thank you and I realized that curses.h is ncurses.h
