### ISSUE TITLE
clangd Segmentation fault in ASTNodeKind

### ISSUE THREAD

**Issue by dennisoberg** [clangd/clangd#1804]
Have built the latest clang from commit c45466cd9a51fe384d2b31e124b77d14c821eb70

emwobde@seroiuts01515 .../llvm-project/build/bin (main)$ ./clangd --version
clangd version 18.0.0 (/workspace/git/emwobde/llvm-project/clang c45466cd9a51fe384d2b31e124b77d14c821eb70)
Features: linux
Platform: x86_64-unknown-linux-gnu

When runnig clangd on all our files it works except one file that makes clangd segmentation fault

See attached file for the output from command:
clangd --log=verbose --check=mars/traf/handlers/test/HccdHandlerTest.cpp

[clangd_HccdHandlerTest.log](https://github.com/clangd/clangd/files/13167071/clangd_HccdHandlerTest.log)

No segmentation fault when using clang/13.0.1 or clang/16.0.3

**Comment by dennisoberg** [comment]
Attached my .clang-tidy
[clang-tidy.txt](https://github.com/clangd/clangd/files/13173695/clang-tidy.txt)

**Comment by HighCommander4** [comment]
Ok, so there are quite a few clang-tidy checks enabled.

Usually, my suggestion in cases like this is to disable the crashing check in `.clangd`, however in a case like this where the crash is in the AST matcher itself, the stack trace doesn't show which check is the relevant one.

Does the crash occur with a corresponding version of (18.0) of `clang-tidy` run on the command line (with the same `.clang-tidy` file)?

**Comment by dennisoberg** [comment]
You are right. It is clang-tidy that does the segmentation fault.
Attached file clang-tidy_segmentation_fault.txt
[clang-tidy_segmentation_fault.txt](https://github.com/clangd/clangd/files/13185613/clang-tidy_segmentation_fault.txt)

**Comment by HighCommander4** [comment]
> It is clang-tidy that does the segmentation fault. Attached file clang-tidy_segmentation_fault.txt [clang-tidy_segmentation_fault.txt](https://github.com/clangd/clangd/files/13185613/clang-tidy_segmentation_fault.txt)

Thanks for checking.

Could you report the clang-tidy crash at https://github.com/llvm/llvm-project/issues please?

**Comment by dennisoberg** [comment]
Yes. A new bug reported in the correct project.
Case can be closed.

**Comment by HighCommander4** [comment]
Thanks!

Linking to the issue for reference: https://github.com/llvm/llvm-project/issues/70460
