### ISSUE TITLE
clangd find references - macros

### ISSUE THREAD

**Issue by dfszb** [clangd/clangd#181]
In my projects, when using clangd, lsp-find-references won't find references for macros. 
Note that lsp-find-definition seems to work.
Note that when using ccls, this seems to work OK (so this seems to be a clangd issue).
I am using clangd 9.0.0
```
clangd --version
clangd version 9.0.0 (tags/RELEASE_900/final)
```
How to reproduce: 
With this simple code, lsp-find-references will not find reference for macro ABC:
```
#include <iostream>
#define ABC(d) d = 1
int main()
{
    int i;
    ABC(i);
    return 0;
}
```

**Comment by hokein** [comment]
assigning to @usx95 who is working on it.

**Comment by hokein** [comment]
I believe this feature is finished.

**Comment by dfszb** [comment]
Just checked with clangd from clang 10.
This is fixed partially, with macros referencing macros not included in references list:
```
#define A(x) ++x
#define B(x) A(x)
int main()
{
    int x = 0;
    A(x);
    B(x);
}
```
clangd will find only one reference for macro A, while ccls (and rtags) will find #define B(x) A(x) as a reference, too.
I think this issue may need reopening.

**Comment by HighCommander4** [comment]
@dfszb I would suggest filing a new issue for this case.
