### ISSUE TITLE
Include Cleaner reports for unused concept headers.

### ISSUE THREAD

**Issue by aikawayataro** [clangd/clangd#1812]
With Include Cleaner (`UnusedIncludes: Strict`) the header is marked as unused by ClangD when using nothing but concepts from this header.

```cpp
#include <concepts> // Marked as unused

// Constrained function template
template<std::integral T>
T square1(T n) {
	return n * n;
}

// requires 1
template<typename T>
T square2(T n) requires std::integral<T> {
	return n * n;
}

// requires 2
template<typename T>
requires std::integral<T>
T square3(T n) {
	return n * n;
}

// Constrained function template with deduced class type
auto square4(std::integral auto n) {
	return n * n;
}

int main() {
	return square1(5) + square2(5) + square3(5) + square4(5);
}
```

**System information**

clangd version 17.0.2
Features: windows
Platform: x86_64-w64-windows-gnu

Operating system: Windows 10

**Comment by i-ky** [comment]
Duplicates #1553 and, transitively, https://github.com/llvm/llvm-project/issues/60702.

**Comment by aikawayataro** [comment]
> Duplicates #1553 and, transitively, [llvm/llvm-project#60702](https://github.com/llvm/llvm-project/issues/60702).

Couldn't find it via search, closing as duplicate.
