### ISSUE TITLE
customize hueristics for `textDocument/switchSourceHeader` ?

### ISSUE THREAD

**Issue by mellery451** [clangd/clangd#182]
I'm not sure exactly what heuristic `clangd` uses to locate header/source file pairs for the purpose of `textDocument/switchSourceHeader` requests, but it seems like it generally doesn't find the corresponding files when they are separated by one or more subdirectories. For example, if you have a header file in `src/component` and the implementation in `src/component/impl`, then `clangd` doesn't find it.

Is there any way to hint or suggest possible relative search paths when trying to locate corresponding source/header files? In the case of header-->source mapping, there might be a solution that would just search the entire compile database (if using one) for the matching source name, but that only works in one direction.

**Comment by hokein** [comment]
The heuristic used by clangd (up to v9) is very naive -- we just look for the corresponding .h/.cc file in the same directory, so it doesn't work for your case.

Good news is that recently we have built a smarter header-source-swich based on the index, it is designed for cases like yours. It will be available in next LLVM release v10.

**Comment by mellery451** [comment]
thanks for the clarification - looking forward to v10.
