### ISSUE TITLE
GotoReferences in `label:` and highlight not accessed variable

### ISSUE THREAD

**Issue by Freed-Wu** [clangd/clangd#1829]
![screen-2023-11-17-15-14-47](https://github.com/clangd/clangd/assets/32936898/e1e3ef5c-b3a4-4d4d-a42f-07e1592b043e)

Press `GotoDefinition` in `label`, I can jump to `label: XXX`. 

But press `GotoReferences` in `label:`, I cannot jump to `goto label`.

It is a missing feautre?

And if a label is not used in any `goto` or `switch`, Can clangd highlight as a not accessed variable?

![screen-2023-11-17-15-17-53](https://github.com/clangd/clangd/assets/32936898/2a55baa6-398f-4da0-8334-38c62109611e)

**Comment by HighCommander4** [comment]
> But press `GotoReferences` in `label:`, I cannot jump to `goto label`.
> 
> It is a missing feautre?

This was actually implemented recently in https://reviews.llvm.org/D150124. It will be in clangd 18.

> And if a label is not used in any `goto` or `switch`, Can clangd highlight as a not accessed variable?

Try adding [-Wunused-label](https://clang.llvm.org/docs/DiagnosticsReference.html#wunused-label) to your compile flags.

**Comment by Freed-Wu** [comment]
> It will be in clangd 18.

Thanks, I wait new version of clangd :smile:
