### ISSUE TITLE
Emacs eglot has improved its clangd support, maybe update https://clang.llvm.org/extra/clangd/Installation.html#editor-plugins

### ISSUE THREAD

**Issue by joaotavora** [clangd/clangd#183]
Hi,

First, thanks for suggesting Eglot in the documentation.  I'm Eglot's author, read your guide, and took some hints from it.   I've tried to address some of the issues you mention [there](https://clang.llvm.org/extra/clangd/Installation.html#editor-plugins).  So, in Eglot version 1.5:

* `company-clang` will no longer interfere, by default;
* Some fuzzy completion support is available (at least a "best effort", based on the `filterText` cookie);
* Completions _should_ be sorted (at least according to what the clangd server sends);

I wonder if you can test it and report back if the issues still persist. If they don't, then I think I can make `clangd` the default choice for C/C++ so you can simplify your suggested configuration a bit.

Also any other feedback is appreciated.

Thanks,
João

**Comment by joaotavora** [comment]
I just realized I could/should have opened this issue in https://github.com/clangd/clangd.github.io/
Maybe even a PR.

Let me know if that's the case...

**Comment by kadircet** [comment]
Hi @joaotavora thanks for reaching out. I wanted to give it a try and check the state of the code-completion, but in the meantime noticed some problematic behavior regarding codeActions(quick fixes to be precise). You should be able to repro with:
```
namespace a { void bar(); }
void foo() {
bar(); // you should have a diag here saying convert bar to a::bar, apply it.
}
```
After applying the fix, eglot sends a textDocument/didChange event with length "3"(i presume, insertion length of "a::") but with the text "a::bar", which doesn't match the length included in the range. Therefore clangd throws the file away, resulting in any consecutive actions in the file to be ignored until "textDocument/didOpen" is performed again.

I suppose it is related to https://github.com/joaotavora/eglot/issues/259.


And regarding completions I tried a few simple cases things seemed to be working, but when I wanted to try some real world examples, things started to break again. I didn't have time to produce a small reproducer this time, but I hope images should be self explanatory:
![image](https://user-images.githubusercontent.com/897555/67188105-f97b9200-f3eb-11e9-83f5-7f0cc31d6cc4.png)
As can be seen I've got the `CodeCompleteOptions` as a candidate here.

But it disappears as soon as I start typing, even if it is an exact prefix:
![image](https://user-images.githubusercontent.com/897555/67188156-09937180-f3ec-11e9-97be-015bece02cb3.png)

Clangd logs still shows that it has been returned as a result:
```
V[10:19:36.615] >>>
{
    "id": 186,
    "jsonrpc": "2.0",
    "result": {
        "isIncomplete": false,
        "items": [{
                    "additionalTextEdits": [{
                        "newText": "#include \"CodeComplete.h\"\n",
                        "range": {
                            "end": {
                                "character": 0,
                                "line": 9
                            },
                            "start": {
                                "character": 0,
                                "line": 9
                            }
                        }
                    }],
                    "detail": "\n\"CodeComplete.h\"",
                    "filterText": "CodeCompleteOptions",
                    "insertText": "CodeCompleteOptions",
                    "insertTextFormat": 2,
                    "kind": 7,
                    "label": "•CodeCompleteOptions",
                    "sortText": "3e669b92CodeCompleteOptions",
                    "textEdit": {
                        "newText": "CodeCompleteOptions",
                        "range": {
                            "end": {
                                "character": 34,
                                "line": 46
                            },
                            "start": {
                                "character": 15,
                                "line": 46
                            }
                        }
                    }
                }
```
btw, it has many more completion items suggested by clangd, but none of them are shown. I've truncated the output to just this one.

**Comment by joaotavora** [comment]
Thanks @kadircet , for the bug reports.  I will analyse them.

Your "real world" case is you hacking on the clangd source right?  Do you think I can reproduce it just by cloning this repo and issuing a argless `clangd` on it?

**Comment by kadircet** [comment]
Yes that should be possible, the file I was fiddling with was https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/ClangdLSPServer.cpp.

To get the exact same behavior you might want to wait for background-indexing to be complete, but there were definitely other results from non-index part of clangd that are not showing up.

**Comment by joaotavora** [comment]
> Yes that should be possible, 

Unfortunately, it isn't.  I need a compilation database, I think. And to do that, I need to be able to compile something.  (just clangd? probably the whole llvm thing, right?).

Unless you pass me your `compile-commands.json`, maybe that will work.

**Comment by joaotavora** [comment]
In the meantime, I will be looking at the issue for which you handed me the no-dependencies repro recipe.

**Comment by kadircet** [comment]
> > Yes that should be possible,
> 
> Unfortunately, it isn't. I need a compilation database, I think. And to do that, I need to be able to compile something. (just clangd? probably the whole llvm thing, right?).

ahh right.

> Unless you pass me your `compile-commands.json`, maybe that will work.
unfortunately it is not portable since it contains some absolute paths(and unless you want to modify them by hand)

but creating of a compile_commands.json should be fairly simple.

```
cd $LLVM_ROOT
mkdir build
cd build
cmake -G Ninja ../llvm/ -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
ln -sf build/compile_commands.json ../compile_commands.json
```

just running the above commands should generate a compilation database in build directory, and link it back to source root so that clangd can find it.

**Comment by joaotavora** [comment]
The cmake step gives me 
```
cmake -G Ninja ../llvm/ -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"                                                                                    master ◼
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/z/Source/Cpp/llvm-project/build/CMakeFiles/CMakeOutput.log".
```

I don't know enough Cmake to understand what this is about.

**Comment by joaotavora** [comment]
I cloned the whole llvm-project repo, btw.  Or, I shallow-cloned it, otherwise I would still be here waiting for it to download.

**Comment by kadircet** [comment]
you can drop the `-G Ninja` part and try setting the env variables for CC and CXX, i.e:

```
CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ../llvm/ -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
```

and also make sure you have clang and clang++ at the paths I mentioned or modify them accordingly. (or you can change them to gcc and g++ if you don't have clang)

**Comment by joaotavora** [comment]
I got the `-G Ninja` working and got a nice `compile_commands.json` in the process. Quite a large one too. But now `clangd` crashes! Here is the backtrace:

```
I[13:22:52.405] clangd version 9.0.0 (https://github.com/msys2/MINGW-packages.git fdafa4d8c4022588676c8ec0985dafaf834258ae)
I[13:22:52.406] Working directory: z:\Source\Cpp\llvm-project
I[13:22:52.406] argv[0]: z:\Vendor\msys2\mingw64\bin\clangd.exe
I[13:22:52.406] Starting LSP over stdin/stdout
I[13:22:52.407] <-- initialize(1)
I[13:22:52.408] --> reply:initialize(1) 0 ms
I[13:22:52.409] <-- initialized
I[13:22:52.409] unhandled notification initialized
I[13:22:52.434] <-- textDocument/didOpen
I[13:22:52.453] <-- workspace/didChangeConfiguration
I[13:22:52.493] Enqueueing 4075 commands for indexing
I[13:22:52.494] Updating file z:\Source\Cpp\llvm-project\clang-tools-extra\clangd\ClangdLSPServer.cpp with command 
[Z:/Source/Cpp/llvm-project/build]
Z:vendormsys2mingw64binc++.exe --driver-mode=g++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/extra/clangd -IZ:/Source/Cpp/llvm-project/clang-tools-extra/clangd -IZ:/Source/Cpp/llvm-project/clang/include -Itools/clang/include -Iinclude -IZ:/Source/Cpp/llvm-project/llvm/include -Wa,-mbig-obj -Werror=date-time -std=gnu++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fno-common -Woverloaded-virtual -fno-strict-aliasing -O2 -UNDEBUG -fno-exceptions -fno-rtti -o toolsclangtoolsextraclangdCMakeFilesobj.clangDaemon.dirClangdLSPServer.cpp.obj -c Z:SourceCppllvm-projectclang-tools-extraclangdClangdLSPServer.cpp -fsyntax-only -resource-dir=z:\Vendor\msys2\mingw64\lib\clang\9.0.0
 #0 0x0000000001cd8020 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x18d8020)
 #1 0x0000000001d0f1d2 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x190f1d2)
 #2 0x0000000001d13a06 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x1913a06)
 #3 0x0000000001d180ad (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x19180ad)
 #4 0x0000000001d18e8d (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x1918e8d)
 #5 0x0000000001ce262c (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x18e262c)
 #6 0x0000000001d4711f (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x194711f)
 #7 0x000000000195e78f (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x155e78f)
 #8 0x0000000000948a89 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x548a89)
 #9 0x0000000000984696 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x584696)
#10 0x0000000000762760 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x362760)
#11 0x000000000082c3a2 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x42c3a2)
#12 0x0000000000826b58 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x426b58)
#13 0x0000000000810794 (z:\Vendor\msys2\mingw64\bin\clangd.exe+0x41
Process EGLOT (llvm-project/c++-mode) stderr finished
```

Perhaps if has something to do with the fact that I'm no MINGW64 and `compile_commands.json` contains paths with windows-style backlashes.  Though they are escaped, maybe this is confusing my version of `clangd` for some reason. 

I had this suspicion from reading "Z:vendormsys2mingw64binc++.exe" in the stderr output.

**Comment by joaotavora** [comment]
Hi @kadircet,

I believe I have fixed the two issues you reported here.  Can you confirm? (you'll need a git clone of Eglot, if you aren't using one already).

**Comment by joaotavora** [comment]
Friendly ping? The Eglot version that fixes these problems is now released.

**Comment by kadircet** [comment]
Hi @joaotavora, I am waiting for our internal Eglot version to be updated, will get back to you as soon as it happens.

**Comment by joaotavora** [comment]
kadir çetinkaya <notifications@github.com> writes:

> Hi @joaotavora, I am waiting for our internal Eglot version to be
> updated, will get back to you as soon as it happens.

OK, no worries, and thanks. João

**Comment by joaotavora** [comment]
Ping? I just pushed a new version of Eglot (and the problems reported in that page seem to be long gone, I think).  Let me know if you prefer a pull request.  Thanks.

**Comment by joaotavora** [comment]
I don't think I'm getting though here, so I've opened a pull request at https://github.com/llvm/clangd-www/pull/1
