### ISSUE TITLE
Regression with "IWYU pragma: keep" in headers

### ISSUE THREAD

**Issue by stk-ableton** [clangd/clangd#1843]
We have a convention to split implementations of inline functions into their own header files; this file is then included at the end of the header that has the declarations, so that clients don't have to know about this. This include at the end of the main header is marked with `// IWYU pragma: keep` to stop clangd from flagging it as unused.

This used to work with clangd 16, but has stopped working with clangd 17. It now reports the include of the impl header as unused even though it is marked with `// IWYU pragma: keep`.

Reproduction:
```
foo.hpp:
#pragma once

template <typename T> void someFunction();

#include "foo-impl.hpp" // IWYU pragma: keep

---

foo-impl.hpp:
#pragma once

template <typename T> void someFunction() {
  // do some work
}

---
main.cpp:
#include "foo.hpp"

int main(void) {
  someFunction<int>();
  return 0;
}
```

<img width="981" alt="image" src="https://github.com/clangd/clangd/assets/7702697/67dd8fe2-b0bf-4b8d-808e-faf9cd052dcc">

**Log**

[clangd-log.txt](https://github.com/clangd/clangd/files/13501486/clangd-log.txt)

**System information**

Output of `clangd --version`:
```
clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
Features: mac+grpc+xpc
Platform: arm64-apple-darwin23.1.0; target=x86_64-apple-darwin23.1.0
```
Editor/LSP plugin: VS Code 1.85.0-insider (Universal), Commit: 2e721b6ec7

Operating system: MacOS 14.1.1

**Comment by stk-ableton** [comment]
@sam-mccall @kirillbobyrev @kadircet Friendly ping. Any thoughts on this? Since there don't seem to be any workarounds (as far as I can tell, at least), this is a bit of a showstopper as it prevents us from upgrading to 17.

**Comment by kirillbobyrev** [comment]
This looks like a regression for sure, I just checked with clangd 17.0.3 and latest snapshot (https://github.com/clangd/clangd/releases/tag/snapshot_20231210) on my MacBook and got the same results. Looks like `// IWYU pragma: keep` should work in this case, but it doesn't even close to HEAD.

I haven't touched the code for quite a while and I know that it's been reworked significantly; Sam and Kadir would definitely know better.

P.S. I think the implementation headers would need `// IWYU pragma: private, include "public.hpp"` but that's unrelated to this issue.

**Comment by kirillbobyrev** [comment]
Oh, interesting, thanks for looking into that!

@stk-ableton if you control the source code, then moving includes to preamble would solve the issue I think?

**Comment by stk-ableton** [comment]
> @stk-ableton if you control the source code, then moving includes to preamble would solve the issue I think?

I do control the source code, but that's not possible in our case, the implementations must be included after the declarations.

**Comment by kadircet** [comment]
hi sorry for the regression here @stk-ableton.

this is embarrassing that it went in :/ unfortunately you're right, I am afraid there's no easy work-around in your case.
i've implemented the functionality in https://github.com/llvm/llvm-project/pull/75612.

I am afraid there won't be any more point releases for 17, but 18 is going to be cut soon, https://github.com/llvm/llvm-project/pull/75612.

**Comment by stk-ableton** [comment]
Thanks for the fix!

> I am afraid there won't be any more point releases for 17, 

That's fine, as long as it's available in a snapshot I'm happy.
