### ISSUE TITLE
clangd crashes with Illegal instruction: 4

### ISSUE THREAD

**Issue by AnakinMac** [clangd/clangd#186]
I'm using latest LLVM git and built with XCode 10.1.

Here's the crash log.

Process:               clangd [58109]
Path:                  /Volumes/VOLUME/*/clangd
Identifier:            clangd
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           clangd [58109]
User ID:               11096

Date/Time:             2019-10-24 09:43:54.826 -0400
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Anonymous UUID:        EA2B3CA8-1749-1263-9AD8-47A4D9377A07

Time Awake Since Boot: 510000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  clangd.main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   clangd [58109]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: clangd.main  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6738f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6744e56e _pthread_cond_wait + 722
2   libc++.1.dylib                	0x00007fff64489a0a std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   clangd                        	0x0000000105c0c415 clang::clangd::wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::condition_variable&, clang::clangd::Deadline) + 117 (Threading.cpp:112)
4   clangd                        	0x0000000105c0be36 bool clang::clangd::wait<clang::clangd::AsyncTaskRunner::wait(clang::clangd::Deadline) const::$_3>(std::__1::unique_lock<std::__1::mutex>&, std::__1::condition_variable&, clang::clangd::Deadline, clang::clangd::AsyncTaskRunner::wait(clang::clangd::Deadline) const::$_3) + 118 (Threading.h:94)
5   clangd                        	0x0000000105c0bd70 clang::clangd::AsyncTaskRunner::wait(clang::clangd::Deadline) const + 144 (Threading.cpp:66)
6   clangd                        	0x0000000105c17660 clang::clangd::AsyncTaskRunner::wait() const + 48 (Threading.h:110)
7   clangd                        	0x0000000105c1728c clang::clangd::TUScheduler::~TUScheduler() + 220 (TUScheduler.cpp:956)
8   clangd                        	0x0000000105c176c5 clang::clangd::TUScheduler::~TUScheduler() + 21 (TUScheduler.cpp:956)
9   clangd                        	0x000000010583c9e1 clang::clangd::ClangdServer::~ClangdServer() + 49 (ClangdServer.h:78)
10  clangd                        	0x000000010583c9a5 clang::clangd::ClangdServer::~ClangdServer() + 21 (ClangdServer.h:78)
11  clangd                        	0x000000010583c97d llvm::optional_detail::OptionalStorage<clang::clangd::ClangdServer, false>::reset() + 45 (Optional.h:66)
12  clangd                        	0x0000000105810ab5 llvm::Optional<clang::clangd::ClangdServer>::reset() + 21 (Optional.h:251)
13  clangd                        	0x00000001058107e1 clang::clangd::ClangdLSPServer::~ClangdLSPServer() + 273 (ClangdLSPServer.cpp:1238)
14  clangd                        	0x0000000105810b85 clang::clangd::ClangdLSPServer::~ClangdLSPServer() + 21 (ClangdLSPServer.cpp:1238)
15  clangd                        	0x000000010570eab7 main + 13207 (ClangdMain.cpp:694)
16  libdyld.dylib                 	0x00007fff672573d5 start + 1

Another one:

Process:               clangd [58038]
Path:                  /Volumes/VOLUME/*/clangd
Identifier:            clangd
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Code Helper [57818]
Responsible:           clangd [58038]
User ID:               11096

Date/Time:             2019-10-24 09:41:46.727 -0400
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Anonymous UUID:        EA2B3CA8-1749-1263-9AD8-47A4D9377A07

Time Awake Since Boot: 510000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  clangd.main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   clangd [58038]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: clangd.main  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6738d1be __read_nocancel + 10
1   libsystem_c.dylib             	0x00007fff672e2e2b _sread + 16
2   libsystem_c.dylib             	0x00007fff672e24a3 __srefill1 + 24
3   libsystem_c.dylib             	0x00007fff672dbf4f fgets + 98
4   clangd                        	0x0000000103374ea1 decltype(fp0(fp1...)) llvm::sys::RetryAfterSignal<std::nullptr_t, char* (char*, int, __sFILE*), char*, int, __sFILE*>(std::nullptr_t const&, char*  const(&)(char*, int, __sFILE*), char* const&, int const&, __sFILE* const&) + 65 (Errno.h:38)
5   clangd                        	0x0000000103374a0b clang::clangd::(anonymous namespace)::readLine(__sFILE*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 859 (JSONTransport.cpp:178)
6   clangd                        	0x0000000103374004 clang::clangd::(anonymous namespace)::JSONTransport::readStandardMessage() + 404 (JSONTransport.cpp:201)
7   clangd                        	0x00000001033730d8 clang::clangd::(anonymous namespace)::JSONTransport::readRawMessage() + 72 (JSONTransport.cpp:118)
8   clangd                        	0x000000010337110c clang::clangd::(anonymous namespace)::JSONTransport::loop(clang::clangd::Transport::MessageHandler&) + 300
9   clangd                        	0x00000001030f5c2a clang::clangd::ClangdLSPServer::run() + 106 (ClangdLSPServer.cpp:1243)
10  clangd                        	0x0000000102ff3a4a main + 13098 (ClangdMain.cpp:674)
11  libdyld.dylib                 	0x00007fff672573d5 start + 1

**Comment by canatella** [comment]
Just to let you know, I had the same problem but I think may clangd was compiled with a previous xcode version (minor version I think). I installed the latest LLVM from homebrew and it seems ok now...

**Comment by kadircet** [comment]
closing as there's no actionable info here.

we need a reproducer/core dump that we can look at, stack traces aren't actionable on its own in this case unfortunately.
