### ISSUE TITLE
Eclipse indexer unable to find std or the first C++ include in files

### ISSUE THREAD

**Issue by mbratch** [clangd/clangd#1865]
I am running Eclipse version 2023-09 (4.29.0) and have the Espressif ESP-IDF plugin version 2.11.1.202310270725 installed.

I installed the clangd indexer and disabled the default indexer per the instructions at [this link](https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/clangd_cdt_support.md). The installation of the clangd indexer went smoothly, but to get it to take effect, I had to delete my project and re-import it.

My first problem with the indexer is that it seems to have trouble finding standard C++ headers. It says "Use of undeclared identifier 'std'" when I reference an `std` library method.

![287558749-19127799-47f2-4690-b5d0-2abd93f71989](https://github.com/espressif/idf-eclipse-plugin/assets/7990964/d8565a98-214d-4b1a-8f3b-2b47d4ec7851)

It also claims it can't find the string header file as indicated below. I noticed that this happens with the first #include in the file. So if I first #include <memory> then #include <string> it will indicate memory cannot be found but it finds string. Weird.

![287558830-9ceb44a1-2fec-41ac-9ecd-08874bcbc5c4](https://github.com/espressif/idf-eclipse-plugin/assets/7990964/db59dae3-e3c1-4001-b6bf-0f205d0d7695)

FInally, I also don't see any context menu commands for "Open declaration". The other indexer supported it. Is that feature unavailable with the clangd indexer?

I've attached the Eclipse log.
[eclipse.log](https://github.com/espressif/idf-eclipse-plugin/files/13553752/eclipse.log)

**Comment by HighCommander4** [comment]
> I noticed that this happens with the first #include in the file. So if I first #include then #include it will indicate memory cannot be found but it finds string. Weird.

Note, the lack of diagnostics about subsequent includes is a symptom of the clang parser giving up after failing to resolve the first include; it doesn't even try resolving subsequent ones.

> I've attached the Eclipse log. [eclipse.log](https://github.com/espressif/idf-eclipse-plugin/files/13553752/eclipse.log)

We'll need clangd logs to diagnose the issue. Maybe @ghentschke can advise how to get those for this editor.

However, the most common solution for this type of issue is to specify `--query-driver` in clangd's arguments as discussed in the last paragraph of https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc.

**Comment by ghentschke** [comment]
As @HighCommander4 already mentioned is the problem that clangd cannot determine the path to standard library.  I think there has been major improvements in cangd version >16 on determining the system includes. The cdt-lsp plugin already uses the  
`--query-driver` command: 
![image](https://github.com/clangd/clangd/assets/123444711/efed0078-56df-456f-aaa9-106d40a459fd)
Please check if this query driver entry  `<yourPath>/bin/*` fixes this issues, because now the query is limited to a certain compiler (when you've followed the instruction [here](https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/clangd_cdt_support.md))

You can enable the Language Server Logging in the Eclispe Preferences here:
![image](https://github.com/clangd/clangd/assets/123444711/4d182c38-c7be-462c-8477-372a69ed2938)

**Comment by mbratch** [comment]
Thank you @ghentschke. I think this highlights the issue.

The tools folder structure for the ESP32 ESP-IDF SDK I'm using is a bit peculiar. This is what I have configured for the Editor (LSP):
![image](https://github.com/clangd/clangd/assets/7990964/3776c844-e6f9-425a-b4b8-03b09c634675)

Here is the context of the directory structure where the tools are. The `include` folder that corresponds to the `bin` folder holding the compiler, shown as item #1, is empty (!). There's another subfolder that has a `bin` and corresponding `include` folder (item #2). This `bin` does not have the compiler, but the corresponding `include` for that `bin` is where all the standard include files appear to be. I'm not sure how the Eclipse compiler is picking them up (since the code compiles). I'll need to look around the configuration to see how that's done.
![image](https://github.com/clangd/clangd/assets/7990964/ed41b5c5-4c2a-433a-a42b-c625b1c9f97c)

**Comment by ghentschke** [comment]
This [CDT fix](https://github.com/eclipse-cdt/cdt/pull/648) might be helpfull, since it fixes a bug for cc.exe on Windows.

**Comment by mbratch** [comment]
Here is my language server log:

[lang_server.log](https://github.com/clangd/clangd/files/13693111/lang_server.log)

**Comment by HighCommander4** [comment]
> Here is my language server log:
> 
> [lang_server.log](https://github.com/clangd/clangd/files/13693111/lang_server.log)

This contains the LSP traffic, but not the language server's own logs.

As discussed at https://clangd.llvm.org/troubleshooting#gathering-logs (emphasis mine):

> Your editor should make clangd’s stderr log available (see [installation](https://clangd.llvm.org/installation) for how). These describe the messages exchanged between the editor and clangd, **and what clangd was thinking**.

@ghentschke is there a way to get at clangd's full stderr output with CDT-LSP?

**Comment by mbratch** [comment]
@HighCommander4 ok sorry for the error. The configuration said "log to console" and that was everything that was printed out on the console. I'll get the correct log and attach when I get a chance.

**Comment by ghentschke** [comment]
@HighCommander4 I think this is what you looking for: 
```txt
I[08:33:54.418] clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
I[08:33:54.419] Features: windows+grpc
I[08:33:54.419] PID: 9648
I[08:33:54.419] Working directory: C:\Users\ghent\cdt-main\eclipse
I[08:33:54.419] argv[0]: C:\temp\clangd-windows-16.0.2\clangd_16.0.2\bin\clangd.exe
I[08:33:54.419] argv[1]: --clang-tidy
I[08:33:54.419] argv[2]: --background-index
I[08:33:54.419] argv[3]: --completion-style=detailed
I[08:33:54.419] argv[4]: --pretty
I[08:33:54.419] argv[5]: --query-driver=C:/Daten/msys64/mingw64/bin/*
I[08:33:54.425] Starting LSP over stdin/stdout
I[08:33:54.475] <-- initialize("1")
I[08:33:54.483] --> reply:initialize("1") 8 ms
I[08:33:54.498] <-- initialized
I[08:33:54.508] <-- textDocument/didOpen
I[08:33:54.622] System includes extractor: successfully executed C:\Daten\msys64\mingw64\bin\clang.exe
	got includes: "C:/Daten/msys64/mingw64/include/c++/11.2.0, C:/Daten/msys64/mingw64/include/c++/11.2.0/x86_64-w64-mingw32, C:/Daten/msys64/mingw64/include/c++/11.2.0/backward, C:/Daten/msys64/mingw64/lib/clang/13.0.0/include, C:/Daten/msys64/mingw64/x86_64-w64-mingw32/include, C:/Daten/msys64/mingw64/include"
	got target: "x86_64-w64-windows-gnu"
```
I've to check how to print this to the Eclipse log.

**Comment by HighCommander4** [comment]
> @HighCommander4 I think this is what you looking for:

Yep, exactly! This contains information printed by clangd (such as the "System includes extractor" line) which is very useful for diagnosing issues of this sort.

Note that there is also more verbose logging which can be enabled by adding `--log=verbose` to the clangd command line, which can also be quite helpful.

**Comment by ghentschke** [comment]
@mbratch  Please run your Eclipse.exe form a  command window with the `-consolelog` argument:
```cmd
Eclipse.exe -consolelog
```
This will open a console window with the logging of the Java process. You should see the clangd log entries as shown in my post above.

**Comment by mbratch** [comment]
Hello @ghentschke I ran the console log as you suggested, attached here.

[eclipse-console-log.txt](https://github.com/clangd/clangd/files/13790639/eclipse-console-log.txt)

**Comment by HighCommander4** [comment]
> I ran the console log as you suggested, attached here.
> 
> [eclipse-console-log.txt](https://github.com/clangd/clangd/files/13790639/eclipse-console-log.txt)

Based on the log, the issue seems to be the mismatch between the `--query-driver` argument (which IIUC comes from the "Drivers" field in the "Editors (LSP)" config page), which is `C:\Users\mdbra\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe`, and the actual compiler driver from the compile command, which is `C:/Users/mdbra/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe`.

I _think_ the difference in slashes is fine, since the actual path gets normalized and on Windows the normalized path should have backslashes, and so it's only the `gcc` vs. `g++` that's an issue.

So, I would expect changing the contents of that "Drivers" field to be `C:\Users\mdbra\.espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe` should resolve the issue.

**Comment by mbratch** [comment]
Thank you @HighCommander4 , I changed the Drivers field to indicate g++ as you noted, but I am still getting the same problem.

**Comment by HighCommander4** [comment]
> Thank you @HighCommander4, I changed the Drivers field to indicate g++ as you noted, but I am still getting the same problem. Is there anything I need to do after changing the Drivers setting to "re-evaluate"?

I think a restart of Eclipse should do it.

If that still doesn't help, could you re-take the logs with `--log=verbose` added to the "Additional" field (under "Drivers") for a more detailed look?

**Comment by HighCommander4** [comment]
> I _think_ the difference in slashes is fine, since the actual path gets normalized and on Windows the normalized path should have backslashes, and so it's only the `gcc` vs. `g++` that's an issue.

I just realized something: the [clangd patch](https://github.com/llvm/llvm-project/pull/66757) to normalize the driver path has not appeared in a release yet; it will appear in clangd 18.

So, with clangd 17 and earlier, the direction of the slashes **is** important, and so in your case you'd need to set the "Drivers" field to `C:/Users/mdbra/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe`.

**Comment by mbratch** [comment]
Thanks @HighCommander4 that all seems to have cleared up the problem!

**Comment by mbratch** [comment]
Thanks @HighCommander4 that all seems to have cleared up the problem!
