### ISSUE TITLE
_Static_assert message not showing correctly

### ISSUE THREAD

**Issue by aalmkainzi** [clangd/clangd#1866]
For some reason, the * is not showing in the `_Static_assert` error message, it shows when compiling but not when hovering over the error. Instead it just shows `"Static assertion failed: ((int), (int))"`.
Completely omitting the stars.

```C
#define ERROR(type) \
_Static_assert(0, "((" #type ")*, (" #type ")*)")

int main()
{
    ERROR(int);
}
```
**System information**

Output of `clangd --version`:
```
Ubuntu clangd version 17.0.2 (1~exp1ubuntu2.1)
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:
Kate
clangd-17

Operating system:
Kubuntu

**Comment by HighCommander4** [comment]
Could you share [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs) please?

**Comment by aalmkainzi** [comment]
I realized this is actually my editor's (Kate) fault. It attempts to make whatever between two * italic
