### ISSUE TITLE
clangd takes up too much memory

### ISSUE THREAD

**Issue by liuwd8** [clangd/clangd#1869]
I am a developer in the chromium community. When I use clangd to build the chromium index, clangd will take up too much memory until my machine freezes.

I can reproduce this problem on Macbook M1 using clangd 17.03 (clangd official version), and the memory usage exceeds 80G. clangd 16.02 (clangd official version) is normal, and the memory is about 4G.

On linux machines, it seems that clangd 17.00 (chromium community version) also has this problem.

**Comment by 5chmidti** [comment]
80G vs 4G is a big difference, https://github.com/llvm/llvm-project/issues/75105 could be the same problem you are facing if chromium uses PCH files. As a potential workaround (might still consume too much memory for locally indexed files), #1630 could be of interest to you, specifically https://github.com/clangd/clangd/issues/1630#issuecomment-1543362393.
