### ISSUE TITLE
No documentation for those defined functions

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#187]
+ clangd version: `10.0.0 (https://github.com/llvm/llvm-project.git f01b9aa89e8cd5d3cca0e13835302f69c1f879d2)`
+ OS: `win10`

1. foo.cpp
```c++
#include "foo.h"

void foo() {}
```
2. foo.h
```c++
#ifndef FOO_H
#define FOO_H

// foo is defined
void foo();

// bar only have declaration
void bar();

#endif
```
3. main.cpp
```c++
#include "foo.h"

int main() {
    foo();
    bar();
}
```
4. compile_commands.json
```
[
    {
        "directory": "F:/VSCode/tt",
        "command": "g++ -Wall -o F:/VSCode/tt/main.cpp.obj F:/VSCode/tt/main.cpp",
        "file": "F:/VSCode/tt/main.cpp"
    },
    {
        "directory": "F:/VSCode/tt",
        "command": "g++ -Wall -o F:/VSCode/tt/foo.cpp.obj F:/VSCode/tt/foo.cpp",
        "file": "F:/VSCode/tt/foo.cpp"
    }
]
```
4. Open `main.cpp` after opening `foo.cpp`
![image](https://user-images.githubusercontent.com/10697249/68268699-428d4080-0092-11ea-882e-d79d60ce2831.png)
![image](https://user-images.githubusercontent.com/10697249/68268711-4a4ce500-0092-11ea-96c9-3be823cb53c9.png)

5. the older version `clangd version 10.0.0 (https://github.com/llvm/llvm-project.git 8d6a863b02f199960590973f06b4c4dd29df578f)` works fine.

**Comment by lh123** [comment]
https://reviews.llvm.org/D68467

**Comment by hokein** [comment]
I believe this is a regression, we should still show documentations for these functions, fixed in https://github.com/llvm/llvm-project/commit/41104a9406dd284d984f7bee30c7756fcfe2b59e.
