### ISSUE TITLE
Clangd crash in Namer::VisitCXXMemberCallExpr() in InlayHints.cpp

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#1873]
I'm getting a crash in [this function](https://searchfox.org/llvm/rev/701f64790520790f75b1f948a752472d421ddaa3/clang-tools-extra/clangd/InlayHints.cpp#287-296).

I don't have a reduced test case at the moment, but just eyeballing the function, it's unconditionally dereferencing `E->getMethodDecl()` and `E->getImplicitObjectArgument()`, and either of those could potentially be null.

This is a regression from https://reviews.llvm.org/D155421 which introduced this code.

cc @sam-mccall, @hokein

**Comment by hokein** [comment]
Thanks. I think your analysis is right:
- it is unlikely that the parameter `E` of `VisitCXXMemberCallExpr` will be null
- E->getMethodDecl() could probably return nullptr (for invalid code)

We should make a sanity check for the `E->getMethodDecl()` there, it would be great to have a reproduced testcase, but if it is too hard, I think it is fine.

**Comment by HighCommander4** [comment]
Reduced testcase:

```c++
class A {};

using Predicate = bool(A::*)();
bool AnyApzc(A* a, Predicate p) {
  if ((a->*p)()) {
  }
}
```

**Comment by HighCommander4** [comment]
When the call is through a pointer to a member, `CXXMemberCallExpr::getCallee()` is (after unwrapping parens) a `BinaryOperator` (with the operator being `->*`).

`getMethodDecl()` only returns non-null if the callee is a `MemberExpr`.

**Comment by HighCommander4** [comment]
Proposed fix: https://github.com/llvm/llvm-project/pull/76492
