### ISSUE TITLE
Clangd crashes when indexing a large project

### ISSUE THREAD

**Issue by res0nance** [clangd/clangd#1874]
Clangd crashes when indexing a large project

The project internally uses gcc as its compiler unsure if relevant.

**Logs**

```
#0 0x00000000004f367b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /__w/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:602:13
 #1 0x00000000004f167c llvm::sys::RunSignalHandlers() /__w/clangd/clangd/llvm-project/llvm/lib/Support/Signals.cpp:105:18
 #2 0x00000000004f3fe6 SignalHandler(int) /__w/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007fa013c75420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x000000000081d471 clang::TemplateArgument::isPackExpansion() const /__w/clangd/clangd/llvm-project/clang/lib/AST/TemplateBase.cpp:249:3
 #5 0x0000000000be3fe3 getPackSubstitutedTemplateArgument /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp:1554:7
 #6 0x0000000000be3fe3 (anonymous namespace)::TemplateInstantiator::TransformTemplateTypeParmType(clang::TypeLocBuilder&, clang::TemplateTypeParmTypeLoc, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp:2226:13
 #7 0x0000000000bbf126 isNull /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/PointerUnion.h:142:33
 #8 0x0000000000bbf126 isNull /__w/clangd/clangd/llvm-project/clang/include/clang/AST/Type.h:804:31
 #9 0x0000000000bbf126 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformType(clang::TypeSourceInfo*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/TreeTransform.h:4871:14
#10 0x0000000000bdb4f7 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateArgument(clang::TemplateArgumentLoc const&, clang::TemplateArgumentLoc&, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/TreeTransform.h:4600:10
#11 0x0000000000bc9c47 bool clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformTemplateArguments<clang::TemplateArgumentLoc const*>(clang::TemplateArgumentLoc const*, clang::TemplateArgumentLoc const*, clang::TemplateArgumentListInfo&, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/TreeTransform.h:4792:13
#12 0x0000000000bd37bf TransformTemplateArguments /__w/clangd/clangd/llvm-project/clang/lib/Sema/TreeTransform.h:622:12
#13 0x0000000000bd37bf clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformConceptSpecializationExpr(clang::ConceptSpecializationExpr*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/TreeTransform.h:12866:20
#14 0x0000000000bcbba1 clang::Sema::SubstConstraintExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaTemplateInstantiate.cpp:4057:23
#15 0x0000000000d424ab SubstituteConstraintExpression(clang::Sema&, clang::NamedDecl const*, clang::Expr const*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaConcept.cpp:790:33
#16 0x0000000000d422c7 clang::Sema::AreConstraintExpressionsEqual(clang::NamedDecl const*, clang::Expr const*, clang::NamedDecl const*, clang::Expr const*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaConcept.cpp:809:21
#17 0x0000000000ad7963 MatchTemplateParameterKind(clang::Sema&, clang::NamedDecl*, clang::NamedDecl const*, clang::NamedDecl*, clang::NamedDecl const*, bool, clang::Sema::TemplateParameterListEqualKind, clang::SourceLocation) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaTemplate.cpp:8144:11
#18 0x0000000000ad706c clang::Sema::TemplateParameterListsAreEqual(clang::NamedDecl const*, clang::TemplateParameterList*, clang::NamedDecl const*, clang::TemplateParameterList*, bool, clang::Sema::TemplateParameterListEqualKind, clang::SourceLocation) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaTemplate.cpp:8234:12
#19 0x0000000000a73ec7 clang::Sema::IsOverload(clang::FunctionDecl*, clang::FunctionDecl*, bool, bool, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaOverload.cpp:1300:38
#20 0x0000000000a738ff clang::Sema::CheckOverload(clang::Scope*, clang::FunctionDecl*, clang::LookupResult const&, clang::NamedDecl*&, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaOverload.cpp:1158:11
#21 0x0000000000da49a0 clang::Sema::CheckFunctionDeclaration(clang::Scope*, clang::FunctionDecl*, clang::LookupResult&, bool, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaDecl.cpp:11729:7
#22 0x0000000000d9820e setRedeclaration /__w/clangd/clangd/llvm-project/clang/include/clang/Sema/DeclSpec.h:2680:51
#23 0x0000000000d9820e clang::Sema::ActOnFunctionDeclarator(clang::Scope*, clang::Declarator&, clang::DeclContext*, clang::TypeSourceInfo*, clang::LookupResult&, llvm::MutableArrayRef<clang::TemplateParameterList*>, bool&) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaDecl.cpp:10451:11
#24 0x0000000000d93903 clang::Sema::HandleDeclarator(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaDecl.cpp:0:0
#25 0x0000000000db45c2 clang::Sema::ActOnStartOfFunctionDef(clang::Scope*, clang::Declarator&, llvm::MutableArrayRef<clang::TemplateParameterList*>, clang::Sema::SkipBodyInfo*, clang::Sema::FnBodyKind) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaDecl.cpp:15039:15
#26 0x00000000020d82e0 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/Parser.cpp:1395:23
#27 0x000000000219d06e clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#28 0x000000000219b23a clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#29 0x000000000219ac0b clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#30 0x00000000020eef54 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:0:0
#31 0x00000000020d52fa clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/Parser.cpp:0:3
#32 0x000000000210c71b ~AttributePool /__w/clangd/clangd/llvm-project/clang/include/clang/Sema/ParsedAttr.h:704:22
#33 0x000000000210c71b ~ParsedAttributes /__w/clangd/clangd/llvm-project/clang/include/clang/Sema/ParsedAttr.h:920:7
#34 0x000000000210c71b clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:263:5
#35 0x000000000210c81b Exit /__w/clangd/clangd/llvm-project/clang/include/clang/Parse/Parser.h:1142:11
#36 0x000000000210c81b clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:286:18
#37 0x000000000210c109 Exit /__w/clangd/clangd/llvm-project/clang/include/clang/Parse/Parser.h:1142:11
#38 0x000000000210c109 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDeclCXX.cpp:242:18
#39 0x00000000020ef0d0 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:0:0
#40 0x00000000020d52fa clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/Parser.cpp:0:3
#41 0x00000000020d3ca7 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/Parser.cpp:742:12
#42 0x00000000020cf73e clang::ParseAST(clang::Sema&, bool, bool) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseAST.cpp:162:5
#43 0x0000000001ea6cdb clang::FrontendAction::Execute() /__w/clangd/clangd/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1063:10
#44 0x00000000015a0cf3 operator bool /__w/clangd/clangd/llvm-project/llvm/include/llvm/Support/Error.h:234:21
#45 0x00000000015a0cf3 clang::clangd::BackgroundIndex::index(clang::tooling::CompileCommand) /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/index/Background.cpp:325:19
#46 0x00000000015a3e62 _M_data /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:176:28
#47 0x00000000015a3e62 _M_is_local /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:211:16
#48 0x00000000015a3e62 _M_dispose /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:220:7
#49 0x00000000015a3e62 ~basic_string /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/basic_string.h:647:9
#50 0x00000000015a3e62 ~CompileCommand /__w/clangd/clangd/llvm-project/clang/include/clang/Tooling/CompilationDatabase.h:44:8
#51 0x00000000015a3e62 operator() /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/index/Background.cpp:168:22
#52 0x00000000015a3e62 std::_Function_handler<void (), clang::clangd::BackgroundIndex::indexFileTask(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::$_3>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:316:2
#53 0x00000000015a784f clang::clangd::BackgroundQueue::work(std::function<void ()>) /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/index/BackgroundQueue.cpp:44:25
#54 0x00000000015a231a ~_Function_base /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/std_function.h:275:11
#55 0x00000000015a231a operator() /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/index/Background.cpp:114:27
#56 0x00000000015a231a void llvm::detail::UniqueFunctionBase<void>::CallImpl<clang::clangd::BackgroundIndex::BackgroundIndex(clang::clangd::ThreadsafeFS const&, clang::clangd::GlobalCompilationDatabase const&, llvm::unique_function<clang::clangd::BackgroundIndexStorage* (llvm::StringRef)>, clang::clangd::BackgroundIndex::Options)::$_1>(void*) /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:220:12
#57 0x0000000001618a71 operator= /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:48:5
#58 0x0000000001618a71 PunnedPointer /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:37:60
#59 0x0000000001618a71 PointerIntPair /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:86:13
#60 0x0000000001618a71 UniqueFunctionBase /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:338:3
#61 0x0000000001618a71 unique_function /__w/clangd/clangd/llvm-project/llvm/include/llvm/ADT/FunctionExtras.h:367:3
#62 0x0000000001618a71 operator() /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:103:14
#63 0x0000000001618a71 operator()<(lambda at /w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15) &> /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:43:11
#64 0x0000000001618a71 invoke_impl<void, (lambda at /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:42:9), (lambda at /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15) &> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:60:14
#65 0x0000000001618a71 invoke<(lambda at /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:42:9), (lambda at /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15) &> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/invoke.h:95:14
#66 0x0000000001618a71 apply_impl<(lambda at /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:42:9), std::tuple<(lambda at /__w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15)> &, 0> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/tuple:1662:14
#67 0x0000000001618a71 apply<(lambda at /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:42:9), std::tuple<(lambda at /w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15)> &> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/tuple:1671:14
#68 0x0000000001618a71 GenericThreadProxy<std::tuple<(lambda at /w/clangd/clangd/llvm-project/clang-tools-extra/clangd/support/Threading.cpp:98:15)> > /w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:41:5
#69 0x0000000001618a71 void* llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::$_1> >(void*) /__w/clangd/clangd/llvm-project/llvm/include/llvm/Support/thread.h:55:5
#70 0x00007fa013c69609 start_thread /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:478:7
#71 0x00007fa013a2f353 clone /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97:0
```

**System information**

Output of `clangd --version`:

```
clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:

Vscode with clangd extension

Operating system:
Ubuntu 20.04

**Comment by HighCommander4** [comment]
Worth checking with the latest snapshot at https://github.com/clangd/clangd/releases/tag/snapshot_20231217, in case the crash has been resolved on trunk.

**Comment by jh244212647** [comment]
i use 
I[23:12:53.625] clangd version 18.0.0git (https://github.com/llvm/llvm-project d8ddcae547e782a4765783c62747381624f076d4)
I[23:12:53.625] Features: linux+grpc

meet same issue. backtrace is follow
#0 0x00000000004f603b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /__w/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x00000000004f3e7e llvm::sys::RunSignalHandlers() /__w/clangd/clangd/llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #2 0x00000000004f69c6 SignalHandler(int) /__w/clangd/clangd/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007feee7c7d730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #4 0x000000000053baa8 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const /__w/clangd/clangd/clangd_snapshot_20231224/tools/clang/include/clang/AST/TypeNodes.inc:0:0
 #5 0x000000000053c920 clang::ASTContext::getTypeInfo(clang::Type const*) const /__w/clangd/clangd/llvm-project/clang/lib/AST/ASTContext.cpp:1859:17
 #6 0x000000000053ccb3 clang::ASTContext::getTypeAlignInChars(clang::QualType) const /__w/clangd/clangd/llvm-project/clang/lib/AST/ASTContext.cpp:2425:30
 #7 0x0000000000d78d4f operator< /__w/clangd/clangd/llvm-project/clang/include/clang/AST/CharUnits.h:107:25
 #8 0x0000000000d78d4f clang::Sema::CheckArgAlignment(clang::SourceLocation, clang::NamedDecl*, llvm::StringRef, clang::QualType, clang::QualType) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaChecking.cpp:7399:16
 #9 0x0000000000d79ff8 clang::Sema::checkCall(clang::NamedDecl*, clang::FunctionProtoType const*, clang::Expr const*, llvm::ArrayRef<clang::Expr const*>, bool, clang::SourceLocation, clang::SourceRange, clang::Sema::VariadicCallType) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaChecking.cpp:7484:9
#10 0x0000000000d7b27b clang::Sema::CheckFunctionCall(clang::FunctionDecl*, clang::CallExpr*, clang::FunctionProtoType const*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaChecking.cpp:7603:3
#11 0x0000000000f6e537 clang::Sema::BuildResolvedCallExpr(clang::Expr*, clang::NamedDecl*, clang::SourceLocation, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, clang::CallExpr::ADLCallKind) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaExpr.cpp:7745:9
#12 0x0000000000afb658 FinishOverloadedCallExpr(clang::Sema&, clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, clang::OverloadCandidateSet*, clang::OverloadCandidate**, clang::OverloadingResult, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaOverload.cpp:0:0
#13 0x0000000000afacb6 clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaOverload.cpp:13998:10
#14 0x0000000000f523f2 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaExpr.cpp:7266:16
#15 0x0000000000f6cd8a clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) /__w/clangd/clangd/llvm-project/clang/lib/Sema/SemaExpr.cpp:7157:7
#16 0x00000000022ca421 clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseExpr.cpp:2152:23
#17 0x00000000022ccec1 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseExpr.cpp:1879:9
#18 0x00000000022d0af5 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseExpr.cpp:0:0
#19 0x00000000022c9081 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseExpr.cpp:693:20
#20 0x00000000022c786c clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseExpr.cpp:179:10
#21 0x0000000002296d01 ParseInitializer /__w/clangd/clangd/llvm-project/clang/include/clang/Parse/Parser.h:0:0
#22 0x0000000002296d01 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:2604:25
#23 0x000000000229478e clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:2337:21
#24 0x00000000022937ce clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:2030:10
#25 0x0000000002293332 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseDecl.cpp:0:0
#26 0x000000000233111d clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:247:16
#27 0x0000000002330824 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:118:20
#28 0x00000000023399d1 clang::Parser::ParseCompoundStatementBody(bool) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:1236:11
#29 0x00000000023313a4 ParseCompoundStatement /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:1030:10
#30 0x00000000023313a4 ParseCompoundStatement /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:995:10
#31 0x00000000023313a4 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:293:12
#32 0x0000000002330824 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:118:20
#33 0x0000000002334e50 ParseStatement /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:46:33
#34 0x0000000002334e50 clang::Parser::ParseWhileStatement(clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:1852:19
#35 0x000000000233158a clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:305:12
#36 0x0000000002330824 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:118:20
#37 0x00000000023399d1 clang::Parser::ParseCompoundStatementBody(bool) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:1236:11
#38 0x00000000023313a4 ParseCompoundStatement /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:1030:10
#39 0x00000000023313a4 ParseCompoundStatement /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:995:10
#40 0x00000000023313a4 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:293:12
#41 0x0000000002330824 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /__w/clangd/clangd/llvm-project/clang/lib/Parse/ParseStmt.cpp:118:20

**Comment by HighCommander4** [comment]
@jh244212647 that stack trace is showing a crash in a different function than the original report, so it's better to file it as a new issue

**Comment by res0nance** [comment]
I no longer get the stacktrace i see with the following snapshot https://github.com/clangd/clangd/releases/tag/snapshot_20231231

Closing this and will file a new issue if I find more issues
