### ISSUE TITLE
The clangd does not recognize file included from different include tree.

### ISSUE THREAD

**Issue by koniroman** [clangd/clangd#1875]
Hello,

I have a simple structure, with two header files header-a and header-b, both placed in different include tree.

```
/tmp/include-a/
  |- header-a

/tmp/include-b/
  |- header-b

/tmp/impl
  |- main.cpp
  |- .clangd
  |- compile_commands.json

```
I configured .clangd with two include dirs /tmp/include-a and /tmp/include-b. 

```
// .clangd
CompileFlags:
  Add: [-xc++, -I/tmp/include-a, -I/tmp/include-b]
  Remove: []
  Compiler: clang++
```

These include files are used by main.cpp. They are both properly recognized by clangd. There are no errors for these includes and I can hover over them and ctr+click to open any of them. So far so good.

```
// main.cpp
#include <header-a> // this is recognized properly (can open file when hovering over it)
#include <header-b> // this is recognized properly too
```

The header-a file includes header-b, and when I open header-a file, clangd can't recognize included header-b:

```
// header-a
#include <header-b> // "'header-b' file not found" error - not possible to open file with hovering 
```

The main.cpp compiles fine with gcc with added these two include paths:

` /usr/bin/g++ -std=c++17 -I/tmp/include-a -I/tmp/include-b  -o main.cpp.o /tmp/impl/main.cpp`

How to reproduce.
1. Extract the structure to /tmp
2. Open folder with code /tmp/impl
3. Open main.cpp -> all headers resolvable
![image](https://github.com/clangd/clangd/assets/46592685/a66cf66d-4cd6-456e-b8fe-e4a3b447014f)

5. Open header-a  -> header-b not recognized
![image](https://github.com/clangd/clangd/assets/46592685/0c5fa327-b4b7-48c0-984c-485ac3ab139b)

The whole structure for reproduction:
[tmp.zip](https://github.com/clangd/clangd/files/13758916/tmp.zip)

And the clangd log:
[clangd.log](https://github.com/clangd/clangd/files/13758921/clangd.log)

Thanks in advance!

Cheers,
Roman

**System information**

Output of `clangd --version`:
clangd version 18.0.0git (https://github.com/llvm/llvm-project c014454f43bf523fee2bf695c075882b1cefd21c)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
VSCode Version: 1.85.1

Operating system:
PopOs 22.04

**Comment by koniroman** [comment]
I found an answer in similar issue #1615.
The solution is to add these includes to user config, in my case ~/.config/clangd/config.yaml:

```
CompileFlags:
  Add: [-xc++, -I/tmp/include-a, -I/tmp/include-b]
  Remove: []
  Compiler: clang++
```

I don't know the rationale, why does it work this way, but IMO it is confusing, as the header-a is properly recognized in one file, while it is not in the other. The only difference is that the first time it is included by file sitting inside project (.cland file) hierarchy, while the other time it is outside. For gcc it is irrelevant ...
I spent the whole day solving this misery ...

**Comment by HighCommander4** [comment]
An alternative solution that I find a bit easier to work with is:

 * Make sure the `-I` flags are in the commands in `compile_commands.json` (for example, by using [Bear](https://github.com/rizsotto/Bear) to generate the `compile_commands.json` file).
 * Run clangd with the `--compile-commands-dir` option as discussed at https://clangd.llvm.org/faq#how-do-i-fix-errors-i-get-when-opening-headers-outside-of-my-project-directory.

Note that with this solution, neither `.clangd` nor `~/,config/clangd/config.yaml` is needed.

**Comment by ReinhardKeil** [comment]
@HighCommander4 thanks for your comment above. Do you know how `--compile-commands-dir` is specified in an VS Code environment. 

`clangd` seems to use the `.clangd` file that is within the directory tree of the source code or the `clangd/config.yaml` file.  This is explained here https://clangd.llvm.org/config#files

**Comment by HighCommander4** [comment]
> Do you know how `--compile-commands-dir` is specified in an VS Code environment.

In vscode settings, under `"clangd.arguments"`.

**Comment by ReinhardKeil** [comment]
Thanks @HighCommander4.  it seems to specify a `config.yaml` file (with similar content as .clangd), i.e. `--compile-commands-dir=<path>/config.yaml`. However even with this option, it failed to recognize files outside the directory tree. 

`/config/clangd/config.yaml` works, however it is system wide and not specific to a VS Code workspace.

Any hints are welcome.

**Comment by HighCommander4** [comment]
@ReinhardKeil The argument to `--compile-commands-dir` is not a path to a `config.yaml` file. Please have a look at `clangd --help` which says the following about it:

```
  --compile-commands-dir=<string>     - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file
```

**Comment by ReinhardKeil** [comment]
@HighCommander4 thanks this was very helpful!
