### ISSUE TITLE
qemu clangd error

### ISSUE THREAD

**Issue by cctv130** [clangd/clangd#1880]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
client:windows11 vscode ssh remote  server:debian12
Output of `clangd --version`:latest

Editor/LSP plugin:

Operating system:
![1703615795157](https://github.com/clangd/clangd/assets/133784576/fdda2db6-50ad-4dc4-ac46-87450991404f)
![image](https://github.com/clangd/clangd/assets/133784576/13ec9395-26a0-4c73-9192-4b29effa2988)

**Comment by HighCommander4** [comment]
Assuming the codebase you have open is this one https://gitlab.com/qemu-project/qemu, it looks like the `audio_int.h` header is not self-contained, for example it references `uint64_t` without including the `<stdint.h>` header that declares it.

Clangd does not currently support files which are not self-contained, please see https://github.com/clangd/clangd/issues/45.
