### ISSUE TITLE
Support rename of macro and namespace

### ISSUE THREAD

**Issue by ghentschke** [clangd/clangd#1890]
Currently thre renaming of a macro definition like 
```C
#define ABC 46
``` 
results in an error reported by clangd:
```json
[2024-01-02T10:23:39.932424800+01:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.cdt.lsp.server:
{"jsonrpc":"2.0","id":"258","method":"textDocument/prepareRename","params":{"textDocument":{"uri":"file:///C:/Users/ghent/cdt-main/runtime-New_configuration/MyCmake/MyCmake.cpp"},"position":{"line":3,"character":9}}}

[2024-01-02T10:23:39.938409+01:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.cdt.lsp.server:
{
  "error": {
    "code": -32001,
    "message": "Cannot rename symbol: symbol is not a supported kind (e.g. namespace, macro)"
  },
  "id": "258",
  "jsonrpc": "2.0"
}
```
Same with namespaces.
Tested with clangd v17.0.3 on Windows and Linux.

**Comment by HighCommander4** [comment]
This one is on file at https://github.com/clangd/clangd/issues/729 with some discussion, let's close this as a duplicate

**Comment by ghentschke** [comment]
> This one is on file at https://github.com/clangd/clangd/issues/729 with some discussion, let's close this as a duplicate

Sorry, haven't found that one while searching the issues.
