### ISSUE TITLE
Operations in regions disabled by #if should not fail silently

### ISSUE THREAD

**Issue by gribozavr** [clangd/clangd#19]
Currently, if the user performs an operation, say, go to definition, on a symbol reference inside a code region skipped by a `#if`, the operation fails silently.  A better user experience would be to supply an error message through LSP, explaining the situation.  However, to the best of my knowledge, LSP does not provide a way to return a custom error message.

**Comment by sam-mccall** [comment]
LSP provides at least three options here:
 - respond to the RPC with an error, which may have a message (`ResponseError.message`). I would expect these messages not to be shown to the user by most clients, and maybe logged instead.
 - `window/showMessage`, which supports various levels
 - `window/logMessage`, which should write to a log

I'll experiment with showMessage to see what VSCode does. I think it's reasonable to expect that some clients will do something with these notifications and use VSCode as an example, and other clients won't do anything with such messages.

Another question is how emitting such messages should work within clangd layering: we currently return `Expected<vector<LocatedSymbol>>` where the Expected communicates harder errors (like "file isn't open"). So we need some channel in the API for sending these softer user-visible errors back.

**Comment by HighCommander4** [comment]
Today vscode gives me a little hover popup saying "No definition found for <symbol>" if I invoke go-to-definition in an inactive code block. I guess this has been fixed then?

**Comment by HighCommander4** [comment]
Closing per last comment.
