### ISSUE TITLE
erro on windows

### ISSUE THREAD

**Issue by lainswork** [clangd/clangd#1901]
Clangd cannot be combined with compile_ Commands.json works together, regardless of compile_ Is the absolute path or relative path recorded in commands.json

**Logs**
 // config.yaml is not exist
```
E:\clangd_17.0.3\bin>clangd --compile-commands-dir "compile_commands_test.json" --check="main.cc" --log=verbose
I[13:18:47.589] clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
I[13:18:47.590] Features: windows+grpc
I[13:18:47.590] PID: 38480
I[13:18:47.590] Working directory: E:\clangd_17.0.3\bin
I[13:18:47.590] argv[0]: clangd
I[13:18:47.590] argv[1]: --compile-commands-dir
I[13:18:47.591] argv[2]: compile_commands_test.json
I[13:18:47.591] argv[3]: --check=main.cc
I[13:18:47.591] argv[4]: --log=verbose
V[13:18:47.595] User config file is C:\Users\{myusername}\AppData\Local\clangd\config.yaml
I[13:18:47.595] Entering check mode (no LSP server)
I[13:18:47.595] Testing on source file E:\clangd_17.0.3\bin\main.cc
I[13:18:47.596] Loading compilation database...
I[13:18:47.612] Failed to find compilation database for E:\clangd_17.0.3\bin\main.cc
I[13:18:47.612] Generic fallback command is: [E:\clangd_17.0.3\bin] "E:\\clangd_17.0.3\\bin\\clang" "-resource-dir=E:\\clangd_17.0.3\\lib\\clang\\17" -- "E:\\clangd_17.0.3\\bin\\main.cc"
I[13:18:47.612] Parsing command...
```
![Snipaste_2024-01-12_13-19-22](https://github.com/clangd/clangd/assets/46841563/d2586bb0-ac4a-4b90-9054-1283013d0648)

**System information**

 clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)

Editor/LSP plugin:
no
i use `clangd --compile-commands-dir "compile_commands_test.json" --check="main.cc" --log=verbose`

Operating system:
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎6/‎21
操作系统版本	22000.2538
体验	Windows 功能体验包 1000.22001.1000.0

**Comment by HighCommander4** [comment]
The value of the `--compile-commands-dir` flag needs to be the **directory** containing the `compile_commands.json` file, not the file itself. Also, the file needs to be named `compile_commands.json` exactly.
