### ISSUE TITLE
[Feature Request] Add a command to force clangd to reparse the compilation database

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#192]
Currently, clangd does not  watch for changes in `compile_commands.json` and `compile_flags.txt`.

I think adding some commands like `Rescan Workspace` or `Restart Clangd` is a simple workarrounds that allows the user to manually invoke clangd to reparse the compilation database.

related: #83, https://reviews.llvm.org/D49267

**Comment by HighCommander4** [comment]
Note, in the vscode client, "Reload window" is a simple way to get clangd to restart and pick up compilation database changes.

**Comment by lh123** [comment]
@HighCommander4 Yes, "Reload Window" can restart clangd. But this is slow because it not only restarts clangd, but also restarts other plugins and restarts the VSCode UI.

**Comment by studgeek** [comment]
For Visual Studio Code, I believe it does have this now with the command  'Restart the clangd language server' which was added in https://github.com/clangd/vscode-clangd/pull/35.

**Comment by HighCommander4** [comment]
Yep, thanks for mentioning that.

In addition, there is now functionality to [watch for changes to `compile_commands.json` in the filesystem](https://github.com/clangd/vscode-clangd/pull/33) and prompt you to restart clangd when that happens.

We may still want to keep this open to track implementation of an even lighter-weight mechanism, that gets clangd to reload the CDB files without restarting clangd altogether (which also means re-reading the index contents and re-building the in-memory index serving structures).

**Comment by studgeek** [comment]
Ah yes, that is the link I actually meant to share - thanks.

+1 to having clang restart itself when the files it depends on change. I think is especially important since it supports multiple compile_commands.json files depending on the files accessed. So really its the one the knows what its currently depending on.

**Comment by HighCommander4** [comment]
> +1 to having clang restart itself when the files it depends on change. I think is especially important since it supports multiple compile_commands.json files depending on the files accessed. So really its the one the knows what its currently depending on.

That is also planned and tracked in #83.

(Note, it won't "restart itself", it'll just reload the CDBs. Clangd can't restart itself without the client's involvement, but it also doesn't need to in this case.)

**Comment by sam-mccall** [comment]
Changes are picked up as of https://github.com/llvm/llvm-project/commit/98993193e9037345ad13720a62974064a5f3d953.
I think this is obsolete now.

**Comment by studgeek** [comment]
Note CL in last change comment added "hot reload" at file level. After that the functionality of automatically restarting clangd when compile_commands.json is changed (described in 2nd to last comment) was removed at some point. Details are in https://github.com/clangd/vscode-clangd/issues/300#issuecomment-2348016329.

I think you can vote there if want option to have clangd restart functionality back also.
