### ISSUE TITLE
Rename feature

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#193]
This issues is tracking the on-going rename stuff in clangd.

**cross-file rename** 
- [x] initial implementation (index-based), https://github.com/llvm/llvm-project/commit/852bafae2bb4d875e8d206168a57667f59c0f9a6
- [x] add range patching heuristics, https://github.com/llvm/llvm-project/commit/891f82222bb8436bfd8db0acfbd5f3621fa53425
- [x] avoid paying O(N^2) cost when generating rename edits, https://github.com/llvm/llvm-project/commit/8805316172a650d62cdb6d3854ef0e54fb300ca6
- [x] handle implicit references returned from the index: @kirillbobyrev 
 https://github.com/llvm/llvm-project/commit/a6860c1af45776e349eaed3e8f0bb7e97abccd89
- [x] a tool to evaluate the rename, and verify the rename results, https://reviews.llvm.org/D71110

**index related**
- [x] surface the background index progress/index freshness, related to #22, @sam-mccall, https://github.com/llvm/llvm-project/commit/7d20e80225b3e4f3f5a8c57929061bef55f3d855
- [ ] extend the index to support virtual/overridden methods, primary templates/specializations

more? e.g. detect file-change events, give users an option to force rebuild the index.

**within-file rename**
- [x] re-implement the rename using SelectionTree + findExplicitReferences, https://github.com/llvm/llvm-project/commit/4f80fc2491cc35730a9a84b86975278b7daa8522
- [ ] get rid of the remaining `tooling::getUSRsForDeclaration` API, @kirillbobyrev 
- [x] fix the SelectionTree behavior on cxx initializer list, fixed by @sam-mccall, https://github.com/llvm/llvm-project/commit/ad9fd320091d44d4b8782c28b72a7be21a2bd68d
- [ ] figure it out how to support renaming UsingDecl, #170 (currently it is broken on both implementations)

**Comment by kirillbobyrev** [comment]
I went ahead and created "rename" label which will make it easier to track related issues as opposed to opening new ones **and** changing this issue/linking it (e.g. users might not know about that and labels are easy to discover). Feel free to delete it if this is something we don't want.

**Comment by hokein** [comment]
I think we can close this tracking issue now as all main blockers are fixed, the remaining items are improvements/bug fixes.
