### ISSUE TITLE
 go-to-definition doesn't work when triggering at the end of the symbol name.

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#194]
I think this is a regression after we switched to SelectionTree + targetDecl in XRefs.cpp https://github.com/llvm/llvm-project/commit/b6429cdd65ffa28591c5b0da37244ab66d0b1785.

```cpp
void func^(); // regression: no definition found

struct Foo^ { // go to the Foo class, works as expected.
  Foo(int);
};
void test() {
  fun^c(); // works as expected.
  func^(); // regression: no definition found
  Foo foo^(1); // go to Foo constructor (new behavior), this is expected.
}
```

**Comment by HighCommander4** [comment]
I think this is because SelectionTree, when given a cursor position, interprets it as referring to the character after the cursor, rather than the character before.

It does make an exception for the case where the character after is whitespace, which is why the `struct Foo^ {` case works.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D70727)

**Comment by hokein** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/939544add98ee6463d6abd6c28fa6c9ac4b6e104 and https://github.com/llvm/llvm-project/commit/2330cee82f0aa06e8063189fe7a68db3e51f3054.
