### ISSUE TITLE
clangd can't select function object correctly

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#195]
```c++
struct foo {
  void operator()(int a);
};

int main() {
    foo func;
    int bar = 0;
    func([[bar]]); // can't select bar.
}
```

**Comment by kadircet** [comment]
I suppose you mean, go-to-definition. It looks like a bug in selection tree, it returns `operator()` as selected node instead of `bar` in the example you mentioned.

**Comment by lh123** [comment]
> I suppose you mean, go-to-definition. It looks like a bug in selection tree, it returns `operator()` as selected node instead of `bar` in the example you mentioned.

Yes, hover over the bar and it will return `void operator()(int a)`  `int bar = 0`

**Comment by hokein** [comment]
looks like a regression introduced by https://github.com/llvm/llvm-project/commit/b6429cdd65ffa28591c5b0da37244ab66d0b1785.

**Comment by sam-mccall** [comment]
Given the code
```
auto lambda = [](const char*){ return 0; };
int x = lambda("y");
// 45678901234567890
```

The `int x` decl has the following ast:
```VarDecl 0x498be48a148 </usr/local/google/home/sammccall/test.cc:2:1, col:19> col:5 x 'int' cinit
`-CXXOperatorCallExpr 0x498be48a358 <col:9, col:19> 'int':'int'
  |-ImplicitCastExpr 0x498be48a2e8 <col:15, col:19> 'int (*)(const char *) const' <FunctionToPointerDecay>
  | `-DeclRefExpr 0x498be48a268 <col:15, col:19> 'int (const char *) const' lvalue CXXMethod 0x498be4f34b0 'operator()' 'int (const char *) const'
  |-ImplicitCastExpr 0x498be48a328 <col:9> 'const (lambda at /usr/local/google/home/sammccall/test.cc:1:15)' lvalue <NoOp>
  | `-DeclRefExpr 0x498be48a1b0 <col:9> '(lambda at /usr/local/google/home/sammccall/test.cc:1:15)':'(lambda at /usr/local/google/home/sammccall/test.cc:1:15)' lvalue Var 0x498be4f31d0 'lambda' '(lambda at /usr/local/google/home/sammccall/test.cc:1:15)':'(lambda at /usr/local/google/home/sammccall/test.cc:1:15)'
  `-ImplicitCastExpr 0x498be48a340 <col:16> 'const char *' <ArrayToPointerDecay>
    `-StringLiteral 0x498be48a248 <col:16> 'const char [2]' lvalue "y"
```

The children are:
1. the callee: `<lambda>::operator()`
2. the `this` argument: reference to `lambda`
3. the argument: string literal `"y"` (decayed from const char[] to const char*)

Unfortunately clang says that the callee DeclRefExpr spans the range from col 15-19. This covers the range of the argument. As these are siblings the first wins and gets to claim the range.

I don't think this range for the DeclRefExpr makes sense, though a change in clang may be invasive. There's also a good argument the node should be implicit...

**Comment by sam-mccall** [comment]
Oops, there's no such thing as an implicit Expr (Stmt) node.
We can just skip it in Selection.
