### ISSUE TITLE
clangd requires absolute path in compile_commands.json to successfully reuse preamble

### ISSUE THREAD

**Issue by konradsa** [clangd/clangd#196]
When editing a C++ file, clangd starts "parsing includes" as soon as I type the first letter in the editor. It seems to queue up all the file changes, and since the files can be quite large, it's always very much behind the latest state of the file. When I stop typing, it takes several minutes for clangd to catch up and go back to idle.

I thought I can mitigate this issue by setting "clangd.syncFileEvents=false" and only parse the file upon save. But setting this config value seems to have no effect, clangd still immediately starts parsing as soon as I start typing anything in the editor, even if it's just inserting a space key.

**Comment by kadircet** [comment]
clangd won't queue up all the changes you performed, it will schedule a rebuild every time you modify a file and debounce that build if you keep editing the file.

So let's say you've typed in `int x;` into a new line, clangd should only perform one rebuild after you stop typing for a few hundred milliseconds.

That build time is ofc subject to the file size, template instantiations, etc. but it shouldn't really take minutes. We have an optimization for skipping the build of the preamble(any includes you have in the current file, before the first declaration). If you've a non standard coding style like:

```cpp
static const char* some_id_for_file = "some_id";
#include <xxx>
.
.
.
some code
```

then clangd won't be able to optimize the preamble part of the current file, and you might get huge build times(in the order of minutes as you mentioned).

If it is possible could you provide a source file that's taking minutes to compile after you perform edits and the clangd logs with `-log=verbose`?
Clangd logs provides details about this process:
```
V[13:00:35.596] Preamble for file xxxx cannot be reused. Attempting to rebuild it.
...
V[13:01:08.968] Built preamble of size 44105772 for file xxxx
...
V[13:02:37.126] Reusing preamble for file xxxxx
```

**Comment by konradsa** [comment]
Thanks for the quick response. I do see this "Preamble ... cannot be reused" error, even though the includes comes first before any declaration. I have some "#pragma GCC diagnostic ..." there, thought that maybe they are causing this, but even after removing them I still see the same preamble error. What else could be causing this preamble optimization failure? I think a pattern I noticed is that it fails to reuse preambles for our cpp files, but for the header files it seems to succeed and those are much faster.

Beyond that, my problem also seems to be vscode specific. Even I tell vscode not to save the file, as soon as I even type a space anywhere into the code, I can see clangd starting to work, by its CPU usage spiking and vscode status line saying "clangd: file is queued" followed immediately by "clangd: parsing includes". What makes me think that is queues up the requests is that I see it constantly updating the error messages which what appears to be intermediate states of the file I was editing, even without the file being saved. So the debounce doesn't seem to work for me.

Is there a way to have vscode-clangd only parse the file when it's saved. What does the syncFileEvents=false setting do, as I see no effect when turning it on or off?

I am using the latest version of vscode and clangd extension on Windows, remotely developing on a Redhat Linux sever. My clangd version is a 10.0.0.

**Comment by kadircet** [comment]
I can't provide more help unless you provide logs or the source file you're working on(with the compile commands).

`sync file events` is an option to configure notifications for changes on the disk.

**Comment by hokein** [comment]
> Is there a way to have vscode-clangd only parse the file when it's saved.

I don't think there is a way to control it, this is by design in LSP. The LSP client sends the `textDocument/didChange` request to LSP server when there is a change in the opening file (even the change is in dirty buffer).

> What does the syncFileEvents=false setting do, as I see no effect when turning it on or off?

This flag is only to configure file-change events on disk, e.g. file on creation/deletion/change. Yes, it does nothing at the moment because clangd doesn't support it yet.

**Comment by konradsa** [comment]
Thanks to both of you, your input was very valuable for me to debug this issue further. It seems that the failure to reuse the preamble in my case is caused by a relative path to the cpp file in my compile_commands.json. file. As soon as I replace the relative path with an absolute path, the performance is much better, as preambles are reused now. Not sure if that is a known or intentional limitation of clangd, but I didn't see this documented anywhere.

**Comment by kadircet** [comment]
We haven't heard of such an issue before, normally preamble optimization is an implementation detail of clangd and should support most of the common use cases, and hopefully just be slow when your use case is not supported.

AFAIK, having relative/absolute paths should not cause this optimization to fail. Would like to take a closer look if you can provide more details.

Unfortunately, it is not documented as it is more of an implementation detail rather than a user-facing feature.

**Comment by konradsa** [comment]
Unfortunately, I can't provide any actual samples, as it's a large proprietary project. But the only change in the end I had to make to fix it was to convert the relative path to the cpp field in the commands field to an absolute path, and now clangd works very well.

So for instance if the command was like this:
"command":"/usr/bin/gcc ... -c foo.cpp -o foo.o"
I changed it to
"command":"/usr/bin/gcc ... -c /absolute/path/to/foo.cpp -o foo.o"

**Comment by konradsa** [comment]
Changed the title to better reflect what the actual issue is. clangd.syncFileEvents is not that important, the premables not being reused is a much bigger issue. After making the fix to the json that I outlined above, clangd now works like a charm with vscode, really impressive work.

**Comment by konradsa** [comment]
Closing this issue, I switched to clangd 9.0 and the absolute path is not required anymore. Before, I was using the custom clangd 10.0 binary that gets distributed with clion. Don't know if that is some issue now that pertains to 10.0 or is isolated to the custom clion version , but doesn't seem to be an issues with clangd 9.0.
