### ISSUE TITLE
Go-To-Definition does not resolve symlinks when used on symbols

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/clangd#197]
I have an include directory with symlinks in the build folder. When I execute (in VSCode) Go-To-Definition on an include file in an include statement, the symlink is resolved and I end up in the original file. When I execute Go-To-Definition on a symbol (class) from the included file, I end up in the symlink in the build directory instead of in the original file.

clangd version: 9

I'm running the clangd extension via the VSCode Remote SSH extension if that makes a difference. clangd itself is running on the remote machine.

**Comment by puremourning** [comment]
Similar? https://reviews.llvm.org/D66254

**Comment by DaanDeMeyer** [comment]
Maybe but I think this will need changes to `locateSymbolAt` in XRefs.cpp.

I'd rather not but I'll build clangd so I can check exactly where LLVM generates the faulty paths.

**Comment by DaanDeMeyer** [comment]
I've started looking into this in more detail. I'm currently at https://github.com/llvm/llvm-project/blob/b63c35ebf76ca0ac89405aeadee2b98a0e91e05e/clang-tools-extra/clangd/SourceCode.cpp#L622. I'm still compiling clangd so I haven't tested yet but it seems that `getCanonicalPath` never resolves symlinks even if the given path is a symlink even though it documents that it resolves symlinks. Is this supposed to be the case?

**Comment by kadircet** [comment]
https://github.com/llvm/llvm-project/blob/b63c35ebf76ca0ac89405aeadee2b98a0e91e05e/clang-tools-extra/clangd/SourceCode.cpp#L652, namely `getCanonicalName` function in `FileManager`(which calls `FileSystem::getRealPath` underneath) is the part that resolves the symlinks.

Note that, as documented inside the implementation(sorry it is not explained in the outer comment), this function only resolves symlinks in the parent path of the source file, not the source file itself. i.e:
if you have `/real/dir/a.cc` in which both `/real` and `/real/dir` are real directories, whereas `/real/dir/a.cc` is a symlink to `/src/a.cc`, clangd will still return `/real/dir/a.cc`
but if you have `/symdir/a.cc` in which `/symdir` is a symlink to `/src` then clangd will resolve it to `/src/a.cc` instead.

Unfortunately reasoning behind this predates me, @sam-mccall might have some explanation.

**Comment by DaanDeMeyer** [comment]
If I look at https://github.com/llvm/llvm-project/commit/dd67793c0c549638cd93cad1142d324b979ba682, It seems like `GetCanonicalPath` was resolving symlinks until you made the changes to unify path canonicalizations. Maybe you oversaw this in your commit? Although I'm having a hard time believing I'm the first one to encounter this issue in the entire year that has passed since that commit.

**Comment by kadircet** [comment]
Yes, as explained in the comment description each of the canonicalization functions were slightly different but IIRC only the behavior currently moved out (the one resolving the symlinks in the parents, but not in the file itself).

Also GoToDefinition was already making use of the [toURI](https://github.com/llvm/llvm-project/commit/dd67793c0c549638cd93cad1142d324b979ba682#diff-a3b9cc13cf291062af57b15036a8844cL54), which behaves similar to current canonicalization function in terms of symlinks.

**Comment by DaanDeMeyer** [comment]
I think I'm missing something really obvious, but before that commit, `GetCanonicalPath` (back then named `GetRealPath`) called `SourceMgr.getFileManager().getVirtualFileSystem()->getRealPath(Path, RealPath)` to resolve the given Path symlinks. In the commit I linked, that statement was removed which I think means `makeLocation` in XRefs.cpp doesn't resolve symlinks anymore since that commit.

**Comment by DaanDeMeyer** [comment]
`uri::canonicalize` which is also called in `makeLocation` does not seem to resolve symlinks either. As far I can see, `ToUri` is never called on the results from `makeLocation` in `LocateSymbolAt` in XRefs.cpp so I think resolving symlinks is just never happening in the code path of goto-definition.

**Comment by kadircet** [comment]
> I think resolving symlinks is just never happening in the code path of goto-definition.

not in a direct way. when you perform go-to-definition on a symbol that is both covered by current translation unit and clangd index, clangd might chose to prioritize index result. As it will have the `real` definition location not just the declaration, which was gathered via `SymbolCollector` either as part of `FileIndex` or `BackgroundIndex`.

While storing symbols `SymbolCollector` was calling `toURI`(now it calls `getCanonicalPath`) and storing the result came out of it.
Later on we surface URIs coming from index directly, without resolving symlinks(as they are resolved while storing). That's the reason why you are not seeing any resolution on that code path directly.

**Comment by DaanDeMeyer** [comment]
Sure but if `getCanonicalPath` doesn't do symlink resolving and is called by `toUri` which expects it to do symlink resolving, doesn't that leave us with the same problem?

**Comment by DaanDeMeyer** [comment]
Sure, but `toUri` doesn't seem to do any symlink resolving either so we're still stuck with the problem that neither `toUri` nor `GetCanonicalPath` are resolving symlinks.

**Comment by kadircet** [comment]
Sorry I seem to be lost, why do you think toURI (in symbolcollector) is not performing symlink resolution? as I've explained above, it calls [FileManager::getCanonicalName](https://github.com/llvm/llvm-project/commit/dd67793c0c549638cd93cad1142d324b979ba682#diff-a3b9cc13cf291062af57b15036a8844cL75) which calls `getRealPath` that does the symlink resolution. Have you read https://github.com/clangd/clangd/issues/197#issuecomment-576383746 ?

**Comment by DaanDeMeyer** [comment]
After changing the implementation of `getCanonicalPath` back to:

```c++
llvm::Optional<std::string> getCanonicalPath(const FileEntry *F,
                                             const SourceManager &SourceMgr) {
  if (!F)
    return None;

  llvm::SmallString<128> FilePath = F->getName();
  if (!llvm::sys::path::is_absolute(FilePath)) {
    if (auto EC =
            SourceMgr.getFileManager().getVirtualFileSystem().makeAbsolute(
                FilePath)) {
      elog("Could not turn relative path '{0}' to absolute: {1}", FilePath,
           EC.message());
      return None;
    }
  }

  SmallString<128> RealPath;
  if (SourceMgr.getFileManager().getVirtualFileSystem().getRealPath(FilePath,
                                                                    RealPath)) {
    log("Could not compute real path: {0}", FilePath);
    return FilePath.str().str();
  }

  return RealPath.str().str();
}
```

File symlinks are once again correctly resolved.

**Comment by kadircet** [comment]
No worries.
Yes you are right the function `getRealPath` was resolving the symlink of the fullpath. And before the change that unifies those functions, it was being called by `makeLocation` as you pointed out.

But the point I am trying to make is, as explained above, `makeLocation` was only called in [one code path](https://github.com/llvm/llvm-project/blob/7120fb9b0ba5474693a56d0f6e632058c9764f84/clang-tools-extra/clangd/XRefs.cpp#L321), it only generates a candidate. yes, that candidate *might* end up being the ultimate result, if the definition is also visible in the current AST.

But after traversing AST, we perform a index lookup, and filepaths received from that one are *not* translated through `makeLocation` but rather sent to `toLSPLocation` as you can see [here](https://github.com/llvm/llvm-project/blob/7120fb9b0ba5474693a56d0f6e632058c9764f84/clang-tools-extra/clangd/XRefs.cpp#L350). and as you can see [here](https://github.com/llvm/llvm-project/blob/7120fb9b0ba5474693a56d0f6e632058c9764f84/clang-tools-extra/clangd/XRefs.cpp#L49) it does *not* perform any resolution etc. because the `toURI` function inside symbolcollector is responsible for putting a canonical URI, and that function, as you have noticed, was and is performing symlink resolution only in directories.

Therefore clangd had a different behavior depending on which source provided the symbol definition(heuristics around that one also has changed over time). So you would go to one file until clangd indexed your project, and then go to some other once clangd indexing has finished. The patch above tried to make that behavior(and some other) more deterministic.

> After changing the implementation of getCanonicalPath back to:
As explained above, this is expected in today's version since *all* code paths are performing the path canonicalization the same way. But now, you are introducing a behaviour change to how indexing code handled symlinks. That's fine on its own, but as I explained above the current behavior was a deliberate decision(that was made before the above mentioned patch unified them all). The problem is I don't remember the reasoning behind, so I am not sure if it is still valid or not.

I hope I made myself clear this time :D

**Comment by DaanDeMeyer** [comment]
Alright now I think I get it. To summarize:

- Before your commit,  `GetRealPath` was used to resolve file symlinks everywhere except `toUri`. Because `GetRealPath' was not used in `toUri`, `toUri` did not resolve symlinks.
- After your commit, all code uses `GetCanonicalPath` which doesn't resolve file symlinks so currently file symlinks are not resolved anywhere.
- After my revision, all code (including `toUri`) resolves file symlinks.

Is that correct? My next question would then be, why not resolve file symlinks and instead do this weird directory stuff that only handles the direct parent directory of a file (what if the grandparent directory is a symlink instead of the parent directory)? I suppose that question is for @sam-mccall to answer.

I definitely think file symlink resolution should be done as my use case is broken without it. If parent directory symlink resolution is supposed to be done, shouldn't it be done recursively for all parent directories? The current behaviour seems unintuitive.

**Comment by sam-mccall** [comment]
Apologies for the current maybe-confused and certainly-underdocumented state.
We're trying to work out whether the motivation for this behavior on the shared codepath was a) specific desired behavior, b) motivated by performance, c) accident/oversight. Best guess is a but I really wish this was recorded.

Symlink behaviour tends to be murky - IME it doesn't tend to be clear what the right thing is, symlinks get used for different things and often two use cases will want different incompatible policies. We should try to fix as many as we can but we need to be cautious.

> I definitely think file symlink resolution should be done as my use case is broken without it.
Could you describe your use case?

> If parent directory symlink resolution is supposed to be done, shouldn't it be done recursively for all parent directories? 
It appears to, on unix at least the FileManager's cache is ultimately backed by `::realpath` which applies to every segment.

**Comment by DaanDeMeyer** [comment]
I'm (forced to) use the scons build system which by default hard links all source files to the build directory and performs the build on those files for some unknown reason (probably related to reproducability). This causes the issue that Go To Definitions in project source files go to the source files in the build directory even though I want to end up in files in the actual source directory. Luckily, scons has an option `--duplicate=soft-hard-copy` that causes source files to be symlinked to the source directory instead of hard linked. Now, every file in the build directory is a symlink to the file in the source directory. However, when using Goto definition, I still end up (using VSCode) in the symlink of the source file in the build directory instead of in the actual source file in the source directory. With my revision, I correctly end up in the actual source file in the source directory.

Ideally, I'd be able to switch build system to something sane but as that's not an option, I would like clangd to support navigating to the original source file via a symlink located in the build directory.

**Comment by DaanDeMeyer** [comment]
@sam-mccall Any opinions on the best approach to symlinks? I want to make an effort to improve on the current situation which unfortunately doesn't work for my use case as explained above. Would adding an option that makes clangd resolve file symlinks be considered an acceptable solution?

**Comment by DaanDeMeyer** [comment]
I've realized it's easy enough for me to maintain a fork of clangd that resolves symlinks for this particular project.

**Comment by lawsonAGMT** [comment]
> I've realized it's easy enough for me to maintain a fork of clangd that resolves symlinks for this particular project.

We have this same issue in our Bazel based project. @DaanDeMeyer are you still maintaining a solution to this?

**Comment by mason-bially** [comment]
Yea I agree this is a real pain point if this is still broken.
