### ISSUE TITLE
`--function-arg-placeholders=0` should apply to variable template arguments as well

### ISSUE THREAD

**Issue by 16bit-ykiko** [clangd/clangd#1976]
Hi there,

There is already an option that can be used to disable the function argument placeholders. Please see this [issue](https://github.com/clangd/vscode-clangd/issues/92). Is it possible to provide a similar option that can be applied to templates?

**Comment by HighCommander4** [comment]
(Transferred to server repo as this is a server-side issue)

**Comment by HighCommander4** [comment]
[Here](https://searchfox.org/llvm/rev/bfb868201f821047015465fb3f0afa6daa321b5f/clang-tools-extra/clangd/CodeComplete.cpp#621-622) is the check which handles class templates but doesn't currently handle variable templates.

**Comment by HighCommander4** [comment]
Proposed fix: https://github.com/llvm/llvm-project/pull/85740
