### ISSUE TITLE
Add option to disable code formatter

### ISSUE THREAD

**Issue by decimad** [clangd/clangd#20]
The vscode clangd addin seems to auto-install clang formatting. It would be nice if this could be turned off, as some people might use a different formatting provider.

**Comment by sam-mccall** [comment]
Thanks, this isn't something we'd thought about.

Can you help us understand the situation:
 - are you talking about when formatting the document manually, format-on-save, format selection, or format-as-you-type?
 - which other formatting extensions do you have installed?
 - anything special about the files (e.g. language, file extension)
 - what behavior do you currently see, and what do you want to happen?

I'm not sure if this is going to be best solved in the clangd extension or vscode proper, but we should investigate.

**Comment by sam-mccall** [comment]
The general case of multiple formatting providers is
https://github.com/Microsoft/vscode/issues/41882

You can apparently switch providers for a filetype with right click -> format document with -> configure default formatter.

Does this work for you?

**Comment by decimad** [comment]
I will try, thank you for bringing this up!
