### ISSUE TITLE
Debian 12 arm64

### ISSUE THREAD

**Issue by root-kidik** [clangd/clangd#2009]
Please add support

**Comment by HighCommander4** [comment]
You can find arm64 binaries on the LLVM project release pages such as https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.3 (clang+llvm-18.1.3-aarch64-linux-gnu.tar.xz package).

**Comment by Moerliy** [comment]
I would love to see a Linux arm64 bin in the releases of this repo too.
I know that I can get it from the offical llvm releases but I don't want to download 1 GB just do get clangd.
Another perc would be that I could integrate clangd into mason (nvim lsp package manager) where there a several people complaining that there is no clangd support for arm right now.

**Comment by HighCommander4** [comment]
There is previous discussion of this topic in #514

I'm going to close this as a duplicate

**Comment by HighCommander4** [comment]
Duplicate og #514
