### ISSUE TITLE
Is there are possbility to set standard / add defines?

### ISSUE THREAD

**Issue by kelbon** [clangd/clangd#2015]
I have project which is compiled with gcc in c++23, compile-commands.json looks like 
```json
{
  "directory": "somedir",
  "command": "g++ -std=c++23 ..."
  "file": "somefile",
  "output": "someoutput.o"
},
```
But clangd does not sees excepted from C++23 stdlib (define __cpp_concepts too small)

What i can do to fix it?

**Comment by kelbon** [comment]
i added -D__cpp_concepts=mydigit to all compile commands in .json (yes i know... but it works)

**Comment by HighCommander4** [comment]
This particular issue (the value of the `__cpp_concepts` macro) was an inconsistency between gcc and clang (which affected the ability to **compile** some libstdc++ headers like `<expected>` with clang, too, i.e. nothing clangd-specific). It was resolved recently in https://github.com/llvm/llvm-project/pull/87998 for llvm 19.
