### ISSUE TITLE
go-to-definition is broken when the symbol is on macro expansion

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#202]
```
// Nothing returned when triggering go-to-definition on all following positions.
EXPECT_THAT(locate^SymbolAt(A^ST, T.po^int("1")), ElementsAre(Sym("str")));
```

Version: Head
Reproduce: Open `clangd/unittests/XRefsTests.cpp`, and call go-to-definition on the code like above.

Should be a SelectionTree issue.

**Comment by sam-mccall** [comment]
Minimal repro:

```
int x(int);
#define M(foo) x(foo)
int a = 42;
int b = M(^a); // want: a, got: x
```

**Comment by sam-mccall** [comment]
Issue is that the ref to `x` is written in the macro, therefore its source range is the whole macro invocation `M(a)`. It's a left-sibling of the ref to `a`.

**Comment by sam-mccall** [comment]
One possible workaround (but unlikely complete solution) is to tag claimed nodes with (handwaving) the macro expansion nesting depth, where macro arg expansions don't count.

**Comment by HighCommander4** [comment]
Should names that don't appear in the macro invocation (like `x` here) ever be valid targets?
