### ISSUE TITLE
Add a fixit for inserting the matching closing brace

### ISSUE THREAD

**Issue by andre-hartmann** [clangd/clangd#2022]
This request was discovered when working in Qt Creator and first reported as [QTCREATORBUG-30732](https://bugreports.qt.io/browse/QTCREATORBUG-30732)

Consider the following C code:
```
#include <string.h>

static char GlobalVariable[64];

int main()
{
    strcpy(GlabalVariable, "Hello World");
    strcpy(GlobalVariable, "Hello World";
    return 0;
}
```
For the first errornous line we get a fixit (light bulb) to rename the variable and the following tooltip:
```
main.c:7:12: Use of undeclared identifier 'GlabalVariable'; did you mean 'GlobalVariable'? (fix available)
main.c:3:13: 'GlobalVariable' declared here
```
but for the second there is only a Clangd error that says a closing brace is missing at column 41:
```
main.c:8:41: Expected ')'
main.c:8:11: to match this '('
```
It would be cool to have fixits for the second kind of errors too.

This is how it looks in Creator:
![screenshot-1](https://github.com/clangd/clangd/assets/23051867/22dd8356-343a-463a-ad27-5e6eceeb3bd5)

**Comment by ckandeler** [comment]
Note that such a fix-it does exist for missing semicolons. I don't know what the major difference is.

**Comment by HighCommander4** [comment]
Could you file this upstream at https://github.com/llvm/llvm-project/ please? Fixits for diagnostics produced by the clang frontend are themselves produced by the frontend; clangd's role is just to surface them in the editor.

**Comment by andre-hartmann** [comment]
Thanks @HighCommander4, I've reported it as [llvm #90027](https://github.com/llvm/llvm-project/issues/90027).

Closing this one now.
