### ISSUE TITLE
Do not limit returned local references

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#204]
While static index may contain too many references and limiting results there might make sense, I would argue it is preferable to always return all references from the current AST.

E.g. try searching for `CmdArgs` [here](https://github.com/llvm/llvm-project/blob/b6d7bbfa004310777cd41448ffc377aea082fc8c/clang/lib/Driver/ToolChains/Clang.cpp#L6179).

Expected: all results of `CmdArgs` are returned.
Actual: only a limited number of results are returned.

**Comment by Lennon925** [comment]
I think it's significant to return all reference results too.
