### ISSUE TITLE
headers from pch are not recognized inside project

### ISSUE THREAD

**Issue by dylsonowski** [clangd/clangd#2040]
As I mentioned in https://github.com/clangd/clangd/issues/2034#issue-2289699133 I have big problem with pch in my project. As it was suggested, adding `Expect.hpp` to pch file was my mistake so I removed it but the error still occur. The same problem is present in `Matrix.hpp`.

![image](https://github.com/clangd/clangd/assets/32763547/f5d924c9-1f0d-4d03-9dc5-25ffc3638ea5)

Strange thing that I realized is the fact that there are no such errors with internal include files added to pch. The problem seems to occur only for std library

**Comment by HighCommander4** [comment]
The workaround I suggested in #2034 was:

> A workaround would be to include `palepch.hpp` from `Expect.hpp`.

i.e. to add `#include "palepch.hpp"` to `Expect.hpp`, to make `Expect.hpp` self-contained.

The same applies to `Matrix.hpp`, that file is also not currently (assuming we're talking about the version [here](https://github.com/dylsonowski/AI-Playground/blob/master/Pale-Engine/src/Core/Math/Matrix.hpp)) self-contained, and adding `#include "palepch.hpp"` to it would make it self-contained and satsify clangd.

**Comment by HighCommander4** [comment]
Like I've said in the other issue, not supporting files which are not self-contained is a known limitation of clangd, tracked in #45.

**Comment by dylsonowski** [comment]
So basically, I can't use clangd with pch?

**Comment by HighCommander4** [comment]
Adding `#include "palepch.hpp"` to headers like `Matrix.hpp` and `Expect.hpp` should not interfere with your ability to use PCH during compilation and benefit from any resulting compile-time speedup.

When the compiler encounters the `#include "palepch.hpp"` in a header like `Matrix.hpp` while translating a source file, it will just ignore its contents since it has already loaded them as a PCH.

**Comment by dylsonowski** [comment]
Ok, the last question. If I get it wright, I have to include my pch file in all header files that needs to use standard library?

**Comment by HighCommander4** [comment]
> I have to include my pch file in all header files that needs to use standard library?

The general principle is, until #45 is implemented, any file that you open for editing with clangd needs to be **self-contained**. That means that for any symbol used in the file (for example, `std::cout`), the header which defines that symbol (for example, `<iostream>`) needs to be included, directly or indirectly, **from that file**.

In this example project, including the PCH header is headers like `Expect.hpp` is an easy way to accomplish that. But alternatively, you could include things like `<iostream>` directly in a header like `Expect.hpp` as well.

**Comment by dylsonowski** [comment]
Ok, thank you for help
