### ISSUE TITLE
Include cleaner recommends removing includes needed for casts to related types

### ISSUE THREAD

**Issue by graveljp** [clangd/clangd#2044]
Clangd's Include Cleaner doesn't know that the definition of a child class is needed to be able to cast a child object to the parent type. See for instance:

**parent.h**
```C++
#pragma once
class Parent {};
```

**child.h**
```C++
#pragma once
#include "parent.h"
class Child : public Parent {};
```

**feature.h**
```C++
#pragma once
class Child;
Child& getChild();
```

**main.cc**
```C++
#include "feature.h"
#include "parent.h"
#include "child.h"  // Complains with "Included header child.h is not used directly"

int main() {
  Parent& parent = getChild();
  return 0;
}
```

In the above example, `#include "child.h"` is needed because without it, the code doesn't compile:

**main_broken.cc**
```C++
#include "feature.h"
#include "parent.h"

int main() {
  Parent& parent = getChild();
  return 0;
}
```

```shell
$ clang++ -xc++ -c main_broken.cc
main_broken.cc:5:11: error: non-const lvalue reference to type 'Parent' cannot bind to a value of unrelated type 'Child'
    5 |   Parent& parent = getChild();
```

**System information**

Output of `clangd --version`:
```
clangd version 19.0.0git (https://github.com/llvm/llvm-project.git 55e59083cb610f30ad21fe8c8cdb9900534937ec)
Features: linux
Platform: x86_64-unknown-linux-gnu
```
Editor/LSP plugin:
VSCode

Operating system:
Linux

**Comment by kadircet** [comment]
this is pretty similar to https://github.com/clangd/clangd/issues/2043, it arises from the fact that include-cleaner do not encourage forward declarations, so closing this one.
