### ISSUE TITLE
Unsupported argument 'cortex-a76.cortex-a55' to option '-mcpu='clang(drv_unsupported_option_argument)

### ISSUE THREAD

**Issue by love1angel** [clangd/clangd#2045]
my environment is a cross compile environment.

after generate compile_commands.json. will get message like this https://github.com/llvm/llvm-project/issues/64958. when remove -mcpu=... will use normally

**Logs**

in compile_commands.json

Unsupported argument 'cortex-a76.cortex-a55' to option '-mcpu='clang(drv_unsupported_option_argument)

**System information**

Output of `clangd --version`:

 % clangd --version
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
vscode clangd

Operating system:
ubuntu 22.04

**Comment by HighCommander4** [comment]
Assuming your build compiler is not clang, it's expected that there are differences between compilers such as what target CPUs they support.

You can use [clangd's config file](https://clangd.llvm.org/config.html#compileflags) to remove or modify flags that clang doesn't recognize, for example:

```yaml
CompileFlags:
  Remove: [-mcpu=*]
```
