### ISSUE TITLE
go-to-definition does not work inside GTest assertions

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#205]
Input:
```cpp
std::vector<int> vec;
ASSERT_EQ(ve^c.s^ize(), 1);
```

Expected: go-to-definition navigates to the local variable and `vector<T>::size`, respectively
Actual: getting errors: `no definition found for 'vec'` and `no definition found for 'size'`

**Comment by kadircet** [comment]
duplicate of https://github.com/clangd/clangd/issues/202
