### ISSUE TITLE
Include Cleaner doesn't include headers needed by default template arguments

### ISSUE THREAD

**Issue by graveljp** [clangd/clangd#2050]
Consider the following files:

**map.h**
```c++
#pragma once

template<typename Key>
class Hasher;

template<typename Key, typename KeyHasher = Hasher<Key>>
class Map {
  KeyHasher hasher_;
};
```

**foo.h**
```c++
#pragma once
class Foo {};
```

**foo_hasher.h**
```c++
#pragma once
#include "map.h"
#include "foo.h"

template<>
class Hasher<Foo> {};
```

**main.cc**
```c++
#include "foo.h"
#include "foo_hasher.h"
#include "map.h"

int main() {
  Map<Foo> map;
  return 0;
}
```

Here, neither Foo nor Map knows that the other exists. A third header, foo_hasher.h, is therefore needed to connect the two. The three headers are needed for `main.cc` to compile. Include Cleaner however recommends removing the `foo_hasher.h` include, which would break the build.

**System information**

Output of `clangd --version`:
```
clangd version 19.0.0git (https://github.com/llvm/llvm-project.git 55e59083cb610f30ad21fe8c8cdb9900534937ec)
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
VSCode

Operating system:
Linux

**Comment by HighCommander4** [comment]
Might be the same issue as #1555?

**Comment by kadircet** [comment]
Unfortunately these sorts of type extensions are actual violations for include-cleaner, as `Hasher` isn't spelled anywhere in the meanwhile, recommended solution is having these types of extensions defined with your type, eg:

foo.h:
```cpp
#pragma once

#include "hasher.h" // should be independent of map.h
class Foo {};

template<>
class Hasher<Foo> {};
```

If you can't migrate to this pattern, you can mark the header providing extension with [// IWYU pragma: always_keep](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-always_keep).
