### ISSUE TITLE
Folding is not available for preprocessor blocks

### ISSUE THREAD

**Issue by davidavetyan** [clangd/clangd#2059]
Expand/collapse button in the left gutter is not available for preprocessor blocks when using clangd.

Example:
![image](https://github.com/clangd/clangd/assets/30115424/ae471798-f46a-42b9-a9aa-e3b8b385d0c7)

Same code when the native Cpp extension is enabled:
![image](https://github.com/clangd/clangd/assets/30115424/ba359f6d-eb3a-45a2-80da-e02c71303cbf)

**Comment by HighCommander4** [comment]
Duplicate of #1661
