### ISSUE TITLE
Clangd is ,after recent update, is labeling my macros as functions, highlighting both them in same color, previously it was correct  

### ISSUE THREAD

**Issue by ravikul505** [clangd/clangd#2063]
![clangdError](https://github.com/clangd/clangd/assets/72021422/3317dd95-3ad1-4683-9dc2-6e0050fc2eb9)
[DESCRIPTION]
i recently updated the clangd to its latest version by using mason,
till that point, all the lsp features run beautifully no problem any where i also use the 
"clangd-extensions", and my macros when used in source files were colored red, automatically,
i never configured it to do that way , but i really like that feature as it was so convinent

after the update all my macros are colored the same way as functions which is purple and even in the autocomplete buffer 
they are being labeled as the lsp as functions, as when the autocomplete buffer is opened , the macros 
are labeled as functions 

is there a way i can turn this back to how it was before  ?? 
![clangdError2](https://github.com/clangd/clangd/assets/72021422/f0a9f746-19af-4255-8f4e-075f369fd3d5)

i have attached an screenshot of my macro definitions and using them in source file ,and the macros being labeled
as functions .

**Logs**
https://drive.google.com/drive/folders/1x5sRGID5AxHzMyN4lWDTnj33wUGQBJRf?usp=drive_link
here is the drive link that contains logs.txt where i have a logs of a session from opening a file writting a predefined macro
and the defining a macro in that file and then using that 

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
[**clangd --version**]:
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

[**Editor/LSP plugin**]:
__INSTALLER PLUGIN__
"williamboman/mason.nvim",

__LSP PLUGIN__
"neovim/nvim-lspconfig",
"williamboman/mason-lspconfig.nvim",
"p00f/clangd_extensions.nvim",

__SNIPPET ENGINE AND AUTOCOMPLETION__
"hrsh7th/cmp-nvim-lsp",
"hrsh7th/nvim-cmp",
"L3MON4D3/LuaSnip",
"saadparwaiz1/cmp_luasnip",
"rafamadriz/friendly-snippets",

[**Operating system**]:
Linux KillEngine 6.9.3-arch1-1
 x86_64 GNU/Linux

**Comment by HighCommander4** [comment]
I'm going to ignore bug reports that copy/paste the issue template without actually providing the information requested in the template.

**Comment by ravikul505** [comment]
wait i aminute just sending all the logs

> I'm going to ignore bug reports that copy/paste the issue template without actually providing the information requested in the template.

wait a minute just sending all the logs , i clicked on submit by mistake

**Comment by HighCommander4** [comment]
Do you know what your old clangd version was before the update?

**Comment by HighCommander4** [comment]
If I understand correct, there are two issues:

 1. During autocomplete, the completion item kind shown for macros is "Function" rather than "Text"
 2. In the editor, macros are colored the same as functions

The first one is a deliberate change, it was changed in clangd 17 and later following a user request in #1484.

For the second one, the clangd server does send different [semantic token types](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#semanticTokenTypes) -- `function` for functions and `macro` for macros. Clients should have a way to customize the colors for each semantic token kinds, though I don't know how to do it for neovim (I use vscode myself). That may be a better question for the neovim issue tracker.

**Comment by ravikul505** [comment]
alright , if its not a bug then i am good, i will see how to customize it , thank you for your time
