### ISSUE TITLE
Unable to write file (Unknown (FileSystemError) ...)

### ISSUE THREAD

**Issue by dwilliamson** [clangd/clangd#208]
I can't edit and save most of the core header files in my project with vscode-clangd enabled. When I hit save, this error pops up:

![image](https://user-images.githubusercontent.com/1532903/69332671-10154300-0c4f-11ea-9eaf-ea88ee8a7ceb.png)

I can freely save most of the the header files in my project but the core ones. It seems this problem is limited to header files that are frequently included by lots of other files.

I *used* to be able to reload the window and hit save really quickly before the plugin loads. However, with latest VSCode, plugin startup time seems to have improved so I have to disable the plugin, reload and save to affect any changes.

**Comment by sam-mccall** [comment]
Ouch :-( Can you test turning off background indexing? Add `-background-index=0` to the clangd arguments list in settings.

Based on your description of the affected files, I think the background indexing is reading these files at the time to compile other source files. This works fine on Unix but as I understand that windows has... less helpful locking rules for concurrent reads and writes.

I'm not sure what a real fix would look like. We had discussed adding a file caching layer to the VFS, which might help here - I believe clang holds the header open for the whole compilation, while the caching layer would open it to read and quickly close it (the first time), and never open it (subsequent times). Even just an LRU cache big enough to hold the most common headers would be sufficient for this problem.

**Comment by dwilliamson** [comment]
I tried to add `-background-index=0` but got an error. Looks like I was using version 7.0.1. I have upgraded to 9.0.0 and that file immediately saves without error. I'll iterate for a while and close this if all is good. Thanks!

**Comment by sam-mccall** [comment]
Oh, I should have checked that first, thanks!
I'm fairly sure this was fixed by https://github.com/llvm-mirror/clang-tools-extra/commit/85903ea17834a64cbf8f7b99702f3e35d4625e12 then.
