### ISSUE TITLE
False positive on Invalid operands to binary expression when working with std::views::transform.

### ISSUE THREAD

**Issue by At11011** [clangd/clangd#2083]
I was using clangd in Neovim when I noticed some odd error messages coming from the LSP that was not manifesting when I was compiling. I created a minimal example, which is shown here:

![image](https://github.com/clangd/clangd/assets/98706086/570a762c-9f8e-4e36-845f-e66de57175eb)

I am using [std::views::transform](https://en.cppreference.com/w/cpp/ranges/transform_view) to extract a view of the double data entries inside a std::vector<std::pair<double, int>>. For some reason, clangd does not like the use of the pipe operator (l) in this context. However, this code compiles and runs without issue (using g++ 11.4.0, not clang).

Here is a minimal example which recreates the problem:

```cpp
#include <iostream>
#include <ranges>
#include <utility>
#include <vector>

auto get_doubles_view(const std::vector<std::pair<double, int>>& vec)
    -> decltype(vec | std::views::transform(&std::pair<double, int>::first)) {
    return vec | std::views::transform(&std::pair<double, int>::first);
}

int main() {
    std::vector<std::pair<double, int>> test = {{0.5, 1}, {1.1, 3}, {7.0, 2}};
    auto doubles_view = get_doubles_view(test);

    for (const auto& d : doubles_view) {
        std::cout << d << ' ';
    }
    std::cout << std::endl;
    return 0;
}
```

This is my CMakeLists.txt file:

```cmake
cmake_minimum_required(VERSION 3.15)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)
add_executable(reinterpret_vec_pair reinterpret_vec_pair.cpp)
```

And I compile/run using these commands

```bash
cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
cmake --build .
./reinterpret_vec_pair 
```

Additional note: The example code provided in the [std::views::transform](https://en.cppreference.com/w/cpp/ranges/transform_view) documentation gives rise to similar errors.

**Logs**

I am somewhat new to neovim, and I am not familiar with the process of extracting logs. I spent some time researching trying to figure it out, but I have not yet been able to extract logs related to clangd. I would appreciate some support on this front if you happen to have a straightfoward answer for me to try.

**System information**

Output of `clangd --version`:
```
Ubuntu clangd version 12.0.1-19ubuntu3
```

Editor/LSP plugin:

I am using neovim (output of nvim --version):

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
as well as lspconfig (running the default clangd settings, as found on the lspconfig [github](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#clangd) page)

Operating system:

Ubuntu 22.04.4 LTS

**Comment by HighCommander4** [comment]
> **System information**
> 
> Output of `clangd --version`:
> 
> ```
> Ubuntu clangd version 12.0.1-19ubuntu3
> ```

Could you try with clangd 18 (the latest version) from https://github.com/clangd/clangd/releases?

Clangd 12 was released in February 2021, a lot of bugs in clang's C++20 support have been fixed since then.

**Comment by At11011** [comment]
> > **System information**
> > Output of `clangd --version`:
> > ```
> > Ubuntu clangd version 12.0.1-19ubuntu3
> > ```
> 
> Could you try with clangd 18 (the latest version) from https://github.com/clangd/clangd/releases?
> 
> Clangd 12 was released in 2021, a lot of bugs in clang's C++20 support have been fixed since then.

This worked! Using clangd18:

```bash
clangd --version
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

these errors are gone. I used the install instructions on https://clangd.llvm.org/installation.html for Ubuntu/Debian, but I didn't realize just how old that version would be. Thank you!

**Comment by HighCommander4** [comment]
One more thing that might be handy: up-to-date versions of clangd (and other LLVM components) can be obtained in package form from https://apt.llvm.org/ as well.
