### ISSUE TITLE
Objective-C semantic highlight

### ISSUE THREAD

**Issue by Pancf** [clangd/clangd#2089]
I find Objective-C property attributes have no semantic highlight. Does clangd support it now? If not, is there support plan?

**Comment by HighCommander4** [comment]
Can you give a code example?

**Comment by Pancf** [comment]
> Can you give a code example?

```objc
@property (nonatomic, getter=isOpacity) BOOL opacity;
```
take above code as example,  `nonatomic` and `getter=isOpacity` are property's attributes, and also Objective-C's keywords. in Xcode, they are highlighted the same as `@property`,`@interface`, etc. but when I use emacs with lsp-clangd as lsp server, this attributes(also keywords) are not highlighted properly.

**Comment by HighCommander4** [comment]
Thanks for clarifying.

Clangd actually does not highlight any keywords. For example, `int` is not highlighted by clangd either. It only highlights **semantic** tokens (mostly identifiers, whose role can only be determined based on a semantic model fo the code).

For highlighting of keywords, clangd leaves this to the client.

For example, with the VSCode client, property attributes are highlighted correctly by the client:

![image](https://github.com/user-attachments/assets/fe72e14f-df9a-4fe0-b394-865d8305ef45)

So, this would be an issue to file with your client (emacs).

**Comment by Pancf** [comment]
i got it, thank you :)
