### ISSUE TITLE
clangd version 18.1.3 default have  "__linux__" flag.

### ISSUE THREAD

**Issue by sheeaza** [clangd/clangd#2095]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**

```
I[05:25:12.606] clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
I[05:25:12.606] Features: linux+grpc
I[05:25:12.606] PID: 3355719
I[05:25:12.606] Working directory: /xxxxce/dev/tmp
I[05:25:12.606] argv[0]: clangd
I[05:25:12.606] argv[1]: --log=verbose
V[05:25:12.606] User config file is /xxxxxfig/clangd/config.yaml
I[05:25:12.606] Starting LSP over stdin/stdout
```

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`: clangd version 18.1.3

Editor/LSP plugin: neovim + coc.vim

Operating system: nixos, linux

**issue**
example codes:
```
#ifdef __linux__
#endif
```
Test with c file with only codes above, found that `__linux__` is defined, which is not expect, I hope this is not defined since I worked on embedded platform's codes which is not linux.
Or is there anyway to remove `__linux__` flag? Note, the `__linux__` is not defined by compile_command.json, this maybe built-in by clangd.

**Comment by HighCommander4** [comment]
Please share a complete log that includes what is printed when the file is opened.

**Comment by sheeaza** [comment]
> Please share a complete log that includes what is printed when the file is opened.

Hi, here is the log, that's a little bit mess.
[1.txt](https://github.com/user-attachments/files/16279532/1.txt)

**Comment by HighCommander4** [comment]
The formatting of this log is pretty hard to read, is it possible to obtain it in the first format you posted?

**Comment by HighCommander4** [comment]
Anyways, from what I can see in the log, you don't have a compilation database (`compile_commands.json` file).

Please read through https://clangd.llvm.org/installation#project-setup and follow the instructions there to set up your project, including in particular generating a compilation database file, and see if that helps.

**Comment by sheeaza** [comment]
> The formatting of this log is pretty hard to read, is it possible to obtain it in the first format you posted?

Hi, I got that from coc vim plugin, seems that it parse log into json format.

**Comment by sheeaza** [comment]
> Anyways, from what I can see in the log, you don't have a compilation database (`compile_commands.json` file).
> 
> 
> 
> Please read through https://clangd.llvm.org/installation#project-setup and follow the instructions there to set up your project, including in particular generating a compilation database file, and see if that helps.

The original situation is setup with compilation database file, the compilation flag does not define __linux__, but clangd parse source file as defined.
So I setup above environment with only 1.c file to analyze this issue.

**Comment by sheeaza** [comment]
![image](https://github.com/user-attachments/assets/e1b32993-dbb2-40f4-95dd-598207a9682f)
If I run clangd on windows with vscode, as you can see the `__linux__` is not defined but `_WIN32` is defined, so I guess it is the clangd binary built-in with them.
The above image is just a 1.c file without compilation database.

**Comment by HighCommander4** [comment]
> > The formatting of this log is pretty hard to read, is it possible to obtain it in the first format you posted?
> 
> Hi, I got that from coc vim plugin, seems that it parse log into json format.

If you are using coc.nvim, I assume you are using the [coc-clangd](https://github.com/clangd/coc-clangd) plugin as well?

There are instructions for getting logs from coc-clangd [here](https://clangd.llvm.org/installation#editor-plugins):

> There are two ways to get request/response logs from coc-clangd:
>
>  1.  Set `"clangd.trace.server": "verbose"` in `:CocConfig`, and check the output in `:CocCommand workspace.showOutput clangd`.
>  2.  Set `"clangd.trace.file": "/tmp/clangd.log"`, clangd will output logs to the file.

**Comment by HighCommander4** [comment]
> The original situation is setup with compilation database file

Can you show a log from that original setup?

Clangd is based on clang which has support for a variety of targets. If you are cross-compiling for a non-Linux target, it should be able to parse the code with the right flags for that target, but it needs to know the compile command to figure out that you are compiling for a non-Linux target. If you are falling back to the default compile command, that will target the host environment.

**Comment by sheeaza** [comment]
> > > The formatting of this log is pretty hard to read, is it possible to obtain it in the first format you posted?
> > 
> > 
> > Hi, I got that from coc vim plugin, seems that it parse log into json format.
> 
> If you are using coc.nvim, I assume you are using the [coc-clangd](https://github.com/clangd/coc-clangd) plugin as well?
> 
> There are instructions for getting logs from coc-clangd [here](https://clangd.llvm.org/installation#editor-plugins):
> 
> > There are two ways to get request/response logs from coc-clangd:
> > 
> > 1. Set `"clangd.trace.server": "verbose"` in `:CocConfig`, and check the output in `:CocCommand workspace.showOutput clangd`.
> > 2. Set `"clangd.trace.file": "/tmp/clangd.log"`, clangd will output logs to the file.

Hi, thanks for these tips, the above log is gotten by 2, which is mess.

1. log by workspace: 
[workspace.log](https://github.com/user-attachments/files/16305574/workspace.log)

2. log by clangd trace: 
[clangd.log](https://github.com/user-attachments/files/16305667/clangd.log)

I may not able to upload compile_commands.json, since it contains some company info.

Another thing is, the neovim+coc.vim+clangd is ran in docker and the compiler in compile_commands.json is not runable.

**Comment by sheeaza** [comment]
> Running clangd with `--query-driver=/local/mnt/workspace/project/QXA.QA.6.0.r23-00038-GEN4.QHS.22-1_3/codes/qnx_ap/qnx_bins/prebuilt_QHS220/host/linux/x86_64/usr/lib/gcc/aarch64-unknown-nto-qnx7.1.0/8.3.0/cc1` should allow it to extract the target information from your compiler.

I ran nvim+coc.vim+clangd in docker container, and the `cc1` compiler is under host and the docker container cannot run the `cc1` cmd actually.

I can sure when compiling under host, the `__linux__` macro is not defined by the `cc1` compiler.

**Comment by HighCommander4** [comment]
In that case, you can try providing the target information manually:

 1. Have a look at https://clangd.llvm.org/guides/system-headers#query-driver for the command that `--query-driver` runs. Run the command manually on the host.
 2. Look for "Target:" in the output and take note of the target name. For me, since I'm not doing cross compilation, it's `x86_64-linux-gnu`.
 3. Pass the target name to clangd using a `.clangd` config file:
     ```
     CompileFlags:
       Add: [--target=x86_64-linux-gnu]
     ```
     (replacing `x86_64-linux-gnu` with the target name printed above)

**Comment by sheeaza** [comment]
> CompileFlags:
>   Add: [--target=x86_64-linux-gnu]

Hi, I tried this, it works, so the definition of `__linux__` is due to my clangd cannot query the compiler and then clangd set default target to linux.

Thanks, I will close this issue.
