### ISSUE TITLE
include file jump error

### ISSUE THREAD

**Issue by Qizhi697** [clangd/clangd#2096]
For those header files in the system-level include directory, when `compile_commands.json` cannot generate their paths, how does clangd find them? For example, in the image below, in the file `x86intrin.h`, there is `#include <ia32intrin.h>.` 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/0ca2fe7f-db01-4f78-826f-eb5cec079cf4">
gcc finds `ia32intrin.h` at `/usr/lib/gcc/x86_64-linux-gnu/9/include/ia32intrin.h`, but clangd jumps to `/root/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/18.1.3/clangd_18.1.3/lib/clang/18/include/ia32intrin.h`, causing an error.
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/c7678078-26ca-42af-b52c-13aabaf03421">

**Logs**
```shell
I[14:41:41.405] <-- textDocument/hover(231)
V[14:41:41.405] ASTWorker running Hover on version 1 of /usr/lib/gcc/x86_64-linux-gnu/9/include/x86intrin.h
I[14:41:41.405] --> reply:textDocument/hover(231) 0 ms
V[14:41:41.405] >>> {"id":231,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"### `ia32intrin.h`  \n\n---\n```\n/root/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/18.1.3/clangd_18.1.3/lib/clang/18/include/ia32intrin.h\n```"}}}
```
**System information**

Output of `clangd --version`: 18.1.3
Editor/LSP plugin: vscode+clangd plugin
Operating system: Ubuntu 20.04.6 LTS

**.clangd FILE**
```shell
CompileFlags:
  Add: [
    "-isystem",
    "/usr/include/c++/9",
    "-isystem",
    "/usr/include/x86_64-linux-gnu/c++/9",
    "-isystem",
    "/usr/include/c++/9/backward",
    "-isystem",
    "/usr/lib/gcc/x86_64-linux-gnu/9/include",
    "-isystem",
    "/usr/local/include", 
    "-isystem",
    "/usr/include/x86_64-linux-gnu",
    "-isystem",
    "/usr/include"
  ]
```

**Comment by HighCommander4** [comment]
> For those header files in the system-level include directory, when `compile_commands.json` cannot generate their paths, how does clangd find them? For example, in the image below, in the file `x86intrin.h`, there is `#include <ia32intrin.h>.` <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/78785363/349845977-0ca2fe7f-db01-4f78-826f-eb5cec079cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODkwNjksIm5iZiI6MTcyMTI4ODc2OSwicGF0aCI6Ii83ODc4NTM2My8zNDk4NDU5NzctMGNhMmZlN2YtZGIwMS00Zjc4LTgyNmYtZWI1Y2VjMDc5Y2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNWZiN2E0NWFjYmRjMjI4ZjYzMjQzNzdjMTVmZGE4NTc0YzM4N2ZjMjczZGY1MDIwMmU0Njc1YmY0YmIyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qX4QxslEM1ZY6Xg8bRaEPqXUFNSpac08GPn-1NbqrmU"> gcc finds `ia32intrin.h` at `/usr/lib/gcc/x86_64-linux-gnu/9/include/ia32intrin.h`, but clangd jumps to `/root/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/18.1.3/clangd_18.1.3/lib/clang/18/include/ia32intrin.h`

Clangd is using its own built-in headers, because the built-in headers are closely coupled to the compiler and using a different compiler's built-in headers can cause unexpected behaviour.

You can find some discussion about this at https://github.com/clangd/clangd/issues/1695. (And https://github.com/clangd/clangd/issues/2074 has been filed recently about adding an easy way to force clangd to use a different compiler's built-in headers.)

 > causing an error. <img alt="image" width="1076" src="https://private-user-images.githubusercontent.com/78785363/349846112-c7678078-26ca-42af-b52c-13aabaf03421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODkwNjksIm5iZiI6MTcyMTI4ODc2OSwicGF0aCI6Ii83ODc4NTM2My8zNDk4NDYxMTItYzc2NzgwNzgtMjZjYS00MmFmLWI1MmMtMTNhYWJhZjAzNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDEzMWQ2MmE0YWQzNzEzYWRiZTU3ZTc0MWNkYzA3ZDMxMTRhYjkzOTJhNGExZTRiOGU4ZjkzYmI4MDg0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJbSJ9ssiTEQ--gNrGggl79thiH3XWWYM8CTIKOAGkE">

This particular error is only tangentially related to clangd's choice of built-in headers. The error is caused by the fact that are you opening in the editor a file that is not self-contained and not meant to be included directly (basically, a case of #45).

The error should not show up in your own source file (the file which includes `<x86intrin.h>`).

**Comment by Qizhi697** [comment]
> The error should not show up in your own source file (the file which includes `<x86intrin.h>`).

Thank you very much for your reply. However, in my source file `profile.cc`, when I hover over the red wavy line, the error shown is indeed in the clangd its built-in header `<ia32intrin.h>`.
<img width="771" alt="image" src="https://github.com/user-attachments/assets/4550e249-099a-4cea-a328-21216895fec6">

**Comment by HighCommander4** [comment]
Can you share a log from a clangd session that involves opening `profile.cc`?

**Comment by Qizhi697** [comment]
Here's the log file I captured from clangd at the bottom of VSCode : https://github.com/Qizhi697/matter/blob/main/clangd_plb.md

**Comment by HighCommander4** [comment]
The problem is that you are manually adding back the include `/usr/lib/gcc/x86_64-linux-gnu/9/include` using your `.clangd` file. Try removing it.

Note that all of the `-isystem` flags in your `.clangd` file are unnecessary. `--query-driver` automates adding these include paths for you (other than the `/usr/lib/gcc/...` one, which is purposely skips precisely to avoid these kinds of errors).

**Comment by Qizhi697** [comment]
When I removed the manually added include path `/usr/lib/gcc/x86_64-linux-gnu/9/include` from the `.clangd` file, the errors indeed disappeared. Thank you very much! 

I would like to know if the paths manually added in the `.clangd` file conflict with those automatically searched by `--query-driver` (because they are basically the same). Why can't we manually add those same paths in the .clangd file after setting `--query-driver`?

**Comment by HighCommander4** [comment]
> I would like to know if the paths manually added in the `.clangd` file conflict with those automatically searched by `--query-driver` (because they are basically the same).

They are mostly the same, the only difference is that `--query-driver` skips the gcc built-in include path (`/usr/lib/gcc/x86_64-linux-gnu/9/include`) whereas you included it.

If you also skipped `/usr/lib/gcc/x86_64-linux-gnu/9/include` but included the others, you wouldn't get the error, your `.clangd` file would just kind of be a no-op.

> Why can't we manually add those same paths in the .clangd file after setting `--query-driver`?

Adding `/usr/lib/gcc/x86_64-linux-gnu/9/include` makes clangd, which uses clang's parser, parse the gcc built-in header, which is meant to be parsed by the gcc parser, leading to the error.

**Comment by Qizhi697** [comment]
Another point is that I have already set `--query-driver=/usr/bin/gcc` (as seen in the earlier clangd log [slice]( https://github.com/Qizhi697/matter/blob/main/clangd_plb.md#:~:text=I%5B13%3A46%3A31.695%5D%20argv%5B1%5D%3A%20%2D%2Dquery%2Ddriver%3D/usr/bin/gcc%2C/usr/bin/g%2B%2B)), and I have also set gcc in `/root/.config/clangd/config.yaml` (as shown below). 
```shell
CompileFlags:
  Compiler: /usr/bin/gcc
```

Why does clangd not jump to `/usr/lib/gcc/x86_64-linux-gnu/9/include/x86intrin.h`, but instead jumps to `/root/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/18.1.3/clangd_18.1.3/lib/clang/18/include/x86intrin.h`?

**Comment by HighCommander4** [comment]
> Why does clangd not jump to `/usr/lib/gcc/x86_64-linux-gnu/9/include/x86intrin.h`, but instead jumps to `/root/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/18.1.3/clangd_18.1.3/lib/clang/18/include/x86intrin.h`?

Well, since are avoiding adding `/usr/lib/gcc/x86_64-linux-gnu/9/include` to clangd's include path, files in that directory will not be found by clangd.

**Comment by Qizhi697** [comment]
Thank you very much for your guidance.
