### ISSUE TITLE
Clangd crashes consistently 

### ISSUE THREAD

**Issue by phonenaing05** [clangd/clangd#2101]
**Problem**
I'm using VS code clangd plugin. It has been working fine on our code repo, recently it started breaking - clangd crashes consistently even with parameters "-j=1 and --background-index=false"

I'm running VS Code on Windows system, ssh into the remote build server for repo access.

**Logs**
[clangd-log.txt](https://github.com/user-attachments/files/16360908/clangd-log.txt)

**System information**
_xxx@dbs-xxxx-04:/usr/include$ lscpu
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 32
Socket(s):                          2
NUMA node(s):                       8
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              1
Model name:                         AMD EPYC 7551 32-Core Processor
Stepping:                           2
Frequency boost:                    enabled
CPU MHz:                            1195.978
CPU max MHz:                        2000.0000
CPU min MHz:                        1200.0000
BogoMIPS:                           3992.30
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          4 MiB
L2 cache:                           32 MiB
L3 cache:                           128 MiB_

**Output of `clangd --version`:**
_Using this clangd plug-in version: 0.1.29_

**Editor/LSP plugin:**
VS Code

**Operating system:**
_NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"_

**Comment by HighCommander4** [comment]
From the log, the crash is caused by this assertion failure:

> tools/clang/include/clang/AST/AbstractBasicReader.inc:722: clang::APValue clang::serialization::BasicReaderBase<T>::readAPValue() [with Impl = clang::ASTRecordReader]: Assertion `lvaluePath->getType() == elemTy && "Unexpected type reference!"' failed.

This assertion has been removed in clangd 16 and later (https://github.com/llvm/llvm-project/commit/2009f2450532450a99c1a03d5e2c30f478121839).

Based on the log, you are using clangd 14.

==> Upgrading to clangd 16 or later should fix the crash.

Up to date clangd release packages can be found at https://github.com/clangd/clangd/releases.

**Comment by phonenaing05** [comment]
Thanks, I will give it a try.

**Comment by phonenaing05** [comment]
Updating to clangd16 resolved the crash. Thank you!
