### ISSUE TITLE
fails to properly read compilation database for system headers

### ISSUE THREAD

**Issue by xave** [clangd/clangd#2111]
I have a simple objective-c test file `main.m`.

```
// main.m
#include <Foundation/Foundation.h>

void myfunc() { NSLog(@"From my func"); }

int main(int argc, const char *argv[]) {
  NSLog(@"Hello world");
  myfunc();
  return 0;
}

```

The functionality of jumping to definitions, declarations, etc is fine for functions and objects that I define myself, however;  `NSLog` information is incomplete and inaccurate. For instance, jumping to definition on the `"Hello world"` call jumps to the call in `myFunc()`. Expected behavior is that it would jump to definition in the `Foundation` header.

Running the command:
`clang -MJ main.json  -framework Foundation -isysroot $(xcrun --show-sdk-path) main.m -o app`

**Logs**

**System information**

Output of `clangd --version`:
```
clangd version 14.0.6
Features: mac
Platform: aarch64-apple-darwin23.5.0
```

Editor/LSP plugin: vim-lsp

Operating system: macOS

**Comment by HighCommander4** [comment]
Please attach [clangd logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs).

It's also worth trying with a newer clangd version (they can be downloaded from https://github.com/clangd/clangd/releases), 14.0 is a couple of years old by now.

**Comment by xave** [comment]
logs attached:
[log.txt](https://github.com/user-attachments/files/16517038/log.txt)

**Comment by HighCommander4** [comment]
> logs attached: [log.txt](https://github.com/user-attachments/files/16517038/log.txt)

This is not a clangd log. This looks like something output by `clang`, not `clangd`.

Clangd logs are what clangd prints to its stderr while you are using it (e.g. while you are opening the file `main.m`). They are typically exposed by the editor (the exact method varies from one editor to another).

**Comment by xave** [comment]
I'm just using `ctags`. If someone could post an example command for this minimal example, that would help others.
