### ISSUE TITLE
Nested dependent name does not get a semantic highlighting

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#214]
In the following code:

```
template <typename T>
struct waldo {
  using location = typename T::resolver::location;  // <-- 
};
```

on the indicated line, `resolver` does not get a semantic highlighting.

**Comment by sam-mccall** [comment]
Isn't this appropriate?
A dependent name is an identifier with unknown meaning. The editor should highlight it as a generic identifier. This is what happens if clangd provides no style.

**Comment by HighCommander4** [comment]
We have a `DependentName` highlighting kind for dependent names. For example, that's what `location` in the above example gets.

**Comment by HighCommander4** [comment]
Err, sorry, we have `DependentType` for dependent types and `DependentName` for dependent non-types. `location` is a `DependentType`, `resolver` should be as well.

That provides more information than leaving them uncolored, since we distinguish between types and non-types.

**Comment by HighCommander4** [comment]
Having semantic colors for dependent names also helps distinguish "this is confirmed to be a dependent name" vs. "this is a place where we have an incomplete AST / a clangd bug / etc.".

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D70746)
