### ISSUE TITLE
The official release for Windows is configured to work with msvc only

### ISSUE THREAD

**Issue by Curculigo** [clangd/clangd#2155]
### Discussed in https://github.com/clangd/clangd/discussions/2118

Please have a look at https://github.com/mstorsjo/llvm-mingw/issues/454.

**Comment by HighCommander4** [comment]
Clangd looks for MSVC system headers by default, but you can use `--query-driver` (discussed at https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc and in more detail at https://clangd.llvm.org/guides/system-headers#query-driver) to point it to the system headers of a gcc installation, including mingw.
