### ISSUE TITLE
--experimental-modules-support doesen't seem to exist

### ISSUE THREAD

**Issue by cool-cose** [clangd/clangd#2163]
I've been trying to use c++ modules for my current project, so i heard that clangd had experimental but still some sort of implementation of support for modules.

right [here](https://clangd.llvm.org/features#experimental-c20-modules-support) it says that to enable modules support you have to use the --experimental-modules-support option. But this option seems to not even exist, when in vscode i add it to the clangd arguments i get this:

clangd.exe: Unknown command line argument '--experimental-modules-support'.  Try: 'C:/msys64/mingw64/bin/clangd.exe --help'
clangd.exe: Did you mean '--print-all-options'?
[Info  - 3:27:31 PM] Connection to server got closed. Server will restart.
[Error - 3:27:31 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 3:27:31 PM] Clang Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097

Output of `clangd --version`:
  clangd version 18.1.8
  Features: windows
  Platform: x86_64-w64-windows-gnu

Editor/LSP plugin:
  Official VS Code Clangd Extension

Operating system:
  windows 11

**Comment by cool-cose** [comment]
THat did seem to fix at least that! i was lucky to find a precompiled binary for clangd 19 because it doesent seem like theres any precompiled binaries for clang 19, but now im running into a different issue. clangd complains about an older unsupported PCH version on import statement, i'm not even sure what PCH has to do with modules.

my best guess would be the mismatch between the clangd version and the clang version?

Im unsure if i should open a new issue over this or if i should keep it in this issue.
If it would be good practice for me to open a new issue please let me know.

**Comment by HighCommander4** [comment]
> Im unsure if i should open a new issue over this or if i should keep it in this issue.

I think your issue will be more discoverable if reported in a dedicated issue with its own description.

**Comment by cool-cose** [comment]
ok! thanks for the help!!
