### ISSUE TITLE
Support InlineValue protocol for constexpr values

### ISSUE THREAD

**Issue by torshepherd** [clangd/clangd#2175]
LSP 3.17 introduced ["Inline Value Request"](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlineValue), whereby the client requests inline values in a document to be rendered at the end of the line (sort of like how error lens or gitlens display things I guess? Not sure since this is new to me).

This seems like it could pair well with C++'s constexpr interpretation. We already show some simple compile-time-known values on hover; a first MVP could probably just expose the same information as a response to an `inlineValues` request.

Challenges I think this could raise:
- I haven't looked carefully but IIRC constexpr hover values are computed upon individual request, not globally. If `vscode` requests inline values all at once at document load/refresh, this could severely impact load times on first-document-open. Though it strikes me, if this is a separate request, then it could be done in a worker thread and not block normal usage of clangd. Big documents could just receive the values response sometime later.
- IIRC `clangd` currently has a bespoke way of performing a limited set of constant folding, but we don't for instance evaluate constexpr function calls. Ideally it would be nice to eventually support _all_ constant evaluation for this feature so that C++ developers have the superpower of seeing all the constexpr results in their editor as they type. However constant evaluation is notoriously slow in both clang and GCC for now, and will probably be infeasible without JITting constexpr functions (probably well out of scope of clangd at this point)

**Comment by torshepherd** [comment]
Note also that this might be an abuse of this feature. I think from looking at examples the `inlineValues` capability is _intended_ to be used with scripting languages to run and show results immediately in the editor

**Comment by 16bit-ykiko** [comment]
This feature should be used to display runtime value of variablewhen debug. Displaying constant expression is not a good idea.

**Comment by torshepherd** [comment]
That's fair, probably can close this. Though if we ever integrate clang-repl this would be neat
