### ISSUE TITLE
when try to use code action to fix the function pointer not initialized problem, clang-tidy add `=nullptr` to the wrong place

### ISSUE THREAD

**Issue by LXYan2333** [clangd/clangd#2179]
# Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

when try to use code action to fix the function pointer not initialized problem, clang-tidy add `=nullptr` to the wrong place.

# If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

```cpp
int main() {
    void(*f)(void*);
}
```

clang-tidy suggest to initialize it:

![image](https://github.com/user-attachments/assets/fb4b22e6-3716-4b40-85f0-6ec473b7cd2a)

but it add `=nullptr` to a wrong location:

![image](https://github.com/user-attachments/assets/c3525baf-5d3e-4083-9de6-8467a3b94cba)

expect behaviour:

```cpp
int main() {
    void(*f )(void*)=nullptr;
}
```

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

not necessary

**System information**

Output of `clangd --version`:

```console
$ clangd-19 --version
Debian clangd version 19.1.2 (++20241001023520+d5498c39fe6a-1~exp1~20241001143639.51)
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:

vscode 1.94.2
clangd plugin: v0.1.29

Operating system:
Debian 12 stable

**Comment by torshepherd** [comment]
I think this is an upstream clang-tidy bug, not clangd

**Comment by LXYan2333** [comment]
> @LXYan2333 please report this upstream at https://github.com/llvm/llvm-project/issues.

thanks.

https://github.com/llvm/llvm-project/issues/112089
