### ISSUE TITLE
Can't rename things in anon namespace

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#218]
Given `namespace { void foo(); }`
Renaming foo fails: "Cannot rename symbol: symbol may be used in other files (not eligible for indexing"

`static void foo()` in the global namespace works, so I think we just need to teach the heuristics about anonymous namespaces.

**Comment by hokein** [comment]
This should be fixed in https://github.com/llvm/llvm-project/commit/902dc6c69ce7985427efa103a7c4099c372da6fa, I just committed it this morning.
