### ISSUE TITLE
clangd does not find C++ header <coroutine> despite correct query-driver and include path

### ISSUE THREAD

**Issue by infogrind** [clangd/clangd#2183]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

I am using clang in neovim on MacOS through the nvim-lsp plugin. Clangd cannot find the `<coroutine>` header file, manifested by this line:
```
#include <coroutine>     ● 'coroutine' file not found
```

In my configuration I have passed the argument `--query-driver=/usr/local/opt/llvm/**`, which is where my clang (installed with homebrew) is included.

In the `lsp.log` file created by `nvim-lsp`, I see that the correct include paths are found. Excerpt from the log:
```
I[17:05:46.152] System includes extractor: successfully executed /usr/local/opt/llvm/bin/clang
	got includes: "/usr/local/Cellar/llvm/19.1.1/bin/../include/c++/v1, /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include, /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks (framework directory)"
	got target: "x86_64-apple-darwin20.6.0"
```

I validated that the `coroutine` include file exists under the first directory in the listed include path:
```
$ stat /usr/local/Cellar/llvm/19.1.1/bin/../include/c++/v1/coroutine
16777220 8745862388 -rw-r--r-- 1 xxxxxx admin 0 1908 "Oct  5 14:51:37 2024" "Oct  1 14:08:12 2024" "Oct  5 17:17:09 2024" "Oct  1 14:08:12 2024" 4096 8 0 /usr/local/Cellar/llvm/19.1.1/bin/../include/c++/v1/coroutine
```

I have also set the C++20 standard in `compile_flags.txt` in my project directory:
```
$ cat compile_flags.txt
-std=c++20
-Wall
```

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

```
#include <coroutine>
```

**Logs**

See https://gist.github.com/infogrind/34140c9d60e2787e59e06512eca46ea9 for full log (with `--log=verbose`).

**System information**

Output of `clangd --version`: Homebrew clangd version 19.1.1

Editor/LSP plugin: Neovim  nvim-lsp

Operating system: MacOS 11.7.10

**Comment by HighCommander4** [comment]
> In the `lsp.log` file created by `nvim-lsp`, I see that the correct include paths are found. Excerpt from the log:
> 
> ```
> I[17:05:46.152] System includes extractor: successfully executed /usr/local/opt/llvm/bin/clang
> 	got includes: "/usr/local/Cellar/llvm/19.1.1/bin/../include/c++/v1, /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include, /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks (framework directory)"
> 	got target: "x86_64-apple-darwin20.6.0"
> ```

I do see this in the log, but further down I see this:

> I[17:05:46.153] Loaded compilation database from /Users/marius/github/experiments/cc_coroutines/compile_flags.txt
> V[17:05:46.153] Broadcasting compilation database from /Users/marius/github/experiments/cc_coroutines
> V[17:05:46.153] System include extraction: not allowed driver /Users/marius/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/bin/clang-tool
> I[17:05:46.153] ASTWorker building file /Users/marius/github/experiments/cc_coroutines/main.cc version 0 with command 
> [/Users/marius/github/experiments/cc_coroutines]
> /Users/marius/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/bin/clang-tool -std=c++23 -Wall -resource-dir=/Users/marius/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/lib/clang/18 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -- /Users/marius/github/experiments/cc_coroutines/main.cc

and it's this run of the system include extractor that's actually used for the `main.cc`. (I'm not quite sure what triggers the earlier run of the system include extractor which succeeds.)

Anyways, the important part is:

> V[17:05:46.153] System include extraction: not allowed driver /Users/marius/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/bin/clang-tool

which tells us that the compiler driver path that clangd is actually using for this file is `/Users/marius/.local/share/nvim/mason/packages/clangd/clangd_18.1.3/bin/clang-tool`, which does not match the pattern allowlisted in `--query-driver`.

As for where this path comes from, I guess it's a default driver path that clangd comes up with based on its own (clangd's) executable path, in cases where it doesn't have a `compile_commands.json` file to get an actual driver path from.

You could fix this by creating a `.clangd` config file in your project root containing:

```yaml
CompileFlags:
  Compiler: /usr/local/opt/llvm/bin/clang
```

which overrides the driver path clangd will use.

In the longer term though, I would recommend migrating from `compile_flags.txt` to `compile_commands.json` (in which case clangd should get the actual compiler driver's path, e.g. `/usr/local/opt/llvm/bin/clang`, from the argv[0] of the commands in `compile_commands.json`).

**Comment by infogrind** [comment]
Thanks a lot Nathan. With this info, I could solve it differently – just used an absolute path to my system clangd in the nvim-lsp config.
