### ISSUE TITLE
Add IgnoreMacros option to readability-function-size

### ISSUE THREAD

**Issue by adambadura** [clangd/clangd#2188]
Add `IgnoreMacros` option to `readability-function-size` check to mimic the same in `readability-function-cognitive-complexity`.

Counting the function size with expanded macros will make it more likely to break limits. Whereas macros are more like function calls regarding the readability.

**Comment by HighCommander4** [comment]
This is an enhancement to a clang-tidy checker, kindly file it at https://github.com/llvm/llvm-project/issues/

**Comment by adambadura** [comment]
Done: https://github.com/llvm/llvm-project/issues/112835 - thanks an sorry!
