### ISSUE TITLE
Clangd 19.1.0 сonstant loading of one CPU core per 100%

### ISSUE THREAD

**Issue by KofTD** [clangd/clangd#2189]
After the first access to the clangd server, its process loads one of the cores up to 100%. At this time, it does not respond to requests to rename variables or code actions at all. There is no such problem on clangd version 18.1.3

```c
int make_correct_guess(int length) {
  srand(time(NULL));

  int rand_slice = 100;

  for (int i = 0; i < length; i++) {
    rand_slice *= 10;
  }

  int guess = rand() % rand_slice + 1;

  return guess;
}
```

In this function, I want to rename the variable "rand_slice" to "rand_size". After that, the above problem appears.

**Logs**
[ERROR][2024-10-21 19:47:44] .../vim/lsp/rpc.lua:770    "rpc"   "/home/daniel/.local/share/nvim/mason/bin/clangd"   "stderr"    "I[19:47:44.505] Failed to find compilation database for /home/daniel/university/lab4/lab.c\n"
[ERROR][2024-10-21 19:47:44] .../vim/lsp/rpc.lua:770    "rpc"   "/home/daniel/.local/share/nvim/mason/bin/clangd"   "stderr"    "V[19:47:44.507] Reusing preamble version 0 for version 6 of /home/daniel/university/lab4/lab.c\n

**System information**

Output of `clangd --version`:
clangd version 19.1.0 (https://github.com/llvm/llvm-project a4bf6cd7cfb1a1421ba92bca9d017b49936c55e4)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:

- Editor: Nvim
- Config: Nvchad
- Plugin: lspconfig

Operating system:
Manjaro Linux (Linux 6.10.13-3-MANJARO), GNOME 46

**Comment by HighCommander4** [comment]
It would be interesting to attach a debugger (e.g. gdb) to the clangd process and get a stack trace during the 100% cpu usage.

**Comment by KofTD** [comment]
After a while, the problem disappeared
