### ISSUE TITLE
Clangd crash when use forward declaration as member reference variable

### ISSUE THREAD

**Issue by lingege321** [clangd/clangd#2194]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

The following code will cause the segmentation fault.
Crash is a forward declaration, and Der struct have the reference to it.
```
struct Crash;

struct Der {
  Der(Crash& d):d{d}{}
  Crash& d;
};
```

 #0 0x00000000006b780b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/u/chielin/local/clangd/clangd/bin/clangd+0x6b780b)
 #1 0x00000000006b503b SignalHandler(int) Signals.cpp:0:0
 #2 0x00007ffff7bc2b20 __restore_rt sigaction.c:0:0
 #3 0x000000000478b451 clang::tidy::modernize::(anonymous namespace)::internal::matcher_isAggregateMatcher::matches(clang::CXXRecordDecl const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const UseDesignatedInitializersCheck.cpp:0:0
 #4 0x00000000052b47ad clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b47ad)
 #5 0x00000000052b49ed clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&clang::ast_matchers::internal::allOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>)>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
 #6 0x00000000052b8634 clang::ast_matchers::internal::(anonymous namespace)::IdDynMatcher::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
 #7 0x00000000052b45fe clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b45fe)
 #8 0x0000000001b55851 clang::ast_matchers::internal::HasDeclarationMatcher<clang::QualType, clang::ast_matchers::internal::Matcher<clang::Decl>>::matchesDecl(clang::Decl const*, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x1b55851)
 #9 0x00000000052b45fe clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b45fe)
#10 0x000000000478d226 clang::ast_matchers::internal::matcher_hasType1Matcher<clang::InitListExpr, clang::ast_matchers::internal::Matcher<clang::Decl>>::matches(clang::InitListExpr const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x478d226)
#11 0x00000000052b47ad clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b47ad)
#12 0x00000000052b49d4 clang::ast_matchers::internal::(anonymous namespace)::VariadicMatcher<&clang::ast_matchers::internal::allOfVariadicOperator(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*, llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher>)>::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#13 0x00000000052b8634 clang::ast_matchers::internal::(anonymous namespace)::IdDynMatcher::dynMatches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const ASTMatchersInternal.cpp:0:0
#14 0x00000000052b45fe clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b45fe)
#15 0x0000000004358038 clang::ast_matchers::internal::TraversalMatcher<clang::Stmt>::matches(clang::Stmt const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x4358038)
#16 0x00000000052b45fe clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const (/u/chielin/local/clangd/clangd/bin/clangd+0x52b45fe)
#17 0x000000000528d582 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) ASTMatchFinder.cpp:0:0
#18 0x00000000052a7d4e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*>>>>*) (.constprop.0) ASTMatchFinder.cpp:0:0
#19 0x00000000052abb69 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) ASTMatchFinder.cpp:0:0
#20 0x00000000052b0c63 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseCXXConstructorDecl(clang::CXXConstructorDecl*) ASTMatchFinder.cpp:0:0
#21 0x00000000052a3c6b clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#22 0x00000000052a3d6a clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDeclContextHelper(clang::DeclContext*) ASTMatchFinder.cpp:0:0
#23 0x00000000052a2a81 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#24 0x00000000052a3c6b clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#25 0x00000000052b0aad clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) ASTMatchFinder.cpp:0:0
#26 0x00000000052a3c6b clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#27 0x00000000052a3f98 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) (/u/chielin/local/clangd/clangd/bin/clangd+0x52a3f98)
#28 0x0000000001b54869 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/u/chielin/local/clangd/clangd/bin/clangd+0x1b54869)
#29 0x0000000001bd693b clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, clang::clangd::ParseInputs, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag>>) TUScheduler.cpp:0:0
#30 0x0000000001bd7357 clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag>>, clang::clangd::WantDiagnostics)::'lambda'()::operator()() (.part.0) TUScheduler.cpp:0:0
#31 0x0000000001bd0aee clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void ()>) (.constprop.0) TUScheduler.cpp:0:0
#32 0x0000000001bd0e9e clang::clangd::(anonymous namespace)::ASTWorker::run() TUScheduler.cpp:0:0
#33 0x0000000001da6317 void* llvm::thread::ThreadProxy<std::tuple<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::'lambda0'()>>(void*) Threading.cpp:0:0
#34 0x00007ffff7bb814a start_thread pthread_create.c:0:0
#35 0x00007ffff660edc3 clone (/lib64/libc.so.6+0xfcdc3)

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:
clangd version 19.1.2 (https://github.com/llvm/llvm-project.git 7ba7d8e2f7b6445b60679da826210cdde29eaf8b)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
VScode - Clangd v0.1.29

Operating system:
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: AlmaLinux
Description:    AlmaLinux release 8.4 (Electric Cheetah)
Release:        8.4
Codename:       ElectricCheetah

**Comment by HighCommander4** [comment]
Please share a complete [clangd log](https://clangd.llvm.org/troubleshooting.html#gathering-logs), as well as the contents of any relevant config files such as `.clangd` or `.clang-tidy`.

**Comment by lingege321** [comment]
Hi @HighCommander4 
Thanks for your hint...
It's related to clang-tidy.
If I turn on the modernize-use-designated-initializers option and it get crash.


I will file an issue to clang-tidy. 
Thank you
