### ISSUE TITLE
Report index progress in BackgroundIndex

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#22]
Would be nice to emit messages like `[number of processed files/number of total files] Indexing file ....`.

**Comment by hokein** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/7d20e80225b3e4f3f5a8c57929061bef55f3d855.

**Comment by EvanHonnold** [comment]
I stumbled over this Issue while trying to figure out how to view the background index's status in Remote VS Code.  Is this possible? Thank you for any help!

**Comment by hokein** [comment]
Yeah, it is possible either in local or remote VSCode.

If the background indexing is being built, you should be able to see the progress in the VSCode status bar.

![image](https://user-images.githubusercontent.com/2557445/78757065-290f5e00-797c-11ea-8e9f-b5a22bfd99b8.png)

The tricky part is that if the indexing is finished, the progressing item on status bar will be disappeared, this is not ideal though. So if you don't see the progressing  item, you can assume the background indexing is finished.
