### ISSUE TITLE
Respect custom `editsNearCursor` capability being set on `capabilities.experimental` object

### ISSUE THREAD

**Issue by rchl** [clangd/clangd#2201]
Clangd supports custom client capability `textDocument.completion.editsNearCursor` ([source](https://searchfox.org/llvm/source/clang-tools-extra/clangd/Protocol.cpp#418)).

According to the LSP spec, the custom/experimental capabilities should be exposed on the root `experimental` object:

> [ClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) define capabilities for dynamic registration, workspace and text document features the client supports. **The `experimental` can be used to pass experimental capabilities under development.**

```
interface ClientCapabilities {
        // ...
	/**
	 * Experimental client capabilities.
	 */
	experimental?: LSPAny;
}
```

Sublime Text LSP client currently follows the spec so it's not straightforward to expose a custom capability like that within the standard capabilities.

I would like to request that clangd also checks for the `editsNearCursor` client capability somewhere within the `experimental` object - either `experimental.editsNearCursor` or `experimental.completion.editsNearCursor` or a variant of that.

See also the corresponding issue in the vscode clangd extension repo - https://github.com/clangd/vscode-clangd/issues/714

**Comment by HighCommander4** [comment]
Proposed fix: https://github.com/llvm/llvm-project/pull/114699

**Comment by av1934413** [comment]
> Clangd supports custom client capability `textDocument.completion.editsNearCursor` ([source](https://searchfox.org/llvm/source/clang-tools-extra/clangd/Protocol.cpp#418)).
> 
> According to the LSP spec, the custom/experimental capabilities should be exposed on the root `experimental` object:
> 
> > [ClientCapabilities](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) define capabilities for dynamic registration, workspace and text document features the client supports. **The `experimental` can be used to pass experimental capabilities under development.**
> 
> ```
> interface ClientCapabilities {
>         // ...
> 	/**
> 	 * Experimental client capabilities.
[Uploading Alphabet - Wikipedia.pdf…]()

> 	 */
> 	experimental?: LSPAny;
> }
> ```
> 
> Sublime Text LSP client currently follows the spec so it's not straightforward to expose a custom capability like that within the standard capabilities.
> 
> I would like to request that clangd also checks for the `editsNearCursor` client capability somewhere within the `experimental` object - either `experimental.editsNearCursor` or `experimental.completion.editsNearCursor` or a variant of that.
> 
> See also the corresponding issue in the vscode clangd extension repo - [clangd/vscode-clangd#714](https://github.com/clangd/vscode-clangd/issues/714)
