### ISSUE TITLE
How to change the path for preambles

### ISSUE THREAD

**Issue by timxx** [clangd/clangd#2213]
On Windows, it default to %TEMP%. clangd will generate lots of preamble pch files, and eat up of the rest disk space for me.
So, is it possible to store the preamble to another path, such as the clangd cache directory?

**Comment by HighCommander4** [comment]
A current supported way is to change the value of the `TEMP` (Windows) or `TMPDIR` (Unix) environment variable.

https://github.com/clangd/clangd/issues/255 is on file about customizing without changing those.

**Comment by timxx** [comment]
> A current supported way is to change the value of the `TEMP` (Windows) or `TMPDIR` (Unix) environment variable.
> 
> #255 is on file about customizing without changing those.

That's a workaround LoL
