### ISSUE TITLE
Gives an error for operator!= between two std::reverse_iterator with a custom stash-iterator, but clang builds it, with no problem

### ISSUE THREAD

**Issue by yodho1psnrls** [clangd/clangd#2224]
Please describe the problem.
I just implemented a custom stash iterator that stores an unsigned integer index
When i use comparison operator!= between two std::reverse_iterator<index_handle>, clang compiles it, but clangd displays an error:
"Invalid operands to binary expression ('std::reverse_iterator<index_handle>' and 'std::reverse_iterator<index_handle>')"

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

-------------------------------------------------------------- handles.h -------------------------------------------------------
```cpp
#pragma once
#include <iterator>
#include <type_traits>

#ifndef uint
typedef unsigned int uint;
#endif

class index_handle {
  uint _id;

public:
  using iterator_category = std::contiguous_iterator_tag;
  using difference_type = int;
  using value_type = uint;
  using pointer = value_type*;   // or also value_type*
  using const_pointer = const value_type*;
  using reference = value_type&; // or also value_type&
  using const_reference = const value_type&;

  static const uint INVALID_INDEX = -1;

  index_handle() : _id(INVALID_INDEX) {}
  explicit index_handle(const uint id) : _id(id) {}

  explicit index_handle(const std::reverse_iterator<index_handle>& it)
    : index_handle(it.base()){}
  
  operator std::reverse_iterator<index_handle>() const {
    return std::reverse_iterator<index_handle>(*this);
  }

  reference operator*() { return _id; }
  const_reference operator*() const { return _id; }  
  pointer operator->() { return &_id; }
  const_pointer operator->() const { return &_id; }
  value_type operator[](const int id) const { return _id + id; }

  index_handle& operator++() { ++_id; return *this; }
  index_handle& operator--() { --_id; return *this; }
  index_handle operator++(int) { auto temp(*this); ++(*this); return temp; }
  index_handle operator--(int) { auto temp(*this); --(*this); return temp; }
  
  template <typename diff_type = uint>
  typename std::enable_if<std::is_integral_v<diff_type>, index_handle&>::type
  operator+=(const diff_type n) { _id += n; return *this; }
  
  template <typename diff_type = uint>
  typename std::enable_if<std::is_integral_v<diff_type>, index_handle&>::type
  operator-=(const diff_type n) { _id -= n; return *this; }
  
  template <typename diff_type = uint>
  typename std::enable_if<std::is_integral_v<diff_type>, index_handle>::type
  operator+(const diff_type n) const { auto temp(*this); return temp += n; }
  
  template <typename diff_type = uint>
  typename std::enable_if<std::is_integral_v<diff_type>, index_handle>::type
  operator-(const diff_type n) const { auto temp(*this); return temp -= n; }


  // Comparison operators
  bool operator==(const index_handle& other) { return _id == other._id; }
  bool operator!=(const index_handle& other) { return _id != other._id; }
  bool operator>(const index_handle& other) { return _id > other._id; }
  bool operator>=(const index_handle& other) { return _id >= other._id; }
  bool operator<(const index_handle& other) { return _id < other._id; }
  bool operator<=(const index_handle& other) { return _id <= other._id; }

};
```
------------------------------------------------------------ main.cpp ---------------------------------------------------------------------
```cpp
#include <iostream>
#include "handles.h"

int main() {

  index_handle beg(0);
  index_handle end(15);
  
  std::reverse_iterator<index_handle> rbeg = end;
  std::reverse_iterator<index_handle> rend = beg;
  
  // Error: Invalid operands to binary expression ('std::reverse_iterator<index_handle>' and 'std::reverse_iterator<index_handle>')
  for(auto it = rbeg; it != rend; ++it)
    std::cout << *it << "\n";

  return 0;
}
```
---------------------------------------------------------------------------------------------------------------------------------------

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:
clangd version 19.1.0 (https://github.com/llvm/llvm-project a4bf6cd7cfb1a1421ba92bca9d017b49936c55e4)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc
(note that i just updated it, from clangd 18.1.3, to check if it is fixed)

Output of `clang --version`:
clang version 18.1.8
Target: x86_64-w64-windows-gnu
Thread model: posix

Editor/LSP plugin: neovim/lsp-config

Operating system: Windows 10

**Comment by HighCommander4** [comment]
I can't reproduce this on Linux.

Could you share [clangd logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs) please?

**Comment by yodho1psnrls** [comment]
I cleaned up my log file, then i set_log_level("trace") in my lsp-config configuration, opened the example once, and this is the result.
[lsp.log](https://github.com/user-attachments/files/17868692/lsp.log)

**Comment by HighCommander4** [comment]
Could you share logs with `--log=verbose` in clangd's arguments?

**Comment by yodho1psnrls** [comment]
lspconfig.clangd.setup {
          cmd = { "clangd", "--background-index", "--log=verbose" }
}
[lsp.log](https://github.com/user-attachments/files/17879563/lsp.log)

**Comment by yodho1psnrls** [comment]
Okay, i checked the lsp.log and saw that there are a lot of boilerplate comments and other things, because it is a project with a lot of other non-related files and comments, and i just created a new absolutely minimal project with only the files i gave for the example above, and now, i dont see this error showing up, but i constrantly get an error message from neovim that says:
"lsp_signatur handler RPC[Error] code_name = InvalidParams, message = "trying to get preamble for non-added document""

**Comment by HighCommander4** [comment]
Thanks. Could you also share the output of `clang -v -x c++ -E -` (run in the same shell where you would run clang to compile the project)?

**Comment by yodho1psnrls** [comment]
Note that you will see different clang version than the one that, i specified initially, because i updated it like two days ago.

Microsoft Windows [Version 10.0.19045.5131]
(c) Microsoft Corporation. All rights reserved.

D:\vim_test\GitHubClangdIssueMinimalProject>clang -v -x c++ -E -
clang version 19.1.4
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Program Files/MSYS2/mingw64/bin
 (in-process)
 "D:/Program Files/MSYS2/mingw64/bin/clang.exe" -cc1 -triple x86_64-w64-windows-gnu -E -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name -
 -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -mms-bitfields -funwind-tables=2 -fno-sized-deallocation -f
no-use-init-array -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=D:/vim_test/GitHubClangdIssueMinimalProject -v -fcoverage-compilation-dir=D:/vim_test/Gi
tHubClangdIssueMinimalProject -resource-dir "D:/Program Files/MSYS2/mingw64/lib/clang/19" -internal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++" -internal-isyste
m "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32" -internal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/backward" -internal-is
ystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0" -internal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0/x86_64-w64-mingw32" -in
ternal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0/backward" -internal-isystem "D:/Program Files/MSYS2/mingw64/include/c++/14.2.0" -internal-isystem "D:/P
rogram Files/MSYS2/mingw64/include/c++/14.2.0/x86_64-w64-mingw32" -internal-isystem "D:/Program Files/MSYS2/mingw64/include/c++/14.2.0/backward" -internal-isystem "D:/Program Files/MSYS2/m
ingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++/x86_64-w64-mingw32" -internal-isystem 
"D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++/backward" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.
2.0" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2.0/x86_64-w64-mingw32" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x
86_64-w64-mingw32/14.2.0/include/g++-v14.2.0/backward" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2" -internal-isystem "D:/Program 
Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2/x86_64-w64-mingw32" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-
v14.2/backward" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mi
ngw32/14.2.0/include/g++-v14/x86_64-w64-mingw32" -internal-isystem "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14/backward" -internal-isystem "D:/Program
 Files/MSYS2/mingw64/lib/clang/19/include" -internal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include" -internal-isystem "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw3
2/usr/include" -internal-isystem "D:/Program Files/MSYS2/mingw64/include" -fdeprecated-macro -ferror-limit 19 -fmessage-length=188 -femulated-tls -fno-use-cxa-atexit -fgnuc-version=4.2.1 -
fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -exception-model=seh -fcolor-diagnostics -faddrsig -o - -x c++ -
clang -cc1 version 19.1.4 based upon LLVM 19.1.4 default target x86_64-w64-windows-gnu
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include/c++/14.2.0/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/c++/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2.0"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2.0/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2.0/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14.2/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14/x86_64-w64-mingw32"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/lib/gcc/x86_64-w64-mingw32/14.2.0/include/g++-v14/backward"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/include"
ignoring nonexistent directory "D:/Program Files/MSYS2/mingw64/x86_64-w64-mingw32/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 D:/Program Files/MSYS2/mingw64/include/c++/14.2.0
 D:/Program Files/MSYS2/mingw64/include/c++/14.2.0/x86_64-w64-mingw32
 D:/Program Files/MSYS2/mingw64/include/c++/14.2.0/backward
 D:/Program Files/MSYS2/mingw64/lib/clang/19/include
 D:/Program Files/MSYS2/mingw64/include
End of search list.

**Comment by HighCommander4** [comment]
Ok, so what I'm seeing here is that the compiler (clang) is using one standard library implementation (libstdc++), and clangd is using a different one (msvc).

This at least potentially provides an explanation for why the two produce different results (no error vs. error).

The usual fix in such cases is to get clangd to use the same standard library headers as the compiler. The easier way to do this is to use clangd's [query-driver](https://clangd.llvm.org/guides/system-headers#query-driver) feature.

Can you try adding `"--query-driver=D:\Program Files\MSYS2\mingw64\bin\clang++.exe"` to clangd's arguments (the same place where you added `"--log=verbose"`) and see if that resolves the error? (If not, please share updated logs with that argument added.)

**Comment by yodho1psnrls** [comment]
Hmm, this makes a lot of sense, i have clang installed through msys2 mingw and i knew that it also has its own standard library implementation installed there, but with clangd when i hover over an std header file it shows the MSVC path, and i thought that clang also uses those for compilation. So it turns out that they use different standard library.

**Comment by yodho1psnrls** [comment]
Yep, that fixed the problem, it now loads std from MSYS2 mingw and i see no Error Message.
![image](https://github.com/user-attachments/assets/ace41f8c-0580-478b-b648-c5ac2e5d0afd)
Thank you for your time sir ! I really appreciate it.
The name of the Issue is very specific, but as it turned out, the problem solution is more generic than that. Should i edit the name, or do something so more people find the solution to a similar issue ?

Oh, and one last thing. Is it possible to not hard code the exact path to clang here, but rather to set this tag to something similar to only clang or CXX enviromental variables or do something in cmake ?
I tried those:
'--query-driver=CXX'
'--query-driver=clang'
But they dont work, like if i set the full path, it defaults back to MSVC's library.

**Comment by HighCommander4** [comment]
> Oh, and one last thing. Is it possible to not hard code the exact path to clang here, but rather to set this tag to something similar to only clang or CXX enviromental variables or do something with cmake, which auto generates me the compile_commands.json ? I tried those: '--query-driver=CXX' '--query-driver=clang++' But they dont work, like if i set the full path, it defaults back to MSVC's library.

The argument to query-driver is actually a glob pattern that serves as an allow-list against which the compiler path from `compile_commands.json` is checked. (This is security feature, since clangd will execute the compiler at that path to query its system includes.) It's that compiler path coming from `compile_commands.json` which is actually executed, if it matches the pattern.

So, instead of a full path like `D:\Program Files\MSYS2\mingw64\bin\clang++.exe`, you could use a glob pattern like `**\clang++.exe`.

(Just be aware of the security implications of doing this: if you check out someone else's codebase, and the source code contains `malicious\clang++.exe` and a `compile_commands.json` file with a command which starts with `malicious\clang++.exe`, clangd will execute `malicious\clang++.exe` because it matches the pattern `**\clang++.exe`.)

As for environment variables, clangd does not itself do environment variable expansion, but clients might have a way to do this. In VSCode, I can put `${env:CXX}` into the value of a setting like clangd arguments, and VSCode will expand it to the value of the `CXX` environment variable. I'm not sure whether Neovim has something similar.

**Comment by yodho1psnrls** [comment]
Nice, the glob pattern works perfectly, security doesnt come to my mind often, so i think i will keep it like that. I also tried the environmental variable expansion ${env:CXX}, but it doesnt expand it.
