### ISSUE TITLE
Provide code completion for members of a non-type template parameter whose type is deduced using CTAD (class template argument deduction)

### ISSUE THREAD

**Issue by Grzzlwmpf** [clangd/clangd#2227]
I have the following sample code:
```cpp

#include <array>
#include <cstddef>
#include <cstdint>

template<size_t dataLength>
struct Config
{
	uint8_t id{};
	std::array<uint8_t, dataLength> data{};
};

template<Config Cfg>
bool test()
{
	return Cfg.data.empty(); // no suggestions for members
}

template<Config<4> Cfg> // explicitly instantiated template type
bool test2()
{
	return Cfg.data.empty(); // member suggestions provided
}

int main()
{
	Config<4> constexpr c{
		.id = 0,
		.data{0,1,2, 3}
	};

	test<c>();
	test2<c>();
}
```

This compiles without issue on both clang 18.1.8 and GCC 14.2.0 using C++20.

However, clangd only provides suggestions for the members of the `Config` struct in the `test2` function where the template parameter has been explicitly instantiated (but doing that is obviously something that completely defeats the purpose of the function being generic in the first place).

**Logs**

Restarted language server, then invoked code completion for struct members in both functions..
[clangd-log.txt](https://github.com/user-attachments/files/17870010/clangd-log.txt)
(folder paths have been anonymized)

**System information**

Output of `clangd --version`: 
```
(built by Brecht Sanders, r1) clangd version 18.1.8
Features: windows
Platform: x86_64-w64-windows-gnu; target=x86_64-w64-mingw32
```
(using the WinLibs build)

Editor/LSP plugin: VSCode using `llvm-vs-code-extensions.vscode-clangd`

Operating system: Windows 11

Also tested with same result on Arch Linux 6.11.9 using VSCode with the same extension and with `clangd --version`:
```
clangd version 18.1.8
Features: linux
Platform: x86_64-pc-linux-gnu
```

**Comment by HighCommander4** [comment]
Go-to-definition on `data` or `empty` does not work either.

Support for this first needs to be implemented in `HeuristicResolver`, which will make go-to-def work.

To get code completion to benefit from it will additionally require #810.

**Comment by HighCommander4** [comment]
> Support for this first needs to be implemented in `HeuristicResolver`, which will make go-to-def work.

Posted a patch for this at https://github.com/llvm/llvm-project/pull/119107.
