### ISSUE TITLE
clangd does not recognize "restrict" key word in c.

### ISSUE THREAD

**Issue by DavidZyy** [clangd/clangd#2237]
![image](https://github.com/user-attachments/assets/787bffd9-3943-49f5-a19b-1ac465896645)
In this function, it report a error at s, because it does not recognize the key word restrict.

**Comment by HighCommander4** [comment]
Could you share [clangd logs](https://clangd.llvm.org/troubleshooting.html#gathering-logs) please?

**Comment by DavidZyy** [comment]
Sure, is this  you want to see?
![image](https://github.com/user-attachments/assets/55113553-0ff5-4e9b-a0f7-1054578f6a0f)
![image](https://github.com/user-attachments/assets/03fbb252-21b0-4af3-94f4-3e63666885cd)

**Comment by HighCommander4** [comment]
No, I'm looking for logs, obtained using the instructions on the page I linked to.

What editor are you using?

**Comment by DavidZyy** [comment]
I am using vscode. 
From Gathering logs, I go to installation to see how to make clangd’s stderr log available.
![image](https://github.com/user-attachments/assets/515f904b-37c1-45cc-933a-80642b6e8515)
And from Editor plugins, I find:
![image](https://github.com/user-attachments/assets/880b5819-6b83-441c-ad71-1ce235c1f49a)
Following it  I can find a mass of output, I am not sure if this is useful...
![image](https://github.com/user-attachments/assets/f79b622f-5f7a-4675-8fa4-0ad6cbceacb4)

**Comment by HighCommander4** [comment]
Yes, it's the right place, however can you:

 1. Add `--log=verbose` to `"clangd.arguments"` in vscode settings, so the logs contain (even) more information
 2. Copy-paste the (entire) logs from the Output window in text form rather than sending a screenshot

**Comment by DavidZyy** [comment]
Sure, but the output is too long, I put them in a log file and upload here.
[a.log](https://github.com/user-attachments/files/17954846/a.log)

**Comment by HighCommander4** [comment]
> Sure, but the output is too long, I put them in a log file and upload here. [a.log](https://github.com/user-attachments/files/17954846/a.log) Is it helpful?

Yes, thanks.

What I'm seeing in the logs is that the `ggml-cpu.c` file is being parsed in C++ mode. This is why the `restrict` keyword, which is part of the C language but not C++, is not recognized.

The reason the file is parsed in C++ mode is that the flag `-xc++` is present in the compile command.

It looks like it the flag may be coming from `compile_flags.txt`. Could you check, and if it's there try removing it?

**Comment by DavidZyy** [comment]
Yes! You are right! I add `-xc++` flag in `compile_flags.txt` because some `.h` files in this project use C++ grammar. For example, in `ggml-cpp.h`, if I do not add this flag, it will report errors:
![image](https://github.com/user-attachments/assets/d7408fc6-e702-4c6d-918a-80456226c7a7)
but if I add this flag, it works well:
![image](https://github.com/user-attachments/assets/278c3a5f-0e68-4384-96b0-3b5f1415bee0)
So It is very tricky, do you have any advices?

**Comment by HighCommander4** [comment]
Instead of putting the `-xc++` flag into `compile_flags.txt` you can create a `.clangd` file (https://clangd.llvm.org/config.html) which supports more flexible rules, for example:

```yaml
If:
  PathMatch: .*\.h

CompileFlags:
  Add: -xc++
```

This will add `-xc++` as a flag only for `.h` files.

**Comment by DavidZyy** [comment]
I try it and it solves my problem Thank you very much! You are a very nice person!

**Comment by HighCommander4** [comment]
Happy to help!
