### ISSUE TITLE
clangd did not choose the correct mode for header file.

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#224]
```
F:.
    compile_flags.txt
    foo.cpp
    foo.h
```
1. compile_flags.txt
```
-Wall
```
2. foo.cpp
```c++
#include "foo.h"
```
3. foo.h
```c++
#include <iostream> // 'iostream' file not foundclang(pp_file_not_found)
```

clangd did not choose the correct mode for the header file.

![image](https://user-images.githubusercontent.com/10697249/70504861-97284d80-1b61-11ea-81c7-5f1af1682d21.png)

I think clangd should respect the `Language Mode` in vscode.

**Comment by fox-tek** [comment]
Hey,
what if you add `-x c++` to your compile flags ?

**Comment by sam-mccall** [comment]
Right - it would be nice to use the language from the editor in the fallback case, but for better or worse the semantics of `compile_flags.txt` mean that *.h should be treated as C in this case, as in `clang -fsyntax-only -Wall foo.h`.

We could potentially override using the language from LSP, but I'm not sure it's the right thing - tools like clang-tidy will still treat foo.h as C in this case, so fixing compile_flags is a better solution.
