### ISSUE TITLE
[BUG] clangd can't recognize c++ header, and a .clangd file doesn't work for me.

### ISSUE THREAD

**Issue by aiyolo** [clangd/clangd#2255]
Please describe the problem.
I followed the instructions as described in https://github.com/clangd/clangd/issues/123, and put a .clangd file in my project directory, the content is:
```
If:
  PathMatch: .*\.h

CompileFlags:
  Add: [-xc++-header]
```
However, another warnings appears in my header file, it warns that 
```
Unsupported option '-x c++-header'; did you mean '/TC' or '/TP'?clang(drv_unsupported_opt_with_suggestion)
```
I'm using a msvc compiler, windows11 and vscode.  how can I fix it?

**Logs**
```
I[17:29:56.644] --> textDocument/clangd.fileStatus
V[17:29:56.644] >>> {
  "jsonrpc": "2.0",
  "method": "textDocument/clangd.fileStatus",
  "params": {
    "state": "idle",
    "uri": "file:///c:/Users/zhu/project/qiaoyi/lig-screen-gl/lig_screen_gl/include/lig_screen_gl.h"
  }
}

V[17:29:56.792] <<< {
  "id": 96,
  "jsonrpc": "2.0",
  "method": "textDocument/codeAction",
  "params": {
    "context": {
      "diagnostics": [
        {
          "code": "drv_unsupported_opt_with_suggestion",
          "message": "Unsupported option '-x c++-header'; did you mean '/TC' or '/TP'?",
          "range": {
            "end": {
              "character": 0,
              "line": 0
            },
            "start": {
              "character": 0,
              "line": 0
            }
          },
          "relatedInformation": [],
          "severity": 1,
          "source": "clang"
        }
      ],
      "only": [
        "quickfix"
      ],
      "triggerKind": 1
    },
    "range": {
      "end": {
        "character": 0,
        "line": 0
      },
      "start": {
        "character": 0,
        "line": 0
      }
    },
    "textDocument": {
      "uri": "file:///c%3A/Users/zhu/project/qiaoyi/lig-screen-gl/lig_screen_gl/include/lig_screen_gl.h"
    }
  }
}

I[17:29:56.792] <-- textDocument/codeAction(96)
V[17:29:56.792] ASTWorker running codeAction on version 1 of c:\Users\zhu\project\qiaoyi\lig-screen-gl\lig_screen_gl\include\lig_screen_gl.h
I[17:29:56.792] --> reply:textDocument/codeAction(96) 0 ms
V[17:29:56.792] >>> {
  "id": 96,
  "jsonrpc": "2.0",
  "result": []
}

I[17:29:56.792] --> textDocument/clangd.fileStatus
V[17:29:56.792] >>> {
  "jsonrpc": "2.0",
  "method": "textDocument/clangd.fileStatus",
  "params": {
    "state": "idle",
    "uri": "file:///c:/Users/zhu/project/qiaoyi/lig-screen-gl/lig_screen_gl/include/lig_screen_gl.h"
  }
}
```

**System information**

Output of `clangd --version`:
```
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc
```
Editor/LSP plugin:

Operating system:
Windows11

**Comment by aiyolo** [comment]
The following is my clangd arguments
![image](https://github.com/user-attachments/assets/561c4f50-aba6-49ad-b5fb-6be04538755e)

**Comment by HighCommander4** [comment]
Could you share a full set of logs starting from clangd startup to when you get the diagnostic?

**Comment by JVApen** [comment]
When using the msvc compatible driver (result of using cl), you should use
````
CompileFlags:
  Add: 
      -Xclang
      -xc++-header
````
This informs the driver that the next argument should be passed along to another layer.

**Comment by aiyolo** [comment]
> When using the msvc compatible driver (result of using cl), you should use
> 
> ```
> CompileFlags:
>   Add: 
>       -Xclang
>       -xc++-header
> ```
> 
> This informs the driver that the next argument should be passed along to another layer.

It seems that this workaround also doen't work. Now here comes another error:
```
unknown argument: '-Xclang -xc++--header'clang(drv_unknown_argument)
```

**Comment by aiyolo** [comment]
> Could you share a full set of logs starting from clangd startup to when you get the diagnostic?

I have uploaded a full set of logs here.
https://[raw.githubusercontent.com/aiyolo/issue-reporter/refs/heads/main/clangd-log.txt](https://raw.githubusercontent.com/aiyolo/issue-reporter/refs/heads/main/clangd-log.txt)

**Comment by JVApen** [comment]
Seems I forgot to add some dashes:
````
CompileFlags:
  Add: 
      - -Xclang
      - -xc++-header
````

**Comment by HighCommander4** [comment]
It seems that @JVApen is correct that adding `-xc++-header` directly to the command does not apply to the MSVC driver syntax.

> When using the msvc compatible driver (result of using cl), you should use
> 
> ```
> CompileFlags:
>   Add: 
>       -Xclang
>       -xc++-header
> ```
> 
> This informs the driver that the next argument should be passed along to another layer.

A slightly simpler alternative might be to use [`/TP`](https://learn.microsoft.com/en-us/cpp/build/reference/tc-tp-tc-tp-specify-source-file-type?view=msvc-170), which is the MSVC syntax's equivalent of `-xc++-header`.

**Comment by aiyolo** [comment]
I''ve tried to use -Xclang and /TP, they can't be handled by clangd, and caused much more errros.

**Comment by HighCommander4** [comment]
As before, please feel free to share logs with the new errors for additional diagnosis.

**Comment by aiyolo** [comment]
If I fill .clangd file with the following contents, I got [clang-log-with-argument-/tp](https://raw.githubusercontent.com/aiyolo/issue-reporter/refs/heads/main/clang-log-2024-1223-1112.txt)
```
If:
  PathMatch: .*\.h

CompileFlags:
  Add: 
      - -Xclang
      - /TP
 ```

If I fill .clangd contents with this, I got [clang-log-with-argument-xc++-header](https://raw.githubusercontent.com/aiyolo/issue-reporter/refs/heads/main/clang-log-2024-1223-1109.txt)
```
If:
  PathMatch: .*\.h

CompileFlags:
  Add: 
      - -Xclang
      - -xc++-header
```

**Comment by JVApen** [comment]
From what I can see, the flag is passed along to cc in the second log file. It does mention the following right before the errors: C:\Users\zhu\project\qiaoyi\lig-screen-gl\lig_screen_gl\res\main.rc
Resource files are something completely different, I have another extension installed for handling them.
Can you configure vs code to unlink these from clangd by configuring them as plain text?

**Comment by HighCommander4** [comment]
Note, for the first one, you don't want `-Xclang`, just `/TP`.

Anyways, I realized what the problem is:

> I[11:12:08.460] ASTWorker building file c:\Users\zhu\project\qiaoyi\lig-screen-gl\lig_screen_gl\include\caltab_params.h version 1 with command inferred from C:\Users\zhu\project\qiaoyi\lig-screen-gl\lig_screen_gl\res\main.rc

 * Clangd is choosing `main.rc` as the file whose compile command to use for `caltab_params.h`.
 * The compile command for `main.rc` uses `"C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22621.0\\x64\\rc.exe"` as the driver.
 * This driver seems to add an implicit `-x c-header` flag to the cc1 command, which comes after (and overrides) your `-x c++-header` command (regardless of whether it was spelt `/TP` or `-Xclang -xc++-header`).

The root issue here is the clangd should be using better heuristics to pick a file whose compile command to use for a header; this is tracked in https://github.com/clangd/clangd/issues/123.

Until that is fixed, a workaround I would suggest is to ensure your `compile_commands.json` file does not contain any entries for `.rc` files.

**Comment by RimuruChan** [comment]
I have the same problem. I usedcmake to add some deps written in C, and Clangd treat all my .h files as C headers because Clangd choose deps as the compile command for .h files
