### ISSUE TITLE
clang-format Unable to set a separate line of c++ attributes

### ISSUE THREAD

**Issue by cc-cao** [clangd/clangd#2263]

**Comment by HighCommander4** [comment]
Please provide additional details, including:
 * a code example
 * what editor action you're performing
 * what you would like to happen
 * what actually happens

Based on the issue description only, I have no idea what this is about.

**Comment by cc-cao** [comment]
[[gnu::unused]] void test() {}

clang-format:
BasedOnStyle: LLVM
IndentWidth: 4
TabWidth: 4
SortIncludes: false
ColumnLimit: 0
PointerAlignment: Left
AlignConsecutiveMacros: Consecutive
AlwaysBreakTemplateDeclarations: true
AllowShortIfStatementsOnASingleLine: true
AllowShortLoopsOnASingleLine: true

expect Attributes can be on a separate line:
[[gnu::unused]] 
void test() {}

**Comment by HighCommander4** [comment]
Try adding:

```
BreakAfterAttributes: Always
```

to the `.clang-format` file.
