### ISSUE TITLE
Resolve dependent call through simple smart pointer type

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#227]
During the review of #141, @sam-mccall suggested getting the following go-to-definition testcase to work:

```c++
template <typename> struct S { void [[foo]](); };
template <typename T> struct unique_ptr {
  T* operator->();
};
template <typename T>
void test(unique_ptr<S<T>>& V) {
  V->fo^o();
}
```

I [pointed out](https://reviews.llvm.org/D71240#1782513) that getting this testcase to work will not imply getting real-world code using `std::unique_ptr` to work, because the actual return type of `std::unique_ptr::operator->` in standard library implementations involves a bunch of metaprogramming.

However, it would still be useful to get this case to work, as people may work with other smart pointer types whose `operator->` is simply declared to return `T*`, as in the testcase.

**Comment by HighCommander4** [comment]
I tried implementing this using Sam's suggestion from the review:

> So it might be worth trying to get the pointee type (if the base type is a TemplateSpecializationType, look up operator-> in the primary template, and replace the base with its return type).

However, even for this simple case, there is a complication. To explain it, I will repeat the testcase, but with `unique_ptr`'s template parameter's name changed from `T` to `U`:

```
template <typename> struct S { void [[foo]](); };
template <typename U> struct unique_ptr {
  U* operator->();
};
template <typename T>
void test(unique_ptr<S<T>>& V) {
  V->fo^o();
}
```

We start by computing the type of `V`, which is `unique_ptr<S<T>>`. This is a `TemplateSpecializationType`, with the primary template `unique_ptr`.

To look up `operator->`, we basically discard the template parameters `S<T>`, and look up `operator->` in the Decl of the primary template. The resulting method decl is `U* operator->`, whose return type is `U*`, where `U` is a `TemplateParmType`.

Notice how this type is useless for the subsequent operation we were hoping to do, which is to look up the name `foo` inside this type.

It seems we are missing a step: to save the template parameter mapping `U --> S<T>` that we discarded when we went from `unique_ptr<S<T>>` to the primary template `unique_ptr`, and then _substitute this mapping back_ into the return type `U*` to get `S<T>*`, after which we can proceed as desired.

This should certainly be doable in theory, but I'm not familiar enough with clang'd AST to say how doable it is in practice. Would appreciate some guidance: does this seem like a reasonable thing to try to do?

**Comment by HighCommander4** [comment]
> Would appreciate some guidance: does this seem like a reasonable thing to try to do?

What gives me pause, in particular, is having seen comments like [this one](https://github.com/clangd/clangd/issues/106#issuecomment-525747968):

> That substitution is exposed by sema (`SubstDefaultTemplateArgumentIfAvailable`) but we don't have access to sema (and if we did, it's probably slow and has side effects like diagnostics).

Would we run into similar limitations if we tried to do the what I described?

**Comment by sam-mccall** [comment]
Thanks a lot for looking into this, and sorry for the "drive-by" nature of some of my comments!

This indeed gets hairy quickly. On the other hand, almost every templated smart pointer is of the form Tmpl<TargetType>.

What do you think about this hack: if we have a TemplateSpecializationType whose first argument is T, assume its `operator->` returns T*? And then do the member lookup in T.

This should address the common case, I think.

**Comment by HighCommander4** [comment]
> What do you think about this hack: if we have a TemplateSpecializationType whose first argument is a type T, assume its `operator->` returns T*? And then do the member lookup in T.

That's a good idea, thanks for suggesting it!

[Proposed fix](https://reviews.llvm.org/D71644)
