### ISSUE TITLE
clangd should omit default template paremeters while printing types

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#229]
related issues:
https://github.com/clangd/clangd/issues/148
https://github.com/clangd/clangd/issues/106
https://github.com/clangd/clangd/issues/227

https://reviews.llvm.org/D71545

**Comment by sam-mccall** [comment]
Richard fixed this in clang: https://github.com/llvm/llvm-project/commit/e7f3e2103cdb567dda4fd52f81bf4bc07179f5a8
