### ISSUE TITLE
Minimizing the LLVM build for clangd development

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#233]
As a clangd contributor, one thing I find frustrating is having to build all of LLVM to develop clangd. It takes a long time to build, and contains many things I don't need for clangd development.

I currently take the following steps to reduce the number of things I have to build:

 * `-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"`
 * `-DLLVM_TARGETS_TO_BUILD=X86`

I'm wondering, are there other things I could do to make the build even smaller / faster?

**Comment by kadircet** [comment]
i am not sure if you can reduce it anymore. (dynamic linking might help)

most of us started making use of `ccache` nowadays thanks to @gribozavr. The build config looks something like this:

```
CC="`which ccache` `which clang`" CXX="`which ccache` `which clang++`" cmake -G Ninja ../llvm/ -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
```

**Comment by HighCommander4** [comment]
I do use both dynamic linking and ccache. Ccache helps for switching between branches, but pulling from upstreaming still invariably causes a "recompile the world".

An example of the sort of thing I'm thinking of: is it possible to avoid building the clang-tidy checkers? They are quite heavy on build time, and unless you're working on clangd's clang-tidy integration, you don't really need them for clangd development.

**Comment by kadircet** [comment]
well, if we had more test/build targets then you could possibly get rid of building those. but currently we have one bulk target for all unittests(ClangdTests), and for lit tests we need the full clangd binary :/

**Comment by sam-mccall** [comment]
I think we could reasonably have a CMake variable for clang-tidy integration.
The hard dependency on the clang-tidy framework would be too messy to avoid, but we use the variable to disable the behavior and not link the *checkers*, which is most of the compile time.

> pulling from upstream still invariably causes a "recompile the world".
yup :-( I miss the good old days when you could (usually) sync clang-tools-extra and not clang/llvm...
Reducing the size of "the world" (I guess we mostly care about `ninja check-clangd`) is one approach, but making changes to headers in Support or Clang rebuild less than 2K files is hard.
Hopefully we're not rebuilding the world after LLVM (proper) changes?

**Comment by HighCommander4** [comment]
(That commit incorrectly referenced this issue.)

**Comment by HighCommander4** [comment]
Thank you @sam-mccall for adding this!
