### ISSUE TITLE
assertion !HitMapping && "recursive macro expansion?" at Tooling/Syntax/Tokens.cpp:458

### ISSUE THREAD

**Issue by jefftrull** [clangd/clangd#239]
I hit this assertion fairly reliably in Emacs lsp-mode usage on a large project. It happens in response to a `textDocument/hover` request - not every time, but frequently enough that clangd will crash within one minute of launching.

At least one other person [has observed this issue](http://lists.llvm.org/pipermail/cfe-dev/2019-November/063956.html) as recently as November.

Stack trace attached.
[trace.txt](https://github.com/clangd/clangd/files/4011868/trace.txt)

**Comment by jefftrull** [comment]
Based on some exploration in gdb I think the problem token is at the beginning of [this line from Boost.Python](https://github.com/boostorg/python/blob/1727b67a5a92c8c3564d4ee244fffd758e54d7cc/include/boost/python/detail/type_list_impl.hpp#L48)

**Comment by jefftrull** [comment]
Still present in 10.0.0 FWIW

**Comment by kadircet** [comment]
This should be fixed with https://github.com/llvm/llvm-project/commit/d66afd6dde542dc373f87e07fe764c071fe20d76. but you'll need a build of clangd from head, or need to wait for this week's nightly build at https://github.com/clangd/clangd/releases

**Comment by jefftrull** [comment]
I cherry-picked that commit and it seems to be working! Thanks very much.
