### ISSUE TITLE
Textual fallback for go-to-definition

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#241]
In cases where go-to-definition cannot produce an AST-based result, it would be useful for it to have a textual fallback, where it would just take the word under the cursor, and look it up in the lexically enclosing scope and its ancestor scopes to try to find a target.

This would be useful for:

  * Occurrences of type / function names in comments.
  * Navigating in the presence of invalid code. (Even with #33 in place, there will be cases where AST building cannot recover effectively but there would be a useful textual target.)

**Comment by sam-mccall** [comment]
> look it up in the lexically enclosing scope

A couple of potential issues:
- lookup is done with sema rather than against the AST. The scope structures it uses are not preserved. We could try to emulate it
- for broken code, we're getting into pseudoparsing which is a big can of worms. Long term, syntax trees would be a good platform for this, I'm not sure doing it ad-hoc would pay off

> Occurrences of type / function names in comments.
This case is easy to recognize (token kind is comment) and a lightweight way to address would be to find the nearest non-comment occurrence (token kind is identifier) and run GTD there. Could potentially fall back to index if not found in this file, but probably needs heuristics to avoid false positives.

> Navigating in the presence of invalid code.
There are lots of cases and implementation options here, and we could spend almost infinite complexity on this. I think we need to be explicit about what the most impactful cases are, and scope (!) a solution appropriately.
E.g. Ilya suggested adding a post-lookup callback to Sema, so we could preserve name lookup results even if the AST subtree gets discarded. But this only makes sense if name lookup actually happens and yields useful results in cases we care about, and we can't easily extend RecoveryExpr to preserve the AST (which is more powerful).

**Comment by sam-mccall** [comment]
Also, this would be at least as useful with `hover`

**Comment by HighCommander4** [comment]
What do you think of an initial approach that does something similar to `getWorkspaceSymbols()` with the word under the cursor as a query? We could initially do it with `FuzzyFindRequest::AnyScope = true`, and later refine the approach to set `FuzzyFindRequest::Scopes` based on what we think are the enclosing scopes.

Yes, it will have some false positives, but I think that's acceptable for these use cases (and certainly an improvement over having no results).

**Comment by HighCommander4** [comment]
> What do you think of an initial approach that does something similar to `getWorkspaceSymbols()` with the word under the cursor as a query? We could initially do it with `FuzzyFindRequest::AnyScope = true`, and later refine the approach to set `FuzzyFindRequest::Scopes` based on what we think are the enclosing scopes.
> 
> Yes, it will have some false positives, but I think that's acceptable for these use cases (and certainly an improvement over having no results).

I wrote a [prototype](https://reviews.llvm.org/D72874) of this approach. Any feedback is welcome!

There is obviously a lot of room to tweak this, but based on my testing in a production codebase, the prototype as written is already a huge improvement for navigating from comments, invalid code, and other non-AST contexts (e.g. strings, dependent contexts where AST heuristics are not useful), compared to the status quo of not offering any results.

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D75479 prototypes lookup based on tokens (find a nearby token that matches the cursor, and try to resolve it).

**Comment by sam-mccall** [comment]
Now we have some experience/experiments with implementation options, and thought more about contexts where this idea applies.

I want to revisit the (expanded!) list of use cases, and discuss behavior for each.

### Comments

If the name refers to something nearby, it's likely to be a true match (maybe
not the only one). False positives might happen with common words used as
variable names (like "enabled").

More-local usage is better, but with "siblings" (overloads, parallel
virtual/concept implementations) we'd like to return all.

There will be non-local references too: we should find "ClangdServer" in the
index (but not "and"!)

**Proposal**:
- starting from the thing the comment is attached to, with increasing syntactic
  scope (like SemanticRanges) look for identifier tokens matching the word
- once we found any in some scope, resolve them all and return them
- if none is found at file scope *and* we think the word is an identifier
  (e.g. CamelCase, backticks) then do an index lookup and return all results

### Dependent code

Dependent name lookup is the important case. We can precisely recognize this
from the AST, and in some cases know if we're looking for a function, non-static
member, etc.

Sometimes AST-based resolution is possible, just not 100% accurate and so not
done by clang. e.g. @HighCommander4's work on looking up dependent-scope
members in the primary template. There are other cases: resolving unqualified
names to matching NamedDecls in enclosing scopes in the file is probably better
than any more textual approach.
Also, where a template is instantiated in the current file, I think in principle
we can find and resolve the corresponding instantiated node. This partially
fails if some but not all instantiations are visible, not sure if that's common.

Typical concept-like templates access members/ADL functions that aren't visible
to the template definition (the dependency edge goes the other way).
Textually scanning for matching names in the current file is likely to find more
dependent code, or possibly specializations that don't reflect the general case.
On the other hand, sometimes this stuff is local, and searching globally will
find lots of collisions.

**Proposal**:
- Use heuristic AST-based resolution whenever possible, try to extend this
- Scan the current file for tokens matching the name, keep only the ones that
  resolve to *declarations* with that name (and match other criteria)
- If there were local declarations, return those
- Search the index, return all results that match the criteria

### Preprocessor-disabled sections (`#ifdef`)

Compared to unstructured comments:
-  it's more likely that words are identifiers
-  we could potentially pseudo-parse to understand e.g. if it's a function
-  the referent may be defined in the disabled section

The last point is dangerous: if we do anything fancy, users may think we can
actually resolve in these counterfactual situations, and that's hard/impossible.

On the other hand, being able to resolve references to common things inside an
`#ifdef win32` is pretty valuable.

**Proposal**:
- Treat this like comments for now

### Macro definitions

This has a lot in common with preprocessor-disabled sections.
If we have usages of the macro in this file, it'd probably be a win to resolve
using those (when all usages agree).

**Proposal**:
- treat this like comments for now
- maybe look at expansions in the future

### String literals

I don't think this case is very important. Are there metaprogramming/logging
scenarios where this is critical, or something else I'm missing?

We could treat this like comments, but...

**Proposal**:
- don't support this case

### Broken code

We're finally starting to land the patches for representing broken code in the
AST (#33). This is fairly extensible, and in principle much more precise than
a textual approach. I'd like to give it a chance to work.

**Proposal**:
- don't support this for now, revisit after RecoveryExpr is stable

**Comment by HighCommander4** [comment]
@sam-mccall the above all sounds good to me as a direction to head towards. A couple of specific comments:

> ### Preprocessor-disabled sections (`#ifdef`)
> 
> Compared to unstructured comments:
> 
>     * it's more likely that words are identifiers
> 
>     * we could potentially pseudo-parse to understand e.g. if it's a function
> 
>     * the referent may be defined in the disabled section
> 
> 
> The last point is dangerous: if we do anything fancy, users may think we can
> actually resolve in these counterfactual situations, and that's hard/impossible.
> 
> On the other hand, being able to resolve references to common things inside an
> `#ifdef win32` is pretty valuable.
> 
> **Proposal**:
> 
>     * Treat this like comments for now

+1, I had in mind use cases where the referent is defined outside the disabled section.

For use cases where there is a significant amount of code defined inside a disabled section, and you want to navigate within that code, my current workaround is to open the code in a configuration (i.e. different `compie_commands.json`) that enables that section. Perhaps, in the future, we could offer a mechanism to let users specify a small number of configurations they care about, and parse the code in each of them and somehow merge the results. However, that's a completely different feature with its own set of issues and tradeoffs, which we can discuss elsewhere.

> ### String literals
> 
> I don't think this case is very important. Are there metaprogramming/logging
> scenarios where this is critical, or something else I'm missing?
> 
> We could treat this like comments, but...
> 
> **Proposal**:
> 
>     * don't support this case

I haven't come across any significant use cases for string literals. Support for them just sort of fell out from support for other non-identifier contexts like comments. I'm fine with not supporting them.

**Comment by HighCommander4** [comment]
While an initial piece of work has landed, we are planning some follow-up pieces for this, so I'm going to re-open this.

**Comment by HighCommander4** [comment]
With https://reviews.llvm.org/D75479 and https://reviews.llvm.org/D76451 landed as well, I think we can consider the issue substantially fixed, and file follow-ups for any further improvements.
