### ISSUE TITLE
go-to-definition doesn not work when "class template argument dedection" is used

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#242]
```c++
template<typename T>
struct Test {
    Test(T t);
};

int main() {
    Test a(5);
//  ^^^^ go-to-def not works
}

```

**Comment by HighCommander4** [comment]
The type specifier here has a `BuiltinTypeLoc` with an empty source range, so it doesn't get selected, only the enclosing `VarDecl` does, which targets itself.

**Comment by HighCommander4** [comment]
> The type specifier here has a `BuiltinTypeLoc` with an empty source range

Sorry, this was happening because my testcase wasn't being parsed in C++17 mode.

In C++17 code, we get a `DeducedTemplateSpecializationTypeLoc`, and it does get selected, so hopefully this will be a simple fix to `TargetFinder`.

**Comment by HighCommander4** [comment]
I tried to fix this in `TargetFinder`, but ran into [PR42914](https://bugs.llvm.org/show_bug.cgi?id=42914), which appears to affect `DeducedTemplateSpecializationTypeLoc` as well.

We could, however, work around this if we're fine with always navigating to the primary template (as opposed to using the deduced template specialization, which could potentially come from a partial or explicit specialization) for now.

**Comment by HighCommander4** [comment]
It looks like PR42914 is not an easy fix, so I suggest we go ahead with the workaround.

[Proposed patch](https://reviews.llvm.org/D72119).
