### ISSUE TITLE
Couldn't build compiler invocation

### ISSUE THREAD

**Issue by e00E** [clangd/clangd#246]
I realize there is #223 but I am not sure if this is the same thing because I am not on Windows and this happens always (not sometimes).

Arch linux

```
> clang --version
clang version 9.0.1
Target: x86_64-pc-linux-gnu
```

I am trying to use clangd through visual studio code on the project https://github.com/swaywm/wlroots .

Clangd does not work.

In the clangd output I can see that every file fails with:

> Couldn't build compiler invocation`

[compile_commands.txt](https://github.com/clangd/clangd/files/4023492/compile_commands.txt)

**Comment by e00E** [comment]
The above linked compile_commands actually works.

It fails if I have set the compiler to clang `env CC=clang meson build`.
When I don't specify `CC` then `cc` is used which is gcc. In either the case the project itself compiles successfully (`ninja -C build`).

This is a failing example [compile_commands.txt](https://github.com/clangd/clangd/files/4023496/compile_commands.txt).

**Comment by puremourning** [comment]
Can you post the clangd log with debug logging enabled? Instructions here: https://clangd.github.io/installation.html

**Comment by e00E** [comment]
This is the normal log [log.txt](https://github.com/clangd/clangd/files/4023637/log.txt). The page you link doesn't mention how to enable *debug* logging specifically.
This is with `log=verbose` if that is what you mean [log.txt](https://github.com/clangd/clangd/files/4023653/log.txt).

**Comment by puremourning** [comment]
Thanks. Out of curiosity do you see these in the verbose output when the compiler is `cc`:

> V[17:35:34.479] Ignored diagnostic. unknown argument: '-pipe'

**Comment by e00E** [comment]
Here is the verbose log with `cc` [log.txt](https://github.com/clangd/clangd/files/4023684/log.txt).
The message you quote does not appear.

**Comment by kadircet** [comment]
I can repro at 9.0.1 release, but it seems to be fixed at head.
