### ISSUE TITLE
Clangd shows redundant return types on some special members

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#252]
Steps to reproduce:
1. Hover over the out-of-line definitions in the following example:
```cpp
struct X {
  X();
  ~X();
  operator int();
};

// Here are the definitions
X::X() {}
X::operator int() {}
X::~X() {}
```

Expected: the hover does not show return types.
Actual: the hover shows return type.

**Comment by sam-mccall** [comment]
Yeah, we debated this a bit for code complete but there's no question we're showing decls here rather than expressions. This seems clearcut.

**Comment by kadircet** [comment]
Oops that one somehow slipped away, thanks for bumping it up.
https://reviews.llvm.org/D73110
