### ISSUE TITLE
Inserting `#include "config.h"` into the top of all parsed header files?

### ISSUE THREAD

**Issue by charlie-ht** [clangd/clangd#257]
In the WebKit, clangd fails to parse all header files because the convention is to start headers with `#if ENABLE(FEATURE)`. The `ENABLE` macros are defined in per directory "config.h"'s, which by convention must only be included in the `.cpp` file, not the header, so tools like `clangd` has no chance of parsing the headers...

This should be fixed in WebKit, but for raisins it won't be :-) Is there any argument I can pass to the server, or configuration I can do in the vscode clangd extension that would allow me to basically say, "Hey, if you're trying to parse a .h file, always prepend #include "config.h" to the source text"? Is that possible somehow?

**Comment by kadircet** [comment]
I suppose you can try adding `-include config.h` to your compile commands.

Unfortunately clangd doesn't support non-selfcontained files, a similar issue in https://github.com/clangd/clangd/issues/45.

**Comment by sam-mccall** [comment]
@kadircet I know we've been down this rabbithole before, but WDYT about a "setting" that's like `map<regex, vector<string>> addFlags`, and maybe a similar `ignoreFlags`?

The questions about where to put it and when to load it remain :-)

**Comment by charlie-ht** [comment]
> I suppose you can try adding `-include config.h` to your compile commands.
> 
> Unfortunately clangd doesn't support non-selfcontained files, a similar issue in #45.

Thanks @kadircet - I found some time to write a script to modify my compile_commands.json to add `-include config.h` and a few other `#define`'s that are needed for clang to properly resolve symbols everywhere in WebKit. The result is great.

Having some settings / API that would allow me to add arbitrary compiler arguments to each entry in the compilation database would be great (or maybe to each entry in a filtered compilation database). Thanks again!

**Comment by kadircet** [comment]
Now we have it! With clangd-11 you can use .clangd config files to add/remove compile flags. More details in http://clangd.llvm.org/config.html#compileflags
