### ISSUE TITLE
clang-tidy suppression at expansion location

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#266]
Given `-clang-tidy-checks=hicpp-signed-bitwise`

```
int y = 1;
#define BAD y|y //A
int x = BAD; //B
```

`clang-tidy` will respect NOLINT at either A or B. clangd will respect it only at A.

**Comment by sam-mccall** [comment]
This is due to trying to avoid reading NOLINT in preamble locations we don't have source code for.
We should be able to restrict this by FileID though, rather than never traversing expansions.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D75286)
