### ISSUE TITLE
clangd in a host/docker setup

### ISSUE THREAD

**Issue by AndreasAZiegler** [clangd/clangd#269]
This is more a question about which setting I have to use to be able to use clangd within my setup and not really an issue.

As I'm running Arch Linux but develop software (in C++) which has to run on Debian and Ubuntu I'm currently on the following setup. I have neovim (because I really like it) with [YouCompleteMe](https://github.com/ycm-core/YouCompleteMe) and [this setup](https://github.com/AlexandreCarlton/ycmd-docker) to run the ycm-server within the Docker (which runs Debian).

Now I would like to give [coc.nvmi](https://github.com/neoclide/coc.nvim) and clangd a chance as it seems to work better according to what I read.

How should I use clangd in such a setup? My current approach, which doesn't work is the following: I start clangd within coc.nvim with theses arguments ```--background-index", "--query-driver", "/home/andreasziegler/mt-robot/docker_includes/debian/**/*4.9```.  I copied the gcc (gcc & g++)  from the docker to ```/home/andreasziegler/mt-robot/docker_includes/debian/bin/```. I also created a compile_commands.txt containing: ```-I /home/andreasziegler/mt-robot/docker_includes/debia/usr/include``` and copied the content of ```/usr/include/``` on the docker to ```/home/andreasziegler/mt-robot/docker_includes/debia/usr/include``` and copied the content of ```/usr/include/``` on the docker to ```. As this setup doesn't work, how should I do it?

**Comment by sam-mccall** [comment]
For remote development, you'll want:
 - the source files available on both environments (mounted from one to the other)
 - a working build on the "remote" machine, with its compile_commands.json symlinked onto the top of the source tree
 - ideally, the c++ stdlib and other libraries from the remote machine also mounted on the editor machine
 - a recent clangd on the "remote" machine: you need https://github.com/llvm/llvm-project/commit/c69ae835d0e0 which isn't in clangd 9 (it will be in 10). Nightly from http://apt.llvm.org/ should work I think.

Then you'll run clangd on the remote machine, and use the --path-mappings flag to describe where source files, library headers etc are mounted on the "editor" machine.

If you need to stick with clangd 9, you should ensure the sources are at the same path in both environments, and expect some surprises if navigating into stdlib.

If this doesn't work, please provide more details (try on a trivial project, include logs with -log=verbose, describe symptoms). You mentioned -query-driver, which shouldn't be needed unless something (else) is unusual about the project.

**Comment by AndreasAZiegler** [comment]
@sam-mccall Thanks a lot for the fast response. So far I was not aware that I need to have a recent clangd on the "remote" machine. To get a recent clangd running on a Debian jessie (8), seems quite a lot of work. I guess I will wait until I can use Ubuntu 18 as remote machine (depends on the company I'm working for) where this should a bit easier to set up.

**Comment by svorobiev** [comment]
if you can afford to run VSCode locally and an SSH server in the container, clangd 10 + current vscode remote SSH works out of the box. I have it working with Ubuntu 16 and Centos7 containers.

**Comment by sam-mccall** [comment]
Yes, I've heard VSCode remote works nicely.

Our binary releases should now work on debian 8: http://github.com/clangd/clangd/releases/latest
I'm going to close this bug as I'm not sure there's more to do here.
