### ISSUE TITLE
rename should not trigger on special `override`, `final` identifiers

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#270]
```c++
class X {
   virtual void foo();
};
class Y : X {
  void foo() over^ride; // not ok: rename is triggered.
};

void foo() {
  int over^ride; // ok: rename works as expected.
}
```

`override` is special, from cppreference: 

> override is an identifier with a special meaning when used after member function declarators: it's not a reserved keyword otherwise.

**Comment by hokein** [comment]
I can't reproduce this with a trunk clangd, I guess this is fixed by having better support of attributes in clangd.

**Comment by sam-mccall** [comment]
I think this might also have been fixed by your patch that verifies that the thing under the cursor actually gets renamed :-)
