### ISSUE TITLE
Extract function is not working

### ISSUE THREAD

**Issue by gkoulin** [clangd/clangd#272]
Hi,

I am not able to get extract function feature to work. Extract variable works fine so do the other features. Could you please provide an example of the selection where you expect extract function option to become available?

**Comment by sureyeaah** [comment]
The documentation at top [here](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp) gives a brief overview of when extract function works.

**Comment by gkoulin** [comment]
I have tried the example in your link but it doesn't produce a light bulb with a suggestion. I have correct setup with `compile_commnads.json` and waited for clangd to finish parsing, current status `clangd: Idle`

vscode-clangd 0.0.20
clangd version 9.0.1

**Comment by sureyeaah** [comment]
Aah, Clangd 9 doesn't ship with Extract to function. Clangd 10 does.

**Comment by gkoulin** [comment]
any idea how to install clangd 10 on mac? llvm comes with 9.0.1

**Comment by kadircet** [comment]
AFAIK, there are no nightly builds for mac. So your best bet would be to
build from source.

**Comment by wusatosi** [comment]
> The documentation at top [here](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp) gives a brief overview of when extract function works.

This should now be [here](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/refactor/tweaks/ExtractFunction.cpp) if anyone is wondering.
