### ISSUE TITLE
Completion debounce is likely too long

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#275]
We have a debounce in code completion: when a file changes, we wait 500ms before rebuilding to see if we get another change. The idea is we want to wait until the user stops typing.

There are several concerns in tuning this behavior. Consider a user typing `foo();`:
 - we want diagnostics ASAP after `;` and don't do concurrent builds, so having a long-running rebuild active when `;` arrives is a problem.
 - diagnostics after `f` are rarely useful and have negative value (distraction) for some users
 - the debounce itself adds latency to diagnostics after `;`

The current behavior is particularly unhelpful for users where rebuild times are fast (e.g. 50ms) and who don't really care about getting more diagnostics on their incomplete code.

Ideas:
 - adapt debounce time based on recent rebuild times for this file
 - allow disabling/customizing debounce time
 - allow concurrent rebuilds so they don't "compete" so much
 - behave differently on different edits

**Comment by kadircet** [comment]
another thing to consider might be to put some cancellation mechanism into clang parser
