### ISSUE TITLE
No quick fixes available for simple moderernazation

### ISSUE THREAD

**Issue by gkoulin** [clangd/clangd#276]
`typedef std::map< InstanceId, WidthAndHeight > InstanceToWidthAndHeight;`

clangd gives the suggestion:

> Use 'using' instead of 'typedef'clang-tidy(modernize-use-using)

yet offers no quick fix for such a simple case

**Comment by sam-mccall** [comment]
I can't reproduce this - I get a quick-fix for the diagnostic using clangd trunk:
```
#include <map>
struct InstanceId{};
struct WidthAndHeight{};
typedef std::map< InstanceId , WidthAndHeight > InstanceToWidthAndHeight;
```

Can you provide a little more info? `clangd --version` output, editor, and a complete minimized example?

**Comment by gkoulin** [comment]
clangd version 10.0.0 (https://git.llvm.org/git/clang.git 65acf43270ea2894dffa0d0b292b92402f80c8cb) (https://git.llvm.org/git/llvm.git 2c4ca6832fa6b306ee6a7010bfb80a3f2596f824)

also this is conjunction with `vscode-clangd 0.0.20`

**Comment by sam-mccall** [comment]
Thanks. Can you give a complete example where it doesn't work? (The code above doesn't compile for example, you need `#include <map>` and declarations for `InstanceId` etc

**Comment by gkoulin** [comment]
Exact example:

![Screenshot 2020-02-05 at 10 57 40](https://user-images.githubusercontent.com/25503221/73836049-5f0e5580-4806-11ea-8631-8fd8acb1c9bd.png)

**Comment by hokein** [comment]
The version you are using is around the mid of October, 2019, I can reproduce this issue with clangd v9 as well, but not the trunk.

You should see the fixit for `typedef int variable;`

It looks like there are a few patches after that to improve the `modernize-use-using` check (I think they fix the sample you gave above). I'd suggest you to wait for the clangd v10 release or just build it from source.
