### ISSUE TITLE
go-to-def should go to the underlying decl if triggered on an alias 

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#277]
```cpp
namespace ns { class Foo {}; }

using ns::F^oo; // should go to the ns::Foo.
```

looks like this is a regression issue, clangd v9 gives both results, alias and underlying decl.

**Comment by sam-mccall** [comment]
+1 to the example. (Definition of a non-renaming alias)

I think we need to avoid regressing non-definition references to renaming aliases:
`using X = Y; ^X foo;`
Jumping to (only) the using decl is clearer here.

The other cases (definition of renaming alias, or non-definition of non-renaming alias) don't matter much I think.
