### ISSUE TITLE
Global rename does not work on some symbols in the LLVM codebase

### ISSUE THREAD

**Issue by kirillbobyrev** [clangd/clangd#281]
There's a nice [tool](https://reviews.llvm.org/D71110) for global rename evaluation that I've been playing with and it lets explore the infrastructure by triggering rename on different symbols. These are the symbols from the LLVM codebase that are known to fail during the renaming stage:

- [ ] `llvm/include/llvm/ADT/Optional.h llvm::Optional`, blacklisted, #280 
- [ ] `llvm/include/llvm/ADT/None.h llvm::None` - does not change anything in the generated code. I'm not sure if it's possible to detect those or not.

To reproduce the failures, the limit on the number of affected files should be removed.

**Comment by kirillbobyrev** [comment]
Some of the known specifics include:

- Default argument values in the function signatures (`void foo(NoneType Variable = None);`)
- Class forward declarations

**Comment by hokein** [comment]
Thanks for the feedback.

I tied to execute rename on `llvm::None`, `llvm::Twine`, I didn't reproduce the issues mentioned above.  Both of them needs some manual tweaks to pass the compilations, but I think these two cases are expected, below are details:

- `llvm::None`,  we have a few unrenamed occurrences, all of them are in *.inc which are most likely tablegen files, e.g. `None` occurrence is hardcoded in https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/Attr.td#L3296, I think this is a limitation of clangd rename;
- `llvm::Twine`, we have a few unrenamed occurrences as well, but all of them are inside macro bodies, clangd doesn't rename these occurrences; 

BTW, for `llvm::None`, I ended up with manually changing <10 files (out of 688 changed files) to make it pass compilation; for `llvm::Twine`, the number is similar, ~6 files out of 686 changed files.

**Comment by kirillbobyrev** [comment]
> Thanks for the feedback.
> 
> I tied to execute rename on `llvm::None`, `llvm::Twine`, I didn't reproduce the issues mentioned above. Both of them needs some manual tweaks to pass the compilations, but I think these two cases are expected, below are details:
> 
> * `llvm::None`,  we have a few unrenamed occurrences, all of them are in *.inc which are most likely tablegen files, e.g. `None` occurrence is hardcoded in https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/Attr.td#L3296, I think this is a limitation of clangd rename;
> * `llvm::Twine`, we have a few unrenamed occurrences as well, but all of them are inside macro bodies, clangd doesn't rename these occurrences;
Hm, that is very strange, I'm wondering what could be different. I was curious to see what files that affects and I simply ran

```
build/bin/clangd-rename --index-path=/tmp/llvm-index.idx --rename-symbol=llvm::Twine -fix llvm/include/llvm/ADT/Twine.h
```

And then this is the code that I have, for example in `llvm/include/llvm/Support/MemoryBuffer.h`

```c++
  /// Open the specified file as a MemoryBuffer, returning a new MemoryBuffer
  /// if successful, otherwise returning null. If FileSize is specified, this
  /// means that the client knows that the file exists and that it has the
  /// specified size.
  ///
  /// \param IsVolatile Set to true to indicate that the contents of the file
  /// can change outside the user's control, e.g. when libclang tries to parse
  /// while the user is editing/updating the file or if the file is on an NFS.
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getFile(const Twine &Filename, int64_t FileSize = -1,
          bool RequiresNullTerminator = true, bool IsVolatile = false);

  /// Read all of the specified file into a MemoryBuffer as a stream
  /// (i.e. until EOF reached). This is useful for special files that
  /// look like a regular file but have 0 size (e.g. /proc/cpuinfo on Linux).
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getFileAsStream(const Twine &Filename);

  /// Given an already-open file descriptor, map some slice of it into a
  /// MemoryBuffer. The slice is specified by an \p Offset and \p MapSize.
  /// Since this is in the middle of a file, the buffer is not null terminated.
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getOpenFileSlice(sys::fs::file_t FD, const Twine &Filename, uint64_t MapSize,
                   int64_t Offset, bool IsVolatile = false);

  /// Given an already-open file descriptor, read the file and return a
  /// MemoryBuffer.
  ///
  /// \param IsVolatile Set to true to indicate that the contents of the file
  /// can change outside the user's control, e.g. when libclang tries to parse
  /// while the user is editing/updating the file or if the file is on an NFS.
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getOpenFile(sys::fs::file_t FD, const Twine &Filename, uint64_t FileSize,
              bool RequiresNullTerminator = true, bool IsVolatile = false);

  /// Open the specified memory range as a MemoryBuffer. Note that InputData
  /// must be null terminated if RequiresNullTerminator is true.
  static std::unique_ptr<MemoryBuffer>
  getMemBuffer(StringRef InputData, StringRef BufferName = "",
               bool RequiresNullTerminator = true);

  static std::unique_ptr<MemoryBuffer>
  getMemBuffer(MemoryBufferRef Ref, bool RequiresNullTerminator = true);

  /// Open the specified memory range as a MemoryBuffer, copying the contents
  /// and taking ownership of it. InputData does not have to be null terminated.
  static std::unique_ptr<MemoryBuffer>
  getMemBufferCopy(StringRef InputData, const Twine &BufferName = "");

  /// Read all of stdin into a file buffer, and return it.
  static ErrorOr<std::unique_ptr<MemoryBuffer>> getSTDIN();

  /// Open the specified file as a MemoryBuffer, or open stdin if the Filename
  /// is "-".
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getFileOrSTDIN(const Twine &Filename, int64_t FileSize = -1,
                 bool RequiresNullTerminator = true);

  /// Map a subrange of the specified file as a MemoryBuffer.
  static ErrorOr<std::unique_ptr<MemoryBuffer>>
  getFileSlice(const Twine &Filename, uint64_t MapSize, uint64_t Offset,
               bool IsVolatile = false);
```

What revision are you on? I applied the mentioned patch on top of a7fd548a4f9e50e1aa2def57bae885604c9c5878

> 
> BTW, for `llvm::None`, I ended up with manually changing <10 files (out of 688 changed files) to make it pass compilation; for `llvm::Twine`, the number is similar, ~6 files out of 686 changed files.

**Comment by kirillbobyrev** [comment]
Regarding the last one: yeah, that's my bad, those are the symbols not being renamed because of the other limit that I didn't remove :(

Will update the case soon.

**Comment by hokein** [comment]
digging more into the `.inc` case today, I think there are two possible situations:
1) if you check out the source code (and doesn't build any targets), the TableGen-generated files (`.inc`) are not existed, so that when you run `clangd-indexer`, you will have no references in the index, so nothing changed in these files;
2) if you have built any target before running the index, the TableGen-generated files are likely existed, so we have references in the index, when you run rename, it does change these files. However, when you build targets to verify the rename results, these files are re-generated, so that the renamed changes in these files are gone;

The correct rename is to update occurrences in source files `.td`, these files are used by TableGen program during the build process, and clangd doesn't have any knowledge about them, this is a reasonable limitation, I think. 

Also I renamed the `llvm::Optional` and encountered the same issue. In summary, I didn't see any failures other than missing references in `.inc` files when renaming `llvm::None`, `llvm::Twine`, `llvm::Optional`.

Closing this bug now, as it is a known limitation. Feel free to reopen it if you have other failures.
