### ISSUE TITLE
textDocument/implementation - derived entities

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#29]
Semantics in LSP aren't totally clear here, but this looks like a good place to show:
 - overrides of virtual functions
 - derived classes of a base
 - maybe template specializations?

In general, where potentially multiple entities have an "is-a" relationship with the thing under the cursor.
We may want this to fall back to "go to definition" behavior as well.

**Comment by HighCommander4** [comment]
Looks like this was added in https://reviews.llvm.org/D91626 and related patches.

Should we close this, or do we plan to do other things (like the "maybe template specializations" mentioned in the description)?

**Comment by sam-mccall** [comment]
Yeah, I think we should close this.

Template specializations would be nice, but I'm not sure anyone's working on it, and keeping bugs open forever because we could always do more is probably a bad habit :-)
