### ISSUE TITLE
Unable to find references for a struct field

### ISSUE THREAD

**Issue by stfairy** [clangd/clangd#292]
I'm examining the source code of git and occasionally there are struct fields that do not reveal their references, but from one of the actual references I can use go to definition without issues.

```
$ git describe
v2.25.1-362-g51ebf55b93
$ clangd --version
clangd version 10.0.0 (Fedora 10.0.0-0.1.rc2.fc32)
$ code --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
$ bear --version
bear 2.4.3
```

I built it with
```
$ bear make prefix=~/.local/git all
```

At the end of the `hash.h` file, there is:

```
struct object_id {
	unsigned char hash[GIT_MAX_RAWSZ];
```

One of the references of the `hash` field is in `hashmap.h`:

```
static inline unsigned int oidhash(const struct object_id *oid)

	memcpy(&hash, oid->hash, sizeof(hash));
```

From the `hash.h` file, Find All References told me there were no results.  Output window:

```
I[19:37:01.731] <-- textDocument/references(543)
I[19:37:01.731] --> reply:textDocument/references(543) 0 ms
I[19:37:01.732] --> textDocument/clangd.fileStatus
```

From the `hashmap.h` file, click on "hash" (as part of "oid->hash"), both "Find All References" and "Go To Definition" work without obvious issues.

**Comment by hokein** [comment]
Thanks for the report, confirmed with the simple case.

```cpp
struct object_id {
   unsigned char ha^sh[10]; // go-to-def, find-references, hover are not working here.
};
```

I guess it might be a selection tree issue.
