### ISSUE TITLE
Crash in UnnamedLocalNoLinkageFinder

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#293]
Needs compile commands for mlir, maybe requires some generated headers to be missing.

V[16:39:59.342] Indexing /redacted/llvm-project/mlir/examples/toy/Ch7/mlir/LowerToLLVM.cpp (digest:=A4EC66E2D1E92970)
V[16:39:59.747] Ignored diagnostic. /redacted/llvm-project/mlir/examples/toy/Ch7/include/toy/ShapeInferenceInterface.h:23:10:'toy/ShapeInferenceOpInterfaces.h.inc' file not found
*** SIGSEGV (@0x8) ***
PC: @     0x555d6139b0ad  (unknown)  (anonymous namespace)::UnnamedLocalNoLinkageFinder::VisitNestedNameSpecifier()
    @     0x555d64315a92       1936  FailureSignalHandler()
    @     0x7fe9457999a0       3344  (unknown)
    @     0x555d6450761a        192  clang::Sema::ActOnTypeParameter()
    @     0x555d64505db9       1968  clang::Parser::ParseTemplateParameters()
    @     0x555d644e734a        656  clang::Parser::ParseTemplateDeclarationOrSpecialization()
    @     0x555d64451941       3152  clang::Parser::ParseCXXClassMemberDeclaration()
    @     0x555d6449cd9f       2064  clang::Parser::ParseClassSpecifier()
    @     0x555d6445b2e8        512  clang::Parser::ParseDeclarationSpecifiers()
    @     0x555d64c0a308        176  clang::Parser::ParseDeclOrFunctionDefInternal()
    @     0x555d64c092a0        784  clang::Parser::ParseExternalDeclaration()
    @     0x555d64c0844b        128  clang::Parser::ParseInnerNamespace()
    @     0x555d614b7973        752  clang::Parser::ParseNamespace()
    @     0x555d614b621a        128  clang::Parser::ParseDeclaration()
    @     0x555d64c09053        784  clang::Parser::ParseExternalDeclaration()
    @     0x555d6537e908        128  clang::Parser::ParseTopLevelDecl()
    @     0x555d618fa4b8        128  clang::ParseAST()
    @     0x555d636ccbd8         96  clang::FrontendAction::Execute()
    @     0x555d62ff5ac2       3200  clang::clangd::BackgroundIndex::index()
    @     0x555d62ffd5a0        336  std::__u::__function::__policy_invoker<>::__call_impl<>()
    @     0x555d63003b7e        272  clang::clangd::BackgroundQueue::work()
    @     0x555d62ffaebe         96  llvm::unique_function<>::CallImpl<>()
    @     0x555d62fe7274        160  llvm::unique_function<>::CallImpl<>()
    @     0x555d6426f89b         32  threadFuncAsync()
    @     0x7fe9457914e8        176  start_thread
    @     0x7fe94560622d  (unknown)  clone

**Comment by kadircet** [comment]
crash seemed to happen at llvm/llvm-project/e8c5fea243ce30640ec9707fabdb635a49b3153c
