### ISSUE TITLE
Color dependent names based on their heuristic target if they have one

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#297]
In the following code:

```c++
template <typename T>
struct Foo {
  int waldo;
  void bar(Foo f) {
    f.waldo;   // <-- "waldo" highlighted as DependentName
  }
};
```

The use of `waldo` on the indicated line is highlighted as a `DependentName`.

Unless I'm mistaken, there is no way that name can resolve to any declaration other than the field in the primary template. So, while it may technically be "dependent", I think it would make sense to color it according to its unambiguous target declaration, i.e. as a field.

**Comment by sam-mccall** [comment]
findExplicitReferences doesn't handle CXXDependentMemberExpr and friends as part of refInExpr() in FindTarget.cpp. It could delegate to the heuristics in findTarget for the actual target, as some other node types do.

Then we'd have the problem that SemanticHighlighting itself adds highlights for such nodes (as "dependent name"). So there would be two conflicting highlights, and the conflict is resolved by dropping both :-)
We have to work out how to preserve the "good" one we want instead, without losing all the dependent-name highlights where the target *can't* be resolved.

**Comment by HighCommander4** [comment]
> findExplicitReferences doesn't handle CXXDependentMemberExpr and friends as part of refInExpr() in FindTarget.cpp. It could delegate to the heuristics in findTarget for the actual target, as some other node types do.

There's an open design / UX question here. Consider the `bar1` and `bar2` methods below:

```c++
template <typename T>
struct Foo {
  int waldo;
  void bar1(Foo f) {
    f.waldo;   // we *know* this resolves to the decl in the primary template
  }
  template <typename U>
  void bar2(Foo<U> f) {
    f.waldo;   // this *probably* resolves to the decl in the primary template,
               // but it could also resolve to a decl in a specialization
  }
};
```

My intention in filing this bug report was to change our coloring from `DependentName` to `Field` for the first case only ("member of current instantiation"), while leaving the second case as `DependentName`.

However, we could considering changing the coloring from `DependentName` to `Field` in both cases. (This is what your suggested implementation strategy would do, and it's arguably easier to implement than distinguishing the two cases.)

The UX question here is: what is more valuable to the user -- knowing that a name is dependent, or having more detailed information about its kind than type vs. value (e.g., field vs. method)?

**Comment by HighCommander4** [comment]
> The UX question here is: what is more valuable to the user -- knowing that a name is dependent, or having more detailed information about its kind than type vs. value (e.g., field vs. method)?

(We could also conceivably add finer-grained dependent highlightings like `DependentField` and `DependentMethod`, but we'd need to retain `DepndentValue` for the case where we can't resolve the name to a decl at all, not even heuristically.)

**Comment by sam-mccall** [comment]
There are quite a few places where clangd trades off precision for usability.
I'm comfortable if highlighting, go-to-def, hover etc treat `waldo` in bar2 as if it were resolved.

I think there's value in exposing strict semantics to people who really want it, e.g. i'd like to turn the "dump AST for selected node" code action (behind `-hidden-features`) into a real feature one day. But IME tools that make reasonable assumptions about dependent code are more useful than those that don't try. (We need to be a little careful about what's reasonable!)

**Comment by HighCommander4** [comment]
> I'm comfortable if highlighting, go-to-def, hover etc treat `waldo` in bar2 as if it were resolved.

Thanks for your thoughts. I agree, and I will re-purpose this issue to make this broader change.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D76896)
