### ISSUE TITLE
`textDocument/hover` Markdown and double escaping of punctuation characters

### ISSUE THREAD

**Issue by danielmartin** [clangd/clangd#301]
My editor is getting the following Markdown as part of the `textDocument/hover` payload:

```
Result: {
  "range": {
    "start": {
      "line": 46,
      "character": 37
    },
    "end": {
      "line": 46,
      "character": 54
    }
  },
  "contents": {
    "value": "### variable `annotationBuilder`  \n\n---\nType\\: `FBS::AnnotationPropertiesBuilder`  \n\n---\n```cpp\n// In AnnotationFlatbufferTest_PrimitiveTypeDeserialization_Test::TestBody\nFBS::AnnotationPropertiesBuilder annotationBuilder(builder)\n```",
    "kind": "markdown"
  }
}
```

As you can see, the colon after "Type" is double escaped: `Type\\:` This is causing that my editor shows an additional backlash in its documentation window:

<img width="384" alt="Screenshot 2020-03-04 at 11 54 48 PM" src="https://user-images.githubusercontent.com/1573717/75960116-ca0f8280-5ebf-11ea-8bf3-f714eedcd9d1.png">

If I paste the same Markdown into a GH issue and preview it, the same additional backslash is rendered:

<img width="665" alt="Screenshot 2020-03-05 at 8 48 37 AM" src="https://user-images.githubusercontent.com/1573717/75960139-d1369080-5ebf-11ea-9c99-ab523a2e72a6.png">

The double backlash seems to be added at https://github.com/llvm/llvm-project/blob/c0b27c489104f6c3c055a3ac1573d05393fe32eb/clang-tools-extra/clangd/FormattedString.cpp#L42 I'm not very familiar with Markdown syntax so my question is, is it really needed to add a double backslash here or a single one would suffice? I'm deciding If this is something that should be fixed server-side or client-side. Thanks.

**Comment by sam-mccall** [comment]
There's just a single backslash in the content, the second one is in the JSON encoding of the string only.

That said, we're indeed doing too much escaping here - it's not necessary and apparently not recognized by GFM.

Over escaping also causes problems in coc.nvim that chooses to display and highlight the markdown.
