### ISSUE TITLE
Completion fails in templates on windows due to implicit -fdelayed-template-parsing

### ISSUE THREAD

**Issue by jabra98** [clangd/clangd#302]
Hello, it seems like the auto completion provided by the vscode clangd extension (for windows) stops working when writing templates. Here a short clip of this behavior: https://streamable.com/6qri0
The version of my clangd application is 9.0.1 (x64 windows). Is there anything I can do?

**Comment by sam-mccall** [comment]
Can you try adding the flag `-fno-delayed-template-parsing` to your compile_commands.json?
(Or if you don't have one, create compile_flags.txt in the same dir with just that string)

MS compilers have a nonstandard way of handling templates, clang has an option to emulate it and turns it on by default on windows (maybe it's needed to parse common libraries?). I was vaguely aware of this but hadn't realized it  might break completion entirely in templates!

**Comment by sam-mccall** [comment]
Long-term fix is to make this work by default in clangd, either by turning off delayed template parsing in general or just in code completion.

Short-term, I think you should be able to add -fno-delayed-template-parsing to CMAKE_CXX_FLAGS and rebuild (unless your build actually relies on this behavior)

**Comment by sam-mccall** [comment]
I'd actually like to keep this open and do a fairly limited fix.

We discussed this and I don't think we can just turn delayed template parsing off in clangd, we'll break people including slightly old windows headers.
However the file the user's editing is unlikely to be broken, and clang will let us build the preamble (headers) with delayed template parsing and then the main-file without it.

So the most-limited fix: turn it off for the code-completion parse only. In most cases of invalid code clang will realize "missing typename" and recover, only in pathological cases will it actually parse the code differently. Users will probably never notice.
The more ambitious fix: turn it off for the main-file parse as well as code-completion, while keeping it on for preamble builds. That means that users will see errors for non-standard code, but only in the file they're actually editing.

**Comment by jabra98** [comment]
Is there an equivalent to `-fdelayed-template-parsing` flag but for MSVC?

**Comment by sam-mccall** [comment]
@kadircet this came up again (code completion
