### ISSUE TITLE
Make {}-braces trigger signature help

### ISSUE THREAD

**Issue by jabra98** [clangd/clangd#306]
It would be nice if writing {} would also trigger argument popups just like () does after declaring a variable. Short clip:
https://streamable.com/cu0zs

**Comment by sam-mccall** [comment]
(This feature is called "signature help" in LSP and internally)

This is definitely possible but requires some work: signature help is triggered by callbacks in the parser, and the I think the parser takes totally different paths for `Foo(...)` and `Foo{...}`.

A couple of other wrinkles I can think of:
 - need to decide what (if anything) to do about constructors taking a `std::initializer_list`
 - it might be harder to resolve bare initializer lists (such as `Foo x = {a, b}` or `return {x}`). This is probably very similar to designated-initializer code completion that @kadircet added recently in https://github.com/llvm/llvm-project/commit/42e9478e0bbbe3468a74d9d07275a61558b220c4

**Comment by jabra98** [comment]
Any ETA for that?

**Comment by sam-mccall** [comment]
No, this isn't something anyone's actively working on. Patches are welcome!

**Comment by HighCommander4** [comment]
See also this newer video illustration (from #726): https://u.teknik.io/wDfuF.mp4
