### ISSUE TITLE
VS Code clangd extension re-parses when close and open the same file

### ISSUE THREAD

**Issue by gkoulin** [clangd/clangd#312]
In VS Code

1. Open a file in a temporary window. Wait for it to parse.
2. Follow a symbol to another file. This closes the current file and opens the new file as temporary.
3. Go back to first file. clangd starts parsing all over again.

Note: reparsing does not happen if you keep the file open.

**System information**
clangd version 10.0.0 (https://git.llvm.org/git/clang.git 65acf43270ea2894dffa0d0b292b92402f80c8cb) (https://git.llvm.org/git/llvm.git 2c4ca6832fa6b306ee6a7010bfb80a3f2596f824)
vscode-clangd 0.0.21

**Comment by sam-mccall** [comment]
That sounds like the intended behaviour: vscode tells clangd the file is closed, clangd cleans up the associated resources. If you open the file again, it needs to be parsed again.

I think it's unlikely we'll change this behaviour directly - keeping files around in case you open them again would tie up a lot of memory. But we may over time make the header parsing more efficient/persistent e.g. by caching header modules on disk.

**Comment by HighCommander4** [comment]
When I started using vscode, one of the first setting changes i made is:

```
  "workbench.editor.enablePreview": false,
  "workbench.editor.enablePreviewFromQuickOpen": false,
```

This causes all opened editors to stay open, thereby avoiding this issue.

**Comment by gkoulin** [comment]
Thanks for the feedback. @sam-mccall you speak of caching on disk. There already a .clangd folder being created with some sort of cache index. What purpose does this serve?

**Comment by kadircet** [comment]
it only stores information about symbols, which is used in actions like code completion, signature help, cross references, rename, go-to-definition etc.

**Comment by gkoulin** [comment]
It seems that while it is parsing headers the cached information is not available.

**Comment by kadircet** [comment]
it depends, some functionality requires semantical information before accessing that cache, otherwise symbols are ambiguous. but for example code completion doesn't require parse to finish, and should be able to provide you with symbols coming from all over the project.

**Comment by juxeii** [comment]
I would also like too see some improvement here. Would be great if the user could decide what a "high" memory load is.
For example: how about an option which lets the user specify to cache the latest n opened files?
Or, what about caching one editor session's files?

**Comment by cswrd** [comment]
I made the same experience. I thought something was wrong with my VS Code remote container setup until I found this thread.

@kadircet you said it's working as intended. In my legacy code base each reopen of a file takes >10s until clangd finished and I can use all features. 2 Questions:

1. Is it correct when the VS Code status bar shows: "_clangd: parsing includes, running Update (1)_" during that period?
2. My first theory was, it doesn't use the index file. So I've set the background index to skip and deleted the index for that file. Shouldn't it recreate an idx file, when I open the source file again? imo the logs (verbose) neither give a hint about writing an index file nor applying an existing one.

**Comment by HighCommander4** [comment]
>     1. Is it correct when the VS Code status bar shows: "_clangd: parsing includes, running Update (1)_" during that period?

Yep.

>     2. My first theory was, it doesn't use the index file. So I've set the background index to skip and deleted the index for that file. Shouldn't it recreate an idx file, when I open the source file again? imo the logs (verbose) neither give a hint about writing an index file nor applying an existing one.

No, building an AST for a file (done on file-open) and adding a file to the index (done in the background if the indexer is enabled) are two separate operations. Information from the AST is used to populate the index, but the index doesn't store the entire AST, but rather information used to cross-reference symbols between different files and used to implement queries such as "find all references in project".

**Comment by lixin-wei** [comment]
> But we may over time make the header parsing more efficient/persistent e.g. by caching header modules on disk.
@sam-mccall Caching AST in disk makes more sense, I've been always wondering why we can't do this yet. Is there any plan for this?

**Comment by lixin-wei** [comment]
> But we may over time make the header parsing more efficient/persistent e.g. by caching header modules on disk.

@sam-mccall Caching AST in disk makes more sense, I've been always wondering why we can't do this yet. Is there any plan for this?

**Comment by WayneZhenLi** [comment]
When you say keeping files around in case I open them again will take a lot of memory, how much memory are we talking about here exactly?  A couple gigabytes?  I open and close files a lot and it's really annoying have to wait like 10 seconds to reparse the file every time I open a file.  It's especially annoying when I'm navigating a large codebase and I have to quickly flip through a ton of different files.  I'd be more than happy to sacrifice a couple gigabytes to avoid this and I think most people would agree

**Comment by WayneZhenLi** [comment]
Moreover, when I'm navigating a large codebase it becomes very messy to keep all the files open.

**Comment by feiyehua** [comment]
Same problem. Maybe cacheing some recently closed files' AST can be a good idea?
