### ISSUE TITLE
vscode: Couldn't start client Clang Language Server

### ISSUE THREAD

**Issue by anon-ord** [clangd/clangd#318]
Please describe the problem.
While using vscode 1.43.2 in remote-server mode, I'm getting a 'Couldn't start Client Language Server' error notification.  clangd is in my bash path on the remote workstation.

Either (a) I have a misconfiguration.  I'm assuming that the language server should be running on the remote workstation where the code is or (b) this is a bug.

**Logs**
Where would I find this log given the above configuration ?

**System information**
Output of `clangd --version`:
Editor/LSP plugin: vscode, plugin versions 0.0.21 and 0.0.20 (I tried both)
Operating system:  server host:  Debian 5.2.17-1rodete3  client host: macOS 10.15.3

**Comment by hokein** [comment]
I suspect that the clangd binary path is not set properly, could you paste the debug log?

You can find the log in VSCode:  “Clang Language Server” in the dropdown of the Output panel (View -> Output).

![image](https://user-images.githubusercontent.com/2557445/77703035-18dda300-6fba-11ea-81f6-fe1d060cafbf.png)

**Comment by anon-ord** [comment]
thanks for the tip on that debug log:

[Error - 1:17:00 PM] Starting client failed
Error: Unsupported server configuration {
    "command": "",
    "args": [
        "--suggest-missing-includes",
        "--clang-tidy",
        "--log=verbose",
        "-background-index=true"
    ]
}

Pretty sure I never modified this.  Not sure what is not supported or where it came from.

**Comment by sam-mccall** [comment]
It looks like the path to clangd ("Clangd: Path") in the settings is set to "".
The default value is "clangd".

Are you sure you didn't change this in the remote extension settings?

**Comment by anon-ord** [comment]
The problem I was having was that the vscode-clangd extension wasn't able to parse "${workspaceFolder}" from the path I had specified to the clangd binary.
