### ISSUE TITLE
clangd sames do not support cross-build args

### ISSUE THREAD

**Issue by haolongzhangm** [clangd/clangd#319]
example: 

host x86-linux

vim open arm target headers ,like arm_neon.h , which u can find at LLVM project

then clangd will err log:

"'neon_vector_type' attribute is not supported for this target [attribute_unsupported]
"

so any plan or ways to let clangd support cross-build supoort ?

**Comment by kadircet** [comment]
you must have a compile_commands.json specifying correct target triplet for cross compilation.

if you have that set, please provide clangd logs, while running clangd with `-log=verbose`. it will contain compile commands picked up by clangd.

**Comment by haolongzhangm** [comment]
@kadircet  

for arm: i add flags : -march=armv5 for  cross, is this correct? 


then i get debug log  below detail: 

V[17:06:40.288] Failed to load shard: /home/zhl/tmp/ycm_clangd_cross_example/1.c
V[17:06:40.288] Indexing /home/zhl/tmp/ycm_clangd_cross_example/1.c (digest:=EFC020C7974A8F38)
I[17:06:40.288] Updating file /home/zhl/tmp/ycm_clangd_cross_example/1.c with command 
[/home/zhl/tmp/ycm_clangd_cross_example]
clang-tool -Wall -Wextra -std=c++14 -x c++ -I /usr/include -I /usr/local/include -D__ARM_NEON -march=armv5 /home/zhl/tmp/ycm_clangd_cross_example/1.c -fsyntax-only -resource-dir=/home/zhl/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/9.0.0
V[17:06:40.297] Preamble for file /home/zhl/tmp/ycm_clangd_cross_example/1.c cannot be reused. Attempting to rebuild it.
V[17:06:40.297] Ignored diagnostic. unknown target CPU 'armv5'
V[17:06:40.297] Ignored diagnostic. unknown target CPU 'armv5'
V[17:06:40.297] Ignored diagnostic. valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
V[17:06:40.297] Ignored diagnostic. valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
E[17:06:40.297] Could not build a preamble for file /home/zhl/tmp/ycm_clangd_cross_example/1.c
E[17:06:40.297] Indexing /home/zhl/tmp/ycm_clangd_cross_example/1.c failed: Couldn't build compiler instance
V[17:06:40.298] Ignored diagnostic. unknown target CPU 'armv5'
V[17:06:40.298] Ignored diagnostic. valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
V[17:06:44.863] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":14,"line":1},"textDocument":{"uri":"file:///home/zhl/tmp/ycm_clangd_cross_example/1.c"}}}

I[17:06:44.863] <-- textDocument/definition(2)
I[17:06:44.863] --> reply:textDocument/definition(2) 0 ms, error: invalid AST
V[17:06:44.864] >>> {"error":{"code":-32001,"message":"invalid AST"},"id":2,"jsonrpc":"2.0"}

zhl@amax-04:~/.vim/bundle/YouCompleteMe$

**Comment by kadircet** [comment]
> for arm: i add flags : -march=armv5 for cross, is this correct?

I don't think so:

```
V[17:06:40.297] Ignored diagnostic. unknown target CPU 'armv5'
V[17:06:40.297] Ignored diagnostic. valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
```

**Comment by haolongzhangm** [comment]
@kadircet  so how let clangd cross support arm? 

sames now valid target CPU values are all X86 sub cpu

**Comment by kadircet** [comment]
that's because march let's you specify a microarchitecture, you should be
using `-target`.

> @kadircet <https://github.com/kadircet> so how let clangd cross support
arm?

You should be passing the same compile commands you use to compile your
file.

**Comment by haolongzhangm** [comment]
@kadircet 

i try add "-target armv7a-none-eabi -march=armv5"  flags, 

but clangd log show:

  1 V[11:58:57.916] Indexing /home/zhl/tmp/ycm_clangd_cross_example/1.c (digest:=EFC020C7974A8F38)
33  I[11:58:57.916] Updating file /home/zhl/tmp/ycm_clangd_cross_example/1.c with command
  1 [/home/zhl/tmp/ycm_clangd_cross_example]
  2 clang-tool -Wall -Wextra -std=c++14 -x c++ -I /usr/include -I /usr/local/include -D__ARM_NEON -target armv7a-none-eabi -march=armv5 /home/zhl/tmp/ycm    _clangd_cross_example/1.c -fsyntax-only -resource-dir=/home/zhl/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/9.0.0
  3 V[11:58:57.927] Ignored diagnostic. unknown argument: '-target armv7a-none-eabi -march=armv5'
  4 V[11:58:57.928] Ignored diagnostic. unknown argument: '-target armv7a-none-eabi -march=armv5'
  5 V[11:58:57.932] Preamble for file /home/zhl/tmp/ycm_clangd_cross_example/1.c cannot be reused. Attemp


so which flags may take effect ?

**Comment by sam-mccall** [comment]
Those are two separate flags, you need two separate entries in the args array.

**Comment by haolongzhangm** [comment]
@sam-mccall  and @kadircet 


  2 I[15:33:27.417] Enqueueing 1 commands for indexing
  1 V[15:33:27.417] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"c","text":"#include \"arm_neon.h\"\n#inc    lude <stdio.h>\n\nint main() {}\n","uri":"file:///home/zhl/tmp/ycm_clangd_cross_example/1.c","version":1}}}
28  
  1 E[15:33:27.418] Tried to create storage for empty directory!
  2 I[15:33:27.418] <-- textDocument/didOpen
  3 V[15:33:27.418] Failed to load shard: /home/zhl/tmp/ycm_clangd_cross_example/1.c
  4 V[15:33:27.418] Indexing /home/zhl/tmp/ycm_clangd_cross_example/1.c (digest:=41A375BF20BA5CDE)
  5 I[15:33:27.418] Updating file /home/zhl/tmp/ycm_clangd_cross_example/1.c with command
  6 [/home/zhl/tmp/ycm_clangd_cross_example]
  7 clang-tool -Wall -Wextra -std=c++14 -x c++ -I /usr/include -I /usr/local/include -D__ARM_NEON --target=armv7a-none-eabi -march=armv5 /home/zhl/tmp/yc    m_clangd_cross_example/1.c -fsyntax-only -resource-dir=/home/zhl/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/9.0.0
  8 V[15:33:27.424] Preamble for file /home/zhl/tmp/ycm_clangd_cross_example/1.c cannot be reused. Attempting to rebuild it.
  9 V[15:33:27.436] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 10 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 11 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 12 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 13 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 14 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 15 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 16 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 17 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 18 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 19 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t    his target
 20 V[15:33:27.437] Dropped diagnostic: /home/zhl/tmp/ycm_clangd_cross_example/1.c: in included file: 'neon_vector_type' attribute is not supported for t

**Comment by kadircet** [comment]
@haolongzhangm sorry i am not a cross compiling person, but it looks like you are providing wrong set of flags. There is nothing magical happening in clangd at this stage, it is just invoking the compiler with the commands you've specified and from the looks of it compiler is failing to compile with the diagnostic you've mentioned.

What compile commands are you using to compile your project(or that file), independent of clangd?

**Comment by haolongzhangm** [comment]
@kadircet  this is just test example, from the log command should be :

clang-tool -Wall -Wextra -std=c++14 -x c++ -I /usr/include -I /usr/local/include -D__ARM_NEON --target=armv7a-none-eabi -march=armv5 /home/zhl/tmp/yc m_clangd_cross_example/1.c

**Comment by kadircet** [comment]
right, I can see that.

What i was trying to say is, these compile commands are not enough to compile that file. You can try executing:

```
clang -Wall -Wextra -std=c++14 -x c++ -I /usr/include -I /usr/local/include -D__ARM_NEON --target=armv7a-none-eabi -march=armv5 /home/zhl/tmp/yc -c m_clangd_cross_example/1.c
```

which should fail with similar diagnostics.

**Comment by haolongzhangm** [comment]
@kadircet @sam-mccall  thanks for u help
