### ISSUE TITLE
invalid AST error, Code: -32001 (v10.0, VSCode, Windows)

### ISSUE THREAD

**Issue by sebmarchand** [clangd/clangd#321]
I'm getting an error when trying to use Clangd 10.0 with VSCode on Windows (with clang-cl.exe):

[Error - 3:48:57 PM] Request textDocument/documentLink failed.
  Message: invalid AST
  Code: -32001 

This happens with all the file I open in VSCode. I'm using the binaries from  https://releases.llvm.org/download.html

Full log (from start of VSCode to the error) here: https://pastebin.com/nqcsp6Rk

**Comment by sam-mccall** [comment]
Key driver errors from the log:

> drv_out_file_argument_with_multiple_sources
> Cannot specify '/Foobj/base/util/memory_pressure/memory_pressure/system_memory_pressure_evaluator_win.obj' when compiling multiple source files

> fe_expected_compiler_job
> Unable to handle compilation, expected exactly one compiler job in ...

(That "invalid AST" error message is terrible, we should fix it)

**Comment by sebmarchand** [comment]
Not sure if it's useful as all the information is probably in the previous log but here's my compile_command entry for this file 


  {
    "directory": "C:\\src\\chrome\\src\\out\\Release",
    "command": "..\\..\\third_party\\llvm-build\\Release+Asserts\\bin\\clang-cl.exe --driver-mode=cl /showIncludes:user -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\win_sdk\\Include\\10.0.18362.0\\um -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\win_sdk\\Include\\10.0.18362.0\\shared -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\win_sdk\\Include\\10.0.18362.0\\winrt -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\win_sdk\\Include\\10.0.18362.0\\ucrt -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\VC\\Tools\\MSVC\\14.23.28105\\include -imsvc..\\..\\third_party\\depot_tools\\win_toolchain\\vs_files\\9ff60e43ba91947baca460d0ca3b1b980c3a2c23\\VC\\Tools\\MSVC\\14.23.28105\\atlmfc\\include -DUSE_AURA=1 \"-DCR_CLANG_REVISION=\\\"n345635-5d881dd8-1\\\"\" -D_HAS_NODISCARD -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_NO_AUTO_LINK -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/boringssl/src/include -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:twoPhase /Zc:sizedDealloc- /X -fmsc-version=1916 /guard:cf,nochecks -m64 /Brepro -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wthread-safety -Wextra-semi /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-pointer-to-int-cast /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi -ftrivial-auto-var-init=pattern /MT -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare /TP /wd4577 /GR- -I../../buildtools/third_party/libc++/trunk/include /c ../../base/util/memory_pressure/system_memory_pressure_evaluator_win.cc /Foobj/base/util/memory_pressure/memory_pressure/system_memory_pressure_evaluator_win.obj /Fd\"obj/base/util/memory_pressure/memory_pressure_cc.pdb\"",
    "file": "../../base/util/memory_pressure/system_memory_pressure_evaluator_win.cc"
  },

**Comment by sam-mccall** [comment]
First obvious question is why the driver is seeing multiple jobs/input files here, it doesn't jump out at me but I don't know clang-cl well.

**Comment by abique** [comment]
I also have the issue.

**Comment by abique** [comment]
Actually I disabled GCC's pre-compiled headers and it seems to work now.

**Comment by kadircet** [comment]
the first thing i noticed is existence of `/showIncludes:user`, which printed text to stdout and mangled channel between clangd and lsp client. Even though there are a couple unknown flags to me, none of them seem to be related to precompiled headers.

the `/showIncludes:user` one is fixed at head currently, can you try again with a clangd built at head(or from our weekly releases at https://github.com/clangd/clangd/releases) ? @sebmarchand

**Comment by sebmarchand** [comment]
I'm now using Clangd ToT and it work fine! I think that we can close this issue as it was only happening with clangd 10.0
