### ISSUE TITLE
Hang with Clangd 11.0 in VSCode on Windows

### ISSUE THREAD

**Issue by sebmarchand** [clangd/clangd#322]
Clangd 11.0 seems to hang when used with VSCode on Windows. If I press ctrl-space to get the autocomplete suggestions I get the "loading..." tooltip but it gets stuck there. Here's a full log of what happen when hitting ctrl-space: https://pastebin.com/Ngf9r6fE

**Comment by sam-mccall** [comment]
The weird thing is those logs show several completely reasonable request/responses. 

My best guess is recently we added some logic to the VSCode plugin that intercepts/transforms results. I'd expect to see either some results or a JS stacktrace though. @hokein any ideas?

When completion is stuck in this way, do other features (go to definition) still work?
Does completion itself ever work, or always gets stuck on loading?

**Comment by sam-mccall** [comment]
(based on the log, I don't see any reason to believe this is OS-specific, but it's probably VSCode-specific)

**Comment by sebmarchand** [comment]
Thanks for looking a this!

Ha maybe, Go-to definition also doesn't work. Everything always get stuck on loading and never completes.

**Comment by hokein** [comment]
The log looks quite reasonable to me. To verify it is VSCode-specific, @sebmarchand could you please try other editors like vim to see whether you can reproduce the issue?

**Comment by sebmarchand** [comment]
I've just confirmed that it works fine in Sublime Text, so it is a VSCode-specific issue! Where should I report this?

**Comment by hokein** [comment]
yeah, it looks like vscode-specific (probably windows-specific as well?), two possible reasons: 

1) our vscode extension is doing something wrong - we should fix it by ourselves
2) a bug in vscode, we should report it to [upstream](https://github.com/microsoft/vscode/issues)
 
it is unclear to me whether 1) or 2) causes it, could you try clangd with a simple `hello-world.cpp` on vscode?

**Comment by sebmarchand** [comment]
I've tried this with a simple hello world on VSCode on Windows and Clangd seems to work just fine. I've copied the compile command file from my Chromium repo (the one where I'm hitting the issue) and tweaked it to build my hello_world.cc file (so it's the same compiler, same flags etc).

**Comment by aeubanks** [comment]
I think I'm running into this as well (trying to use clangd/vscode on the LLVM codebase). I ran vscode with some logging output, this appeared right after I attempted a hover and looks relevant:

[17436:0423/173743.984:INFO:CONSOLE(3983)] "Error: Header must provide a Content-Length property.
        at StreamMessageReader.onData (c:\Users\aeubanks\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.23\node_modules\vscode-jsonrpc\lib\messageReader.js:163:27)
        at Socket.<anonymous> (c:\Users\aeubanks\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.23\node_modules\vscode-jsonrpc\lib\messageReader.js:148:18)
        at Socket.emit (events.js:203:13)
        at addChunk (_stream_readable.js:295:12)
        at readableAddChunk (_stream_readable.js:276:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: file:///C:/Users/aeubanks/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (3983)

**Comment by brianosman** [comment]
FYI: Pretty sure I'm hitting this too, on a smaller codebase (a library used within Chromium). It spent a while indexing everything, and then every VS Code initiated operation appeared to hang. The clangd Output window in VSC made it look like the server was responding, but the editor never did anything.

**Comment by aeubanks** [comment]
I manually replayed some of the requests vscode makes to clangd. It looks like clangd is outputting some extra lines on stdout (I made sure to suppress stderr):

Content-Length: 1511

{"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",">",":"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticHighlighting":{"scopes":[["variable.other.cpp"],["variable.other.local.cpp"],["variable.parameter.cpp"],["entity.name.function.cpp"],["entity.name.function.method.cpp"],["entity.name.function.method.static.cpp"],["variable.other.field.cpp"],["variable.other.field.static.cpp"],["entity.name.type.class.cpp"],["entity.name.type.enum.cpp"],["variable.other.enummember.cpp"],["entity.name.type.typedef.cpp"],["entity.name.type.dependent.cpp"],["entity.name.other.dependent.cpp"],["entity.name.namespace.cpp"],["entity.name.type.template.cpp"],["storage.type.primitive.cpp"],["entity.name.function.preprocessor.cpp"],["meta.disabled"]]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":2,"typeHierarchyProvider":true,"workspaceSymbolProvider":true}}}Note: including file: ../llvm/include\llvm/ADT/Twine.h
Note: including file:  ../llvm/include\llvm/ADT/SmallVector.h
Note: including file:   ../llvm/include\llvm/ADT/iterator_range.h
Note: including file:    C:/PROGRA~2/MICROS~1/2017/PROFES~1/VC/Tools/MSVC/14.16.27023/include\iterator
Note: including file:     C:/PROGRA~2/MICROS~1/2017/PROFES~1/VC/Tools/MSVC/14.16.27023/include\istream


Looks like it's printing includes: https://github.com/llvm/llvm-project/blob/4cf73a3fc665743474cfe96cbb51bffabea0255f/clang/lib/Frontend/HeaderIncludeGen.cpp#L61.
Is https://bugs.llvm.org/show_bug.cgi?id=44092 related?

**Comment by kadircet** [comment]
thanks for digging into this @aeubanks!, your findings seem to be correct.

apparently there's a compile flag called `/showIncludes` which prints output to `llvm::outs()` (or to `llvm::errs()` in presence of other outputting flags, like `/E`, yikes :/

There are command line adjusters for stripping output generating options, I suppose we should also filter that in there or maybe finally start controlling the cc1 opts struct instead of doing the messy string manipulations.
