### ISSUE TITLE
clangd suggests wrong header for int64_t

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#327]
since system header mapping only contains it as `std::int64_t` we fail to remap `int64_t` into `<cstdint>` and insert implementation header that's platform/stdlib dependent, e.g. `<bits/stdint-intn.h>`.

repro:

```cpp
#include <cstdint>
int64_t^
```

**Comment by sam-mccall** [comment]
I think this is a dup of #68 

Pretty sure we should just map them in both std:: and ::. Heard a convincing argument from absl folks that the C++ stdlib is basically forced to export the unqualified symbols and the wiggle room left by the standard isn't usable in practice.

**Comment by kadircet** [comment]
movin discussion to #68
