### ISSUE TITLE
Go-to-definition for broken function calls

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#33]
If we fail to produce a full, typechecked expression, go-to-definition won't resolve symbols - even in cases where there's only one function overload candidate (and it wasn't satisfied).

This is really common when trying to get a call right.

e.g.
```
void foo(char*X) {
  foo(1); // go to defintion on "foo" doesn't work
}
```

(And probably other constructs too, function calls are just the most obvious)

**Comment by sam-mccall** [comment]
We also don't seem to build an AST when out-of-line defining a member function that doesn't exist.
(Related because I think the solution here might be building recovery ASTs in more contexts)

**Comment by HighCommander4** [comment]
Even if there are multiple overload candidates, we could offer all of them as results (as `textDocument/definition` supports returning multiple locations, presumably with the idea that clients will list them in a popup or something and allow the user to choose one to navigate to).

**Comment by HighCommander4** [comment]
Another very common use case for this is changing a function signature: you might update a call site first, and then expect that go-to-definition on the call site still takes you to the definition so you can update that.

(Even more commonly for methods: you update the declaration first, and expect that go-to-definition still takes you to the out of line definition so you can update that.)

**Comment by sam-mccall** [comment]
Yes, these are all really annoying and have a common fix. I had a prototype for generating dummy expressions in these contexts, but the fix is in the guts of clang and needs to be designed pretty carefully. Ilya's going to look into how best to add this and possibly reconcile with existing machinery like TypoExpr

**Comment by HighCommander4** [comment]
For reference, I believe the patch being referred to is [this one](https://reviews.llvm.org/D69330).

**Comment by tbodt** [comment]
What's the status of this? The patch linked above seems to have been accepted (though not landed).

**Comment by kadircet** [comment]
it has a parent patch that's still under review https://reviews.llvm.org/D65591

**Comment by hokein** [comment]
I'm picking up the work from Ilya, the plan is to land the recovery expression patches in Q1

- [ ] 1.  refactor: move the computing-dependency code to a dedicated file, https://reviews.llvm.org/D73638, ready for review 
- [ ] 2. introduce the error bit https://reviews.llvm.org/D65591, ready for review.
- [ ] 3. reduce the binaryOperator to make space for the extra "error "bit, https://reviews.llvm.org/D75443: we need to wait for @mibintc to move the FPoption to trailing object
- [ ] 4. reduce spurious "using template keyword" diagnostic: https://reviews.llvm.org/D65592, working on it.

- [ ] 5. land the final patch of introducing the recovery expression https://reviews.llvm.org/D69330: working on this, there are some new issues when rebasing to master.

dependencies: `(1, 3) -> 2 -> 4 -> 5`

**Comment by hokein** [comment]
so I'd consider this is done, at least the initial stage -- all patches were landed (and it works well on  the above mention case), and this feature is hidden under the `--recovery-ast` flag, currently it is off by default, but we're going to turn it on in the near future.

We have further development/enhancement plan (e.g. cover more cases, preserve types when possible), I'd open separate issues to track them.
