### ISSUE TITLE
textDocument/hover isn't showing function comments

### ISSUE THREAD

**Issue by thegala** [clangd/clangd#334]
Hello, 
I have problem with textDocument/hover with C. Basically when I call for function description without opening file I only got function without it's comment.
I tried this with simple HelloWorld.
Here are log files from that session. First I called textDocument/hover without opening file where function is defined. Next call was with previously open function declaration file.
This is issue I opened for coc.nvim if you want to more information https://github.com/neoclide/coc.nvim/issues/1745.
Problem is appearing in both nvim, and VSCode.

Log file
https://gist.github.com/8674ad280ebb278b934783492afdc0b0.

**Comment by kadircet** [comment]
It has been fixed with clangd 10. You can find it in https://releases.llvm.org/download.html#10.0.0

**Comment by thegala** [comment]
Thx.
