### ISSUE TITLE
System headers not found when linking -stdlib=libc++  

### ISSUE THREAD

**Issue by thejohnfreeman** [clangd/clangd#338]
Test case [here](https://github.com/thejohnfreeman/try-clangd). It's a hello world configured to compile with clang++ and `-stdlib=libc++`. It builds and runs on my machine (details below). CMake produces this `compile_commands.json`:

```js
[
{
  "directory": "/home/jfreeman/code/try-clangd/build",
  "command": "/usr/bin/clang++    -stdlib=libc++   -o CMakeFiles/main.dir/main.cpp.o -c /home/jfreeman/code/try-clangd/main.cpp",
  "file": "/home/jfreeman/code/try-clangd/main.cpp"
}
]
```

With this `compile_commands.json`, I get two diagnostics: `'cstdio': file not found` and `Use of undeclared identifier 'std'`. I've attached the log as [bad.log](https://github.com/clangd/clangd/files/4484245/bad.log).

If I remove the `-stdlib=c++` option from `CXX_FLAGS`, then the diagnostics go away. I've attached this log as [good.log](https://github.com/clangd/clangd/files/4484247/good.log).

**System information**
Output of `clangd --version`: `clangd version 10.0.0-++20200412073924+50d7e5d5e7d-1~exp1~20200412054519.133`
Editor/LSP plugin: Neovim + vim-lsp
Operating system: Ubuntu 19.10 Eoan, clang-10, clangd-10, libc++-10-dev, libc++abi-10-dev

**Comment by kirillbobyrev** [comment]
Thank you for a detailed description and a repo! I've been trying to reproduce it on different systems while slowly getting to the setup which is the closest to yours, but I didn't manage to get the same issue on my machines.

**Comment by OlegOAndreev** [comment]
FWIW, I had the same issue but it has been fixed in 11.0.0-rc1 for me.

**Comment by kirillbobyrev** [comment]
> , I had the same issue but it has be

Good to know, thank you!

I'm closing this issue, let me know if the issue persists and we will investigate it.

**Comment by samvv** [comment]
Could this issue be re-opened? I'm having the exact same problem in a relatively complex project. As soon as I add `-stdlib=libc++` either as `CXXFLAGS` or inside `CMakeLists.txt` under `CMAKE_CXX_FLAGS`, clangd does not find a single system header.

I'll try to create a minimally reproducible example.

**Comment by samvv** [comment]
Found the issue: it was probably a version incompatibility between a very recent CMake (3.20.2) and an older ccache (3.7.7). Disabling ccache made everything work just fine. Sorry for the noise!
