### ISSUE TITLE
Don't pollute the home directory, use XDG_CACHE_HOME

### ISSUE THREAD

**Issue by VojtechStep** [clangd/clangd#341]
When clangd cannot determine the project path of a file, it dumps its index files into `~/.clangd/index` (or at least that's what I gathered from [this part](https://github.com/llvm/llvm-project/blob/a7afb211dc460bd4cfb2542ad1f9b05876b57ba1/clang-tools-extra/clangd/index/BackgroundIndexStorage.cpp#L115) of the indexer source code, and it's consistent with my experience).

I think this should not be the case, and instead the tool should conform to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), specifically use `$XDG_CACHE_HOME/clangd` as its base directory.

I'm not at all familiar with the code base, but I guess fixing this should be as easy as not setting the default to HomeDir.

**Comment by sam-mccall** [comment]
This seems reasonable, there must be equivalents for other platforms too.
AFAICS there's no abstraction for this in LLVM unlike `llvm::sys::path::home_directory` which is probably why it started this way.

Patches welcome!

**Comment by VojtechStep** [comment]
I would like to submit a patch, but I'm not sure what the correct procedure is. Do I need to recreate this bug report in the LLVM bug tracker? I assume I submit the patch via Phabricator, tagging you as a reviewer (based on CODE_OWNERS)?

**Comment by kadircet** [comment]
no need to duplicate the issue in llvm bug tracker, just sending a patch
through phabricator is enough.

you can check https://llvm.org/docs/Contributing.html#how-to-submit-a-patch for
details.

**Comment by philip1987** [comment]
First off, thank you for fixing this. How can I get this patched version of clangd? I am on MacOS running `clangd version 10.0.1` (installed through home brew) and it does not seem to be implemented there yet.
I already have the following line in my .zshenv `export XDG_CACHE_HOME=$HOME/.cache
`
Yet `~/.clangd/index` keeps getting recreated.

**Comment by c02y** [comment]
Why do I get `.cache/clangd/index` inside the project directory.

**Comment by sam-mccall** [comment]
@philip1987 Sorry it's way too late now but you can see the releases it was included in on the commit page, the fix was in 11.0.

@c02y the XDG_CACHE_HOME is only used for indexing when clangd can't determine the project root (e.g. for indexing system headers). `$PROJECT/.cache/clangd/index` is the intended location for project index data. We chose this mostly to give the data the right lifetime: if you delete the source tree then the index is automatically gone too. We don't currently have an option to disable this, but you can symlink .cache somewhere else if you prefer.

**Comment by AlynxZhou** [comment]
> @c02y the XDG_CACHE_HOME is only used for indexing when clangd can't determine the project root (e.g. for indexing system headers). `$PROJECT/.cache/clangd/index` is the intended location for project index data. We chose this mostly to give the data the right lifetime: if you delete the source tree then the index is automatically gone too. We don't currently have an option to disable this, but you can symlink .cache somewhere else if you prefer.

Maybe an option to disable this or move this outside is better, sometimes I contribute to other projects and I always need to check whether I committed `.cache` by mistake. And if I add a line in `.gitignore`, I have to explain to other devs about this change, other people may not use clangd for complete or format.

**Comment by AlynxZhou** [comment]
Or maybe some options like `--compile-commands-dir` is good, so I can put `.cache` under project build dir, which is already in `.gitignore` for most projects.

**Comment by HighCommander4** [comment]
Adding an option to customize the index storage location is tracked in https://github.com/clangd/clangd/issues/184
