### ISSUE TITLE
Black and white lists of files to index

### ISSUE THREAD

**Issue by Yanpas** [clangd/clangd#342]
I have a very big project with about 6k files. Most of them don't make any sence to me. Allow filtering files to index via black and white lists as ccls does.

**Comment by HighCommander4** [comment]
This would definitely be useful.

I currently accomplish this outside of clangd by using [`jq`](https://stedolan.github.io/jq/) to filter my `compile_commands.json` file.

**Comment by kadircet** [comment]
out of curiosity, do you want to blacklist those because symbols coming from those parts of the project are undesired(e.g in code completion) or do you want to disable it to reduce work while indexing?

**Comment by Yanpas** [comment]
@kadircet the second, it's tons of work (40 mintutes), on my laptop(!!!). 1 thousand of files which I'm interested in are in libsrc folder (librariers) and the rest projects don't depend on each other mostly and located in various folders. Here is how I do it in ccls:

```json5
        "ccls.index.initialBlacklist" : [".*"], // or *, both regexp and globs work
	"ccls.index.initialWhitelist" : [
		"libsrc",
		"project1",
		"project2"
	],
```

**Comment by Yanpas** [comment]
ccls shows progress as well, it would be useful:
![image](https://user-images.githubusercontent.com/7345761/79703161-9d1e0000-82b2-11ea-8323-fec0d3907937.png)

**Comment by kadircet** [comment]
> @kadircet the second, it's tons of work (40 mintutes), on my laptop(!!!). 1 thousand of files which I'm interested in are in libsrc folder (librariers) and the rest projects don't depend on each other mostly and located in various folders. Here is how I do it in ccls:

Yeah it makes sense, we lack the mechanism to specifiy options that are both user and project specific(e.g. those white/black lists).

> ccls shows progress as well, it would be useful:

that's also available with clangd, but you'll need a newer version. IIRC clangd-10 should be enough, you can also use the weekly build in https://github.com/clangd/clangd/releases

**Comment by sam-mccall** [comment]
This is implemented in latest snapshots and upcoming clangd 11: http://clangd.llvm.org/config.html

**Comment by arekzaluski** [comment]
@sam-mccall Could you please point at the exact config for it, with an example? I do not see an option in documentation (http://clangd.llvm.org/config.html) to blacklist/whitelist a folder.

**Comment by kadircet** [comment]
It is the `Index.Background` option, which is the first example in `Index` section. but you need to combine it with `If.PathMatch`, e.g:
```
If:
  PathMatch: some/sub/dir/.*
Index:
  Background: Skip
```

**Comment by arekzaluski** [comment]
@kadircet This option disables only background indexing. I'm looking for an option that completely disables C/C++ intellisense for files in a given blacklisted folder.
