### ISSUE TITLE
File completion of header paths

### ISSUE THREAD

**Issue by oblitum** [clangd/clangd#366]
Hi, I'm using coc-clangd now, previously I used ccls, sorry I'm not sure whether this should be a coc task or server but it used to work with ccls.

When completing headers, I'm not getting file path completion, just direct headers, for example, `#include <i` provides iostream and others as options, but `#include <some_dir/` won't show any file in that include directory, seems I need to type some char for them to show (same for `#include <`).

**Comment by oblitum** [comment]
As an aside I also miss code fold implementation from ccls.

**Comment by sam-mccall** [comment]
Ah, good catch.
We send trigger characters of `.>:` so coc only sends us a completion request after typing those characters or identifier chars. We don't trigger on / or the < or " at the start of a directive (though if you somehow force a request there, it does work).

Fix would be to 

> As an aside I also miss code fold implementation from ccls.

Yep, this is #310, waiting for someone to get around to it. For C++, it seems like there's a bunch of different kinds of foldable regions that (from the implementation side) are almost unrelated. We have to start somewhere, please comment on the bug which are most important to you.

**Comment by oblitum** [comment]
thx for response.

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D79456
