### ISSUE TITLE
__builtin_types_compatible_p( ) prevents proper parsing of a symbol

### ISSUE THREAD

**Issue by kting28** [clangd/clangd#373]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

```
#define CHECK_AND_CALL(_op_a, _op_b, _op_c)\
  do {\
    if (__builtin_types_compatible_p(typeof(_op_a), int) &&\
        __builtin_types_compatible_p(typeof(_op_c), int))\
      _op_a+_op_b+_op_c;\
  }while (0);

int main() {
  int a;
  int b;
  int c;
  CHECK_AND_CALL(a, b, c);
}
```

Here clangd is not able to parse the `a` and `c` (no definition/references found) but `b` in the macro is behaving correctly (i.e. editor can look up the definition). If I remove the __builtin_types_compatible_p( ) check, all parameters can be looked up in the "CHECK_AND_CALL" macro

What's puzzling is that clangd 9.0.0 does not exhibit the same behavior.
**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
Output of `clangd --version`: clangd version 10.0.0
Editor/LSP plugin:  vim-lsp and vscode
Operating system: Linux

**Comment by kting28** [comment]
I tried a few experiments in fact any complex  if/else statements inside the macro above has the effect.

**Comment by sam-mccall** [comment]
This works again in latest clangd. (You can grab a snapshot from the github releases, or wait for the 11 release).

I'm not sure exactly which commit fixed it, but we revamped go-to-definition between 9.0 and 10.0 which caused the regression (and also improved a bunch of things!), and the fix must have come too late.

**Comment by kting28** [comment]
Compiled from latest and can confirm this works again. Thanks
