### ISSUE TITLE
"WarningsAsErrors" in .clang-tidy makes it ignore "NOLINT" comments

### ISSUE THREAD

**Issue by RedDwarf69** [clangd/clangd#375]
With clangd 10.0.0, from Fedora 32, the following code

```
auto main() -> int {
    // NOLINTNEXTLINE(cppcoreguidelines-owning-memory)
    auto *a = new int;
}
```

shows a "problem" in VSCode if the .clang-tidy file contains `WarningsAsErrors: '*'`.

clang-tidy itself ignores de warning/error.

**Comment by HighCommander4** [comment]
Thanks for the report.

A [comment](https://github.com/llvm/llvm-project/blob/47b95d7cf462b824b2fbea1eb1a64e9c3eaa1a95/clang-tools-extra/clangd/ParsedAST.cpp#L317) in the clangd source says the following:

```
  // Check for warning-as-error.
  // We deliberately let this take precedence over suppression comments
  // to match clang-tidy's behaviour.
```

However, looking at the clang-tidy source, it actually lets suppression comments take precedence over warning-as-error (consistent with what you report), and looking at the history, this has been the case already when the above clangd comment was written.

So... I don't know what I was thinking when I wrote that comment :/

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D79691)
