### ISSUE TITLE
"#pragma once" being ignored results in complain about redefined symbol

### ISSUE THREAD

**Issue by RedDwarf69** [clangd/clangd#377]
With the attached project [clangd_bug.tar.gz](https://github.com/clangd/clangd/files/4601383/clangd_bug.tar.gz)
With clangd 10.0.0 on Fedora 32, with VSCode.

Results in this error

![with_include](https://user-images.githubusercontent.com/1608276/81446242-70069400-9172-11ea-8f0a-0278e6c6bf55.png)

If I remove the recursive (but protected with "#pragma once") #include I get this other error

![without_include](https://user-images.githubusercontent.com/1608276/81446316-87de1800-9172-11ea-9324-a3e9a2127e73.png)

**Comment by brianlheim** [comment]
I'm also seeing this! I wrote a post about it on the Discourse forum here: https://llvm.discourse.group/t/is-there-an-easy-workaround-for-this-clangd-behavior-re-pragma-once/3585. The reproducer I found is mostly the same, so I'll just quote the rest of my post:

> As I understand it, this happens because:
> 
>  - a.hpp includes a.ipp and a.ipp includes a.hpp
>  - both use pragma once (and not include guards)
> - when a.hpp is the target of clangd’s --check, it effectively is treated as the “main file” which means #pragma once is not treated the same way as if the header were being included in, for example, main.cpp above
> - therefore, a.hpp ends up being included twice and that results in the redefinition of void g()
> 
> The practical result of this is that when I’m editing a header with this structure in VSCode, there’s always an error indication from clangd on the line where the impl header is included, which is quite distracting. I’m wondering if there’s a way to work around that?
> 
> Some ideas I’ve already considered:
> 
> - switch to traditional include guards: works, but it would be difficult to change this within my organization
> - remove the include at the start of the impl header: leads to tons of errors when editing impl header files, because the declarations from the header are no longer visible
> - remove the include at the end of the regular header: no-go, because including the header should always result in an include of the corresponding impl header
> 
> I’m not sure it makes sense because I’m fairly new to this tooling, but I would almost like for clangd (or this extension?) to “synthesize” a cpp file including the header, since that’s how it will be encountered in compilation. (Then again, I can also see how all of this could be avoided by just using traditional include guards in the first place!)

**Comment by smeznaric** [comment]
A simple rule that I think would help:

- If there is a .h/.hpp file that includes a .inl/.ipp file then, for the purposes of linting the inl file, treat it as though it includes .h/.hpp file at the beginning 
- Then we can remove the #include <h_file.h> from the inl line and everything should be happy!
- Some people might include h file in inl file because they might use other tools that aren't able to recognise that inl file doesn't need the include. If so, ignore that include when linting the h file.
