### ISSUE TITLE
Include completion fails at the end of file

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#38]
Input (no newline at the end!):
```cpp
/// file comment
#include "llvm/Sup
```
Expected:
A completion for 'Support' folder.

Actual:
Global completion results.

The problem goes away if I linebreak at the end of the first line.

**Comment by HighCommander4** [comment]
This seems to work fine in trunk.

**Comment by lh123** [comment]
+ clangd version:  clangd version 11.0.0 (https://github.com/llvm/llvm-project.git 3badd17b6989621b5aa2732800f697dabbda034d)
+ OS: Windows 10

I think this issue still exists.

![image](https://user-images.githubusercontent.com/10697249/84476669-0e7d9c00-acc1-11ea-89ea-3a7ea9ada167.png)
