### ISSUE TITLE
Show access specifiers as part of the Hover information

### ISSUE THREAD

**Issue by danielmartin** [clangd/clangd#382]
One piece of information about a method definition that it's sometimes needed is if its member access is public, private, etc. This can be useful, for example, if you are inside a `.cpp` file and want to know quickly if a member is accessible outside of the class or not. Knowing if a field is protected can also be useful if we consider them a code smell and would like to refactor them.

I propose this can be shown as part of the hover Markdown contents. For example, instead of 

```
instance-method HoverInfo::present

...
// In ...
```

Clangd would show

```
public instance-method HoverInfo::present

...
// In ...
```

Any thoughts? As far as I know, visibility, linkage, member access is not trivially computable in Clang, but maybe if you restrict it to a couple of easy and useful cases (like member method accessibility), the feature can be reliable and useful to programmers, without much impact on the information that is already available in the hover popup. Thanks.

**Comment by hokein** [comment]
this sounds a useful feature to me.

And sometimes I'd like to know whether a member function is overriding a virtual member from a base class, would be nice to show it in hover as well.

**Comment by Trass3r** [comment]
Looks like this is implemented now.

**Comment by danielmartin** [comment]
Yes, I implemented this in https://github.com/llvm/llvm-project/commit/6407aa9d2e0e225bc81d3b2602d6e6ed79912ec2 I'll close the issue.
