### ISSUE TITLE
why all checks not work? 

### ISSUE THREAD

**Issue by mumin16** [clangd/clangd#384]
why all checks not work? This is my settings.json:

{
    "clangd.arguments": [
        "--suggest-missing-includes",
        "--log=verbose",
        "-pretty",
        "-background-index=true",
        "--clang-tidy",        
        "--clang-tidy-checks=*",
        "--compile-commands-dir=build"
    ]
}

is there complete settings.json?

**Comment by kadircet** [comment]
Hi Mumin,

Due to the way we integrate with clang-tidy some of the checks wouldn't trigger. But most of them should still be working. If you are not getting any diagnostics at all, could you please share the logs?

Are there some specific checks you are missing?

**Comment by mumin16** [comment]
settings.json's configration is true?

**Comment by sam-mccall** [comment]
Sorry, I don't think there's a clear enough bug or feature request here.

The issue tracker can't be a discussion or support forum, as this makes it harder to track work on the project.
General discussion belongs on the [LLVM discourse forum](https://llvm.discourse.group/c/llvm-project/clangd).
