### ISSUE TITLE
[vscode] attribute in macro can break syntax highlighting

### ISSUE THREAD

**Issue by kiwixz** [clangd/clangd#385]
Parsing of a string as an attribute argument breaks vscode syntax highlighting.
clangd is still understanding the code.

Image of the problem:
![not working](https://user-images.githubusercontent.com/8900147/81689609-bc93ed00-945a-11ea-9701-27bc7014f7d7.png)

Source code:
```cpp
#pragma once

#if 1
#   define MACRO(attr) [[attr]]
#else
#   define MACRO(attr)
#endif

struct S {
    MACRO(deprecated("some unrecognized string size() some unrecognized string"))
    int f() { return 0; }

    int other;
};
```

**System information**
Output of `clangd --version`:  clangd version 11.0.0 (https://github.com/llvm/llvm-project cc9fefec4368efb64e78dee1109e342b37d21bca)
Editor/LSP plugin:  vscode-clangd
Operating system:  Ubuntu 18.04.4

**Comment by hokein** [comment]
I believe this is a bug in vscode semantic highlighting, move it to https://github.com/jeff-hykin/cpp-textmate-grammar/issues/474
