### ISSUE TITLE
A way to silence `drv_unknown_argument` warnings.

### ISSUE THREAD

**Issue by randrej** [clangd/clangd#386]
I use `clangd` with a `compile_commands.json` file that's generated by CMake. CMake is invoked with `gcc` as the compiler for this project, and a `gcc`-specific argument (`-fstack-usage`) gets put into `compile_commands.json`.

`clangd` warns me that `-fstack-usage` isn't a valid argument on line 1 of every single file, which is annoying.
Is there a way to silence this warning? If not, I think it'd be nice from a usability point of view to add a way to disable this warning.

Thanks!

**Comment by sam-mccall** [comment]
Not today. There's a few ways we could go here:
 - once we have config, we will allow rule-based filtering of args from the compilation database
 - we could have a hard-coded filter filter well-known ignored args
 - we could have a hard-coded blacklist of well-known false positives from drv_unknown_argument
 - we could filter drv_unknown_argument entirely. I worry this is sometimes a symptom of an argv we failed to properly parse, though.

**Comment by randrej** [comment]
Any of your suggestions would do, really, rule-based filtering being the best.

An alternative would be to allow disabling checks, so you could disable `drv_unknown_argument` errors altogether.

**Comment by sam-mccall** [comment]
As of clangd 11, you can create a config file in the project or user config dir that strips `-fstack-usage`

http://clangd.llvm.org/config.html

And specifically:
```
CompileFlags:
  Remove: -fstack-usage
```

Customizable filtering of diagnostics is also an interesting idea we should keep in mind, but I think the original need is addressed (at least in the latest snapshots)
