### ISSUE TITLE
No completion for tok::kw___builtin_va_arg

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#39]
**Input:**
```cpp
#include "clang/Basic/TokenKinds.h"
auto t = tok::va^
```

**Expected:**
`tok::kw___builtin_va_arg` is in the results.

**Actual:**
empty results.

**Comment by kirillbobyrev** [comment]
We don't have `va` bigram for this identifier. This is a deliberate choice we made to make the index take less space at the cost of slightly reduced quality.

[D113995](https://reviews.llvm.org/D113995) will make `tok:kw^` and `tok::bu^` match but we'll stop producing bigrams after processing the second segment in the identifier.
