### ISSUE TITLE
Invalid "unused function" warning in nested template calls

### ISSUE THREAD

**Issue by hakonrk** [clangd/clangd#397]
I'm using clangd 10.0.0 via the VIM code completion plugin "YouCompleteMe" (YCM). With template-heavy code, I sometimes get invalid warnings about unused functions. Here's a reduced testcase that reproduces the problem when clangd tries to compile it with `-Wall`:

```c++
#include <algorithm>
#include <iostream>
#include <vector>

// This static function is incorrectly reported as unused...
static double area(double r)
{
    return 3.14 * r * r;
}

template <typename Iter>
void print_sum_area_of_circles(Iter begin, Iter end)
{
    double sum_area = [&]() {
        double sum = 0.0;
        std::for_each(begin, end, [&](auto const& radius) {
            sum += area(radius);  // ... even though it is used here
        });
        return sum;
    }();
    std::cout << sum_area << "\n";
}

int main(int argc, char* argv[])
{
    std::vector<double> radiuses{ 1.0, 2.0, 3.0 };

    print_sum_area_of_circles(begin(radiuses), end(radiuses));

    return 0;
}
```

The `area()` function is reported as unused if clangd tries to compile the code with `-Wall`. The code compiles without warnings with `clang++`.

I asked the YCM developers about it, and they assume it happens because clangd intentionally does not instantiate all templates to make it run faster. The problem goes away if I replace `std::for_each` with a regular for loop, thereby lowering the level of nested template calls by one, so their hypothesis sounds plausible.

Feel free to close this issue if this is working the way you intended (that is, the gains in speed are so significant that it is worth sacrificing correct behavior in code that nests template calls).

**Comment by hokein** [comment]
Yeah, this is a known issue, tracking in #363.
