### ISSUE TITLE
Index the standard library

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#403]
Ideally opening a blank c++ file (no compilation database etc) would still have the standard library available in the index for code completion.

Not sure on the best mechanism: background index?

**Comment by kadircet** [comment]
another idea:
what about calling addDocument with a phantom file containing all the stdlib headers at startup and then making them available in dynamic index? this solution has the potential downside of emitting diagnostics though, also requires re-indexing whole stl with each clangd-instance.

my 2cents on background index solution:
it might be off, or busy building other TUs. And even after indexing finishes we might not build a new serving structure for a while (I don't think anything apart from being off is really practical though). 

OTHO, using background indexing implies that we can index a phantom file with a constant path and share it among other projects/clangd-instances, without re-indexing all the time. this has the downside of showing wrong-ish symbols in case of projects making use of custom tool-chains, again i don't think this is a big problem though (as suggested headers will likely be correct, only the symbol might be missing from time to time, which will be diagnosed).

sounds like background-index is a better fit overall, as enqueueing a phantom file to it seems less hacky than calling add/removeDocument on ClangdServer.

**Comment by HighCommander4** [comment]
It looks like this was implemented in clangd 15 (https://reviews.llvm.org/D115232) and enabled by default in clangd 16 (https://reviews.llvm.org/D133968). Can the issue be closed?

**Comment by HighCommander4** [comment]
Closing per previous comment.
