### ISSUE TITLE
C++17 as default version.

### ISSUE THREAD

**Issue by zlianon** [clangd/clangd#405]
`clangd` by default show completions from `C++14`, this can be changed via `compile_commands.json`, but it's very irritating when you just want to open single `C++` file and make small prototype using `C++17` features without generating or manual creating `compile_commands.json` for that single file.

`C++14` is pretty old, I think is time to go forward.
Or, another option is to add a new command to `clangd` for setting default `C++` version, something like this: `clangd --std=c++17`.

Sorry for my bad English. Thanks!

**Comment by sam-mccall** [comment]
We're unlikely to diverge from `clang` here.

However we will add ways to configure the compile flags used, on a per-project or global level.

You'll be able to put something like this in ~/.config/clangd/config

```
Flags:
  Append: [ -std=c++17 ]
```

**Comment by hokein** [comment]
`clangd.fallbackFlags` can help in some degree.

if you just want to create a single C++17 file (no specific compile command is found), you can use the `"clangd.fallbackFlags": ["-std=c++17"]` (both coc-clangd, vscode-clangd are supported).

**Comment by sam-mccall** [comment]
Oh right, I missed this was without a compilation database.
You can set fallback flags, or also create `compile_flags.txt` containing `-std=c++17` which acts like a simple compile database.

Going to close this for now, as there are a few workarounds and this will definitely be covered by the config work too.
