### ISSUE TITLE
Definition not found when providing no arguments on functions with parameters 

### ISSUE THREAD

**Issue by zlianon** [clangd/clangd#410]
I understand that `clangd` can't find definition when some functions/methods are overridden (different number of parameters, types...) and you provide nothing, but I think is better to `clangd` try to find FIRST definition by NAME when can't by parameters, like in this case.

I hope I put things together well, I'm pretty new in C++.
Sorry for my bad English.

**Logs**
https://asciinema.org/a/cr78gWj8OvtzCtTOgFnCZpJt9
https://gist.github.com/zlianon/7f5d4b12bee69b5bf53c2bc999e71abe

**System information**
Output of `clangd --version`: `Ubuntu clangd version 10.0.1-++20200529022935+a634a80615b-1~exp1~20200529003545.39`
Editor/LSP plugin: `Neovim`/`coc.nvim` with `coc-clangd`
Operating system: `Ubuntu 20.04 (Docker)`

**Comment by HighCommander4** [comment]
It works for me if I run clangd with `--recovery-ast=true`. This is an experimental feature that was added recently (see #33) and will become the default in the future.

**Comment by hokein** [comment]
Yeah, `--recovery-ast` can help in this case. It should be flipped on by default soon-ish.

To use this feature, you'd need a new version clangd, clangd 10 is not enough, consider using weekly snapshots at https://github.com/clangd/clangd/releases.
