### ISSUE TITLE
Parse bodies of std::{make_unique,forward} in preamble

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#412]
These functions are tiny and thus cheap to parse. They're mostly used in function bodies so won't get instantiated much in the preamble.

But this will allow us to expand `make_unique` when it's used in the main file, and thus provide diagnostics.

It also opens the door to providing signature help (by looking inside the function body to see where the args get forwarded).

**Comment by HighCommander4** [comment]
It's worth noting that some codebases may have other functions than these two standard ones, that serve a similar purpose.

cquery, which special-cases "make" functions for a somewhat related reason (so that "find references" on constructors finds the call sites of "make" functions), applies its heuristic to [every function whose name starts with `make`](https://github.com/cquery-project/cquery/blob/70c755b2e390d3edfb594a84a7531beb26b2bc07/src/clang_indexer.cc#L2139).

**Comment by gislan** [comment]
This could be another use case for a per-codebase config files. You'd still want some good default heuristic, but for cases it misses you could configure it via config.

**Comment by sam-mccall** [comment]
Yeah, there's definitely a few strategies here:
 - hardcoded list, anyone else is out of luck
 - heuristics: e.g. parse functions that are textually short and/or most-used per the index (requires a bunch of infra work)
 - just make it a setting (whitelist function)

The considerations for what makes a good/bad tradeoff are subtle - I think we should probably be pretty conservative about them, and think pretty carefully initially about new examples. If it's hard to make good decisions with the implementation in mind, it's going to be challenging at best for users.

`make_unique` is an easy win (and justifies the feature even if we never add anything else):
 - it's cheap - one statement, no types instantiated (that aren't already in the signature)
 - parsing it reveals a function (constructor) call where errors are common
 - it's incredibly widely used 

`make_shared` *appears* similar but is a clear loss:
 - it's expensive, instantiating several class templates
 - it's useless: the valuable constructor call is hidden in a different template with a private name
 - it's widely used (less so than make_unique)

`forward` is a loss too, I was mistaken about this one: 
 - it's cheap to parse, though instantiated a *lot* from within templates
 - and widely used
 - but it only helps with data flow analysis (maybe some clang-tidy checks at the margin), it's not needed for diagnostics

Before making this anything other than a whitelist, I'd really like to see examples that test the boundary.

**Comment by sam-mccall** [comment]
Going to close this for now - I'd expect make_unique covered a large fraction of the viable cases here, we can reopen if we find more.

**Comment by Trass3r** [comment]
Did this also fix `make_shared`?

**Comment by HighCommander4** [comment]
> Did this also fix `make_shared`?

No, this change was specific to `std::make_unique`. The reason for not including `make_shared` is discussed above:

> `make_shared` _appears_ similar but is a clear loss:
> 
>    * it's expensive, instantiating several class templates
> 
>    * it's useless: the valuable constructor call is hidden in a different template with a private name
> 
>    * it's widely used (less so than make_unique)
