### ISSUE TITLE
Not possible to specify a specific C++ version when also working on C files

### ISSUE THREAD

**Issue by Cannedfood** [clangd/clangd#431]
It is currently not possible to use this Extension for C *and* specify a specific C++ version:

If you use `-std=c++20`, and open a C file you get the following error (at the first character in the file):
> Invalid argument '-std=c++20' not allowed with 'C' clang(drv_argument_not_allowed_with)

You can also not just force it to be treated as C++ with `--language=c++`:
> Unable to handle compilation, expected exactly one compiler job in ' "/usr/bin/clang-tool" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "# freetype2" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mthread-model" "posix" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib/clang/10.0.0" "-I" "thirdparty/freetype2/include" "-I" "thirdparty/harfbuzz/src" "-I" "build" "-D" "FT2_BUILD_LIBRARY=1" "-D" "HAVE_PTHREAD=1" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/x86_64-pc-linux-gnu" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/clang/10.0.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/myname/dev/UI" "-ferror-limit" "19" "-fmessage-length" "0" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-faddrsig" "-x" "c++" "# freetype2";  "/usr/bin/clang-tool" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "# harfbuzz" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mthread-model" "posix" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib/clang/10.0.0" "-I" "thirdparty/freetype2/include" "-I" "thirdparty/harfbuzz/src" "-I" "build" "-D" "FT2_BUILD_LIBRARY=1" "-D" "HAVE_PTHREAD=1" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/x86_64-pc-linux-gnu" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/clang/10.0.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/myname/dev/UI" "-ferror-limit" "19" "-fmessage-length" "0" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-faddrsig" "-x" "c++" "# harfbuzz";  "/usr/bin/clang-tool" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "bdf.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mthread-model" "posix" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-dwarf-column-info" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib/clang/10.0.0" "-I" "thirdparty/freetype2/include" "-I" "thirdparty/harfbuzz/src" "-I" "build" "-D" "FT2_BUILD_LIBRARY=1" "-D" "HAVE_PTHREAD=1" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/x86_64-pc-linux-gnu" "-internal-isystem" "/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/clang/10.0.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++20" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/myname/dev/UI" "-ferror-limit" "19" "-fmessage-length" "0" "-stack-protector" "2" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fcxx-exceptions" "-fexceptions" "-fdiagnostics-show-option" "-faddrsig" "-x" "c++" "/home/myname/dev/ui/thirdparty/freetype2/src/bdf/bdf.c"; 'clang(fe_expected_compiler_job)

**System information**
Clangd version: clangd version 10.0.0
clangd extension version: 0.1.6
Operating system: Linux (Archlinux)

**Comment by sam-mccall** [comment]
OK, as of clangd 11 options are:
 - use compile_commands.json (preferred) - this will configure the language for each file
 - use fallback flags or compile_commands.txt if all files are the same language
 - use `.clangd` config file to specify -std=c++20 for .cpp files, or everything except .c files, or so

Regarding your example, I'm not sure where the `# freetype2` strings etc come from - I suspect in the flags you're providing? Those aren't valid clang flags, and nothing is going to strip them out.
