### ISSUE TITLE
How to make clangd works right on .c files?

### ISSUE THREAD

**Issue by BSDxxxx** [clangd/clangd#434]
![image](https://user-images.githubusercontent.com/59258592/85115426-384d3a80-b24e-11ea-8ee6-d8411b94fd61.png)
I'm wiriting c program rather than c++ with coc-clangd in neovim, but there is some annoying error hint on right syntax, how can I fix this?

**Comment by kadircet** [comment]
you should have a compile_commands.json or compile_flags.txt describing how your sources can be compiled to clangd.

you can find more details in http://clangd.llvm.org/installation.html#project-setup

if you've got that setup correctly but still getting those errors, please attach clangd logs.

**Comment by BSDxxxx** [comment]
@kadircet Could please show me an example for `C` ? I'm not familiar with clangd commands.
