### ISSUE TITLE
Is there any plan to add musl c release build?

### ISSUE THREAD

**Issue by sheeaza** [clangd/clangd#450]
As title.

**Comment by HighCommander4** [comment]
I don't understand what this means. I see [musl](https://musl.libc.org/) is a C standard library implementation, but what does it have to do with clangd?

**Comment by sheeaza** [comment]
currently I am using alpine linux for development, and it uses musl c as c library, there is not glibc on alpine linux, so is there any plan to add clangd release built against musl c? Or I will need to built one myself

**Comment by sam-mccall** [comment]
Major releases are generally packaged by distro vendors in a way that fits into their system, that's usually the *best* way to install it.

That said, for the standalone zip releases:
No plans, but patches welcome if you find an easy way to produce statically linked clangd binaries using musl - I think this could replace our current builds. (Binaries *dynamically* linked for musl systems seem niche enough that I can't see us maintaining them)

When looking at how to build portable binaries for the GitHub releases, I did briefly look at musl+static but it looked like you'd need a nonstandard toolchain to build them on the standard GitHub Actions runner images, so I didn't look much further.

**Comment by hawkinchina** [comment]
i met the same problem: clangd for alpine linux in the docker.
