### ISSUE TITLE
Find references on overriden method does not return usages of base method

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#46]
And the other way around.

Input:
```cpp
struct  Base {
  virtual void foo() = 0;
};

struct Derived : Base {
  void foo() override;
};

void test(Base *b, Derived *d) {
  b->foo(); // #1 
  d->foo(); // #2
}
```

Expected: searching for references of `Base::foo()`  and `Derived::foo()` returns both references.
Actual: `Base::foo()` returns only `#1`, `Derived::foo()` returns only `#2`.

**Comment by sam-mccall** [comment]
just noting offline discussion:
 - refs to base method should be returned when querying derived method
 - disagreement over whether refs to derived method should be returned when querying base method

**Comment by HighCommander4** [comment]
In case it helps to document some existing practice, Eclipse CDT:

>  * refs to base method should be returned when querying derived method

does this

>    * disagreement over whether refs to derived method should be returned when querying base method

does not do this.

I think the underlying mental model is that the thing being searched for is the function body / implementation. When searching for the derived implementation, every caller of the base method is at least potentially invoking that derived implementation. When searching for the base implementation, however, calls to the derived method do not invoke the base implementation (except perhaps indirectly if the derived impl delegates to the base one, but that of course is covered by the reference in the derived impl itself).

I do think it would be nice if refs to the base method were annotated as "potential matches" when querying the derived method. LSP does not currently have a way of annotating references with extra info like this, though I've [proposed this](https://github.com/Microsoft/language-server-protocol/issues/396) (with a different annotation in mind) and the response has been favourable.

**Comment by sam-mccall** [comment]
This has been implemented (references to base methods are shown, but not to derived methods)
