### ISSUE TITLE
better auto-completion for function arguments

### ISSUE THREAD

**Issue by Trass3r** [clangd/clangd#462]
For example it could suggest the respective enum members in this case (in the real code it didn't even suggest the enum type, maybe because it was further away in the code in some header file or because it was nested in a class):
```c++
enum class Flags { A, B };
enum class Flags2 { A, B };
void foo(Flags, Flags2);

void bar()
{
    foo(Flags::A, )
}
```

![grafik](https://user-images.githubusercontent.com/404623/87790369-c104c980-c840-11ea-9476-f7c5f4d221ab.png)

Tested with clangd-10.

**Comment by kadircet** [comment]
this seems to be fixed at head. it might also be a vscode related issue though (i can't test as i don't have access to it :( ) e.g. not showing results with `::` in them.

![image](https://user-images.githubusercontent.com/897555/87804906-d552c180-c854-11ea-8bcc-41f925dbe07b.png)

**Comment by HighCommander4** [comment]
Works for me with vscode.
