### ISSUE TITLE
[VSCode Extension] Not working with precompiled headers enabled.

### ISSUE THREAD

**Issue by shinjitumala** [clangd/clangd#468]
I have encountered a problem where clangd stops working when I'm using precompiled headers.

I am using cmake and clang to enable precompiled headers.
Here is the cmake code:
```
target_precompile_headers(LaboHouse PUBLIC include/labo/server/WS_Headers.h
                          extern/json/single_include/nlohmann/json.hpp)
```
Simply commenting out these 2 lines to disable precompiled headers fixes the issue.

Are there any workarounds I am not aware of? Any help would be greatly appreciated.

**Logs**
Sorry I couldn't figure out how to do this in VS Code at the moment.

**System information**
Output of `clangd --version`:  `clangd version 10.0.0`
Editor/LSP plugin: `VSCode`
Operating system: `Arch Linux (kernel: 5.7.9-arch1-1)`

**Comment by kirillbobyrev** [comment]
> Sorry I couldn't figure out how to do this in VS Code at the moment.

To access Clangd logs you can press "Problems" below ([Problems Panel](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_41.md#problems-panel)), then "Output" and switch from "Tasks" to "Clang Language Server".

**Comment by kadircet** [comment]
we've improved handling of pch related flags recently, unfortunately they are not available in clangd 10.

you can try:
- getting a build of clangd from source
- make use of one of our weekly builds https://github.com/clangd/clangd/releases
- wait until clangd-11 is out (likely about a month)

please let us know if you give one of these options a try. also please upload the logs if situation isn't resolved as pointed out by Kirill.

**Comment by shinjitumala** [comment]
@kirillbobyrev Thank you. I'll remember that for when the log is needed to debug the problem. In this particular case, it looks like this issue was known.

@kadircet Thank you. I'll try building it from source since I compile LLVM in my machine. Is it safe to assume that enabling clangd in LLVM project is enough?

**Comment by kirillbobyrev** [comment]
> @kadircet Thank you. I'll try building it from source since I compile LLVM in my machine. Is it safe to assume that enabling clangd in LLVM project is enough?

When building from source, enable clang-tools-extra via `-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"` and Clangd will be available for building. In general, it's quite safe to use the one built from sources (I think most of the time our team does that) but there are occasional regressions there sometimes. You can also build from LLVM 11 release branch, this should be very stable, but weekly snapshots are also nice!
