### ISSUE TITLE
Hover should show diagnostic before documentation

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#471]
If I hover over an identifier which has an associated diagnostic, the hover shows me the documentation associated with the identifier first, and then the diagnostic. If the documentation consists of enough lines, I have to scroll the hover window to get to the diagnostic.

I think the diagnostic is the more important piece of information, so it should come first.

**Comment by sam-mccall** [comment]
Agreed, but this is up to the editor, which one are you using?

We don't surface diagnostics in hover responses at all. We could, but I suspect that won't end well...

**Comment by HighCommander4** [comment]
I'm using the vscode. I guess I should close this as it's a vscode issue.
