### ISSUE TITLE
The Enter key causes indentation problems.

### ISSUE THREAD

**Issue by yuxiio** [clangd/clangd#472]
When you write code, the enter key causes indentation problems. It should be the problem. I don't know what to do.
Press the enter key, the text will inexplicably indent two space bar, not my tab space size. It's weird.
![SharedScreenshot](https://user-images.githubusercontent.com/60165314/88459534-babdbf80-cec8-11ea-8cf1-c6278d1e96e3.jpg)

**Comment by kirillbobyrev** [comment]
This is just a guess, but you might have "Format on typing" enabled and not having any `.clang-format`, that causes Clangd to use the default formatting style which would be LLVM; 2 spaces are used in LLVM Coding Style, so when you press Enter the indentation is adjusted accordingly. To confirm whether this is the case you could try putting the following `.clang-format` file into the same directory with the file you're editing:

```yaml
---
IndentWidth: 4
```

If that happens to be the case, you would likely want to set `--fallback-style` flag for the default formatting style.

**Comment by yuxiio** [comment]
Well, I've found the problem, it's really a .clang-format problem, the data has been revised according to your suggestion, the problem has been resolved. Thank you, I'm a novice, and I've come up with this... problems. Ha ha.
