### ISSUE TITLE
Go-to-def on template template argument

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#473]
```c++
template <typename T>
struct [[vector]] {};

template <template <typename U> class container = v^ector>
struct foo {};
```

Currently, we incorrectly target the `container` token.

**Comment by HighCommander4** [comment]
The issue is not limited to default arguments. It happens for any use of a template template argument, e.g.:

```
template <typename T>
struct vector {};

template <template <typename U> class container>
struct foo {};

foo<v^ector> X;
```

**Comment by HighCommander4** [comment]
The issue here appears to be that there is nothing in the template template argument for `SelectionTree` to latch onto, so it just selects the enclosing node.

As far as I can tell, the only nodes associated with a template template argument are:

  * A `TemplateArgumentLoc` representing the entire template argument. **This is not one the node types that `DynTypedNode` can represent.**
    * (There is a `TemplateArgument` wrapped by the `TemplateArgumentLoc`. This _can_ be represented by `DynTypedNode`, but is not suitable for selection purposes because it **does not have any location info**.)
  * A `NestedNameSpecifiedLoc` representing the qualifier of the _template-name_, if any. This part is fine; if a qualifier is present, names in the qualifier are selected correctly.
  * A `TemplateName` representing the _template-name_ itself. This is again not suitable for selection purposes because it **does not have any location info**.

@sam-mccall @hokein @kadircet -- I would appreciate some guidance here. Should we add `TemplateArgumentLoc` to the set of node types that `DynTypedNode` can represent?

**Comment by hokein** [comment]
> Should we add TemplateArgumentLoc to the set of node types that DynTypedNode can represent?

yeah, this sounds reasonable to me. It also opens the door to add a "templateArgumentLoc" AST matcher.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D85503)
