### ISSUE TITLE
clangd crashed in a complicated template type deduction

### ISSUE THREAD

**Issue by RedFog** [clangd/clangd#474]
```cpp
template<typename T>
struct Test{
    template<template<typename>class head, template<typename>class... tails>
    struct delegate{
        template<typename Y>
        struct result{
            typedef typename delegate<tails...>::template result<typename head<Y>::type>::type type;
        };
    };
    template<template<typename>class head>
    struct delegate<head>{
        template<typename Y>
        struct result{
            typedef typename head<Y>::type type;
        };
    };
    template<template<typename...>class typeclass>
    struct check{
        template<typename Y>
        struct result{
            typedef typeclass<Y> type;
        };
    };
    typedef typename delegate<
        // check<std::forward_list>::template result,
        // check<std::list>::template result,
        // check<std::deque>::template result,
        check<std::vector>::template result
    >::template result<T>::type type;
};
```

_it's just an example, in which some significant type conversions are removed._

when I typed the template arguments in the last `typedef` , clangd crashed. 

but it actually works, in clang. it's obviously `Test<int>::type` is `std::vector<int>`. and `static_assert(std::is_same_v<Test<int>::type, std::vector<int>>);` does not cause any error.

so why clangd crashed? or what mistake?

by the way, clang does not support the C++17 feature that makes `template<typename>class` match `std::vector` now? but cppreference says it does.

**System information**
clang 11.0.3, -std=c++17
VSCode 1.46.0, Xcode 11.4.1
MacOS 10.15.5

**Comment by HighCommander4** [comment]
> by the way, clang does not support the C++17 feature that makes `template<typename>class` match `std::vector` now? but cppreference says it does.

There is an entry for this on [clang's C++ status page](https://clang.llvm.org/cxx_status.html), in the C++17 table, under "Matching template template parameters to compatible arguments". The status is marked as "Partial", with the following note:

> Despite being the resolution to a Defect Report, this feature is disabled by default in all language versions, and can be enabled explicitly with the flag -frelaxed-template-template-args in Clang 4 onwards. The change to the standard lacks a corresponding change for template partial ordering, resulting in ambiguity errors for reasonable and previously-valid code. This issue is expected to be rectified soon.

**Comment by HighCommander4** [comment]
As for the crash, I haven't been able to reproduce it (testing on Linux).

Could you provide a few more specifics please:

  * The complete file contents, including any `#include` statements at the top (presumably, you need at least `#include <vector>` for the code to compile).
  * What standard library you are using (libc++ or libstdc++).
  * Is pasting the code into an empty editor enough to reproduce the error, or do I need to take some editor action like uncommenting the commented lines, or invoking code-complete somewhere?

**Comment by RedFog** [comment]
> > by the way, clang does not support the C++17 feature that makes `template<typename>class` match `std::vector` now? but cppreference says it does.
> 
> There is an entry for this on [clang's C++ status page](https://clang.llvm.org/cxx_status.html), in the C++17 table, under "Matching template template parameters to compatible arguments". The status is marked as "Partial", with the following note:
> 
> > Despite being the resolution to a Defect Report, this feature is disabled by default in all language versions, and can be enabled explicitly with the flag -frelaxed-template-template-args in Clang 4 onwards. The change to the standard lacks a corresponding change for template partial ordering, resulting in ambiguity errors for reasonable and previously-valid code. This issue is expected to be rectified soon.

okay, thanks for your help.



> As for the crash, I haven't been able to reproduce it (testing on Linux).
> 
> Could you provide a few more specifics please:
> 
> * The complete file contents, including any `#include` statements at the top (presumably, you need at least `#include <vector>` for the code to compile).
> * What standard library you are using (libc++ or libstdc++).
> * Is pasting the code into an empty editor enough to reproduce the error, or do I need to take some editor action like uncommenting the commented lines, or invoking code-complete somewhere?

```cpp
#include <vector>
#include <type_traits>

template<typename T>
struct Test{
    template<template<typename>class head, template<typename>class... tails>
    struct delegate{
        template<typename Y>
        struct result{
            typedef typename delegate<tails...>::template result<typename head<Y>::type>::type type;
        };
    };
    template<template<typename>class head>
    struct delegate<head>{
        template<typename Y>
        struct result{
            typedef typename head<Y>::type type;
        };
    };
    template<template<typename...>class typeclass>
    struct check{
        template<typename Y>
        struct result{
            typedef typeclass<Y> type;
        };
    };
    typedef typename delegate<
        check<std::vector>::template result
    >::template result<T>::type type;
};


int main(){
    static_assert(std::is_same_v<std::vector<int>, Test<int>::type>);
    return 0;
}
```
just this code could crash the clangd, and still compile correctly in **Xcode, clang -std=c++17 -stdlib=libc++**.

and I put it in an independent workspace, and set these flags
```
clang -std=c++17 -Wall -DDEBUG -stdlib=libc++
```
in compile_commands.json. clangd crashes as soon as I reopen this workspace. 

it looks like this code is thought invalid by clangd server, it crashes (5 times and gives up) when the entire typedef is written completely, rather than some editor actions make it crash.

**Comment by HighCommander4** [comment]
Thanks for the additional info. I did try your updated example with libc++ headers, and was still unable to reproduce the crash.

Maybe it's a Linux vs. Mac related difference, e.g. custom patches in Xcode's clang version, or system-specific things in the libc++ headers.

I will leave it to a Mac user to try to repro this.

**Comment by RedFog** [comment]
@HighCommander4 

clangd crashed in another situation today. so I tried to compare their similarity and finally I found a minimum code:
```cpp
template<typename Y>
struct A{
    template<typename T>
    struct B{
        typedef T type;
    };
};

template<template<typename...>class X>
struct C{
    typedef int type;
};

template<typename T>
using C_t = typename C<A<T>::template B>::type;
```
it exactly means, clangd crashes if _**an internal class template of a class template is transmitted as a template argument, in the case the enclosing class template is a dependent type**_.

so is it a bug of clangd or anything else that expose in this case?

**Comment by HighCommander4** [comment]
I do not get a crash on this reduced example, either.

**Comment by RedFog** [comment]
after clangd is updated to 11.0.0, this problem is solved.
