### ISSUE TITLE
Clangd ignores no lint comments

### ISSUE THREAD

**Issue by KingKili** [clangd/clangd#477]
Clangd ignores no lint comments in Code. The same code does not print any warnings when checked with clang-tidy.

```
int main() {
     // NOLINTNEXTLINE(cppcoreguidelines-init-variables, clang-diagnostic-unused-variable)
    bool ret;
    return 1;
}
```
**Logs**
[log.txt](https://github.com/clangd/clangd/files/4990802/log.txt)

**System information**
Output of `10.0.0 (Fedora 10.0.0-2.fc32)`:
Editor/LSP plugin: SublimeText/LSP
Operating system: Fedora 32

**Comment by HighCommander4** [comment]
Could you provide your `.clang-tidy` configuration file as well please?

**Comment by HighCommander4** [comment]
In particular, if you have `WarningsAsErrors` enabled for this check, then this is a known issue in clangd 10 that has been fixed in trunk (#375).

**Comment by KingKili** [comment]
Yes I have enabled this flag, and the issue looks very similar. I will try trunk and let you know.
[clang-tidy](https://github.com/clangd/clangd/files/4993265/clang-tidy.txt)

**Comment by KingKili** [comment]
Thanks, it is fixed on master.
