### ISSUE TITLE
Boosting of recent names in switch statements is unhelpful

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#48]
I was trying to write a switch statement for an enum

```cpp
enum {
A,
B,
C,
D,
} X;
switch(X) {
  case A:break;
  case B:break;
  case ^
}
```

was expecting at least alphabetical order, but unfortunately B popsup as first element and makes it hard to find next value. Maybe we should even demote values that we've already seen in switch statements/if else blocks?

**Comment by ilya-biryukov** [comment]
Or even remove it from completion results. Completing `B` in that case would produce a compiler error.

**Comment by kadircet** [comment]
This is fixed now, clangd no longer suggests enum values that have already been handled in a switch.
