### ISSUE TITLE
No libc++ on system and clangd does not work with libstdc++: No user feedback of problem source

### ISSUE THREAD

**Issue by matu3ba** [clangd/clangd#482]
After installation via pacman on Manjaro, the header are not found by clangd. Clang++ and g++ work fine on execution though.
Is there a helper tool to show all include paths from clang or how are they resolved?
Why are clang and clangd using different methods for header including?

compile_flags.txt
```
g++
-std=c++17
-Wall
-Wextra
-Weffc++
-Wstrict-aliasing
-Werror
# -pretty # no effect
# -log=verbose # no effect
# -I/usr/include/c++/10.1.0/ # optional different messages
```

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).
```
#include <cstdint>      /* defined int types */ // 'cstdint' file not found XOR in included file 'bits/c++config.h' file not found 
#include <iostream>     /* std::cout */ // 'iostream' not found XOR In included file 'bits/c++config.h' file not found

int32_t x; //Unknown type name 'int32_t'
  std::string string() { //use of undeclared identifier 'std' XOR No member named 'string' in namespace 'std'
   return "x";
}
```

**Logs**
I cant find a way to extract error messages as text from the setup set, since there is no parameter option example and inserting into compile_flags.txt does not work.

**System information**
Output of `clangd --version`: 10.0.0
Editor/LSP plugin: neovim NVIM v0.5.0-619-g1153ac903
Operating system: Manjaro (Arch derivate)

**Comment by kadircet** [comment]
please try without `g++` in your compile_flags.txt, it should only consist of flags without the tool name.

if it doesn't work, without clangd logs there isn't much we can do unfortunately. you can consult your plugins documentation for figuring out how to access language server's log files.

**Comment by matu3ba** [comment]
Without `g++` yields the same result. 

Is there somethinig like a complete description of `clangd lsp` and `program_build.txt`?
I dont find the specification and there is no doc folder in the source code.
In this [list](https://clang.llvm.org/docs/) clangd is also not listed and neither a spec.

I want to file a PR to nvim-lsp.

**Comment by matu3ba** [comment]
Here is my log with `--log=verbose`
I tried to use
`--query-driver=/usr/include/c++/10.1.0,` and with string quotations, but that did not fix it either.

What is `unhandled notification initialized` ?
[lsp.log](https://github.com/clangd/clangd/files/5031001/lsp.log)

The file is a header file.

**Comment by kadircet** [comment]
logs you've provided are truncated please include everything from the start, it enables us to see clangd version and flags. Also this doesn't include the diagnostics, so please wait until diagnostics show up and copy the log until the very end.

Apart from all of these, the logs look like they came from a mac machine and not a linux, and clangd version used seems to be 8, a version bundled with YCM which is pretty old nowadays. If you are trying to make use of clangd in a mac environment we had recent improvements to system library detection, so you would need to use a newer version of clangd, at least 10.

You can retrieve new versions from https://releases.llvm.org/ or https://github.com/clangd/clangd/releases.

**Comment by matu3ba** [comment]
1. Downloaded latest snapshot and moved it to `.local/bin`.
2. included the bin folder as path (at `.local/bin/clangd/bin`)
3.1 Tried to use the lsp and had the same result.
That did not work.
3.2 copy the lib file to `/usr/lib/clang/12.0.0/include`
That did not work.
3.3 copied the header files to `/usr/include/clang/Headers`.
That not work either.

The c++ headers from clang and clangd do not ship with the file `cstdint`, but `stdint.h`.
Does this break things?
What are the exact paths or how is the system library detected?

**Comment by mica100** [comment]
I had same problem. C++ System header not found by clangd (tested with 10.0.0 and 11.0.0-rc1). Problem was that clangd (and clang) detected g++-8 on my Ubuntu, while only g++-7 was installed with C++-stdlib. I found out compiling one file with clang and -E and -v option. So clang told me, that it's detected /usr/include/c++/8 as system-header include, while this dir was empty. After installing g++-8 package on Ubuntu (or only libstdc++-8-dev) clang and clangd working great.

Details found here: https://gatowololo.github.io/blog/clangmissingheaders/

**Comment by matu3ba** [comment]
@kadircet [This should be the problem](https://github.com/google/filament/issues/104).
Arch ships clang without libc++. Also the AUR is currently broken.

**Comment by matu3ba** [comment]
> I had same problem. C++ System header not found by clangd (tested with 10.0.0 and 11.0.0-rc1). Problem was that clangd (and clang) detected g++-8 on my Ubuntu, while only g++-7 was installed with C++-stdlib. 

Thanks for hinting the problem source.
I dont have any libc++ installed, because for some reason Arch decided to not ship libc++. The AUR also is also kind of broken. :-/

**Comment by kirillbobyrev** [comment]
> > I had same problem. C++ System header not found by clangd (tested with 10.0.0 and 11.0.0-rc1). Problem was that clangd (and clang) detected g++-8 on my Ubuntu, while only g++-7 was installed with C++-stdlib.
> 
> Thanks for hinting the problem source.
> I dont have any libc++ installed, because for some reason Arch decided to not ship libc++. The AUR also is also kind of broken. :-/
I've just installed libc++ from AUR: all tests green, I can compile simple code with `-stdlib=libc++`. Could you specify: in what way is it broken? I remember there were problems with libc++ on Arch in the past but I don't see any right now.

**Comment by kadircet** [comment]
> @kadircet [This should be the problem](https://github.com/google/filament/issues/104).
> Arch ships clang without libc++. Also the AUR is currently broken.
> 
> Would it be possible to do a quick checkup, if an according libc++ is provided?

You can try running:
```
clang -xc++ /dev/null -c -v -E -stdlib=libstdc++
```
(or `-stdlib=libc++` version, depending on which stdlib you are looking for)

and check for directories found after `#include <...> search starts here:`

**Comment by matu3ba** [comment]
Using cmake-generated content, ie with a vim plugin fixed the issue.

I would recommend strongly to use cmake-generated files ie with [vim-cmake](https://github.com/cdelledonne/vim-cmake) or have endless grief. 

This generated for me a g++ command which just worked.
