### ISSUE TITLE
allow supply extra args from clangd command line

### ISSUE THREAD

**Issue by ZSaberLv0** [clangd/clangd#483]
maybe something like this:

```
clangd --init='{"extraArgs":"-Ixxx"}'
```

example: the [ccls](https://github.com/MaskRay/ccls) has [clang.extraArgs](https://github.com/MaskRay/ccls/wiki/Customization#clangextraargs--clangexcludeargs)

---

why not `compile_flags.txt` :
* on different system, the header search path differs
* we may use scripts to detect actual path (typically for LSP plugins or configs)
* of course, we can use scripts to generate temporary `compile_flags.txt`,
    but that's not very convenient

**Comment by kadircet** [comment]
with the upcoming clangd-11 you can have a `.clangd` file in your project root with the following contents:

```
CompileFlags:
  Add: [-Werror, -Wall]
```

but unfortunately there's no way to do that for clangd-10. you can either wait for the release (which should happen in ~a month), fetch one of our weekly spanshots from https://github.com/clangd/clangd/releases, or try building clangd from source.

**Comment by ZSaberLv0** [comment]
`.clangd` or `compile_flags.txt` does not matter

the actual problem is, header seach path differs on different system,
typically we would use scripts to find the path and then start clangd server

generate temporary config files is not very convenient,
especially for simple project or temp or test files

**Comment by kadircet** [comment]
oh I see what you mean now. you might want to check http://clangd.llvm.org/extensions.html#compilation-commands

**Comment by ZSaberLv0** [comment]
`fallbackFlags` is what I want, thanks

PS: I'm so sorry for not finding it, but it's really hard to find the `fallbackFlags` option, maybe it's better to mention it around `compile_flags.txt`?
