### ISSUE TITLE
Is there a way to pass flags such as -ferror-limit to clangd.

### ISSUE THREAD

**Issue by it29zeni** [clangd/clangd#495]
I am working on a large code base which is nearly 15 years old. This code compiles perfectly with gcc but when clang parses the code a lot of warnings/errors are identified. This is causes clangd to stop processing those files. Fixes the errors/warnings found with clangd is nearly impossible. 

Due to this I am seeing  the following error from output screen of clangd language server. I am using clangd 10.0.0.1 which was built from source. 

failed to compile <FileName> index may be incomplete clangd.

If there was a way to pass the flag to clangd, then it will allow the clangd to scan and parse all the symbols and not stop on errors. 

I believe this may the reason why I could be seeing the following error finding in refrences. 

I have a class A with Function B defined in file1.cc and in another class E I have a pointer to object of class A and call Function B in file2.cc. When I try to find all the references of the function B it does not list the call in file2.cc. This may be because the header file was not processes and has no information of this class A and function B.

**Comment by kadircet** [comment]
i guess you already have a compilation database, so you can try amending it to contain the extra flags you want, which is a pain.

or you can build clangd 11.0, either from the source or make use of our pre-built binaries in https://github.com/clangd/clangd/releases/tag/11.0.0-rc1. We've introduced configuration support, which would allow you to specify extra args easily. you can check CompileFlags section of http://clangd.llvm.org/config.html for details.

**Comment by kadircet** [comment]
Oh forgot to mention, this might not be the root cause behind the missing symbols. IIRC clang would just stop emitting diagnostics after hitting too many errors, it would still keep parsing the rest of the file. So if you've got missing symbols it might be because there were some errors/diags preventing clang from generating the symbol completely.

**Comment by it29zeni** [comment]
Thank you. I will try out this. Is this a corresponding VSCODE clangd plugin which takes in this parameter?

**Comment by smhc** [comment]
You could try:
-extra-arg="-ferror-limit x"

I did something similar with https://github.com/clangd/clangd/issues/24
before that issue was fixed.

**Comment by sam-mccall** [comment]
You can now add extra args for parsing files using config:
https://clangd.llvm.org/config.html

```
CompileFlags:
  Add: -ferror-limit=100
```
