### ISSUE TITLE
AddUsing refactor tweak: Add option to prefix with "::" all the usings

### ISSUE THREAD

**Issue by slash-dev** [clangd/clangd#497]
It usually is safer to set the full namespace name to using declarations with the "::" prefix. For example:

`using ::My::Class`

vs 

`using My::Class`

I know not everyone has the same coding style which is why I suggest this could be determined based on the current usings code style. So if the current usings are consistently prefixed by "::" or not, do the same. If it's inconsistent or no using is set, the current behavior can be kept.

**Comment by kadircet** [comment]
@gislan

**Comment by sam-mccall** [comment]
Yeah, we've had other complaints about this.

While we can add an option, the default behavior should be as good as it can be.
The first try was "whatever the user typed", but it seems common to write `foo::bar` and `using ::foo::bar`.

Ideas for defaults:
 - qualify if :: was typed (current)
 - qualify if :: was typed OR some existing using is qualified
 - always qualify

In the distant future, it'd be nice to have a fast indexer infer the coding style of the project and use that. But we don't have the infrastructure for that today.

**Comment by gislan** [comment]
I added basic style detection - if all using statements we see have :: in front, we'll add one too. 
https://github.com/llvm/llvm-project/commit/4d90ff59ac453a67ac692ffdf8242e4cfbd2b34f
