### ISSUE TITLE
Breadcrumb bar does not include gtest name

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#500]
**Steps to reproduce**

  1. Open a clangd unit test file like `XRefsTests.cpp` in vscode
  2. Place the cursor inside any test body, e.g. `TEST(LocateSymbol, Alias)`.

**Expected results**

The breadcrumb bar contains an entry reflecting the name of the test.

I'm not asking for special handling for gtests; the generated entity name (e.g. `LocateSymbol_Alias_Test::TestBody`) would be fine.

**Actual results**

There is no such entry in the breadcrumb bar, so if the test is long, you have to scroll up to see its name.

**Comment by hokein** [comment]
Looks like the outline panel (which shares the same underlying implementation documentSymbol) has this information, it shows the generated name (`LocateSymbol_Alias_Test::TestBody`). 

I guess maybe we don't handle range/selection range properly, for macro cases.

**Comment by HighCommander4** [comment]
This is similar to (possibly the same as ) #475.

**Comment by HighCommander4** [comment]
Reduced testcase:

```c++
#define TEST(Class)                                                            \
  struct Class {                                                               \
    void Function();                                                           \
  };                                                                           \
  void Class::Function()

TEST(Class) {
  int var1;
  int var2;
}
```

**Comment by HighCommander4** [comment]
The `documentSymbol` results include both `Class` and `Class::Function`, but their ranges are `6:5-6:10` and `4:14-4:22`, respectively (and selection ranges are the same).

**Comment by HighCommander4** [comment]
So, for `Class`, the range `6:5-6:10` is reasonable -- the entire class definition occurs inside the expansion of `TEST(Class)`.

The issue is `Class::Function`. The key here is that the token `Function` does not come from a macro argument, it comes from the macro definition. As a result, the computed `selectionRange` is the occurrence of the `Function` token in the macro definition. The `range` is actually computed correctly as encompassing the macro invocation and the subsequent function-body tokens -- but this means `range` does not contain `selectionRange`. We then run the [following logic](https://github.com/llvm/llvm-project/blob/aa769358d8c80d06963d7bc529dd6edd76d3f0de/clang-tools-extra/clangd/FindSymbols.cpp#L159):

```c++
  if (!SI.range.contains(SI.selectionRange)) {
    // 'selectionRange' must be contained in 'range', so in cases where clang
    // reports unrelated ranges we need to reconcile somehow.
    SI.range = SI.selectionRange;
  }
```

and the `range` we wanted is overwritten with the much less useful `selectionRange`.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D88463)
