### ISSUE TITLE
Improve recovery for expression with access into incomplete type

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#502]
In the following code:

```c++
struct Incomplete;

struct Waldo {
  Incomplete* mIncomplete;
};

int main() {
  Waldo waldo;
  waldo.mIncomplete->Method();  // <--
}
```

on the indicated line, go-to-def does not work for either of the `waldo` or `mIncomplete` tokens. In principle it should, using recovery-ast.

**Comment by hokein** [comment]
yeah, I think this is a missing case.
