### ISSUE TITLE
clangd crashing

### ISSUE THREAD

**Issue by iraizo** [clangd/clangd#505]
Please describe the problem.
clangd crashes instantly after opening visual studio code.

**Logs**
https://hastebin.com/ferunuwogu.sql

**System information**
Output of `clangd --version`: i justus the extension (clangd) which is on 0.1.6
Editor/LSP plugin: visual studio code
Operating system: MacOS High Sierra 10.13.6 17G66 x86_6

**Comment by hokein** [comment]
Looks like our weekly-built clangd is not compatible on MacOS 10.13.

Our binary is built via GitHub Action, the CI server uses MacOS 10.15 from the log. I think we need to specify the minimal version of MacOS via `CMAKE_OSX_DEPLOYMENT_TARGET` in the build config.

**Comment by iraizo** [comment]
> 
> 
> Looks like our weekly-built clangd is not compatible on MacOS 10.13.
> 
> Our binary is built via GitHub Action, the CI server uses MacOS 10.15 from the log. I think we need to specify the minimal version of MacOS via `CMAKE_OSX_DEPLOYMENT_TARGET` in the build config.

Is there a way i can fix this on my side so i dont need to wait for a fixed build?

**Comment by hokein** [comment]
before we come up with a fix, there are a few options:

- build clangd from llvm-project source
- download the official clangd release from https://releases.llvm.org/
- install clangd via `homebrew` (`brew install llvm`)

and you need to specify the clangd binary path in `clangd.arguments` array in your vscode `settings.json`.

**Comment by iraizo** [comment]
> 
> 
> before we come up with a fix, there are a few options:
> 
>     * build clangd from llvm-project source
> 
>     * download the official clangd release from https://releases.llvm.org/
> 
>     * install clangd via `homebrew` (`brew install llvm`)
> 
> 
> and you need to specify the clangd binary path in `clangd.arguments` array in your vscode `settings.json`.

Ah i already installed llvm via homebrew, ill do that then
