### ISSUE TITLE
Type hierarchy children are sometimes limited to a subset

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#510]
Given the following three files:

`header.hpp`:
```c++
template <typename> struct RAV {};
```

`source1.cpp`:
```c++
#include "header.hpp"
struct A : RAV<A> {};
struct B : RAV<B> {};
struct C : RAV<C> {};
```

`source2.cpp`:
```c++
#include "header.hpp"
struct D : RAV<D> {};
struct E : RAV<E> {};
struct F : RAV<F> {};
```

 * if I open `source2.cpp` and perform Type Hierarchy on `RAV<D>`, I get a tree containing just three children,  `D`, `E`, and `F`.
 * If I then open `source1.cpp` and perform Type Hierarchy on `RAV<A>`, I now get a tree with all six children.
 * If I then go back to `source2.cpp`and perform Type Hierarchy on `RAV<D>` again, I again get all six children.

**Comment by HighCommander4** [comment]
Here's what seems to be happening:

During background indexing, we parse two translation units, `source1.cpp` and `source2.cpp`, picking up 3 `BaseOf` relations in each one. However, the index contents are divided into per-file "shards" which are more granular than translation units, e.g. `header.hpp` gets its own shard.

When deciding which shard gets a relation, we use [this logic](https://github.com/llvm/llvm-project/blob/b21ddded8f04fee925bbf9e6458347104b5b99eb/clang-tools-extra/clangd/index/FileIndex.cpp#L150):

>  // Attribute relations to the file declaraing their Subject as Object might
>  // not have been indexed, see SymbolCollector::processRelations for details.

Since the relation is `BaseOf`, the subject is `RAV`, which is declared in `header.hpp`, so all six relations are attributed to the `header.hpp` shard.

However, when combining the contents of the shards into a single index, in `FileSymbols::update()` we [overwrite](https://github.com/llvm/llvm-project/blob/b21ddded8f04fee925bbf9e6458347104b5b99eb/clang-tools-extra/clangd/index/FileIndex.cpp#L250) `header.hpp`'s relations in the merged index, with the `header.hpp` relations from the most recent translation unit that was processed.

So, when we index `source1.cpp`, the merged index initially has `header.hpp` -> `{A, B, C}` relations. When we index `source2.cpp`, that gets overwritten to `header.hpp` -> `{D, E, F}` relations, and the original `{A, B, C}` are lost.

In the cases where it works, which seem to require that `source1.cpp` has been opened, I am guessing the `{A, B, C}` relations are picked up from the dynamic index.

**Comment by HighCommander4** [comment]
Suggestions for how to resolve this are welcome.

  * Should we change the attribution logic, to attribute relations to the file declaring their Object? (That will fix the problem for `BaseOf`, but the problem can resurface later if we start using other relations such that a header symbol can participate as an Object for different relations in different TUs.)
  * Should we modify the logic in `FileSymbols::update()` to merge the relations per-file rather than overwrite them? (For this, I'm not sure how we would distinguish between "the header shard has different relations because they come from a different translation unit" vs. "the header shard has different relations because the header was modified".)
  * Something else?

**Comment by HighCommander4** [comment]
>    * Should we change the attribution logic, to attribute relations to the file declaring their Object? (That will fix the problem for `BaseOf`, but the problem can resurface later if we start using other relations such that a header symbol can participate as an Object for different relations in different TUs.)

In the absence of a better idea, I went with this for now.

[Proposed fix](https://reviews.llvm.org/D87256).

**Comment by kadircet** [comment]
Hi Nathan, thanks for the detailed explanation of the problem and sorry for both forgetting about sharding/merging logic in the initial design and the late reply (on my defense, i was on vacation :P)

As you mentioned storing them in Objects should stop the bleeding, but will introduce some extra semantic requirement on the Relations by saying "Object" must point at the symbol that triggered the relation (hence attribution of relation is to that file). 

Another thing we can do is, perform double attribution as we do for symbols. They are attributed to both the declaration and definition location (for a different reason, we try to ensure both declaration and definition of a symbol is available no matter which shard you've loaded). We can do the same for the relations and attribute them to both Subject and Object. That way we no longer add an extra constraint while forming a relation. But this comes at the cost of implementing a merging logic. Currently Relations coming from different slabs are just appended into a single vector in FileSymbols, after double attribution we would need to de-duplicate them before creating an index.

Does that SG?

**Comment by HighCommander4** [comment]
Thanks for the suggestion! Just to make sure I'm understanding it correctly: this would involve storing a copy of the relation in both shards (e.g. on disk)?

**Comment by kadircet** [comment]
Yes. But note that this doesn't imply doubling the on-disk size, as header shard will only be written once in the case of multiple TUs having relations with subjects from the same header. The last one to write will win the race, so we'll only have duplicates in the header for relations defined in a single TU. (and the in-memory representation is already de-duplicated)

**Comment by HighCommander4** [comment]
Hmm... this comment is making me think I don't understand the suggestion after all.

If you have a base class in `header.hpp` and a derived class in `source.cpp`, and we are attributing the relation to both the subject and the object, we will we storing the relation on disk in both the shard for `header.hpp` and the shard for `source.cpp`, right?

**Comment by kadircet** [comment]
Yes you are right. As I mentioned, things change with multiple TUs. E.g. if you have a base class defined in `a.h` and two derived classes in `b.cc` and `c.cc`.  Shard for `a.h` will only contain a single duplicate relation, either the one coming from `b.cc` or `c.cc`, whereas the shards for b.cc and c.cc will only contain relations defined in them.

Does that make sense?

**Comment by HighCommander4** [comment]
Yep, I see what you mean now, thanks! I will update the patch as suggested.
