### ISSUE TITLE
default template arguments with operator() issue

### ISSUE THREAD

**Issue by springhack** [clangd/clangd#513]
When using default template arguments with operator(), it show this, same as vscode-clangd

Repo is chromium tags/81.0.4044.92

Demo using `base/containers/flat_map.h`

Also has problem with function default parameters with operator() (eg: base::NullCallback())

![Lark20200901155806](https://user-images.githubusercontent.com/2389889/91824022-aeb5e200-ec6c-11ea-851a-2accbced8651.png)

**System information**
Output of `clangd --version`: `clangd version 10.0.1`
Editor/LSP plugin: `coc-clangd/vscode-clangd`
Operating system: `macOS Catalina 10.15.6 (19G2021)`

**Comment by HighCommander4** [comment]
To be clear: this is a false-positive diagnostic that does not occur during the actual build?

It would be useful to have complete example code that reproduces the issue.

**Comment by springhack** [comment]
@HighCommander4 after test, I found it was a problem cause by precompiled headers, not a problem of clangd, so I will close this issue, and thx for reply
