### ISSUE TITLE
Misleading references in using/typedef with template.

### ISSUE THREAD

**Issue by lightmelodies** [clangd/clangd#515]
``` c++
using X = std::vector<int>;
X x;
std::vector<double> y;
```
When invoking find-references on `X`, it suggests both `x` and `y` refer to `X`.This is misleading. We should limit the result to `std::vector<int>` rather than any instance of `std::vector`.

**Comment by HighCommander4** [comment]
[Proposed fix](https://reviews.llvm.org/D87225)

**Comment by hokein** [comment]
I think there are two separated issues: 1) xrefs on template specializations 2) xrefs on renaming-alias/non-renaming-alias

For 1), thanks for the patch! `std::vec^tor<int>` position is ambiguous, it could refer to two things: the primary template, or the template specialization `vector<int>`, question is that how do we know which one does the user want? Maybe we can borrow the idea of go-to-def on constructors:  `vector^<int>` or `vector<int>^` means the template specialization, other places like `vec^tor<int>` means the primary template.  

If we want to support this, there are a few more things:
  - extend our index to support template specializations
  - we probably want to do the same thing for go-to-def as well

For 2), we are returning refs of underlying decls if we trigger xrefs on an renaming-alias, I think we should just return refs of alias (e.g. in above example, if xrefs is invoked on `X`, showing `X` refs, and no `vector<...>`).

**Comment by HighCommander4** [comment]
Thank you, @hokein, your analysis makes sense to me.

I modified the patch to fix issue (2) instead.

For issue (1), let's defer it to another ticket, as it's more involved (requires index changes).

**Comment by HighCommander4** [comment]
> For issue (1), let's defer it to another ticket, as it's more involved (requires index changes).

Filed #536 for this.
