### ISSUE TITLE
How does `clangd` know where a function definition is when only one file has been indexed?

### ISSUE THREAD

**Issue by johndebord** [clangd/clangd#530]
How does `clangd` know where a function definition is when only one file has been indexed through the LSP (Language Server Protocol) message `textDocument/didOpen`?

This question is based off of the assumption that there is no `compile_commands.json` file for `clangd` to work with.

To the best of my knowledge `clangd` will _partially index_(?) a given file when `clangd` receives the LSP message `textDocument/didOpen` with no `compile_commands.json` file in the workspace(?).

Thus the index of the file being _partially indexed_ will only reside in RAM.

So how is `clangd` aware of definitions outside of the _partially indexed_ file when it has no awareness of any outside files?

Or is it aware?

Or is it made aware of other files by some heuristic that looks at the relative path or the includes (`#include "<filename.hpp>"`) that only reside in directories `<root-project-dir>/src` and the likes thereof?

**Comment by HighCommander4** [comment]
When clangd opens a file, it processes it as a **translation unit**. That is, it tries to process it in a similar way to how a compiler would as part of building your project.

This means that, in addition to being aware of the declarations occurring directly in the file, clangd tries to resolve the `#include` statements in the file, and if successful, it will be aware of the declarations in those files as well.

A function being called in your file must at least be declared (not necessarily defined) in some header included by that file, so, again assuming clangd can resolve the includes, it can find that declaration even if other translation units in the project (such as the one containing the function's definiion, if not inline) are not indexed.

Checking whether clangd is able to resolve a particular include can be done by performing go-to-definition on the `#include` statement itself: if the include is resolved, the editor should navigate to the included file. (In addition, clangd will usually show diagnostics for unresolved includes.)

If you're wondering _why_ a particular include is being resolved, the best way to answer that is to check the clangd log (the way to access that varies by client). When opening a file, clangd will print the **compile command** it's using to process that file. You should be able to run that command directly from the shell: if it can resolve your includes, so can clangd.

**Comment by kadircet** [comment]
That is a pretty comprehensive answer, please re-open if you got further questions.
