### ISSUE TITLE
Go to definition for auto keyword

### ISSUE THREAD

**Issue by stianval** [clangd/clangd#532]
Go to definition for auto types does not seem to work even though the type seems to be deducted correctly when hovering the auto keyword, and for suggestions when using `.` or `->` with the type

**Comment by stianval** [comment]
Wrong repo, intended for vscode plugin

**Comment by kadircet** [comment]
actually that's the correct repo. as vscode plugin is a mere proxy, it is clangd itself that doesn't handle go-to requests on `auto/decltype` keywords.

**Comment by qchateau** [comment]
I'm working on this, see https://reviews.llvm.org/D92977

**Comment by HighCommander4** [comment]
Thanks for the patch! I think we can close the bug as it has been committed.

(For future patches, if you put "fixes <link to github issue>" in the commit message, the issue will be auto-closed on commit.)
