### ISSUE TITLE
In Windows10, Can’t find standard library headers, Help me

### ISSUE THREAD

**Issue by MeYunhai** [clangd/clangd#535]
system: window10
tools: vscode, cmake, mingw64
issue:
![image](https://user-images.githubusercontent.com/38174523/93706295-66952b80-fb57-11ea-95ee-eddb2799468f.png)
CMakeList:
![image](https://user-images.githubusercontent.com/38174523/93706536-dd332880-fb59-11ea-9369-cf3455a493b7.png)
compile_commands.json:
![image](https://user-images.githubusercontent.com/38174523/93706540-ecb27180-fb59-11ea-9522-cc9270275da0.png)
settings.json:
![image](https://user-images.githubusercontent.com/38174523/93707179-eb377800-fb5e-11ea-8d61-fa68ff11fe1c.png)
log:
[log.txt](https://github.com/clangd/clangd/files/5251313/log.txt)

**Comment by ArcsinX** [comment]
Try
```
--query-driver=C:\\MinGW\\bin\\g*
```
instead of
```
--query-driver=C:\\MinGW
```

**Comment by MeYunhai** [comment]
> Try
> 
> ```
> --query-driver=C:\\MinGW\\bin\\g*
> ```
> 
> instead of
> 
> ```
> --query-driver=C:\\MinGW
> ```

I did it. Thank you very much.
