### ISSUE TITLE
--query-driver not having any effect

### ISSUE THREAD

**Issue by hsnabn** [clangd/clangd#537]
Hi, I'm trying to set up clangd with vscode, I've installed the extension and it has downloaded latest clangd. However, due to having only MinGW installed at the moment, I would like to use its header files with clangd.

I am trying to only write a small program, a C++ program (a small assignment), so I am using `compile_flags.txt`.
Contents are only `-Wall`.

I am running clangd with `--query-driver=C:\Compilers\MinGW\bin\gcc.exe` and `--log=verbose`.

I hoped that since I set the query driver clangd would pick up the relevant folders from gcc, I checked with gcc executable standalone from clean shell and it picked them up.

Looked at the `QueryDriverDatabase.cpp` for my version, [here](https://github.com/llvm/llvm-project/blob/release/10.x/clang-tools-extra/clangd/QueryDriverDatabase.cpp), and referencing with the clangd output, I only get the message that default clangd driver is not whitelisted, but no messages pertaining to gcc executable I passed as query driver.

If I am doing something wrong, please let me know. Posted an issue just in case this was a bug :).

The contents of the file are only a placeholder, but this file `grades.cpp`:
```cpp
#include <string>

int main()
{
    int x = 0;
    return 0;
}
```
gives me `'string' file not found` error (as well as unused variable `x`, that was just checking if `compile_flags.txt` worked :) )

**Logs**
[clangd_log.txt](https://github.com/clangd/clangd/files/5258069/clangd_log.txt)

**System information**
Output of `clangd --version`: clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
Editor/LSP plugin: Visual Studio Code, llvm-vs-code-extensions.vscode-clangd 0.1.7
Operating system: Windows 10 Pro x64 version 2004, OS build 19041.508

**Comment by kadircet** [comment]
`--query-driver` option on itself just specifies an allowed list of drivers to execute. The real driver paths are deduced from compile commands. Unfortunately compile_flags.txt has no way to specify the driver path, hence you need a compile_commands.json file, specifying `C:\Compilers\MinGW\bin\gcc.exe` as the driver for it to take effect.

Once it works you should see a log that looks like: `System include extractor: successfully executed`.

**Comment by hsnabn** [comment]
Ahhh, I see. I'll close the issue then, as it seems like this pretty much sums it up.

Thanks!

**Comment by LimingFang** [comment]
> 

Does it mean that if we don't specify `query-driver`, there won't be any limitation?

**Comment by kadircet** [comment]
no, it means clangd won't execute any drivers since an empty glob can't match any driver path.

**Comment by LimingFang** [comment]
Here is several case, could you check if my understanding is right?   
- No `compile_commands.json`, no query_driver option given, so clangd is not expected working?
- Generate `compile_commands.json` via cmake but no query_driver option given, so cland will use compile specified in `compile_commands.json`, right?
- No `compile_commands.json` but query_driver specified( `clang` for example), so at least clangd would work all right at least in term of c++ std library(`#include <vector>`), right?
 
Thanks for your reply!

**Comment by HighCommander4** [comment]
To review:

 1. The purpose of `compile_commands.json` is to provide clangd with include paths and other compiler flags (such as `-D SYMBOL`) needed to the files in the project. In practice this is needed for most real-world projects, but one can imagine a simple project (where, for example, all `#include` directives are expressed using paths relative to the current file, such that no `-I` flags are necessary) where it is not.
 2. The purpose of `--query-driver` is to allow clangd to query another compiler driver for its **built-in include paths**. This is only necessary in cases where the build compiler uses different built-in include paths than clang (specifically, the clang from the same package as clangd) does -- usually, cross-compilation setups (e.g. build compiler targets embedded environment), but could be some others (e.g. mingw on windows).
 3. `--query-driver` requires `compile_commands.json`, and the argument needs to match (more specifically, it needs to b e a glob which accepts) the compiler from `compile_commands.json`.

So, to answer your questions:

>     * No `compile_commands.json`, no query_driver option given, so clangd is not expected working?

Clangd will not query the compiler for its built-in include paths, but will use its own built-in include paths.

Clangd will not use any project-specific flags.

Whether or not the result "works" will depend on the project.

>     * Generate `compile_commands.json` via cmake but no query_driver option given, so cland will use compile specified in `compile_commands.json`, right?

Clangd will use the compile flags from the `compile_commands.json`, and its own built-in includes.

>     * No `compile_commands.json` but query_driver specified( `clang` for example), so at least clangd would work all right at least in term of c++ std library(`#include <vector>`), right?

This will be the same as the first scenario (clangd will use its own built-in include paths). To get clangd to query the built-in include paths of a different compiler, `--query-driver` needs to be used together with `compile_commands.json`.

**Comment by LimingFang** [comment]
Thanks for your detailed reply! I have one extra puzzles:  
If i haven't installed clang, where does  the built-in include paths of clangd come from?   For example, i have gcc installed, but i don't generate a `compile_commands.json` file.

**Comment by HighCommander4** [comment]
> If i haven't installed clang, where does the built-in include paths of clangd come from?

I think they are compiled into the libclangDriver.so (or dll) library that ships with clangd and which clangd loads.

If you have a `clang` executable in the same directory as `clangd`, then running a command like:

```
echo | clang -x c++ -E -v -
```

should get `clang` to print them.

**Comment by LimingFang** [comment]
Thanks again for your help! My final understanding is that clangd will find include path(gcc or clang) via some library, and `query-driver` is some what rubbish

**Comment by HighCommander4** [comment]
Yes, `--query-driver` is only needed in cases where the built-in include paths are not what you want for some reason (for example, they point to a standard library installation that's not present on your system, or one that's wrong for the target you're compiling for in a corss-compilation scenario).

**Comment by Michaelzhouisnotwhite** [comment]
> To review:
> 
> 1. The purpose of `compile_commands.json` is to provide clangd with include paths and other compiler flags (such as `-D SYMBOL`) needed to the files in the project. In practice this is needed for most real-world projects, but one can imagine a simple project (where, for example, all `#include` directives are expressed using paths relative to the current file, such that no `-I` flags are necessary) where it is not.
> 2. The purpose of `--query-driver` is to allow clangd to query another compiler driver for its **built-in include paths**. This is only necessary in cases where the build compiler uses different built-in include paths than clang (specifically, the clang from the same package as clangd) does -- usually, cross-compilation setups (e.g. build compiler targets embedded environment), but could be some others (e.g. mingw on windows).
> 3. `--query-driver` requires `compile_commands.json`, and the argument needs to match (more specifically, it needs to b e a glob which accepts) the compiler from `compile_commands.json`.
> 
> So, to answer your questions:
> 
> > * No `compile_commands.json`, no query_driver option given, so clangd is not expected working?
> 
> Clangd will not query the compiler for its built-in include paths, but will use its own built-in include paths.
> 
> Clangd will not use any project-specific flags.
> 
> Whether or not the result "works" will depend on the project.
> 
> > * Generate `compile_commands.json` via cmake but no query_driver option given, so cland will use compile specified in `compile_commands.json`, right?
> 
> Clangd will use the compile flags from the `compile_commands.json`, and its own built-in includes.
> 
> > * No `compile_commands.json` but query_driver specified( `clang` for example), so at least clangd would work all right at least in term of c++ std library(`#include <vector>`), right?
> 
> This will be the same as the first scenario (clangd will use its own built-in include paths). To get clangd to query the built-in include paths of a different compiler, `--query-driver` needs to be used together with `compile_commands.json`.

How to prevent clangd use it built-in lirary. Cause my include path should be in mingw64/include according to the compile_commands.json. However, the clangd gave me the headers from msvc.

**Comment by HighCommander4** [comment]
> How to prevent clangd use it built-in lirary. Cause my include path should be in mingw64/include according to the compile_commands.json. However, the clangd gave me the headers from msvc.

Using `--query-driver` as discussed above should cause clangd to use the built-in includes of your build compiler (e.g. mingw) rather than its own.

**Comment by HighCommander4** [comment]
> How to prevent clangd use it built-in lirary. Cause my include path should be in mingw64/include according to the compile_commands.json. However, the clangd gave me the headers from msvc.

Using `--query-driver` as discussed above should cause clangd to use the built-in includes of your build compiler (e.g. mingw) rather than its own.

**Comment by 71GA** [comment]
For the love of God, could ANYONE from `clangd` dev team already write a reasonable documentation with all these small details?

**Comment by HighCommander4** [comment]
We have a fair amount of coverage of this topic at https://clangd.llvm.org/guides/system-headers.

There is always room for further improvement / clarification. Clangd is an open-source project, anyone can propose a documentation (or other kind of) patch.

**Comment by HighCommander4** [comment]
I did want to clarify something I said earlier in this thread:

> > If i haven't installed clang, where does the built-in include paths of clangd come from?
> 
> I think they are compiled into the libclangDriver.so (or dll) library that ships with clangd and which clangd loads.

This made it sound like the paths are hard-coded into libclangDriver, which I don't think is the case. Rather, I believe libclangDriver contains some logic for locating the built-in include paths relative to the path of the driver, and also taking into account the target.

This is discussed in more detail in https://clangd.llvm.org/guides/system-headers#heuristic-search-for-system-headers.

**Comment by Michaelzhouisnotwhite** [comment]
> > How to prevent clangd use it built-in lirary. Cause my include path should be in mingw64/include according to the compile_commands.json. However, the clangd gave me the headers from msvc.
> 
> Using `--query-driver` as discussed above should cause clangd to use the built-in includes of your build compiler (e.g. mingw) rather than its own.

OK. I've found the solution. use ` --target=x86_64-w64-windows-gnu` to specify the mingw library.

**Comment by joaotavora** [comment]
My two cents is that I was able to use `--query-driver` successfully after carefully reading the explanations of @HighCommander4 nad @kadircet . But boy could the documentation @ https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clangd/Configuration.html see improvements :-) 

Anyway, my use case is the ESP-IDF embedded development toolkit and its `esp32` family of toolchains, for example the c++ compiler of the `esp32` toolchain usually lives at: 

`$HOME/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++`

You may have  CMake project spitting out a super-precise `compile_commands.json` that references this very compiler:

```
...
{
  "directory": "/home/REDACTED/REDACTED/build/esp-idf/xtensa",
  "command": "/home/REDACTED/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -I/home/REDACTED/REDACTED/build/config -I/opt/esp-idf/components/xtensa/include -I/opt/esp-idf/components/xtensa/esp32/include -I/opt/esp-idf/components/newlib/platform_include -I/opt/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/opt/esp-idf/components/freertos/esp_additions/include/freertos -I/opt/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/opt/esp-idf/components/freertos/esp_additions/include -I/opt/esp-idf/components/esp_hw_support/include -I/opt/esp-idf/components/esp_hw_support/include/soc -I/opt/esp-idf/components/esp_hw_support/include/soc/esp32 -I/opt/esp-idf/components/esp_hw_support/port/esp32/. -I/opt/esp-idf/components/esp_hw_support/port/esp32/private_include -I/opt/esp-idf/components/heap/include -I/opt/esp-idf/components/log/include -I/opt/esp-idf/components/soc/include -I/opt/esp-idf/components/soc/esp32/. -I/opt/esp-idf/components/soc/esp32/include -I/opt/esp-idf/components/hal/esp32/include -I/opt/esp-idf/components/hal/include -I/opt/esp-idf/components/hal/platform_port/include -I/opt/esp-idf/components/esp_rom/include -I/opt/esp-idf/components/esp_rom/include/esp32 -I/opt/esp-idf/components/esp_rom/esp32 -I/opt/esp-idf/components/esp_common/include -I/opt/esp-idf/components/esp_system/include -I/opt/esp-idf/components/esp_system/port/soc -I/opt/esp-idf/components/esp_system/port/include/private -mlong-calls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/REDACTED/REDACTED=. -fmacro-prefix-map=/opt/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\\\"HEAD-HASH-NOTFOUND\\\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -o CMakeFiles/__idf_xtensa.dir/eri.c.obj -c /opt/esp-idf/components/xtensa/eri.c",
  "file": "/opt/esp-idf/components/xtensa/eri.c",
  "output": "esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/eri.c.obj"
},
```

You'd think it is enough, but it's not, and that's where `-query-driver` comes in.  Eventually, one of these includees will look for a `machine/endian.h` which is located relative to a system include that only the `xtensa-esp32-elf-g++` compiler knows about.  So you must whitelist the compiler by passing a suitable glob to `-query-driver`.   I just passed "lazy" glob "**" which worked fine, starting `clangd` from Emacs ([eglot client](https://clangd.llvm.org/installation.html#editor-plugins)) with

```
clangd --query-driver=**
```

EDIT: After typing this I realized that this is still not enough.  See the `-mlong-calls` argument there?  I had to change it manually from `-mlongcalls` across the whole `compile_commands.json`.  The compilation line itself seems fine. AFAIK the `xtensa-esp32-elf-gcc` in question groks `-mlongcalls`, but `clangd` doesnt.  It reports this:

```
clang [drv_unknown_argument_with_suggestion]: Unknown argument '-mlongcalls'; did you mean '-mlong-calls'?
```

Maybe this is not related to `--query-driver` at all and there is a separate option to fix this.  I'll investigate.

**Comment by HighCommander4** [comment]
> But boy could the documentation @ https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clangd/Configuration.html see improvements :-)

That documentation is for llvm 10.0, which was 6 releases ago.

The corresponding link for the latest release, llvm 16.0 (https://releases.llvm.org/16.0.0/tools/clang/tools/extra/docs/clangd/Configuration.html) redirects to the clangd website (https://clangd.llvm.org/), where we have more detailed documentation, including of `--query-driver` at https://clangd.llvm.org/guides/system-headers#query-driver.

Further improvements to the documentation, or suggestions for how to make it more discoverable, are always welcome.

**Comment by joaotavora** [comment]
> That documentation is for llvm 10.0, which was 6 releases ago.

Whoops sorry. In my defense that's what Google turned up for "Clangd query-driver".

The new documentation seems much better at first sight, though there are still a couple of points i don't understand, abs and others that maybe be improved, such as how to be able to tell that querying is kicking in and exactly how. But I'll come back later with more notes after more experiments.

Thanks very much for the correction and Clangd in general.

**Comment by Spongman** [comment]
> Using `--query-driver` as discussed above should cause clangd to use the built-in includes of your build compiler (e.g. mingw) rather than its own.

I'm not seeing this behavior with `clangd version 13.0.1`:

```
clangd --query-driver=/opt/rh/devtoolset-11/root/usr/bin/g++ --check=/home/user/project/source.hpp
---
Compile command from CDB is: /opt/rh/devtoolset-11/root/usr/bin/c++ --driver-mode=g++ <flags from compile_commands.json> -resource-dir=/opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1 -- /home/user/project/source.hpp
---
internal (cc1) args are: -cc1 -triple x86_64-redhat-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name LWM2MListener.hpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/user/project/build -resource-dir /opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1 <flags from compile_commands.json> -internal-isystem /opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1/include -internal-isystem /usr/local/include -internal-externc-isystem /include -internal-externc-isystem /usr/include <more from compile_commands.json> -fdebug-compilation-dir=/home/user/project/build -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++-header /home/user/project/source.hpp
```

i don't see any indication anywhere that clangd is accessing the headers in `/opt/rh/devtoolset-11`

**Comment by HighCommander4** [comment]
> > Using `--query-driver` as discussed above should cause clangd to use the built-in includes of your build compiler (e.g. mingw) rather than its own.
> 
> I'm not seeing this behavior with `clangd version 13.0.1`:
> 
> ```
> clangd --query-driver=/opt/rh/devtoolset-11/root/usr/bin/g++ --check=/home/user/project/source.hpp
> ---
> Compile command from CDB is: /opt/rh/devtoolset-11/root/usr/bin/c++ --driver-mode=g++ <flags from compile_commands.json> -resource-dir=/opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1 -- /home/user/project/source.hpp
> ---
> internal (cc1) args are: -cc1 -triple x86_64-redhat-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name LWM2MListener.hpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/user/project/build -resource-dir /opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1 <flags from compile_commands.json> -internal-isystem /opt/rh/llvm-toolset-13.0/root/usr/lib64/clang/13.0.1/include -internal-isystem /usr/local/include -internal-externc-isystem /include -internal-externc-isystem /usr/include <more from compile_commands.json> -fdebug-compilation-dir=/home/user/project/build -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++-header /home/user/project/source.hpp
> ```
> 
> i don't see any indication anywhere that clangd is accessing the headers in `/opt/rh/devtoolset-11`

Try `--query-driver=/opt/rh/devtoolset-11/root/usr/bin/c++`; it needs to match the argv[0] of the compile command.

**Comment by Spongman** [comment]
> Try `--query-driver=/opt/rh/devtoolset-11/root/usr/bin/c++`; it needs to match the argv[0] of the compile command.

that was it. thanks!

**Comment by roussak** [comment]
I have one more use-case. I'm currently working on the project which is being built in a specially configured container. The `build/compile_commands.json` is being generated during the build. The GNU C compiler is being used to compile the sources, but because the includes are more or less different inside vs outside of the container, the `clangd` can't find/parse all the inclusions. I even copied the headers from the container, but I doesn't see a way how to make the `clangd` to search within them. The `--query-driver` option looks useless in such a case because the compilers' paths are the same inside and outside of the container. I tried to play with `-isysroot` option, but it gives nothing.

So, it would be nice if someone give me the right direction to achieve the goal.

**Comment by wrightleft** [comment]
> --query-driver=**

This is what I needed to get things going without worrying about where the compiler was. I'm using Yocto, which generates my entire build chain in a sysroot directory. I don't need to worry about the actual path to the compiler. Just do it!
