### ISSUE TITLE
clangd-indexer mentioned in docs but not included for distribution

### ISSUE THREAD

**Issue by snizovtsev** [clangd/clangd#541]
While reading docs about [indexing](https://clangd.llvm.org/design/indexing.html#static-index) I was confused because `clangd-indexer` isn't shipped with Arch Linux. First I thought that this is a trivial maintainer's bug but after unsuccessful digging into build system found that it's not included for `install` target.

Since someone on Arch Forum [faced with this independently to me](https://bbs.archlinux.org/viewtopic.php?id=244528) i think this part of documentation is a bit confusing. And as #344 declined i'm not sure that `clangd-indexer` is supposed to be in distribution. Anyway, I think the documentation should clarify status of this tool.

**Comment by kadircet** [comment]
yes clangd-indexer tools is intentionally left out of distribution packages as most of the users shouldn't need it. especially after clangd-9 which made background-index the default.

why do you need clangd-indexer exactly? to help us understand if there's a use case we've missed.

**Comment by snizovtsev** [comment]
> why do you need clangd-indexer exactly? to help us understand if there's a use case we've missed.

I like using `clangd-indexer` to check flags conveniently from a shell before opening any files in the editor. It shows all diagnostics beforehand, which helps me not to loose my focus fixing irritating diagnostics spam.

**Comment by kadircet** [comment]
Ah nice! @sam-mccall actually landed a specific patch for exactly this use case. But it won't be available before clangd-12, unless you build clangd from head or make use of our [weekly snapshots](https://github.com/clangd/clangd/releases).

You can find details about the feature in https://reviews.llvm.org/D88338.

But basically invoking `clangd -check=path/to/some/file/in/your/project.cc -log=verbose` should provide you with the information you are looking for.

**Comment by ToBoMi** [comment]
This can be closed right?
Indexing tools are delivered in the releases since the release of [19th October 2020](https://github.com/clangd/clangd/releases/tag/snapshot_20201018).

**Comment by HighCommander4** [comment]
I think so. Please feel free to reopen if I've misunderstood.

**Comment by drcxd** [comment]
Hello, I have found that release 18.1.2 for Windows does not include a clangd-indexer.

 I have also built clangd from source on Linux. This does not built the indexer as well.

```
└─$ clangd --version
clangd version 19.0.0git (https://github.com/llvm/llvm-project.git 2582965c160486f9e3b0680f1cebc5ffdef9620c)
Features: linux
```

**Comment by HighCommander4** [comment]
> Hello, I have found that release 18.1.2 for Windows does not include a clangd-indexer.

Where are you getting this release from? The [one in this repo](https://github.com/clangd/clangd/releases/tag/18.1.2) does not contain any binary assets yet (the release is under discussion at https://github.com/clangd/clangd/issues/1948).

> I have also built clangd from source on Linux. This does not built the indexer as well.

Note that `clangd-indexer` is a separate target from `clangd`, so you need to run e.g. `ninja clangd-indexer`.

**Comment by drcxd** [comment]
> Where are you getting this release from?

I usually install clangd by installing the whole llvm project, I get my release from here: https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.2

```
PS C:\Users\Administrator> clangd --version
clangd version 18.1.2
Features: windows
Platform: x86_64-pc-windows-msvc
```

So, is this the real clangd 18.1.2?

**Comment by HighCommander4** [comment]
> > Where are you getting this release from?
> 
> I usually install clangd by installing the whole llvm project, I get my release from here: https://github.com/llvm/llvm-project/releases/tag/llvmorg-18.1.2
> 
> ```
> PS C:\Users\Administrator> clangd --version
> clangd version 18.1.2
> Features: windows
> Platform: x86_64-pc-windows-msvc
> ```
> 
> So, is this the real clangd 18.1.2?

Yes, however the llvm-project packages have never included `clangd-indexer` (i.e. it's not there for 17 or earlier versions either).

So to summarize, your options for getting clangd-indexer are:

 1. Use version 17 from https://github.com/clangd/clangd/releases/tag/17.0.3 (clangd_indexing_tools-windows package).
 2. Wait for #1948 to be resolved and then use version 18 from https://github.com/clangd/clangd/releases/tag/18.1.2
 3. Build version 18 (or trunk) from source

**Comment by drcxd** [comment]
Thanks, but I remeber that clangd 17.x has the bug that it can not correctly locate the compile command for a header file, if a source file includes it has never been opened. Guess I have to build the indexer myself.
