### ISSUE TITLE
Any option to disable auto headers import? (clangd-9)

### ISSUE THREAD

**Issue by mihaelartz** [clangd/clangd#55]

**Comment by sam-mccall** [comment]
There's a flag: `-header-insertion=never`. You should be able to set you editor to pass that flag to clangd.

Only relatively recently (since r358075).

Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.

**Comment by mihaelartz** [comment]
@sam-mccall Example:
```cpp
#include <iostream> // iostream include, <ostream> header!

int main() {
    std::cout << std::endl; // when accept completion for endl, auto import ostream header
}

// No need to add a new header, sorry for my bad English! Thanks.

```
![Webp net-gifmaker](https://user-images.githubusercontent.com/29631158/59146668-489ec880-89f1-11e9-8fdc-b943c76d237b.gif)

**Comment by mihaelartz** [comment]
@sam-mccall Another problem, in C
![2019-06-08-133844_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/59146837-666d2d00-89f3-11e9-820b-d61c98f47edb.png)

**Comment by sam-mccall** [comment]
`iostream`: you're right - the default `-header-insertion=iwyu` will always include the canonical header, even if it's already transitively included (because transitive includes are usually unspecified).
`endl` is a bit of an edge-case because it's provided by `<ostream>` but `<iostream>` specified to include it since c++03 (IIRC). I think it's not clear that handling these cases in some special way would be worth the complexity, we should probably see if it comes up again.

Thanks for mentioning C, we do want to fix that soon. We'll track that further in #32.

**Comment by fox-tek** [comment]
Hey,
What about the problem of C++ headers being suggested in C projects ?
I haven't seen any kind of solution about it after one or two hours of searching.
CLangd just can't find `.h` files when editing `.c` files ?
My compile_commands.json has `-x c` for every file yet I still get C++ headers, which is very annoying.
Thanks.

**Comment by amit-nayar** [comment]
There is also the issue where a header gets included when you are only forward declaring a class/struct inside a header file (when `--header-insertion=iwyu`).

This completely defeats the purpose of using forward declarations when wanting to cut down on the use of indirect headers.

**Comment by ZSaberLv0** [comment]
> Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.

I'd prefer to disable this feature too, and here's my reason:
some libs supply an all-in-one header, but the auto header import results to some internal or sub module's header

I'd prefer to have some quickfix way to allow user to perform auto import manually

**Comment by kadircet** [comment]
> some libs supply an all-in-one header, but the auto header import results to some internal or sub module's header

normally we respect IWYU pragmas in such libraries telling us to not make use of some private headers etc. but unfortunately not all libraries are written with those annotations. maybe we can improve the situation by enabling users to provide such annotations through config, e.g:
```
HeaderInsertion:
  Match: hard/to/know/path/component/private/.*
  Use: hard/to/know/path/component.h
```

**Comment by vbrunini** [comment]
What about letting users provide an IWYU mapping file (https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md) in the config?

**Comment by jkordani** [comment]
@kadircet what are these IWYU pragmas?

**Comment by kirillbobyrev** [comment]
> @kadircet what are these IWYU pragmas?

https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md

**Comment by rhd** [comment]
> There's a flag: `-header-insertion=never`. You should be able to set you editor to pass that flag to clangd.
> 
> Only relatively recently (since r358075).
> 
> Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.

My use-case that `clangd` gets wrong is when you use [spack environments](https://spack.readthedocs.io/en/latest/environments.html) to manage the dependencies. It will insert something like `#include ".spack-env/view/<hash>/spdlog/spdlog.h"` instead of `#include <spdlog/spdlog.h>`

It would be great if you could tell `clangd` to ignore certain directories.

`clangd` is great - thanks for maintaining it.

**Comment by HighCommander4** [comment]
> My use-case that `clangd` gets wrong is when you use [spack environments](https://spack.readthedocs.io/en/latest/environments.html) to manage the dependencies. It will insert something like `#include ".spack-env/view/<hash>/spdlog/spdlog.h"` instead of `#include <spdlog/spdlog.h>`
> 
> It would be great if you could tell `clangd` to ignore certain directories.

Would the proposal in #1367 address your use case?

If so, you may want to comment there in support of it.

Otherwise, you may want to file a new issue about your use case.

**Comment by RafiWho** [comment]
> There's a flag: `-header-insertion=never`. You should be able to set you editor to pass that flag to clangd.
> 
> Only relatively recently (since r358075).
> 
> Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.

and how can i do that?

**Comment by HighCommander4** [comment]
> > There's a flag: `-header-insertion=never`. You should be able to set you editor to pass that flag to clangd.
> > Only relatively recently (since r358075).
> > Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.
> 
> and how can i do that?

If you mean how to pass command-line arguments to clangd, it depends on your editor. In vscode it's `"clangd.arguments"` in vscode's settings.

**Comment by RafiWho** [comment]
> > > There's a flag: `-header-insertion=never`. You should be able to set you editor to pass that flag to clangd.
> > > Only relatively recently (since r358075).
> > > Would be good to know details of why you're disabling it/where it's going wrong - wrong file for symbol, #include spelling of the filename is wrong, correct #include but you'd rather get the symbol transitively, etc.
> > 
> > 
> > and how can i do that?
> 
> If you mean how to pass command-line arguments to clangd, it depends on your editor. In vscode it's `"clangd.arguments"` in vscode's settings.

im using sublime  and i have tried to create compile_flags.txt file where i pass the flag but didnt work. If u could help me  with that.

**Comment by HighCommander4** [comment]
> im using sublime and i have tried to create compile_flags.txt file where i pass the flag but didnt work. If u could help me with that.

-header-insertion=never is not a flag for clangd to use in the compile command, it's a flag to clangd itself

Have a look at https://clangd.llvm.org/installation#under-the-hood-3 for how to specify this for sublime; it goes in the same place as --log=verbose would

**Comment by RafiWho** [comment]
> > im using sublime and i have tried to create compile_flags.txt file where i pass the flag but didnt work. If u could help me with that.
> 
> -header-insertion=never is not a flag for clangd to use in the compile command, it's a flag to clangd itself
> 
> Have a look at https://clangd.llvm.org/installation#editor-plugins for how to specify this (expand the Sublime Text section); it goes in the same place as --log=verbose would

![image](https://github.com/clangd/clangd/assets/109935777/3379f40c-bc96-4d29-bf01-8aa8128bc253)
done this but didnt work

**Comment by HighCommander4** [comment]
This is really a question about Sublime Text, but it looks to me like `"command"` expects the executable name as well as any arguments, so you want `"command": ["clangd", "-header-insertion=never"]`

**Comment by RafiWho** [comment]
> This is really a question about Sublime Text, but it looks to me like `"command"` expects the executable name as well as any arguments, so you want `"command": ["clangd", "-header-insertion=never"]`

bro it stoped all of my completion :)

**Comment by jdhdhsbjd6454543** [comment]
How should I use LunarVim?

**Comment by jdhdhsbjd6454543** [comment]
> > > im using sublime and i have tried to create compile_flags.txt file where i pass the flag but didnt work. If u could help me with that.我使用Sublime，我试图创建compile_flags.txt文件，我在其中传递标志但没有工作。如果你能帮我的话。
> > 
> > 
> > -header-insertion=never is not a flag for clangd to use in the compile command, it's a flag to clangd itself-header-insertion=never 不是 clangd 在编译命令中使用的标志，它是一个 clang 本身的标志
> > Have a look at https://clangd.llvm.org/installation#editor-plugins for how to specify this (expand the Sublime Text section); it goes in the same place as --log=verbose would查看 https://clangd.llvm.org/installation#editor-plugins 了解如何指定此项（展开“崇高文本”部分）;它与 --log=verbose 在同一个地方
> 
> ![image](https://user-images.githubusercontent.com/109935777/264654768-3379f40c-bc96-4d29-bf01-8aa8128bc253.png) did this but happened nothing做了这个但什么也没发生

How should I pass this parameter to LunarVim?"。

**Comment by Kerosin3** [comment]
Would like to add that I cannot deal with auto insertion in nvim+coc.
I suppose that coc-clangd is not working as expected, neither of params is being supplied to clang server, and header insertion also.
I fugured this out because **-std=c++20** is passes only via clangd/config.yaml, and not coc-settings, coc-clangd.
Does anyone knows how to pass arguments to clangd using nvim coc? (headers insertion, standart etc)
my coc-settings are

	"languageserver": {
		"coc-clangd": {
			"enable": true,
			"command": "clangd",
			"trace.server": "verbose",
			"arguments": [
				"--header-insertion=never",
				"--log=verbose",
				"-j=4",
				"-std=c++20",
				"--fallback-style=LLVM",
			],
			"rootPatterns": [
				"compile_flags.txt",
				"compile_commands.json"
			],
			"filetypes": [
				"cc",
				"cpp",
				"c++",
				"objc",
				"objcpp"
			],
			"fallbackFlags": [
				"-std=c++20",
			],
		},
	},

**Comment by HighCommander4** [comment]
This issue is not a good place to get help with how to pass arguments to the language server in various flavours of vim. (I have no idea, I don't use vim. Some other clangd users use vim but I don't know how likely they are to see your questons.)

Please ask in the respective vim or vim plugin issue trackers (e.g. https://github.com/neoclide/coc.nvim)

**Comment by Naakinn** [comment]
>  Does anyone knows how to pass arguments to clangd using nvim coc? (headers insertion, standart etc)

According to [coc-clangd documentation](https://github.com/clangd/coc-clangd?tab=readme-ov-file#configurations), use this in your `coc-settings.json` file  (`:CocConfig` to open).
```
{
  "clangd.arguments": [
    "-header-insertion=never" 
  ]
}
```

**Comment by qiyuewuyi2333** [comment]
For the latercome, if you using **VS Code** with **Clangd extension**, you just need to add `--header-insertion=never` to the clangd: Arguments. 
If that doesn't work, please try the following methods:
- ensure you change this setting in workspace setting and others, too.
- reload the window or clangd server
