### ISSUE TITLE
Support partially qualified names in workspace/symbol

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#550]
I originally filed this as https://github.com/clangd/vscode-clangd/issues/31 (it was transferred into the vscode-clangd repo after filing). That ticket has been closed, but the issue is only partially fixed.

Specifically, in that ticket, a vscode-specific issue that led to `workspace/symbol` queries with a **fully qualified name** as a search string not returning results, was fixed.

There is a remaining issue on the server side, that `workspace/symbol` queries with **partially qualified names** do not return results. For example, searching for `Class::Method` should match `ns::Class::Method` or `ns1::ns2::Class::Method` if such entities exist.

**Comment by kadircet** [comment]
That definitely makes sense to me, send out https://reviews.llvm.org/D88814. This might degrade the search performance for top-level but not fully-qualified searches. e.g. `clang::` vs `::clang`. But I think providing results for sub-scopes like `clangd::` is definitely worth it.

I wonder what will others think tho. Hence did not assign anyone for review yet :D

**Comment by kadircet** [comment]
To summarize an offline discussion and give a bit more details:

- An unqualified lookup (e.g. `Foo`) or a fully-qualified lookup (e.g. `::Foo`) isn't going to be affected by this change.
- Qualified lookups of the form `foo::bar::Baz` are going to be a lookup in all scopes, with symbols from `::foo::bar` being boosted and any results that doesn't have `foo::bar::` as a "sub-scope" will be filtered.
