### ISSUE TITLE
Rename only some occurrences of templates

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#554]
(Clearly related to #280 but this is a bug rather than a FR).

```
template <typename> bool ^X = true;
bool Z = X<int>;
template <typename T> bool f() { return X<T>; }
```

Rename X (at ^) to Y.
Expect all 3 lines to be changed, or failing that an error message.
Instead we get the following broken code, only line 3 is changed (not where the cursor was!):

```
template <typename> bool ^X = true;
bool Z = X<int>;
template <typename T> bool f() { return Y<T>; }
```

Apart from the specific bug here, maybe we should have a sanity check that rename actually changed something at the cursor?

**System information**
Output of `clangd --version`: 25692b7765e2364896a0136f5b54dde3de2dd563

**Comment by sam-mccall** [comment]
(sorry for the bad description, obviously these are not **class** templates...)

**Comment by hokein** [comment]
it is fixed at head.
