### ISSUE TITLE
CompileFlags: {Add: -xc++} doesn't work

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#555]
Forcing headers to be treated as C++ is a common use case.

However the obvious idiom doesn't work because -x only works when it occurs *before* the file. (Motivation: handling of multiple files).

Ideas:
 - find/define another clang flag for this
 - insert arguments first (but can't override subsequent ones)
 - special case -x (insert after previous occurrence or at start)
 - change -x to work retroactively if there are multiple filenames

**Comment by cloudhan** [comment]
`*.cuh` file also affected.

the generated command under hood is `/usr/bin/clang <myfile> -xcuda-header -std=c++11 --cuda-path=/usr/local/cuda-10.2 --cuda-gpu-arch=sm_61 -L/usr/local/cuda-10.2/lib64 -I/usr/local/cuda-10.2/include -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1`

with the following error:
```
I[00:07:42.801] --> reply:textDocument/documentLink(5) 41 ms, error: invalid AST
[Error - 12:07:42 AM] Request textDocument/documentLink failed.
  Message: invalid AST
  Code: -32001
```

**Comment by sam-mccall** [comment]
A slightly more elegant option:
- always insert before `--` (this is the right thing to do anyway, see https://reviews.llvm.org/D99523)
- normalize commands: `clang -flag1 foo.cc -flag2` => `clang -flags1 -flag2 -- foo.cc` before applying CompileFlags

The latter may be complicated but at least this is conceptually pretty simple and "just" a matter of implementation.
