### ISSUE TITLE
-stdlib=libc++ appears to be ignored

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#558]
From logs

V[10:40:54.061] Ignored diagnostic. argument unused during compilation: '-stdlib=libc++'

But this should surely affect the frontend.

**Comment by kadircet** [comment]
I can't reproduce this. Are we sure the TU in question is a c++ file? I think this error would only show up for non-c++ TUs, e.g. if one passes `-xc` or so.

**Comment by sam-mccall** [comment]
Yes, you're right - this was in combination with #555.
