### ISSUE TITLE
[Feature Request] Support Hover on constexpr expression.

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#56]
**1. Hover on constexpr function.**
![1](https://user-images.githubusercontent.com/10697249/59329329-37bbc300-8d21-11e9-8e28-463d07f8ff9d.png)
**2. Hover on sizeof expression.**
![2](https://user-images.githubusercontent.com/10697249/59329331-38545980-8d21-11e9-8741-dcff56311fab.png)
**3. Hover on template.**
![3](https://user-images.githubusercontent.com/10697249/59329335-39858680-8d21-11e9-942d-4b6e90f30196.png)
**4. Hover on literal**
![4](https://user-images.githubusercontent.com/10697249/59342958-647dd380-8d3d-11e9-81f4-b5be43b512a6.png)

**Comment by sam-mccall** [comment]
Great examples. Are the hovers shown from the Microsoft C++ plugin?

I believe all of these are cases of expressions that can be evaluated using `Expr::EvaluateAsRValue`. @kadircet, this seems like something we could add to the new structured hover?

**Comment by lh123** [comment]
> Great examples. Are the hovers shown from the Microsoft C++ plugin?
Yes

**Comment by kadircet** [comment]
This is mostly done after https://github.com/llvm/llvm-project/commit/287a874d1c460302677a1530a75d94bae4d4a348 except:
- hovering over expressions like `StringLiteral`s and `sizeof/alignof`
- better printing for stringliterals
