### ISSUE TITLE
Better support for completion when in the middle of a word

### ISSUE THREAD

**Issue by ammen99** [clangd/clangd#567]
Consider the following file:
```cpp
int main()
{
    int refactoring_twice;
    refact<cursor>wice;
}
```

and the cursor is at the indicated place. Now I trigger autocomplete, I get the suggestion for `refactoring_twice` but after insertion the text becomes:

```cpp
int main()
{
    int refactoring_twice;
    refactoring_twicewice;
}
```

The autocompletion is inserted just as clangd says (I verified with debug logs and clangd says to replace the `refact` part only).
Before I have used `ycmd` for completion and it would replace the whole `refactwice` word.

I am using clangd 10.0.0, sorry if this is available in git.

**Comment by HighCommander4** [comment]
I think this is covered by #387.

**Comment by ammen99** [comment]
> I think this is covered by #387.

Indeed, closing this one.
