### ISSUE TITLE
Add additional flags to flags extracted from compilation database

### ISSUE THREAD

**Issue by Kamilcuk** [clangd/clangd#569]
First of all, amazing project and great work!

Parsing `compile_commands.json` is sometimes not enough. The cross-compiling toolchain comes with many predeterminated options it was _internally_ configured with, like `--sysroot=` and has a different set of predefined preprocessing macros depending on slight compile flags that are passed to the compiler. I could potentially generate:

    $ something-something-gcc -mcpu=cortex-m0 -mthumb -mabi=aapcs -mfloat-abi=soft -dM -E -x c /dev/null | sed -nE '/#define +([^ ]+) +(.+)$/{ s//-D\1=\2/; s/"/\\"/g; s/.*/"&"/; p; }' | sed 's/$/,/' |
    "-D__DBL_MIN_EXP__=(-1021)","-D__HQ_FBIT__=15",".... etc. etc. ",-Dsomething=something"
    $ something-something-gcc -mcpu=cortex-m0 -mthumb -mabi=aapcs -mfloat-abi=soft -Os -dM -E -x c /dev/null -v |& sed -zE 's/.*-isysroot ([^ ]*).*/"--sysroot=\1"/'
    "--sysroot=/some/path/to/sysroot/something-eabi"

and then add all these flags to `fallbackFlags`. But, sadly, `fallbackFlags` is __not__ used when `compile_commands.json` is found, so then, sadly, I would have to remove `compile_commands.json` and work without database.

Could it be possible to append custom flags __with__ the flags extracted from `compile_commands.json`? Like `"initializationOptions": { "extraDatabaseFlags": ["-Dfoo=1", "--sysroot=somelocation"] }`? What is the preferred way I should take? I believe current workaround I'll do will be `cat compile_commands.json | jq '.[].command += " -Dfoo=1 --sysroot=/some/path"' > compile_commands.json`. The ideal solution would be to extract these flags by clangd itself from the compiler present in `compile_commands.json` - I do not wish to aim that high, just a simple "append flags" will be just enough for me.

I read https://github.com/thomasjo/atom-ide-cpp/issues/16 https://reviews.llvm.org/D53641 https://reviews.llvm.org/D34947 https://reviews.llvm.org/D53641 , but I do not understand, I think it's about a `extraFlags` option that has different purpose. I tried going through source code, I believe [in here protocol.c](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/Protocol.cpp#L1133) should be added `O.mapOptional("extraDatabaseFlags", Opts.extraDatabaseFlags)`, then [here ClangdLSPServer](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/ClangdLSPServer.cpp#L505) would need `Params.initializationOptions.extraDatabaseFlags` be added, and [in GlobalCompilationDatabase.cpp](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp) additional constructor parameter and class member and then finally [in here](https://github.com/llvm/llvm-project/blob/master/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp#L54) they would have to be added to `Argv` maybe, right?

**Comment by HighCommander4** [comment]
Does the [Config mechanism](https://clangd.llvm.org/config.html) in clangd 11 (see `CompileFlags:` example) meet your needs?

**Comment by Kamilcuk** [comment]
Yes! I installed clangd11 and tested it - yes, the `CompileFlags: Add:` array is added after flags extracted from `compile_commands.json`. Didn't knew about this option. Thank you!
