### ISSUE TITLE
'.' as trigger character for pointers

### ISSUE THREAD

**Issue by leungbk** [clangd/clangd#574]
``` c
struct Circle {
  int radius;
};

int main() {
  struct Circle c;
  struct Circle *c_ptr = &c;

  c_ptr[X]
}
```

With the `ccls` language server, typing `.` where indicated in the above code will trigger a completion request, and selecting that completion will complete as `c_ptr->radius`.

It would be nice if `clangd` also supported something like this.

**Comment by HighCommander4** [comment]
This does work for me, exactly as described.
