### ISSUE TITLE
Can clangd recognize cuda version 11.1?

### ISSUE THREAD

**Issue by joonwoolee42** [clangd/clangd#576]
I'm trying to write c++ code with cuda version 11.1, but clangd seems not to recognize cuda. I wrote '--cuda-gpu-arch=sm_61' to compile_flags.txt because my gpu is Geforce GTX 1080 Ti, but it shows the following error message. How can I make clangd recognize the c++ code with cuda version 11.1? The version of clangd is 10.0.

![image](https://user-images.githubusercontent.com/66359100/97851919-616ff280-1d39-11eb-9751-8fda9b598fcf.png)

**Comment by kadircet** [comment]
You might need to pass extra flags pointing at your libcuda installation and headers. You can find more details in https://llvm.org/docs/CompileCudaWithLLVM.html.

Try to get a command line that will make this compile work for bare clang first, then try to pass that to clangd via compile_flags.txt and if it doesn't work please reply with clangd logs and the command line invocation for clang.

**Comment by joonwoolee42** [comment]
![image](https://user-images.githubusercontent.com/66359100/97956154-48277e80-1deb-11eb-8988-17af913b979a.png)


Thanks for giving me a clear reference, but the bare clang also cannot compile it. The above picture shows the error message. The first command follows the example command in your reference page, and the second command adds --cuda-path=/usr/local/cuda-11.1. Both commands caused the same error messages.

**Comment by kadircet** [comment]
I am sorry I can't help more here really, as I mentioned above this is rather a situation you need to resolve on clang side. I am happy to help you out once you manage to compile your file using clang and face issues within clangd.

**Comment by joonwoolee42** [comment]
I understand your point. Thanks for your help!
