### ISSUE TITLE
Clarify documentation of compile_flags.txt on the Getting Started page

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#578]
Based on answering user questions in the clangd channel, there are two things about `compile_flags.txt` that users commonly do not realize and that trips them up:

 1. That it takes precedence over `compile_commands.json`, leading to `compile_commands.json` being ignored if they have both.
 2. That no background indexing occurs with `compile_flags.txt`. (Which, combined with (1), can mean no background indexing even with `compile_commands.json` if they have a `compile_flags.txt` lying around say from an earlier attempt.)

I think the [Getting Started page](https://clangd.llvm.org/installation.html) could add some warnings to make these things clearer.

**Comment by njames93** [comment]
compile_flags doesn't take precedence by design. Its undefined which takes precedence. Maybe that should be addressed.

**Comment by sam-mccall** [comment]
These days it is defined: compile_commands takes precedence, because we bypass the plugin infrastructure (to allow efficient change detection).
