### ISSUE TITLE
Add more, better build instructions.

### ISSUE THREAD

**Issue by anakimluke** [clangd/clangd#579]
I looked in a bunch of places, and still I found it pretty difficult to find good build instructions; I ended up by not building it and using a pre-compiled binary because it seemed daunting to me to compile clang(or llvm? sorry, I'm new) from source, as they seem to be big projects and I'm not on a great machine.

I hope you can find relevant places to put these instructions on, like this repo, the llvm repo readme, the clangd directory readme file on the llvm repo, on the site..

Thank you! :)

**Comment by kadircet** [comment]
Sent out https://reviews.llvm.org/D91186

**Comment by HighCommander4** [comment]
There are now build instructions at https://github.com/llvm/llvm-project/tree/main/clang-tools-extra/clangd#building-and-testing-clangd (though I wonder if it would be more convenient to have them directly at https://github.com/clangd/clangd/blob/master/README.md).

**Comment by kadircet** [comment]
The main reason we put it into the LLVM repo is, it is the context where it makes sense. I am sending a patch to mention compiling from sources in installation section of clangd.llvm.org. I don't think clangd/clangd's readme is suitable as-is for such information. But we can rearrange the layout to accommodate such information, I just don't think the audience looking at the clangd/clangd/README.md will be really interested in compiling clangd from sources.
