### ISSUE TITLE
Detect presence of clangd

### ISSUE THREAD

**Issue by jan-wassenberg** [clangd/clangd#581]
Sometimes we need to detect whether a code model/IDE are parsing or we're actually compiling. Examples:
- avoid graying out conditional code sections (`#if defined(MEMORY_SANITIZER)`)
- hide multiple inclusion of source files from code models because generating a preamble would fail (https://reviews.llvm.org/D53866)

Other parsers provide predefined macros for this: `__CDT_PARSER__, __INTELLISENSE__, Q_CREATOR_RUN`.

Is there already a way to reliably differentiate clangd from clang? If not, can we add such a macro?

**Comment by HighCommander4** [comment]
I believe you can accomplish this, with a macro name of your choice, via the [Config](https://clangd.llvm.org/config.html) mechanism (present in clangd 11 and later).

You can add the following to the project's `.clangd` file:

```
CompileFlags:                     
  Add: [-D__CLANGD__]
```

and this will cause clangd to add `-D__CLANGD__` to the compile flags it uses to process files (which has the effect of causing the macro `__CLANGD__` to be defined). You can of course choose a different macro name, including a project-specific one if you'd like.

**Comment by jan-wassenberg** [comment]
Sounds good, thank you, we'll do it that way :)

**Comment by kadircet** [comment]
I am not sure how generic the problem is (it sounds pretty specific to a project), but if future travelers end up here for different projects I think we might consider setting a predefined macro like `__BUILDING_PREAMBLE__` in clang instead of clangd to solve this problem for all clang-based tools.

**Comment by jan-wassenberg** [comment]
A clang predefined macro for preamble could be useful for include-related issues.

FYI I think it's more widely useful for code model parsers to identify themselves, Eclipse/MSVC/Qt Creator do so. This is a nice escape hatch for complicated code including but not limited to recursive includes.
Other examples:
- workaround for missing features (`__attribute__`): https://github.com/Inori/GPCS4/blob/511561384ad63a868c2fc550737fa44dcf698e52/GPCS4/Common/IntellisenseClang.h
- helping them cope with CUDA or other dialects: https://github.com/sunyinqi0508/cuLines/blob/20d11193b86c737999a96b8415c037681d70e956/cuLines/cuProxy.cuh

**Comment by HighCommander4** [comment]
> we might consider setting a predefined macro like `__BUILDING_PREAMBLE__` in clang instead of clangd to solve this problem for all clang-based tools.

Why would we make the macro specific to preambles?

**Comment by kadircet** [comment]
> Why would we make the macro specific to preambles?

I've suggested that because the initial problem seemed to be centered around self-inclusion of a file in the preamble with different preprocessor states. But looks like there are other usages as well, especially outside of the preamble section.

I would lean towards suggesting people to add it through a `.clangd` file rather than hardcoding it, as it doesn't seem to be affecting a huge portion of the user base.
