### ISSUE TITLE
Unexpected add using declaration behavior on type aliases.

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#584]
```cpp
struct Y {};
namespace a {
using X = Y;
}  // namespace a

void foo() { a::X^ x; }
```

Trigger code actions at `^`. First of all the message says, `Add using declaration for Y`, rather than `a::X`. After executing the action it inserts `using a::Y` at the top of the file, which is wrong as the symbol's unqual name is `X` (insertion point is also wrong, this needs to be inserted after type declaration, but a separate bug) but replaces `a::X` with `X`, which works as expected.

**Comment by gislan** [comment]
Fixed in  https://reviews.llvm.org/D91966
