### ISSUE TITLE
issue with clangd and spacemacs on Catalina 10.15.7

### ISSUE THREAD

**Issue by xyderos** [clangd/clangd#595]
Hi,

I have been trying to debug an executable on 10.15.7 written in C11. I loaded the executable and tried to run but I got an error message from the debug server a couple of seconds later saying that:
`error: Attach failed: "Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries when the attached failed.  The subsystem that denied the attach permission will likely have logged an informative message`

I checked the console app and I got a couple of entries of that:

`error: MachTask::TaskPortForProcessID task_for_pid failed: ::task_for_pid ( target_tport = 0x0103, pid = 10984, &task ) => err = 0x00000005 ((os/kern) failure)`

Then that:

`error: MachTask::StartExceptionThread (): task invalid, exception thread start failed.`

That:

`error: MachProcess::AttachForDebug failed to start exception thread: unable to start the exception thread`

and finally I got the first error message again.

I am assuming that there is a security thread by the debugserver process?

If I run it standalone on the lldb it is working fine.

Thanks for your help!

**Comment by HighCommander4** [comment]
I don't understand how this is related to clangd. Clangd deals with powering editor language features (like go-to-definition, semantic highlighting, find-references etc.) only, not debugging.

**Comment by puremourning** [comment]
the debugserver needs to be codesigned, or if you're using gdb, gdb needs to be code signed.

usually, tell your debugger front end to use the system debugserver.

but certainly nothing to do with clangd.

**Comment by xyderos** [comment]
Alright, thanks for your help though and sorry for the irrelevant issue. Ill close this thread.
