### ISSUE TITLE
Clang-tidy integration

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#6]
Inital idea:

**Goal**
Make clang-tidy checks available as hints while coding.

**Implementation idea**
Link in clang-tidy library and run checks as part of diagnostics (r347298)

**UI**
Surface main-file results as regular diagnostics

**Performance**
Make it fast by restricting AST traversal to the main file (r346847)
 Limit scope to AST-matcher based checks, not static analyzers etc

**Comment by sam-mccall** [comment]
Many of the pieces for this have landed.

Still to do:
 - put this feature behind a flag until ready to launch
 - verify that "as diagnostics" is a suitable UI. Can we reduce noise from existing diagnostics?
 - consider enabling warnings flags from .clang-tidy files

**Comment by sam-mccall** [comment]
Idea about noise level: this would be greatly reduced if we could show warnings only on changed code.

We lack VCS integration for this, but it's not impossible:
  - as a baseline, we can just track edits to the file via LSP
  - editors with VCS integration can send changed-line list as an LSP extension on `textDocument/didChange`
We may want to put other non-build-system warnings behind this behavior too, e.g. injected -Wdeprecated

**Comment by sam-mccall** [comment]
@hokein are we happy with the current behavior here? Feel free to close if so.

**Comment by hokein** [comment]
Yes, from the internal experience, we're happy with the current behavior (showing clang-tidy warnings for the whole files), one missing point is to enable it by default in upstream, have sent https://reviews.llvm.org/D60560.

**Comment by hokein** [comment]
It is on by default now. Close it.
