### ISSUE TITLE
textDocument/codeAction returns too many fixits if two clang-tidy checks produce the same diagnostic

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#60]
**Steps to reproduce**

These were tested with Theia as the client (see [corresponding Theia issue](https://github.com/theia-ide/theia/issues/5425)), but should be applicable to any client.

 1. Configure clangd to run with `--clang-tidy --clang-tidy-checks=modernize-use-nullptr,hicpp-use-nullptr`. These two checks both flag code that uses `0` for a null pointer constant and suggest changing it to `nullptr`.
 2. In the editor, write some code that triggers the check, such as:

```
void foo() {
    char* p = 0;
}
```

  3. This triggers the same diagnostic twice. (Which is fine, or at least is not in scope for this bug.)
  4. Activate `textDocument/codeAction` for the location of the issued diagnostic.
  5. Observe that there are **four** fixits suggesting to change the `0` to a `nullptr`.

Two fixits would be reasonable given the circumstances, as there are two diagnostics. Four is clearly too many :)

**Comment by HighCommander4** [comment]
**Diagnosis**

The reason we produce four fixits boils down to the fact that `ClangdLSPServer::FixItsMap` stores fixits [keyed on `clangd::Diagnostic`](https://github.com/llvm/llvm-project/blob/5e83d8fff43cb23c61f4b85e899c935226faef5a/clang-tools-extra/clangd/ClangdLSPServer.h#L127), with a [comparator](https://github.com/llvm/llvm-project/blob/5e83d8fff43cb23c61f4b85e899c935226faef5a/clang-tools-extra/clangd/Protocol.h#L647) that considers only the diagnostic's message and range.

In this case, the diagnostics produced by the two checks have the same message and range, though they have different diagnostic codes.

So, at the time `FixItsMap` is computed, both checks add their fixit to the list associated with the same `clangd::Diagnostic`.

Later, when `textDocument/codeAction` is handled, we look up the two diagnostics in the map, and for each one return both fixits from the associated list, giving a total of four.

**Potential solution**

Modify `LSPDiagnosticCompare` to include the diagnostic's code in the comparison s well.

**Comment by HighCommander4** [comment]
Patch implementing proposed solution: https://reviews.llvm.org/D63316

**Comment by kadircet** [comment]
This has landed with https://reviews.llvm.org/rL363889
