### ISSUE TITLE
Support for nested functions /w gcc

### ISSUE THREAD

**Issue by aganm** [clangd/clangd#607]
I'm using gcc to compile and clangd together.
clang does not support nested functions, but since gcc does, would it be possible for clangd to add support for them when gcc is used for compilation?

**Comment by HighCommander4** [comment]
Clangd uses clang for parsing, so it would have to be supported in clang as an optional extension, or something like that.

**Comment by aganm** [comment]
Thanks! I shall ask the clang people then.

**Comment by aganm** [comment]
Leaving open for reference.

**Comment by HighCommander4** [comment]
If you file an issue in the [LLVM bug tracker](https://bugs.llvm.org/), feel free to link to it from here.

**Comment by aganm** [comment]
I stopped using nested functions altogether to be able to compile with clang. If clang ever decides to add support for them, I might consider reusing them. Anyways, not an issue anymore.
