### ISSUE TITLE
trying to get AST for non-added document

### ISSUE THREAD

**Issue by haferburg** [clangd/clangd#609]
:: --> clangd textDocument/documentHighlight(35)
    clangd: V[14:15:17.480] <<< {"id":35,"jsonrpc":"2.0","method":"textDocument/documentHighlight","params":{"position":{"character":42,"line":4481},"textDocument":{"uri":"file:///D:/proj/src/main.cpp"}}}
    clangd: 
    clangd: I[14:15:17.480] <-- textDocument/documentHighlight(35)
    clangd: I[14:15:17.480] --> reply:textDocument/documentHighlight(35) 0 ms, error: -32602: trying to get AST for non-added document
    clangd: V[14:15:17.480] >>> {"error":{"code":-32602,"message":"trying to get AST for non-added document"},"id":35,"jsonrpc":"2.0"}
    clangd: 
    :: <<< clangd 35

I'm not sure what I did to get into this state. I'm using Sublime Text with the LSP plugin. It was working properly at first. As far as I remember, I dragged a tab with this file from one "focus group" to another, then it stopped working.

I found this: https://github.com/emacs-lsp/lsp-mode/issues/582. I don't have non-ascii characters in the file.

**Comment by sam-mccall** [comment]
The editor tells clangd which files are open/closed, and clangd only supports operating on files that are open. That error message is what you get if the file has not been opened, or has been opened and then closed[1].

I think it's extremely likely this is an editor/client bug, a full clangd log including the `textDocument/didOpen` and `textDocument/didClose` messages (with `clangd --log=verbose`) would be the way to tell for sure.

>  As far as I remember, I dragged a tab with this file from one "focus group" to another, then it stopped working

My *guess* is that the way the sublime LSP plugin translates internal events into LSP notifications is not handling this case really well. Ideally, it would not send any open/close events. Closing and reopening the document, in that order, would also work. But if a new open event is sent *before* the close event, then clangd will see the sequence "open(ok) ... open(error: already open) close(ok) documentHighlight(error: not open)".

@rwols in case any of this rings a bell, I don't know anything about sublime's event model.

---

[1] (The one exception is if we get a corrupt incremental update to an open file, then we don't know what its content is and the protocol gives us no way to recover. We put the file into a "closed" state in that case, as there's nothing else to do but crash, really).

**Comment by rwols** [comment]
Sorry for the late reply. But I cannot reproduce this for the ST4 alpha. So, when that goes public it'll be auto-fixed.

This is definitely a client bug, not something clangd can do anything about.

**Comment by haferburg** [comment]
Alright, thanks @rwols I'll close it then.
