### ISSUE TITLE
Mark inner public structs and static methods as IndexedForCodeCompletion

### ISSUE THREAD

**Issue by kadircet** [clangd/clangd#61]
```cpp
struct Test {
  struct Inner {};
  static void foo();
};

Inn^
fo^
```

We do not provide the completion for `Inner`, which I believe we should with a required qualifier `Test::`.

This also applies to static methods.

**Comment by sam-mccall** [comment]
FWIW this was a deliberate decision to keep the index size manageable.
We provide completion within the scope of the outer class, and when
qualified by the outer class name (using Sema completion).

Apart from in pre-namespace codebases where classes are used as pseudo-ns,
are you sure this will add more signal than noise? (And enough to justify
the cost)

**Comment by ilya-biryukov** [comment]
From the user's standpoint a static function in a class is not much different from a function inside a namespace. I would argue that providing completions in provided cases seems useful.

But do agree that we have to be careful with the index size if we plan to do this and also make sure we don't suggest struct and functions inside templates, e.g.
```cpp
template <class T>
struct Test {
  static void foo();
};

fo^
```

**Comment by kadircet** [comment]
Update: today we already store these in the index (I believe we always did, see https://github.com/llvm/llvm-project/blame/cac6d2173103c3a3c963985697fbc4f7943f5a7f/clang-tools-extra/clangd/index/SymbolCollector.cpp#L275, recorddecls as contexts are always stored). they only show up in workspace symbol requests today.

Regarding showing them in code completion though, I think I agree with the sentiment that this is more likely to cause noise than helping the user. As I wouldn't want to see `create` methods from all the factories in a codebase all of a sudden, similarly for inner classes. Moreover we don't seem to have any extra complaints.

I wonder what exact use case I had in mind at the time I was filing the request, maybe there's value in showing the methods/inner types available for symbols defined within the main file, but I don't think it makes sense at a global scope. Hence closing this one.
