### ISSUE TITLE
Changing file name makes clangd include errors disappear.

### ISSUE THREAD

**Issue by browser-bug** [clangd/clangd#610]
I'm getting a `file not found` error during a header inclusion which is kinda odd since inside the same header folder another file has no problems at all including that. I've tried rebuilding multiple times generating a new compile_commands.json but with no luck. It seems to be a clangd issue because compiling the project leads to no error of that kind at all. 
What is odd is that changing that file name makes the errors disappear.

```
├── paho_remote_implementation.hpp <- no errors including remote_handler.hpp
├── virtual_channel.hpp <- file not found including remote_handler.hpp
├── remote_handler.hpp
```

**Comment by sam-mccall** [comment]
Clangd understands how to parse your files (including where to search for headers etc) by using a compilation database.

Typically this is compile_commands.json generated by your build system, but most build systems *don't* know about headers or include them in compile_commands.json, so what follows is a bunch of hacks and heuristics.

Clangd will try to pick the entry in compile_commands.json whose name most closely matches the file you have open (e.g. foo/bar.h -> foo/bar.cc). This tends to works well either if the two files actually correspond, or if most files in the project build with similar flags. It's not foolproof of course. You can see this in the logs, e.g...

> I[15:07:22.138] ASTWorker building file /home/sammccall/src/llvm-project/clang-tools-extra/clangd/**CodeComplete.h** version 1 with command **inferred from /home/sammccall/src/llvm-project/clang-tools-extra/clangd/CodeComplete.cpp**
[/home/sammccall/src/llvm-project/build]
/usr/bin/c++ --driver-mode=g++ ... (lots of flags)

It would be nice to do something more forgiving (e.g. inject other include directories from other files in the project, detect missing include paths and recover), but it's complicated and not something we're likely to get to soon. (There are a lot of constraints, e.g. multi-hundred-megabyte compile_commands.json files that you want to avoid fully parsing upfront)

Best workaround I can suggest involves [clangd config files](https://clangd.llvm.org/config.html) which allow you to inject flags (in your case `-I<somepath>`) into the compile commands for specific files.

**Comment by browser-bug** [comment]
I tried adding something simple like the following into the `.clangd` file inside my root project directory but with no success. I don't know if I'm messing up the sintax or how I can test it for errors (the documentation page isn't really fully detailed).

```
If:                                               # Apply this config conditionally
  PathMatch: include/agora/virtual_channel.hpp    # only to these headers

CompileFlags:                                   # Tweak the parse settings
  Add: [-I/home/bernardo/Development/margot/agora/include]                              # append this to the compile_commands.json file
```

**Comment by sam-mccall** [comment]
What's your clangd version? Config was first added to version 11.

(You can look at the stderr logs to see if there are any errors parsing the config file)

**Comment by browser-bug** [comment]
I have version 11. I don't see any warnings about the config file so sintax should be correct. This is the output from clangd and as you said I can see the incorrect "inferation" that hits `virtual_channel.hpp`. This unfortunately doesn't fix the issue.

```
I[..] ASTWorker building file /.../Development/margot/agora/include/agora/virtual_channel.hpp version 1 with command inferred from /.../Development/margot/agora/build/_deps/margot-src/margot/src/virtual_channel_impl_paho.cc
[/.../Development/margot/agora/build/_deps/margot-build/margot]
/usr/bin/c++ --driver-mode=g++ -I/.../Development/margot/agora/build/_deps/margot-src/margot/include -g -Wall -g -O0 -pthread -c /.../Development/margot/agora/include/agora/virtual_channel.hpp -fsyntax-only -resource-dir=/.../.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
```
What's interesting is that removing the conditional statement from the `.clangd` file somehow works. I don't know if that's because the compile flag gets attached to every file at that point but the output proves it gets injected. I'm wondering if the PathMatch is working at all at this point (in my case of course).

```
I[..] ASTWorker building file /../Development/margot/agora/include/agora/virtual_channel.hpp version 1 with command inferred from /../Development/margot/agora/build/_deps/margot-src/margot/src/virtual_channel_impl_paho.cc
[/../Development/margot/agora/build/_deps/margot-build/margot]
/usr/bin/c++ --driver-mode=g++ -I/../Development/margot/agora/build/_deps/margot-src/margot/include -g -Wall -g -O0 -pthread -c /../Development/margot/agora/include/agora/virtual_channel.hpp -I/../Development/margot/agora/include -fsyntax-only -resource-dir=/../.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
I[..] ASTWorker building file /../Development/margot/agora/include/agora/remote_handler.hpp version 1 with command inferred from /../Development/margot/agora/src/application_handler.cpp
[/../Development/margot/agora/build]
/usr/bin/c++ --driver-mode=g++ -DBOOST_ALL_NO_LIB -Dagora_EXPORTS -I/../Development/margot/agora/include -I/../Development/margot/agora/build/_deps/margot-src/heel/include -g -fPIC -Wall -g -O0 -pthread -c -std=gnu++17 /../Development/margot/agora/include/agora/remote_handler.hpp -I/../Development/margot/agora/include -fsyntax-only -resource-dir=/../.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/lib/clang/11.0.0
```
