### ISSUE TITLE
cant get clangd works with unreal projects

### ISSUE THREAD

**Issue by Shogo175R** [clangd/clangd#611]
hello.
i'm using clangd with unreal project but i still get a lo of error from the intellisense like "'PawnBase.generated.h' file not found" and so on, i generated the compile_commands file with the UnrealBuildTool but now way to get clangd work in the right way.

VScode Version: 1.51.1 (user setup)
OS : windows 10
unreal version : 4.25.3
clangd version :  0.1.8

any help?

**Comment by nyngwang** [comment]
Did you resolve it? I cannot help you without more details. But it seems that the location of `compile_commands` matters.

**Comment by simdax** [comment]
I can help for this one, and I wish I could make it work with clangd :)

Now, Unreal generates every compile_commands in .vscode.
I'm not sure if the name matters, but this config dont works

![image](https://user-images.githubusercontent.com/2458806/201133152-1188168a-08fb-4101-b753-1b51e1363579.png)

any idea ?

**Comment by simdax** [comment]
No way to be more modular ? Like a multi-project/multi-compile-commands repo ?

**Comment by i-ky** [comment]
> No way to be more modular ? Like a multi-project/multi-compile-commands repo ?

I am not sure what kind of modularity you need. clangd searches for `compile_commands.json` in parent directories of an opened file as well as in `build/` subdirectory of parent directories, so a source tree can have multiple `compile_commands.json` "responsible" for different parts of the source tree.

If you have multiple `compile_commands.json` responsible for the same files (different build configurations, platforms or whatever), then you will need to use symlinks or edit [configuration file](https://clangd.llvm.org/config#compilationdatabase) to switch between compilation databases.

**Comment by simdax** [comment]
OK no it's good.

The easy way to go for Unreal Users is to copy the
.vscode/CompileCommands_Default.json
to a standard compile_comands.json at the root of your project, and it should go directly

thanks
