### ISSUE TITLE
Autocompleted word is not being corrected in the buffer

### ISSUE THREAD

**Issue by ZigaSajovic** [clangd/clangd#613]
## Result from CocInfo

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.79-4f517cc785
coc.nvim directory: /home/ziga/.vim/plugged/coc.nvim
term: alacritty
platform: linux

## Clangd version

clangd version 10.0.0-4ubuntu1

## Describe the bug

When using autocomplete, the selected word is not corrected in the buffer.

[See gif here](https://gfycat.com/blueantiquecrow)

However, it does so, when autocompleting headers.

[See gif here](https://gfycat.com/spectacularcavernouschevrotain)

As the behavior is different in the two cases, this might be a bug. 

Please note that I do have

```json
  "suggest.fixInsertedWord":true,
```
in my config

----

I do not think this is a problem with **coc** itself, as when I use it with other language servers, this issue does not happen.

**Comment by HighCommander4** [comment]
Looks like #387.

**Comment by HighCommander4** [comment]
(Closing as duplicate.)
