### ISSUE TITLE
Show errors in the configuration file

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#614]
**Currently**, errors are only shown in stderr.
![image](https://user-images.githubusercontent.com/10697249/100825135-5ae8ae00-3492-11eb-92fd-3b8802c72789.png)

**Expected:**
Show errors in the configuration file, just like code diagnosis.
![image](https://user-images.githubusercontent.com/10697249/100824985-10673180-3492-11eb-9485-31bc614ba298.png)

**Comment by sam-mccall** [comment]
Agree. The implementation was designed with this possiblity in mind (e.g. tracks locations of errors carefully).

I wonder whether clients will be ok with us blindly publishing diagnostics that are not "open" (at least, not associated with the language server because they have the wrong file type)

**Comment by njames93** [comment]
As a follow on from this, Is it wise to extend this to publishing diagnostics from parsing `.clang-tidy` and `.clang-format` config files?
Earlier today I was helping a user(on the clangd discord) debug why clangd appeared to not read their `.clang-format` file when formatting their project.
It was only after searching through their log file that the error was discovered to be the YAML parser failing to parse their configuration. As parsing these configurations will *almost* silently fail on parsing errors it could lead users to think there is a bug in the tools or they may just never notice they aren't working as expected.
In these cases its of course possible to have the error jump out by running the standalone tools, but that's not something we should expect users to have to do.

For the record the user in question didn't know where the log was written so they would have a near impossible task of figuring out the cause without help.

**Comment by sam-mccall** [comment]
Yeah, I think this makes sense. Even without precise location information, an LSP diagnostic at line 1 of the config file seems like a nice way to present this.

I wonder if there's a better API than the diagnostic-callback-passed-into-provider one, though.

**Comment by njames93** [comment]
The YAML parser does have precise location information, though sometimes errors are questionable, but that's an issue for another day.
