### ISSUE TITLE
wondows , use clangd and mingw-w64 in vscode ,  find c++ headers error

### ISSUE THREAD

**Issue by didi514354875** [clangd/clangd#615]
set  --query-driver=C:\\PROGRA~1\\MINGW-~1\\bin\\X86_64*.* ,but clangd  find c++ header files in error path , some in MinGw c++ inlcude path,   some in MSVC c++ include path, please help me

**Comment by sam-mccall** [comment]
Sorry, there's not enough info here to suggest a bug, and we can't provide support apart from handling bug reports.
