### ISSUE TITLE
Can not identify class in *.hpp

### ISSUE THREAD

**Issue by JeongJae0815** [clangd/clangd#619]
**System information**
clangd version 11.0.1
Operating system: Ubuntu 18.04(docker)

Hi guys!!:) I've moved to clangd from intellisense recently. Now I am a huge fan of clang, clangd 👍 
Unfortunately, I've got critical issue on my c++ project with clangd.
For some reason, my header consist of cxx,h and h(for template class).
In *.hxx, clangd can not recognize class(which is defined in *.h ). It does indentify a function well tho.
Back on intellisense, It does well, but clangd doen't.(but compiling does work well on both)
what should I do for making clangd recognizing *.hpp well from class(defined in *.h)? 
Here is simple project

--------------------------file tree---------------------------------
```
|-- CMakeLists.txt
|-- Functions
|   |-- A.cxx
|   |-- A.h
|   |-- A.hxx
|   `-- CMakeLists.txt
|-- compile_commands.json -> ./build/compile_commands.json
`-- test.cxx

```
--------------------------CMakeLists.txt(on the top)---------------------------------
```
cmake_minimum_required(VERSION 3.15)
# set the project name and version
project(pcl-clangd-test VERSION 1.0)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pipe -std=c++11 -fPIC -w")
add_subdirectory(Functions)

add_executable(test test.cxx)
target_link_libraries(test PUBLIC A)
```
--------------------------test.cxx---------------------------------
```
#include "A.h"
int main(){
    A test_A(3);
    test_A.set_a(4);
    test_A.print_par();
    out_of_class_A();
}
```

--------------------------CMakeLists.txt(in Function)---------------------------------
```
# add the library that runs
add_library(A A.cxx) # velodyne_preprocessing.cxx 

target_include_directories(A
                            PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}
                            )
```
--------------------------A.cxx---------------------------------
`#include "A.h"`

--------------------------A.h---------------------------------
```
#pragma once

class A{
    public:
    A(int num){
        a=num;
    }
    void print_par();
    void set_a(int num);
    private:
    int a;

};
void out_of_class_A();
#include "A.hxx"
```

--------------------------A.hxx---------------------------------
```
#ifndef A_HXX
#define A_HXX
#include <iostream>
void A::print_par(){
    std::cout<<"a : "<<a<<std::endl;
}
void A::set_a(int num){
    a=num;
}
void out_of_class_A(){
    std::cout<<"haha"<<std::endl;
}

#endif
```
cannot indentify class "A" on "A::print_par()", "A::set_a()"
can identify "out_of_class_A" well.

**Comment by sam-mccall** [comment]
The problem is when processing A.hxx in isolation, there's no way to understand its association with A.h. (This isn't an issue when compiling as you never process it in isolation).

The simplest solution is to `#include "A.h"` from in A.hxx.
Now they circularly include each other, but since each is header-guarded you'll be fine.

For slightly complicated reasons clangd will warn about recursive inclusion in `test.hxx` but everything should work fine. (If you switch test.hxx to use `#pragma once` this will go away, though this isn't really a principled solution and I wouldn't recommend the pragma in general).

**Comment by JeongJae0815** [comment]
@sam-mccall 
Thank you for replying 👍 . I should follow your advice for a while. Is there another way? Like  modifying CMake or using another option on clangd,

**Comment by HighCommander4** [comment]
I don't think so, the underlying limitation in clangd is #45.

**Comment by JeongJae0815** [comment]
@HighCommander4
I appreciate it :) 
I'll keep that in mind
