### ISSUE TITLE
Enum semantic highlighting

### ISSUE THREAD

**Issue by rapgenic** [clangd/clangd#622]
In the more recent semantic highlighting feature (I am testing with clangd master, but I think this is related to every server supporting the new highlighting protocol) there is some inconsistency in how enums are rendered (using vscode screenshots but this should apply to other editors too).

- Enum declaration (working and highlighted as expected):
  ![Schermata da 2020-12-11 12-32-58](https://user-images.githubusercontent.com/10487071/101899756-a3008280-3bae-11eb-9767-8513b9e9d711.png)
- **Enum usage (actual vs expected):**
  ![Schermata da 2020-12-11 12-32-24](https://user-images.githubusercontent.com/10487071/101900035-17d3bc80-3baf-11eb-9319-33799fa9b9dc.png)

### Possible reason

I think this is due to the fact that in the SemanticHighlighting.cpp file the type `HighlightingKind::EnumConstant` is assigned to LSP explicitly nonstandard type `enumConstant`, whereas [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens) already provides `enumMember` (see https://github.com/llvm/llvm-project/blob/4c5e0c7fd801ccc52d3b137fa685d4215a6c57ed/clang-tools-extra/clangd/SemanticHighlighting.cpp#L573)

I tried substituting `enumConstant` with `enumMember`, that, to me, seems to refer to the same concept, and the highlighting works now as expected. Is there a reason it is not this way?

**Comment by rapgenic** [comment]
An otherwise quick workaround is to add in your configuration (this is of course vscode specific):
```json
    "editor.semanticTokenColorCustomizations": {
        "[Default Dark+]": {
            "rules": {
                "enumConstant:cpp": "#4FC1FF",
                "enumConstant:c": "#4FC1FF"
            }
        }
    },
```

Reporting in case anyone needs this, as a separate message

**Comment by njames93** [comment]
Unsure why it was that way, I've put a patch in to address this shortcoming https://reviews.llvm.org/D93113

**Comment by njames93** [comment]
A quick look suggests that in LSP 2.x `enumMember` wasn't defined, that may be the reason why it was added as an extension.

**Comment by njames93** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/62b4a69969c38158ce0c49803c50c32a76bbbe14 Made a typo so github wont auto close this
