### ISSUE TITLE
Add a __CLANGD__ macro

### ISSUE THREAD

**Issue by njames93** [clangd/clangd#624]
This is a feature that exists on the Intellisense compiler which can improve UX.
The idea is when when Intellisense runs over your code it defines a macro called `__INTELLISENSE__`. Using this you can disable blocks of code that may negatively affect UX. 
This is useful for doing some kind of pre-processor hackery with multiplie inclusions of the same file.

It can also be used to suppress errors if your code has some extensions that Intellisense doesn't understand.
Given how accommodating clang is for extensions(both MSVC and gcc) I can't see that issue appearing too often, but for teams running custom patched versions of compilers this could be a definite improvement.

As its rather trivial to implement with no penalty if unused, it definitely warrants being accommodated.

**Comment by HighCommander4** [comment]
There is some discussion of this in #581.

**Comment by njames93** [comment]
Fair enough, Closing this
