### ISSUE TITLE
[Feature request] fix bugprone-sizeof-expression false positives sizeof(A*)

### ISSUE THREAD

**Issue by fx-carton** [clangd/clangd#625]
In C, it's common to take the size of pointers; for example:
```
struct T** array;
size_t numElements;
array = malloc(numElements * sizeof(*array));
```
Since `*array` is a pointer, `clangd` returns the following warning:
```
Suspicious usage of 'sizeof(A*)'; pointer to aggregate [bugprone-sizeof-expression]
```
The code is, however, correct; and this is a common pattern. Could `clangd` detect such cases?

Alternatively, I'd be fine with a way to disable those warnings, because I don't want false positives like this.

**Comment by fx-carton** [comment]
Conversely, there is no warning for :
```
array = malloc(numElements * sizeof(**array));
```

It could be useful if a warning was issued in that case.

**Comment by HighCommander4** [comment]
clangd just exposes diagnostics from [clang-tidy](http://clang.llvm.org/extra/clang-tidy/).

clang-tidy provides a number of ways to suppress diagnostics, such as disabling a specific warning via the `.clang-tidy` configuration file, or disabling warnings on a specific line via a `// NOLINT` comment`; see the page linked above for details.

If you feel the above mechanisms are not sufficient and would like to propose a change to the default behaviour of clang-tidy, pleae file a bug in the [clang-tidy component](https://bugs.llvm.org/enter_bug.cgi?product=clang-tools-extra&component=clang-tidy) of the LLVM bug tracker.

**Comment by fx-carton** [comment]
Ah I see, I didn't know this was from clang-tidy. Indeed I can use `-clang-tidy-checks` to disable the warning. I still think the warning should be improved, but as you said, this is an issue in clang-tidy, not clangd. So I'm closing the issue here.
