### ISSUE TITLE
.clang-format unkown key "BraceWrappingAfterControlStatementStyle"

### ISSUE THREAD

**Issue by JanHildenbrandBosch** [clangd/clangd#626]
I'm using the clangd extension for vscode to auto-format the code. 
My understanding is, that this is done through the clangd (and not over an installed clang-format binary). Although clangd-10 is installed it seems that the .clang-format does not understand every command of clang-format-10 (https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormatStyleOptions.html e.g. "BraceWrappingAfterControlStatementStyle"). Instead only  "AfterControlStatement : true" works currently which seems to be from an earlier version.

This seems very confusing to me. My expectation would be clangd-10 includes clang-format-10.
Apologies if this is not the correct repo for this issue.

**Logs**
```
.clang-format
BraceWrapping :
  BraceWrappingAfterControlStatementStyle : Always
BreakBeforeBraces: Custom
```
```
YAML:31:45: error: unknown key 'BraceWrappingAfterControlStatementStyle'
  BraceWrappingAfterControlStatementStyle : Always
                                            ^~~~~~
I[16:24:25.667] getStyle() failed for file /workspace/***/File.c: Error reading /workspace/.clang-format: Invalid argument.
```

**System information**
Output of `clangd --version`: clangd version 10.0.0-4ubuntu1~18.04.2 
Editor/LSP plugin: vscode - clangd extension
Operating system: ubuntu 18.04 lts

**Comment by gislan** [comment]
The option is called AfterControlStatement. BraceWrappingAfterControlStatementStyle is the type (enum) of this option. It means values of Always, Never and MultiLine are allowed, as well as true/false for backwards compatibility. You want something like:

```
BraceWrapping:
  AfterControlStatement: Always
```

**Comment by JanHildenbrandBosch** [comment]
You are perfectly right. Thanks for the help!
