### ISSUE TITLE
[semantic highlighting] regression: class member not colored anymore

### ISSUE THREAD

**Issue by maximeB** [clangd/clangd#627]
Using clangd-11 the class member are colored in blue (vscode OneDarkPro theme)
Using clangd-12 the class member are colored as regular variable.

**System information**
Output of `clangd --version`: clangd version 12.0.0 (https://github.com/llvm/llvm-project.git 8acb5f2723ecaf0f1904a085ad79d0623cec38f6)
Editor/LSP plugin: vscode/clangd
Operating system: Windows (remote ssh on centos 7)

**Comment by njames93** [comment]
In https://github.com/llvm/llvm-project/commit/de5b0b776fd7de72078256e003ede4fb5c37cdcb, Fields were updated from being reported as `member` to `property`. 

My guess is you have `property` mapped to the same colour as `variable`.

**Comment by maximeB** [comment]
Indeed, changing the "property" settings solved it.
Thank you very much for such a quick support 👍 

For reference I added the following in my settings:
```json
"editor.semanticTokenColorCustomizations": {
        "[One Dark Pro]": {
            "rules": {
                "property": {
                    "foreground": "#61afef",
                    "fontStyle": "italic bold"
                },
            }
        },
    }
```
