### ISSUE TITLE
Clang-tidy information should not be taken into account when the Checks is provided on the command line.

### ISSUE THREAD

**Issue by lmcbout** [clangd/clangd#63]
### Description
It seems the "Checks: hicpp*" from a clang-tidy in the same folder is also considered
  when executing the command from the command line.

From  https://clang.llvm.org/extra/clang-tidy/
Section: Configuration files:
"If any configuration options have a corresponding command-line
  option, command-line option takes precedence. "
  
  Note:  Command: "clang -clang-tidy -clang-tidy-checks=* File1.cpp", I get warnings for "hicpp*, readability* and modernize-* ".

### Reproduction Steps
No file: clang-tidy
command: clang -clang-tidy -clang-tidy-checks=modernize-* File1.cpp should only return warnings associated to " modernize " ==> OK

Now create a file : .clang-tidy and set the following: " Checks: hicpp*, "
Run the same command : clang -clang-tidy -clang-tidy-checks=modernize-* File1.cpp ==> get warnings for hicpp* and modernize* ==> NOT OK according 
of the comment on the documentation.
I think it was nice to be able to supersede the value set in ".clang-tidy" file

**OS:**
Ubuntu 16.04
Clangd: clangd version  9

**Diagnostics:** 
According to documentation , the "Checks" from the .clang-tidy file should only apply when the "-clang-tidy-checks=" is not provided from the command line.

**Comment by hokein** [comment]
This is by-design in clang-tidy. The document might be confusing there -- basically we merge the configs from `.clang-tidy` and `-clang-tidy-checks`.

If you want to drop the configs from `.clang-tidy`, you'd need to disable it in `-clang-tidy-checks`, which is `--clang-tidy-checks=-*, modernize-*`.

**Comment by lmcbout** [comment]
I think it would be nice if the documentation was updated to remove confusion.
Thanks @hokein  for your information.
