### ISSUE TITLE
Cannot find some system headers when clangd is located outside of /usr/local/bin

### ISSUE THREAD

**Issue by smhc** [clangd/clangd#64]
test.c:
```
#include <stdlib.h>
int main() {
    return 0;
}
```

clangd reports the diagnostic: In included file: 'stddef.h' file not found /usr/include/stdlib.h:32:10: note: error occurred here.

clangd version: clangd version 9.0.0 (/clang 0bddef79019a23ab14fcdb27028e55e484674c88)

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28.0.1)

Oracle Linux 7.6: https://hub.docker.com/_/oraclelinux/
FROM oraclelinux:7.6

**Comment by smhc** [comment]
If clangd is located in /usr/local/bin this is not an issue. 
However if a static build of clangd is located in a different path it cannot find some system headers.

Is there a possible workaround for this problem? Perhaps --resource-dir ?

**Comment by kadircet** [comment]
Could you share an entry from your compile commands.json file?

**Comment by smhc** [comment]
The compile_commands.json file is simply:

```
[
    {
        "arguments": [
            "gcc",
            "-c",
            "test.c"
        ],
        "directory": "/home/x",
        "file": "test.c"
    }
]
```

As mentioned, it works fine with --resource-dir=/usr/local/lib/clang/9.0.0, but otherwise fails.
It should be easy enough to reproduce by simply putting a statically built clangd in a different directory than /usr/local/bin and using gcc as the compiler.

Are the headers in /usr/local/lib/clang/9.0.0/include meant to be a requirement for running clangd, or is this a possible oversight? It does seem strange to me if it is a requirement.

**Comment by ilya-biryukov** [comment]
`compile_commands.json` is not an issue here.

If you move the `clangd` binary around, you should also put the builtin headers alongside it.
`clangd` looks tries to find those relative to its path in `../lib/clang/<version>/include`. E.g. if you have `clangd` version 9 at `/opt/bin/clangd`, it will look for builtin headers at `/opt/lib/clang/9.0.0/include`.

**Comment by ilya-biryukov** [comment]
Note that this only applies to a small set of builtin headers, search locations for other common headers (e.g. C and C++ standard library headers) are should be inferred independent of `clangd`'s binary location.

**Comment by smhc** [comment]
Thank you Ilya, I'll take that as confirmation these builtin clang headers are a runtime requirement for clangd. From my testing these seem like the only additional dependency for a static built clangd on a typical linux installation. 

I am putting together an internal distribution of clangd for environments that do not have a llvm/clang installation.  Bundling the headers and using --resource-dir is an ok workaround for me. I assume people doing the same with libclang tools encountered the same issue(?).

clangd is quite useful as a standlone tool combined with vscode-clangd and the like. One day it might be nice to have a clangd only distribution that does not require installing clang or hacking together the needed headers. 

I am happy to close the issue.
