### ISSUE TITLE
Wrong parameter types in extracted function

### ISSUE THREAD

**Issue by OleksandrKvl** [clangd/clangd#640]
Extracting from this function:
```cpp
void f(const std::vector<int> &v1, std::vector<int>& v2)
{
    const auto x = v1.size() + v2.size();
}
```
results in broken parameter types for `std::vector`:
```cpp
void extracted(std::const std::vector<int>& v1, std::std::vector<int>& v2)
{
    const auto x = v1.size() + v2.size();
}
```

The problem is probably somewhere in `printType()`/`getQualification()` functions which yield a wrong string representation of a type.

**System information**
Output of `clangd --version`: Ubuntu clangd version 11.0.1-++20201218093155+43ff75f2c3fe-1~exp1~20201218203809.158
Editor/LSP plugin: vscode 1.52.1, clangd 0.1.8
Operating system: Ubuntu 20.04

**Comment by HighCommander4** [comment]
Similar to #524
