### ISSUE TITLE
Newer weekly snapshot releases are missing binaries

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#641]
The latest weekly snapshot release that has binaries is 20201122 (Nov 22).

There are newer snapshot releases such as [20210103 (Jan 3)](https://github.com/clangd/clangd/releases/tag/untagged-f99a062c2d64f4751e96), but they are missing binaries. They are also marked as `Draft` rather than `Pre-release`, and do not appear to be accessible to users who are not project members.

**Comment by kirillbobyrev** [comment]
Yes, there was a problem with new gRPC version and CMake build with remote index enabled shortly before I went on vacation. I'm coming back the next week and was going to start by looking into this. An easy way to fix is to downgrade gRPC version to what it was before but the one currently being installed we use in the buildbots and I'm curious to understand why it isn't working as expected.

Apologies for the problems caused, I didn't originally see it and only noticed when on vacation.

**Comment by sam-mccall** [comment]
The Draft vs Pre-release bit is working as intended by the way.

The last step of the automation publishes the draft, so if the build fails then it isn't published. This is good for the general public, as these stay hidden.

Leaving the drafts around without marking them somehow is confusing for project members, but I don't think it's worth complicating the automation to fix it.

**Comment by ammen99** [comment]
Sorry if this is a stupid question, but was the latest build supposed to work? (it doesn't)

https://github.com/clangd/clangd/releases/tag/snapshot_20210113

**Comment by kirillbobyrev** [comment]
No such things as stupid questions! The build is supposed to work but it was still running by the time you commented. Our infrastructure is a little complicated: "periodic" script creates new release and tag, "autobuild" then marks the release as "draft" making it private, starts the build and unmarks release as "draft" making it visible again after success. I actually forgot tags are always public so everyone can see those :) After the build is complete, binaries are uploaded to the release snapshot and to the appropriate tag.  The snapshot you linked is functional now, you can see the uploaded assets now.

**Comment by ammen99** [comment]
@kirillbobyrev Thanks a lot, I can indeed see the binaries now :)
