### ISSUE TITLE
textDocument/implementation doesn't resolve local classes

### ISSUE THREAD

**Issue by njames93** [clangd/clangd#644]
Take this annotated example, where implementation is called on the points `$^` and returns the corresponding ranges `$[[]]`
```c++
class $Class^A {
public:
  virtual ~A();
  virtual void $Method^doSomething();
};

class $Class[[B]] : A {
public:
  void $Method[[doSomething]]() override {}
};

namespace Other {
class $Class[[C]] : A {
public:
  void $Method[[doSomething]]() override {}
};
} // namespace Other

void foo() {
  class D : A {
  public:
    void doSomething() override {}
  };
}
```
As can be seen, the implementation(`D`) in `foo`  is not returned.
This behaviour appears to happen when everything is defined in the same file, or if the implementations are in their own cpp file.

**Comment by HighCommander4** [comment]
Type hierarchy has the same issue.

**Comment by usx95** [comment]
Thanks for filing this.
Both `textDocument/typeHierarchy`(for subclasses) and `textDocument/implementation` are driven by the index.
Currently the index does not collect local symbols (such as those declared inside a `FunctionDecl`, `BlockDecl`,..).
This was done primarily to reduce the size of the index and thus the results are not entirely accurate in such a case.

**Comment by njames93** [comment]
Would it be wise to index just polymorphic classes inside functions, blocks, lambdas etc. There may be a case to index all records, but i feel there could be too much of a penalty there.

**Comment by hokein** [comment]
As discussed offline with @usx95, indexing function-local classes (and its methods) looks like a reasonable fix.
Defining a class inside function body is not a super common pattern, so the increase of memory should not be large. 

I think it is worth to try this solution and see how it goes (measuring the size of the index and the performance of the index).

**Comment by usx95** [comment]
Sent https://reviews.llvm.org/D94785 for review.

**Comment by njames93** [comment]
Thanks for fixing this :+1:
