### ISSUE TITLE
documentation is bad comparing to ccls

### ISSUE THREAD

**Issue by GopherJ** [clangd/clangd#645]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
Output of `clangd --version`: `clangd version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)`
Editor/LSP plugin: `coc.nvim, neovim`
Operating system: `LInux Mint 19.3`

![image](https://user-images.githubusercontent.com/33961674/104594380-5d354f00-5671-11eb-89a0-ab8a77b48553.png)

**Comment by njames93** [comment]
Care to elaborate. Any specific places you feel are lacking documentation. The website does a pretty decent job as it is right now.

**Comment by HighCommander4** [comment]
I think the reporter is referring to the way a function's Doxygen documentation is rendered in the posted screenshot (which I assume is of a hover window).

**Comment by GopherJ** [comment]
@HighCommander4 @njames93 Yes I mean the function documentation, I'm not sure it's clangd's error or coc.nvim's error

**Comment by HighCommander4** [comment]
Dupe of #529?

**Comment by kadircet** [comment]
This is a mixture of coc.nvim's markdown mocking and clangd's lack of doxygen comment parsing.

as mentioned in https://github.com/clangd/coc-clangd/issues/48#issuecomment-633141452, we've changed our escaping to be less aggressive with recent versions of clangd. you can try with clangd-11 to have better results, which is available at https://releases.llvm.org/download.html#11.0.0.

though the doxygen comment processing is still lacking as @HighCommander4 pointed out.

**Comment by GopherJ** [comment]
@kadircet Hi, I justed tested and it's much more, it's not perfect yet but thanks for improving it.

![image](https://user-images.githubusercontent.com/33961674/104709445-3e8d9180-571f-11eb-9f91-b41f3170dc8e.png)

I think the documentation is a little bit too wide, but this is maybe the json library's issue. The `@param` is not highlighted yet, I'll try some other colorscheme to see if it improves

**Comment by GopherJ** [comment]
@kadircet @HighCommander4 Let's only open #529 thanks for your replies
