### ISSUE TITLE
VSCode Plug-in terminates unexpectedly when searching for symbols

### ISSUE THREAD

**Issue by moether** [clangd/clangd#648]
Using one of the current development snapshots of clangd, the vscode plugin suddenly stops when I use Ctrl-T and search for "main".
The issue is always reproducible using for example the libwebsockets project from https://github.com/warmcat/libwebsockets/archive/v4.1.6.tar.gz
Note that this problem never occurs when I switch back to clangd 11.0.

**Extension Host Tab**
`[2021-01-15 08:48:12.994] [exthost] [error] [llvm-vs-code-extensions.vscode-clangd] provider FAILED
[2021-01-15 08:48:12.994] [exthost] [error] Error: Connection got disposed.
	at Object.dispose (/home/thomasm4/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/home/thomasm4/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at /home/thomasm4/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.9/node_modules/vscode-languageclient/lib/common/client.js:2320:28`

**Full Clangd Logs**
[issuelog.txt](https://github.com/clangd/vscode-clangd/files/5819476/issuelog.txt)

**System information**
Clangd version (from the log, or `clangd --version`): clangd version 12.0.0 (https://github.com/llvm/llvm-project.git ceb9379a90f5a320d19f5694ef00b4d1164fa7d6)
clangd extension version: 0.1.9
Operating system: Manjaro Linux

**Comment by kadircet** [comment]
Sent out https://reviews.llvm.org/D94755

**Comment by moether** [comment]
Your diff fixes the issue. Thanks for the quick response!
