### ISSUE TITLE
SelectionTree returns wrong common ancestor in multiple variable declaration 

### ISSUE THREAD

**Issue by sureyeaah** [clangd/clangd#65]
```cpp
int main() {
  int a = 1;
  int a = 1, b = 2;
}
```

Upon selecting 1, the common ancestor should just be 1 with the type IntegerLiteral in both statements but in the second statement, the common ancestor is the whole declaration.

**Comment by sureyeaah** [comment]
Another test case:
int a[] = {1, 3};

**Comment by kadircet** [comment]
not sure about the second case, but for the first case there is `decls()` inside `DeclContext`.
we can check if there is any other `VarDecl` inside current context that is overlapping with current one and choose the one with minimum length(which should be the first decl).
