### ISSUE TITLE
Clangd website should document which features (e.g. config keys) were introduced in which versions

### ISSUE THREAD

**Issue by ell1e** [clangd/clangd#650]
The `ClangTidy` key as documented here https://clangd.llvm.org/config.html doesn't appear to work, I'm getting a warning: `Unknown Config key ClangTidy`. I want to disable `bugprone-sizeof-expression` because it is extremely high on false positives in my project. (A lot of bogus `Suspicious usage of 'sizeof(A*)'; pointer to aggregate` messages, basically.)

This is the config file in question:

```
Index:
  Background: Build

ClangTidy:
  Add: modernize*
  Remove: bugprone-sizeof-expression
```

**Logs**
```
I[07:43:29.640] clangd version 11.0.0 (Fedora 11.0.0-2.fc33)
I[07:43:29.641] PID: 655860
I[07:43:29.641] Working directory: /home/ellie/prj
I[07:43:29.641] argv[0]: /usr/bin/clangd
I[07:43:29.641] Starting LSP over stdin/stdout
I[07:43:29.641] <-- initialize(0)
I[07:43:29.641] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
I[07:43:29.641] --> reply:initialize(0) 0 ms
I[07:43:29.660] <-- initialized
I[07:43:29.660] <-- textDocument/didOpen
I[07:43:29.661] config warning at /home/ellie/prj/.clangd:4:0: Unknown Config key ClangTidy
I[07:43:29.661] Loaded compilation database from /home/ellie/Develop/prj
I[07:43:29.661] --> window/workDoneProgress/create(0)
I[07:43:29.661] Enqueueing 0 commands for indexing
```

**System information**
Output of `clangd --version`: `clangd version 11.0.0 (Fedora 11.0.0-2.fc33)`
Editor/LSP plugin: clangd plugin 0.1.7 for VSCodium 1.51.1
Operating system: Fedora 33

**Comment by HighCommander4** [comment]
I think it was added in clangd 12.

**Comment by ell1e** [comment]
Ah, that would certainly explain it. Maybe the documentation could use a `clang 12` badge then? I see a `clang 11` one at the top for the existence of the config file, but the `ClangTidy` section itself has no mention that this specific option was added later.

Was `If` also added in 12 by any chance? Since I'm having some trouble getting that one to work as well.

**Comment by HighCommander4** [comment]
You make a good point about different clangd versions.

As a point of comparison, for clang-tidy, there are separate websites for [clang-tidy 11](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html) vs. [clang-tidy 12](https://clang.llvm.org/extra/clang-tidy/index.html), each built from the relevant branch of the LLVM repo.

Perhaps it should work similarly for clangd?

**Comment by HighCommander4** [comment]
> Was `If` also added in 12 by any chance?

I'm pretty sure `If` is supported since clangd 11.

> Since I'm having some trouble getting that one to work as well.

Please feel free to file an issue with more details.

**Comment by HighCommander4** [comment]
> As a point of comparison, for clang-tidy, there are separate websites for [clang-tidy 11](https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html) vs. [clang-tidy 12](https://clang.llvm.org/extra/clang-tidy/index.html), each built from the relevant branch of the LLVM repo.
> 
> Perhaps it should work similarly for clangd?

(I realize that the clangd website lives in a [separate repo](https://github.com/llvm/clangd-www), but its contents could still be snapshotted at a time an LLVM release is cut.)

**Comment by DNS320** [comment]
@ell1e
I think you ran into the same problem as I did: https://github.com/llvm/clangd-www/pull/24
This should work:
```
Diagnostics:
  ClangTidy:
    Add: modernize*
    Remove: bugprone-sizeof-expression
```

**Comment by ell1e** [comment]
Omg yes, looks like it! Great find, and thanks for cross-referencing it here! :tada:
