### ISSUE TITLE
How to find files in a different shell environment

### ISSUE THREAD

**Issue by nesc1** [clangd/clangd#657]
Hi,

I'm trying to use clangd with vscode but i'm getting to much errors about missing files.

I'm using WSL in windows with vscode using remote ssh.
On the linux environment i'm building the project inside a special environment.
In the linux system I have no boost for example installed and in the build environment shell I have the boost installation and include files.

Inside this environment I build my project all ok and I see all the include files that clangd is saying that are missing.

Outside the build environment these files are accessible for example on /home/nuno/sdk/usr/include/...

My question is, is it possible to instruct the clangd to instead of looking into /usr/include/... path look into /home/nuno/sdk/usr/include/...
And if it is, how can I do this?

Another problem is that the gcc/clang version inside the environment is different from my system... don't know if this is also a problem.

Best regards,
Nuno

**Comment by kadircet** [comment]
> My question is, is it possible to instruct the clangd to instead of looking into /usr/include/... path look into /home/nuno/sdk/usr/include/...

you can achieve this by providing clangd with appropriate compile flags. `--sysroot` might be helpful. As for passing these to clangd, you have a couple of options as explained in http://clangd.llvm.org/installation.html#project-setup and http://clangd.llvm.org/config.html#compileflags

> Another problem is that the gcc/clang version inside the environment is different from my system... don't know if this is also a problem.

yes and no. clangd embeds its own version of clang compiler, so it won't make use of the system installed compiler. but there might be different issues if you generate your compile flags through a build system and there are some flags clangd can't understand. but it should be a rare issue as gcc and clang is mostly compatible compile-options-wise.

**Comment by njames93** [comment]
You can use the [query-driver](https://releases.llvm.org/10.0.0/tools/clang/tools/extra/docs/clangd/Configuration.html#query-driver) Flag to let clangd execute the binary found in the compile_commands and figure out its include path.
Alternatively you can use the `CompileFlags` in [.clangd config](https://clangd.llvm.org/config.html) to manually add the includes
```
CompileFlags:
  Add [ isystem=/home/nuno/sdk/usr/include/ ]
```
Syntax may be a little off but something like that should work.

**Comment by nesc1** [comment]
Hi all, thank you all for your help, it seems that the:
```yaml
CompileFlags:
  Add: [ isystem=/home/nuno/sdks-mgu/curr/usr/include ]
```
did the trick to find the system files, at least it does not complain about not finding the file (it does not open it when i use "go to definition")

but now i'm receiving a lot of errors like:
```
{
	"resource": "/home/nuno/workspace/project/common/framework/include/mgu/Logger.h",
	"owner": "_generated_diagnostic_collection_name_#16",
	"code": "fe_expected_compiler_job",
	"severity": 8,
	"message": "Unable to handle compilation, expected exactly one compiler job in ' \"/usr/bin/c++\" \"-cc1\" \"-triple\" \"x86_64-unknown-linux-gnu\" \"-fsyntax-only\"\"-ferror-limit\" \"19\" \"-stack-protector\" \"2\" \"-fgnuc-version=4.2.1\" \"-fcxx-exceptions\" \"-fexceptions\" \"-vectorize-loops\" \"-vectorize-slp\" \"-faddrsig\" \"-x\" \"c++-header\" \"isystem=/home/nuno/sdk/curr/usr/include\"; '",......
	"source": "clang",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

```

**Comment by nesc1** [comment]
i think the only possible solution for this is to "force" the clangd to work inside the special shell.

Is this possible to force clangd to work inside an environment created by a shell?

**Comment by sam-mccall** [comment]
You've added `isystem=...` but the flag needs a leading dash: `-isystem=...`.

**Comment by nesc1** [comment]
@sam-mccall  yap you are correct but that only fix the clangd errors of compilation, it still can't find some system files that are for example in directories that cmake knows but clangd don't know.
what I really need is to have the clangd environment inside the build shell environment... need to find out if this is possible to do...
Thanks for all the help.

**Comment by sam-mccall** [comment]
CMake is supposed to communicate what it knows via compile_commands.json. The compiler should communicate what it knows when probed with --query-driver.

If you can't build in the environment where you're trying to run clangd in, and are trying to use compile_commands.json from a different environment or --query-driver with a compiler that can't build the project, then this is beyond what we can help with. I'd recommend trying to run clangd in the build environment. I can't tell if that's what you're doing, but based on the differences you mention between "build environment" and "Linux environment" I guess maybe not.
