### ISSUE TITLE
Custom include path

### ISSUE THREAD

**Issue by kolserdav** [clangd/clangd#663]
Hello!
If header file location is not standard then extension mark #include line as error;
How i can set custom include path for `clangd`?

**Comment by kadircet** [comment]
You can make use of a compilation database to tell clangd about your include paths. See http://clangd.llvm.org/installation.html#project-setup and clangd.llvm.org/config.html#compileflags for details.

**Comment by kolserdav** [comment]
> You can make use of a compilation database to tell clangd about your include paths. See http://clangd.llvm.org/installation.html#project-setup and clangd.llvm.org/config.html#compileflags for details.

It works)
I added `"clangd.arguments": ["-I./path/to/custom/include"]` in my local `settings.json` then restart `code` and problem was solwed.
Thank you!

**Comment by kolserdav** [comment]
I was mistaken, if I add a certain path to that `clangd` seems to stop working altogether, since it does not mark in red even those files that do not exist at all.

**Comment by kadircet** [comment]
"clangd.arguments" is for passing arguments to clangd itself.

you need to:
- provide your compile flags through `compile_flags.txt` or `compile_commands.json` as described in the `Project Setup` section of http://clangd.llvm.org/installation.html#project-setup, or
- have a `.clangd` config file as described in http://clangd.llvm.org/config.html#compileflags with contents
  ```
  CompileFlags:
    Add: -I./path/to/custom/include
  ```

**Comment by sam-mccall** [comment]
Closing as this definitely does work.
We should improve our docs though.
