### ISSUE TITLE
Nonsense include suggestions in empty files

### ISSUE THREAD

**Issue by njames93** [clangd/clangd#664]
If you have an empty file and write `#include <` then bring up completion, The results are less than ideal 
![Screenshot from 2021-01-25 11-56-29](https://user-images.githubusercontent.com/5469473/105703013-87ee9580-5f04-11eb-8d31-5387e1762f3d.png)

I've tried to test a few configurations and I've narrowed it down as best as I can.
If there is any code in the file it will work, this could be as simple as a single ';' this bug wont reproduce.
![Screenshot from 2021-01-25 12-18-42](https://user-images.githubusercontent.com/5469473/105705060-8f636e00-5f07-11eb-960b-ebf93ecc63ce.png)

It can be observed with both quoted and angle bracket includes.
The quotes/brackets can't be closed and must be followed directly with eof.
`#include <{EOF}`, `#include "{EOF}` both trigger this issue, However this doesn't as there is a new line:
```
#include <
{EOF}
```
![image](https://user-images.githubusercontent.com/5469473/105705198-c89bde00-5f07-11eb-82c5-a9d3f6228e1a.png)

**System information**
Output of `clangd --version`: clangd version 12.0.0 (git@github.com:llvm/llvm-project.git d18c3c7b18e9e78145d701c4687682848071ab98) - been observed on released versions too.
Editor/LSP plugin: vscode 1.52.1/ vscode-clangd 0.19
Operating system: ubuntu 20.04.1

**Comment by kpyrkosz** [comment]
I have observed exactly the same issue on:
- debian buster with clang-12 built from source
- debian testing, clang 11 from apt repository
- windows with official clang-11 release
All 3 environments are using VScode

**Comment by HighCommander4** [comment]
Sounds like a dupe of #433.

**Comment by njames93** [comment]
Good point, but I think this repro is a little more informative
