### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by Mr-Pyro** [clangd/clangd#667]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

I am getting "'iostream' file not foundclang(pp_file_not_found)" false positive in VSCode. Clangd
seems to have just stop working.

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

`#include <iostream>

int main(int argc, char **argv)
{

  if (argc != 2)
  {

    std::cout << "Incorrect number of arguments.\n" << argv[0] << " <scenario number>\n";

  }

  return 0;

}
`
Code compiles correctly on the system with installed compilers. Tried reinstalling clangd / clang. Tried --query-driver. No changes to clangd config have been made. I have recently installed mingw recently for cross-compiling (don't think this would have changed anything).  

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

https://paste.ubuntu.com/p/X72bqxZRs4/

**System information**
Output of `clangd --version`: clangd version 11.0.0 (from logs)
Editor/LSP plugin: llvm-vs-code-extensions.vscode-clangd
Operating system: Pop!_OS 20.04 LTS x86_64

**Comment by kadircet** [comment]
can you try installing libstdc++ ?  possibly via `sudo apt-get install libstdc++-10-dev`

**Comment by Mr-Pyro** [comment]
> can you try installing libstdc++ ? possibly via `sudo apt-get install libstdc++-10-dev`

oh thats weird. It works again now. Thank you.
