### ISSUE TITLE
Find-refs on virtual hierarchy goes (partly) in wrong direction

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#668]
At trunk, given:

```
struct A { virtual void foo() = 0; };
struct B : A { void foo() override; };
```

Find refs on A::foo() shows:
- decls of `A::foo()`
- decls of `B::foo()`
- refs to `A::foo()`
- refs to `B::foo()` <-- this seems dubious

Find refs on B::foo() shows:
- **no** decls of `A::foo()`
- decls of `B::foo()`
- **no** refs of `A::foo()` <-- this seems dubious
- refs of `B::foo()`

It looks like the implementation grabs the derived classes from the index and just adds them to findReferences index query.
Instead I'd suggest:
 - we add *base* methods to a separate refs lookup, and exclude declarations. (Base methods/classes are available through the AST)
 - after we find the derived classes with relations, perform a lookup (not refs) on them to find their locations. This will give us declaration + definition locations - for derived classes we want the definition and for derived methods we want the declaration location. (These are the locations that actually mention the base)

**Comment by HighCommander4** [comment]
#46 contains some related discussion

**Comment by usx95** [comment]
With the above changes: 
```
struct A { virtual void foo() = 0; };
struct B : A { void foo() override; };
```

Find refs on A::foo() shows:
- decls of `A::foo()`
- decls of `B::foo()`
- refs to `A::foo()`
- no refs to `B::foo()` (**new**)

Find refs on B::foo() shows:
- decls of `A::foo()` (**new**)
- decls of `B::foo()`
- refs of `A::foo()` (**new**)
- refs of `B::foo()`

**Comment by tom-anders** [comment]
I think I found a small bug here:

```
struct A { virtual void foo() = 0; };
struct B : A { void foo() override; }; // textDocument/references returns a->foo() and b->foo()

void test() {
    A* a = new B();
    a->foo(); // A

    B* b = new B();
    b->foo(); // textDocument/references only returns b->foo() here, but NOT a->foo() here
}
```
Tested with clangd-14 (a91cfd1990255aea545683083329c2ad3fee4518)

**Comment by HighCommander4** [comment]
@tom-anders probably best to file a new issue, it's easy for a comment on a closed issue to be overlooked

**Comment by tom-anders** [comment]
Done, see #881
