### ISSUE TITLE
Support explicitly ignoring compilation database when using .clangd

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/clangd#672]
I'm doing some work on systemd-boot. Because systemd boot is an efi application and building efi applications isn't directly supported by meson, systemd's build system, the systemd-boot build is done entirely using meson custom targets. The specifics of this aren't important but a side effect of this is that the commands to build systemd-boot do not end up in the compilation database generated by meson.

To work around this, my idea was to use a .clangd file and list the compilation flags explicitly. However, even when specifying a .clangd file, clangd still uses another file from the compilation database as a heuristic and appends the flags from the .clangd to this compilation flag instead of using the flags from the .clangd file exclusively.

Ideally, CompileFlags would have an option IgnoreCompilationDatabase that would make clangd ignore the compilation database for all files managed by that .clangd config.

**Comment by sam-mccall** [comment]
I actually landed this just before the 12 release cut, and haven't updated the docs yet.  https://github.com/llvm/llvm-project/commit/118c33ef47acae6ebb91350cf8f7bfb85427ef4e#diff-4c122c87e83ef21b528325199fc2fdb05bec0e6278603e5245bc7ecea055d57bR154

In the `CompileFlags` section, you can specify `CompilationDatabase: None`. Other valid values are `Ancestors` (the default) or the path to a directory containing the CDB.

You'll need a really recent build, or the upcoming 12 release, though.

**Comment by DaanDeMeyer** [comment]
Awesome! Thanks for adding this!
