### ISSUE TITLE
Support -include flag

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/clangd#673]
From GCC's man page:

> -include file
    Process file as if "#include "file"" appeared as the first line of the primary source file. However, the first directory searched for file is the preprocessor's working directory instead of the directory containing the main source file. If not found there, it is searched for in the remainder of the "#include "..."" search chain as normal.

This currently isn't handled correctly by clangd. I get error diagnostics on symbols from the headers passed via the -include option. Would it be possible to support this?

**Comment by kadircet** [comment]
Could you provide more details on how you tried and what diagnostics you got? As clangd does support implicitly including headers via `-include`.

e.g. have a compile_flags.txt with (the same should work with compile_commands.json):
```
-include
abc.h
```

and then having abc.h with:
```
int abc;
```

and a.c with:
```
void foo() { abc = 2; }
```

you should not get any errors in a.c.

**Comment by DaanDeMeyer** [comment]
You're right, I just tried again and it works. I must have gotten something wrong with the paths. Thanks for the support!
