### ISSUE TITLE
clangd does not navigate to definition of a function if a call does not match exact function's signature

### ISSUE THREAD

**Issue by dowel** [clangd/clangd#674]
Assuming we have a function defined as follows:
`
void foo(int arg) {
    do_something_with_args(arg);
}
`

and somewhere else I have a call:
`foo(10, 20);`

If I ask to navigate to `foo` from the invocation spot, clangd refuses to do so unless the invocation signature matches exactly the function's declaration. I.e. if the code is `foo(10);` it works.

At a glance current behavior makes sense, but it does not fit the typical workflow where a programmer decides to add an argument to a function, adds it in the caller and then wants to jump to the function itself to change the function. I.e. in the example above the intent is to change `foo` to accept two arguments, but once I change the invocation, I cannot jump to `foo` anymore.

The problem equally applies to functions and C++ methods. 

Some side notes:
1. I could not really make my mind if this is an enhancement or a bug report. It is kind of both. Filing it as a bug.
2. I tried to change the code myself and post a pull request, but the learning curve is quite steep. Filing a bug with the hope that someone more knowledgable can fix it in no time.

**Comment by HighCommander4** [comment]
This works for me with recent clangd. It uses the "recovery AST" feature, which I think was made default in clangd 11 (and added behind the `--recovery-ast=true` command-line option in a previous release, possibly clangd 10).

**Comment by dowel** [comment]
I do have clangd-11. Trying to confirm that indeed it works as expected.

**Comment by dowel** [comment]
Unfortunately I don't see that it works too well. As soon as one of the arguments to a function is even of the wrong type, navigation stops working. I also noticed this with complex structures. E.g. when I navigate to internal member of a structure (or a class), navigation stops if I try to reference wrong member. For example:
```
struct foo {
    int member;
};
struct bar {
    struct foo f;
};
```

and somewhere in the code I have
```
struct bar b;
b.f.not_member;
```
and try to navigate to `b.f`, it does not work unless I either remove `.not_member` or fix it to be `.member`.

**Comment by HighCommander4** [comment]
> Unfortunately I don't see that it works too well. As soon as one of the arguments to a function is even of the wrong type, navigation stops working. 

Could you post an example please? There may very well be cases that the recovery-ast feature misses, but we need examples to make progress on them.

> I also noticed this with complex structures. E.g. when I navigate to internal member of a structure (or a class), navigation stops if I try to reference wrong member. For example:
> 
> ```
> struct foo {
>     int member;
> };
> struct bar {
>     struct foo f;
> };
> ```
> 
> and somewhere in the code I have
> 
> ```
> struct bar b;
> b.f.not_member;
> ```
> 
> and try to navigate to `b.f`, it does not work unless I either remove `.not_member` or fix it to be `.member`.

This works for me as well. Note, I'm using clangd nightly; perhaps this case has been improved since clangd 11.

**Comment by dowel** [comment]
I finally got some time to try the nightly build. At a glance it seems better. I'd like to keep this ticket open for another few days to make sure that the problem has indeed been fixed.

**Comment by sam-mccall** [comment]
Closing this, this feature will by its nature always be incomplete, but the common cases mentioned in this bug are supported today.
