### ISSUE TITLE
find-refs missing references from dependent node.

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#675]
given the following code:

```
template <typename T> void foo(); 
template <typename T> void bar() {
  foo<T>(); // find-refs only gives 1 foo-decl reference
}
```

I think find-refs should consider the UnresolvedLookupExpr `foo<T>()` as the reference of `foo` decl. The fix is to extend the libindex to report references from `UnresolvedLookupExpr`.

**Comment by HighCommander4** [comment]
Sam [mentioned](https://github.com/clangd/clangd/issues/399#issuecomment-633451281) that we may want to switch the implementation of find-refs from `libIndex` to `FindTargets` at some point. I believe that would solve this.

**Comment by hokein** [comment]
Yes, exactly. Switching from libindex to FindTargets is one of tasks in our backlog, but we don't prioritize it at the moment (at least Q1).
