### ISSUE TITLE
Leading type cast leads clangd to crash at code completion

### ISSUE THREAD

**Issue by ArcsinX** [clangd/clangd#676]
I found two problems, when having a leading type cast leads clangd to crash at code completion.

#### Problem 1
```c
void bar(){}
void foo() {
  (void)(bar)(^);
}
```
This could be fixed here: https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaCodeComplete.cpp#L5605 by adding `Fn->getType().isNull()` but I think this is not a correct way to fix this.

#### Problem 2
Similar to the previous one. (this one could be reproduced only with C code)
```c
struct Struct {
  int I;
};
int main() {
  struct Struct *S;
  return (int)(S)->^I;
}
```
This could be fixes with the similar check here: https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaCodeComplete.cpp#L5168

Seems these problems are related, because removing leading type cast helps. Can't figure out how to solve this in the correct way =(

**Comment by kadircet** [comment]
sent out https://reviews.llvm.org/D95935 for problem 1.

**Comment by kadircet** [comment]
added the fix for second one into that patch too, since they are related.
