### ISSUE TITLE
Go to definition called on a destructor declaration goes to the class definition

### ISSUE THREAD

**Issue by njames93** [clangd/clangd#679]
If a class has an out of line defined destructor, triggering go to definition on the declaration inside the class goes to the class definition, rather than the destructor definition. The reverse of this also happens, calling go to declaration on the out of line definition will again go to the class, rather than the destructor declaration inside the class.

It's also observed that hovering over the destructor declaration returns hover info pertaining to the class rather than the destructor. Although given how comments on destructors typically aren't useful, I think that behaviour is acceptable.

System information
Output of clangd --version: clangd version 13.0.0 (git@github.com:llvm/llvm-project.git cf37d03e79d227a5f6a9526c914afd01bcb6aeec)
Editor/LSP plugin: vscode 1.52.1 / vscode-clangd 0.1.9
Operating system: ubuntu 20.04.1

**Comment by HighCommander4** [comment]
#179 is related.

A workaround is to invoke the go-to-def in this position: `Class::[^]~Class`.

**Comment by HighCommander4** [comment]
It looks like this has been addressed by #179; closing.
