### ISSUE TITLE
Internal libstdc++ header suggested as include for uint8_t

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#68]
**Repro:** try completing `uint8_t`.

**Expected:** `#include <cstdint>` is added.
**Actual:** `#include <bits/stdint-uintn.h>` is added.

Note that if I choose to complete `std::uint8_t`, I get `<cstdint>` as expected.
We seem to have `std::uint8_t` in the canonical header map, but not `::uint8_t` (from global namespace).

**Comment by hokein** [comment]
The canonical mapping only tracks std symbols (for C++) and C library symbols (for C).

Symbols from C header within global namespace are pretty tricky in C++. C++ standard doesn't specify this behavior [1]: `#include<cstdint>` would imports all symbols in `std` namespace and **perhaps** in global namespace. 

I don't have an ideal solution in mind. We may use a whitelist for these common symbols. 

[1]: D.5 C standard library headers

> 2 Every C header, each of which has a name of the form name.h, behaves as if each name placed in the standard library namespace by the corresponding cname header is placed within the global namespace scope. It is unspecified whether these names are first declared or defined within namespace scope (3.3.6) of the namespace std and are then injected into the global namespace scope by explicit using-declarations (7.3.3).

> 3 [Example: The header `<cstdlib>` assuredly provides its declarations and definitions within the namespace std. It may also provide these names within the global namespace. The header <stdlib.h> assuredly provides the same declarations and definitions within the global namespace, much as in the C Standard. It may also provide these names within the namespace std. — end example ]

**Comment by sam-mccall** [comment]
The standard seems clear-ish: if you want to use std::printf you must include cstdio, if you want ::printf you must use stdio.h. 

Needless to say, people don't do this :-) they use a mix of std and unqualified, and are not very IWYU-clean. And code completion might exacerbate this.

Policy ideas:
 - we can say the c++ headers provide the symbol of that's true for the current standard library (index)
 - we can look at the popular std lib impls to see whether they provide the symbols in practice
 - we can downrank the unqualified symbols aggressively in c++ (maybe depending on the current set of includes)
 - we can never insert includes for the unqualified symbols
 - we can suggest a "qualify with std" fix (diagnostic?) if the unqualified name is used and its header isn't directly includes

**Comment by kadircet** [comment]
what about being on the safe side by mapping the symbols in global namespace into C header?
e.g
```
int64_t -> <stdint.h>
```

**Comment by sam-mccall** [comment]
Not sure that's safer, we'll end up with both cstdint and stdint.h included. Maybe we can add a hack for that.

**Comment by kadircet** [comment]
i said safer because stdint.h is guaranteed to have the symbol in global
namespace.

**Comment by kadircet** [comment]
Looks like this has been fixed, we seem to be only missing the mapping of `size_t` currently. so closing this as we've got another report for size_t

**Comment by yan12125** [comment]
The merged commit seems to be available since LLVm 12? https://github.com/llvm/llvm-project/commit/9190f17a7cc56b6eb6885fc8d08c8ac81d2c0c98

**Comment by kadircet** [comment]
yes it should be

**Comment by yan12125** [comment]
Great, thanks!
