### ISSUE TITLE
Standard header include directory specified with isystem not found

### ISSUE THREAD

**Issue by DaanDeMeyer** [clangd/clangd#683]
In my environment, the standard library include directory is specified via -isystem (don't ask me why). After verifying the isystem option path was correct in compile_commands.json and verifying that the iostream header was available in that directory, clangd still prints a diagnostic about <iostream> not being found in my test file (a simple hello world). Is this supposed to work with clangd 12.0.0 or does clangd only look for standard library includes in a fixed set of directories?

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

I'm not sure if I'm allowed to attach logs but I can ask whether this is possible if that might help.

**System information**
Output of `clangd --version`: clangd version 12.0.0 (git@github.com:llvm/llvm-project.git 72f12467ded52160d52025e13a6217f00fe25f68)
Editor/LSP plugin: vscode-clangd (remote)
Operating system: Linux

**Comment by HighCommander4** [comment]
I believe this is expected to work.

Perhaps clangd is not finding the `compile_commands.json`, or not using the right entry from it for some reasons? It's hard to tell without logs.

**Comment by HighCommander4** [comment]
A good sanity-check is to look at the log yourself for a line of the form:

> ASTWorker building file <path> version <version> with command [<directory>] <command>

and then see if (a) the command is what you expect, and (b) manually go to <directory> and run <command> in a shell and see if you still get the error.

**Comment by DaanDeMeyer** [comment]
I can confirm copy pasting the command from the logs and running it works fine and compiles the file as expected.

**Comment by DaanDeMeyer** [comment]
If someone can point me at the source code in LLVM where include directories are iterated I can add some logging there to see where clangd is looking for these includes.

**Comment by HighCommander4** [comment]
[This](https://searchfox.org/llvm/rev/0fcbbde2c7b02b89503d5d1b631229d64eab7104/clang/lib/Frontend/InitHeaderSearch.cpp#621) might be a good place to start looking.

**Comment by DaanDeMeyer** [comment]
Alright, that helped me get to the bottom of things. Not clangd's issue. Thanks for the help!
