### ISSUE TITLE
false positive on name conflict detection

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#685]
void test(int a); // => rename a => s, we detect a conflict in the body (actually, rename here is legal, this is just a declaration)
void test(int a) {
  int s;
}

**Comment by kadircet** [comment]
just an opinion, but i would actually expect a rename on a function parameter to rename occurrences in all the other declarations/definitions. (i suppose it is not easy with our current model of the index, but is probably a better UX we might want to achieve eventually.)

**Comment by kirillbobyrev** [comment]
@kadircet this would potentially make every rename (except in actual local scopes) global - quite scare for the performance reason. I agree that we should probably find all forward declarations & definitions within the main file itself for argument renaming.

Added a `FIXME` in https://reviews.llvm.org/D96247.

@hokein thanks for noticing and filing a bug!

**Comment by kadircet** [comment]
> @kadircet this would potentially make every rename (except in actual local scopes) global - quite scare for the performance reason. I agree that we should probably find all forward declarations & definitions within the main file itself for argument renaming.

right, but that's still a different interaction. if user intention is indeed renaming a parameter, especially just on a function declaration that's not a definition, they likely want to update all other places. as otherwise they could've just changed the text manually rather than triggering the rename workflow. (since no other references needs updating if you are only changing parameter name on a function declaration.)

**Comment by hokein** [comment]
> just an opinion, but i would actually expect a rename on a function parameter to rename occurrences in all the other declarations/definitions. (i suppose it is not easy with our current model of the index, but is probably a better UX we might want to achieve eventually.)

I agree that this is a nicer behavior.

- low hanging fruit: if rename is triggered in the definition, we can get all? decls from the AST, thus we could rename parameters for those decls; we might miss some decls, but I guess it should cover major case (where there is a decl in .h file, and a def in .cc file);
- tricky thing: if rename is triggered a non-def declaration, we don't have information neither from the index nor the AST,  peer-file parsing might help this case;
