### ISSUE TITLE
clangd does not index files indirectly included by the project

### ISSUE THREAD

**Issue by WTassoux** [clangd/clangd#693]
Hello,

I started using clangd recently and I have noticed that the headers indirectly included of my project are not indexed at all. For example, if I include boost/optional.hpp and I try to look at it, clangd will fail to find boost/optional/optional.hpp even though the include directory has been specified for both.

This is easily reproduceable with the following example:

**compile_commands.json**
```
[{
    "command": "g++ -I/data/Boost/include/ -o A.o -c A.cpp",
    "directory": "/home/me/tests/clangd/",
    "file": "A.cpp"
  }
]
```

**A.cpp**
```
#include <boost/optional.hpp>

int main()
{
  return 0;
}
```

In VSCode, when looking at boost/optional.hpp, the include directive will be underlined by red squiggles indicating that clangd did not find this include, even though it is available in the provided include directory.

![image](https://user-images.githubusercontent.com/1386182/108077268-9dbb2a80-706c-11eb-8b04-273600679030.png)

I am not sure whether this is desired behavior or not but if it is the case, it would be a great improvement to be able to browse through all include files with proper indexation.

Regards,

William

**Comment by kadircet** [comment]
Unfortunately this is WAI (or a known issue if you want). the compile_commands.json you have only covers the files under the directory containing it (probably `/home/me/tests/clangd/`).
So whenever you open A.cpp, clangd knows it can search for headers in `/data/Boost/include/`. But once you jump into boost/optional.hpp, which is not governed by the compile_commands.json you linked above, clangd uses a fallback command.
Unfortunately that command doesn't know about include paths, hence you don't get any include resolution.

You can workaround this issue by having a `~/.config/clangd/config.yaml` with contents:
```
If:
  PathMatch: /data/Boost/include/.*
CompileFlags:
  Add: -I/data/Boost/include/
```

**Comment by WTassoux** [comment]
Hello and thanks for your answer and the workaround,

On my actual project, things are a bit trickier as I have many internal libraries located in external folders, and some of these libraries are calling each other, so it'd be a bit difficult to manage dependencies like this. I'll see if I can find a way to make it work :)

Hopefully one day the option to automatically parse external includes will be available. That'd be a great addition !

I'm not sure whether I should close this issue or not, as it is working as intended it is probably more a feature request than a bug report.

Regards,

Willia,

**Comment by kadircet** [comment]
we had an issue around inferring compile flags for headers from source files user have been editing, normally that would be the canonical issue we should link this to. but i can't seem to find it :(

**Comment by HighCommander4** [comment]
Passing `--compile-commands-dir=<workspace-path>` (or whatever path contains the project's `compile_commands.json`) as a command-line argument to clangd should fix this.

In clangd 12 there is a way to specify this using `config.yaml` as well.

**Comment by WTassoux** [comment]
Hello and thanks for your replies.

@HighCommander4 Tested and approved ! Specifying --compile-commands-dir fixes the issue and allows indexation of headers outside the original project.  This will make browsing our codebase much easier. 

Regards,

William
