### ISSUE TITLE
huge memory consumption

### ISSUE THREAD

**Issue by GopherJ** [clangd/clangd#694]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

I've read https://github.com/clangd/clangd/issues/251 and it seems now clangd  doesn't eat so much memory anymore, but still it eats 2x memory than rust-analyzer. (**2.2GB vs 1.2GB on a small-medium project with no edit activity**)

![image](https://user-images.githubusercontent.com/33961674/108222073-697e6180-7173-11eb-9428-6c472e27c603.png)

rust-analyzer already claimed that they need to fix the huge memory consumption, will clangd take this into account?

See also: 
https://github.com/rust-analyzer/rust-analyzer/issues/1252

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
Output of `clangd --version`:  `Ubuntu clangd version 11.0.0-2~ubuntu20.04.1`
Editor/LSP plugin: `coc.nvim + neovim`
Operating system: `Linux Mint v20 cinamon`

**Comment by GopherJ** [comment]
This is important because often we need to edit at the same time multiple projects. If it consumes 2.2 GB with no editing activity it limits the number of projects we can work on.

**Comment by njames93** [comment]
This was fixed in https://github.com/llvm/llvm-project/commit/b8c37153d5393aad96feefe0b4689b7b62bc160d. That's in the 12 release branch.

**Comment by GopherJ** [comment]
ok thanks I'll try it

**Comment by njames93** [comment]
https://github.com/clangd/clangd/releases/tag/12.0.0-rc1 You can try this RC build, should be pretty stable.

**Comment by sam-mccall** [comment]
(Going to close this as presumptively fixed as the symptoms/config exactly match the problem that got fixed in the 12 release cycle)
