### ISSUE TITLE
Code Action: capture variable in the lambda function

### ISSUE THREAD

**Issue by kirillbobyrev** [clangd/clangd#697]
Given

```c++
int Variable = 42;
[]() {
  ++Variable;
};
```

We get the warning `Variable 'Variable' cannot be implicitly captured in a lambda with no capture-default specified [clang: lambda_impcap]`. It would be nice to suggest adding `Variable` to the capture list.

**Comment by njames93** [comment]
Put https://reviews.llvm.org/D96975 up for review, definitely needs refinement tho.

**Comment by kirillbobyrev** [comment]
Wow, this is really cool! Thank you for doing this, I will definitely take
a look!

**Comment by njames93** [comment]
Just a little demo so far.
![Peek 2021-02-18 19-35](https://user-images.githubusercontent.com/5469473/108411436-8cb31a80-7220-11eb-8293-e0615372790e.gif)

**Comment by njames93** [comment]
I think this can be closed now?

**Comment by kirillbobyrev** [comment]
> I think this can be closed now?

Right, thanks a lot 🙂 Also, for closing automatically "Resolves" or "Fixes" works, "Addresses" doesn't do the job 😞

Here's a list of acceptable words: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
