### ISSUE TITLE
HELP clanfd's auto format contradict with my vscode indent space settings(4 spaces)

### ISSUE THREAD

**Issue by Ramblestsad** [clangd/clangd#700]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
Output of `clangd --version`:
Editor/LSP plugin:
Operating system:

**Comment by sam-mccall** [comment]
Clangd uses clang-format for formatting, it in configured with a .clang-format file.
https://clang.llvm.org/docs/ClangFormat.html

(LSP does let the editor communicate a few formatting settings to the server, but unfortunately it made them mandatory, so editors send them even if they're incorrect, so we have to ignore them)
