### ISSUE TITLE
Can I disable code-formatting?

### ISSUE THREAD

**Issue by Ramblestsad** [clangd/clangd#702]
I have clangd extension installed in vscode, but I do not want the code-formatting comes with the extension. Is there anyway to disable it?

**Comment by njames93** [comment]
clangd will respect any .clang-format file in your directory tree, you can use that to disable formatting completely if you'd like
```yaml
// .clang-format
DisableFormat: true
```
This will harm refactorings which typically rely on clang format to reformat them.
You can also update your settings to set the default formatter to use another extension or to not format at all.
```json
  "[cpp]":{
    "editor.defaultFormatter": null
  }
```

**Comment by Ramblestsad** [comment]
> clangd will respect any .clang-format file in your directory tree, you can use that to disable formatting completely if you'd like
> 
> ```yaml
> // .clang-format
> DisableFormat: true
> ```
> 
> This will harm refactorings which typically rely on clang format to reformat them.
> You can also update your settings to set the default formatter to use another extension or to not format at all.
> 
> ```json
>   "[cpp]":{
>     "editor.defaultFormatter": null
>   }
> ```

thanks for the reply! Solved my problem. Have a good one!

**Comment by Ramblestsad** [comment]
OH, one more thing forgot to mention.
I am using clangd in my main.c file for autocomplete now, but it seems do not suggest "return", "typedef" and so on.
It seems like not suggesting C keywords.

**Comment by dufferzafar** [comment]
Setting this doesn't actually disable formatting that happens on paste (`Ctrl+V`)

```
  "[cpp]":{
    "editor.defaultFormatter": null
  }
```

**Comment by CatonTheRoRo** [comment]
Setting `DisableFormat: true` at global clangd configuration file `config.yaml` does not do the thing, beside the fact other settings at it work flawlessly.

**Comment by HighCommander4** [comment]
> Setting `DisableFormat: true` at global clangd configuration file `config.yaml` does not do the thing, beside the fact other settings at it work flawlessly.

`DisableFormat: true` is not a clangd setting. It's a clang-format setting that goes in a `.clang-format` config file.

**Comment by CatonTheRoRo** [comment]
> > Setting `DisableFormat: true` at global clangd configuration file `config.yaml` does not do the thing, beside the fact other settings at it work flawlessly.
> 
> `DisableFormat: true` is not a clangd setting. It's a clang-format setting that goes in a `.clang-format` config file.

ok, but can `.clang-format` be global?

**Comment by HighCommander4** [comment]
> can `.clang-format` be global

Looking at the [clang-format docs](https://clang.llvm.org/docs/ClangFormatStyleOptions.html), I don't see a mention of something similar to clangd's "user config file" (e.g. a file that goes in a place like `~/.config` and applies everywhere).

I think the closest to this would be to place a `.clang-format` file fairly high up in the directory tree, for example if you place it at `/home/user/.clang-format`, it will apply to all files in `/home/user` in any subdirectories.

---

With that said, in my opinion, if your intention is to completely disable formatting, it's better to do this at the editor level.
