### ISSUE TITLE
one is deprecated that makes all overloads treated as deprecated?

### ISSUE THREAD

**Issue by RedFog** [clangd/clangd#705]
**example:**
<1>
<img width="815" alt="xxx" src="https://user-images.githubusercontent.com/7519886/109646067-aa726f00-7b92-11eb-9e0c-f7e751ce36bf.png">
<img width="838" alt="xxx2" src="https://user-images.githubusercontent.com/7519886/109647259-08538680-7b94-11eb-9fa8-c97038075bb7.png">
It makes me think that all overloads are deprecated.

not only in the member functions, it also occurs in *qualified name lookup*:
<2>
<img width="812" alt="xxx3" src="https://user-images.githubusercontent.com/7519886/109647361-291bdc00-7b94-11eb-8972-083712cd5439.png">
<img width="837" alt="xxx4" src="https://user-images.githubusercontent.com/7519886/109647511-54063000-7b94-11eb-8e1a-a6e6fdebae31.png">

but compared with these, it looks normal in this situation:
<3>
<img width="813" alt="xxx5" src="https://user-images.githubusercontent.com/7519886/109647640-80ba4780-7b94-11eb-89f9-39672f9b8266.png">

**proposed:**
solution like what <3> does is acceptable. but furthermore, is it possible to classify them into deprecated ones and others?
it will look like: (assume `foo2` to be `foo`)
<img width="821" alt="yyy" src="https://user-images.githubusercontent.com/7519886/109649189-8749be80-7b96-11eb-9c33-0d447898b98a.png">

**System information**
**clangd 11.0.0
VSCode 1.53.2
macOS Catalina 10.15.7**

**Comment by sam-mccall** [comment]
Current behavior is essentially arbitrary: when we build an overload bundle, properties are initially taken from the arbitrary "first" candidate and then updated as we see more candidates. But we never update the deprecated state, so we just return whether the first candidate was deprecated.

Marking it deprecated only if *all* candidates in the bundle are deprecated (like your <3>) seems reasonable and is easy.

I don't think deprecation is common or important enough to justify the complexity of splitting the bundle on it, though. (It is possible, by modifying CompletionCandidate::overloadSet() in CodeComplete.cpp, but complicated splitting logic can be surprising).
