### ISSUE TITLE
pragma unroll directive causes clangd to crash

### ISSUE THREAD

**Issue by BenByington** [clangd/clangd#712]
> Please describe the problem.
> For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html
> 

Clangd appears to crash when indexing a file with #pragma unroll statements.  In my limited testing a #pragma unroll without an argument appears to be fine, but when given a numeric argument it aborts with a segmentation fault.

> If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

The following minimal function reproduces the behaviour on my end:
void Foo()
{
    #pragma unroll 1
    for (int i = 1; i < 10; ++i) {}
}

> **Logs**
> Please attach the clangd stderr log if you can. (Usually available from the editor)
> If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
> If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

If the snippet above is placed as the sole contents of a file `clangd_crash.cpp` then the output of a manual clangd --check run is as follows:
[bbyington@localhost ~]$ clangd --check=clangd_crash.cpp --log=verbose
I[14:16:39.485] clangd version 12.0.0 (https://github.com/llvm/llvm-project.git 67d6fbe0f157ba78e8131964d60155dc1090f409)
I[14:16:39.485] PID: 6705
I[14:16:39.485] Working directory: /home/UNIXHOME/bbyington
I[14:16:39.485] argv[0]: clangd
I[14:16:39.485] argv[1]: --check=clangd_crash.cpp
I[14:16:39.485] argv[2]: --log=verbose
V[14:16:39.485] User config file is /home/UNIXHOME/bbyington/.config/clangd/config.yaml
I[14:16:39.485] Entering check mode (no LSP server)
I[14:16:39.485] Testing on source file /home/UNIXHOME/bbyington/clangd_crash.cpp
I[14:16:39.485] Loading compilation database...
I[14:16:39.486] Failed to find compilation database for /home/UNIXHOME/bbyington/clangd_crash.cpp
I[14:16:39.486] Generic fallback command is: /home/UNIXHOME/bbyington/llvm-install-12/bin/clang /home/UNIXHOME/bbyington/clangd_crash.cpp -fsyntax-only -resource-dir=/home/UNIXHOME/bbyington/llvm-install-12/lib/clang/12.0.0
I[14:16:39.487] Parsing command...
I[14:16:39.490] internal (cc1) args are: -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -main-file-name clangd_crash.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/UNIXHOME/bbyington/llvm-install-12/lib/clang/12.0.0 -internal-isystem /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8 -internal-isystem /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/x86_64-redhat-linux -internal-isystem /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/backward -internal-isystem /usr/local/include -internal-isystem /home/UNIXHOME/bbyington/llvm-install-12/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/UNIXHOME/bbyington -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -x c++ /home/UNIXHOME/bbyington/clangd_crash.cpp
I[14:16:39.490] Building preamble...
I[14:16:39.497] Indexing headers...
V[14:16:39.498] indexed preamble AST for /home/UNIXHOME/bbyington/clangd_crash.cpp version null:
  symbol slab: 0 symbols, 120 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 0 relations, 24 bytes
V[14:16:39.498] Built preamble of size 208384 for file /home/UNIXHOME/bbyington/clangd_crash.cpp version null
I[14:16:39.498] Building AST...
ok Token(`void`, void, length = 4)
ok Token(`Foo`, identifier, length = 3)
ok Token(`(`, l_paren, length = 1)
ok Token(`)`, r_paren, length = 1)
ok Token(`{`, l_brace, length = 1)
ok Token(`1`, numeric_constant, length = 1)
!! Token(``, eof, length = 0)
   Token(`for`, for, length = 3)
   Token(`(`, l_paren, length = 1)
   Token(`int`, int, length = 3)
   Token(`i`, identifier, length = 1)
Couldn't map expanded token to spelled tokens!
UNREACHABLE executed at /home/UNIXHOME/bbyington/llvm-project/clang/lib/Tooling/Syntax/Tokens.cpp:786!
 #0 0x00000000005be68e llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x5be68e)
 #1 0x00000000005bc6f5 llvm::sys::RunSignalHandlers() (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x5bc6f5)
 #2 0x00000000005bc83d SignalHandler(int) (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x5bc83d)
 #3 0x00007f3db559e630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00007f3db418c387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f3db418da78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x0000000000580dca (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x580dca)
 #7 0x0000000000a8dcec clang::syntax::TokenCollector::Builder::diagnoseAdvanceFailure() (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0xa8dcec)
 #8 0x0000000000a93dee clang::syntax::TokenCollector::Builder::build() && (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0xa93dee)
 #9 0x0000000000a9411d clang::syntax::TokenCollector::consume() && (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0xa9411d)
#10 0x0000000000c00ce9 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0xc00ce9)
#11 0x0000000000566a9a clang::clangd::check(llvm::StringRef, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&) (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x566a9a)
#12 0x0000000000480c57 main (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x480c57)
#13 0x00007f3db4178555 __libc_start_main (/lib64/libc.so.6+0x22555)
#14 0x0000000000493325 _start (/home/UNIXHOME/bbyington/llvm-install-12/bin/clangd+0x493325)
Aborted (core dumped)

**System information**
Output of `clangd --version`: clangd version 12.0.0 (https://github.com/llvm/llvm-project.git 67d6fbe0f157ba78e8131964d60155dc1090f409)
Editor/LSP plugin: emacs + lsp-mode (but the above reproduction is using clangd directly with the --check option)
Operating system: Centos 7, with a custom built llvm installed

**Comment by sam-mccall** [comment]
BTW, thanks for the really helpful report! We had some vague awareness that pragmas were crashy, but this helped a lot!

**Comment by BenByington** [comment]
Glad to be of help.  I've also cherry-picked the new fix into my personal build, and the project I distilled my reproducing case from seems to parse nicely now.  So thanks for the speedy fix!
