### ISSUE TITLE
Search + replace (:substitute) text with nvim-lsp causes clangd to respond to most requests with error -32602, until file is re-loaded

### ISSUE THREAD

**Issue by danngreen** [clangd/clangd#717]
**Please describe the problem.**

In neovim (nightly v0.5) when editing a document with clangd 12.0.0rc2 or 11.1.0 as the lsp server, everything works wonderfully... Until you do a search and replace (in vim/nvim, this is the `:s/xxx/yyy/` command). After doing that, clangd responds with errors (often error -36202) to all further lsp requests until the document is re-loaded (in nvim a "reload" is done by `:e`, which re-opens the file and re-attaches it to the lsp server).

If you manually change the same text (without doing a search/replace), there is no error.

Here is a simple project to reproduce this:
```
//main.c
int main() {
	int x = 555;
}
```

```
//Makefile (only needed to generate compile_commands.json)
CC=gcc
all: main.o
	$(CC) -o range_bug main.o
```

```
//compile_commands.json
//generated by `compiledb make`
[
 {
  "directory": "/Users/myusername/src/clangd_nvimlsp_range_bug",
  "arguments": [
   "gcc",
   "-c",
   "-o",
   "main.o",
   "main.c"
  ],
  "file": "main.c"
 }
]
```

```
//nvim-lsp-setup.lua
--[snip]--

require'lspconfig'.clangd.setup {
	cmd = {
		"/Users/myusername/bin/clangd_12.0.0-rc2/bin/clangd",
		"--background-index",
		"--log=verbose",
		"-j=32",
		"--cross-file-rename",
		"--completion-style=bundled",
		"--query-driver=/usr/bin/g*",
		"--pch-storage=memory",
		"--enable-config"
	},
	filetypes = {"c", "cpp", "objc", "objcpp"},
	root_dir = nvim_lsp.util.root_pattern(".clangd", "compile_commands.json" ),
	on_attach = on_attach_vim,
	capabilities = { textDocument = { completion = { completionItem = { snippetSupport = false } } } },
	flags = {allow_incremental_sync = true},
	init_options = { clangdFileStatus = false }
};

--[snip]--
```
To reproduce the error:

1. Open main.c with nvim 0.5 (nightly). Verify lsp is working by, for example, typing garbage text and seeing diagnostics display.
2. Move the cursor to line 2
3. Issue the command `:s/5/4/g` (this says to replace every 5 with a 4 on the current line)
4. Verify lsp is not working by typing garbage text and not seeing any diagnostics display. 
5. Open the lsp log and verify clangd is responding with error -32602 "trying to get AST for non-added document" and other errors in response to all lsp requests for this file.

I don't know if it's a problem with nvim-lsp or clangd or some difference in communication between the two. If anyone knows  how to determine that, I would appreciate knowing!

**Logs**
clangd log from the above steps is attached here:

[lsp.log](https://github.com/clangd/clangd/files/6104221/lsp.log)

Noteworthy log entries:

Line 20) This is where the error happens:
```
[ ERROR ] 2021-03-08T12:20:07-0800 ] ...latest/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"/Users/dann/bin/clangd_12.0.0-rc2/bin/clangd"	"stderr"	"V[12:20:07.554] <<<
{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didChange\",\"params\":{\"contentChanges\":[{\"range\":{\"end\":{\"character\":0,\"line\":2},\"start\":{\"character\":0,\"line\":1}},\"rangeLength\":28,\"text\":\"\\tint x = 444;\
\"}],\"textDocument\":{\"uri\":\"file:///Users/design/src/clangd_nvimlsp_range_bug/main.c\",\"version\":4}}}
I[12:20:07.554]
<-- textDocument/didChange
E[12:20:07.554] Failed to update /Users/design/src/clangd_nvimlsp_range_bug/main.c: Change's rangeLength (28) doesn't match the computed range length (14).
"
```
The bit about `Change's rangeLength (28) doesn't match the computed range length (14)` makes me think of a utf-8 vs utf-16 error. I've played with (attempted to?) setup nvim-lsp to only use one or the other, but it seems to have no effect or mangles the LSP requests and the client and server don't communicate. This still feels like a clue, though...

In this case the two numbers in this error are 28 and 14, but they're not always exactly a 2:1 ratio, but they are always close. Other search/replaces in other files generated these errors:
`Change's rangeLength (13) doesn't match the computed range length (7)`
`Change's rangeLength (983) doesn't match the computed range length (494)`
`Change's rangeLength (200) doesn't match the computed range length (98)`
`Change's rangeLength (184) doesn't match the computed range length (90)`

Regardless, after this error, nothing works.
Line 21 and many after) All textDocument/documentHighlight LSP requests are responded with `error: -32602: trying to get AST for non-added document`
Lines 23-24) A textdocument/didChange is responded with `Trying to remove file from TUScheduler that is not tracked: /Users/myusername/src/clangd_nvimlsp_range_bug/main.c`
followed by a `Failed to update /Users/myusername/src/clangd_nvimlsp_range_bug/main.c: Trying to do incremental update on non-added document: /Users/myusername/src/clangd_nvimlsp_range_bug/main.c`

**System information**
Output of `clangd --version`:
`clangd version 12.0.0 (https://github.com/llvm/llvm-project 4918a3d138b907a571f496661b5367e090e1e8bb)`

Same behavior with clangd 11.1.0 (installed with brew):
`clang version 11.1.0
Target: x86_64-apple-darwin20.3.0
`

Editor/LSP plugin:
NVIM v0.5.0-dev+1116-gbda12927b
Same issue with earlier nightly versions as far back as I've tested.

Operating system:
macOS Big Sur 11.2.2
Same issue with macOS Catalina 10.15.7 and clangd 11.0.0 (installed with brew)

**Comment by danngreen** [comment]
Aha! The process of writing this issue led me to try something else.
Removing `flags = {allow_incremental_sync = true}`
from the nvim settings makes nvim send the correct rangeLength parameter value. Then, there are no errors.

So, it seems the issue is with nvim sending an incorrect rangeLength value.

It also seems that rangeLength is a deprecated parameter in the lsp specs:
https://github.com/microsoft/language-server-protocol/issues/9

Perhaps a useful improvement to clangd would be to have it continue working even if it notices the rangeLength parameter doesn't match (range.end - range.start)?

In any case, I'll shift my focus to neovim.

**Comment by kadircet** [comment]
> So, it seems the issue is with nvim sending an incorrect rangeLength value.

I agree with the verdict here, by looking at the logs.

> Perhaps a useful improvement to clangd would be to have it continue working even if it notices the rangeLength parameter doesn't match (range.end - range.start)?

It might also mean we are drifting away from actual contents of the buffer though, which will result in all the features breaking, you'll hover on one symbol and get info about another, there will be numerous false diagnostics, even code completion won't have any useful results. So we chose to just error out, rather than showing wrong information and burning resources. As the only thing for user to do in such a scenario is either restart clangd or re-add the document (if their editor allows them to do so).

> In any case, I'll shift my focus to neovim.

Thanks! Please mention the new issue around here so we can also keep a tab on it.

(closing this one, as I don't think there's any action items for us to take on clangd side)

**Comment by danngreen** [comment]
Thanks. Just to update: this PR for neovim fixes the issue:
https://github.com/neovim/neovim/pull/14079
