### ISSUE TITLE
help me! about semantic highlighting

### ISSUE THREAD

**Issue by Ava-alt** [clangd/clangd#718]
Please describe the problem.
There seems to be a problem about semantic highlighting。 Hope to give some guidance

![image](https://user-images.githubusercontent.com/79972211/110438932-d1302880-80f1-11eb-928d-cd9a1f34049a.png)
![image](https://user-images.githubusercontent.com/79972211/110439486-7ea33c00-80f2-11eb-8082-e81c4e805a6b.png)

**Logs**
I[15:14:38.397] clangd version 12.0.0 (https://github.com/llvm/llvm-project 4918a3d138b907a571f496661b5367e090e1e8bb)
I[15:14:38.397] PID: 2033
I[15:14:38.397] Working directory: /data/code/test11/test
I[15:14:38.397] argv[0]: /usr/local/bin/clangd
I[15:14:38.397] Starting LSP over stdin/stdout
I[15:14:38.397] <-- initialize(0)
I[15:14:38.398] --> reply:initialize(0) 0 ms
I[15:14:38.398] <-- initialized
I[15:14:38.399] <-- textDocument/didOpen
I[15:14:38.399] <-- textDocument/didOpen
I[15:14:38.399] <-- textDocument/didOpen
I[15:14:38.400] --> textDocument/clangd.fileStatus
I[15:14:38.400] Loaded compilation database from /data/code/test11/test/.theia/compile_commands.json
I[15:14:38.400] ASTWorker building file /data/code/test11/test/exam/main.cpp version 1 with command 
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -std=gnu++14 -o CMakeFiles/exam.dir/main.cpp.o -c /data/code/test11/test/exam/main.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:14:38.400] ASTWorker building file /data/code/test11/test/exam/test.cpp version 1 with command inferred from /data/code/test11/test/exam/main.cpp
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -c -std=gnu++14 /data/code/test11/test/exam/test.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:14:38.402] Enqueueing 1 commands for indexing
I[15:14:38.403] --> textDocument/clangd.fileStatus
I[15:14:38.404] --> textDocument/clangd.fileStatus
I[15:14:38.449] <-- textDocument/codeAction(1)
I[15:14:38.449] <-- textDocument/codeAction(2)
I[15:14:38.449] <-- textDocument/codeAction(3)
I[15:14:38.449] <-- textDocument/documentLink(4)
I[15:14:38.449] <-- textDocument/documentLink(5)
I[15:14:38.449] <-- textDocument/documentLink(6)
I[15:14:38.767] --> textDocument/publishDiagnostics
I[15:14:38.767] ASTWorker building file /data/code/test11/test/exam/hello.cpp version 1 with command inferred from /data/code/test11/test/exam/main.cpp
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -c -std=gnu++14 /data/code/test11/test/exam/hello.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:14:38.768] --> textDocument/clangd.fileStatus
I[15:14:38.769] --> textDocument/clangd.fileStatus
I[15:14:39.035] --> textDocument/publishDiagnostics
I[15:14:39.035] --> reply:textDocument/codeAction(1) 586 ms
I[15:14:39.036] --> reply:textDocument/documentLink(4) 586 ms
I[15:14:39.036] --> textDocument/clangd.fileStatus
I[15:14:39.036] --> reply:textDocument/codeAction(3) 586 ms
I[15:14:39.037] --> reply:textDocument/documentLink(6) 587 ms
I[15:14:39.037] --> textDocument/clangd.fileStatus
I[15:14:39.220] Indexed /data/code/test11/test/exam/main.cpp (8158 symbols, 31940 refs, 199 files)
I[15:14:39.373] --> textDocument/publishDiagnostics
I[15:14:39.374] --> reply:textDocument/codeAction(2) 924 ms
I[15:14:39.374] --> reply:textDocument/documentLink(5) 924 ms
I[15:14:39.374] --> textDocument/clangd.fileStatus
I[15:15:28.366] <-- textDocument/hover(7)
I[15:15:28.366] --> reply:textDocument/hover(7) 0 ms
I[15:15:28.366] --> textDocument/clangd.fileStatus
I[15:15:28.782] <-- shutdown(8)
I[15:15:28.782] --> reply:shutdown(8) 0 ms
I[15:15:28.782] <-- exit
I[15:15:28.782] LSP finished, exiting with status 0
I[15:15:28.788] clangd version 12.0.0 (https://github.com/llvm/llvm-project 4918a3d138b907a571f496661b5367e090e1e8bb)
I[15:15:28.789] PID: 2259
I[15:15:28.789] Working directory: /data/code/test11/test
I[15:15:28.789] argv[0]: /usr/local/bin/clangd
I[15:15:28.789] Starting LSP over stdin/stdout
I[15:15:28.789] <-- initialize(0)
I[15:15:28.789] --> reply:initialize(0) 0 ms
I[15:15:28.790] <-- initialized
I[15:15:28.790] <-- textDocument/didOpen
I[15:15:28.790] <-- textDocument/didOpen
I[15:15:28.790] <-- textDocument/didOpen
I[15:15:28.792] --> textDocument/clangd.fileStatus
I[15:15:28.792] Loaded compilation database from /data/code/test11/test/.theia/compile_commands.json
I[15:15:28.792] Enqueueing 1 commands for indexing
I[15:15:28.793] ASTWorker building file /data/code/test11/test/exam/hello.cpp version 1 with command inferred from /data/code/test11/test/exam/main.cpp
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -c -std=gnu++14 /data/code/test11/test/exam/hello.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:15:28.793] ASTWorker building file /data/code/test11/test/exam/test.cpp version 1 with command inferred from /data/code/test11/test/exam/main.cpp
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -c -std=gnu++14 /data/code/test11/test/exam/test.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:15:28.794] --> textDocument/clangd.fileStatus
I[15:15:28.794] --> textDocument/clangd.fileStatus
I[15:15:28.881] <-- textDocument/codeAction(1)
I[15:15:28.881] <-- textDocument/codeAction(2)
I[15:15:28.881] <-- textDocument/codeAction(3)
I[15:15:28.881] <-- textDocument/documentLink(4)
I[15:15:28.881] <-- textDocument/documentLink(5)
I[15:15:28.881] <-- textDocument/documentLink(6)
I[15:15:29.164] --> textDocument/publishDiagnostics
I[15:15:29.164] --> reply:textDocument/codeAction(1) 283 ms
I[15:15:29.164] --> reply:textDocument/documentLink(4) 283 ms
I[15:15:29.164] --> textDocument/clangd.fileStatus
I[15:15:29.164] ASTWorker building file /data/code/test11/test/exam/main.cpp version 1 with command 
[/data/code/test11/test/exam]
/usr/lib/llvm-6.0/bin/c++ --driver-mode=g++ -std=gnu++14 -o CMakeFiles/exam.dir/main.cpp.o -c /data/code/test11/test/exam/main.cpp -fsyntax-only -resource-dir=/usr/local/lib/clang/12.0.0
I[15:15:29.165] --> textDocument/clangd.fileStatus
I[15:15:29.404] --> textDocument/publishDiagnostics
I[15:15:29.405] --> reply:textDocument/codeAction(2) 523 ms
I[15:15:29.405] --> reply:textDocument/documentLink(5) 523 ms
I[15:15:29.405] --> textDocument/clangd.fileStatus
I[15:15:29.759] --> textDocument/publishDiagnostics
I[15:15:29.759] --> reply:textDocument/codeAction(3) 878 ms
I[15:15:29.759] --> reply:textDocument/documentLink(6) 878 ms
I[15:15:29.759] --> textDocument/clangd.fileStatus
I[15:20:32.347] <-- $/setTraceNotification
I[15:20:32.347] unhandled notification $/setTraceNotification
I[15:20:42.673] <-- $/setTraceNotification
I[15:20:42.674] unhandled notification $/setTraceNotification
I[15:21:32.168] <-- $/setTraceNotification
I[15:21:32.168] unhandled notification $/setTraceNotification
I[15:30:01.230] <-- $/setTraceNotification
I[15:30:01.230] unhandled notification $/setTraceNotification
I[15:30:17.454] <-- $/setTraceNotification
I[15:30:17.454] unhandled notification $/setTraceNotification
I[16:05:32.226] <-- textDocument/hover(7)
I[16:05:32.227] --> reply:textDocument/hover(7) 0 ms
I[16:05:32.227] --> textDocument/clangd.fileStatus
I[16:05:32.521] <-- shutdown(8)
I[16:05:32.521] --> reply:shutdown(8) 0 ms
I[16:05:32.522] <-- exit
I[16:05:32.522] LSP finished, exiting with status 0

**System information**
Output of `clangd --version`:
clangd version 12.0.0
Editor/LSP plugin:

Operating system:
The environment is ubuntu（Linux version 4.15.0-117-generic (buildd@lcy01-amd64-008) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #118-Ubuntu）

**Comment by sam-mccall** [comment]
There's not enough information here to understand what the problem is, or what the editor is. From the logs it appears semantic highlighting is not enabled (either with the old or the new protocol).

I'm afraid this is not a support channel - if you can narrow down the problem to a bug in clangd, please do.

**Comment by kirillbobyrev** [comment]
(also, make sure you have this in your `settings.json`)
```json
  "editor.semanticHighlighting.enabled": true,
  "clangd.semanticHighlighting": true,
```
