### ISSUE TITLE
Clang-tidy not consistent when reporting the linter checks option

### ISSUE THREAD

**Issue by lmcbout** [clangd/clangd#72]
When using clangd with the linter (clang-tidy), selecting the "Show Fixes", (Click on the light bulb), clangd return  the "title"  with the "checks" value and sometimes without. To be consistent, I think it should be there all the times. 
It would show where the "checks"  value are from, so as an example, 
for the "readability-uppercase-literal-suffix" and "hicpp-uppercase-literal-suffix" when both are reported, we should be able to distinguish the reference. 
When clangd reports "use a trailing return type for this function [modernize-use-trailing-return-type]",
 we know from which linter criteria it comes from.

see without the linter code reference:
![LinterInfoNotAvailable](https://user-images.githubusercontent.com/419051/60292488-370f5900-98eb-11e9-91b0-32981910332d.png)

With linter code information:
![LinterCodeAvailable](https://user-images.githubusercontent.com/419051/60292497-41c9ee00-98eb-11e9-851b-3a588b892f92.png)

**Comment by hokein** [comment]
clangd uses a heuristic to synthesize this message (e.g. Change 'X' to 'Y', Insert 'XX') from the source change, but it only works for simple cases (the fix contains a single modification of the code);

The heuristic fails on the `modernize-use-trailing-return-type` case because the fix contains 2 modifications of the code, then we fall back to use the clang-tidy diagnostic message. But having a trailing check name in the message seems a bug to me (I remember we stripped the ' [some-check-name]' suffix from the clang-tidy message).

**Comment by lmcbout** [comment]
When you look for the first case, it looks like duplication because the display of the heuristics is not visible.
Duplication has been fix by issue #60 .
If more than one heuristic has the same comment, should we only show one solution to fix it !
If I run clang-tidy  from the command line , not from clangd,  only one solution is returned.

**Comment by HighCommander4** [comment]
It sounds like the underlying issue is that the fixits were being duplicated in the first place, and that was fixed in #75, making the issue of whether or not the fixit message includes the check name moot. @lmcbout can you confirm that this is the case?

**Comment by lmcbout** [comment]
I did not test issue #75 with the latest fix. Issue #75 was for multiple duplication when using a color structure. I don't know if they remove the duplication of "Fixes it " that comes from different rules!
If it removes it, then this issue becomes obsolete, otherwise, having the linter rules name might still apply,
what do you think !

**Comment by hokein** [comment]
>  I don't know if they remove the duplication of "Fixes it " that comes from different rules!

Yes, the fix for #75 also removes the duplication from clang-tidy alias checks, so for your above case `"readability-uppercase-literal-suffix" and "hicpp-uppercase-literal-suffix"`, only one diagnostic message (and one `Fixes it`) will be shown in vscode.
