### ISSUE TITLE
"Could not build CompilerInvocation" cause and workaround on VSCode on Windows

### ISSUE THREAD

**Issue by johnwbyrd** [clangd/clangd#721]
I'm entering this as a bug report, though it's mostly a breadcrumb for future users of the clangd plugin on Windows using Visual Studio Code.

If you've configured your project to build with compiler_commands.json, and the compiler in question is not _exactly_ clang.exe, then you will get "Could not build CompilerInvocation cause" warning messages, and clangd will refuse to index the files in your project.

This can easily occur if you are using clang's MSVC compatibility compiler, which is clang-cl.exe, for building your project.  The CMake support in VS Code makes it easy to stumble into a configuration where you're compiling with some other binary than clang.

clangd should probably log a warning if it detects that the compiler being called in the compilation step, is named anything other than "clang" or "clang.exe".  It should expressly warn _against_ compiling with clang-cl.

**Comment by sam-mccall** [comment]
This is actually supposed to work: we should be able to parse clang-cl command lines.
It's certainly not as well-tested as the gcc-style command lines though.

Would you be able to provide the compile command and error message from the logs?

**Comment by kadircet** [comment]
We've improved these cases quite recently, can you try with a new clangd, preferably from https://github.com/clangd/clangd/releases/tag/snapshot_20210829 ?

**Comment by elevir** [comment]
@kadircet it seems to be working 😎

**Comment by kadircet** [comment]
Glad to hear that! @johnwbyrd I am closing this as there hasn't been any follow-ups from your side and we performed some improvements. Feel free to re-open with more information if the issue persists with newer versions of clangd.
