### ISSUE TITLE
[Bug] Renaming a symbol with multi-file appearence causes the new name to be invalid.

### ISSUE THREAD

**Issue by ItsCubeTime** [clangd/clangd#728]
https://user-images.githubusercontent.com/20190653/113029338-98352200-918c-11eb-97c5-4b42058a8456.mp4

Demonstrated in the video. Happens when renaming seemingly all symbol types

**System information**
Output of `0.1.11`:
Editor/LSP plugin:VS Code
Operating system: Win10

**Comment by ItsCubeTime** [comment]
Actually I just realized this might be due to that I also have C/C++ by Microsoft enabled. I will likely close this task if that turns out to be the case.

**Comment by sam-mccall** [comment]
I believe this is the issue fixed by https://github.com/llvm/llvm-project/commit/b63cd4db915c08e0cb4cf668a18de24b67f2c44c which will be in clangd 12.

(I assume you're not using a clangd 12 RC, but the version number you've included in the bug report appears to be a vscode-clangd version number rather than clangd itself)

**Comment by sam-mccall** [comment]
This fix is part of clangd, not vscode-clangd, so it's not distributed through vscode marketplace.

12 isn't released yet, but you can try 12rc2: https://github.com/clangd/clangd/releases/tag/12.0.0-rc2

**Comment by ItsCubeTime** [comment]
> This fix is part of clangd, not vscode-clangd, so it's not distributed through vscode marketplace.
> 
> 12 isn't released yet, but you can try 12rc2: https://github.com/clangd/clangd/releases/tag/12.0.0-rc2

Hi, yes thanks :) I just found my way over there and tried it. Works like a charm.

Theres a "limitation" or issue with the vs code extension however that it doesnt quite seem to let you change the path to the clangd.exe it uses. I will be opening a feature request for this in clangd/vscode-clangd/issues
