### ISSUE TITLE
Code action to add a using declaration

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#73]
Before:

```
void foo() {
  int x = bar::baz();
  //           ^^^
}
```

After:

```
using bar::baz;

void foo() {
  int x = baz();
}
```

Some questions about
 - what scope to add the using decl in (TU scope? Namespace scope?)
 - try to group with other using decls?
 - detect shadowing cases?

**Comment by kadircet** [comment]
we've got that code action now. thanks to adamcz@
