### ISSUE TITLE
Modules with clangd configuration

### ISSUE THREAD

**Issue by login224444** [clangd/clangd#733]
```
    //name.cpp
    export module name;
    import <string>;
    export std::string name() {
      return "User";
    }

    // main.cpp
    import <iostream>;
    import name;
    int main() {
      std::cout << name();
    }
```
```
    clang++-12 -Wall -std=c++20 -stdlib=libc++ -fmodules -c name.cpp -Xclang -emit-module-interface -o name.pcm  
    clang++-12 -Wall -std=c++20 -stdlib=libc++ -fmodules -fprebuilt-module-path=. name.cpp main.cpp
```

I know these commands below are wrong, because needed different compilation for each file. How to make clangd aware of it, some general approach for different names exists? And .. any advice how to enable import module autocmplete? Because "--header-insertion=never" is not good.
```
    //compile_flags.txt
    -std=c++20
    -fmodules
    -stdlib=libc++
    -fprebuilt-module-path=.
```
![Screenshot_2021-04-06_01-05-59](https://user-images.githubusercontent.com/74967516/113630863-a4801a00-9679-11eb-8607-b046a93ab791.png)

**Comment by kadircet** [comment]
> How to make clangd aware of it, some general approach for different names exists

you can make use of compile_commands.json instead, which supports declaring compile flags per file.

> any advice how to enable import module autocmplete?

unfortunately that's not supported yet

**Comment by login224444** [comment]
> > How to make clangd aware of it, some general approach for different names exists
> 
> you can make use of compile_commands.json instead, which supports declaring compile flags per file.
> 
> > any advice how to enable import module autocmplete?
> 
> unfortunately that's not supported yet

Thanks for answering! I've made as you told.

```
// Makefile
all: first second
first:
	/usr/bin/clang++12 -Wall -std=c++20 -stdlib=libc++ -fmodules -c name.cpp -Xclang -emit-module-interface -o modules/name.pcm
second:
	/usr/bin/clang++12 -Wall -std=c++20 -stdlib=libc++ -fmodules -fprebuilt-module-path=./modules name.cpp main.cpp
```
bear make

```
// compile_commands.json
[
    {
        "arguments": [
            "/usr/bin/clang++",
            "-c",
            "-Wall",
            "-std=c++20",
            "-stdlib=libc++",
            "-fmodules",
            "-Xclang",
            "-emit-module-interface",
            "-o",
            "modules/name.pcm",
            "name.cpp"
        ],
        "directory": "/home/user/Cpp/Build",
        "file": "name.cpp"
    },
    {
        "arguments": [
            "/usr/bin/clang++",
            "-c",
            "-Wall",
            "-std=c++20",
            "-stdlib=libc++",
            "-fmodules",
            "-fprebuilt-module-path=./modules",
            "name.cpp"
        ],
        "directory": "/home/user/Cpp/Build",
        "file": "name.cpp"
    },
    {
        "arguments": [
            "/usr/bin/clang++",
            "-c",
            "-Wall",
            "-std=c++20",
            "-stdlib=libc++",
            "-fmodules",
            "-fprebuilt-module-path=./modules",
            "main.cpp"
        ],
        "directory": "/home/user/Cpp/Build",
        "file": "main.cpp"
    }
]
```
But two problems remain, if remove .cache/clang and open editor for checking file:
![Screenshot_2021-04-06_15-43-01](https://user-images.githubusercontent.com/74967516/113705710-cebfef00-96ee-11eb-8342-c4cb89c5d69d.png)

If build project with make, after it cache conflict:
![Screenshot_2021-04-06_15-44-13](https://user-images.githubusercontent.com/74967516/113705832-f616bc00-96ee-11eb-8d62-207371e5e6f4.png)
