### ISSUE TITLE
Confusion on the `Configuration` page

### ISSUE THREAD

**Issue by siegel** [clangd/clangd#735]
On the [clangd configuration page](https://clangd.llvm.org/config.html), in the `Files` section, the first bullet point reads:

```
project configuration: a file named .clangd in the source tree. (clangd searches in all parent directories of the active file).

Generally this should be used for shared and checked-in settings.
```

However, `.clangd` appears to be a directory, not a file.

Should `config.yaml` be placed in `.clangd/`? If not, where should it be for project-specific configuration?

**System information**
Output of `clangd --version`: n/a
Editor/LSP plugin: n/a
Operating system: n/a

**Comment by HighCommander4** [comment]
> Output of `clangd --version`: n/a

The answer to this is relevant to this question. The config mechanism was introduced in clangd 11.

**Comment by siegel** [comment]
> The answer to this is relevant to this question. The config mechanism was introduced in clangd 11.

If you insist. :-)

`xcrun clangd --version` reports: `Apple clangd version 12.0.0 (clang-1200.0.32.27)`

`/usr/local/opt/llvm/bin/clangd --version` (the version installed by `brew install llvm`) reports: `clangd version 11.1.0`

**Comment by kirillbobyrev** [comment]
> However, .clangd appears to be a directory, not a file.

`.clangd` used to be where we store temporary files pre clangd-11. Since clangd-11, we decided to use `.clangd` name for the *configuration file*, as mentioned in the Configuration docs.

You are right - this is quite unfortunate because it confuses users, we should probably have documentation for that.

We are no longer making use of `.clangd` directory - you can safely delete it and use `.clangd` name for the configuration file.

**Comment by siegel** [comment]
@kirillbobyrev great -- I appreciate the clarification. I'm assuming that clangd 11 either ignores a `.clangd` directory or uses it with its contents, but in either case it helps greatly to know which end is up. :-)

**Comment by kirillbobyrev** [comment]
@siegel no problem! Thanks for bringing it up, I thought we had a mention of this somewhere but I don't see it, so this is potentially confusing to more people - hence the update in documentation will certainly be helpful.
