### ISSUE TITLE
Misleading error message "Failed to find compilation database for " caused by syntax errors in compile_commands.json

### ISSUE THREAD

**Issue by bgoodr** [clangd/clangd#739]
Below is the output (obfuscated) of the result of viewing a file ("aaa_interface.C") in my text editor. This output is run through `cat -n` to I can refer to line numbers.

```
     1	I[16:52:04.560] clangd version 11.0.0
     2	I[16:52:04.560] PID: 189988
     3	I[16:52:04.560] Working directory: /the/git/worktree/root_dir
     4	I[16:52:04.560] argv[0]: /the/path/to/the/clang-11/head_directory/bin/clangd
     5	I[16:52:04.560] argv[1]: --header-insertion-decorators=0
     6	I[16:52:04.560] Starting LSP over stdin/stdout
     7	I[16:52:04.566] <-- initialize(1)
     8	I[16:52:04.567] --> reply:initialize(1) 0 ms
     9	I[16:52:04.959] <-- initialized
    10	I[16:52:04.967] <-- textDocument/didOpen
    11	I[16:52:05.025] Failed to find compilation database for /the/git/worktree/root_dir/dir1/dir2/dir3/dir4/dir5/dir6/aaa_interface.C
    12	I[16:52:05.025] ASTWorker building file /the/git/worktree/root_dir/dir1/dir2/dir3/dir4/dir5/dir6/aaa_interface.C version 0 with command clangd fallback
    13	[/the/git/worktree/root_dir/dir1/dir2/dir3/dir4/dir5/dir6]
    14	/usr/bin/clang /the/git/worktree/root_dir/dir1/dir2/dir3/dir4/dir5/dir6/aaa_interface.C -fsyntax-only -resource-dir=/path/to/clang/head/dir/lib/clang/11.0.0
```

Notice one line 3 that clangd is detecting the "Working directory". Notice on line 11 it says it "Failed to find compilation database for". But the compilation database file does exist at /the/git/worktree/root_dir/compile_commands.json.

The compile_commands.json file is definitely found, but it has a syntax error. And, that results in the "Failed to find compilation database for" error. So, the error message on line 11 is misleading. 

You can reproduce this by adding a syntax error to an existing compile_commands.json file. Here, I'm adding additional backslashes which foul up the parsing:

```
{
  "directory": "path/to/some/directory",
  "command": "/path/to/bin/clang++ -DSOME_MACRO=\\\\"value\\\\" -c aaa_interface.C -o aaa_interface.o",
  "file": "path/to/some/source/directory/aaa_interface.C"
},
```

The expectation here is that the error message be specific to what the cause, not be a "catch-all" error message for both inability to find files and syntax errors in those files.

**System information**
Output of `clangd --version`: clangd version 11.0.0
Editor/LSP plugin: GNU Emacs 27.1/lsp-mode
Operating system: RedHatEnterprise 8.2

**Comment by HighCommander4** [comment]
When I try this locally, immediately before the "Failed to find" message in the log, I see a "Failed to load" message:

```
E[18:22:56.645] Failed to load compilation database from <path>/compile_commands.json: Expected string as value.
I[18:22:56.645] Failed to find compilation database for <path>/test.cpp
```

The error message isn't super-descriptive (for example, it doesn't point to the line of the json file where the error occurred), but it does at least identify that it tried loading a CDB at a particular path and failed.

**Comment by HighCommander4** [comment]
It looks like the "failed to load" error is new in clangd 12 (added in [this patch](https://reviews.llvm.org/D92663)).

So, this was indeed an issue in clangd 11 but has been fixed in clangd 12.

**Comment by bgoodr** [comment]
Closing the issue given the comment from @HighCommander4 
Thanks to the both of you. I will just wait until I can move to clangd 12.
