### ISSUE TITLE
[Feature Request] Display document when hovering

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#74]
### Display document when hovering.

![image](https://user-images.githubusercontent.com/10697249/60517232-e1cfaf00-9d11-11e9-9f30-6e0b2d3c2320.png)
**Expected**
![image](https://user-images.githubusercontent.com/10697249/60517363-278c7780-9d12-11e9-85b5-d71e698236dd.png)

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D64296

We actually have this field in the struct, it's just not output (pending a revamp on hover rendering I think, but we should add this in a simple way before the llvm9 branch)

We also need to query the index, as for symbols outside the main file we can't get the comment from the AST.

**Comment by sam-mccall** [comment]
r365522

**Comment by sam-mccall** [comment]
The rendering might not be ideal, I'd really like to revisit hover rendering at some point. But I wanted a simple version of this to make the llvm-9 release cut.

If you can try it out in the next few days, there's still time to make minor changes.

**Comment by lh123** [comment]
Thanks for the quick fix.
![image](https://user-images.githubusercontent.com/10697249/60969256-b3755380-a351-11e9-9219-e5e6da193ce8.png)
 **But the document cannot be displayed when hovering over the macro.**

Hover on macro.
![image](https://user-images.githubusercontent.com/10697249/60969339-e0c20180-a351-11e9-8d6a-56ec6ab63e32.png)
