### ISSUE TITLE
rename symbol when use clang-tidy fix feature

### ISSUE THREAD

**Issue by findNextStep** [clangd/clangd#741]
for example we have two file in project
test.h
```cpp
void test_func();
```
test.cpp
```cpp
#include <cstdio>
void test_func(){ printf("test\r\n");}
```
and the test_func is `Invalid case style for function` and we click `quick fix` only funcition name in test.h will be change, but it should change both in test.cpp and test.h

**Comment by njames93** [comment]
The current integration of clang-tidy and clangd doesn't really allow for this. The best solution for this would annoyingly involve creating a new version of the check that's based on clangds internal renaming mechanisms. Though it's still not a perfect solution

**Comment by HighCommander4** [comment]
I'm going to forward-dupe this to #1589 which contains more detailed discussion of this issue (and there is work towards resolving it in https://github.com/llvm/llvm-project/pull/78454).
