### ISSUE TITLE
support skip range in #ifdefine case

### ISSUE THREAD

**Issue by findNextStep** [clangd/clangd#742]
when use ccls as lsp in macro it show like below
![image](https://user-images.githubusercontent.com/26270464/114532216-35a94f00-9c7f-11eb-84a4-5844d01d8007.png)
it`s very useful when write code with OS like the webrtc physical socket server, this is how clangd show
![image](https://user-images.githubusercontent.com/26270464/114532568-8a4cca00-9c7f-11eb-885d-da11f19fdf82.png)
and this is how ccls work 
![image](https://user-images.githubusercontent.com/26270464/114532672-9f295d80-9c7f-11eb-9e62-62b670af9783.png)

**Comment by njames93** [comment]
I'm not entirely sure when it was added but that feature exists. Which clangd version(and editor) are you using?
It's a few months old but could you try using the latest rc build - https://github.com/clangd/clangd/releases/tag/12.0.0-rc2 and see if you get expected behaviour.

**Comment by findNextStep** [comment]
yes it work ,but i found that clangd will crash every time when i enable `folding-ranges`

**Comment by findNextStep** [comment]
any way it work fine

**Comment by njames93** [comment]
> yes it work ,but i found that clangd will crash every time when i enable `folding-ranges`

Yes, folding ranges has issues see #310. That's why its not enabled by default for the time being.

**Comment by kirillbobyrev** [comment]
Yes, folding ranges is a separate feature anyway. Unfortunately, it's long before being available because we want to use it as a testing field for the Syntax Trees feature we're currently working on but it got sidetracked a lot and needs a lot of design and effort to be available.
