### ISSUE TITLE
 textDocument/codeAction returns too many fixits when using a color structure 

### ISSUE THREAD

**Issue by lmcbout** [clangd/clangd#75]
refer to issue #60 
Using the following structure in a ".cpp" or a" .h"  files produces 8 times, i.e. 4 "readability-
uppercase-literal-suffix"  and 4 "hicpp-uppercase-literal-suffix" values

Test case: add the following structure in any .cpp or .h file:
```
#include <GLFW/glfw3.h>

typedef struct {
  GLfloat r, g, b, a;
} Color;
const Color blue = {0.13, 0.59, 0.95, 1.0f};
```
 Use the followings checks:  "--clang-tidy-checks=*"
result when clicking on the light bulb : 8 times reporting the following
==> "kind": "quickfix",
        "title": "change 'f' to 'F'"

**Comment by marcdumais-work** [comment]
Hi,

Here's a short animated .gif that shows the problem described above, using [Theia](https://github.com/theia-ide/theia) as client:

![Peek 2019-07-04 09-25](https://user-images.githubusercontent.com/25749063/60670506-daf28a80-9e3e-11e9-8466-7929727e3614.gif)

**Comment by hokein** [comment]
upstream https://reviews.llvm.org/D64127 should fix this.

**Comment by lmcbout** [comment]
Thanks for the quick fix

**Comment by sam-mccall** [comment]
Fixed in r365204
