### ISSUE TITLE
Always showing some unnecessary errors?

### ISSUE THREAD

**Issue by sleeperzjf** [clangd/clangd#751]
Like this:
![image](https://user-images.githubusercontent.com/65698607/115182825-3887c200-a10d-11eb-8a40-df9e92f366da.png)

**Comment by kirillbobyrev** [comment]
Hi! We would need more information to understand what is going on. E.g. logs or the full source file (if it's self-contained). I can't see the rest of the source file but it might be missing some `#include`s from the Standard Library. Can you compile this file without any errors with Clang?

**Comment by kirillbobyrev** [comment]
Not enough information to determine if this is a real bug or a real C++ error. Feel free to reopen the issue with more information if you believe this is a real problem.
