### ISSUE TITLE
Incorrect error with pointer as return type

### ISSUE THREAD

**Issue by NoahHakansson** [clangd/clangd#764]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**
Output of `clangd --version`: ubuntu 11.0.0-2
Editor/LSP plugin: neovim with Coc-clangd
Operating system: pop_os (ubuntu)

I get this error, I dont get this error in vscode using another LSP, but i get it using clangd in neovim.
![image](https://user-images.githubusercontent.com/26793631/116418770-ba2dcd00-a83c-11eb-8c4e-4f696822339a.png)

If i write the code like this clangd doesnt throw an error, but i shouldnt have to write it like this.
![image](https://user-images.githubusercontent.com/26793631/116419466-5fe13c00-a83d-11eb-9a85-9d89cda6a6aa.png)

**Comment by HighCommander4** [comment]
What compiler are you using to build your code? It looks like accepting the first version may be a non-standard extension.

**Comment by NoahHakansson** [comment]
> What compiler are you using to build your code? It looks like accepting the first version may be a non-standard extension.

I use clang++ to compile.

**Comment by HighCommander4** [comment]
I put together a minimal example that matches what's on your screen:

```c++
template <typename T>
struct RBTree {
  struct Node {};

  Node* searchTree(T element, Node* currNode);
};

template <typename T>
Node* RBTree<T>::searchTree(T element, Node* currNode) {
  return nullptr;
}
```

and clang++ (tested with version 12) does indeed reject it.

Perhaps you're using a different version of clang, or with different flags, that accepts this? Or perhaps your code is different in a relevant way (in which case, please post a complete code example that shows the problem).

**Comment by NoahHakansson** [comment]
> I put together a minimal example that matches your screenshot:
> 
> ```c++
> template <typename T>
> struct RBTree {
>   struct Node {};
> 
>   Node* searchTree(T element, Node* currNode);
> };
> 
> template <typename T>
> Node* RBTree<T>::searchTree(T element, Node* currNode) {
>   return nullptr;
> }
> ```
> 
> and clang++ (tested with version 12) does indeed reject it.
> 
> Perhaps you're using a different version of clang, or with different flags, that accepts this? Or perhaps your code is different in a relevant way (in which case, please post a complete code example that shows the problem).

Okay, no you are right compiler does throw an error. Im not sure what i did before that made it compile. Maybe just trying to many different things and not saving properly...

Sorry to waste your time!

**Comment by HighCommander4** [comment]
As a general point of interest, the shorter form works with the C++11 late-specified return type syntax:

```c++
template <typename T>
auto RBTree<T>::searchTree(T element, Node* currNode) -> Node* {
```

The reason is that the class's scope starts when the compiler sees `RBTree<T>::`, so if `Node*` appears lexically after that, it knows to look up `Node` in the class scope (but if it occurs lexically before, it does not).

**Comment by NoahHakansson** [comment]
> As a general point of interest, the shorter form works with the C++11 late-specified return type syntax:
> 
> ```c++
> template <typename T>
> auto RBTree<T>::searchTree(T element, Node* currNode) -> Node* {
> ```
> 
> The reason is that the class's scope starts when the compiler sees `RBTree<T>::`, so if `Node*` appears lexically after that, it knows to look up `Node` in the class scope (but if it occurs lexically before, it does not).

Oh wow, didn't know late-specified return type was a thing.
That's very informative thank you again!!
