### ISSUE TITLE
clangd crashes often

### ISSUE THREAD

**Issue by pedro-esteves-pinto** [clangd/clangd#769]
Please describe the problem.
clangd crashed. 

**Logs**
 #0 0x00007f60434efa43 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xbd9a43)
 #1 0x00007f60434edd22 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xbd7d22)
 #2 0x00007f60434f00aa (/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xbda0aa)
 #3 0x00007f604ad611f0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x141f0)
 #4 0x00007f6049233914 (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x112e914)
 #5 0x00007f6049409b8f (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x1304b8f)
 #6 0x00007f60493fc6bf clang::Sema::LookupVisibleDecls(clang::DeclContext*, clang::Sema::LookupNameKind, clang::VisibleDeclConsumer&, bool, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x12f76bf)
 #7 0x00007f6049121a48 clang::Sema::CodeCompleteQualifiedId(clang::Scope*, clang::CXXScopeSpec&, bool, bool, clang::QualType, clang::QualType) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x101ca48)
 #8 0x00007f6048a8caae clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool, bool*, bool, clang::IdentifierInfo**, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x987aae)
 #9 0x00007f6048af254b clang::Parser::TryAnnotateTypeOrScopeToken() (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ed54b)
#10 0x00007f6048ae615b clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e115b)
#11 0x00007f6048ae7c98 clang::Parser::isCXXTypeId(clang::Parser::TentativeCXXTypeIdContext, bool&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e2c98)
#12 0x00007f6048ae453e clang::Parser::ParseTemplateArgument() (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9df53e)
#13 0x00007f6048ae431b clang::Parser::ParseTemplateArgumentList(llvm::SmallVector<clang::ParsedTemplateArgument, 16u>&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9df31b)
#14 0x00007f6048ae4243 clang::Parser::ParseTemplateIdAfterTemplateName(bool, clang::SourceLocation&, llvm::SmallVector<clang::ParsedTemplateArgument, 16u>&, clang::SourceLocation&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9df243)
#15 0x00007f6048ae2f4f clang::Parser::AnnotateTemplateIdToken(clang::OpaquePtr<clang::TemplateName>, clang::TemplateNameKind, clang::CXXScopeSpec&, clang::SourceLocation, clang::UnqualifiedId&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ddf4f)
#16 0x00007f6048a8c344 clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool, bool*, bool, clang::IdentifierInfo**, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x987344)
#17 0x00007f6048af254b clang::Parser::TryAnnotateTypeOrScopeToken() (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ed54b)
#18 0x00007f6048ae615b clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e115b)
#19 0x00007f6048ae5a57 clang::Parser::isCXXSimpleDeclaration(bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e0a57)
#20 0x00007f6048ad0eaf clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cbeaf)
#21 0x00007f6048ad020f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cb20f)
#22 0x00007f6048ad8080 clang::Parser::ParseCompoundStatementBody(bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9d3080)
#23 0x00007f6048ad0683 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cb683)
#24 0x00007f6048ad020f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cb20f)
#25 0x00007f6048ad33e5 clang::Parser::ParseIfStatement(clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ce3e5)
#26 0x00007f6048ad085b clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cb85b)
#27 0x00007f6048ad020f clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9cb20f)
#28 0x00007f6048ad8080 clang::Parser::ParseCompoundStatementBody(bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9d3080)
#29 0x00007f6048ad8ee5 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9d3ee5)
#30 0x00007f6048af0501 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9eb501)
#31 0x00007f6048a532bf clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x94e2bf)
#32 0x00007f6048aef78d clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ea78d)
#33 0x00007f6048aef19c clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9ea19c)
#34 0x00007f6048aee33f clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e933f)
#35 0x00007f6048a66a2a clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x961a2a)
#36 0x00007f6048a66b24 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x961b24)
#37 0x00007f6048a665df clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9615df)
#38 0x00007f6048a4d57c clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::Parser::ParsedAttributesWithRange&, clang::SourceLocation*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x94857c)
#39 0x00007f6048aedb0c clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e8b0c)
#40 0x00007f6048aecb2f clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e7b2f)
#41 0x00007f6048aec547 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x9e7547)
#42 0x00007f6048a3daf7 clang::ParseAST(clang::Sema&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x938af7)
#43 0x00007f6049fd6d48 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.12+0x1ed1d48)
#44 0x00000000005605bf (/usr/lib/llvm-12/bin/clangd+0x5605bf)
#45 0x000000000055f737 (/usr/lib/llvm-12/bin/clangd+0x55f737)
#46 0x000000000055345f (/usr/lib/llvm-12/bin/clangd+0x55345f)
#47 0x0000000000670a56 (/usr/lib/llvm-12/bin/clangd+0x670a56)
#48 0x00000000007e3681 (/usr/lib/llvm-12/bin/clangd+0x7e3681)
#49 0x00007f60434f161f (/lib/x86_64-linux-gnu/libLLVM-12.so.1+0xbdb61f)
#50 0x00007f604ad56450 start_thread ./nptl/pthread_create.c:474:7
#51 0x00007f60424bdd53 clone ./misc/.
Process clangd stderr<3> finished

**System information**
Output of `clangd --version`:  Ubuntu clangd version 12.0.0-1ubuntu1

Editor/LSP plugin: emacs 27.1.5

Operating system: Ubuntu 21.04 docker container

**Comment by njames93** [comment]
Without a reproducer there's not a lot we can do about this crash.

**Comment by pedro-esteves-pinto** [comment]
Understood, I will try to get one but its not easy, the crashes are common but they happen in the middle of a typing and its hard to know exactly what was the editor state when the crash happened. If I get a deterministic case I will try to pair it down to a repro.

**Comment by pedro-esteves-pinto** [comment]
OK, here is an attempt at a repro. The code below will trigger a crash if I type std::un amd wait for the editor to offer suggestions around line 30. I am using clangd 12, with the following switches:

/usr/lib/llvm-12/bin/clang++ --driver-mode=g++ -g -Wall -Wextra -Wpedantic -Werror -Wmisleading-indentation -g --std=c++2a -fsanitize=undefined,address,leak -DLZMA_API_STATIC -DGFLAGS_DLL_DECLARE_FLAG= -DGFLAGS_DLL_DEFINE_FLAG= -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DFOLLY_HAVE_ELF -o file.cpp.o -c file.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-12/lib/clang/12.0.0


`#include <ostream>
#include <unordered_map>

namespace ns {
template <class Tag, class ValueT>
struct ValueWrapper {
   Value v;
};
} // namespace ns

namespace std {
template <typename Tag, typename Value>
struct hash<ns::ValueWrapper<Tag, Value>> {
   std::size_t operator()(const ns::ValueWrapper<Tag, Value> &k) const {
      return hash<Value>()(k.value());
   }
};

} // namespace std

using Quantity = ns::ValueWrapper<struct QuantityTag, std::uint32_t>;
constexpr uint32_t operator+(Quantity lhs, Quantity rhs);
constexpr uint32_t operator*(Quantity lhs, Quantity rhs);

class A {};

class ABC {
 public:
   explicit ABC(std::unordered_map<int, A> const &);
   // delete this comment and type std::un and wait for the editor to offer suggestions
};
`

**Comment by kadircet** [comment]
seems quite similar to https://github.com/clangd/clangd/issues/771. I am seeing the same assertion failure:
```
clangd: /usr/local/google/home/kadircet/repos/llvm/llvm/include/llvm/ADT/DenseMap.h:1260: DenseMapIterator<KeyT, ValueT, KeyInfoT, Bucket, IsConst> &llvm::DenseMapIterator<clang::DeclarationName, clang::StoredDeclsList, llvm::DenseMapInfo<clang::DeclarationName>, llvm::detail::DenseMapPair<clang::DeclarationName, clang::StoredDeclsList>, false>::operator++() [KeyT = clang::DeclarationName, ValueT = clang::StoredDeclsList, KeyInfoT = llvm::DenseMapInfo<clang::DeclarationName>, Bucket = llvm::detail::DenseMapPair<clang::DeclarationName, clang::StoredDeclsList>, IsConst = false]: 
Assertion `isHandleInSync() && "invalid iterator access!"' failed.
```
