### ISSUE TITLE
sub-optimal comment token ranges

### ISSUE THREAD

**Issue by Trass3r** [clangd/clangd#773]
Moved from https://github.com/clangd/vscode-clangd/issues/85#issuecomment-834288300.

> ![1d8889f6e2913db87750cccfcf208441](https://user-images.githubusercontent.com/18388795/95929353-a1663a00-0d78-11eb-8a51-313fe3bb30f0.png)

It should probably only mark the inactive content as comments like in the picture. But for code like

```cpp
#ifdef PLATFORM_X
...
#elif PLATFORM_Y // or a simple #else
```
It marks the else  as a comment too when active.
And I think I saw with `#if 0 ... #endif` it marks everything as comments.

I guess one could also only mark the part of the if that is false but it may look weird with lines like `#if A && B`.

Tested on v12.

Btw is this available for `constexpr if` too?

**Comment by HighCommander4** [comment]
I closed this because I believe the primary issue has been addressed by https://reviews.llvm.org/D151190.

For this part:

> Btw is this available for `constexpr if` too?

I would suggest filing a follow-up issue. (The current answer is "no" but it would potentially be interesting to contemplate.)
