### ISSUE TITLE
System headers are not ignored.

### ISSUE THREAD

**Issue by Falven** [clangd/clangd#776]
I am not sure if I am misunderstanding this situation.
Sample repo [here](https://github.com/Falven/clangd-arduino).
clangd is complaining about a system include:

```
-----------------------------------------------------------------------------------------------------
|             Too many errors emitted, stopping now clang(fatal_too_many_errors)                       |
-----------------------------------------------------------------------------------------------------
|  In included file: anonymous bit-field cannot have qualifiers clang(anon_bitfield_qualifiers) |
|  ac.h(241, 18): Error occurred here                                                                                           |
-----------------------------------------------------------------------------------------------------
#include <Arduino.h>
_              _
```
At first I though it may be a static analysis check failure. I am invoking clangd with `--clang-tidy` and I have a `.clang-tidy` in my repo root with the following setting:

```
HeaderFilterRegex: '.*'
```
As clang-tidy states that:

`Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.`

My thoughts are clangd should ignore the `#include <Arduino.h>` given that it is a system include, and on top of that should be ignored by clang-tidy. Maybe I'm not understanding how the clang-tidy `--header-filter` parameter works, or if maybe this is a bug, but I believe clangd is ignoring my `.clang-tidy` `--header-filter` setting.

If I run `clang-tidy` manually: 

```
$ clang-tidy -dump-config
---
Checks:          'clang-diagnostic-*,clang-analyzer-*,-*, altera-*, boost-*, bugprone-*, cert-*, clang-analyzer-*, cppcoreguidelines-*, google-*, llvm-*, modernize-*, performance-*, portability-*, readability-*'
WarningsAsErrors: ''
HeaderFilterRegex: '.*'
AnalyzeTemporaryDtors: false
FormatStyle:     google
User:            falve
CheckOptions:
  - key:             bugprone-argument-comment.CommentBoolLiterals
    value:           '0'
...
```
I can see that it's picking up my config and now I see that it is not a `.clang-tidy` error, rather clang is trying to compile the included file, even though my `compile_commands.json` is specifying the directory as a `-isystem` system include, and I am passing `-w` as a compile command.
Why is `clangd` trying to compile this system include? If it does need to process this header for cases where symbols are used, is there at least a way to tell clang to compile it as C rather than CPP? I think that may at least eliminate some of the headers.

**Logs**
I[17:14:52.442] clangd version 12.0.0 (https://github.com/kirillbobyrev/llvm-project 8a844a3a321ea56da21af4d48433ad493b1bcfae)
I[17:14:52.443] PID: 3172
I[17:14:52.443] Working directory: c:\Users\falve\OneDrive\Documents\Arduino\libraries\oprintstream
I[17:14:52.443] argv[0]: c:\Users\falve\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\12.0.0\clangd_12.0.0\bin\clangd.exe
I[17:14:52.443] argv[1]: --log=verbose
I[17:14:52.443] argv[2]: --query-driver=C:\Users\falve\AppData\Local\Arduino15\packages\*\tools\**/*-g*.exe
I[17:14:52.443] argv[3]: --clang-tidy
V[17:14:52.451] User config file is C:\Users\falve\AppData\Local\clangd\config.yaml
I[17:14:52.451] Starting LSP over stdin/stdout

V[17:26:29.341] <<< {"id":34,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[{"code":"anon_bitfield_qualifiers","message":"In included file: anonymous bit-field cannot have qualifiers","range":{"end":{"character":10,"line":2},"start":{"character":9,"line":2}},"relatedInformation":[{"location":{"range":{"end":{"character":18,"line":240},"start":{"character":17,"line":240}},"uri":"file:///c%3A/Users/falve/AppData/Local/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd21/include/component/ac.h"},"message":"Error occurred here"}],"severity":1,"source":"clang"}],"only":["quickfix"]},"range":{"end":{"character":10,"line":2},"start":{"character":9,"line":2}},"textDocument":{"uri":"file:///c%3A/Users/falve/OneDrive/Documents/Arduino/libraries/oprintstream/examples/basic-example/basic-example.ino"}}}

**System information**
clangd version 11.0.0
Editor/LSP plugin: VSCode clangd
Operating system: Windows 10  x64 Version 10.0.19043 Build 19043

**Comment by HighCommander4** [comment]
clang-tidy is a **linting** tool that produces diagnostics related to code quality, typically warnings. The purpose for Its mechanism to suppress diagnostics in system headers is that consumers of system headers usually don't care about linting issues in those headers.

"anonymous bit-field cannot have qualifiers", on the other hand, is a **compiler error**, i.e. it indicates the code is ill-formed. There is no mechanism to suppress compiler errors in system headers, because those _are_ relevant. If you get such an error during your regular build, it means your project doesn't build.

If you get the compiler error only with clangd and not during your regular build, that suggests there's a configuration issue where clangd is using different flags (or doing something else that's different) than your regular build. See [this post](https://llvm.discourse.group/t/clangd-cant-find-system-headers-with-mingw-target/3387/2) for some tips on how to investigate such configuration issues.

**Comment by kadircet** [comment]
+1 to all Nathan said. I wouldn't suggest suppressing errors, but in some rare occasions it might be really hard to get clangd to parse the code in the config you want (i.e. builds succeed but clangd is complaining). In such a scenario you can have a clangd config at `~/.config/clangd/config.yaml` that looks like:
```
If:
  PathMatch: /path/to/my/codebase/.*
Diagnostics:
  Suppress: [anon_bitfield_qualifiers]
```
More details on [config files](https://clangd.llvm.org/config.html).

**Comment by kadircet** [comment]
Also closing as there isn't much we can do here. OTOH, if you figure out what discrepancy between your build vs clangd config is causing the issue, and think that it wasn't a user error but some issue with clangd feel free to open a new issue about that particular case so that we can take a closer look.

**Comment by Falven** [comment]
> +1 to all Nathan said. I wouldn't suggest suppressing errors, but in some rare occasions it might be really hard to get clangd to parse the code in the config you want (i.e. builds succeed but clangd is complaining). In such a scenario you can have a clangd config at `~/.config/clangd/config.yaml` that looks like:
> 
> ```
> If:
>   PathMatch: /path/to/my/codebase/.*
> Diagnostics:
>   Suppress: [anon_bitfield_qualifiers]
> ```
> 
> More details on [config files](https://clangd.llvm.org/config.html).

It does build with the command that `clangd` generates in a terminal window. So I am not sure why the extension mentions `anon_bitfield_qualifiers`. Regardless, I can't get the config you posted to work. Neither form y user config location nor the project `.clangd`.
