### ISSUE TITLE
clangd importing <cstddef> whenever autocompleting NULL in a C file

### ISSUE THREAD

**Issue by sarimaleem** [clangd/clangd#780]
Whenever I'm editing code in a C file, and I select NULL in my autocomplete, the header <cstddef> is imported despite it being a C++ header.

**System information**
Output of `clangd --version:
`clangd version 10.0.0-4ubuntu1`

Editor/LSP plugin: 
LSP plugins this issue happened on:
`nvim-lspconfig` with `nvim-compe`
`coc.nvim`

Operating system: WSL Ubuntu

**Comment by kadircet** [comment]
This is mitigated in clangd-12 via https://github.com/llvm/llvm-project/commit/64168c6d996b6fdd017488785e0e9ce5ce05be54.
