### ISSUE TITLE
no documentation shown for function-like macros

### ISSUE THREAD

**Issue by Trass3r** [clangd/clangd#782]
For macros like this
```cpp
/** ...
@param [in] ...
@return ERRORTYPE
 */
#define FillBuffer(h, ....) ((T*)h)->FillBuffer(...)
```
the hover popup for the definition or a call does not show the documentation:
```cpp
macro FillBuffer
#define FillBuffer(....
```

clangd version 12.0.0 d28af7c65

**Comment by kadircet** [comment]
this is not specific to function-like macros and a dupe of https://github.com/clangd/clangd/issues/140, see https://github.com/clangd/clangd/discussions/779 too.
