### ISSUE TITLE
IWYU: Unused headers/missing includes

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#79]
We know there are dragons here (correctness is hard, and it's often hard to know what correctness even means). But this is an important/popular enough feature that the perfect shouldn't be the enemy of the good.

JetBrains recently shipped unused includes based on their clangd engine in CLion 2019.2.
There's obviously also prior art in the IWYU tool (https://github.com/include-what-you-use/include-what-you-use) - that's how we all learned about the dragons.
We can poke at these for inspiration in making messy tradeoffs.

**Comment by mcraveiro** [comment]
First, many thanks for a great piece of software that keeps on getting better and better with each release! In terms of IWYU support, I for one would love to have this in clangd, even if it has a few false positives/false negatives; after all, you can always switch it off.

**Comment by kiwixz** [comment]
We now have some include logic to find the missing headers, could we build upon it to have a warning or coloration on unused includes ?  Or maybe we should give the burden of finding those to clang-tidy ?

**Comment by mcraveiro** [comment]
I personally think clangd should do it (perhaps as well as clang-tidy) because its really convenient to see the coloration when you are editing a file... I think these are two separate and equally useful use cases (local vs global?). My two Angolan Kwanzas at any rate.

**Comment by kadircet** [comment]
FYI, warnings for unused includes are currently available, controlled through `Diagnostics.UnusedIncludes` [config](https://clangd.llvm.org/config) option, and we plan to provide diagnostics for missing includes soon.

**Comment by mcraveiro** [comment]
Thanks for the update @kadircet. I'm afraid it is not obvious to me how to enable this in my ```.clangd```. Can you provide a MWE please? I mean, I presume it will have the form:

```
Diagnostics:
  UnusedIncludes:
```

But I am not quite sure.

**Comment by kadircet** [comment]
ah sorry I forgot that we don't have an entry in the config documentation yet. It should look like:
```
Diagnostics:
  UnusedIncludes: Strict
```

And you'll need a fresh build of clangd, you can get one from https://github.com/clangd/clangd/releases/tag/snapshot_20211212 or build it yourself from LLVM sources.

**Comment by mcraveiro** [comment]
Thanks very much for your prompt response.

**Comment by rburchell** [comment]
Is there a clang-tidy equivilent to this? Rmoving unused includes (and enforcing their removal in CI) seems like something I would expect to see there, but I haven't been able to find it thus far.

**Comment by kirillbobyrev** [comment]
> Is there a clang-tidy equivilent to this? Rmoving unused includes (and enforcing their removal in CI) seems like something I would expect to see there, but I haven't been able to find it thus far.

Short answer: there isn't right now, but we're actively working on making it possible to provide warnings on both unused and missing includes in clangd **and** Clang-Tidy. Our next step is uplifting and extending some of the work we already did for IncludeClenaer within clangd: there will be a common library that we will have adapters for in both clangd and Clang-TIdy.

There's some discussion on this topic here: https://reviews.llvm.org/D121593

**Comment by sam-mccall** [comment]
I've started a discussion on extracting a library so we can have a clang-tidy check: https://discourse.llvm.org/t/rfc-lifting-include-cleaner-missing-unused-include-detection-out-of-clangd/61228

**Comment by sam-mccall** [comment]
Both unused + missing are now implemented: https://clangd.llvm.org/guides/include-cleaner
The unused-includes check is now on by default (in the next release). Missing includes not yet, must be manually enabled.
The clang-tidy check exists: `misc-include-cleaner`

Going to call this done (eventually maybe we'll turn on missing includes by default, too?)

**Comment by kirillbobyrev** [comment]
@sam-mccall great job, congrats to everyone on the team!

**Comment by lukka** [comment]
A

**Comment by davidzchen** [comment]
According to the [documentation](Generates findings only for the main file of a translation unit) for `misc-include-cleaner`, it "only generates findings for the main file of a translation unit."

Is there a check that generates missing include findings for all files?

**Comment by HighCommander4** [comment]
> According to the [documentation](Generates findings only for the main file of a translation unit) for `misc-include-cleaner`, it "only generates findings for the main file of a translation unit."
> 
> Is there a check that generates missing include findings for all files?

So do you mean that e.g. if `Main.cpp` includes `A.hpp`, and `A.hpp` is missing an include for `B.hpp`, you'd like to see a diagnostic about that (with a quick fix that would add an include of `B.hpp` to `A.hpp`) when opening `Main.cpp` in the editor?

**Comment by davidzchen** [comment]
I did some searching, and it turns out that what I was looking for were the clangd missing/unused includes checks. For anyone interested, these checks are turned on by adding a `.clangd` file to the root of the repository with:

```
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
```
