### ISSUE TITLE
Configure to use C++ on .h files

### ISSUE THREAD

**Issue by AlefCS** [clangd/clangd#790]
Hey guys, I'm using C++ to do some work development. I don't use a `compile_commands.json` because the compilation environment runs on a VM, so generated `compile_commands.json` use VM's paths. But I configured the flags manually with `compile_flags.txt` file, just have a few flags.

I noticed that `.h` are triggering C and not C++ language. So when I open these kind of file I got an error of "Invalid argument" for using `-std=c++11` flag. Also got some errors for STL includes, like `map` or `string`. I believe this can be solved with some easy configuration but really don't know how to do it.

PS: I just installed coc.nvim plugin and coc-clangd. Besides that, the only configuration I've done was the `compile_flags.txt` file.

**Comment by sam-mccall** [comment]
Yes, -xc++ or -xc++-header is the flag you want.
