### ISSUE TITLE
Merge cppreference with completion info

### ISSUE THREAD

**Issue by user84441** [clangd/clangd#791]
is it possible to merge that? It can be good. Because now it lacks any reasonable information with item.

**Comment by kirillbobyrev** [comment]
This sounds like a useful addition. I don't know if we can actually parse cppreference somehow (it's not Markdown and it has some syntax we would probably be unable to parse well) but maybe just the links to cppreference for Standard Library classes and functions would be a good MVP.

**Comment by HighCommander4** [comment]
#1315 is a similar suggestion for hovers
