### ISSUE TITLE
`textDocument/signatureHelp` should not hint the underlying function for a function-like macro

### ISSUE THREAD

**Issue by aganm** [clangd/clangd#795]
I'm not sure if this is an issue related to clangd or coc-clangd.

Say I have a function
`void my_function(int x, const char *xstr);`
and a macro
`#define my_macro(x) my_function(x, #x)`

When I open the parenthese for the function like macro `my_macro`, I expect the intellisense to show me the parameters for `my_macro`, but the intellisense shows me information about what is behind the macro rather than the macro itself which is not helpful. If I type `my_macro(` , coc-clangd powered intellisense shows `my_function(int x, const char *xstr)`.

![76695140-155d2a00-6652-11ea-9414-ecd807c70263](https://user-images.githubusercontent.com/20380758/121397962-db490980-c922-11eb-852d-b6e7d096a883.gif)

```
void my_function(int x, const char *xstr)
{
}

#define my_macro(x) my_function(x, #x)

int main(int argc, char **argv)
{
	my_macro
}
```

**System information**
Operating system: Debian Sid
Clangd version: Debian clangd version 12.0.1-+rc1-1
clangd extension version: 
```
 ## versions
  
  vim version: VIM - Vi IMproved 8.2 8022434
  node version: v12.21.0
  coc.nvim version: 0.0.80-825a54d780
  coc.nvim directory: /home/aganm/.vim/plugged/coc.nvim
  term: dumb
  platform: linux

```

**Comment by HighCommander4** [comment]
Filed in duplicate (#794).
