### ISSUE TITLE
Can this coc.nvim plugin change the c++ format style?

### ISSUE THREAD

**Issue by lixiao189** [clangd/clangd#796]
I wish each line has an indent of length4, how can I make it?

**Comment by kirillbobyrev** [comment]
Clangd [embeds Clang-Format](https://clangd.llvm.org/features#formatting) and uses its style to determine the indenation width and other formatting options. The way you change the style is by putting [`.clang-format` file](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) into the project root and configuring the options. You can also make use of the `--fallback-style` argument and try something that fits you better than the default one (`LLVM`), e.g. Microsoft has indent width of 4 that you might like.

**Comment by kirillbobyrev** [comment]
Marking this issue as resolved, please let me know if you have any other questions or the proposes solution doesn't work for you.
