### ISSUE TITLE
findDocumentHighlights/findReferences issue with anonymous union/struct fields

### ISSUE THREAD

**Issue by theorlangur** [clangd/clangd#798]
Following annotated piece of C++ is not properly highlighted (all usages of 'someVal')

```
R"cpp(// Highlighting anonymous member fields of union
        struct X{
           union{
             int [[someVal]];
             float someFVal;
           };
        };
         void foo(){
           X x;
           x.$write[[someVal]] = 1;
           x.[[some^Val]] += 1;
           x.[[someVal]] += 1;
        }
       )cpp"
```

As I understand this is due to SelectionTree providing wrong (incomplete?) info for someVal, so that when obtaining encoded string instead of getting something like: `..@S@x@Ua@someVal` it skips `@Ua` and `someVal` has an empty name so the whole getSymbolID fails and returns empty hash object.

this is my attempt of working around the issue:
https://github.com/theorlangur/llvm-project/commit/83119fe57b3d5d1891451f20d9af3d7d28f6b340

**Comment by hokein** [comment]
Thanks for the report. 

This is an interesting bug, this looks like a bug in clang's AST.

So the AST for the expression `x.someVal;` is like:

```
-MemberExpr 0x9355b60 <line:27:12, col:14> 'int' lvalue .someVal
  | `-MemberExpr 0x9355b18 <col:12, col:14> 'X::(anonymous union at /tmp/t.cpp:13:12)' lvalue .
  |   `-DeclRefExpr 0x9355af8 <col:12> 'X' lvalue Var 0x9329aa0 'x' 'X'
```

Note that both MemberExprs have the same location range (the end location claims to the  `someVal` token), so selection tree ends up with the inner `MemberExpr` if the cursor is around `som^eVal`.

I think this is a clang bug about the source location for the inner MemberExpr, we should probably fix that location in clang.

**Comment by theorlangur** [comment]
if I understand correctly, this is the piece, that skips USR generation all together when it encounters a field declaration with an empty name:

https://clang.llvm.org/doxygen/USRGeneration_8cpp_source.html#l00216

**Comment by sam-mccall** [comment]
There's at least a SelectionTree bug here, sent https://reviews.llvm.org/D104376
