### ISSUE TITLE
SystemHeadersMapping doesn't work in dynamic index

### ISSUE THREAD

**Issue by hokein** [clangd/clangd#8]
In https://reviews.llvm.org/D57508, we enable include insertion in dynamic index.

Reproduce step:
1. running clangd without any static index
2. run code completion at 

```
#include <vector>
std::^
```
Actual result:
![image](https://user-images.githubusercontent.com/2557445/52486832-7b0ff480-2bbc-11e9-99d6-e65cc907d79e.png)

Expected result: The include header should be STL header, e.g. ` <memory>`.

Off-topic: this feature seems a bit noisy, in the sample above, completion symbols are from `<vector>` or headers being included transitively, the code is still compilable without the include insertion.

**Comment by kadircet** [comment]
Fixed with https://reviews.llvm.org/D58029
