### ISSUE TITLE
Mechanism to customize/modify flags retrieved from CDB.

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#80]
e.g. blacklist -fstack-usage or -fconserve-stack, which are flags we don't have.

e.g. insert -gcc-toolchain to work around standard library discovery.

Probably need the ability to scope to at least project, maybe match files/commandlines/flags with patterns.

**Comment by sam-mccall** [comment]
Request: https://www.reddit.com/r/cpp/comments/cafj21/ccls_clangd_and_cquery/etc7a2v/

**Comment by kadircet** [comment]
Ooops, missed that one somehow. But https://reviews.llvm.org/D62804 and https://reviews.llvm.org/D63194 should help with this.

**Comment by sam-mccall** [comment]
This is done now via config system.
