### ISSUE TITLE
Go to definition/implementation doesn't list the implementation until the file is opened once

### ISSUE THREAD

**Issue by Pipirongu** [clangd/clangd#802]
I use clangd with vscode. I want to use the "Go to definition" or "Go to implementation" functionality. But when I use it on an interface's function. It won't list the file containing the implementation until that file is opened once. 

When the implementation file is opened, I can see that clangd is changed from idle to indexing. Not sure if that's related to the issue?

The impl file only needs to be opened once and the functionality will work correctly, even after restart.

**System information**
clang12

**Comment by HighCommander4** [comment]
Based on the discussion of this issue on Discord (I assume "Phisen" there is you), it sounds like the issue was that if a project contains multiple compilation databases (`compile_commands.json` files) in different subdirectories, then indexing of a particular subdirectory is only triggered when a source file in that subdirectory is opened.

An effective way to resolve this is to combine the different CDBs into one (which you mentioned you were already doing, but the subdirectory CDBs need to be removed otherwise they take precedence over the combined one).

**Comment by Pipirongu** [comment]
Yes Phisen on Discord is me. I've deleted the CDBs in the subdirectories and cleared the cached index files. The issue finding the impl file looks to be resolved. And I don't see that it's indexing every source file I open like before.

Should the index be completely built for a project when starting vscode? I noticed that the total index value in the status bar is much smaller than when I had CDBs in subdirectories. Once, when I thought it was done indexing(no indicator in status bar) and clicked around in different source files. Then it started to index additional X amount of entries.

**Comment by HighCommander4** [comment]
My experience using clangd with a project with a single CDB is that when you first open the project:

  * For a few seconds / a minute, the progress indicator will say "0/1", while clangd starts up, loads the CDB, and builds a list of files to be indexed.
  * It will then change to something like "0/8000" (the number of source files that need indexing) and the first number will slowly increase as the indexing process progresses. Indexing happens in parallel, with the number of threads I believe defaulting to the number of cores, but customizable via `-j`.

If you interrupt indexing before it completes, when you next start clangd the total number will reflect the number of files remaining to index (e.g. if you interrupt at 6000/8000, on next startup it will be 0/2000). If you pull from upstream such that some files change, clangd knows which files are out of date and need reindexing, and will show e.g. 0/1000 if 1000 files need reindexing.
