### ISSUE TITLE
The map::emplace syntax error is not diagnosed

### ISSUE THREAD

**Issue by lingege32** [clangd/clangd#803]
Hi experts,
When I use `emplace` method of `std::map`, I find that the diagnosis is not shown.
The example code like following:
``` cpp
int main()
{
    std::map<int, char*> a;
    int b = 1;
    a.emplace(2,b); // <--- should print out the error because b is not char*
    return 0;
}
```

**Logs**
I[13:52:31.557] Indexed main.cpp (13192 symbols, 51310 refs, 245 files)
I[13:52:31.557] Failed to compile /home/lingege32/_practice/cpp-concurrency/main.cpp, index may be incomplete
  Noted: The failed info show only in the first indexing, a.k.a after removing .cache directory

**System information**
Output of `clangd --version`:
  Ubuntu clangd version 11.0.0-2~ubuntu20.04.1

Arguments of clangd:
  I[13:41:03.808] argv[0]: /usr/bin/clangd
  I[13:41:03.808] argv[1]: --log=info

compile commands invoked by clangd:
  `/usr/lib/llvm-11/bin/clang++ --driver-mode=g++ -c -std=c++20 -Wall -Werror -Wextra -O3 -o main.o main.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.0`

Editor/LSP plugin:
  VScode/Clangd

Operating system:
  WSL2 in Windows10

**Comment by HighCommander4** [comment]
This has to do with the fact that `emplace()` has a permissive signature (`template <typename... Args> emplace(Args&&...)`), and therefore the type mismatch does not occur directly at the call site, but inside the implementation of `emplace()`.

For performance reasons, clangd does not parse the bodies of function templates in header files, so it does not produce this diagnostic.

Please see #137 for more discussion.
