### ISSUE TITLE
Destructor jumps to definition and declaration

### ISSUE THREAD

**Issue by CW150150** [clangd/clangd#804]
Error with destructor jumping to definition or declaration:For example, MainWindow::~MainWindow, which only works when my cursor is in front of ~. When I move the cursor to 'MainWindow' in '~MainWinow', it will show and jump to this class. I think this is probably caused by parsing text objects in VS Code
![e96462f671946693aa64285ea858659](https://user-images.githubusercontent.com/53039864/123044986-fb9dbb80-d42c-11eb-8c76-233e74ae9c39.png)
![c9f9fa43a580e930254382776195d31](https://user-images.githubusercontent.com/53039864/123044992-fccee880-d42c-11eb-8aef-e1a205d88224.png)

**Comment by HighCommander4** [comment]
Known issue, on file at https://github.com/clangd/clangd/issues/679
