### ISSUE TITLE
[Feature Request] Add support for .rsp files in compile_commands.json

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#81]
Add support for .rsp files in compile_commands.json
```json
{
  "directory": "D:/LLVM/build/lib/Support",
  "command": "g++.exe ... @CMakeFiles/LLVMSupport.dir/includes_CXX.rsp ... D:\\LLVM\\llvm\\lib\\Support\\AArch64TargetParser.cpp",
  "file": "D:/LLVM/llvm/lib/Support/AArch64TargetParser.cpp"
}
```

**Comment by sam-mccall** [comment]
For context, these are command line arguments that get expanded from a file.

This is a bit tricky design-wise: making JSONCompilationDatabase might be surprising/hard to encapsulate, but if we defer this to later then wrapping CDB implementations (like the inference for headers) may not see important flags like the filetype.

My sense is that important flags may be less likely to be stowed away in such files.

**Comment by lh123** [comment]
>My sense is that important flags may be less likely to be stowed away in such files.

Yes, usually only `-I` and `-l` flags are stored in the rsp file

**Comment by Mirko-von-Leipzig** [comment]
+1 for this issue. CMake commonly uses these rsp files to get around character limits, and is in some cases on by default.

As a work-around for CMake one can disable rsp usage by setting `CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=off`.

So either use `cmake -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=off` or add the line `set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES OFF)` to your CMake script.

**Comment by lh123** [comment]
https://reviews.llvm.org/D70222
