### ISSUE TITLE
Format specifies type 'char' but the argument has type 'char'

### ISSUE THREAD

**Issue by vinicius507** [clangd/clangd#813]
Using `printf` with flags `%hhd` gives the error:
> Format specifies type 'char' but the argument has type 'char'

To reproduce:
```c
#include <stdio.h>

int main(void)
{
    printf("%hhd\n", 'a');
    return (0);
}
```

**System information**
Output of `clangd --version`: 12.0.0
Editor/LSP plugin: Neovim 0.5 with native LSP
Operating system: Arch Linux

**Comment by HighCommander4** [comment]
Do you get this diagnostic when building your code with clang?

**Comment by vinicius507** [comment]
> Do you get this diagnostic when building your code with clang?

Actually, yes. I didn't compile it yesterday. Should I transfer the bug report?

**Comment by kadircet** [comment]
yes you should file a bug at https://bugs.llvm.org/ instead, under component clang.
