### ISSUE TITLE
Adopt vscode-clangd specific implementation for completion

### ISSUE THREAD

**Issue by hrsh7th** [clangd/clangd#815]
I'm implementing a completion plugin for neovim that should work the same as VSCode's behavior.

I found the plugin does not work well when using clangd's `dot-to-arrow` completion.

I found the difference with VSCode after some of the investigations.
That difference is vscode-clangd's following implementation.

https://github.com/clangd/vscode-clangd/blob/master/src/clangd-context.ts#L102

This implementation means the CompletionItem#filterText should contain the text that between `textEdit.range.start.character` and keyword position. .

I hope this extension's implementation will be implemented in clangd itself.

**Comment by sam-mccall** [comment]
VSCode's aggressive client-side reranking/filtering is harmful, please don't emulate it if possible.

The filterText hack is tightly coupled to VSCode's behavior and doesn't belong in clangd proper (it's very likely to break well-behaved editors)

**Comment by hrsh7th** [comment]
Thank you for your quick response.


I will consider how to make it work.
