### ISSUE TITLE
-xc++ and -xc++-header only work if I put them before the path to the header file

### ISSUE THREAD

**Issue by rickyelopez** [clangd/clangd#816]
I'm using a config file in `~/.config/clangd/config.yaml` to add arguments to the clangd command based on where I am in the project structure. One subdirectory uses C++ while most of the others use C, so I'm trying to get clangd to treat everything in that subdirectory as C++. Here's what I've got currently:

```
If:
    PathExclude: .*/c++dir/.*
CompileFlags:
    Add: [-xc,
        -xc-header,
    ]

---

If:
    PathMatch: .*/c++dir/.*
CompileFlags:
    Add: [-xc++,
        -xc++-header,
    ]
```

This is working in the sense that the arguments are added to the command. However, it is not producing the desired effect. I'm still getting `error: unknown typename 'class'`. I tried running the generated command myself in the terminal and it does, in fact, produce that output. However, if I move the arguments that I added and place them _before_ the path to the file (rather than directly after the path), it works perfectly!

What gives? Is this as intended? Is there any way I can get the arguments added before the file path using this method?

Thanks!

**Comment by HighCommander4** [comment]
This is a known issue, on file as https://github.com/clangd/clangd/issues/555

**Comment by rickyelopez** [comment]
Cool, thanks!
