### ISSUE TITLE
clangd crash when including a header

### ISSUE THREAD

**Issue by queendelacruz** [clangd/clangd#819]
I am currently using vscode with clangd as LSP. I get this clangd crash often:
```
clangd: /qdelacru/llvm/clang/lib/Lex/LiteralSupport.cpp:539: clang::NumericLiteralParser::NumericLiteralParser(llvm::StringRef, clang::SourceLocation, const clang::SourceManager &, const clang::LangOptions &, const clang::TargetInfo &, clang::DiagnosticsEngine &): Assertion `!isPreprocessingNumberBody(*ThisTokEnd) && "didn't maximally munch?"' failed.
...
#9 0x00000000012c4aa8 clang::NumericLiteralParser::NumericLiteralParser(llvm::StringRef, clang::SourceLocation, clang::SourceManager const&, clang::LangOptions const&, clang::TargetInfo const&, clang::DiagnosticsEngine&) /qdelacru/llvm-project/clang/lib/Lex/LiteralSupport.cpp:0:3
#10 0x0000000004405a3d clang::Sema::ActOnNumericConstant(clang::Token const&, clang::Scope*) /qdelacru/llvm-project/clang/lib/Sema/SemaExpr.cpp:3707:15
#11 0x0000000003bdea13 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) /qdelacru/llvm-project/clang/lib/Parse/ParseExpr.cpp:991:19
#12 0x0000000003bdb1f4 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) /qdelacru/llvm-project/clang/lib/Parse/ParseExpr.cpp:681:20
#13 0x0000000003bd9598 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) /qdelacru/llvm-project/clang/lib/Parse/ParseExpr.cpp:173:20
#14 0x0000000003ba8ec3 clang::Parser::ParseInitializer() /qdelacru/llvm-project/clang/include/clang/Parse/Parser.h:2001:14
#15 0x0000000003b98822 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /qdelacru/llvm-project/clang/lib/Parse/ParseDecl.cpp:2356:25
#16 0x0000000003b96e35 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) /qdelacru/llvm-project/clang/lib/Parse/ParseDecl.cpp:2092:9
#17 0x0000000003b70247 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) /qdelacru/llvm-project/clang/lib/Parse/Parser.cpp:1137:10
#18 0x0000000003b6f850 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) /qdelacru/llvm-project/clang/lib/Parse/Parser.cpp:1153:12
#19 0x0000000003b6f0cf clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) /qdelacru/llvm-project/clang/lib/Parse/Parser.cpp:975:12
#20 0x0000000003b6d301 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) /qdelacru/llvm-project/clang/lib/Parse/Parser.cpp:720:12
#21 0x0000000003b6cb53 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) /qdelacru/llvm-project/clang/lib/Parse/Parser.cpp:592:8
#22 0x0000000003b6824e clang::ParseAST(clang::Sema&, bool, bool) /qdelacru/llvm-project/clang/lib/Parse/ParseAST.cpp:157:15
#23 0x00000000038864e2 clang::ASTFrontendAction::ExecuteAction() /qdelacru/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1060:1
#24 0x0000000003885ea8 clang::FrontendAction::Execute() /qdelacru/llvm-project/clang/lib/Frontend/FrontendAction.cpp:955:7
#25 0x00000000017c72ff clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clang
```

To repro, if I try to include a header above the macro I get the error above sometimes. 
```

#define MACRO_SIZE       32

int num = MACRO_SIZE;
```
It seems like when clang is trying to resolve the macro, the token at LiteralSupport.cpp:539 seems to be off by one (like it sees ' 3' instead of '32'). This is reproducible on the latest main branch but when i use the --async-preamble=false flag in clangd 11 I can't reproduce the error anymore so it makes me think this could be an issue with a stale preamble.

**System information**
clangd version 13.0.0 (https://github.com/llvm/llvm-project.git 424f14f0d2e98b83a41bdc7408f15d28aaa4cbd0)
Editor/LSP plugin: vscode
Operating system: Linux

**Comment by kadircet** [comment]
It is very well likely that I managed to screw up some things while patching up preambles. The logic actually tries to spell macro body as-is to prevent such failures, and I couldn't really manage to reproduce. Can you record a crashing session with `--input-mirror-file=/tmp/clangd_mirror.txt` and send that file here so that I can take a closer look at the issue?

**Comment by queendelacruz** [comment]
This is the 
[clangd_mirror.txt](https://github.com/clangd/clangd/files/6859259/clangd_mirror.txt)

FYI I was trying to figure out a solution for this problem, and since I noticed that macro location is off by one I tried using the macro's source location when comparing old preamble vs new preamble.
```
--- a/clang-tools-extra/clangd/Preamble.cpp
+++ b/clang-tools-extra/clangd/Preamble.cpp
@@ -142,10 +142,11 @@ struct TextualPPDirective {
   unsigned DirectiveLine;
   // Full text that's representing the directive, including the `#`.
   std::string Text;
+  SourceLocation Loc;

   bool operator==(const TextualPPDirective &RHS) const {
-    return std::tie(DirectiveLine, Text) ==
-           std::tie(RHS.DirectiveLine, RHS.Text);
+    return std::tie(DirectiveLine, Text, Loc) ==
+           std::tie(RHS.DirectiveLine, RHS.Text, RHS.Loc);
   }
 };

@@ -213,6 +214,7 @@ struct DirectiveCollector : public PPCallbacks {
     TextualPPDirective &TD = TextualDirectives.back();

     const auto *MI = MD->getMacroInfo();
+    TD.Loc = MI->getDefinitionLoc();
     TD.Text =
         spellDirective("#define ",
                        CharSourceRange::getTokenRange(
```
This seems to fix for this small example, but the error still persists when I use this version of clangd on a bigger c file. I'm trying to narrow down to a smaller example

**Comment by queendelacruz** [comment]
Also note that the other crash I was seeing is related to code completion. I noticed that we don't patch the preamble when parsing for code completion https://code.woboq.org/llvm/clang-tools-extra/clangd/CodeComplete.cpp.html#1870
But this seems to likely cause problems if we are using stale preambles?

**Comment by kadircet** [comment]
Sorry I still cannot reproduce the crash on my side, and just noticed mirror file is not enough by itself, since timing of edits are also important. You can try reproducing by adding a test case to https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clangd/unittests/PreambleTests.cpp#L351. The idea is you first provide contents for the stale preamble, something like the following IIUC:
```cpp
#define FOO        42
int foo = FOO;
```

afterwards you provide the new contents, e.g:
```cpp
#define BAR
#define FOO  42
int foo = FOO;
```

The test mechanism builds the new contents using the preamble build from the old contents.

As for usage of stale preambles, yes, in theory you are right making use of stale preambles for any operation could throw clangd off, hence it tries hard to make sure file reads with offsets from preamble are not issued. Code completion has been using stale preambles since day 0 (at least since I joined) and it has been OK so far.
