### ISSUE TITLE
compile_flags.txt over compile_commands.json

### ISSUE THREAD

**Issue by mmanyen** [clangd/clangd#825]
I am working with an oddball cross compiler and clangd flags all of the compiler directives as problems in the file. 

When I delete the json file and provide a compile_flags.txt file, it works fine. 

I would like an option to force clangd to use the txt file and not compile_commands.json.

**Comment by HighCommander4** [comment]
One way to accomplish this today would be to place the `compile_flags.txt` into a different directory, and point clangd to that directory using the command-line option `--compile-commands-dir=<directory>`.

**Comment by kadircet** [comment]
I don't think it would be feasible to have a knob to specify which one should take precedence, we would rather need something that will define an order. It sounds like both an overkill (as the demand is low) and won't interact nicely with all the custom database implementations people might have downstream.

That being said, an extra to what Nathan pointed out, you can make use of `CompileFlags.CompilationDatabase` config to specify that directory in file/project granularity. See https://clangd.llvm.org/config#compilationdatabase.

**Comment by mmanyen** [comment]
Srry, but --compile-commands-dir=~/ did not work when the json file was present

Yes, there is a compile_commands.txt file in the home directory

**Comment by HighCommander4** [comment]
> Srry, but --compile-commands-dir=~/ did not work when the json file was present

The suggestion was to place the compile_flags.txt into a **different** directory (which does not contain a `compile_commands.json`), and use `--compile-commands-dir` to point clangd at that directory.

**Comment by mmanyen** [comment]
The source is not in my home directory
