### ISSUE TITLE
clangd returns incorrect indent for snippets

### ISSUE THREAD

**Issue by fannheyward** [clangd/clangd#828]
For example, `while` will return the snippet, but the indent before `statements` is incorrect.

**Logs**
```json
{
    "filterText": "while",
    "insertText": "while (${1:expression}) {\n${0:statements}\n}",
    "insertTextFormat": 2,
    "kind": 15,
    "label": " while (expression) {statements}",
    "score": 8,
    "sortText": "3f000000while",
    "textEdit": {
        "newText": "while (${1:expression}) {\n${0:statements}\n}",
        "range": {
            "end": {
                "character": 7,
                "line": 21
            },
            "start": {
                "character": 4,
                "line": 21
            }
        }
    }
}
```

![](https://files.gitter.im/5c7cd365d73408ce4fb98b75/BtuD/image.png)

**System information**
Output of `clangd --version`: clangd 12
Editor/LSP plugin: coc-clangd/vscode-clangd
Operating system: macOS

**Comment by kadircet** [comment]
yes that's WAI. since running formatting on every code completion item in advance is not feasible latency-wise, we rather expect the user to trigger formatting explicitly, or the editor to send a format on type request after selection of a completion item.
