### ISSUE TITLE
[Feature Request] Watch for changes in "compile_commands.json" and "compile_flags.txt"

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#83]
Currently only restart VSCode to make clangd re-read "compile_commands.json" and "compile_flags.txt"

**Comment by sam-mccall** [comment]
Good idea. The most obvious way I can think of is put a `bool stale()` method on CompilationDatabase.

**Comment by Trass3r** [comment]
> Currently only restart VSCode to make clangd re-read "compile_commands.json" and "compile_flags.txt"

Well there's a command `Restart the clangd language server` which is slightly less bad but still the file should just be watched properly.

**Comment by kadircet** [comment]
@ChristianKuehnel

**Comment by sam-mccall** [comment]
This was done in https://github.com/llvm/llvm-project/commit/98993193e9037345ad13720a62974064a5f3d953 and some related commits.

**Comment by studgeek** [comment]
Note this issue's functionality of restarting when compile_commands.json was removed at some point in favor of just "hot reload" at file level. Details are in https://github.com/clangd/vscode-clangd/issues/300#issuecomment-2348016329.

I think you can vote there if want option to have clangd restart functionality back also.
