### ISSUE TITLE
Array of nested template structs/class not completing

### ISSUE THREAD

**Issue by yorkerhazan** [clangd/clangd#831]
A class/struct that has array of template struct with nested template argument (`foo` in the example) doesn't recognise the class. In this example, `TemplateExample` holds an array of the template struct `NestedStruct`.

```c++
template <int foo>
struct NestedStruct
{
	int a = foo;
	int b = foo + 1;

	int boo()
	{
		return a + b;
	}
};

template<int foo>
struct TemplateExample 
{
	NestedStruct<foo> arr[5];

	int boo(int index)
	{
		// Auto Completion not working
		return arr[index].boo();
	}
};
```
**Logs**
[logs.txt](https://github.com/clangd/clangd/files/6915742/logs.txt)

**System information**

Output of `clangd --version`: clangd version 10.0.0-4ubuntu1

Editor/LSP plugin: Sublime 4107 with sublime_lsp

Operating system: Ubuntu 20.04

**Comment by kadircet** [comment]
this is what the ast node for `arr[0].boo();` looks like:
```
        |-CallExpr 0xaf3f6a0 <line:15:5, col:16> '<dependent type>'
        | `-CXXDependentScopeMemberExpr 0xaf3f658 <col:5, col:12> '<dependent type>' lvalue .boo
        |   `-ArraySubscriptExpr 0xaf3f638 <col:5, col:10> '<dependent type>' lvalue
        |     |-MemberExpr 0xaf3f5e8 <col:5> 'NestedStruct<foo> [5]' lvalue ->arr 0xaf109d8
        |     | `-CXXThisExpr 0xaf3f5d8 <col:5> 'TemplateExample<foo> *' implicit this
        |     `-IntegerLiteral 0xaf3f618 <col:9> 'int' 0
```

unfortunately `ArraySubscriptExpr` produces a `dependent type` rather than a `NestedStruct<foo>`. I am not sure how complicated it would be, but we can try to make use of underlying type for subscripts on arrays/pointers since they can't (?) have overloaded `operator[]`.

**Comment by sam-mccall** [comment]
We can hack more rules into code completion [getApproximateType](https://code.woboq.org/llvm/clang/lib/Sema/SemaCodeComplete.cpp.html#_ZN12_GLOBAL__N_118getApproximateTypeEPKN5clang4ExprE)

But I think clang's AST might be being too conservative here in not typing the expr and we can fix it at that level.
If i'm reading the rules right:
 - overloading isn't an issue here (over.sub, over.match.oper) if we can prove the LHS doesn't have class type
 - in the non-overload case, one arg must be pointer or array, and the other must be integer or enum (LHS vs RHS doesn't matter). So if LHS is pointer-or-array, we can assume it's the base and thus determine the type.

**Comment by sam-mccall** [comment]
https://reviews.llvm.org/D107275

Not sure exactly how far to go with this, hopefully Richard can weigh in
