### ISSUE TITLE
Clang messages can not close.

### ISSUE THREAD

**Issue by Hungpro3112** [clangd/clangd#833]
I have a c file with some mistakes 
![image](https://user-images.githubusercontent.com/75968004/128113720-4a1c8fb2-19dc-40e1-aa01-f3acd69d9c00.png)

When i put a cursor on `putchar()` it appear a message like above. But when a change a cursor to another place it not disappear
and still there.
![image](https://user-images.githubusercontent.com/75968004/128114067-1ae675ea-a9ff-4477-b730-3cbe9d0575f8.png)

Or when i change to other files it still there:
![image](https://user-images.githubusercontent.com/75968004/128114002-b6513b9a-2558-4e4e-9f6a-2a6fc785fefd.png)

I don't know this is a bug or i forgot some config 

Thanks for your help !!!

**Comment by HighCommander4** [comment]
That looks like an issue with your client (I can't tell from the screenshot which one it is).

**Comment by sam-mccall** [comment]
Definitely a client bug.
Looks like vim, `:call popup_clear()` will fix it. (But not prevent it happening again)

**Comment by Hungpro3112** [comment]
> Definitely a client bug.
> Looks like vim, `:call popup_clear()` will fix it. (But not prevent it happening again)

So how to solve this problem permanently?

**Comment by kadircet** [comment]
by filing a bug to your LSP client maintainer.

**Comment by Hungpro3112** [comment]
> by filing a bug to your LSP client maintainer.

What do you mean?

**Comment by kadircet** [comment]
The problem you are facing is not related to clangd. You must've installed a vim plugin to enable clangd. I am telling that you should contact maintainer of that plugin about this issue.
