### ISSUE TITLE
If and else need to more convenient to use

### ISSUE THREAD

**Issue by Hungpro3112** [clangd/clangd#837]
I use clangd for autocomplete c code in vim
When I use `if` or `else` or `else if`, it is really helpful to open braces in `expression` and auto-delete the suggestion when i type the `expression` ( This is really good ). But it has a uncomfortable when go to write the `statements`. I want it auto-delete when i type my statement but the word `statements` is still there and i have to delete it every time.

![bandicam 2021-08-06 20-57-30-162](https://user-images.githubusercontent.com/75968004/128523935-ac131f70-8b8b-4570-b271-7237ab7ccb3f.gif)

**Comment by sam-mccall** [comment]
This is up to the editor/editor plugin, not the language server.

When there are multiple placeholders, coc.nvim uses the shortcut key ctrl-j to jump to and select the next placeholder. If you don't do this then it remains as regular text.
(To some extent this is probably a limitation of what's possible in vim).

**Comment by Hungpro3112** [comment]
> This is up to the editor/editor plugin, not the language server.
> 
> When there are multiple placeholders, coc.nvim uses the shortcut key ctrl-j to jump to and select the next placeholder. If you don't do this then it remains as regular text.
> (To some extent this is probably a limitation of what's possible in vim).

Can you tell my where the document about shortcut in coc.nvim?
