### ISSUE TITLE
drv_unknown_argument '-fconserve-stack' '-fno-allow-store-data-races'

### ISSUE THREAD

**Issue by PanQL** [clangd/clangd#844]
clangd just does not accept some gcc options like conserve-stack. I use it with neovim and get some errors bellow:

[clang drv_unknown_argument] [E] Unknown argument: '-fconserve-stack'
[clang drv_unknown_argument] [E] Unknown argument: '-fno-allow-store-data-races'

while everything goes well when I use ccls instead.

**System information**

Output of `clangd --version`: clangd version 12.0.1

Editor/LSP plugin: neovim/coc

Operating system: Gentoo Linux

**Comment by HighCommander4** [comment]
You can remove the offending flags by adding the following to `.clangd` (see [config file docs](https://clangd.llvm.org/config.html)):

```
CompileFlags:
  Remove: [-fconserve-stack, -fno-allow-store-data-races]
```
