### ISSUE TITLE
Show signature of a lambda in completion results

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#85]
Input:
```cpp
void test() {
 auto foo = [](int a, int b) { ... };
 foo^
}
```
Expected: type of foo in completion list mentions lambda signature, e.g. `(int a, int b) -> void`.
Actual: type of foo is `<lambda>`.

**Comment by sureyeaah** [comment]
This would require changing the `Declaration` inside `CodeCompletionResult` before it is converted to `CodeCompletionString`. Probably requires making changes to `CodeCompleteConsumer` in clang.

**Comment by kirillbobyrev** [comment]
[D70445](https://reviews.llvm.org/D70445) up for review.

**Comment by kirillbobyrev** [comment]
Fixed in https://github.com/llvm/llvm-project/commit/7f0dcf665dd22be296805bc7a1c71a36243c4e09.
