### ISSUE TITLE
clangd not working with CMake's precompiled headers

### ISSUE THREAD

**Issue by hojdars** [clangd/clangd#856]
Hello!

I ran into an issue of how clangd interacts with CMake's precompiled headers. It seems that clangd doesn't know how to handle them, even if `compile_commands.json` specify the include. Since CMake and precompiled headers are involved, I created a minimal repository to demonstrate the behavior:

https://github.com/hojdars/precompiled-clangd-vscode

When running clang-tidy it correctly finds the two possible improvements in the code (namely the missing `const` on `A::GetInt` and the possible simplification in the `for` loop).

However, it also emits an error saying `Use of undeclared identifier 'say' (undeclared_var_use)` indicating it does not see the `hello.hpp` file as an include, even though `compile_commands.json` contain this:

```json
{
  "directory": "/<path-to-code>/precompiled-clangd-vscode/build",
  "command": "/usr/bin/x86_64-linux-gnu-g++-10    -g   -Winvalid-pch -include /<path-to-code>/precompiled-clangd-vscode/CMakeFiles/hello-world.dir/cmake_pch.hxx -o CMakeFiles/hello-world.dir/main.cpp.o -c /<path-to-code>/precompiled-clangd-vscode/main.cpp",
  "file": "/<path-to-code>/precompiled-clangd-vscode/main.cpp"
}
```

(see the project's README for an image of what I am getting in VS Code).

Lastly, I am not sure if this is a problem of `clangd` or maybe a bug in `vscode-clangd` since I do use that extension. I am not proficient with clangd from the CLI, so sorry for not being more specific!

Lastly lastly, it might be the case that I messed up the project's configuration. If that is the case, I apologize.

**Logs**

[clangd.log](https://github.com/clangd/clangd/files/7119744/clangd.log)

The important line being `V[09:25:30.808] Trying to fix unresolved name "say" in scopes: []`

**System information**

Output of `clangd --version`: clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)

Editor/LSP plugin: VS Code

Operating system: Linux Mint 20.2

P.S.: I love using clangd and its subtools (like clang-tidy, I can't live without it <3), thank you all for the work!

**Comment by HighCommander4** [comment]
I don't think clang can read gcc's precompiled header format. I believe the formats are tied to the respective compiler internals, and as such I don't think that's going to change.

Do you have the option of building your project with clang, and thus using its PCH format?

**Comment by hojdars** [comment]
Oh that would explain it! However, even when building the dummy project with clang, the errors still remain. The precompiled file changes **from**:
```c++
/* generated by CMake */

#pragma GCC system_header
#ifdef __cplusplus
#include "/home/hojdar/Projects/vscode-clang/precompiled/hello.hpp"
#endif // __cplusplus
```
**to**:
```c++
/* generated by CMake */

#pragma clang system_header
#ifdef __cplusplus
#include "/home/hojdar/Projects/vscode-clang/precompiled/hello.hpp"
#endif // __cplusplus
```
But the same error - `Use of undeclared identifier 'say' (undeclared_var_use)` - is still present.

A new clang warning is shown in the precompiled file though: `#pragma system_header ignored in main file clang(-Wpragma-system-header-outside-header)`. I am at the limit of my experience here, so I am not sure if it's me or clang/clangd who is messing up here :)

**Comment by hojdars** [comment]
I seem to be running into the same problem as another user in this issue: https://gitlab.kitware.com/cmake/cmake/-/issues/22081

Using his workarounds solves the problem in the dummy project.

As a result, this does not seem to be a clangd bug, but rather a clang quirk and thus I am closing the issue.

**Comment by kadircet** [comment]
FWIW this seems to be WAI for me when using clang as compiler with the CMAKE. The generated compilation database looks like:
```
{
  "directory": "/tmp/precompiled-clangd-vscode/build",
  "command": "/usr/bin/c++ -Winvalid-pch -Xclang -include-pch -Xclang /tmp/precompiled-clangd-vscode/build/CMakeFiles/hello-world.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /tmp/precompiled-clangd-vscode/build/CMakeFiles/hello-world.dir/cmake_pch.hxx -o CMakeFiles/hello-world.dir/main.cpp.o -c /tmp/precompiled-clangd-vscode/main.cpp",
  "file": "/tmp/precompiled-clangd-vscode/main.cpp"
}
```

As you can see it passes `-include` explicitly to the cc1 via `-Xclang`, which results in the following invocation underneath:
```
... -include-pch /tmp/precompiled-clangd-vscode/build/CMakeFiles/hello-world.dir/cmake_pch.hxx.pch -include /tmp/precompiled-clangd-vscode/build/CMakeFiles/hello-world.dir/cmake_pch.hxx .... -x c++ /tmp/precompiled-clangd-vscod      e/main.cpp
```

Clangd later on ignores the `-include-pch` as it can't really make use of any PCH built with a version different than the clang embedded inside, but it still knows about the `-include` to use, hence everything works as expected.

Whereas when used with gcc, the generated compile commands looks like:
```
{
  "directory": "/tmp/precompiled-clangd-vscode/build",
  "command": "/usr/bin/g++ -Winvalid-pch -include /tmp/precompiled-clangd-vscode/build/CMakeFiles/hello-world.dir/cmake_pch.hxx -o CMakeFiles/hello-world.dir/main.cpp.o -c /tmp/precompiled-clangd-vscode/main.cpp",
  "file": "/tmp/precompiled-clangd-vscode/main.cpp"
}
```

This one passes `-include` to the driver, and unfortunately clang driver looks for an existing pch/gch file and [converts](https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/ToolChains/Clang.cpp#L1339) the `-include` silently to a `-include-pch`, without preserving the `-include`. So everything actually works with GCC until the build is run and PCH is generated.

I suppose a proper fix would be to change the driver to preserve the `-include` flag in such cases, as the `-include-pch` effectively adds a `-include` for the underlying header, making the explicit `-include` a no-op whenever the PCH file exists. This might cause problems when the original file name used to generate the PCH is different than the one mentioned with `-include` (not sure if this can happen in reality). If there's push back from the community, I suppose we can try to add a `-include` in clangd's compiler invocation creation logic before clearing out the implicit pch file.
