### ISSUE TITLE
Warning when symbols are included indirectly

### ISSUE THREAD

**Issue by playgithub** [clangd/clangd#857]
As below, `b.h` references `class A` in `a.h`, but `b.h` doesn't include `a.h` directly but indirectly.
`clangd` will show a warning for `class A` in `b.h`, for it doesn't know `class A`.

a.h
```cpp
class A
{
    ...
}
```

b.h
```cpp
void test(const A & a);
```

b.cpp
```cpp
#include "a.h"
#include "b.h"

void test(const A & a)
{
   ...
}
```

I think direct includes as clangd does is more robust, but it incurrs more needless compilation when header files change.
If using extra declares as below, there might be too much declares like:
```
class A;
class B;
class C;
```
Still not good enough.

It is not bad if `clangd` knows indirect inlcudes.
Is there an option for this?

**Comment by HighCommander4** [comment]
This is https://github.com/clangd/clangd/issues/45. Please see the discussion there for why it's not easy to support.
