### ISSUE TITLE
Header files defined in ./include folder are not properly read with coc-clangd

### ISSUE THREAD

**Issue by vlashada** [clangd/clangd#862]
I just recently started writing C++, and I installed coc-clangd (love the extension, great job and a big thank you to those who maintain it!). My problem is that I am trying to split my project into multiple files, using headers to include the files. When I put my header files in `./include/project_name/header_file.h`, and include them using `#include "project_name/header_file.h"`, I am able to compile, but coc gives a red line, and the functions I am calling are also missing coc.

How can this be fixed?

`
> tree
.
├── include
│  └── project_name
│     └── functions.h
├── makefile
└── src
   ├── functions.cpp
   └── main.cpp
`

**System information**
Clangd version (from the log, or `clangd --version`): 12.0.1
clangd extension version (from `:CocInfo`):
## versions

vim version: NVIM v0.5.0
node version: v16.7.0
coc.nvim version: 0.0.80-73861dc2ae
coc.nvim directory: /home/username/.config/nvim/autoload/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2021-09-11T21:01:00.175 INFO (pid:47140) [plugin] - coc.nvim 0.0.80-73861dc2ae initialized with node: v16.7.0 after 166ms
2021-09-11T21:01:01.778 INFO (pid:47140) [attach] - receive notification: showInfo []

Operating system:
Arch Linux

**Comment by kirillbobyrev** [comment]
Hi! What you're seeing is [clangd not being able to infer the project structure](https://clangd.llvm.org/troubleshooting#cant-find-includes-within-your-project). It needs `compile_commands.json` either from the CMake invocation but can also be achieved through Bear if you'rer using Makefile instead. Please see [project setup](https://clangd.llvm.org/installation#project-setup).

In the meantime, I'll mark the issue as "resolved", please feel free to reopen and ask more questions if you have more problems.

**Comment by vlashada** [comment]
Thank you for the fast response, I got it to work. I have a question though; is it possible to have a "general" compile_commands.json, that will always include the "include/*" directory from the root of my current project?

**Comment by kirillbobyrev** [comment]
Unfortunately, I don't think this is possible. You can always add `-I` flag through `.clangd` [config file](https://clangd.llvm.org/config) (either local or global) but, again, the optimal experience would still require `comile_commands.json` because clangd still would need to infer other compile flags and be able to index the whole project correctly.
