### ISSUE TITLE
Call Hierarchies support

### ISSUE THREAD

**Issue by pidgeon777** [clangd/clangd#867]
Does `clangd` support incoming and outgoing call hierarchies for functions?

**Comment by HighCommander4** [comment]
Please see #162.

To summarize briefly:

  * Support for incoming calls was added in clangd 12.
  * Outgoing calls has a patch but is kind of stalled. See [this comment](https://github.com/clangd/clangd/issues/162#issuecomment-785487106) and feel free to weight in there.
