### ISSUE TITLE
[clang-tidy] plans to add '-warnings-as-errors' flag as a command line argument

### ISSUE THREAD

**Issue by vince-fugnitto** [clangd/clangd#87]
**Description**

Are there any plans to add the `-warnings-as-errors` flag when the `clang-tidy` and `clang-tidy-checks` are provided through the command line. Based on the documentation from https://clang.llvm.org/extra/clang-tidy/, the flag should upgrade any warnings emitted by the checks flag into errors.

**Comment by sam-mccall** [comment]
The severity with which warnings are treated tends to be a project-level decision. Are you able to put this in a `.clang-tidy` file? Format is described in https://clang.llvm.org/extra/clang-tidy/

This is the preferred way to configure .clang-tidy with clangd (and IMO at all). `-clang-tidy-checks` is an escape hatch, mostly for testing, but I don't think we want to go down the path of exposing every clang-tidy option as a clangd flag.

**Comment by vince-fugnitto** [comment]
@sam-mccall thank you for the clarification and your comments.

> The severity with which warnings are treated tends to be a project-level decision. Are you able to put this in a `.clang-tidy` file? Format is described in https://clang.llvm.org/extra/clang-tidy/. I do believe we support `WarningsAsErrors` as of https://reviews.llvm.org/D61841

Yes, I was able to use the `WarningsAsErrors` included in the `.clang-tidy` file previously.
If this is the recommended way forward I completely understand, and I agree it's more of a project level decision which flags to turn on, and which to treat as errors.


> `-clang-tidy-checks` is an escape hatch, mostly for testing, but I don't think we want to go down the path of exposing every clang-tidy option as a clangd flag.

Thank you for the clarification, I had noticed the `-clang-tidy-checks` in `clangd` and was simply wondering as to why a flag similar to `-clang-tidy-warnings-as-errors` wasn't exposed but now I understand. I agree that it wouldn't be the best way forward to expose every clang-tidy option as a clangd flag.
