### ISSUE TITLE
clangd configuration in YAML cannot specify format-style for clang-tidy

### ISSUE THREAD

**Issue by Wongboo** [clangd/clangd#874]
**Clangd** configuration in **YAML** cannot specify format-style for clang-tidy, the possible options are add, remove and checkoptions, of course, one can get these option by
```
 clang-tidy --format-style=llvm --dump-config
```
But the transition from these config to **config.yaml** is very complicated

**Comment by HighCommander4** [comment]
Note that clangd does respect `.clang-tidy` files as well, so you could specify the format-style there.

**Comment by Wongboo** [comment]
Sorry, my problem
