### ISSUE TITLE
Parse makefile variables for -I or /I paths

### ISSUE THREAD

**Issue by awsdert** [clangd/clangd#875]
So I have this in my GNUmakfile:

```
CLONED?=..
CGLM_DIR?=$(CLONED)/cglm
CGLM_INC_DIR?=$(CGLM_DIR)/include
CGLM_LIB_DIR?=$(CGLM_DIR)/lib

IFLAGS:=-I "$(CGLM_INC_DIR)"
```
Surely it's possible for clangd to do quick scan of variables and rules to find anything that looks like direction to an include directory, even if the resulting support is imperfect to start with it would at least silence the error "header not found", wether or not it points to the right header is another question but that's still preferable to "not found"

**Comment by kirillbobyrev** [comment]
This seems rather complicated and error-prone. Why not use [Bear](https://github.com/rizsotto/Bear) to generate the `compile_commands.json` (or `clangd.yaml` or even `compile_flags.txt`)? This would eliminate the problems of clangd being imprecise and not understanding the code correctly.

**Comment by awsdert** [comment]
Because I'm not trying to send compile commands to clangd, I'm just using it as an extension to "Code - OSS" (really poor name for uniqueness if you ask me), for switching mode I'm trying to rely on the "Makefile Tools" extension (although I find that one equally lacking but hey ho). Perhaps you could get those "Bear" developers to convert their makefile analysis code into libbear or something which you could then outsource the analysis process to, you'd only have to provide an option to switch from auto detection to manual declaration of options/defines to apply prior to the analysis process, then hunt through the list of commands libbear gives to identify the -I or /I expeced, that should result in the correct headers being used.

**Comment by kirillbobyrev** [comment]
`compile_commands.json` is the way clangd (and most other Clang tools, e.g. Clang-Tidy) understands projects. Truly "understanding" Makefiles it is really hard and is sadly out of scope for the clangd project.

In order for clangd to work correctly, it should have the right directives, please see [documentation](https://clangd.llvm.org/installation#project-setup) for more information. I can agree that `compile_commands.json` is not the most convenient format but there are enough tools to make its generation easy and painless.
