### ISSUE TITLE
Impossible to go to definition of anonymous struct/union member

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#877]
Consider this code:
```
struct S {
    struct { int number; };
    int func() { return number; }
};
```
If you do textDocument/definition on the reference to number inside func(), the returned location is the one of the inner struct, rather than the member inside it.

Output of `clangd --version`:
clangd version 14.0.0 (https://github.com/llvm/llvm-project.git 5685eb950da7c6901c8b264a3c93e8ea63b34d3d)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu

**Comment by ckandeler** [comment]
I can confirm that the linked patch fixes my issue.

**Comment by kadircet** [comment]
This has landed upstream as https://github.com/llvm/llvm-project/commit/512aa8485010009f6ec1b8d9deea3effe67e0106.
