### ISSUE TITLE
How to disable the warning of "modernize-use-trailing-return-type"?

### ISSUE THREAD

**Issue by jievince** [clangd/clangd#884]
I use vscode-clangd, and I don't need this check.

**Comment by HighCommander4** [comment]
Please see https://clangd.llvm.org/config.html#clangtidy

**Comment by jievince** [comment]
Hi @HighCommander4 , I can't find the clang tidy's configuration file, I use the vscode's remote which is linux, I haven't find the configuration file in `~/.config/clangd/config.yaml`.

**Comment by HighCommander4** [comment]
The file doesn't exist until you create it. Note it's **clangd's** configuration file, which allows specifying clang-tidy checks to disable, among other things you can configure.

(clang-tidy has its own configuration file called `.clang-tidy`, see https://clang.llvm.org/extra/clang-tidy/. That's an alternative way to disable specific checks, that would apply to standalone invocations of clang-tidy as well as clangd.)

**Comment by jievince** [comment]
Hi, I created a ~/.clang-tidy file, its content is:
```
Checks: '*,-bugprone-signed-char-misuse,-cert-dcl21-cpp,-cert-err58-cpp,-cert-err60-cpp,-cppcoreguidelines-avoid-c-arrays,-cppcoreguidelines-avoid-magic-numbers,-cppcoreguidelines-macro-usage,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-type-reinterpret-cast,-fuchsia-*,-google-runtime-references,-hicpp-avoid-c-arrays,-hicpp-no-array-decay,-hicpp-vararg,-modernize-avoid-c-arrays,-modernize-use-trailing-return-type,-readability-implicit-bool-conversion,-readability-magic-numbers'
WarningsAsErrors: '*'
HeaderFilterRegex: '\/include\/'
AnalyzeTemporaryDtors: false
```
But it doesn't work, and I don't know why.
![image](https://user-images.githubusercontent.com/38901892/135787795-121eff41-fa4f-4a38-b6ad-0267fe7ff426.png)

**Comment by HighCommander4** [comment]
Some possible guesses:

 * There is a `.clang-tidy` file in your project directory which takes precedence, and enables the mentioned check?
 * Your project is not in the directory tree of your home directory, making `~/.clang-tidy` not apply?

The `.clang-tidy` files that apply to the source file are those found in the directory containing the source file, and its ancestor directories, with directories "closer to" the file taking precedence.

**Comment by jievince** [comment]
Hi,  the guess one is true for me, thank you very much!

**Comment by GitMensch** [comment]
I have a similar issue with project based configuration, `.clangd` in the project root is documented - but seems to not apply.
I have the following UTF8-encoded text file in the project root - directly next to compile-commands.json, which are applied:

```text
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    CheckOptions:
      readability-misleading-indentation: false
      readability-identifier-naming.VariableCase: lower_case
```

I'm using `llvm-vs-code-extensions.vscode-clangd` 0.1.12, with `Ubuntu clangd version 14.0.0-1ubuntu1`.

Any idea how to get this working?


Side note: Ideally I'd like to have `readability-misleading-indentation` working, but it stumbles over newlines which I guess fails under "need consistent whitespace to work correctly".

**Comment by HighCommander4** [comment]
@GitMensch `CheckOptions` is only for specifying options specific to a check (like `readability-identifier-naming.VariableCase`), not for disabling checks. To disable `readability-misleading-indentation`, try:

```
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Remove: readability-misleading-indentation
    CheckOptions:
      readability-identifier-naming.VariableCase: lower_case
```
