### ISSUE TITLE
clangd can't access variables defined outside of the current file. 

### ISSUE THREAD

**Issue by polarbub** [clangd/clangd#885]
Take this for example. This is the main file: https://pastebin.com/ScG2FpsV and this is the header: `foo = 2;`. clangd can't find the foo in the includee file (the pastebin link). 

I have my `compile_commands.json` in the root directory of my project. It can be seen here https://pastebin.com/pjf1kJyc

**Logs**
https://pastebin.com/32FnMSwh

That has verbose mode on.

**System information & OS**

NeoFetch:
https://pastebin.com/0nY9x339

Output of `clangd --version`: `clangd version 12.0.1`

Editor/LSP plugin: VS Code

**Comment by HighCommander4** [comment]
This is a known issue, see #45.

A file included at non-global scope is by definition not self-contained.
