### ISSUE TITLE
InsertTextFormat of completions is always "Snippet", even if it's not actually one

### ISSUE THREAD

**Issue by tom-anders** [clangd/clangd#894]
When enabling snippets via the client capabilities, all suggested CompletionItems will have their InsertTextFormat set to "Snippet", even if they aren't actually a snippet.

This seems to be hardcoded in [`CodeCompletion::render`](https://searchfox.org/llvm/source/clang-tools-extra/clangd/CodeComplete.cpp#2006). Maybe it would make sense to take the `kind` into account here? For example, CompletionItemKind::Field should never actually contain a snippet, right?

**Comment by HighCommander4** [comment]
I think functionally it shouldn't matter, as I don't think there's any reason a plain-text completion proposal would contain meta-characters like `$` that have a meaning for snippets. (But maybe I'm overlooking something?)

The behaviour seems to date back to [this change](https://reviews.llvm.org/D41450) (with [this review comment](https://reviews.llvm.org/D41450?id=127718#inline-362127) being relevant).

**Comment by tom-anders** [comment]
So the problem is that nvim-cmp (completion engine for neovim's builtin LSP) does not support dot-repeat when the inserted item is a snippet: https://github.com/hrsh7th/nvim-cmp/issues/338. This could surely be improved on the plugin side, but I figured that clangd technically also could be a bit more precise when setting the InsertTextFormat.

**Comment by HighCommander4** [comment]
Ah, I see. In that case, yeah, I think it would be fine to make the InsertTextFormat sent by clangd more precise.

**Comment by sam-mccall** [comment]
https://github.com/llvm/llvm-project/commit/4fb62e138398263dbefaa499c712929562bdf3bd should cover the common case. It's possible we sometimes generate a nonempty but plaintext-compatible SnippetSuffix, but I can't think of such a case.

**Comment by tom-anders** [comment]
Just wanted to say that this works perfectly now, thanks for you work!
