### ISSUE TITLE
How can I set the code style of snippet complete

### ISSUE THREAD

**Issue by stillwuyan** [clangd/clangd#895]
I used clangd as the backend of lsp-mode (emacs), in c++ language when I type "if", the code style of snippet complete is as below:
```
if (condition) {                                                                                                                                                                       
    statements                                                                                                                                                                         
}
```
I want to change the code style to this (curly brackets in new line):
```
if (condition)
{                                                                                                                                                                       
    statements                                                                                                                                                                         
}
```
I have tried "--fallback-style={BasedOnStyle: GNU, UseTab: Always}", but it didn't work.
Is there any method that could achieve this? 
Thanks in advance.

**Comment by kadircet** [comment]
Unfortunately we don't support formatting of code completion suggestions. As there are usually a huge amount of completion suggestions and formatting them eagerly would result in a lot of latency.

You can try functionality like format on type/save, not sure what kind of functionality lsp-mode supports.

**Comment by pengjianaixue** [comment]
I also need this feature, Is already support in the latest release version?

**Comment by HighCommander4** [comment]
> I also need this feature, Is already support in the latest release version?

This has not been implemented, but I think it's a valid request. We have #1235 open which is very similar, maybe we can use that issue to track it.
