### ISSUE TITLE
Support for proprietary ARM compiler system headers

### ISSUE THREAD

**Issue by aelray** [clangd/clangd#911]
We are using the ARM compiler v6 for a Cortex-M build. Clangd fails in querying the compiler for the correct system headers beacuse of license issues. It fails with:

```
System include extraction: driver execution failed with return code: 1. Args: ['/opt/armclang/bin/armclang', '-E', '-x', 'c++-header', '-', '-v']
```
according to the VSCode logs.

Our license is restricted to a certain type of Cortex-M processor such that the compiler won't tell you anything useful if you don't query it with something like:

```
-mcpu=cortex-m*
```
where the asterisk denotes the processor type.

**Comment by Eplankton** [comment]
> 成功了，非常感谢！

Sorry, I have met similarly problem under Windows using armclang(integrated in Keil), and I wonder whether you have seen such thing as `not found __config_site` ? It happens because clangd can't recognize the `__ARMCOMPILER_VERSION` macro.

**Comment by Eplankton** [comment]
> That worked, thank you very much!

Sorry, I ran into a similar problem using armclang (integrated in Keil) under Windows, I wonder if you have seen such an issue. `not found __config_site`? This happens because clangd doesn't recognize the `__ARMCOMPILER_VERSION` macro.

**Comment by FlyyingPiggy2020** [comment]
> > That worked, thank you very much!
> 
> Sorry, I ran into a similar problem using armclang (integrated in Keil) under Windows, I wonder if you have seen such an issue. `not found __config_site`? This happens because clangd doesn't recognize the `__ARMCOMPILER_VERSION` macro.

i have same problem , do you fix it?

**Comment by Eplankton** [comment]
> > > That worked, thank you very much!
> > 
> > 
> > Sorry, I ran into a similar problem using armclang (integrated in Keil) under Windows, I wonder if you have seen such an issue. `not found __config_site`? This happens because clangd doesn't recognize the `__ARMCOMPILER_VERSION` macro.
> 
> i have same problem , do you fix it?

We have moved to arm-gcc-toolchains and problems solved, but still not for keil mdk6's compiler.

**Comment by FlyyingPiggy2020** [comment]
> > > > That worked, thank you very much!
> > > 
> > > 
> > > Sorry, I ran into a similar problem using armclang (integrated in Keil) under Windows, I wonder if you have seen such an issue. `not found __config_site`? This happens because clangd doesn't recognize the `__ARMCOMPILER_VERSION` macro.
> > 
> > 
> > i have same problem , do you fix it?
> 
> We have moved to arm-gcc-toolchains and problems solved, but still not for keil mdk6's compiler.

I solved the problem by using a .clang file like the one below:
```
CompileFlags:
  Add: 
    - -IC:\\Keil_v5\\ARM\\ARMCLANG\\include
    - -D__ARMCC_VERSION=6010050 
```
However, this is not universal. I have to manually enter `__ARMCC_VERSION`
