### ISSUE TITLE
will clangd reindex incrementally or entirely when we add a new cpp file?

### ISSUE THREAD

**Issue by tarik-jin** [clangd/clangd#913]
not a feature request, just want to know what we need to do properly when we add a new cpp file into a large project with compile_commands.json file has been generated before.

**Comment by tarik-jin** [comment]
try in local environment and it seems that clangd will process new-added file with similar compile options like other files?

**Comment by HighCommander4** [comment]
Yes, if a file is missing a compile command, clangd will infer one from a command of a nearby file.

However, the file will not be indexed (so, for example, new symbols it introduces will not show up in `workspace/symbol` search).

So, at some point, you'll want to re-generate the compile_commands.json to include the new file. Clangd should know to reindex only the new file.
