### ISSUE TITLE
clangd hangs when building AST of nested macro

### ISSUE THREAD

**Issue by 9tin9tin9** [clangd/clangd#917]
Problem: clangs hangs at building AST when expanding nested macro

code: https://gist.github.com/9tin9tin9/8145049d78d8c8dacba88fccc4941bc1
log: https://gist.github.com/9tin9tin9/0099bdb6d2261956bf0a9889e167596e
system information: Macbook Pro 2017; MacOS Big Sur 11.5.2

**Comment by sam-mccall** [comment]
Hmm, I can't reproduce this hang, though clangd --check does take 40 seconds for "testing features at each token".

Would you be able to check if this still hangs with a recent build e.g. https://github.com/clangd/clangd/releases/tag/snapshot_20211031 ?

**Comment by 9tin9tin9** [comment]
It took 6 mins for it to kill itself on the original version 13.0.0
log: https://gist.github.com/9tin9tin9/9be0f22e1dced26a2b92bdec91d2289d

And using the build you gave me
log: https://gist.github.com/9tin9tin9/1166d168372b782810a4bb2334c7a146
took 6 mins for it to kill itself again.

**Comment by kadircet** [comment]
I think the main issue here is the memory usage. It uses about 14GB memory at its peak. Running clang on the same code only consumes about 80MB. Sending out a patch which brings down peak memory usage down to ~60MB.
