### ISSUE TITLE
How can I disable auto-includes on completion?

### ISSUE THREAD

**Issue by cerevra** [clangd/clangd#918]
Hi

https://github.com/clangd/vscode-clangd#include-management
>Code completion works across your codebase and adds #include directives where needed

Code completion adds too many includes. How can I disable adding includes on using completion?

Thank you

UPD: Steps
1. Insert `fo`
2. Press `Enter`

Actual behaviour:
  * `fo` was replaced with `foo`
  * `#include "foo.h"` was added

Actual behaviour:
  * `fo` was replaced with `foo`

**Comment by kirillbobyrev** [comment]
> Actual behaviour:
> - fo was replaced with foo
> - #include "foo.h" was added
>
> Actual behaviour:
> - fo was replaced with foo

Did you mean **desired behaviour** in the second case?

To disable the header insertion, pass `--header-insertion=never` (default is `iwyu`) to clangd.

Either way, we're interested why you don't find this feature useful: is it adding the includes that are actually not used or is it just a matter of the code style in your codebase? If it is, do you use umbrella headers instead or is there any other reason to not include the used headers directly?

**Comment by kirillbobyrev** [comment]
Oh, and since you're using the VSCode extension, the way to pass flags is putting the following into `settings.json`:

```json
  "clangd.arguments": [
    "--header-insertion=never"
  ],
```

**Comment by cerevra** [comment]
>Did you mean desired behaviour in the second case?

Yes, my bad. Excuse me please.

>is it adding the includes that are actually not used

No, all of them are actually used.

>is it just a matter of the code style in your codebase?

Probably it is right description.
1. sometimes feature includes "something_fwd.h" files - in this cases common header is required
2. always feature includes header,  which already was included from other included header - i.e., for string. It is not our style
3. feature adds `#include "....h"` but codestyle requires `#include <....h>` - from project root

-----------------------
`--header-insertion=never` helped a lot. Thank you very much
