### ISSUE TITLE
Building in containers: Path mappings to host directories

### ISSUE THREAD

**Issue by wosrediinanatour** [clangd/clangd#920]
Let's assume a build system that starts CMAKE in a container (Podman, Docker), where the produced compiler_commands.json contains absolute paths in the container.

It would be good to be able to use cland & compile_commands.json on the host, i.e the paths are mapped to the host file system.

**Comment by kirillbobyrev** [comment]
Could you please give more information on why you want this? Building `compile_commands.json` should be really fast and is probably not the bottleneck most of the times. I can understand if you're building an index for a really large project on a different machine, and we have some path translation handling for the [remote index](https://clangd.llvm.org/design/remote-index) feature at the moment, but why is it important to transfer the `compile_commands.json`? And wouldn't simple textual replacement work in your case? After all, `compile_commands.json` is just a text file, you can just use `sed` to replace absolute paths in the container with the absolute paths in your system.

**Comment by wosrediinanatour** [comment]
I cannot produce  `compile_commands.json` on the host, since I don't now the compiler flags/parameters.  Building the file can be done e.g. by CMAKE during each build. If you build in a container (source directory mounted), then the `compile_commands.json` is produced containing  container paths.

My approach is to not install any addional software on top of a given build container, so that such a container can be used as is.

I could use `sed` after each build manually on the host. But it would more comfortable, if this would be done by `clangd` automatically. I am using VIM with [VIM-ALE](https://github.com/dense-analysis/ale), which could start `clangd` and use it. But the paths don't match, so I cannot use `clangd`.

**Comment by kirillbobyrev** [comment]
> I cannot produce `compile_commands.json` on the host, since I don't now the compiler flags/parameters. Building the file can be done e.g. by CMAKE during each build. If you build in a container (source directory mounted), then the `compile_commands.json` is produced containing container paths.

If that's the only problem, I think you can always dump the CMake variables to reproduce the same build on the host.

> My approach is to not install any addional software on top of a given build container, so that such a container can be used as is.
> 
> I could use `sed` after each build manually on the host. But it would more comfortable, if this would be done by `clangd` automatically. I am using VIM with [VIM-ALE](https://github.com/dense-analysis/ale), which could start `clangd` and use it. But the paths don't match, so I cannot use `clangd`.

You can probably just use `sed` + [`watchman`](https://facebook.github.io/watchman/) to do the path replacement automatically every time the `compile_commands.json` changes.

Overall, I think it's a really rare use-case and (to my understanding) can be easily fixed with few lines of scripts (if you disagree, please let me know), so I'm not sure there would be a lot of value to many users in adding it _within_ clangd.

@sam-mccall @kadircet might have other opinions, please reopen the issue if you do!

**Comment by wosrediinanatour** [comment]
You are right - thx for your input.

**Comment by kadircet** [comment]
we've got a solution if you run `clangd` inside the docker container too. you can read details in https://lists.llvm.org/pipermail/clangd-dev/2019-January/000231.html and https://reviews.llvm.org/D64305. We should probably better document this feature :(

**Comment by wosrediinanatour** [comment]
Thank you for the links! 

I had thought running cland in the container, but that may be a problem, if clangd&dependencies  can't be easily installed.
Anyway. It is also a good solution in some cases.
