### ISSUE TITLE
--function-arg-placeholders should also influence macros

### ISSUE THREAD

**Issue by Lyude** [clangd/clangd#922]
Hi! I've been using clangd for a while and recently switched over to neovim's built-in LSP support, in doing so I noticed that clangd would automatically insert the names of function arguments when completing functions. Unfortunately this feature is honestly very painful to have enabled in my setup. If anything I would **much** rather just have signature help displayed above where I'm typing so I don't have to switch input modes multiple times.

Anyway: So I've been trying to turn it off, since other completion tools like rust-analyzer seem to support such functionality. I eventually found `--function-arg-placeholders`, but then discovered that this only seems to affect completion for function calls and not function-like macros.

I'd like to propose that:

* This feature be moved out of hidden options, it's not entirely clear to me why it's hidden there in the first place and I'm hoping there isn't a reason for this…
* This feature be expanded to apply to any kind of construct where argument placeholders apply, such as with macro-like function calls

**Comment by Lyude** [comment]
Almost forgot to mention, I'm using clangd version 12.0.1 (Fedora 12.0.1-1.fc34) with nvim-cmp and nvim-lspconfig, along with nvim v0.5.1

**Comment by sam-mccall** [comment]
> If anything I would much rather just have signature help displayed above where I'm typing so I don't have to switch input modes multiple times

Yeah, placeholders and signature help are somewhat redundant, this request makes sense and in fact I think we have a (private) frontend that disables placeholder snippets for this reason.

(There are some annoyances, like if completion needs to insert a header to make the function visible, signature help may not be immediately available)

I think it makes sense to unhide this option, maybe even by default when the client indicates signature help support.

@kadircet thoughts?

> other completion tools like rust-analyzer seem to support such functionality

This is good to know - out of curiosity, what do they call this option?

> but then discovered that this only seems to affect completion for function calls and not function-like macros

This is a simple bug that can be fix (we list Function/Method in `summarizeSnippet`)

**Comment by kadircet** [comment]
> I think it makes sense to unhide this option.

Agree with this one.

> maybe even by default when the client indicates signature help support.

This feels a little bit more involved. I can't say that I've coded in a setup with snippets support before but having them or not changes the UX a lot, e.g. people can jump back and forth between params easily. Also in my opinion in an "ideal" client this should not interfere with signature help, hence I'd rather not touch the default.

**Comment by sam-mccall** [comment]
Oops, linked that commit to the wrong bug...

**Comment by Lyude** [comment]
> > other completion tools like rust-analyzer seem to support such functionality
> 
> This is good to know - out of curiosity, what do they call this option?

`rust-analyzer.completion.addCallArgumentSnippets`

> 
> > but then discovered that this only seems to affect completion for function calls and not function-like macros
> 
> This is a simple bug that can be fix (we list Function/Method in `summarizeSnippet`)

woo! Thanks for looking into this :)
