### ISSUE TITLE
False positive in include-cleaner

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#934]
With both clangd and sources from llvm main (5fedbd5b181523541331eee3008467a39f0334cb)

XRefs.cpp marks `llvm/ADT/ScopeExit` as unused. However `llvm::make_scope_exit` is called around line 1000.

**Comment by kirillbobyrev** [comment]
Minimal reproducer:

```c++
template <typename T> void ^foo(T &&F) {}
template <typename T> void bar() { foo([] {}); }
```

**Comment by sam-mccall** [comment]
Thanks. I guess there are at least two related cases here:
- we haven't picked a candidate because overload resolution is delayed
- we can't find the "right" candidate yet because it's only available via ADL

The latter is harder to deal with.
(The original example had a qualified name, and the reduced one is unqualified, so they're not quite identical but still fine)

**Comment by sam-mccall** [comment]
I'm guessing the original case can be fixed by handling OverloadExpr and iterating over the decks

**Comment by kirillbobyrev** [comment]
Based on the AST built from that code, it seems to be the latter (ADL):

```
UnresolvedLookupExpr 0xf467a0 <col:3> '<overloaded function type>' lvalue (ADL) = 'foo' 0xf46410
```

I'll investigate further.

**Comment by kirillbobyrev** [comment]
Oh, nvm, I didn't understand your comment correctly. It looks to be the first case. [D114287](https://reviews.llvm.org/D114287) is out for review.
