### ISSUE TITLE
Too many incorrect error feedbacks from the LSP

### ISSUE THREAD

**Issue by BooleanCube** [clangd/clangd#938]
For basically any C++ file I edit in neovim now, it shows me random useless errors (shown down below), could I write a config script to ignore such errors or is there sometime actually wrong with the code. The code executes and runs perfectly btw. I don't understand these errors but I can't seem to get rid of them either and don't seem to impose any actual bug in the code because it runs just fine.

![image](https://user-images.githubusercontent.com/47650058/143789322-621cf236-d60b-4da5-b271-8aef3ba15ba9.png)
![image](https://user-images.githubusercontent.com/47650058/143789327-73568784-2f18-416f-bf9c-27275721f889.png)
![image](https://user-images.githubusercontent.com/47650058/143789336-df27f47d-b204-4a8c-bd14-b10cabfeb7ca.png)

**Logs**
![image](https://user-images.githubusercontent.com/47650058/143789391-4c69995b-11c3-415a-8177-db4edc26213e.png)

**System information**
clangd version: 13.0.0 (latest)
clangd extension version: 0.17.0
![image](https://user-images.githubusercontent.com/47650058/143789537-118f1b91-aecc-4e1b-b76b-d86e32e60358.png)
Operating system: Windows 10

**Comment by kirillbobyrev** [comment]
The LSP errors do not seem incorrect: clangd can not find `bits/stdc++.h`. The reason is that it isn't in your default search path and it isn't a system library clangd knows about. The clangd installation consists of two things: a binary and Standard Library headers that will be used by default.

I'm guessing you are compiling with MinGW, is that correct? The way to solve the problem you described is to tell clangd where to find `bits/stdc++.h`. Could you try compiling the file with verbose output `g++ -v file.cpp` (or something similar) for the file and show the output?

The lines I'm looking for are looking like this:

```
#include <...> search starts here:
 /usr/include/c++/10
 /usr/include/x86_64-linux-gnu/c++/10
 ...
End of search list.
```

What you want to locate is the directory with `bits/stdc++.h`. See which of the printed directories actually has the header you want and add it to clangd search path.

In my case (Debian), this would be `/usr/include/x86_64-linux-gnu/c++/10/bits/stdc++.h"` and the [clangd config file](https://clangd.llvm.org/config.html) would look like this

```yaml
CompileFlags:
  Add: [-I=/usr/include/x86_64-linux-gnu/c++/10/]
```

Please let me know if this works for you.

**Comment by HighCommander4** [comment]
See also [this entry in on troubleshooting page](https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc) which described as approach (using `--query-driver`) for clangd to discover the compiler's built-in include paths automatically.

**Comment by BooleanCube** [comment]
> The LSP errors do not seem incorrect: clangd can not find `bits/stdc++.h`. The reason is that it isn't in your default search path and it isn't a system library clangd knows about. The clangd installation consists of two things: a binary and Standard Library headers that will be used by default. This is the system headers clangd will "know" about by default. `bits/stdc++.h` isn't one of them because it's a GNU C++ header, not a Standard Library header that is somehow defined by the ISO.
> 
> I'm guessing you are compiling with MinGW, is that correct? The way to solve the problem you described is to tell clangd where to find `bits/stdc++.h`. Could you try compiling the file with verbose output `g++ -v file.cpp` (or something similar) for the file and show the output?
> 
> The lines I'm looking for are looking like this:
> 
> ```
> #include <...> search starts here:
>  /usr/include/c++/10
>  /usr/include/x86_64-linux-gnu/c++/10
>  ...
> End of search list.
> ```
> 
> What you want to locate is the directory with `bits/stdc++.h`. See which of the printed directories actually have the header you want and add it to clangd search path.
> 
> In my case (Debian), this would be `/usr/include/x86_64-linux-gnu/c++/10/bits/stdc++.h"` and the [clangd config file](https://clangd.llvm.org/config.html) would look like this
> 
> ```yaml
> CompileFlags:
>   Add: [-I=/usr/include/x86_64-linux-gnu/c++/10/]
> ```
> 
> Please let me know if this works for you.

Yea, I am using MinGW to compile the C++ files and I tried doing what you said, however I still get the same error of it not being able to find the library.

This is what I got from the verbose output:
![image](https://user-images.githubusercontent.com/47650058/143958841-8f8cef3c-5358-428d-9ac8-7b7ee0a4c95b.png)

This was the file directory it was in:
![image](https://user-images.githubusercontent.com/47650058/143959303-8d5edfef-6afd-47b0-b449-9cdae7c626b5.png)

This was the config.yaml file I configured:
![image](https://user-images.githubusercontent.com/47650058/143959737-8fc31833-82a4-4141-be8a-8efab2da6531.png)

**Comment by kirillbobyrev** [comment]
Oops, sorry, I think the `-I=/path/` is prohibited by clang and should be `-I/path/` (I'm always confused by this), please try without it, i.e.

```yaml
CompileFlags:
  Add: [-IC:Tools/...]
```

**Comment by kadircet** [comment]
As described throughout the issue, this is mostly a configuration problem. I recommend you also take a look at https://clangd.llvm.org/guides/system-headers, especially the bit around having `--target=x86_64-w64-mingw32` in compile flags has been the resolution for such issues in the past.

**Comment by BooleanCube** [comment]
> Oops, sorry, I think the `-I=/path/` is prohibited by clang and should be `-I/path/` (I'm always confused by this), please try without it, i.e.
> 
> ```yaml
> CompileFlags:
>   Add: [-IC:Tools/...]
> ```

Interestingly enough, changing the directory to `[-I/Tools/path.../]` changed something, but now it gives me another different error that goes along the lines of `In included file: 'cassert' file not found - [clang: pp_file_not_found]`.
![image](https://user-images.githubusercontent.com/47650058/144170145-a7a7d7b6-7e62-4372-83b0-0cd67c71a202.png)

**Comment by kirillbobyrev** [comment]
Hm, this is interesting because at least that one should exist in the default search path. But as @kadircet and @HighCommander4 mentioned, there is more generic way of locating mingw headers, please follow their advice.

**Comment by BooleanCube** [comment]
I see somebody, suggested the `--query-driver` method but I am confused as to where I am supposed to pass this in? After the addition of the compile flags?
I am kinda lost on what I have to do so I tried putting it after a command line statement in a last ditch attempt because the [troubleshooting page](https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc) linked by @HighCommander4 doesn't specify.
![image](https://user-images.githubusercontent.com/47650058/144330952-10cc6947-be5b-486a-8b0e-3f302d92b98e.png)

I already have tried following along with the [System Headers page](https://clangd.llvm.org/guides/system-headers) that @kadircet linked and it didn't seem to work. I tried configuring the clangd configuration file accordingly above but I still get very weird errors about it not being able to find 'cassert'. There are other such methods to add the headers in the compile flags such as the compile_flags.txt or compile_commands.json files, but it doesn't specify where the files are supposed to be located either. I have located where the mingw headers are but the instructions are somewhat vague.

We can all see that it has read the configuration file when I run the `:CocCommand workspace.showOutput` command in neovim:
![image](https://user-images.githubusercontent.com/47650058/144332976-d6efabfc-a40e-4730-8403-0b0d99f3623a.png)
but we still see the error:
![image](https://user-images.githubusercontent.com/47650058/144333122-8f90bc7c-8bba-42b5-b0db-3e152603035d.png)

**Comment by HighCommander4** [comment]
`--query-driver` is a command-line argument of clangd itself. The place where it's specified depends on the editor; for vscode, it's added to "clangd.arguments" in settings.json; not sure about vim.

The value of `--query-driver` should be the path to the compiler as it appears at the beginning of the compile commands in `compile_commands.json` (or a regex that accepts this path). This tells clangd to query that compiler executable for built-in includes.

If you don't have a `compile_commands.json`, the first step is to create one using one of the methods described in the [Getting started](https://clangd.llvm.org/installation#project-setup) documentation.

**Comment by BooleanCube** [comment]
**UPDATE:**
I found the cassert file they were referencing in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++`
and there was also a bits/ folder in that directory. So all I did at first was copy the stdc++.h file from `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32/bits/` and pasted it in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/bits`. I thought that would fix it but apparently not, it asked for some other file like `bits/c++config.h` which I was able to find in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32/bits/` so now I copied and pasted all of the files in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/mingw32/bits/` to `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/bits/`. Now, that all the headers are accessible, I thought it would work right? No. It is now asking for some unknown file which I can't find called `assert.h` instead of `cassert` like before. I was able to find a `debug/assertions.h` in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++/debug/` but I don't believe that is the correct one. However, it looks like it is able to locate and parse the <bits/stdc++.h> header now and I no longer receive related bugs, however I still do receive other weird bugs which I assume is caused by the absence of an `asssert.h` file in `Tools/MinGW/lib/gcc/mingw32/6.3.0/include/c++`.

Is there supposed to be a directory where clangd has their own headers that I can add to the compile flags instead because it seems my mingw compiler is missing some vital headers.

I also thought that fixing the location of the `<bits/stdc++.h>` header would allow me to be able to get intellisense from the server but it seems I don't get the full intellisense even though I get code completion and some intellisense: 
![image](https://user-images.githubusercontent.com/47650058/144335009-2f8bdfc6-2492-4144-b7f3-5ae441a55613.png)
![image](https://user-images.githubusercontent.com/47650058/144334937-5535089a-e991-477e-85f2-9cd9bf51da18.png)

This is an example of the jdtls server intellisense on a java file: 
![image](https://user-images.githubusercontent.com/47650058/144335300-0b09359d-13f7-404d-8892-a8b787a62844.png)
![image](https://user-images.githubusercontent.com/47650058/144335474-d496cdb7-ad1b-4671-aac2-15defcf25069.png)
does clangd do something similar with C++ files because I have never seen clangd work like this before so I just want to make sure clangd can do this too right?

**Comment by livrth** [comment]
Is there any progress towards a solution to this issue? I'm a macOS user also having this problem.

**Comment by HighCommander4** [comment]
> Is there any progress towards a solution to this issue? I'm a macOS user also having this problem.

Please have a look at https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc, and if you're not able to resolve your issue by following the suggestions there (particularly, using `--query-driver`), then open a new issue and attach [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs).
