### ISSUE TITLE
Clangd should use "rootUri" and "workspaceFolders" in LSP specification as its workspace

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#94]
Currently workspace is inferred from the containing CDB.

**Comment by sam-mccall** [comment]
Can you describe what problem you're trying to solve?

**Comment by lh123** [comment]
Currently, clang creates a ".clangd" folder based on the path of the CDB, but I want it to be created in the folder pointed to by rootUri.
eg: When complile_commands.json is located in the build folder, the ".clangd" folder is also located in the build folder.

**Comment by kadircet** [comment]
background-index shards are tightly coupled with the compile_commands.json that generated them, hence it makes sense for them to be cached on a location based on that. Moreover rootUri/workspaceFolders are not information that's provided by all the editors nor some information that we can base most of our assumptions on (e.g. do we re-index the project every time user opens up a different directory?). Also the location of the shards nor the contents are an implementation detail of clangd and should not be of importance to the user (apart from eating their disk space). Hence closing this as won't fix.

We definitely have some requests around customizing the location of index shards though. It might make sense to have an option to customize that instead. Feel free to pile up on one of the threads having such a request if you think that'll be useful for you.

**Comment by HighCommander4** [comment]
Note, there is some discussion of a "strong workspace mode" in https://github.com/clangd/clangd/discussions/907#discussioncomment-1540740 which I think could be quite useful for editors that opt into it.
