### ISSUE TITLE
Allow custom clangd cache location

### ISSUE THREAD

**Issue by Yanpas** [clangd/clangd#946]
I have a small home directory (1gb), and all my development takes place in /nfs/user/. I'd rather have a cache inside my project directory.

**System information**

Output of `clangd --version`: 12

Editor/LSP plugin:

Operating system: rhel7

**Comment by sam-mccall** [comment]
Your project cache should be stored next to compile_commands.json, but files outside any project's scope are indeed indexed in a central location.

If you set `$XDG_CACHE_HOME` clangd will store its central cache under that path instead of ~/.config.
