### ISSUE TITLE
Can't make code completion for the methods of class fields when developing chromium.

### ISSUE THREAD

**Issue by XiangQingW** [clangd/clangd#948]
Can't make code completion for the methods of class fields when developing chromium.

But it's right to make code completion for the methods of local variables, and it's also right to make code completion for the methods of class fields when developing a simple CMake-based project.

**Logs**
The verbose logs of code completion for the methods of a class field:
`
V[18:18:08.699] <<< {"id":76,"jsonrpc":"2.0","method":"textDocument/completion","params":{"context":{"triggerCharacter":".","triggerKind":2},"position":{"character":10,"line":46},"textDocument":{"uri":"file:///home/*****/message/dependencies.h"}}}`
`I[18:18:08.699] <-- textDocument/completion(76)`
`I[18:18:08.707] --> reply:textDocument/completion(76) 8 ms`
`V[18:18:08.707] >>> {"id":76,"jsonrpc":"2.0","result":{"isIncomplete":false,"items":[]}}`
[error_clangd.log](https://github.com/clangd/clangd/files/7692778/error_clangd.log)

The verbose logs of code completion for the methods of local variables:
`V[18:11:38.854] <<< {"id":176,"jsonrpc":"2.0","method":"textDocument/completion","params":{"context":{"triggerCharacter":".","triggerKind":2},"position":{"character":7,"line":75},"textDocument":{"uri":"file:///home/wxq/aha/aha/morpheus/message/dependencies.cc"}}}`
`I[18:11:38.854] <-- textDocument/completion(176)`
`I[18:11:38.881] --> reply:textDocument/completion(176) 26 ms`
`V[18:11:38.881] >>> {"id":176,"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[{"detail":"const ::entities::ChatConfig &","filterText":"chat_config","insertText":"chat_config()","insertTextFormat":2,"kind":2,"label":" chat_config() const","score":1.2384182214736938,"sortText":"40617b83chat_config","textEdit":{"newText":"chat_config()","range":{"end":{"character":7,"line":75},"start":{"character":7,"line":75}", "***other items***"]}}
`
[ok_clangd.log](https://github.com/clangd/clangd/files/7692817/ok_clangd.log)

**System information**
Linux XPS-8930 5.4.0-91-generic 102~18.04.1-Ubuntu 

Output of `clangd --version`:
clangd version 13.0.0 (GitHub - llvm/llvm-project: Th... d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
emac/lsp-mode

Operating system:
Linux

**Comment by sam-mccall** [comment]
There's not really enough information in the report or the logs to understand what's happening. If you can reduce it to a small example that would be helpful.

The one clue from the logs is there are lots of compile errors coming from inside the standard library, which sounds a lot like the compile command for the file isn't correct/working. Are there lots of diagnostics shown? Can you provide the output of `clangd --check=$YOUR_FILE`?

**Comment by XiangQingW** [comment]
@sam-mccall  Thanks for the hint. After I move the `lib/clang/13.0.0/include` to the correct directory, clangd works well.
