### ISSUE TITLE
Suggestion on Range-v3 error doesn't take into account the deprecation of ranges::view namespace

### ISSUE THREAD

**Issue by Aster89** [clangd/clangd#951]
In
```cpp
#include <range/v3/view/single.hpp>
auto xxx = ranges::single(3);
```
the second line is wrong, because `single` lives in `ranges::views`, but clangd suggests a wrong correction, `ranges::view`, which deprecated.

**Logs**

There's no error.

**System information**

Output of `clangd --version`: 13.0.0

Editor/LSP plugin: Vim+YCM

Operating system: Archlinux

**Comment by sam-mccall** [comment]
FWIW with latest ranges-v3 master your example yields `No member named 'single' in namespace 'ranges'; did you mean 'ranges::views::single'? (fix available)` for me.

It looks like the `view` namespace was renamed to `views` in 5b49299604, I don't see any evidence of deprecation.

In any case, these suggestions come from clang. If you want clang's typo correction to take deprecation into account and have a clear example, you'll want to file against llvm/llvm-project.

> Logs
> There's no error.

This is not helpful, you're complaining about a suggested correction, but haven't provided details about it. Those details are in the logs...

**Comment by Aster89** [comment]
> This is not helpful, you're complaining about a suggested correction, but haven't provided details about it. Those details are in the logs...

@sam-mccall , I've added clangd's stderr. Is it helpful?

> I don't see any evidence of deprecation.

The diagnostic I see after accepting the correction to `ranges::view::single` is
```
'view' is deprecated: The ranges::view namespace has been renamed to ranges::views. (Sorry!)  :95:15: note: 'view' has been explicitly marked deprecated here [-Wdeprecated-declarations]
```

**Comment by sam-mccall** [comment]
Thanks, the log helps (version info & indexes/flags) though -log=verbose would include the diagnostic details.

It turns out you're passing `-std=c++17` somehow (through YCM) which is critical.

This is definitely a clang issue, `clang -fsyntax-only -std=c++17 uffa.cpp` exhibits the same behavior.

I'm not very familiar with typo-correction, glancing at the code it looks like it looks for the name in all namespaces that have been seen, probably it could use some kind of preference order. This seems like a reasonable clang FR.

**Comment by Aster89** [comment]
By
> This seems like a reasonable clang FR

You mean, as earlier, I should file a bug report
> against llvm/llvm-project

right?

**Comment by HighCommander4** [comment]
Yep, the LLVM bug tracker was recently migrated from Bugzilla to Github, you can now file an issue directly on Github: https://github.com/llvm/llvm-project/issues
