### ISSUE TITLE
clangd warning - `expected expression`

### ISSUE THREAD

**Issue by erwin** [clangd/clangd#958]
I'm not very good with Marco's that represent functions, so please try to bear with me.

clangd is giving me an `expected expression` warning each time I try the following:

```c

#define TB_TRACE_MODULE_NAME "foo"
#   define tb_trace_i(fmt, arg ...)                 tb_trace_p(__tb_prefix__, fmt, ## arg)
#   define tb_trace_p(prefix, fmt, arg ...)                 do { tb_trace_done(prefix, TB_TRACE_MODULE_NAME, fmt __tb_newline__, ## arg); } while (0)
void       tb_trace_done(char const* prefix, char const* module, char const* format, ...);

int main () {
    tb_trace_i("hello `expected expression` warning...");
}
```

This code is from a fairly popular C library (3800 github stars) called tbox. It's a chinese cross-platform alternative to `glib`. The `tb_trace_i` function is implemented here:
[tb_trace_i function in prefix/trace.h](https://github.com/tboox/tbox/blob/master/src/tbox/prefix/trace.h)

I try to avoid my own Marco functions so probably introduced other problems here, but I tried to simplify to the above, and I still get the `Expected Expression` warning.

```c
#define TRACER(fmt, arg ...) do { trace_done(char const * module, char const * format, ...); } while (0)

int main () {
  TRACER("Example");
}
```

# Questions:

1. Is there an error in the code that's triggering the `expected expression` warning?

Or

2. Or is there a project wide way to disable this warning for any use of this function, without loosing other warnings?

**System information**

Output of `clangd --version`:

```
clangd --version
Ubuntu clangd version 13.0.0-2
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin:

I'm seeing this same error whether I run `clangd --check=...`, or in `neovim` or `vscode`.

Operating system:

I'm seeing this consistently both on Ubuntu 21.10 and Windows 11.

Thanks very much for taking the time to read through this! 
If you're able to provide any additional feedback, I of course will very much appreciate that!

Thank you!!!

**Comment by erwin** [comment]
I thought perhaps I could use something like:

```yaml
Diagnostics:
  ClangTidy:
    Remove: expected-expression
```

However, `clangd` reports this as an error rather than a warning... Strange as it runs fine on `cl` on win32/64, `clangd` on mac and `gcc` on Linux.

If anyone else has a workaround idea that would be appreciated too!

**Comment by sam-mccall** [comment]
The example from your report is broken: `__tb_prefix__` etc isn't defined anywhere. Similarly in the second snippet `trace_done` is not defined.
(I appreciate the effort to minimize the example, but I think in this case some important stuff got dropped)

I downloaded tbox and i get no warnings for this code:
```
#include <tbox.h>
int main () {
    tb_trace_i("hello `expected expression` warning...");
}
```

Can you specify exactly what version (commit) of tbox you have, and a snippet of code that you expect to work but gives errors?

> However, clangd reports this as an error rather than a warning

Yeah, this is a hard parse error. It can't be suppressed and other clangd features are not going to work very well if clang/clangd can't parse the code.

**Comment by erwin** [comment]
Thanks for looking into that Sam.

I'm just getting started with the `xmake` build tool that comes from the same author as `tbox`, and I was embedding the tbox dependency directly in my example project under `project/deps/tbox`, instead of just linking to the normal finished libraries and including the system installed headers.

I think that's part of where my error came from.

Hearing that it works for you was very helpful, and now I've got it working too!

My apologies for the time waste. I should have made a more complete and minimal example and posted in it's entirety... Mine was not complete enough, and not minimal enough. Sorry.

On a more upbeat note, thanks so much for your work on `clangd`! Combined with neovim it's my favorite development environment ever!

**Comment by sam-mccall** [comment]
No worries, I'm glad you got it working!
