### ISSUE TITLE
Clangd 12 doesn't seem to see headers in /usr/include

### ISSUE THREAD

**Issue by konradsa** [clangd/clangd#960]
Dev host was just upgraded to Redhat 8 from Redhat 7. Clangd 12 now doesn't seem to find anything in /usr/include anymore. For instance, get an error "sys/types.h file not found", which is located in /usr/include. This was working fine before on Redhat 7.

I added the query-driver directive, and I can see that some built-in paths are discovered, but /usr/include is not among them:
```
I[19:46:22.045] System includes extractor: successfully executed /opt/rh/gcc-toolset-10/root/usr/bin/gcc
	got includes: "/opt/rh/gcc-toolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10, /opt/rh/gcc-toolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/x86_64-redhat-linux, /opt/rh/gcc-toolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/backward, /opt/rh/gcc-toolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/include, /opt/rh/gcc-toolset-10/root/usr/include"
```

I tried to add "-isystem /usr/include" manually to all commands in the compile_commands.json, and then it seems to find the /usr/include headers, but then I run into this problem here: https://llvm.discourse.group/t/in-included-file-stdlib-h-file-not-found/1694/6. So that is not a solution either.

**Comment by sam-mccall** [comment]
Can you provide verbose logs for an example failure, with & without the query-driver option? 

Is this a release from this github repo, from llvm.org, or somewhere else?

It looks like your GCC is using a nonstandard sysroot and that's why query-driver didn't work. Can *gcc* find these headers?

Possible workaround might be `-isysroot/` if clangd has been compiled with weird options or env variables are set...

**Comment by konradsa** [comment]
I think I got the problem, your sysroot suggestion got me on the right path.

We are using bazel as our build system, it creates a symlink to the actual sysroot and passes it to gcc as as a --sysroot compile flag.

However, for some reason it doesn't pass the first directory in the path. So let's say our relative location of the sysroot from the build directory is x/y/z, bazel only passes --sysroot=y/z to gcc, and for some reason gcc seems to be okay with that. But that causes clangd not being able to find the sysroot.

After creating a .clangd config file in the build directory that does the following:
`CompileFlags:
  Remove: [--sysroot=y/z]
  Add: [--sysroot=x/y/z]`
clangd works now as expected.
