### ISSUE TITLE
clangd fails parsing file with gcc attribute

### ISSUE THREAD

**Issue by MiniSoda** [clangd/clangd#961]
clangd wrongfully complains that I should insert  a '{'  (Expected identifier or '{')

```c++
#pragma once

#include <string>

namespace platinum::lah
{
namespace __attribute__ ((visibility ("default"))) BoardIdDecoder
{
  std::string DecryptStringBoardIdentification(std::string const & strIn);
  std::string DecodeBoardIdentification(std::string const & strIn);
}
}
```
Everything will be fine after removing the gcc attribute.
I guess we don't filter out this gibberish for clang so clangd is complaining?

**Comment by HighCommander4** [comment]
It looks like the error has to do with the placement of the attribute. Clang accepts it if it's placed after the namespace name:

```c++
namespace BoardIdDecoder __attribute__ ((visibility ("default"))) 
```

**Comment by MiniSoda** [comment]
Thanks, it doesn't hurt to move the attribute to the rear in my case.
so I'll close this issue.
