### ISSUE TITLE
System header not found

### ISSUE THREAD

**Issue by nicolasmartin3d** [clangd/clangd#97]
Hello,
I am using clangd in Visual Studio code, via vscode-clangd extension.
I am on MacOsX, clangd is installed using macports, (port install clang-8.0)

It seems clangd is unable to find sytem include headers.
I basically run clangd with the following command line : 
`clangd -resource-dir=/opt/local/libexec/llvm8.0/lib/clang/8.0.0 -background-index -log=verbose`

This is the file I'm testing with :
```
#include <string>

int main(int argc, char* argv[]) {
}
```

This is my compile_commands.json :

 ```
[
{
  "directory": "/tmp/build",
  "command": "/opt/local/bin/clang++    -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/test.dir/test.cpp.o -c /tmp/test.cpp",
  "file": "/tmp/test.cpp"
}
]
```

This is an excerpt from the output I get :
```
V[20:10:00.226] Preamble for file /private/tmp/test.cpp cannot be reused. Attempting to rebuild it.
V[20:10:00.228] Ignored diagnostic. /tmp/test.cpp:1:10:'string' file not found
Skipping TU due to uncompilable errors
E[20:10:00.228] Indexing /tmp/test.cpp failed: IndexingAction failed: has uncompilable errors
```

Any ideas what could be wrong ?

**Comment by widgetii** [comment]
Had the same issue
Could you test your installation with simple compile_flags.txt file (temporary moving compile_commands.json somewhere else before tests)?

```sh
cc -E -x c++ - -v < /dev/null 2>&1 | \
    awk '/End of search list./ { show=0 } \
    { if (show) printf "-I%s\n",$1 }; \
    /#include <...> search starts here:/ { show=1; }' \
    > compile_flags.txt
```

**Comment by nicolasmartin3d** [comment]
It seems to be working.
Is this a bug ? Is there a way to keep using the compile_commands.json file instead (this is MWE, but the project I'm working on is too complex to use a simple compile_flags.txt file).

**Comment by widgetii** [comment]
`compile_flags.txt` is a simple approach to work with one-file project such yours. Consider use CMake or similar tool to autogenerate proper `compile_flags.txt`. I believe in your case you could move `-I` lines from `compile_flags.txt` to your `compile_flags.txt` and it will work too.

**Comment by nicolasmartin3d** [comment]
But `compile_flags.txt` does not make sense if you have different (maybe incompatible) flags for different files, does it ? That's the point of the `compile_commands.json` I suppose.
In any case, is it considered normal that the system header include paths can not be autodetected by `clangd` ?

**Comment by kadircet** [comment]
clangd detects system headers from the path of the driver. i assume you have a custom build version of clang and clangd in your `/opt/local/bin/` folder, I would suggest also building lib(std)c++ or you can try changing your compile_commands.json to point at system clang, i.e:

```
[
{
 "directory": "/tmp/build",
 "command": "/usr/bin/clang++    -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -o CMakeFiles/test.dir/test.cpp.o -c /tmp/test.cpp",
 "file": "/tmp/test.cpp"
}
]
```

I put /usr/bin/clang++, but basically whatever the `which clang++` outputs(and I hope the ones in /opt are not in your path and gonna mess with this one).

PS: The binary in compile_commands.json is not directly used by clangd, but it is path is used by clang frontend to figure out where some "implicit" resources(including lib(std)c++) are.

**Comment by nicolasmartin3d** [comment]
I have a custom clang/clangd built with macports since clang provided with MacOsX does not provide this tool (clangd). Why does it need to have a libstdc++ built with it since it seems to only need the headers to be available ? 

In any case, I don't understand why `/opt/local/bin/clangd` can not find the system headers when compiling with `/opt/local/bin/clang`, I have no errors ? Is the detection done differently ? 
I don't want to have to manually mess with the include flags in my `compile_commands.json`.

**Comment by thomasjm** [comment]
> clangd detects system headers from the path of the driver.

Is there any way to tell `clangd` about additional system header paths @kadircet ? 

I've been trying to put `-isystem` flags in my `compile_flags.txt`, but it doesn't seem to be working. I'm building environments with Nix so it looks like this:

```
-isystem /nix/store/somehash-glibc-2.27-dev/include
-isystem /nix/store/somehash-libc++-5.0.2/include/c++/v1
```

And yet when I do `#include <stdio.h>`, I get a diagnostic `'stdio.h' file not found`.

**Comment by oxycoder** [comment]
assume brew make shortcut /usr/local/opt/llvm -> /usr/local/Cellar/llvm/8.0.0_1/
You have to add those line to .bash_profile

```
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
```

It's work for me with:

- VS Code 1.36.1
- CMake Tool (vector of bool) : now maintenance by microsoft
- vscode-clangd
- CodeLLDB

**Comment by kadircet** [comment]
> > clangd detects system headers from the path of the driver.
> 
> Is there any way to tell `clangd` about additional system header paths @kadircet ?
> 
> I've been trying to put `-isystem` flags in my `compile_flags.txt`, but it doesn't seem to be working. I'm building environments with Nix so it looks like this:
> 
> ```
> -isystem /nix/store/somehash-glibc-2.27-dev/include
> -isystem /nix/store/somehash-libc++-5.0.2/include/c++/v1
> ```
> 
> And yet when I do `#include <stdio.h>`, I get a diagnostic `'stdio.h' file not found`.

Yes, what you are doing looks legit. Are you sure that compile_flags.txt is in a path that is picked up by clangd?

You can check it by searching for "Updating file .* with command" in clangd logs which should be followed by compile command that's used by clangd.

**Comment by lh123** [comment]
>Yes, what you are doing looks legit.

The format of the `complite_flags.txt` file should be incorrect.
```
-isystem
/nix/store/somehash-glibc-2.27-dev/include
-isystem
/nix/store/somehash-libc++-5.0.2/include/c++/v1
```

**Comment by ianpan870102** [comment]
Have you tried re-installing the header files? Try this, at least this is how I solved my own problem: `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`

**Comment by badfilms** [comment]
The `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` solution is not a long-term solution. Apple has deprecated `/usr/include`. If you upgrade to Catalina, you will no longer have this option.

**Comment by sam-mccall** [comment]
We added a bunch of standard library probing (see the commits in #178) designed to make clangd better emulate system clang on mac (it invokes xcrun to get the relevant settings). We also added more useful logging (with `-log=verbose`) at around the same time.

I'm not familiar with all the setups described in this bug, I'd expect those changes to fix things if you have xcode installed, and not to help if you're relying entirely on nix/brew/etc, but that's a bit of a guess.

Would any of the people having problems here be able to try a recent build - either [llvm 10 RC2](https://prereleases.llvm.org/10.0.0/) or a [clangd snapshot build](https://github.com/clangd/clangd/releases) and see whether the issue is resolved?

**Comment by sam-mccall** [comment]
Great! I'm going to call this fixed then, if people are still seeing this (on Mac, with snapshot builds or 10.0) then let me know and I'll reopen.

**Comment by GianUlli** [comment]
I have an interesting version of this problem. I'm also trying to use clangd in VS Code on macOS Catalina. I installed it today from homebrew (LLVM 10.0), which should contain the latest fixes if I understood this thread correctly. I still had problems with clangd not finding the system header files. My original `compile_commands.json`:

```
[
{
  "directory": "/Users/gian/Desktop/test/build",
  "command": "/usr/bin/clang++    -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -o CMakeFiles/main.dir/main.cpp.o -c /Users/gian/Desktop/test/main.cpp",
  "file": "/Users/gian/Desktop/test/main.cpp"
}
]
```
Notice that `/usr/bin/clang++` is used as compiler because I selected the corresponding "kit" in the [CMake toolbar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools). I tried various things to fix this but no combination of new flags for `clangd` seemed to help.

What finally fixed the problem was changing the kit to `[Unspecified]`, which changes the `compile_commands.json` to

```
[
{
  "directory": "/Users/gian/Desktop/test/build",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -o CMakeFiles/main.dir/main.cpp.o -c /Users/gian/Desktop/test/main.cpp",
  "file": "/Users/gian/Desktop/test/main.cpp"
}
]
```
When CMake itself is selecting the compiler, it chooses `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++` instead of `/usr/bin/clang++`. I don't know what the difference between those two executable is (apart from location). They return exactly the same version:

```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
(they are not symlinked)

My problem is resolved but I thought, I post a comment in case someone else runs into a similar issue.

**Comment by thejohnfreeman** [comment]
I'm having this same problem with clangd-10 on Ubuntu 19.10 Eoan with Neovim + vim-lsp, but I'm not sure if I should ask for help here or in a new issue...

```cpp
#include <cstdio> // 'cstdio' file not found

int main() {
    std::printf("hello, world!\n"); // Use of undeclared identifier 'std'
    return 0;
}
```

```js
// compile_commands.json
{
  "directory": "/home/jfreeman/code/try-asio/build",
  "command": "/usr/bin/clang++    -stdlib=libc++   -o CMakeFiles/clangd.dir/clangd.cpp.o -c /home/jfreeman/code/try-asio/clangd.cpp",
  "file": "/home/jfreeman/code/try-asio/clangd.cpp"
}
```

**Comment by sam-mccall** [comment]
@GianUlli thanks! As I understand it, /usr/bin/clang++ is a wrapper program on max os X that basically runs `xcrun clang++` which locates the real clang binary. We recognize this pattern when we find `clang` on the path ourselves, but not when `/usr/bin/clang++` is explicitly specified. Maybe we need to do that too...

@thejohnfreeman best to open a new bug as the underlying issue discussed in this one is mac-specific (sorry it wasn't labeled yet). We'll need some more information though: does the clang++ command from compile_commands.json actually work on your system, can you provide verbose logs from clangd etc.

**Comment by thejohnfreeman** [comment]
@sam-mccall thank you, I've created a [new issue](https://github.com/clangd/clangd/issues/338).

**Comment by chrstphrchvz** [comment]
@nicolasmartin3d wrote:
> clang provided with MacOsX does not provide this tool (clangd).

I came across this issue from searching, and want to point out that Xcode **does** include clangd, it just isn't on the default PATH. It can be run using `xcrun -r clangd`.
