### ISSUE TITLE
Hover info for types pulled in via a using declaration is less useful than it used to be

### ISSUE THREAD

**Issue by ckandeler** [clangd/clangd#989]
Consider this piece of code:
```
namespace N { struct S {}; }
void f()
{
    using N::S;
    S s;
}
```
Hovering over S in the declaration of s used to say: 
"struct S
// In namespace N
struct S {}
"

But after https://reviews.llvm.org/D114251, it now says:
"using S
// In f
using N::S"

The former information seem to be the more relevant one.

**Comment by tom-anders** [comment]
Should be fixed since https://reviews.llvm.org/D133664

**Comment by HighCommander4** [comment]
Closing per above, thanks for the patch!
