### ISSUE TITLE
Implicit -fdelayed-template-parsing breaks various tests (and features)

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#99]
This is on by default on windows, but reproducible on linux by injecting the flag.

We get no AST for function bodies where the function templates aren't instantiated, so various features (xrefs, SelectionTree etc) don't work.

Unfortunately the flag is compilation-global, and old windows SDKs can't parse without it (thus the default).

Ilya suggested we walk the top-level decls looking for delayed-parse function templates in the main file only, and force parsing of them.

**Comment by kadircet** [comment]
This should've been fixed/improved to the extend that makes most of the features work via https://github.com/llvm/llvm-project/commit/038f03cb5ef5d44676cbde06560ed2668f4a7acc and https://github.com/llvm/llvm-project/commit/6d7637dc460a3602d725eca8698fa0ecd920031b.

This is not perfect though, we might be missing some information from non-instantiated templates in the preamble, but it's unclear how important that is without real world examples. So closing this.
