### ISSUE TITLE
"Unknown argument" as a "syntax" error.

### ISSUE THREAD

**Issue by YellowOnion** [clangd/clangd#993]
I'm using doom emacs, on linux kernel.

I get these 7 lines on every single c related file I have open:
![image](https://user-images.githubusercontent.com/364160/150518535-e2609303-db7a-4d18-8f84-62bbc3b5121d.png)

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:
```
clangd version 13.0.0
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
Doom Emacs, lsp-mode

Operating system:
NixOS

**Comment by kadircet** [comment]
Yes, that's supoptimal but letting users know that the compile flags being used for the file are not compatible with clang is an important signal to keep.

You can suppress those by having a .clangd config file with contents that look like:
```
CompileFlags:
  Remove:
    - -mno-fp-ret-in387
    - ...
```

See [clangd.llvm.org/config](https://clangd.llvm.org/config#remove) for details.

**Comment by YellowOnion** [comment]
@kadircet why are they errors? can't you display them as warnings / info? are these flags likely to actually cause issues if LSP just ignores them?

Like who cares if LSP is ignoring `-fconserve-stack`, it's just a performance flag, it's not going to help me debug my code right?
