### ISSUE TITLE
Suppress warnings about included files not found

### ISSUE THREAD

**Issue by fcying** [clangd/clangd#995]
I work in a code workspace where I do not have all files.
When editing a file, I see several a warning about included files not found which owned by another team. 
I test Suppress: '*' but not work, only Suppress other warning.
Can supress add support for this warning?

**Comment by vogelsgesang** [comment]
I actually sometimes face the same problem:
In my code base, some of our headers are generated by the build system only at build time.
So, I have to run a full build before being able to use `clangd`.
Would be nice if `clangd` could handle the case where some headers are missing more nicely

**Comment by HighCommander4** [comment]
I just tried this locally, and `Suppress: '*'` does disable diagnostics about included files not being found as well.

To investigate this further, could you please share your clangd version, and a minimal project (including the config file) which demonstrates the issue?

**Comment by fcying** [comment]
@HighCommander4

**Comment by fcying** [comment]
@HighCommander4 
clangd --version
```
clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

`.clangd`
```
Diagnostics:
  Suppress: ['*']
```

test file: main.c, have two warning. if I add `Suppress: ['*']`, it only have `'t.h' file not found`
```
#include "t.h"              //'t.h' file not found

int main(void)
{
    int a = 3.3;       //Implicit conversion from 'double' to 'int' changes value from 3.3 to 3
    return 0;
}
```

test in debian 11, neovim 0.6.1, neovim mini init.lua
```
local fn, cmd = vim.fn, vim.cmd
local root_dir = fn.fnamemodify(fn.resolve(fn.expand('<sfile>:p')), ':h')

cmd('set packpath=' .. root_dir .. '/plugged')
cmd('set runtimepath^=' .. root_dir .. '/plugged')
local install_path = root_dir .. '/plugged/pack/packer/opt/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    Bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

cmd([[
    set mouse=n
    packadd packer.nvim
    nnoremap <space>pu :PackerSync<CR>
    nnoremap <space>pc :PackerCompile<CR>
]])

local packer = require('packer')
local use = packer.use
packer.init({
    package_root = root_dir .. '/plugged/pack',
    compile_path  = root_dir .. '/plugged/plugin/packer_compiled.lua',
})

use {'wbthomason/packer.nvim', opt = true}
use 'neovim/nvim-lspconfig'

if Bootstrap then
    packer.sync()
end

local nvim_lsp = require('lspconfig')
nvim_lsp['clangd'].setup {}
```

Reproduce:
```
nvim -u init.lua main.c
get two warning

use Suppress: '*'
nvim -u init.lua main.c
only file not found warning
```

**Comment by HighCommander4** [comment]
Thanks. I realize now that this is due to #906, a bug that I fixed a few months ago. Its fix will appear in clangd 14, and it's also present in the [weekly snapshot releases](https://github.com/clangd/clangd/releases).

**Comment by fcying** [comment]
tks, I test weekly snapshot releases, it can suppress `file not found` with `pp_file_not_found`
